### ISSUE TITLE
SAM should fall back to copy if mounting a directory fails

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-sam-cli#1005]
### Describe your idea/feature/enhancement

I wish SAM CLI would fall back to deep copy everywhere (build. invoke (zip and debugger-path) if docker mounting fails

**Comment by qingchm** [comment]
@abrooksv Hey can I please get some more context on why you want sam to auto switch mode if the containerized actions fail? How I'm understanding your ask is that if the container mounting fails, would would like the build, for example still succeed without the use of containers. What scenarios would make this a better approach than re-running the build command without specifying the --use-container flag? My concern with switching is, currently containerized actions and normal actions can output different build folder structures (for example the dependencies will be built incrementally for non-container cached builds but not yet for containerized ones). With this being a concern I would not suggest any sort of auto-switching, thanks for understanding! Let me know if I'm misunderstanding the context here or if you have some strong reasons for this feature (maybe automation related?)

**Comment by jfuss** [comment]
Closing due inactivity. Please create a new issue if you would still like this feature.
