### ISSUE TITLE
ALB support from SAM 

### ISSUE THREAD

**Issue by nikhilbhoj** [aws/aws-sam-cli#1008]
### Describe your idea/feature/enhancement

Provide a clear description. Ex. I wish SAM CLI would [...]

I would be see the option of testing and deploying Lambda functions for ALB ( Application load balancer )

### Proposal

Add details of how to add this to the product.

Right now API gateway is support for local testing and deployment using sam local start-api.

Similarly there should be sam local start-load-balancer command and the events to test it.

In the SAM Template need to have 
Events:
       ALB:
          Type: ALB
 which is as above are only for API Gateway enabled and not for  ALB.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

### Additional Details

Further the Cloud formation currently does not support Target group to be exposed as Lambada target

as the protocol and port are required in the current cloudformation template for ALB are mandatory but for exposing Lambda as ALB target it is not.

**Comment by jfuss** [comment]
This relates to the SAM Spec supporting this. The issue tracking that is [here](https://github.com/awslabs/serverless-application-model/issues/721)

**Comment by patchu** [comment]
Any progress on this? It would be useful for local testing of Lambda functions placed behind ALBs.

**Comment by awerlang** [comment]
At this time ```sam local start-api``` supports emulating lambdas for ALB but ALB behaves differently in a couple aspects:

- Doesn't automatically url-decodes query string parameters;
- Fails when Boolean ```true``` exist as a response header value

**Comment by patchu** [comment]
When I run ```sam local start-api``` in the directory, I get back the message: ```Error: Template does not have any APIs connected to Lambda functions``` . Which is true. I have it set up as an ALB target, not as an API. I wouldn't want to add an API just to get it running with SAM.

My Lambda functions return HTML which is then consumed by the browsers hitting the ALB endpoint. What I did was write a local proxy to go between the browser and ```sam local start-lambda```, and I'm able to do my local testing that way.

**Comment by Novik71** [comment]
> At this time `sam local start-api` supports emulating lambdas for ALB 

Would you be able to elaborate on exactly how you have achieved this?

**Comment by archwebio** [comment]
Hello, any information on the status of this issue?
I have great interest on it.
Thanks,

**Comment by samlamgithub** [comment]
Hi, is there any progress on this? Would to very useful to have this support, thanks

**Comment by jfuss** [comment]
Thank you for the interest. We are still exploring a Plugin based solution for local development to allow the community to enable/extend features like this. Give that, we are closing this in favor of the Plugins tracking issue: https://github.com/aws/aws-sam-cli/issues/3265
