### ISSUE TITLE
ork/exec /opt/bootstrap: permission denied when using Layers

### ISSUE THREAD

**Issue by ashish-dirkmedia-de** [aws/aws-sam-cli#1014]
I am using Bref for building serverless PHP applications using layers.
All works with layers when deployed using sam. But on local I get 

Error: fork/exec /opt/bootstrap: permission denied

Work env. 
aws --version
aws-cli/1.16.103 Python/3.6.0 Windows/10 botocore/1.12.93

sam --version
SAM CLI, version 0.11.0

Docker desktop Version 2.0.0.2

I debugged on it seems SAM have issue with custom layers
Can you please help.

The template I use
template.yaml
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ''

Globals:
Function:
Environment:
Variables:
# Laravel environment variables
APP_STORAGE: '/tmp'

Resources:
MyFunction:
Type: AWS::Serverless::Function
Properties:
FunctionName: 'my-function'
Description: ''
CodeUri: .
Handler: index.php
Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
Runtime: provided
Layers:
- 'arn:aws:lambda:eu-west-1:209497400698:layer:php-72-fpm:1'
Events:
# The function will match all HTTP URLs
HttpRoot:
Type: Api
Properties:
Path: /
Method: ANY
HttpSubPaths:
Type: Api
Properties:
Path: /{proxy+}
Method: ANY
```
All works on Prod correctly when deployed only local showing this error

**Comment by TheSriram** [comment]
Have seen this issue crop up on a bad installation of docker, have you tried it on another windows computer to see if this is repeatable?

**Comment by jsamouh** [comment]
Same for me

**Comment by slootjes** [comment]
Same here with these versions:

- Docker Desktop 2.0.0.3 (31259)
- aws-cli/1.16.117 Python/3.6.5 Windows/10 botocore/1.12.107
- SAM CLI, version 0.12.0

**Comment by matlar83** [comment]
Same error

**Comment by Lohn** [comment]
Same here:
Docker Desktop 2.0.2.0 (31088) 
Docker version 18.09.1, build 4c52b90
aws-cli/1.16.169 Python/2.7.16 Windows/10 botocore/1.12.160
SAM CLI, version 0.16.1

**Comment by sriram-mv** [comment]
Have you tried setting permissions on the codeuri and layer folders as well, and re-tried it?
