### ISSUE TITLE
Cannot connect to MediaConvert Endpoint

### ISSUE THREAD

**Issue by maxhayward** [aws/aws-sam-cli#1028]
### Description

Running the simple Python function below via aws-sam-cli produces an error. Running the same function via Lambda (direct in AWS) works, as does running the code directly in a Python script on the same Workspace.

I have tested across all available Python runtimes.

### Steps to reproduce

Run the following code:

```
# Get media convert client   
mc_client = boto3.client(
    'mediaconvert',
    aws_access_key_id=<aws_access_key>,
    aws_secret_access_key=<aws_secret_key>,
    region_name=<region>
)

# Get the endpoint 
mc_endpoint = mc_client.describe_endpoints()
print(mc_endpoint)
```

### Observed result

`{
  "errorType": "EndpointConnectionError",
  "errorMessage": "Could not connect to the endpoint URL: \"https://mediaconvert.eu-west-1.amazonaws.com/2017-08-29/endpoints\"",
  "stackTrace": [
    "  File \"/var/task/MediaConvert.py\", line 24, in handler\n    mc_endpoints = mc_client.describe_endpoints()\n",
    "  File \"/var/runtime/botocore/client.py\", line 320, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
    "  File \"/var/runtime/botocore/client.py\", line 610, in _make_api_call\n    operation_model, request_dict)\n",
    "  File \"/var/runtime/botocore/endpoint.py\", line 102, in make_request\n    return self._send_request(request_dict, operation_model)\n",
    "  File \"/var/runtime/botocore/endpoint.py\", line 136, in _send_request\n    success_response, exception):\n",
    "  File \"/var/runtime/botocore/endpoint.py\", line 210, in _needs_retry\n    caught_exception=caught_exception, request_dict=request_dict)\n",
    "  File \"/var/runtime/botocore/hooks.py\", line 356, in emit\n    return self._emitter.emit(aliased_event_name, **kwargs)\n",
    "  File \"/var/runtime/botocore/hooks.py\", line 228, in emit\n    return self._emit(event_name, kwargs)\n",
    "  File \"/var/runtime/botocore/hooks.py\", line 211, in _emit\n    response = handler(**kwargs)\n",
    "  File \"/var/runtime/botocore/retryhandler.py\", line 183, in __call__\n    if self._checker(attempts, response, caught_exception):\n",
    "  File \"/var/runtime/botocore/retryhandler.py\", line 251, in __call__\n    caught_exception)\n",
    "  File \"/var/runtime/botocore/retryhandler.py\", line 277, in _should_retry\n    return self._checker(attempt_number, response, caught_exception)\n",
    "  File \"/var/runtime/botocore/retryhandler.py\", line 317, in __call__\n    caught_exception)\n",
    "  File \"/var/runtime/botocore/retryhandler.py\", line 223, in __call__\n    attempt_number, caught_exception)\n",
    "  File \"/var/runtime/botocore/retryhandler.py\", line 359, in _check_caught_exception\n    raise caught_exception\n",
    "  File \"/var/runtime/botocore/endpoint.py\", line 179, in _get_response\n    http_response = self._send(request)\n",
    "  File \"/var/runtime/botocore/endpoint.py\", line 223, in _send\n    return self.http_session.send(request)\n",
    "  File \"/var/runtime/botocore/httpsession.py\", line 278, in send\n    raise EndpointConnectionError(endpoint_url=request.url, error=e)\n"
  ]
}
`

### Expected result

A JSON string containing the appropriate endpoint.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Amazon Linux (via Amazon Workspaces)
2. `sam --version`: SAM CLI, version 0.11.0

**Comment by jfuss** [comment]
@maxhayward What is the command you are running? Are you passing `--profile` to the command or have your credentials setup as the `default` profile through `aws configure`?

**Comment by maxhayward** [comment]
The command is `sam local invoke -e event.json` - I am not passing in a profile to the sam command, wasn't aware that was required as  the mediaconvert client is using AKSK on instantiation.

**Comment by jfuss** [comment]
But you are configuring a Boto3 client, so you would need aws creds right? SAM CLI will use the `default` profile or the one passed in through `--profile`.

**Comment by maxhayward** [comment]
The creds are being passed direct to the client. `<aws_access_key>` and `<aws_secret_key>` are redacted.

I've tried passing `--profile` into the sam command, but with no luck.

**Comment by jfuss** [comment]
Does the credentials you are using have the correct permission scope? This is outside of SAM CLI's scope.

**Comment by maxhayward** [comment]
Yes the credentials have the correct permissions, I tested the same function code in a Python script outside of aws-sam-cli and it works.
