### ISSUE TITLE
Integration with localstack

### ISSUE THREAD

**Issue by bikerp** [aws/aws-sam-cli#1066]
Hi,
it would be great if sam local would integrate with [localstack](https://github.com/localstack/localstack). I know I can provide endpoint in the code e.g. 
`
const SNS = new AWS.SNS({
    endpoint: new AWS.Endpoint('http://localhost:4575'),
});
`
But I would prefer not to pollute the code.

Thanks

**Comment by jfuss** [comment]
@bikerp Thanks for the issue. Can you describe more what you mean or are looking for?

For you to integrate with LocalStack, you would need to override the endpoint for each of the services you use. SAM CLI doesn't control your function code or what it connects too, so I believe what you want is already supported by overriding the Endpoint and running LocalStack on your machine.

**Comment by bikerp** [comment]
I could imagine a CLI parameter e.g. --sns-endpoint-url http://..... or something like that

**Comment by jfuss** [comment]
@bikerp You would still need to configure the SDKs within your Lambda Function. So at the end, you will still need to do something like you have above. Maybe I am missing something but my recommendation is to configure the SNS or other AWS service conditionally (only set the `AWS.Endpoint` when running within SAM CLI).

**Comment by bikerp** [comment]
@jfuss If the configuration of endpoint in SDK is a must then my request is pointless. I thought that SDK will construct the endpoint from some specific environment variables.

**Comment by jfuss** [comment]
@bikerp I am not aware of this capability. I did a look through [Boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html) (the sdk I am most familiar with) and didn't see any configuration that would allow this. If you find it, please share but at the moment the only way I know of is it override it when you create the client. I can see this being a pretty useful feature (limits code configuration for local vs cloud). 

I will leave this open for a little while to see if this is already available and I am just missing the configuration before closing.

**Comment by LazerFX** [comment]
For the .NET SDK, you can set a global configuration value that allows you to override the endpoints.  If you were referencing localstack, then this file could be generated such that it points to the local environment...

[Overriding Endpoints in the .NET SDK](https://aws.amazon.com/blogs/developer/overriding-endpoints-in-the-aws-sdk-for-net/)

I don't know if this is also supported in other environments and SDK editions, but it's been in since part-way through version 2 of the .NET SDK.

```xml
<appSettings>
   ...
   <add key="AWSEndpointDefinition" value="c:pathtoendpoints.xml"
   ...
</appSettings>
```
