### ISSUE TITLE
Debug dotnetcore 2.1 in Visual Studio 2017/2019

### ISSUE THREAD

**Issue by MuazOthman** [aws/aws-sam-cli#1120]
### Describe your idea/feature/enhancement

We're currently migrating from a monolith ASP.NET Core app to a serverless architecture and SAM proved to be a valuable asset. However, the team is much more comfortable with VS (currently 2017 and we're moving to 2019) and not that much with VSCode.

Now that SAM supports debugging dotnetcore functions using VSCode (#568), we're wondering if this can ever translate to the full Visual Studio 2017/2019?

**Comment by ssenchenko** [comment]
Integration with IDEs is provided by [AWS Toolkit](https://github.com/aws/aws-toolkit-visual-studio).
You can file a feature request to improve VS support there.
