### ISSUE TITLE
Add event switch to sam build

### ISSUE THREAD

**Issue by ms-clovis** [aws/aws-sam-cli#1159]
I wish sam build had an event (switch/flag)(ie. -e) that could point at the event file and simply move and rename the event file to the build directory.

sam build .... -e or --event foo.json would be moved to the build directory and renamed event.json for the invoke command.

**Comment by jfuss** [comment]
@ms-clovis Can you describe what value this provides? Build is meant to compile/produce artifacts ready to be package/deployed/invoked. What would be the need to have the `even.json` file with the artifacts instead of in your project's source?

**Comment by ms-clovis** [comment]
In the same way sam build -t moves and renames the template, then the user would have the template and event json in the build folder for running a local test. I hope that makes sense to you.

**Comment by morefaey** [comment]
@ms-clovis if you still have this issue, please reopen. it should not be relevant to the current version of sam cli
