### ISSUE TITLE
Validate or test that a lambda returns expected API Gateway response

### ISSUE THREAD

**Issue by Rubiedo** [aws/aws-sam-cli#1172]
### Describe your idea/feature/enhancement

It'd be nice if there were a way to validate or test whether a lambda is returning a proper response to API Gateway and provide insight into response errors. 

Sometimes I may have additional headers, or I may be a new user. The documentation provides a simple example, but it doesn't provide detail for intermediate or advanced use cases. 

### Proposal

Add a command to validate/test whether or not a lambda is returning a proper response. This may involve invoking the function itself and testing the response from lambda.

**Comment by awood45** [comment]
Can you explain in more detail what you mean by a "proper response" in this case?

**Comment by mingkun2020** [comment]
@Rubiedo Closing this issue since inactive for a long time. If you encounter this issue anymore, feel free to reopen it.
