### ISSUE TITLE
Add debug messages for docker mounts

### ISSUE THREAD

**Issue by maxheyer** [aws/aws-sam-cli#1191]
### Description

To debug mount problems within docker it would be great to have some debug messages about what is being mounted into the lambci container.

### Additional Details
**I try to debug the error below (What means there is no file named index.js):**
 Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)

**Comment by maxheyer** [comment]
To debug the issue discussed in slack it would be great to see what files are being mounted into the lambci container. With the current output it's not possible to ensure if the contents of the directory are being mounted correctly.

**Comment by TheSriram** [comment]
If they are not getting mounted correctly, it could very well be a docker permissions issue. Have you tried sharing the appropriate directory?

**Comment by maxheyer** [comment]
The issue with my mounts are the same as reported in https://github.com/awslabs/aws-sam-cli/issues/181. I just opened this issue to give more debug messages to people who will have the same issue in the future. @TheSriram

**Comment by jfuss** [comment]
Closing this due to age. As stated above, we do say what directory we are mounting. I recall docker not giving us anyway to know if the mount was successful, so we mount and assume docker handles things correctly. If this is still something you would like us to do, feel free to create a new issue (closed issues are hard to track).
