### ISSUE TITLE
Support for building nested stacks with SAM resources

### ISSUE THREAD

**Issue by kgeisink** [aws/aws-sam-cli#1213]
### Describe your idea/feature/enhancement

I would like for it to be possible to deploy a CloudFormation template which contains SAM resources and a nested stack which template in turn also contains SAM resources, without having to update the TemplateURL property of the nested stack in a separate, custom step.

Currently, when both the parent stack and nested stack contain SAM resources, they have to be built separately. This means that the TemplateURL property that refers to the nested stack's template is going to be wrong, not pointing to the template prepared by `sam build`. It would be great if this relation is kept during the build step, so packaging will still work as normal.

### Proposal

(I don't know enough details about SAM CLI to know how realistic any proposal that I have is.)

* Add a parameter to the `build` command that allows you to list your nested templates.
* Somehow find the TemplateURL of any AWS::CloudFormation::Stack resource in a template and verify whether it contains SAM resources.

### Additional Details

* In issue #936 it was mentioned that nested templates are not yet supported in any SAM CLI commands and that it needed a general issue.
* Putting the nested stack into SAR can work for some of the solutions out there, but not all resource types are supported by SAR so this can still be a problem.

**Comment by michaelgwgutierrez** [comment]
I too would like to see this feature. Currently as a workaround you can run "sam build" on all the nested SAM projects and then build/package/deploy from the parent SAM. A recursive SAM build could be added to projects using nested SAM applications.

**Comment by trek10-k37z** [comment]
+1

**Comment by jeswanthamazon** [comment]
+1 for this feature

**Comment by netochaves** [comment]
+1 for this

**Comment by BeneyKim** [comment]
+1 for this

**Comment by made2591-eb** [comment]
I was encountering this problem even before moving to nested stack. What's wrong with `sam build`?

**Comment by trek10-k37z** [comment]
+1

**Comment by edreanernst** [comment]
+1

**Comment by codergeorgej** [comment]
+1

**Comment by ronaldour** [comment]
> I too would like to see this feature. Currently as a workaround you can run "sam build" on all the nested SAM projects and then build/package/deploy from the parent SAM. A recursive SAM build could be added to projects using nested SAM applications.

This is not feasible as the parent template would need to point to the generated yaml template in the _.aws-sam_ directory to use the built packages. See #2061 
Does anyone has another workaround for this?

I would love to see the `sam build` to work recursively as `sam package does` please share updates or suggestions.

**Comment by aahung** [comment]
It is implemented in #2662, to be released

**Comment by aahung** [comment]
released in v1.20.0

**Comment by aahung** [comment]
let us know if you encounter any issues with nested stacks!

**Comment by milesgranger** [comment]
Looking forward to giving it a go very soon, thanks so much! :100:
