### ISSUE TITLE
"sam local start-api" treats lambda response as invalid when Content-Type header is null

### ISSUE THREAD

**Issue by GREsau** [aws/aws-sam-cli#1218]
### Description

If a lambda function does not set the Content-Type response header, then the API Gateway will default it to application/json. To prevent this, the lambda can explicitly set the Content-Type to null - for example, the Amazon.Lambda.AspNetCoreServer .NET nuget package does this ([relevant code here](https://github.com/aws/aws-lambda-dotnet/blob/1a76fa07ce520a5cfc910adb42df81fa19a1ff32/Libraries/src/Amazon.Lambda.AspNetCoreServer/APIGatewayProxyFunction.cs#L268)) This works fine when the function is deployed to AWS, but breaks when run locally using `sam local start-api`.

### Steps to reproduce

Create a new SAM API gateway project and make the function set the Content-Type response header to `null`.
e.g. using `sam init --runtime dotnetcore2.1` and changing the FunctionHandler to:
```c#
public APIGatewayProxyResponse FunctionHandler(APIGatewayProxyRequest apigProxyEvent, ILambdaContext context)
{
    return new APIGatewayProxyResponse
    {
        StatusCode = 204,
        Headers = new Dictionary<string, string> { { "Content-Type", null } }
    };
}
```
Then build the project with `sam build` and run it locally using `sam local start-api`.

### Observed result

Sending an HTTP GET request to the function returns a 502 HTTP error. The SAM CLI logs:
> REPORT RequestId f0936733-e011-4a2a-8154-cbba483985bb   Duration: 399 ms        Billed Duration: 400 ms Memory Size 128 MB      Max Memory Used: 40 MB
> 2019-06-08 22:37:24 Function returned an invalid response (must include one of: body, headers, multiValueHeaders or statusCode in the response object). Response received: {"statusCode":204,"headers":{"Content-Type":null},"multiValueHeaders":null,"body":null,"isBase64Encoded":false}
> 2019-06-08 22:37:24 127.0.0.1 - - [08/Jun/2019 22:37:24] "GET /hello HTTP/1.1" 502 -

### Expected result

Sending an HTTP GET request to the function returns a 204 No Content result, and no Content-Type header is included in the response. This is the behaviour when the project is actually deployed to the AWS.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: SAM CLI, version 0.17.0

**Comment by GREsau** [comment]
This seems to be caused by the call to `best_match()` in _should_base64_decode_body [here](https://github.com/awslabs/aws-sam-cli/blob/5171db2a15405427df470b49a1609edc71efc9bf/samcli/local/apigw/local_apigw_service.py#L277) raising a TypeError when `None` is in the list it's given. 

A similar problem occurs when the Content-Type is set to an invalid mimetype e.g. "foo". In this case, `best_match()` raises a ValueError, which will also result in the local api gateway service returning a 502.

**Comment by awood45** [comment]
I was able to reproduce this in the Node runtime as well with aws-sam-cli 0.19.0

**Comment by jfuss** [comment]
I just tried this with python and no longer get an error. 

```
return {
        "statusCode": 200,
        "headers": {"Content-Type": None},
        "body": json.dumps({
            "message": "hello world",
            # "location": ip.text.replace("\n", "")
        }),
    }
```

Closing this assuming this has been corrected (this was last validated on a very old SAM CLI version). If this is still happening, please create a new issue.
