### ISSUE TITLE
Allow specifying docker container in which to build code

### ISSUE THREAD

**Issue by mcouthon** [aws/aws-sam-cli#1231]
### Describe your idea/feature/enhancement

Sometimes with Python code one requires compiling packages that rely on C libraries. For example, trying to install `mysqlclient` in the default container will result in an error.

A way to overcome this issue, is to create a new Docker image, based on the `lambci/lambda:build-python2.7` one, that will have `mysql-devel` and `python-devel` installed in it, and use _it_ when running `sam build -u`.

### Proposal

An obvious solution is just to provide an optional flag, e.g.

```bash
sam build --use-container --docker-image lambci/lambda:my-awesome-image
```

### Additional Details

I don't know enough about the SAM CLI infra to say, but if possible, it would be even better if one could provide a `Dockerfile` in the template.

**Comment by lbalceda** [comment]
Im new to SAM as well but I think that's the `-u /  --use-container` flag . check https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html

**Comment by khamaileon** [comment]
+1 for Dockerfile support.
```
FROM lambci/lambda:build-python3.6

# Install your dependencies
RUN yum -y install mysql-devel
```

**Comment by subzero112233** [comment]
would be great if supported

**Comment by prcongithub** [comment]
Isn't there any other workaround till then?

**Comment by jfuss** [comment]
@prcongithub You could build the image locally, retag it as the image we download, and then pass `--skip-pull-image`.

**Comment by solarmosaic-kflorence** [comment]
Being able to configure a `Dockerfile` would be great.

**Comment by ramonmedeiros** [comment]
I follow @jfuss solution and was really good:

```
docker pull MY_IMAGE
docker tag MY_IMAGE amazon/aws-sam-cli-build-image-python3.8
sam build --use-container --skip-pull-image .....
```

**Comment by khamaileon** [comment]
Now that we can use a Docker image as a lambda deployment package, we should close this issue.

**Comment by polothy** [comment]
> Now that we can use a Docker image as a lambda deployment package

Is there a doc on how to do this?

**Comment by khamaileon** [comment]
https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/

**Comment by polothy** [comment]
That sort of feels like a long workaround, converting all of your lambdas from basic zip packages to Docker images vs being able to specify the Docker image to use to bundle your lambda.  I'd still do a +1 for this issue.

**Comment by solarmosaic-kflorence** [comment]
hm, that looks neat, but how would you use that in conjunction with SAM? it seems like SAM should just support building from a DockerFile at that point, similar to how you can use MAKE files.

**Comment by zoellner** [comment]
This seems to be a breaking change from sam-cli v0.x to v1.x
Previously `lambci/lambda` containers were used which provided `yum` to install additional packages. With the new `amazon/aws-sam-cli-build-image-*` containers that's not possible anymore

**Comment by simlu** [comment]
@zoellner did you ever find a workaround for this? We are currently in the process of switching from lambci to the new sam build images and not having access to `yum` is a bit of a problem...

**Comment by zoellner** [comment]
@simlu no, I'm still building things with the old containers

**Comment by simlu** [comment]
Kk, thanks for the reply. We'll probably be using lambci node 14 when/if that gets released

**Comment by jfuss** [comment]
This is now supported in v1.22.0. You can use the `--build-image` option. Docs can be found [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html) or `sam build --help`. 

Closing
