### ISSUE TITLE
`sam build` builds the same CodeUri multiple times

### ISSUE THREAD

**Issue by benkehoe** [aws/aws-sam-cli#1236]
### Describe your idea/feature/enhancement

`sam build` treats each function separately, even if they share the same CodeUri. This leads to unnecessarily longer build times.

### Proposal

People may rely on the structure of `.aws-sam`, so maybe stick with a directory per function, but if a function uses the same CodeUri as a function that we've already built in this build, just copy the build directory rather than run a new build.

**Comment by TheSriram** [comment]
https://github.com/awslabs/aws-sam-cli/pull/1180 is a step in that direction.

**Comment by Arekusei** [comment]
any news?

**Comment by sriram-mv** [comment]
https://github.com/aws/aws-sam-cli/issues/1236 makes sure that if functions reference the same exact codeuri, they are built only once.

**Comment by benkehoe** [comment]
@sriram-mv were you intending to reference a PR or comment on a different issue? This issue is #1236

**Comment by sriram-mv** [comment]
Oops you are right. https://github.com/aws/aws-sam-cli/pull/2232 this is the PR I wanted to reference.

**Comment by benkehoe** [comment]
Awesome! Loving that the companion to "Hello World" in the tests is "Hello Mars"

**Comment by forgivegod** [comment]
looks like 1.6.0 addresses this:
https://github.com/aws/aws-sam-cli/releases/tag/v1.6.0

**Comment by awood45** [comment]
Resolved in `1.6.2`
