### ISSUE TITLE
Need --public  flag to make applications visible publicly in sam publish command

### ISSUE THREAD

**Issue by himanshu219** [aws/aws-sam-cli#1276]
Currently when one publishes sam applications using sam publish command then one has to go to the console and toggle the make public switch to make them visible to others.

### Proposal

sam publish --template <packaged_template_path> --region  <AWS_REGION> --public 
by default if public is not specified then it should be private

**Comment by mingkun2020** [comment]
Thanks for the feature request! We have a [roadmap](https://github.com/aws/aws-sam-cli/wiki/SAM-CLI-Roadmap) here, but we also try to take in popular feature requests based on 👍🏽 from the community. We will be adding this to our intake for prioritization.

**Comment by jfuss** [comment]
Closing due inactivity. Please create a new issue if you would still like this feature.
