### ISSUE TITLE
support webpack

### ISSUE THREAD

**Issue by azarboon** [aws/aws-sam-cli#1277]
I would like the SAM CLI be able to support Webpack out of box. We need linters and code formatters, so Webpack is must for us.

**Comment by trivikr** [comment]
Any update on this request?
The closest solution I could find was https://github.com/SnappyTutorials/aws-sam-webpack-plugin

**Comment by super132** [comment]
We have already released the support of [esBuild](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjmq-3ru4H7AhWMAjQIHSDnAoYQFnoECCEQAQ&url=https%3A%2F%2Fdocs.aws.amazon.com%2Fserverless-application-model%2Flatest%2Fdeveloperguide%2Fserverless-sam-cli-using-build-typescript.html&usg=AOvVaw3bN_Wr6KCJavqfw3kIQzrx). Please give it a try to see if it helps on your problem. Thanks.

**Comment by mildaniel** [comment]
Since we now have native support for a different bundler (esbuild) as mentioned by @super132, and we haven't had much recent traction on this issue I will resolve. Please re-open if you still feel as though Webpack support is an important feature for you.
