### ISSUE TITLE
New resource type: AWS::Serverless::StateMachine

### ISSUE THREAD

**Issue by alexcasalboni** [aws/aws-sam-cli#1281]
### Describe your idea/feature/enhancement

I wish SAM CLI would be able to package AWS Step Function definitions when you run `sam package`. At the moment, you can only inline the JSON definition as a string and it's a pain because you don't get any validation/linting.

I've also created a corresponding issue here: https://github.com/aws/aws-cli/issues/4335

### Proposal

We could define a new resource type `AWS::Serverless::StateMachine` and take care of this transformation here. Alternatively, we could add this functionality in the AWS CLI (but that would require modifying the CloudFormation doc as well).

Ping @heitorlessa

**Comment by awood45** [comment]
This does sound useful, and I'm going to move this to the AWS SAM repo.

**Comment by jfuss** [comment]
This was released with version [v0.52](https://github.com/aws/aws-sam-cli/releases/tag/v0.52.0).

Closing
