### ISSUE TITLE
Less verbose logging

### ISSUE THREAD

**Issue by zafarella** [aws/aws-sam-cli#1291]
### Less verbose logging of the progress - reducing noise
the sam cli should have an option to be less verbose or just be less verbose but provide a flag to be more verbose.

### Proposal

For instance, `sam package` command print progress like:
```
Uploading to 6c10f7319c36f4474bddc098cc2ea299  262144 / 30227673.0  (0.87%)
Uploading to 6c10f7319c36f4474bddc098cc2ea299  524288 / 30227673.0  (1.73%)
Uploading to 6c10f7319c36f4474bddc098cc2ea299  786432 / 30227673.0  (2.60%)
...
...
```
which is not really necessary in the CI environment.

**Comment by awood45** [comment]
Noted as a feature request - also happy to take a PR for this if anyone wants to take this on as a first issue.

**Comment by qingchm** [comment]
Implemented and released
