### ISSUE TITLE
API Gateway is not accepting the Lambda JSON response

### ISSUE THREAD

**Issue by dejan92** [aws/aws-sam-cli#1398]
### Description

I'm using `sam local start-api` process to test my SAM template application consisting of API Gateway and Lambda function. When I invoke just the lambda function with `sam local invoke -e event.json myLambdaName` it returns the expected response, but when i use `sam local start-api` it throws the Invalid response key error, where it's not recognizing the response from the lambda. So the error message is the following : 
`Invalid API Gateway Response Keys: {'error'} in {'statusCode': 200, 'body': {'myExpectedContentHere'}, 'headers': {'Access-Control-Allow-Origin': '*'}, 'error': None}`

#### Environment details 

1. OS: Windows10 Pro
2. `sam --version 0.21.0`:

I also tried it with 0.19.0 and 0.15.0

**Comment by awood45** [comment]
I don't believe that `error` is a valid response key to API Gateway. What are you using that key for in your response?

**Comment by dejan92** [comment]
@awood45 I'm not sure I understood your question .. I don't use the key. When I invoke the function I get this response `{"statusCode":200,"body":{"permmissions":[],"roles":[],"_id":"5d6f77609e068455e030f709","email":"some@mail.com","username":"some@mail.com"},"headers":{"Access-Control-Allow-Origin":"*"},"error":null}` which is indeed a valid JSON response, right ? So I can't figure out why when I use the local start-api and do the call to API Gateway I'm getting the error from the previous comment ? The problem should be somewhere in the Gateway, because the Lambda is tested isolated and it's working properly

**Comment by CoshUS** [comment]
API Gateway only accepts statusCode, body, headers, and isBase64Encoded in a response shape.
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.v2.
