### ISSUE TITLE
Local api socket:54321 permission denied

### ISSUE THREAD

**Issue by taigi100** [aws/aws-sam-cli#1423]
### Description

Was working on a project and all was going well. Until today when suddenly I started getting the following error:
`listen tcp 127.0.0.1:54321: socket: permission denied`
which occurs during the `sam start local-api` in the GO process. What I mean by this is that the process seems to start, but gets stuck and yields this error at `lambda.start(handler)`.

All the development was done in a VM, so the actual "changes" since last tested were installing snapd and nodejs. I also checked the logs and there doesn't seem to be any other app using the port. 

P.S.
 - Tried running `sam start local-api` as sudo.
 - used `chmod 777` on the handler

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Deepin
2. `sam --version`: 0.22.0

**Comment by TheSriram** [comment]
Is this just that port? Does using other ports work as expected? Does installing the previous version of sam cli negate the current problem with port `54321`

**Comment by taigi100** [comment]
I tried switching the port to 8080 or 4200, same result (with a different port error).
I tried uninstalling / installing the 0.22.0 version - same result
I'm installing using homebrew and I can't seem to find an earlier version of the cli. Thing is, it worked with this version for a while and suddenly stopped working. Other than installing node, angular cli, and generating an angular project I didn't do anything. Seems a bit weird to suddenly lose permissions :-?

**Comment by jfuss** [comment]
@taigi100 Is this still happening? `start-api` does not use the port by default so something else, either docker or your code, is getting hung up on port `54321`.

> which occurs during the sam start local-api in the GO process.

What go process? Docker or your function code?

**Comment by diegotony** [comment]
I have the same issue, is there any solution ?

**Comment by morefaey** [comment]
@diegotony do you still face this issue? if yes, please reopen
