### ISSUE TITLE
Does sam support sym linked node_modules?

### ISSUE THREAD

**Issue by ktersius** [aws/aws-sam-cli#1446]
In order to speed up our build process we switched to symlinking the /dist/node_modules folder to our ./node_modules  folder instead of copying it over on builds.

Unfortunately this seems to break sam local start-api as on the very first require it cannot find the module. 

Is there some way to get this to work or just not supported?

**Comment by TheSriram** [comment]
For symlinks to work inside containers, I believe they need to be absolute paths, and both directories need to be mounted within the container. Need to dig deeper on this particular issue.

**Comment by sriram-mv** [comment]
Going to close this issue in favor of esbuild solutions for faster builds along with cached and parallel builds. Please re-open this issue if it's still something that we need to target.
