### ISSUE TITLE
Allow to mount additional volumes when invoking lambda in debugger mode

### ISSUE THREAD

**Issue by sdubov** [aws/aws-sam-cli#1485]
### Describe your idea/feature/enhancement
We use a custom debugger when running .net lambda under debug mode. This debugger process produce some logs. I would like to have an option to get those logs for investigation purposes, e.g. investigate debugger process failures during lambda run. It would be great to have an option to pass an additional option through SAM CLI to mount additional volumes in Docker.

### Proposal
Extend SAM CLI to have an additional option `--additional-volume` with `multiple=True` flag that mount directories in a Docker container that run lambda.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)
No changes needed.

### Additional Details
The mapping should use the following rules:
- All specified volumes are mounted inside `/tmp/lambci_volumes` folder
- Each volume is mounted to a remote volume directory + host directory base name (e.g. `/Users/<user>/mount_this` should be mounted to `/tmp/lambci_volumes/mount_this` directory)
- Remote directory should have write access to be able to write logs into a folder.

**Comment by dacgray** [comment]
For reference - this is how we get around this issue:

https://github.com/dacgray/sam-local-start-api-container-image-volume-mount

**Comment by moelasmar** [comment]
similar to issue #2589
