### ISSUE TITLE
Function returned an invalid response when json values or keys contains special characters

### ISSUE THREAD

**Issue by joernkleinbub** [aws/aws-sam-cli#1530]
**Description**
I am using Golang for requesting Data from a MongoDB  to send a JSON via Lambda. I get the results from MongoDB and I can "marshal" the data to json successfully.
But when I want to send the data back as a response body I get sometimes the Error
http: 502 
Function returned an invalid response (must include one of: body, headers, multiValueHeaders or statusCode in the response object).

It seems that the problem is: When I have special characters like ü,ö,ä,é in the JSON (in a key name or a value text) I get that error. When the special characters are missing it is working well.

**Steps to reproduce**
Define a simple hardcoded response body like this JSON:
```
body := "[{\"test\":\"test\"}]"  -> success
body := "[{\"test\":\"tesüt\"}]" -> failing
```
sam is started simply with 
sam local start-api --debug

the APIGateway event definition in GOLANG is that:

```
resp := events.APIGatewayProxyResponse{
	Body:      body,
	StatusCode: 200,
	Headers: make(map[string]string),
	IsBase64Encoded: false,
	MultiValueHeaders: nil,
}
resp.Headers["Content-Type"] = "application/json"
```

**Observed result**
Function returned an invalid response (must include one of: body, headers, multiValueHeaders or statusCode in the response object). Response received: {"statusCode":200,"headers":{"Content-Type":"application/json"},"multiValueHeaders":null,"body":"[{\"test\":\"tesüt\"}]"}

**Expected result**
2019-11-14 12:22:23 127.0.0.1 - - [14/Nov/2019 12:22:23] "GET /searchapi?searchstring=Lu&lang=de HTTP/1.1" 200 -
Response-body: [{"test":"tesüt"}]

**Additional environment details**

1. OS: Linux Ubuntu 18.04
2. `sam --version`: SAM CLI, version 0.23.0

**Comment by CoshUS** [comment]
Closing as this issue is inactive.
Feel free to leave more information below and I can reopen this issue.
