### ISSUE TITLE
Add `--base-dir` option to local invoke and start-api

### ISSUE THREAD

**Issue by pierreis** [aws/aws-sam-cli#1541]
### Describe your idea/feature/enhancement

I suggest to add the `--base-dir option` to `sam local invoke` as well as `sam start-api`

### Proposal

The `-s, --base-dir DIRECTORY` exists in `sam build` to control the location of the source code relative to the template. This is extremely useful in cases where code is compiled out-of-source (say, from TypeScript to JavaScript), but we want to build from the output folder of the said compilation.

Because of the lack of such option in `sam local invoke` or `sam start-api`, there is no choice but to point the template to the generated code folder (besides generating a new template). It would be great for this option to be added to these two actions.

**Comment by sanathkr** [comment]
This sounds like a good feature request for the usecase and also to be consist with other commands. It should be simple to implement the feature. Feel free to send us a PR if you get to it.

**Comment by qingchm** [comment]
> ### Describe your idea/feature/enhancement
> I suggest to add the `--base-dir option` to `sam local invoke` as well as `sam start-api`
> 
> ### Proposal
> The `-s, --base-dir DIRECTORY` exists in `sam build` to control the location of the source code relative to the template. This is extremely useful in cases where code is compiled out-of-source (say, from TypeScript to JavaScript), but we want to build from the output folder of the said compilation.
> 
> Because of the lack of such option in `sam local invoke` or `sam start-api`, there is no choice but to point the template to the generated code folder (besides generating a new template). It would be great for this option to be added to these two actions.

Hey just wondering, can you specify any use case such that the --template option to specify the location of the template file cannot satisfy your needs that a --base-dir option is needed? I would love to hear the rationales behind it, since in my opinion --template and --base-dir fulfill similar needs for you. Thanks!

**Comment by qingchm** [comment]
Could not get in contact with the requesting customer, can re-open if communication established
