### ISSUE TITLE
Verify docker-lambda images

### ISSUE THREAD

**Issue by mhart** [aws/aws-sam-cli#1542]
docker-lambda now signs images using DCT:

https://github.com/lambci/docker-lambda#verifying-images

aws-sam-cli could now verify the signatures of the images if you'd like

Up to you, but I thought I'd let you know 👍

**Comment by mhart** [comment]
Looks like this might depend on support in `docker-py` – https://github.com/docker/docker-py/issues/1773 – unless you just want to shell out to docker.

**Comment by sanathkr** [comment]
Awesome. I don't think we will want to shell out to docker. I will leave this open for tracking purposes.
