### ISSUE TITLE
sam deploy with a samconfig.toml file should output the full sam deploy command

### ISSUE THREAD

**Issue by ericallam** [aws/aws-sam-cli#1616]
### Describe your idea/feature/enhancement

Guided deploy is nice for discovering what information is needed to supply to the `sam deploy` command. It would be nice to be able to see what the `sam deploy` command is for a given `samconfig.toml` file to assist in using `sam deploy` in environments where the `samconfig.toml` file cannot be used.

### Proposal

Output the full `sam deploy` command using the given values from a `samconfig.toml` file.

**Comment by benkehoe** [comment]
I'd like this to be maybe a "dry run"-only type thing? Like, let me ask SAM to print the current sam command corresponding to the config, without deploying.

**Comment by sriram-mv** [comment]
```
SAM_DEBUG=true sam deploy
Config file location: /Users/....../samconfig.toml
Loading configuration values from [default.['deploy'].parameters] (env.command_name.section) in config file at '/Users/......../samconfig.toml'...
Configuration values successfully loaded.
Configuration values are: {'stack_name': 'abc', 's3_bucket': 'mybucket', 's3_prefix': 'myprefix', 'region': 'us-west-2', 'capabilities': 'CAPABILITY_IAM'}
```

you will be able to see the full set of variables that are used.

For not deploying, you could to turn on confirm change-set and not deploy at the end as one option.  I'm going to close this original issue, dry-run could be its own separate issue.
