### ISSUE TITLE
Default S3 bucket if not set

### ISSUE THREAD

**Issue by mikebroberts** [aws/aws-sam-cli#1643]
While I like the new interactive "sam deploy" to setup the config file, what I think might be even better for buckets is if there's no bucket defined then sam cli uses a default name (and prefix), creating if necessary.

E.g. if there's no bucket available in context (either the config file or --s3-bucket) then look to see if (say) S3 bucket sam-cli-ACCOUNT_ID-REGION exists (where ACCOUNT_ID and REGION are substituted for the correct values) - if it doesn't then create it with some useful lifecycle and encryption policies. Then use that bucket, perhaps also by setting the prefix to the stack-name.

This wouldn't update the config file - it would just be for this particular invocation of sam deploy.

**Comment by sanathkr** [comment]
Definitely a good feature request. 

We try to identify if the account/region has been bootstrapped by the presence of the CloudFormation bootstrap stack. We don't want to create buckets outside of the stack various reasons. Most importantly using predictable bucket names opens up the possibility of bucket hijack attacks.

We do have all the right pieces to support this feature.

**Comment by sriram-mv** [comment]
`--resolve-s3` to sam deploy will figure out the s3 bucket by itself. Closing this issue.

**Comment by nimishbansal** [comment]
if we apply `--resolve-s3` , does aws managed bucket leads to cost for s3?
