### ISSUE TITLE
SAM 0.37.0 does not print AWS_LOGSTREAM statements anymore

### ISSUE THREAD

**Issue by CAJan93** [aws/aws-sam-cli#1662]
### Description

If you invoke a compiled artifact (written in C++) using `sam local invoke` the `AWS_LOGSTREAM` statements are no longer printed. 

### Steps to reproduce

- Update from version 0.30.0 to 0.37.0.
- Compile your C++ code for Lambda ([example here](https://aws.amazon.com/blogs/compute/introducing-the-c-lambda-runtime/))
- Your code should include AWS_LOGSTREAM statements
- make sure your log-level is correct `Aws::Utils::Logging::LogLevel::Trace`
- call function with `echo '{"my":"event"}' |  sam local invoke HelloWorldFunction --debug -l tmp.log`

### Observed results

Neither the console output nor tmp.log contains any logstream statements.

### Expected result

The console should print the logstream-statements.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 19.10
2. `sam --version`: 0.37.0

**Comment by wchengru** [comment]
I will close it because SAM CLI doesn't support C++ in the latest version 1.37.0. Please reopen it if you have more questions.
