### ISSUE TITLE
Show location of credentials file on invocation

### ISSUE THREAD

**Issue by timoschinkel** [aws/aws-sam-cli#1724]
In versions before `0.33.1`, when running `sam start-api` and invoking a function one of the lines informs the user of the location from where AWS credentials are loaded:

```bash
YYYY-MM-DD HH:MM:SS Found credentials in shared credentials file: ~/.aws/credentials
```

Starting from version `0.33.1` this line is no longer present. When running with the additional option `--debug` in the debug information is the line:

```bash
Loading AWS credentials from session with profile 'development'
```

In the release notes I cannot find this change, so I'm wondering what the reason was to remove this piece of information from the output and if it can be added again. 

A little bit of background; we use the STS Chrome extension to download a credentials file. This file is by default downloaded into `~/Downloads`. Resolving the message that my token had expired took me a while as I did not immediately realise where the credentials were searched.

I'm running MacOS 10.14.6

**Comment by sriram-mv** [comment]
We removed this to make the output cleaner, we can consider adding this output back to debug.

**Comment by timoschinkel** [comment]
I think adding it to the debug output will already offer enough information.

**Comment by CoshUS** [comment]
The output, `Found credentials in shared credentials file...` , is generated by boto3 instead of sam-cli.
Closing. Feel free to reopen is there is further issue.
