### ISSUE TITLE
Feature request: support of step functions

### ISSUE THREAD

**Issue by hervenivon** [aws/aws-sam-cli#174]
We are thrilled to use the serverless capacities of Amazon Web Services. 

Still, we met some issues with local development.

We turn ourselves to other local development capabilities like https://serverless.com/ or https://localstack.cloud/ not to mention our custom build for local tooling.

Is there any chance to see a support of the awesome [step functions](https://aws.amazon.com/step-functions/) in [AWS SAM local](https://aws.amazon.com/blogs/aws/new-aws-sam-local-beta-build-and-test-serverless-applications-locally/)

**Comment by purefan** [comment]
Not sure I understand how Step Functions would apply to Sam Local, do yo perhaps mean that you want a GUI to coordinate the flow of a trigger?

**Comment by HerveNivon** [comment]
As a managed state machine, entirely serverless, it may belong to SAM local by definition itself.

Step functions service is an integral part of our serverless applications. Two use cases:
1. A workflow with multiple steps and logic to process emails we receive,
2. An `API` endpoint that calls several lambda functions.

**Comment by HerveNivon** [comment]
Hi SAM

Any AWS comment? 

We are using Step Functions more and more on our side and we would be delighted of an official AWS support.

In the meantime we have started our work on a step functions local implementation: https://github.com/airware/stepfunctions-local

**Comment by Nr18** [comment]
Stumbled on a question in slack and found this thread because i would love to see support for StepFunctions in sam local. I also found this one: https://www.npmjs.com/package/stepfunctions-local but i prefer to have 1 tool like sam local that handles these things for development.

**Comment by Azuaron** [comment]
We're designing a new system and looking at Step Functions for the implementation. Being able to develop them locally with SAM might be the difference between using Step Functions and using something else.

**Comment by HerveNivon** [comment]
That really is a great news! Any ETA?

How can we help? Happy to share use cases or development effort!

**Comment by xliiauo** [comment]
+1 thanks

**Comment by d-me-tree** [comment]
+1

**Comment by 5t33** [comment]
+1

**Comment by phainamikaze** [comment]
+1

**Comment by asyba** [comment]
+1

**Comment by mlubavin-vg** [comment]
+1

**Comment by RobReus** [comment]
Well over 2 years later, any update?
+1

**Comment by elixyre** [comment]
you can call locally a step-function from a lambda using sam-local if you overwrite boto3. (In my requirements.txt I added `boto3==1.10.45`).

Whatever, a straight forward integrate should be great!

+1

**Comment by noonii** [comment]
+1

**Comment by hervenivon** [comment]
boom 🚀 
https://github.com/awslabs/aws-sam-cli/pull/2009

**Comment by timoschilling** [comment]
I would like to keep this ticket open until SAM CLI has local support for step functions, like it does with for lambdas with `invoke` and `start-lambda`.

**Comment by hervenivon** [comment]
Seems fair.

**Comment by awsjeffg** [comment]
@timoschilling I am currently reviewing older issues that are still open. I am closing this issue for now because we have implemented SAM support for Step Functions ( SFn ) but we have no plans currently to support a local emulation for SFn in the way I think you are asking.

If you feel strongly regarding local emulation of some sort, please file another issue and mention me, and I will be happy to investigate your use case.
