### ISSUE TITLE
Setting up debugger with AWS SAM CLI (GoLang)

### ISSUE THREAD

**Issue by aarthisankaran** [aws/aws-sam-cli#1740]
Steps used:
1) Installed delve: go get -u github.com/go-delve/delve/cmd/dlv

2) sudo /usr/sbin/DevToolsSecurity -enable

3) GOOS=linux GOARCH=amd64 go build -gcflags='-N -l' -o /Users/qgv313/development/qgv313org/GraphQL/securedcard-data-api/.dev/localserver ./develop/localserver/gateway.go ./develop/localserver/localserver.go ./develop/localserver/main.go

4) GOARCH=amd64 GOOS=linux go build -o ./dlv github.com/go-delve/delve/cmd/dlv

5) sam local start-api -d 3030 --template template.yaml --debugger-path ./ --debug-args "-delveAPI=2" 

$ sam local start-api -d 3030 --template template.yaml --debugger-path ./ --debug-args "-delveAPI=2" 
Mounting LocalServer at http://127.0.0.1:3000/health [GET]
Mounting LocalServer at http://127.0.0.1:3000/graphql [POST]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
 * Tip: There are .env files present. Do "pip install python-dotenv" to use them.
2020-01-22 09:50:07  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
.
.
Tried hitting the server http://127.0.0.1:3000/graphql, get below error message
.
.
Invoking .dev/localserver (go1.x)
Fetching lambci/lambda:go1.x Docker container image......
Mounting /Users/qgv313/development/qgv313org/GraphQL/securedcard-data-api as /var/task:ro,delegated inside runtime container
Could not create config directory: mkdir /home/sbx_user1051: permission denied.API server listening at: [::]:3030
2020-01-22T14:50:21Z info layer=debugger launching process with args: [/var/task/.dev/localserver]
could not launch process: fork/exec /var/task/.dev/localserver: no such file or directory

**Comment by aarthisankaran** [comment]
here is a snippet of my template.yaml

`AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  securedcard-data-api
  
  Sample SAM Template for securedcard-data-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 100

Resources:
  LocalServer:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: .dev/localserver
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        Data:
          Type: Api
          Properties:
            Path: /graphql
            Method: POST
        Health:
          Type: Api
          Properties:
            Path: /health
            Method: GET`

**Comment by sriram-mv** [comment]
Do invokes work normally as well? Or do you see this issue only on debugging?

**Comment by aarthisankaran** [comment]
Yes it works fine when I run in non-debug mode.

GOOS=linux GOARCH=amd64 go build -o .dev/localserver ./develop/localserver/gateway.go ./develop/localserver/localserver.go ./develop/localserver/main.go


sam local start-api --template template.yaml --port 3030
Mounting LocalServer at http://127.0.0.1:3030/graphql [POST]
Mounting LocalServer at http://127.0.0.1:3030/health [GET]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
 * Tip: There are .env files present. Do "pip install python-dotenv" to use them.
2020-01-24 08:58:56  * Running on http://127.0.0.1:3030/ (Press CTRL+C to quit)




Invoking .dev/localserver (go1.x)

Fetching lambci/lambda:go1.x Docker container image......
Mounting /Users/qgv313/development/qgv313org/GraphQL/securedcard-data-api as /var/task:ro,delegated inside runtime container

AND WORKS FINE

**Comment by aarthisankaran** [comment]
I made some progress by specifying CodeUri in the template.yaml


qgv313@38f9d3c01d26 ~/development/qgv313org/GraphQL/securedcard-data-api (debug) 
$ GOOS=linux GOARCH=amd64 go build -gcflags="all=-N -l" -o ./develop/localserver/localserver ./develop/localserver/gateway.go ./develop/localserver/localserver.go ./develop/localserver/main.go
qgv313@38f9d3c01d26 ~/development/qgv313org/GraphQL/securedcard-data-api (debug) 
$ GOARCH=amd64 GOOS=linux go build -o ./dlv github.com/go-delve/delve/cmd/dlv
qgv313@38f9d3c01d26 ~/development/qgv313org/GraphQL/securedcard-data-api (debug) 
$ sam local start-api -d 3030 --template template.yaml --debugger-path ./ --debug-args "-delveAPI=2"
Mounting LocalServer at http://127.0.0.1:3000/health [GET]
Mounting LocalServer at http://127.0.0.1:3000/graphql [POST]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
 * Tip: There are .env files present. Do "pip install python-dotenv" to use them.
2020-01-24 16:07:57  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)


Invoking localserver (go1.x)

Fetching lambci/lambda:go1.x Docker container image......
Mounting /Users/qgv313/development/qgv313org/GraphQL/securedcard-data-api/develop/localserver as /var/task:ro,delegated inside runtime container
Could not create config directory: mkdir /home/sbx_user1051: permission denied.API server listening at: [::]:3030
2020-01-24T21:08:05Z info layer=debugger launching process with args: [/var/task/localserver]


IT JUST HANGS HERE NOW - not sure if it because it wasn't able to create the config directory

**Comment by aarthisankaran** [comment]
go version go1.13.4 darwin/amd64

**Comment by aarthisankaran** [comment]
[template.yaml.zip](https://github.com/awslabs/aws-sam-cli/files/4110733/template.yaml.zip)

**Comment by aarthisankaran** [comment]
my template.yaml:

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  securedcard-data-api

  Sample SAM Template for securedcard-data-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 100

Resources:
  LocalServer:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: develop/localserver/
      Handler: localserver
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        Data:
          Type: Api
          Properties:
            Path: /graphql
            Method: POST
        Health:
          Type: Api
          Properties:
            Path: /health
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          ENV: LOCAL
          TRXN_DB_HOST: !Ref TrxnDbHost
          TRXN_DB_PORT: !Ref TrxnDbPort
          TRXN_DB_NAME: !Ref TrxnDbName
          TRXN_DB_USER: !Ref TrxnDbUser
          TRXN_DB_PASSWORD: !Ref TrxnDbPassword
          APPN_DB_API: !Ref AppnDbAPI
          DEPACCT_DB_API: !Ref DepAcctDbAPI
          DEPTRXN_DB_API: !Ref DepTrxnDbAPI

**Comment by jfuss** [comment]
@aarthisankaran 

> IT JUST HANGS HERE NOW - not sure if it because it wasn't able to create the config directory

It is waiting for the debugger to attach. Did you launch the debugger?

**Comment by aarthisankaran** [comment]
I am using Goland. It seems to launch but I am not able to see if it is attached.

<img width="914" alt="Screen Shot 2020-01-24 at 4 23 28 PM" src="https://user-images.githubusercontent.com/8172428/73105043-ec2be300-3ec5-11ea-84ad-3100e9bb18ae.png">

**Comment by aarthisankaran** [comment]
Even though the api port I specify is 3030, it mounts at 3000 and I assume debug port should connect to 3000. Either case I tried both 3030 and 3000 unable to tell it attaches. It doesn't terminate.

$ sam local start-api -d 3030 --template template.yaml --debugger-path ./ --debug-args "-delveAPI=2"
Mounting LocalServer at http://127.0.0.1:3000/health [GET]
Mounting LocalServer at http://127.0.0.1:3000/graphql [POST]

**Comment by aarthisankaran** [comment]
@jfuss @sriram-mv can I get some help here please!

**Comment by aarthisankaran** [comment]
Any update on this issue?

**Comment by JMRolf-Spok** [comment]
I am also experiencing this issue.

**Comment by JMRolf-Spok** [comment]
For me the issue of the Lambda appearing to hang was, as @jfuss suggested, an issue of my debugging not attaching correctly. I'm using VS Code rather than GoLand as in @aarthisankaran's case, but the symptom being the same tells me it is probably the result of the same problem. Once I updated my launch.json for VS Code to the appropriate configuration, the Lambda ran to completion.

For some reason my breakpoints didn't get hit, but that is a different problem I believe that is just related to VS Code.

**Comment by sriram-mv** [comment]
This is the guide for the go debugging: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-debugging-golang.html

**Comment by jechen95** [comment]
@JMRolf-Spok I'm having this issue but with sam local start-lambda. Can you elaborate on what you've updated in your launch.json?

**Comment by sriram-mv** [comment]
I'm going to close this issue as there is a official doc on go debugging referenced here and the https://github.com/aws/aws-sam-cli/pull/2555 recently fixed issues with go debugging.

**Comment by trixpan** [comment]
@sriram-mv this still broken.

Breakpoints don't seem to work using intellij and 

```
% sam --version
SAM CLI, version 1.19.1
```

Running on MacOS

**Comment by danludwig** [comment]
> > IT JUST HANGS HERE NOW - not sure if it because it wasn't able to create the config directory
> 
> It is waiting for the debugger to attach. Did you launch the debugger?

I can confirm that it did work for me. Something like this in Makefile:
```
debugapi:
	go env -w CGO_ENABLED=0
	GOOS=linux GOARCH=amd64 go build -gcflags="all=-N -l" -o ./.debug/local/hw ./hw/main.go
	GOARCH=amd64 GOOS=linux go build -o ./.debug/dlv/dlv github.com/go-delve/delve/cmd/dlv
	go env -w CGO_ENABLED=1
	sam local start-api -d 5858 --template template.yaml --debugger-path ./.debug/dlv --debug-args "-delveAPI=2"

```

and change your template.yaml to point to the new binaries
```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      # CodeUri: hw/
      # Handler: hw
      CodeUri: .debug/local/
      Handler: hw
      Runtime: go1.x
      Architectures:
        - x86_64
```
and add this to launch.json
```
    {
      "name": "attach sam-app0",
      "type": "go",
      "request": "attach",
      "mode": "remote",
      "port": 5858,
      "host": "127.0.0.1",
      "cwd": "${workspaceFolder}"
    }
```

With that, if I start by running `make debugapi`, the output prints
> GO_ENABLED=0
> GOOS=linux GOARCH=amd64 go build -gcflags="all=-N -l" -o ./.debug/local/hw ./hw/main.go
> GOARCH=amd64 GOOS=linux go build -o ./.debug/dlv/dlv github.com/go-delve/delve/cmd/dlv
> go env -w CGO_ENABLED=1
> sam local start-api -d 5858 --template template.yaml --debugger-path ./.debug/dlv --debug-args "-delveAPI=2"
> Initializing the lambda functions containers.
> Local image is up-to-date
> Using local image: public.ecr.aws/lambda/go:1-rapid-x86_64.
> 
> Mounting /Users/dan/code/github/danludwig/preploy-data/sam-app0/.debug/local as /var/task:ro,delegated inside runtime container
> Containers Initialization is done.
> Mounting HelloWorldFunction at http://127.0.0.1:3000/hello [GET]
> You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. If you used sam build before running local commands, you will need to re-run sam build for the changes to be picked up. You only need to restart SAM CLI if you update your AWS SAM template
> 2023-02-28 19:51:59  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)

then hit the server with `curl http://localhost:3000/hello`, it prints this

> Invoking hw (go1.x)
> Reuse the created warm container for Lambda function 'HelloWorldFunction'
> Lambda function 'HelloWorldFunction' is already running
> API server listening at: [::]:5858
> 2023-03-01T00:53:42Z warning layer=rpc Listening for remote connections (connections are not authenticated nor encrypted)
> 2023-03-01T00:53:42Z info layer=debugger launching process with args: [/var/task/hw]

Now, make sure there is a breakpoint in your main.go code file and that the vscode launch configuration above is selected, hit F5 to attach:

> 2023-03-01T00:55:18Z info layer=debugger created breakpoint: &api.Breakpoint{ID:1, Name:"", Addr:0x86ff59, Addrs:[]uint64{0x86ff59}, AddrPid:[]int{28}, File:"/Users/dan/code/github/danludwig/preploy-data/sam-app0/hw/main.go", Line:26, FunctionName:"main.handler", Cond:"", HitCond:"", HitCondPerG:false, Tracepoint:false, TraceReturn:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(0xc00026c120), LoadLocals:(*api.LoadConfig)(0xc00026c150), WatchExpr:"", WatchType:0x0, VerboseDescr:[]string(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0, Disabled:false, UserData:interface {}(nil)}
> 2023-03-01T00:55:18Z debug layer=debugger continuing
