### ISSUE TITLE
samcli/lib/package/s3_uploader.py on_progress writes progress to stderr causing issues with CD/CD

### ISSUE THREAD

**Issue by IanLeeClaxton** [aws/aws-sam-cli#1775]
### Description

When doing a sam deploy I am getting issues as information is being written to the stderr when uploading sam deployments to s3. 

Surely if you want to change the font colour there is a better way of doing this.

Most CI/CD systems will flag if anything is written to the stderr stream and I would prefer not to redirect as this will mask any real issues.

### Steps to reproduce

sam deploy with s3 bucket configured

### Observed result

Upload progress written to stderr

### Expected result

Upload progress written to a stdout

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: windows 10
2. `sam --version`: 0.40.0

**Comment by sriram-mv** [comment]
We actually had feedback from the community where they wanted it this way. It was originally writing to stdout.

Will add this a feature request.

**Comment by IanLeeClaxton** [comment]
I have seen this practice with other Aws apps also and has been a headache redirecting the stderr stream to avoid error reporting.

Maybe an option like the aws s3 sync command --no-progress would work as well as the suggestion from this chap to change the output color:
https://stackoverflow.com/questions/287871/how-to-print-colored-text-in-terminal-in-python#287944

Thanks for the quick response and happy to help if needed.

Ian

**Comment by sriram-mv** [comment]
sam package now has `--no-progressbar`. Closing this issue,
