### ISSUE TITLE
Sort sam init runtimes alphanumerically

### ISSUE THREAD

**Issue by awschristou** [aws/aws-sam-cli#1782]
### Describe your idea/feature/enhancement

![image](https://user-images.githubusercontent.com/39839589/74185353-53070700-4bfd-11ea-9e5b-6d57667f4543.png)

The list of runtimes shown in `sam init` are hard to look through. For example, if I was interested in a node app, I have to hunt through the list to find one up top, and one in the middle (7 in the image). 
 I think two improvements could help improve time to locate the runtime of interest:

* alphanumeric-sort the runtimes
* right-align the numbers (1-13 in the image)

**Comment by jfuss** [comment]
@awschristou This are sorted this way on purpose. The first group is (1-6) are the latest of each runtime, then 6-13 are grouped by runtime from the newest to oldest.

**Comment by awschristou** [comment]
That's interesting... I understand why you'd want to have the current runtimes up front, especially if the list were (for example) 50 entries large. I think the current presentation doesn't make it easy to find runtime(s) for users, which may run counter to providing an interactive menu.

What if the list showed _only_ the current runtimes (alphabetically sorted), and an (n+1) option to "Show additional runtimes". Selecting the latter can then list all runtimes sorted alphabetically. Would this address the same concerns and improve visual location of runtimes?

**Comment by sriram-mv** [comment]
@awschristou sam init workflow has been redesigned to enable some shortcuts and the runtimes are indeed sorted alphabetically now.

`sam init` also gives you a banner to showcase selecting a runtime directly before starting the interactive experience.
