### ISSUE TITLE
sam local start-api sends timeouts on some computers

### ISSUE THREAD

**Issue by snavarro89** [aws/aws-sam-cli#1792]
Hello

I am running version 0.41.0 of aws-sam-cli. When running the template hello world of go. On some computers we get the error "timeout 5 seconds" on those same computers sometimes it works and sometimes it doesnt. We have increased the timeout up to 60 seconds and nothing. All computers are running Ubuntu 18 LTS.  When creating a node project the api url works correctly. 
Has this happened to anyone?

**Comment by sriram-mv** [comment]
Interesting, does --debug have any clues?

**Comment by CoshUS** [comment]
Closing.
Feel free to reopen if there is further information or issue.
