### ISSUE TITLE
AWS SAM S3 Cors

### ISSUE THREAD

**Issue by Haga14** [aws/aws-sam-cli#1816]
### Description

I am setting up a serverless app that is composed of an S3 bucket, a lambda function and API Gateway. I need my S3 bucket to trigger a notification on every upload event and feed the info into my lambda function. 

The uploads to S3 bucket are happening via a pre-signed URL and hence, I need my bucket to allow requests from anywhere (access-control-allow-origin: *). This cors config works fine with API gateway. I'm able to access my lambda from where. However, when my lambda generates my pre-signed url and I attempt the upload, I get a cors allow origin issue in the preflight. I have tried setting cors on the S3 bucket as follows, but for some reason this doesn't work and I can't find any documentation on this anywhere. 

I should also point out, that I can't just manually create an S3 bucket and set it up separately, then hook it up to the event in this template. For some reason, the S3 bucket referenced by the event must be also created in the same bucket?!?!?? (I tried it, and got error that says that)

`  SrcBucket:
    Type: AWS::S3::Bucket
    BucketName: "****************************************"
    PublicAccessBlockConfiguration:
      - BlockPublicAcls: false
      - BlockPublicPolicy: false
      - IgnorePublicAcls: false
      - RestrictPublicBuckets: false
    CorsRules:
      - AllowedMethods: "'GET,PUT,OPTIONS'"
      - AllowedHeaders: "'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Access-Control-Allow-Origin'"
      - AllowedOrigin: "'*'"
`
### Steps to reproduce

Here's the Same Template:
`
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: '
  '
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: '''GET,POST,OPTIONS'''
      AllowHeaders: '''DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Access-Control-Allow-Origin'''
      AllowOrigin: '''*'''
Parameters:
  BucketNamePrefix:
    Type: String
    Default: **************
  DBName:
    Type: String
    Default: ****************
Resources:
  ***************:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ***********
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
      - S3CrudPolicy:
          BucketName:
            Fn::Sub: ${BucketNamePrefix}-get-object
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DBName
      Environment:
        Variables:
          s3Bucket: ***********************
      Events:
        ApiCall:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: /upload
            Method: POST
        CreateThumbnailEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: SrcBucket
            Events: s3:ObjectCreated:*
  SrcBucket:
    Type: AWS::S3::Bucket
    BucketName: ************************
    PublicAccessBlockConfiguration:
    - BlockPublicAcls: false
    - BlockPublicPolicy: false
    - IgnorePublicAcls: false
    - RestrictPublicBuckets: false
    CorsRules:
    - AllowedMethods: '''GET,PUT,OPTIONS'''
    - AllowedHeaders: '''DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Access-Control-Allow-Origin'''
    - AllowedOrigin: '''*'''
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Variables:
        LambdaFunctionName:
          Ref: *******************

1. OS: Linux
2. `sam --version`:Latest

`Add --debug flag to command you are running`

**Comment by cro13** [comment]
You can try something like:
`  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "MyBucket"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
            AllowedOrigins:
              - "*"
`

**Comment by jfuss** [comment]
Given the age, I am going to close this. It seems like this is more of a question about how to write the CloudFormation template and nothing specific to the CLI.
