### ISSUE TITLE
Support running sam-local on hosts with log drivers such as awslogs

### ISSUE THREAD

**Issue by jhovell** [aws/aws-sam-cli#182]
If a logging driver such as `awslogs` is configured in `/etc/sysconfig/docker` it is impossible to use sam local on the host. The reason seems to be that certain features required by sam local are not made available by the awslogs driver. This is a known limitation of certain logging drivers, but sam local does not specify an overriding log driver such as json, journald, etc for lambci containers or expose the ability to override this logging driver to the user.

Ideally awslogs log driver would support reading but absent that it must be possible to override or specify an adequate logging driver when starting lambci containers in sam local.

Similar issue where a similar logging driver error is encountered:

https://github.com/docker/compose/issues/2379

Currently any attempt to run sam local on a host with a log driver that does not support reading such as awslogs fails with a message:

command: `aws local invoke MyFunction -e event.json `
output:
```
sam-local> 2017/10/25 06:19:56 Invoking myapp.EventHandler::handleRequest (java8)
23:19:56 sam-local> 2017/10/25 06:19:56 Decompressing /mnt/sam/target/myapp.jar
23:19:58 sam-local> 2017/10/25 06:19:58 Connecting container 5ba2950fe6792b4fd1fabf38f2221a7f167aa904d0ed670b0f65d19abb018f26 to network myapp
23:19:58 sam-local> 
23:19:58 sam-local> Error attaching: configured logging reader does not support reading
```

If you run `start-api` instead of invoke, you get a much less helpful error since this Docker error is presumably attempted to be parsed into JSON... I think `invalid character E` comes from the first character of `Error attaching: configured logging reader...`

https://github.com/awslabs/aws-sam-local/issues/122#issuecomment-339181498
```
Function returned an invalid response (must include one of: body, headers or statusCode in the response object): invalid character 'E' looking for beginning of value
```

Allowing overriding of the logging driver (or even better having sam local specify a built in logging driver that it requires) seems acceptable because there is not really a use case for logs from these containers outside of the context of running sam local

**Comment by sanathkr** [comment]
When would you want to use this feature? This logging driver won't be present in Lambda. So what's the point in using it locally?

**Comment by jhovell** [comment]
@sanathkr for CI. We're running sam-local on an EC2/ECS instance that is part of a Jenkins cluster that uses awslogs on all containers *by default*. Maybe the title was unclear but I'd like to be able to receive log messages somehow. Right now sam-local throws up trying to parse an error about awslogs. 

From the original request:

>but sam local does not specify an overriding log driver such as json, journald, etc for lambci containers or expose the ability to override this logging driver to the user.

I'd like to be able to specify a "normal" Docker logs driver for SAM local lambda containers.

**Comment by morefaey** [comment]
@jhovell please reopen this if you still think it is needed.
