### ISSUE TITLE
SAM deploy changeset missing "Replacement" column

### ISSUE THREAD

**Issue by peter-hindos** [aws/aws-sam-cli#1844]
Hi,

I'm using version 0.43.0 and when I run sam deploy on my stack, the changeset preview is missing the "Replacement" column. So I do not know whether my resource is going to be replaced or not. I need to log in to the console and inspect the change set there in order to determine if a replacement will take place.

Would be nice to have this information available in shell without the need to check in console.

**Comment by c2tarun** [comment]
To add some more context, some resources in AWS can be replaced to modify. Eg: if we change schema of DynamoDB table it'll be replaced, but changing read capacity will only modify the resource. This could be useful information to display.
