### ISSUE TITLE
Parallelize build Command

### ISSUE THREAD

**Issue by Kotaimen** [aws/aws-sam-cli#1876]
SAM builds lambda functions sequentially, so when SAM template is having large amount of lambda functions build process is very slow, especially when `--use-container` is enabled.

I'd like to SAM build lambda functions in parallel to speed up build, especially when running sam-cli in CodeBuild and it's only utilizing a single core.

**Comment by jfuss** [comment]
@Kotaimen Thanks for the request. Both `sam build` and `sam package` doing building/packaging sequentially right now :(. This is defiantly an improvement worth doing for customers with large amounts of lambda functions. Updating labels.

**Comment by mndeveci** [comment]
With the release of [1.9.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.9.0), SAM CLI now supports parallel builds
