### ISSUE TITLE
Sam package error

### ISSUE THREAD

**Issue by newbie737** [aws/aws-sam-cli#1883]
### Description

I am following this tutorial: https://read.acloud.guru/build-your-own-multi-user-photo-album-app-with-react-graphql-and-aws-amplify-374800b22e96 and all was good until the step "Deploying a SAM Template file"

### Steps to reproduce

I run the command:`  sam package --template-file template.yaml --s3-bucket <some_bucket_name> --output-template-file packaged.yml --debug`

### Observed result
I have the following errors:

> Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
> Unable to export
> Traceback (most recent call last):
>   File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.41.0/libexec/lib/python3.7/site-packages/samcli/lib/package/artifact_exporter.py", line 265, in export
>     self.do_export(resource_id, resource_dict, parent_dir)
>   File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.41.0/libexec/lib/python3.7/site-packages/samcli/lib/package/artifact_exporter.py", line 281, in do_export
>     uploaded_url = upload_local_artifacts(resource_id, resource_dict, self.PROPERTY_NAME, parent_dir, self.uploader)
>   File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.41.0/libexec/lib/python3.7/site-packages/samcli/lib/package/artifact_exporter.py", line 151, in upload_local_artifacts
>     return zip_and_upload(local_path, uploader)
>   File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.41.0/libexec/lib/python3.7/site-packages/samcli/lib/package/artifact_exporter.py", line 168, in zip_and_upload
>     with zip_folder(local_path) as zip_file:
>   File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/contextlib.py", line 112, in __enter__
>     return next(self.gen)
>   File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.41.0/libexec/lib/python3.7/site-packages/samcli/lib/package/artifact_exporter.py", line 183, in zip_folder
>     zipfile_name = make_zip(filename, folder_path)
>   File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.41.0/libexec/lib/python3.7/site-packages/samcli/lib/package/artifact_exporter.py", line 201, in make_zip
>     zf.write(full_path, relative_path)
>   File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/zipfile.py", line 1730, in write
>     zinfo = ZipInfo.from_file(filename, arcname)
>   File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/zipfile.py", line 518, in from_file
>     st = os.stat(filename)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/Development/photo-albums/photo_processor/src/node_modules/.bin/detect-libc'
> Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam package', 'duration': 126, 'exitReason': 'ExportFailedError', 'exitCode': 1, 'requestId': '32-*** ', 'installationId': ' 32-*** ', 'sessionId': ' 32-*** ', 'executionEnvironment': 'CLI', 'pyversion': '3.7.6', 'samcliVersion': '0.41.0'}}]}
> HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
> Error: Unable to upload artifact src/ referenced by CodeUri parameter of PhotoProcessorFunction resource.
> [Errno 2] No such file or directory: '/home/Development/photo-albums/photo_processor/src/node_modules/.bin/detect-libc'
> 
> 

### Expected result
I dont know why I see  `[Errno 2] No such file or directory: /home/Development/photo-albums/photo_processor/src/node_modules/.bin/detect-lib`, since there is such folder and I can see it from the command line

Also, I dont understand the first line of the error message, namely: 

> Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics

I configured my bucket to be in another zone, not us-west-2

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu
2. `sam --version`: SAM CLI, version 0.41.0

Posting my template.yaml file, if needed, but it is the one from the tutorial; also when I run `sam validate` it says it is a valid template

```
# photo_processor/template.yml

AWSTemplateFormatVersion:                 '2010-09-09'
Transform:                                AWS::Serverless-2016-10-31
Description:                              >
    photo_processor
    Sample SAM Template for photo_processor

Parameters:
    S3UserfilesBucketArn:
        Type:                             String

Globals:
    Function:
        Timeout:                          10

Resources:
    PhotoProcessorFunctionIamRole:
        Type:                             "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version:                  "2012-10-17"
                Statement:
                    -
                        Effect:           Allow
                        Principal:
                            Service:      [lambda.amazonaws.com]
                        Action:           ["sts:AssumeRole"]
            ManagedPolicyArns:            ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"]
            Path:                         "/"
            Policies:
                -
                    PolicyName:           "AllPrivsForPhotoAlbumUserfilesBucket"
                    PolicyDocument:
                        Version:          "2012-10-17"
                        Statement:
                            -
                                Effect:   "Allow"
                                Action:   "s3:*"
                                Resource: !Join ["/", [!Ref S3UserfilesBucketArn, "*"]]
    PhotoProcessorFunction:
        Type:                             AWS::Serverless::Function
        Properties:
            CodeUri:                      src/
            Handler:                      app.lambda_handler
            Role:                         !GetAtt PhotoProcessorFunctionIamRole.Arn
            Runtime:                      nodejs12.x
            Environment:
                Variables:
                    THUMBNAIL_WIDTH:      80
                    THUMBNAIL_HEIGHT:     80
    BucketPermission:
        Type:                             AWS::Lambda::Permission
        Properties:
            Action:                       'lambda:InvokeFunction'
            FunctionName:                 !Ref PhotoProcessorFunction
            Principal:                    s3.amazonaws.com
            SourceAccount:                !Ref "AWS::AccountId"
            SourceArn:                    !Ref S3UserfilesBucketArn

Outputs:
    PhotoProcessorFunction:
      Description:                        "Photo Processor Lambda Function ARN"
      Value:                              !GetAtt PhotoProcessorFunction.Arn
    PhotoProcessorFunctionIamRole:
      Description:                        "IAM Role created for Photo Processor function"
      Value:                              !GetAtt PhotoProcessorFunctionIamRole.Arn
```

**Comment by sriram-mv** [comment]
did you try `sam build` before trying to sam package?

**Comment by newbie737** [comment]
@sriram-mv  I just did ` sam build ` and it again failed with the following output:

`Building resource 'PhotoProcessorFunction'
Running NodejsNpmBuilder:NpmPack
Running NodejsNpmBuilder:CopyNpmrc
Running NodejsNpmBuilder:CopySource
Running NodejsNpmBuilder:NpmInstall

Build Failed
Error: NodejsNpmBuilder:NpmInstall - NPM Failed: npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
info sharp Using cached /home/.npm/_libvips/libvips-8.6.1-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=12.14.0 runtime=node arch=x64 platform=linux)
In file included from ../src/common.cc:27:0:
../src/common.h:82:20: error: ‘Handle’ is not a member of ‘v8’
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                    ^~~~~~
../src/common.h:82:37: error: expected primary-expression before ‘>’ token
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                     ^
../src/common.h:82:39: error: ‘obj’ was not declared in this scope
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                       ^~~
../src/common.h:82:56: error: expected primary-expression before ‘attr’
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                                        ^~~~
../src/common.h:82:60: error: expression list treated as compound expression in initializer [-fpermissive]
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                                            ^
../src/common.h:83:29: error: ‘Handle’ is not a member of ‘v8’
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                             ^~~~~~
../src/common.h:83:46: error: expected primary-expression before ‘>’ token
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                                              ^
../src/common.h:83:48: error: ‘obj’ was not declared in this scope
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                                                ^~~
../src/common.h:83:65: error: expected primary-expression before ‘attr’
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                                                                 ^~~~
../src/common.h:84:48: error: ‘Handle’ is not a member of ‘v8’
   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                ^~~~~~
../src/common.h:84:65: error: expected primary-expression before ‘>’ token
   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                                 ^
../src/common.h:84:67: error: ‘obj’ was not declared in this scope
   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                                   ^~~
../src/common.h:84:84: error: expected primary-expression before ‘attr’
   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                                                    ^~~~
../src/common.h:84:37: warning: variable templates only available with -std=c++14 or -std=gnu++14
   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                     ^~~~~~
../src/common.h:84:90: error: expected ‘;’ before ‘{’ token
   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                                                          ^
../src/common.h:87:37: error: ‘Handle’ is not a member of ‘v8’
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                     ^~~~~~
../src/common.h:87:54: error: expected primary-expression before ‘>’ token
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                                      ^
../src/common.h:87:56: error: ‘obj’ was not declared in this scope
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                                        ^~~
../src/common.h:87:73: error: expected primary-expression before ‘attr’
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                                                         ^~~~
../src/common.h:87:26: warning: variable templates only available with -std=c++14 or -std=gnu++14
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                          ^~~~~~
../src/common.h:87:79: error: expected ‘;’ before ‘{’ token
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                                                               ^
../src/common.h:90:37: error: ‘Handle’ is not a member of ‘v8’
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
                                     ^~~~~~
../src/common.h:90:54: error: expected primary-expression before ‘>’ token
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
                                                      ^
../src/common.h:90:56: error: ‘obj’ was not declared in this scope
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
                                                        ^~~
../src/common.h:90:61: error: expected primary-expression before ‘int’
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
                                                             ^~~
../src/common.h:87:26: warning: variable templates only available with -std=c++14 or -std=gnu++14
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                          ^~~~~~
../src/common.h:90:71: error: expected ‘;’ before ‘{’ token
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
                                                                       ^
../src/common.h:96:9: error: ‘Handle’ is not a member of ‘v8’
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
         ^~~~~~
../src/common.h:96:26: error: expected primary-expression before ‘>’ token
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
                          ^
../src/common.h:96:28: error: ‘input’ was not declared in this scope
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
                            ^~~~~
../src/common.h:96:28: note: suggested alternative: ‘ino_t’
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
                            ^~~~~
                            ino_t
../src/common.h:96:70: error: expected primary-expression before ‘&’ token
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
                                                                      ^
../src/common.h:96:71: error: ‘buffersToPersist’ was not declared in this scope
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
                                                                       ^~~~~~~~~~~~~~~~
../src/common.h:96:87: error: expression list treated as compound expression in initializer [-fpermissive]
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
                                                                                       ^
../src/common.cc:34:20: error: redefinition of ‘bool sharp::HasAttr’
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
                    ^~~~~~
In file included from ../src/common.cc:27:0:
../src/common.h:82:8: note: ‘bool sharp::HasAttr’ previously defined here
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
        ^~~~~~~
../src/common.cc:34:20: error: ‘Handle’ is not a member of ‘v8’
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
                    ^~~~~~
../src/common.cc:34:37: error: expected primary-expression before ‘>’ token
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
                                     ^
../src/common.cc:34:39: error: ‘obj’ was not declared in this scope
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
                                       ^~~
../src/common.cc:34:56: error: expected primary-expression before ‘attr’
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
                                                        ^~~~
../src/common.cc:37:29: error: redefinition of ‘std::string sharp::AttrAsStr’
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
                             ^~~~~~
In file included from ../src/common.cc:27:0:
../src/common.h:83:15: note: ‘std::string sharp::AttrAsStr’ previously declared here
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
               ^~~~~~~~~
../src/common.cc:37:29: error: ‘Handle’ is not a member of ‘v8’
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
                             ^~~~~~
../src/common.cc:37:46: error: expected primary-expression before ‘>’ token
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
                                              ^
../src/common.cc:37:48: error: ‘obj’ was not declared in this scope
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
                                                ^~~
../src/common.cc:37:65: error: expected primary-expression before ‘attr’
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
                                                                 ^~~~
../src/common.cc:43:9: error: redefinition of ‘sharp::InputDescriptor* sharp::CreateInputDescriptor’
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
         ^~~~~~
In file included from ../src/common.cc:27:0:
../src/common.h:95:20: note: ‘sharp::InputDescriptor* sharp::CreateInputDescriptor’ previously defined here
   InputDescriptor* CreateInputDescriptor(
                    ^~~~~~~~~~~~~~~~~~~~~
../src/common.cc:43:9: error: ‘Handle’ is not a member of ‘v8’
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
         ^~~~~~
../src/common.cc:43:26: error: expected primary-expression before ‘>’ token
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
                          ^
../src/common.cc:43:28: error: ‘input’ was not declared in this scope
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
                            ^~~~~
../src/common.cc:43:28: note: suggested alternative: ‘ino_t’
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
                            ^~~~~
                            ino_t
../src/common.cc:43:70: error: expected primary-expression before ‘&’ token
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
                                                                      ^
../src/common.cc:43:71: error: ‘buffersToPersist’ was not declared in this scope
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
                                                                       ^~~~~~~~~~~~~~~~
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-74-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/Development/photo-albums/photo_processor/.aws-sam/build/PhotoProcessorFunction/node_modules/sharp
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN photo_processor@1.0.0 No repository field.
npm WARN photo_processor@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.20.8 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.20.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

`
Tbh, I am new at SAM and I was just following the above tutorial to generate my thumbnails. It didnt mention the `sam build` command just `sam package`

**Comment by newbie737** [comment]
@sriram-mv the second error to me, indicates that there might be problem with the permissions; however when I did `ls -l` I got the following output: `rwxrwxrwx 1 username  detect-libc` so to me the permissions look OK? Yet I dont understand why did I get the second error `[Errno 2] No such file or directory: '/home/Development/photo-albums/photo_processor/src/node_modules/.bin/detect-libc'`

**Comment by sriram-mv** [comment]
hmm, do you face the same error with sam build --use-container

**Comment by sriram-mv** [comment]
also do you face this with the native nodejs template supplied with sam init. try sam init, follow the prompts and see if you are still facing this issue.

**Comment by CoshUS** [comment]
Closing as no more information was provided.
Feel free to reopen if there is further discussion.
