### ISSUE TITLE
SAM TOML file should support array of capabilities

### ISSUE THREAD

**Issue by drumadrian** [aws/aws-sam-cli#1899]
### Describe your idea/feature/enhancement:

The _samconfig.toml_ file allows specifying capabilities like this: 

`capabilities = "CAPABILITY_IAM"
`

This documentation page explains that SAM uses TOML: 
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html

### Proposal:

The [TOML](https://github.com/toml-lang/toml) documentation shows that [TOML arrays](https://github.com/toml-lang/toml#array) are expressed like this: 

```
integers = [ 1, 2, 3 ]
colors = [ "red", "yellow", "green" ]
nested_array_of_int = [ [ 1, 2 ], [3, 4, 5] ]
nested_mixed_array = [ [ 1, 2 ], ["a", "b", "c"] ]
string_array = [ "all", 'strings', """are the same""", '''type''' ]

# Mixed-type arrays are allowed
numbers = [ 0.1, 0.2, 0.5, 1, 2, 5 ]
contributors = [
  "Foo Bar <foo@example.com>",
  { name = "Baz Qux", email = "bazqux@example.com", url = "https://example.com/bazqux" }
]
```

The SAM TOML file should allow this as a valid expression of **multiple** _capabilities_: 

`capabilities = [ "CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND" ]
`

### Additional Details:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)?
- **I do not believe this will require updates to the SAM Spec.** 

_Thank you for considering this feature_

**Comment by sriram-mv** [comment]
Thanks for the feature request. you should be able to have multiple values in your samconfig.toml file this way right now, but i have tagged this issue as feature request. 👍 

```
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
```

**Comment by drumadrian** [comment]
Thank you @sriram-mv 

I was able to use that approach to have multiple values in my _samconfig.toml_ file

Screenshot: 
<img width="961" alt="successful multiple capabilities" src="https://user-images.githubusercontent.com/6573380/77810691-04011e00-7053-11ea-8aaf-4c34345b88e3.png">

**Comment by matheuscanela** [comment]
Hi sriram-mv@

I added a PR for the documentation as it is not clear; however, I would recommend updating the documentation once this feature is released.

**Comment by aahung** [comment]
Also there seems to be no way to specify multiple capacities using cli args.

**Comment by qingchm** [comment]
I think changing the default option behaviour would be a breaking change for many so instead of a feature request I think this should be a UX change request. Multiple values for capabilities for both toml and cli arg are realized by having a long string with values separated by space like: capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM". I think this is still a relevant request since the doc and the help text doesn't mention this.

**Comment by drumadrian** [comment]
Hi @qingchm, 

   That sounds good.  I hope we can find a way to implement this change without breaking anyone's code.  

 Maybe a warning from the CLI could help.

Thanks for looking into this 🤓

**Comment by qingchm** [comment]
My pleasure!

**Comment by sriram-mv** [comment]
```bash
[default.deploy]
[default.deploy.parameters]
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
resolve_s3 = true
```

On further investigation, above seems to work. Is this something that you are still running into?

**Comment by drumadrian** [comment]
Hey @sriram-mv  🤓 

  This request has been open for a while so I think the context of my original request is expired.  

I don't use the Serverless Application Model (SAM) anymore, so can't say if this is still an issue.  I was able to use your [help](https://github.com/aws/aws-sam-cli/issues/1899#issuecomment-605350252) in _May 2022_ to specify multiple values so I updated this request and finished my project. 

I think the request can be closed if all possible valid expressions of multiple capabilities are working:

For example: 

`capabilities = [ "CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND" ] 
`
 
Thank you for helping with this request.  I sincerely appreciate that Amazonians try their best to follow up on customer requests.  Let me know if you need anything else.  I don't mind jumping on a Chime call.  

Take care, 

Adrian

**Comment by jfuss** [comment]
Checked with the team! Yes, we can finally close this one out!
