### ISSUE TITLE
sam validate fails for cognito lambda trigger

### ISSUE THREAD

**Issue by mk0sojo** [aws/aws-sam-cli#1959]
### Description

When running the below sam validate or deploying the following template:

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
          - Name: verified_phone_number
            Priority: 2
      AutoVerifiedAttributes:
        - email
        - phone_number
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: true
        DeviceOnlyRememberedOnUserPrompt: true
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      EmailVerificationSubject: Cognito Confirmation
      EmailVerificationMessage: 'Your verification code is {####}.'
      EnabledMfas:
        - SMS_MFA
        - SOFTWARE_TOKEN_MFA
      MfaConfiguration: OPTIONAL
      Schema:
        - Name: family_name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: given_name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: phone_number
          AttributeDataType: String
          Mutable: true
          Required: true
      UsernameAttributes:
        - email
      UserPoolAddOns:
        AdvancedSecurityMode: ENFORCED

  PostSignupConfirmationLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: !Ref LambdaRuntime
      CodeUri:
        Bucket: !Ref Bucket
        Key: !Ref LambdaPostSignupConfirmationFunctionS3Key
      Handler: bin/index.handler
      Timeout: 20
      Events:
        PostConfirmationEvent:
          Type: Cognito
          Properties:
            UserPool: !Ref UserPool
            Trigger: PostConfirmation

I get the following error Error: [InvalidResourceException('UserPool', 'property AccountRecoverySetting not defined for resource of type AWS::Cognito::UserPool')] ('UserPool', 'property AccountRecoverySetting not defined for resource of type AWS::Cognito::UserPool').

If I remove AccountRecoverySetting  I get the following error:

Error: [InvalidResourceException('UserPool', 'property EnabledMfas not defined for resource of type AWS::Cognito::UserPool')] ('UserPool', 'property EnabledMfas not defined for resource of 
type AWS::Cognito::UserPool')

If I remove EnabledMfas the validation passes. I can also make it pass removing the Events from the lambda.

### Steps to reproduce

Run sam validate on above template

### Observed result

sam validate --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
Template provided at 'C:\brokerid\test\template.yaml' was invalid SAM Template.
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam validate', 'duration': 4308, 'exitReason': 'InvalidSamTemplateException', 'exitCode': 1, 'requestId': '45693a59-2b0b-4cdc-9706-7431051aac55', 'installationId': '44afe8f0-166a-4450-b80c-b47b83621b23', 'sessionId': 'd244ff86-d510-4215-8543-3479bdcb1e62', 'executionEnvironment': 'CLI', 'pyversion': '3.7.6', 'samcliVersion': '0.41.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: [InvalidResourceException('UserPool', 'property AccountRecoverySetting not defined for resource of type AWS::Cognito::UserPool')] ('UserPool', 'property AccountRecoverySetting not defined for resource of type AWS::Cognito::UserPool')

### Expected result
Validation pass

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: 0.41.0

`Add --debug flag to command you are running`

**Comment by mk0sojo** [comment]
Looks like it is being fixed under #1506

**Comment by sriram-mv** [comment]
Closing this issue. One can also look at running `sam validate --lint` with the latest versions of AWS SAM CLI.
