### ISSUE TITLE
SAM not including swagger correctly?

### ISSUE THREAD

**Issue by hwhea** [aws/aws-sam-cli#2002]
### Description

In the AWS Console, if I take my swagger file and create an API based on that using AWS Console's import API feature I get an API Gateway that includes models (schema in Swagger) and properly structured integration requests. 

However, when I include the exact same swagger in my DefinitionBody in the sam yaml file, no models are created, and integration requests are simply changed to Lambda Proxy, where they are not when using the Console's import function.

Is this to be expected? Is there something I am missing?

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: tried Windows & Mac
2. `sam --version`: SAM CLI, version 0.50.0

**Comment by sriram-mv** [comment]
could you share the definition body you are using?

**Comment by sriram-mv** [comment]
Closing this, please re-open if necessary.
