### ISSUE TITLE
Reuse built packages for sam build & sam package

### ISSUE THREAD

**Issue by ronaldour** [aws/aws-sam-cli#2061]
### Describe your idea/feature/enhancement

The issue that I'm facing is that sometimes I make changes to the _template.yml_ file that doesn't require to build the lambda packages again (e.g. Changing env variables or functions properties) however to apply the changes we must run `sam build` which means that all the lambdas are going to be built again which increases the build time unnecessarily.
It would be nice if the SAM CLI could package the templates without rebuilding everything if it's not required

### Proposal

I have two ideas for it:

1. Allow the `sam package` command to reuse the already built packages (by `sam build`) to allow updates to the _template.yml_ file without rebuilding the lambdas. Currently if we build the lambdas using `sam build` we cannot modify the _template.yml_ file and run `sam package` because it is going to use the generated `template.yaml` under the _.aws-sam_ directory and if we specify `sam package --template` then it is not going to pick the already built packages so the lambdas would be deployed without the dependencies, so this would be a really useful feature.

2. Allow the `sam build` command to reuse the already built packages and build the lambdas only if the files for that specific lambda have changed. When we have multiple lambdas defined in the same template it's a waste of time to build all the lambdas when we have modified only one of them. We can also provide a `--force-build` option or something similar to force building all the lambdas if it's required by the user.

### Additional Details

I would like to discuss what are the options for this issue and I can offer myself to contribute creating a PR with a solution agreed by everyone

**Comment by mndeveci** [comment]
Hi Ronaldo,

Thanks for bringing this up. We are definitely aware of that is a pain point for our customers. As of now, build cleans everything and starts from scratch. And we would like to hear your ideas, so if you can compile a design document, we would be happy to review it for future works.

Thanks

**Comment by mndeveci** [comment]
SAM CLI 1.9.0 now supports builds with caching enabled, see https://github.com/aws/aws-sam-cli/releases/tag/v1.9.0
