### ISSUE TITLE
Support AWS::ApiGatewayV2::Api resources

### ISSUE THREAD

**Issue by brandonryan** [aws/aws-sam-cli#2067]
### Describe your idea/feature/enhancement
sam-cli currently supports using `AWS::Lambda::Function` and `AWS::ApiGateway::RestApi`
It would make sense for it to also support `AWS::ApiGatewayV2::Api` without the need for the serverless version

### Proposal
Add Resource types and logic to [cfn_api_provider](https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/lib/providers/cfn_api_provider.py)

**Comment by brandonryan** [comment]
Id be happy to work on a pr for this if wanted

**Comment by WinterYukky** [comment]
I want this because I want to use the `aws-cdk`.
How about create a cfn_api_v2_provider?

**Comment by brandonryan** [comment]
That would be fine too.

**Comment by brandonryan** [comment]
Closing this because it seems to be supported now
https://github.com/aws/aws-sam-cli/commit/ea88b90118ae6604229fdf8245c0df10df9011a7#diff-1be35e00e63d07d9574da74bb34236ca28e2fc9c7a4ce26ca83fd6ec2ce0d418
