### ISSUE TITLE
Hash during package uses absolute paths

### ISSUE THREAD

**Issue by anvar** [aws/aws-sam-cli#2110]
### Description

I noticed that the code used to compute the hash for a lambda CodeUri hash uses the absolute filepath when calculating the hash [1]. This has some potentially uninteded consequences when running on a build farm such as CodeBuild as the build directory is ephemeral and changes between each build. This results in the lambda function being deployed every time, even when nothing has changed except for the build root directory. My proposal is to change it so that it takes the filepath relative to the root directory into account instead of the absolute one as per below:

From:
`md5_dir.update(filepath.encode("utf-8"))`

To:
`md5_dir.update(os.path.relpath(filepath, directory).encode("utf-8"))`

[1] https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/lib/utils/hash.py#L60

### Steps to reproduce

1) Run `sam package ...` and take note of the generated hash
2) Move the build root directory to a different directory, whichout making any other changes
3) Run `sam package ...` and see that the hash has changed even though nothing in the lambda source directory changed

### Observed result

Hash changes

### Expected result

Hash remains the same as nothing inside of the lambda source directory has changed.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS X
2. `sam --version`: `0.53.0`

**Comment by sriram-mv** [comment]
Definitely open to getting a PR on this, relative path seems to make sense :)

**Comment by anvar** [comment]
Okay, great. Just thought I would check before setting up a local dev environment. Will submit shortly!

**Comment by mndeveci** [comment]
Fixed with https://github.com/awslabs/aws-sam-cli/pull/2163, waiting for the next release atm.

**Comment by mndeveci** [comment]
Released with [SAM CLI v1.2.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.2.0)
