### ISSUE TITLE
Allow copy .gitignore files

### ISSUE THREAD

**Issue by elefantelimpio** [aws/aws-sam-cli#2128]
I would like to know If there is any possibility to tell sam build command to copy files that are excluded via .gitignore

**Comment by awood45** [comment]
Can you expand a bit more on what runtime you're using and what you're trying to do?

**Comment by elefantelimpio** [comment]
Good morning @awood45 !

I'm using aws-sdk for nodeJS. I think It could be a great idea to tell **sam build** command to copy specific files to dist folder. Thanks in advance

**Comment by juakotorres** [comment]
I'm also having this issue, i need to exclude credentials but i need that sam build include those files. For example a json file with the database connection settings, i don't want to include this file on my git project but i want to sam build to include it.

Runtime: nodejs12.x 

Is there a way to configure sam build to include those files that are in .gitignore?

**Comment by CoshUS** [comment]
Closing as this is NPM related.
