### ISSUE TITLE
sam init workflow for layers

### ISSUE THREAD

**Issue by tim-pugh** [aws/aws-sam-cli#2131]
### Describe your idea/feature/enhancement

The sam cli command ' sam init ' is a great workflow, and I think having an additional selection (besides just runtimes) would be for layers.

For example:

sam init
Which template source would you like to use?
	1 - AWS Quick Start Templates
	2 - Custom Template Location
Choice: 1

Which runtime would you like to use?
	1 - nodejs12.x
	2 - python3.8
	3 - ruby2.7
	4 - go1.x
	5 - java11
	6 - dotnetcore3.1
	7 - nodejs10.x
	8 - python3.7
	9 - python3.6
	10 - python2.7
	11 - ruby2.5
	12 - java8
	13 - dotnetcore2.1
	14 - dotnetcore2.0
	15 - dotnetcore1.0
         16 - layer <-- Suggested addition

### Proposal

If we can get an idea of a starting point to hit the ground running on making this addition, I think following the similar processes for the runtime workflows could make this quick work.

The normal recommendations for creating layers is to spin up an EC2 instance, or of course just making a new template specifically for layers; however I think having it as a dedicated workflow would greatly simplify and speed up layer creations.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

I don't believe this is going to warrant an update to the SAM Spec as it's already in the spec; this is more along the lines of making it faster and more user friendly for users to create layers solely.

In addition to layers, having a documented workflow for the community at large to create new/modify "Quick Start Templates" could be a beneficial side effect. One such idea that comes to mind is enabling X-Ray in a workflow, which can be a bit more hands on when you need to define the API Gateway resource. A workflow could make it bit quicker.

**Comment by jfuss** [comment]
Thanks for the issue. This should be solved through our docs: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-layers.html or https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-layers.html. If either are not sufficient, please provide feedback through the docs site. 

Closing.
