### ISSUE TITLE
Custom version

### ISSUE THREAD

**Issue by eliecer2000** [aws/aws-sam-cli#2145]
Hello, I would like to make certain changes in a fork repository, but I have no idea how to install it to work in production, that is, to be able to tell my clients to install that personality version.

Thank you for your attention.

**Comment by jfuss** [comment]
@eliecer2000 Trying to understand a little deeper. Why do you want clients to install your version? Why not contribute said changes here so all customers could benefit?

**Comment by eliecer2000** [comment]
I would like to use the sam bootstrap command so as not to have to use sam deploy --guide since in the code that I give to the client I already specify the parameters in samconfig and I don't need him to modify them.

**Comment by CoshUS** [comment]
@eliecer2000 Method to install in production depends on your client's environment. SAM-CLI will work just fine if you package your version and let your clients run it with python. As for binary installation, there are different tools to build python projects for different OS. You can look into PyInstaller if that's what you want.
