### ISSUE TITLE
Defining region in template.yml file

### ISSUE THREAD

**Issue by pfdtk** [aws/aws-sam-cli#2156]
There are few lambda function defined in my template.yml file, some of them are designed to use in region ap-southeast-1, and some in us-east-1，so is it possible add a keyword `region` in template.yml so that the sam cli will upload the code to multiple region?

**Comment by timoschilling** [comment]
Based on the CloudFormation contains one `template.yml` can only be deployed into one region at a time. To solve your problem you need to split your functions into two `template.yml` files, one for each region.

**Comment by jfuss** [comment]
@pfdtk On `sam package|deploy`, we upload to the region that you are currently deploying to (specified through `--region`, `AWS_DEFAULT_REGION`, or region defined for the profile you are using). The way to upload to multiple regions is to run the `sam package` command in each region you want to deploy too. This is a common practice and allows you to control where things are uploaded too. All commands in SAM CLI (and I believe the same holds true in AWS CLI), do things on a region basis.

If you need to upload to many regions, then running `sam package|deploy` in that region is the pattern you want to use.
