### ISSUE TITLE
Sam build ignores the dist folder

### ISSUE THREAD

**Issue by hariharasudhan-nineleaps** [aws/aws-sam-cli#2179]
### Description
I am using sam application with nodejs, i will be using typescript and i have mentioned `dist` folder in `.gitignore` file, now when i run `sam build` the `dist` folder not copying to `.aws-sam` folder, but if i remove dist folder from `.gitignore` its copying correctly, how to resolve this issue

1. OS: Ubuntu
2. `sam --version`: 1.1.0

**Comment by omer-to** [comment]
I'm facing the same, why is that?

**Comment by ekingunoncu** [comment]
Probably they check .gitignore to minimize sam build to deploy to lambda.
Adding files array to my package.json like below resolved my issue.
`  "files": [
    "/dist"
  ],`
