### ISSUE TITLE
sam publish mangles the parameters in the UI when trying to deploy, it uses AWS::Events::Rule as a parameter group label 

### ISSUE THREAD

**Issue by rojomisin** [aws/aws-sam-cli#2182]
### Description
Publishing a SAR template using `sam publish`, w/ one of my resources being a `AWS::Events::Rule`, which whatever I name that event resource, ends up being the label that organizes the Parameters in the AWS Console UI when launching the published template.

### Steps to reproduce
- create a sam template w/ parameters
- add in an Events::Rule resource w/ a name
- publish the template
- try to consume the published template from the console/UI

### Observed result
![Screen Shot 2020-08-25 at 8 32 51 AM](https://user-images.githubusercontent.com/3313148/91203164-a7fcfd00-e6b7-11ea-8a65-67ebe88a4dd3.png)

```
...
  RTOEventRule:
    Type: AWS::Events::Rule
    Properties:
      RoleArn: !GetAtt RTORPORole.Arn
...
```

### Expected result
I am not specifying any grouping or parameter labels that are named "RTOEventRule" yet it's using that for some reason.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

I think this has to do w/ SAM/CFN not collecting the Event Rule resource Name/Header properly
![Screen Shot 2020-08-25 at 9 48 07 AM](https://user-images.githubusercontent.com/3313148/91204239-a2ec7d80-e6b8-11ea-950e-27eb6237b4c2.png)
![Screen Shot 2020-08-25 at 9 47 51 AM](https://user-images.githubusercontent.com/3313148/91204241-a4b64100-e6b8-11ea-8dc3-41b860a7dd9d.png)

1. OS: OS X 10.14.6
2. `sam --version`: 1.1.0

`Add --debug flag to command you are running`
command completes fine, but the one thing I think is causing this bug is that this resource is allowed to be nameless/headless...

**Comment by mingkun2020** [comment]
Hi rojomisin, I got a message from our premium support team said this is fixed. Is this issue has been resolved?

**Comment by CoshUS** [comment]
Closing as there is no response.
Feel free to reopen is there is further information or issue.
