### ISSUE TITLE
Sam Destroy

### ISSUE THREAD

**Issue by sriram-mv** [aws/aws-sam-cli#2191]
* Add a SAM CLI command to help destroy stacks that went into a `ROLLBACK_COMPLETE` state and are un-usable.

### Describe your idea/feature/enhancement

* Needs fleshing out.

### Proposal

Add details of how to add this to the product.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

**Comment by iRoachie** [comment]
Should this just do the functionality of [cloudformation delete-stack](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/delete-stack.html)?

**Comment by henrysingleton** [comment]
Could this be similar to the `--on-failure` option for cli command `aws cloudformation create-stack`, where you could specify  DO_NOTHING, ROLLBACK, DELETE? Or does SAM have to deal with other more complex edge-cases?

**Comment by KyleTryon** [comment]
> Should this just do the functionality of [cloudformation delete-stack](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/delete-stack.html)?

Adding to this why it might be useful to duplicate this functionality: In a CI environment, you may not have the AWS CLI installed/configured if the sam cli is all that is needed.

**Comment by KylePeterDavies** [comment]
This is frustrating that there is no sam destroy / delete command.

**Comment by KylePeterDavies** [comment]
> > Should this just do the functionality of [cloudformation delete-stack](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/delete-stack.html)?
> 
> Adding to this why it might be useful to duplicate this functionality: In a CI environment, you may not have the AWS CLI installed/configured if the sam cli is all that is needed.

It is also more complexity for those who starting with the cloud, I've gone from needing AWS SAM, to needing AWS CLI

**Comment by xpdable** [comment]
I meet similar scenario while I put all our SAM thing to CICD. Once `sam deploy` failed the stack as `ROLLBACK_COMPLETE`, the next deploy will be stucked. 
The most frustrated thing is it would be just fine to delete the stack either manually or via cli if it is the initial deploy. Meaning that you do not have any existing resource deployed before. Then the deletion of the stack impacts nothing.
However, if the failed occurs on existing (non-initial) deployed stack, the deletion will cause resource deletion as well. It breaks the concept of what we are chasing of CICD.
Any suggestion guys?

**Comment by osulli** [comment]
+1

I'd also add a use-case is simply tidying up an environment, be it an ephemeral or slightly more persistent testing environment.

--

Official(?) solution is to delete the CloudFormation Stack either via AWS Console or the IDE AWS Toolkit plugins (which I can recommend).

**Comment by jfuss** [comment]
Released (as `sam delete`) in [v1.29](https://github.com/aws/aws-sam-cli/releases/tag/v1.29.0)

Closing
