### ISSUE TITLE
Multiple SAM templates deployed to one emulator

### ISSUE THREAD

**Issue by elenasch** [aws/aws-sam-cli#2196]
### Describe your idea/feature/enhancement

I have multiple teams developing lambdas. Each has their own SAM template spec. 
It would be nice be able to deploy multiple CF stacks (multiple SAM templates) on to one emulator. 
When devs develop locally, they  may need to run a bigger applications that potentially is talking to multiple CF stacks with lambdas. So instead of developers having to start an emulator for each template, they could start one emulator and deploy multiple templates to it

**Comment by wchengru** [comment]
Could you please explain more about this? Some example templates would also be helpful. Thanks!

**Comment by mingkun2020** [comment]
Closing. Feel free to reopen if there is more information on this issue.
