### ISSUE TITLE
Package Layer: No such file or directory

### ISSUE THREAD

**Issue by destinyb-realityi** [aws/aws-sam-cli#2202]
### Description

I have a custom `AWS::Serverless::LayerVersion` in my SAM local template used to add the `git` binary to my docker container. However, when I go to run `sam package ...` I'm getting an error that it cannot upload the artifacts because files do not exist. I have determined this is a problem with the symbolic links created when running `sam build` but I'm not sure how to get around this.

### Observed result

```
Error: Unable to upload artifact dependencies/ referenced by ContentUri parameter of GitLayer resource.
[Errno 2] No such file or directory: '/Users/destinybonavita/Desktop/Projects/test/dependencies/lib/libnssckbi.so'
```

### Expected result

Package to be packaged and uploaded to S3

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS latest
2. `sam --version`: 0.48.0

**Comment by CoshUS** [comment]
@destinyb-realityi Can you try using the latest SAM CLI version(1.2.0) and check whether this issue still exists?

**Comment by destinyb-realityi** [comment]
Hi @CoshUS, I'm having the same issue with 1.2.0

**Comment by awood45** [comment]
Can you explain more about how you constructed this layer? I'd like to attempt to recreate this, but I don't have enough information with which to recreate this. How can I construct a layer like you did, so that I can try to locally reproduce this in my own template?

**Comment by CoshUS** [comment]
Closing as this issue is blocked without more details.
Feel free to leave more information below and I can reopen this issue.
