### ISSUE TITLE
 Failed to install AWS-SAM-CLI on AWS Linux

### ISSUE THREAD

**Issue by rmundkowsky** [aws/aws-sam-cli#2214]
### Description

sam fails to run after being installed.

### Steps to reproduce

sam --version

### Observed result

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'aws-sam-cli==1.2.0' distribution was not found and is required by the application
### Expected result

SAM CLI, version 1.2.0

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Amazon Linux 2
2. `sam --version`: this fails, but i am guessing 1.2.0

**Comment by wchengru** [comment]
This may happens when multiple version are installed at the same time.
Can you provide how you install aws-sam-cli and python3.7? For example, install by brew, and the steps you install them.
If you install through brew, can you please try reinstall them?

**Comment by starpebble** [comment]
I agree, the aws-sam-cli installation process is crippled on amazon linux.  I don't have an official fix.  Please kindly consider this procedure to work around the problem.  The problem to work around is that brew installs sam-cli and configures it to use the exact python version also installed by brew.  Here's are unofficial instructions to configure aws-sam-cli to uses python3.7:

1. Install homebrew on amazon linux (done)
1. Install aws-sam-cli , `brew tap aws/tap` `brew install aws-sam-cli` (done)
1. Force reinstall python@3.7 with homebrew `brew reinstall python@3.7`
1. Check version, `sam --version` and expect 1.2.0

brew executes these commands upon `brew reinstall python@3.7` - the following commands reinstall the aws-sam-cli.  The brew reinstallation configures aws-sam-cli to use python 3.7.
```
==> Reinstalling aws/tap/aws-sam-cli 
==> python3.7 -c import setuptools... --no-user-cfg install --prefix=/tmp/aws-sam-cli--homebrew-virtualenv-20200912-5317-32re1x/target --ins
==> python3.7 -s /tmp/aws-sam-cli--homebrew-virtualenv-20200912-5317-32re1x/target/bin/virtualenv -p python3.7 /home/linuxbrew/.linuxbrew/Ce
==> /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.2.0/libexec/bin/pip install pip==19.2.3
==> /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.2.0/libexec/bin/pip install -v --ignore-installed /tmp/aws-sam-cli-20200912-5317-1yy81is
==> /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.2.0/libexec/bin/pip uninstall -y aws-sam-cli
==> /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.2.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/aws-s
```

**Comment by rmundkowsky** [comment]
running "brew reinstall python@3.7" seems to have fixed it.

**Comment by starpebble** [comment]
@rmundkowsky Neat. Happy trails. The simple workaround is kinda like the hidden arts of brew.

**Comment by sriram-mv** [comment]
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html has a native installer for Linux. This is based off Pyinstaller and does not have a brew dependency.
