### ISSUE TITLE
SAM guided deploy does not respect AWS Region set in config file

### ISSUE THREAD

**Issue by rts-rob** [aws/aws-sam-cli#2230]
### Description

Briefly describe the bug you are facing.

When using guided deploy with `sam deploy --guided`, AWS SAM CLI does not respect the AWS Region set in the config file. This requires the user to manually enter the Region on every first deploy, placing an unnecessary mental burden on the developer. This can result in the unintended deployment of applications to _us-east-1_. This creates confusion for developers and a non-intuitive developer experience.

### Steps to reproduce

1. Create and activate an AWS profile with a default Region **other than** _us-east-1_ by running `aws configure` or manually editing _~/.aws/config_
1. Create an AWS SAM app with `sam init`
1. Change into the new app directory
1. [Optional depending on runtime and template] Run `sam build`
1. Run `sam deploy --guided`

### Observed result

SAM CLI presents: `AWS Region [us-east-1]: `

### Expected result

SAM CLI presents: `AWS Region [<profile Region>]: `

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: all
2. `sam --version`: SAM CLI, version 1.2.0

**Comment by singledigit** [comment]
+1

**Comment by awsjeffg** [comment]
The [docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html) don't explicitly cover what should happen here, what they do say instead is:

> region
>
 >   Set the region you want to deploy to. If you omit region, then the AWS SAM CLI will try to resolve the region through AWS profiles and then environment variables.

I think I agree, it seems reasonable that if a customer has set a default region via aws cli it would follow that SAM would try to discover and honor that intent. I'll dig a bit further and see what the original design intent was.

**Comment by mgrandis** [comment]
Fixed in 1.16

**Comment by DanCookeWillow** [comment]
What is the workaround for this? 

I cannot imagine a CF template that doesn't use at least AWS::Region, are we just supposed to hardcode these values if we want to use `sam local` ?

Would be amazing to get some kind of support

Surely its as simple as just reading AWS_REGION or AWS_DEFAULT_REGION when running locally?
