### ISSUE TITLE
Feature Request: Add X-Ray support to Step Function State Machine

### ISSUE THREAD

**Issue by marekq** [aws/aws-sam-cli#2231]
Description:

AWS recently released X-Ray support for Step Functions; https://aws.amazon.com/blogs/compute/introducing-aws-x-ray-new-integration-with-aws-step-functions/

The feature can be configured through CloudFormation, but the TracingConfiguration option to configure tracing is not present in SAM yet. It would be great if we can also deploy this through SAM CLI. 

CloudFormation docs; https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-statemachine-tracingconfiguration.html

AWS SAM docs; https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html

I'd be happy to issue a PR with the fix, but need to dig into how I could do this for SAM. If anyone has pointers on where to start, I'd be happy to hear your advice!

**Comment by CoshUS** [comment]
This integration is supported in our new [SAM release](https://github.com/aws/serverless-application-model/releases/tag/v1.27.0) and is in our SAM CLI roadmap for a future release.

**Comment by marekq** [comment]
Amazing, thanks for the quick response!
