### ISSUE TITLE
Outputs to show API endpoints

### ISSUE THREAD

**Issue by mikezang** [aws/aws-sam-cli#2238]
### Describe your idea/feature/enhancement
I use `aws-cli/2.0.5 Python/3.7.5 Windows/7 botocore/2.0.0dev9` with `SAM CLI, version 1.2.0`, when I defined as below:
> Outputs:
　ApiUrl:
   　　Description: "API Gateway endpoint URL for stag stage"
　　　Value:
　　　　Fn::Sub: https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${EnvType}

I got Outputs as below:
> Key　　　　 ApiUrl
Description　 API Gateway endpoint URL for stag stage
Value　　　　**_https://abcdefghi1.execute-api.ap-northeast-1.amazonaws.com/stag_**

### Proposal
I want to Outputs can show all of my API Gateway endpoints, like serverless run `serverless deploy -v` as below :
> Service Information
service: serverless-hello-world
stage: dev
region: us-east-1
api keys:
　None
_endpoints:
　**_GET - https://abcdefghi1.execute-api.ap-northeast-1./stag/hello-world
　GET - https://abcdefghi1.execute-api.ap-northeast-1./stag/hello-world2_**
functions:
　**_helloWorld: serverless-hello-world-dev-helloWorld
　helloWorld2: serverless-hello-world-dev-helloWorld2_**

Things to consider:
1. May I get what I need in current version SAM?
2. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

**Comment by forgivegod** [comment]
See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html

**Comment by mikezang** [comment]
I read it but I still don’t know how to do it, can you show me a example here?

**Comment by sriram-mv** [comment]
These are outputs that are defined in your template file, you can create outputs as you require them to be in the template. SAM CLI only looks at outputs within the template file and showcases them. It does not have any logic to reconstruct outputs based on the content of the template itself.

**Comment by kaihendry** [comment]
If you have no changes to deploy, it's not possible to see the endpoints, right?

    Error: No changes to deploy. Stack XXXXXXXXX is up to date


Awful usability.

**Comment by forgivegod** [comment]
> Awful usability.

Since multiple way to get the outputs of a stack, I would disagree.  Please see the following, maybe they will be helpful:
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-exports.html#using-cfn-stack-exports-listing
- https://stackoverflow.com/questions/41628487/getting-outputs-from-aws-cloudformation-describe-stacks
