### ISSUE TITLE
sam package is not building template correctly

### ISSUE THREAD

**Issue by steveunixson** [aws/aws-sam-cli#2239]
### Description

template generated by sam package is invalid on Ubuntu 18.04

### Steps to reproduce

1. Use ubuntu 18.04
2. Install aws-sam-cli using pip
3. `sam package --s3-bucket bucket-name --output-template-file template-s3.yaml --profile profile-name`

### Observed result

template-s3.yaml

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: s3://------my code uri---------
      Runtime: nodejs12.x
      Timeout: 300
      MemorySize: 128

That's actually it. The file contains just that and nothing more!
### Expected result

it should be a valid AWS Cloudformation template

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 18.04
2. `sam --version`: SAM CLI, version 1.2.0

`Add --debug flag to command you are running`

Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
Sending Telemetry: {'metrics': [{'templateWarning': {'awsProfileProvided': True, 'debugFlagProvided': True, 'region': '', 'warningName': 'CodeDeployWarning', 'warningCount': 0, 'requestId': 'd99afa63-0548-4ad7-90f5-3a6824661364', 'installationId': '9f10dbaa-c755-4f72-9668-2b1ffecc7c0d', 'sessionId': '9a3d1cfb-119c-43f6-9a3c-585cbac0089d', 'executionEnvironment': 'CLI', 'pyversion': '3.6.9', 'samcliVersion': '1.2.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
File with same data is already exists at db4b14da03094fbdc7d1dfebbe18d990. Skipping upload

Successfully packaged artifacts and wrote output template to file template-s3.yaml.
Execute the following command to deploy the packaged template
sam deploy --template-file /home/unixson/Development/myapp/template-s3.yaml --stack-name <YOUR STACK NAME>

Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': True, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam package', 'duration': 5943, 'exitReason': 'success', 'exitCode': 0, 'requestId': '0d6fd199-e7a4-45b1-98ce-dbc1f24f2c7b', 'installationId': '9f10dbaa-c755-4f72-9668-2b1ffecc7c0d', 'sessionId': '9a3d1cfb-119c-43f6-9a3c-585cbac0089d', 'executionEnvironment': 'CLI', 'pyversion': '3.6.9', 'samcliVersion': '1.2.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)

**Comment by hawflau** [comment]
Hi @steveunixson, can you also provide the template that was used as the input?

**Comment by sriram-mv** [comment]
@steveunixson I'm not sure what you mean, sam package will change properties such that those artifacts referenced by them have now been uploaded to s3. It does give back a valid sam template. I'm not sure what you mean here.

I'm closing this issue, but feel free to re-open it if you feel there's something not right.
