### ISSUE TITLE
Brew install/upgrade currently broken for aws-sam-cli (1.3.1)

### ISSUE THREAD

**Issue by tljdebrouwer** [aws/aws-sam-cli#2247]
### Description

Brew upgrade doesn't work for aws-sam-cli

### Steps to reproduce

Use brew upgrade aws-sam-cli

### Observed result

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "aws-sam-cli"
Download failed: https://api.github.com/repos/aws/aws-sam-cli/tarball/v1.3.1

### Expected result

AWS SAM CLI is ssuccesfull  upgraded

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: OSX
2. `sam --version`: SAM CLI, version 1.0.0

**Comment by gautierdag** [comment]
I have the same problem with the install command `brew install aws-sam-cli`.

Which also points to `https://api.github.com/repos/aws/aws-sam-cli/tarball/v1.3.1` and to `https://github.com/aws/aws-sam-cli/releases/download/v1.3.1//aws-sam-cli-1.3.1.sierra.bottle.tar.gz` which both seem to be broken:

```
Downloading https://github.com/aws/aws-sam-cli/releases/download/v1.3.1//aws-sam-cli-1.3.1.sierra.bottle.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "aws-sam-cli"
Download failed: https://github.com/aws/aws-sam-cli/releases/download/v1.3.1//aws-sam-cli-1.3.1.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
...
Downloading from https://codeload.github.com/aws/aws-sam-cli/legacy.tar.gz/v1.3.1
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "aws-sam-cli"
Download failed: https://api.github.com/repos/aws/aws-sam-cli/tarball/v1.3.1
```

**Comment by tljdebrouwer** [comment]
I did work around this to modify the /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/bottle-configs/aws-sam-cli.json to point to v1.3.0 and run ```HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade aws-sam-cli```

**Comment by arnelenero** [comment]
> I did work around this to modify the /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/bottle-configs/aws-sam-cli.json to point to v1.3.0 and run `HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade aws-sam-cli`

This is a good workaround for now. Just need to modify the SHA value as well. Thanks.

**Comment by gautierdag** [comment]
> I did work around this to modify the /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/bottle-configs/aws-sam-cli.json to point to v1.3.0 and run `HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade aws-sam-cli`

Nice! Can confirm this workaround works for the install as well. 

For those not wanting to wait for the official fix:

You can replace `/usr/local/Homebrew/Library/Taps/aws/homebrew-tap/bottle-configs/aws-sam-cli.json` with:
```
{
    "version": "1.3.0",
    "url": "https://api.github.com/repos/aws/aws-sam-cli/tarball/v1.3.0",
    "sha256": "2f1cc3a2c26be40d64539749e1a51e4baf8ba31e40179278ff07e202f26ac8c6",
    "name": "aws-sam-cli",
    "bin": "sam",
    "bottle": {
        "root_url": "https://github.com/aws/aws-sam-cli/releases/download/v1.3.0/",
        "sha256": {
            "sierra": "fdf0f9f56c4b096a0c71e594a2c8f2cd3d9bb0e36106fbea6bea70eb57e5465c",
            "linux": "afbbcc5cef8b7fd3f2b0fb0d096b9983bb55dc7a91af3b840daa80e86e4d0958"
        }
    }
}
```
And run `HOMEBREW_NO_AUTO_UPDATE=1 brew install aws-sam-cli`

Not sure if HOMEBREW_NO_AUTO_UPDATE is actually needed ..  and obviously run this all at your own risk.

**Comment by superwoou** [comment]
I did install without HOMEBREW_NO_AUTO_UPDATE=1 and it worked!

> > I did work around this to modify the /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/bottle-configs/aws-sam-cli.json to point to v1.3.0 and run `HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade aws-sam-cli`
> 
> Nice! Can confirm this workaround works for the install as well.
> 
> For those not wanting to wait for the official fix:
> 
> You can replace `/usr/local/Homebrew/Library/Taps/aws/homebrew-tap/bottle-configs/aws-sam-cli.json` with:
> 
> ```
> {
>     "version": "1.3.0",
>     "url": "https://api.github.com/repos/aws/aws-sam-cli/tarball/v1.3.0",
>     "sha256": "2f1cc3a2c26be40d64539749e1a51e4baf8ba31e40179278ff07e202f26ac8c6",
>     "name": "aws-sam-cli",
>     "bin": "sam",
>     "bottle": {
>         "root_url": "https://github.com/aws/aws-sam-cli/releases/download/v1.3.0/",
>         "sha256": {
>             "sierra": "fdf0f9f56c4b096a0c71e594a2c8f2cd3d9bb0e36106fbea6bea70eb57e5465c",
>             "linux": "afbbcc5cef8b7fd3f2b0fb0d096b9983bb55dc7a91af3b840daa80e86e4d0958"
>         }
>     }
> }
> ```
> 
> And run `HOMEBREW_NO_AUTO_UPDATE=1 brew install aws-sam-cli`
> 
> Not sure if HOMEBREW_NO_AUTO_UPDATE is actually needed .. and obviously run this all at your own risk.

I did install without HOMEBREW_NO_AUTO_UPDATE=1 and it worked!

**Comment by mingkun2020** [comment]
Hi @tljdebrouwer , @gautierdag, @arnelenero and @superwoou ,

Thanks for reporting this issue, we were in middle of our release when we ran into another issue. We have rolled back to sam cli v1.3.0 and fixed brew tap for now. Feel free to reopen it if this happens again.

**Comment by joshua-bestor-sp** [comment]
Hi, I am getting this error today @mingkun2020

**Comment by mingkun2020** [comment]
@joshua-bestor-sp We just completed the release, could you try it again?
