### ISSUE TITLE
Build Images (ECR/Docker) Format & Resources Included

### ISSUE THREAD

**Issue by metaskills** [aws/aws-sam-cli#2254]
During the 1.0 release I noticed the local invoke (and start api) as well as the build images were moved from Michael's `lambci/lambda:build-${runtime}` Docker images to ones located at `amazon/aws-sam-cli-build-image-${runtime}`. One difference I noticed is that these new images lack the AWS SDK installed as a global package. I found this high level tools useful for abstract tooling around the development, test, and build/deploy cycles. Sure, each application can (and should) package their own deps for the runtime - but I think having these packages as global tools for build images has been helpful in the past and may be for others that were used to that feature. Thanks!!!

cc @TheRealJeffG

**Comment by awood45** [comment]
Can you tell me a bit more about how they're used? We definitely can add the SDKs (the build image source is in this repo and we'll even take PRs on them) to the build images, just want to understand the use case to make sure we can test it.

**Comment by metaskills** [comment]
Sure! I have two use cases now. All assume that I make use of the SAM containers heavily for dev & testing. Basically these containers are the complete working env. Which I think is a killer pattern for small to large functions. For small, unit tests frameworks are in the same env, for larger projects running the development server is isolated to that system (again in the container) like express or rails server. So the use cases

The first is around Rails application's building. In this scenario we do a few things. One is use `aws ssm` for the rails master encryption key. The other is `aws s3 sync` for compiling assets. Seen here at these doc links below. Right now the AWS CLI is on these images. However, I am calling them out here because at one time I was doing these in Ruby via the SDK and my preference is the CLI when I can.

* https://lamby.custominktech.com/docs/environment_and_configuration
* https://lamby.custominktech.com/docs/asset_host_and_precompiling

The other is around is around Lambda Layers, again to facilitate a fully working /opt directory in said containers for local development. In this process in our `bin/bootstrap` convention we will do similar work as in the Lambda Builders but in a Ruby script to a) parse the template.yaml b) instantiate a lambda client c) get the layer download link d) download it and uncompress to the container. This is done in Ruby using the SDK. So far this is my only use case. Even in our Node projects we use the Ruby container since YAML parsing is build into the language.

So ultimately if SAM provided a hook to do the same things builders were doing in the container, I would not need the SDK. Likewise, I'm not able to move this use case to the CLI because most of the work is parsing the template.yaml. Hope that helps!

**Comment by metaskills** [comment]
Today while updating for the Lamby cookiecutter for Lambda Container usage I noticed our new fancy ECR images like `public.ecr.aws/lambda/${runtime}` and was hoping that maybe the SAM tools were going to unify on AWS' new public registry. Instead, I found that these two formats are used.

* `amazon/aws-sam-cli-build-image-${runtime}`
* `amazon/aws-sam-cli-emulation-image-${runtime}`

Where `build` and `emulation` are the distinction I was looking for. Since my needs want to use these "build" images as development image in Rails Lambda projects I would like to ask the following:

#### 1) Will these build images be updated to match the emulation? 

For example, I noticed the build image here has not been updated in 22 days but the runtime/emulation was updated hours ago. Which may be fine,  but wanted to ask.

* https://hub.docker.com/r/amazon/aws-sam-cli-build-image-ruby2.7
* https://hub.docker.com/r/amazon/aws-sam-cli-emulation-image-ruby2.7

#### 2) Will the Docker hub images be discontinued? 

I think it would help newcomers working with these images if they were all on ECR. In this case I would hope to find the build variants on there too. So for example:

* `public.ecr.aws/lambda/build-${runtime}`
* `public.ecr.aws/lambda/${runtime}`

This would mirror the previous lambci setup and I think help developers like myself use these as needed in different ways. I can provide working examples when I finish updating Lamby to use containers. 

* lambci/lambda:build-ruby2.7
* lambci/lambda:ruby2.7

**Comment by metaskills** [comment]
Was just poking around on some of the tooling in these images to highlight their update frequency.

```
$ dk-lbash amazon/aws-sam-cli-build-image-ruby2.7
bash-4.2# sam --version
SAM CLI, version 1.9.0
```

```
$ dk-lbash lambci/lambda:build-ruby2.7
bash-4.2# sam --version
SAM CLI, version 1.11.0
```

**Comment by omenking** [comment]
@metaskills is `lambci/lambda` and `amazon/aws-sam-cli-build-image` the same thing?

> the build images were moved from Michael's lambci/lambda:build-${runtime} Docker images to ones located at amazon/aws-sam-cli-build-image-${runtime}

I am currently trying to build my own containers. I have to do this because I need to install a bunch of python data science libraries that won't fit within Lambda Layers.

I am confused why SAM is not using `public.ecr.aws/lambda/${runtime}`. I wish AWS would just only have one way. I suppose Docker Hub could act as an alternative repository in-case ECR was ever down? 🤷‍♂️

**Comment by metaskills** [comment]
Hey Andrew! It is important to remember that SAM has two types of images depending on the command you run. Most commands use the "runtime" image which mimics the real runtime. But `sam build` uses the "build" images. 

In most cases the "runtime" images are the same as the ones on the public ECR. But, right now there is no public ECR image that has an equivalent of "built" which includes compile tools, etc. on them. 

My preference would be both "runtime" and "build" be on public ECR. If I were you and building deps, I would use a multi-stage docker process and use the "build" image, then copy your packages, etc (opt dir) into the "runtime" image. Hope the helps.

**Comment by hoffa** [comment]
We now publish build images to the [ECR Public Gallery](https://gallery.ecr.aws/?page=1&searchTerm=sam&verified=verified) (e.g. `public.ecr.aws/sam/build-python3.8`).

**Comment by mr-davidc** [comment]
Hi @hoffa,

Do you know if there are any plans to also publish the official SAM build images to Docker Hub? The only reason I ask is that the company I work for uses Bitbucket Pipelines as their CI/CD tool and from what I can tell, Bitbucket Pipelines internally only caches public images pulled from Docker Hub.

Thanks
