### ISSUE TITLE
Keep a public archive of old `amazon/aws-sam-cli-build-image-*` on Docker Hub

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-sam-cli#2255]
### Describe your idea/feature/enhancement

Is this the project that produces `amazon/aws-sam-cli-build-image-*` images on Docker Hub?

I wish that the project kept a public Docker Hub archive of previously built and released images. As it stands, there is only a `latest` tag available in the [python 3.7 tag list](https://hub.docker.com/r/amazon/aws-sam-cli-build-image-python3.7/tags). I wish that I could pull an image that is at least a few weeks older. This would help me when reproducing builds and when getting to the bottom of certain build errors.

For instance, in PR aws/aws-cdk#9582, while searching for the cause of a `pip install` reproducibility problem, I needed to see what would happen when using an older version of `amazon/aws-sam-cli-build-image-python3.7`. By chance, I was able to find a six-week-old copy of the image kicking around. I was able to save the image from one computer and transfer it to another to determine the nature of the asset hash change. If there were a public archive of less recently built images, I wouldn't need to be so lucky.

### Proposal

I would suggest that the project provide additional tags for the docker images that are pushed up rather than providing only a `latest` image tag. If the images are released with the sam cli itself, then maybe the images can have the same versioning convention? Otherwise, perhaps the date could be encoded into tag names.

### Additional Details

None that I can think of.

**Comment by hoffa** [comment]
FWIW, the images on ECR Public are tagged: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-image-repositories.html
