### ISSUE TITLE
Unable to install the msodbcsql17 , mssql-tools

### ISSUE THREAD

**Issue by ragasivasankar** [aws/aws-sam-cli#2256]
### Description
I am trying to install the msodbcsql ,mssql-tools to connect to mssql using sam build. it throws the exception.  Could not satisfy the requriment: msodbcsql

Briefly describe the bug you are facing.

### Steps to reproduce
1.In the requirments.txt for add the msobdcsql17 file.
2. run the sam build

Provide steps to replicate.

### Observed result

Please provide command output with `--debug` flag set.

### Expected result

Describe what you expected.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:1.3.2

`Add --debug flag to command you are running`

**Comment by aahung** [comment]
Hi @ragasivasankar, can you provide information about your OS version, the content of requirements.txt and the full error message?

**Comment by CoshUS** [comment]
Closing.
Feel free to reopen is there is further information or issue.
