### ISSUE TITLE
Unable to deploy successfully when using S3 access point

### ISSUE THREAD

**Issue by SurrealTiggi** [aws/aws-sam-cli#2261]
## Description

Not sure if this a bug per se, or just a lacking feature due to CloudFormation limitations. Basically, I use sam to deploy resources to multiple AWS accounts, but was wondering if a central S3 bucket can be used for artifacts.
SAM itself logs an expected regex to `--s3-bucket` that seems to support S3 access points.

### Steps to reproduce

* Create a simply sam template
* Configure a public S3 bucket with an access point
* Attempt to deploy

I attempted to create this within the same AWS account. Running `sam deploy` with `--s3-bucket <local_bucket_name>` deploys successfully.

### Observed result

```
$ sam deploy --debug --stack-name test-stack --capabilities CAPABILITY_IAM --s3-bucket arn:aws:s3:eu-west-1:<aws_account_id>:accesspoint/<accesspoint_name> --s3-prefix test

	Deploying with following values
	===============================
	Stack name                 : test-stack
	Region                     : eu-west-1
	Confirm changeset          : False
	Deployment s3 bucket       : <same as above>
	Capabilities               : ["CAPABILITY_IAM"]
	Parameter overrides        : {}

Initiating deployment
=====================
No Parameters detected in the template
1 resources found in the template
Found Serverless function with name='TestFunc' and CodeUri='.'
Uploading to test/123456789abcdefghijklmnopqrstuvwxyz.template  591 / 591.0  (100.00%)

Error: Failed to create changeset for the stack: test-stack, An error occurred (InternalFailure) when calling the CreateChangeSet operation (reached max retries: 4): Unknown
```

### Expected result

Stack is successfully created, with artifacts stored in a central S3 bucket

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
Mac
2. `sam --version`:
SAM CLI, version 1.2.0

**Comment by jfuss** [comment]
This appears to be an issue from CloudFormation as the upload was successful, from looking at the logs. If you are still hitting this issue, I would encourage you to contact AWS Support.

Closing as this is a service issue not CLI.
