### ISSUE TITLE
Globals --> Support Fn::Transform

### ISSUE THREAD

**Issue by spiffcs** [aws/aws-sam-cli#2267]
### Describe your idea/feature/enhancement

Earlier versions of SAM CLI (0.47.0) used to support the following:
```
Globals:
  Fn::Transform:
    Name: AWS::Include
      Parameters:
        Location: !Sub
          - s3://{EnvironmentURL}/function_globals.yaml
          - { EnvironmentURL: !Ref EnvironmentURL }
```
```
# function_globals.yaml
Function:
  Tags:
   ......
  Environment:
  .......
  VpcConfig:
  ..........
```
### Proposal

Update validation array of `['API', 'Function', 'HttpApi', 'SimpleTable']` to allow cloudformation functions that import files from remote sources. 

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

I think we can talk through this feature on this thread to formalize it in the spec.
If you pull down an older version you'll see this functionality already existed before the validation was added.

### Additional Details
Here is the schema from [serverless-application-model](https://github.com/aws/serverless-application-model/blob/develop/samtranslator/validator/sam_schema/schema.json)

I think we would have to update the spec to allow for cloudformation functions to be included as a valid sam document [here](https://github.com/aws/serverless-application-model/blob/1ba4e567901bf53f104f853fcdfae5fad7a2bda9/samtranslator/validator/sam_schema/schema.json#L1039-L1060)

If there is a better way to allow for `Fn::Transform` to be allowed in this section let me know.

**Comment by eugene-bright** [comment]
It looks like I have the same issue with `Type: AWS::Serverless::Api`:

```yaml
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: test.yaml
```

I'm getting error:

```log
"Unable to add Auth configuration because 'DefinitionBody' does not contain a valid Swagger definition."
```

Looks like `sam validate` doesn't bother to process `Fn::Transform`.

**Comment by eugene-bright** [comment]
The most interesting part is that I can't work it around by using `DefinitionUri`.

```log
"Auth works only with inline Swagger specified in 'DefinitionBody' property."
```

**Comment by spiffcs** [comment]
Checked back on this today and it's still gating on the swagger definition.

I'm going to close this issue for now since we've moved on from aws-sam-cli to other ways to organize our infrastructure, but if anyone does find this and has ideas on how to get things like `Fn::Transform` allowed by the swagger validation ping me here and I can maybe help.
