### ISSUE TITLE
sam build outputting node_modules folder when there are only devDependencies in package.json

### ISSUE THREAD

**Issue by danludwig** [aws/aws-sam-cli#2269]
### Description

The `sam build --use-container` command is generating a node_modules folder in the build output directory when the project's package.json contains only devDependencies. This only started happening today, builds yesterday did not output this folder, and nothing in the project has changed.

### Steps to reproduce

1. Create a new sam project with devDependencies chai and mocha, tests in src/tests/ folder, and .npmignore including `tests/*`.
2. Run sam build --use-container --debug on the project

### Observed result

Observe that the output folder ./.aws-sam/build/Function contains a node_modules folder with dependencies such as define-properties, es-abstract, es-to-primitive, function-bind, has, and others.

### Expected result

Expected the build output to not contain a node_modules folder, since the package.json includes zero prod dependencies, only two devDependencies. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:Both  Windows 10 and Ubuntu
2. `sam --version`: Both 0.38.0 (local windows 10 machine) and 1.1.0 (ubuntu running on codebuild standard/4.0 image)

`Add --debug flag to command you are running`

**Comment by anthony-tietjen-navex** [comment]
I was able to reproduce the issue.

Running sam build --debug against a node project with a package.json that only contains devDependencies creates a /.aws-sam/node_modules/ folder

From the output of sam build --debug I see that it runs the following

> npm install -q --no-audit --no-save --production --unsafe-perm

If I run that command in the same folder as the package.json then no node_modules folder is created.

**Comment by danludwig** [comment]
It smells like this is coming from the lambci container that sam is downloading and using to build. When I run this, it looks to be using the lambci/lambda/build-nodejs12.x image, which according to docker hub, was updated by @mhart a day ago. Michael, what was that update to the above image? It seems that npm install now has different behavior in with that image than it did on Wednesday 9/30/2020. Something is now not ignoring dev dependencies, and is putting a node_modules folder in the build output when it shouldn't (and wasn't before).

**Comment by mhart** [comment]
Oh, I thought aws-sam-cli wasn't using my images since v1.0.0

**Comment by mhart** [comment]
Btw, what version of `npm` are you using? If I run:

```
npm install -q --no-audit --no-save --production --unsafe-perm
```

On my mac, node v12.18.4, npm 6.14.8

It *does* install all dev dependencies.

This is because `npm install` doesn't have a `--production` flag. Only `npm ci` does.

**Comment by mhart** [comment]
The issue is with aws-lambda-builders I believe: https://github.com/aws/aws-lambda-builders/issues/200

**Comment by mhart** [comment]
Actually, scratch that. The docs *do* mention a `--production` flag further down. For some reason it's having no effect for me on node v12.18.4 and npm 6.14.8. Digging into why – but I can reproduce on my local machine for what it's worth

**Comment by anthony-tietjen-navex** [comment]
Found some more info. On MacOS, using node@12.14.0 and npm@6.13.4.

In a project that only has devDependencies, when I run the following command on my host machine and the package-lock.json file _does exists_, then the node_modules folder doesn't get created. But when I run it when the package-lock.json file _does not exist_, then the node_modules folder gets created. 

> npm install -q --no-audit --no-save --production --unsafe-perm

Then when I run sam build against a project that _does have_ a package-lock.json, I noticed that in the .aws-sam folder, the package-lock.json file doesn't exist. If there is no package-lock.json in the sam temp folder that would explain why the sam build function generates the node_modules folder, but we looked at an older copy of our .aws-sam output from Wednesday and it also doesn't have the package-lock.json file, so that doesn't explain why the behavior changed from Wednesday to Thursday.

**Comment by mhart** [comment]
It could be this? https://github.com/npm/cli/issues/1113

**Comment by mhart** [comment]
And so possibly either:

1. one of your dependencies has updated to include a shrinkwrap (or a dep with a shrinkwrap), or:
2. the recent update to node and npm in the Lambda images (it was updated to v12.18.4 in the last few days) has cause this bug to creep into npm

**Comment by anthony-tietjen-navex** [comment]
@mhart Looks like it might be more of a dependency thing. If I put mocha in devDependencies, then I get about 14 folders in the node_modules folder. But if I move mocha to the dependencies, then I get about 100 folders in node_modules.

If I put a smaller depdendency like "has" in devDependencies then node_modules doesn't get created.

**Comment by anthony-tietjen-navex** [comment]
Nothing in our devDependencies changed versions from one day to the next, but I suppose a sub-dependency in there could have changed to add a shrinkwrap. And the existence of package-lock.json in the repo, but lack of that package-lock.json in the .aws-sam output folder could help explain that.

**Comment by anthony-tietjen-navex** [comment]
Narrowing in. It's looking like a sub-dependency of mocha caused the change. I removed mocha and left my other devDependencies there and it didn't generate node_modules. As soon as I put mocha back into devDependencies the node_modules come back. (FYI, using mocha@8.1.3)

**Comment by mhart** [comment]
Yup, can reproduce – it's omitting `"dev": true` from some of the sub-dependencies in package-lock.json. See: https://github.com/npm/cli/issues/1113#issuecomment-702895055 for a "workaround"... sort of

**Comment by danludwig** [comment]
> Oh, I thought aws-sam-cli wasn't using my images since v1.0.0

You're right. Locally I am running 0.38.0, and at least some of our codebuild images seem to be running 0.48.0. I just logged `sam --version` to one of our buildspecs though, which used SAM CLI 1.1.0 and does in fact use a different image, `amazon/aws-sam-cli-build-image-nodejs12.x`.

I'm not sorry for @mentioning you though Michael, because you've pointed out the shrinkwrap issue which probably has something to do with this now that it's been narrowed to mocha devDependency being the culprit here. Appreciate that, thank!

**Comment by mhart** [comment]
Basically, try this: `npm install -D mocha es-abstract && npm rm es-abstract`

**Comment by mndeveci** [comment]
Hi @danludwig , @anthony-tietjen-navex , @mhart ,

Sorry for the inconvenience but looking at the https://github.com/npm/cli/issues/1113 issue, upgrading to npm v7 fixes this issue. I upgraded by running `npm install -g npm@7` and function's node_modules folder only has `.package-lock.json` file in it.

Please let us know if you have further issues on this

**Comment by CoshUS** [comment]
Closing as solution was provided in the previous comment.
Feel free to reopen if there is further issue on this topic.
