### ISSUE TITLE
[Question] Is it possible to connect to a database running on localhost?

### ISSUE THREAD

**Issue by pmtarantino** [aws/aws-sam-cli#2272]
Hello,

On my team we have several functions running on AWS lambda, and now we want to start testing locally instead of having to deploy everytime we want to test something.

I installing sam-cli, Docker, and finally I was able to make it work on my local (doing ```sam build``` and then ```sam local start-api```).

However, the database where these functions writes, are running on localhost (outside the docker machine where are being executed). If I try connecting using localhost, they fail because I suppose they are checking inside the Docker VM.

Is it possible to connect to the hosting machine database? If not, it would be really hard to debug these functions.

(I hope I made myself clear)

**Comment by pmtarantino** [comment]
By the way, I tried this https://github.com/aws/aws-sam-cli/issues/669  (both using ```--docker-network host``` and ```"host.docker.internal"```) and it didn't work (I am on Windows 10).

**Comment by sriram-mv** [comment]
@pmtarantino : what version of SAM CLI are you on? can you run your command with `--debug`. Can you explain what happens when it doesn't work, does it crash, does it stay stuck?

**Comment by pmtarantino** [comment]
Current version is 1.4.0. It says it cannot resolve domain name host.docker.internal.

**Comment by jfuss** [comment]
@pmtarantino `--docker-network host` will not work as you expected. On windows, this does not make the service running in the container able to talk to your machine's localhost. It is actually attaching the container running to the VM's localhost.

**Comment by make-ing** [comment]
I have the same problem running on Linux. We try to access services running on the locahost (outside of the container) with no success so far. The solution for running a docker container manualy with the option `--add-host host.docker.internal:host-gateway` works, but it seems not suported by sam. Is there another way to allow the container to access services running on the Linux host?

**Comment by nazShg48** [comment]
I have same problems. Can't connect to a PG that is running locally on Linux.
I tried different options for `--container-host-interface`, `--container-host`, `--docker-network`. No success.
SAM CLI, version 1.53.0

Without ability to connect to a local DB there is no sense to use SAM at all, for our team.
Any ideas how to fix this issue?

**Comment by nazShg48** [comment]
Downgraded SAM to 1.12.0 and `--docker-network host` works just fine. But it can not be a right solution to stay with outdated version, please fix this issue.

**Comment by asinghvi-aurora** [comment]
@jfuss Can this be re-opened? As @bluprince13 mentioned we cannot use `--add-host` with SAM CLI. `-add-host` is needed on Linux to set up `host.docker.internal` to point to the docker host.

**Comment by DiegoBri11** [comment]
@asinghvi-aurora Added in this PR https://github.com/aws/aws-sam-cli/pull/6078
