### ISSUE TITLE
Source code for /samcli/local/preview-rapid/init

### ISSUE THREAD

**Issue by mhart** [aws/aws-sam-cli#2283]
### Describe your idea/feature/enhancement

The new extensions support introduced a new rapid init binary:

https://github.com/aws/aws-sam-cli/blob/57ef28401ec58f7d79dca1835c4da27653c79bec/samcli/local/preview-rapid/init

But it doesn't look like the source code was included or linked to (that I could see)

### Proposal

Include the source code (and clarify the license if it's not Apache) in this repository, or link to the repository that has this source.

Thanks!

**Comment by awood45** [comment]
The license for the entire project, including that distributed binary, is Apache 2.0. The exception to this is the vended code in the `samcli/local/rapid` and `samcli/local/go-boostrap` folders, as specified in the `THIRD-PARTY-LICENSES` file. Third party dependencies of that binary are mentioned in the `THIRD-PARTY-LICENSES` file as well. We have not yet released the source code for that binary.

**Comment by jfuss** [comment]
Source code can be found in this repo: https://github.com/aws/aws-lambda-runtime-interface-emulator
