### ISSUE TITLE
Unable to debug golang function using dlv from AWS documentation (`GLIBC_2.32' not found)

### ISSUE THREAD

**Issue by tebruno99** [aws/aws-sam-cli#2294]
### Description

Unable to debug golang applications using sam local invoke following the documentation provided by AWS. glibc used to build dlv doesn't seem to be compat with the glibc in the docker image. sam build cannot build in a docker container so not sure what we are suppose to do about this.

### Steps to reproduce

```
mkdir delve
GOARCH=amd64 GOOS=linux go build -o delve/dlv github.com/go-delve/delve/cmd/dlv
GOARCH=amd64 GOOS=linux go build -o dlv github.com/go-delve/delve/cmd/dlv
sam local invoke CrmEntityImportWorkerFunction -e unittestdata/crmentityimporter/events/110791.event --profile=tbrunomind -d 5986 --debugger-path delve/ --debug-args "-delveAPI=2" --debug"
```

### Observed result

```
local invoke command is called
Collected default values for parameters: {'ENV': 'dev'}
...
...
...
Private data, just list of ENV vars and template values
..
...
19 resources found in the template
Found Serverless function with name='CrmEntityImportWorkerFunction' and CodeUri='./crm-entity-import-worker/'
....
...
....
(Private data, just a list of all functions)
...
...
...
...
Found one Lambda function with name 'CrmEntityImportWorkerFunction'
Invoking crm-entity-import-worker (go1.x)
Environment variables overrides data is standard format
Loading AWS credentials from session with profile 'mywork'
Resolving code path. Cwd=/home/tbruno/Projects/GolandProjects/lambda-crm-integration, CodeUri=./crm-entity-import-worker/
Resolved absolute path to code is /home/tbruno/Projects/GolandProjects/lambda-crm-integration/crm-entity-import-worker
Code /home/tbruno/Projects/GolandProjects/lambda-crm-integration/crm-entity-import-worker is not a zip/jar file
Image was not found.
Building image...Adding custom GO Bootstrap to support debugging
.........................
Failed to download image with name amazon/aws-sam-cli-emulation-image-go1.x:debug-1.6.2
Failed to download a new amazon/aws-sam-cli-emulation-image-go1.x:debug-1.6.2 image. Invoking with the already downloaded image.
Mounting /home/tbruno/Projects/GolandProjects/lambda-crm-integration/crm-entity-import-worker as /var/task:ro,delegated inside runtime container
Setting up SIGTERM interrupt handler
/tmp/lambci_debug_files/dlv: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/lambci_debug_files/dlv)

```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: ArchLinux/Manjaro
2. `sam --version`: SAM CLI, version 1.6.2

**Comment by mndeveci** [comment]
Hi @tebruno99 ,

Can you provide the link of the documentation that you followed?

**Comment by tebruno99** [comment]
This is the documentation:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-debugging-golang.html

This problem seems larger than that though. It seems that new Distributions will be breaking GLIBC compat or the Lambda images are broken somehow. 

I get the same error if I build locally and sam deploy directly into AWS.  AWS Lambda reports that my lambda cannot be run because `GLIBC_2.32` not found.

**Comment by tebruno99** [comment]
This may be one of those cases like a few of my other reported bugs that adding Go to be able to build in a container would be the "real" solution for compatibility.

**Comment by mndeveci** [comment]
Hi @tebruno99 ,

Thanks for the link. I followed the steps there on OSX and on a Manjaro instance on VM (XFCE edition from their website), but both builds successfully run and I was able to debug the application. I tested with HelloWorld example.

Could this issue be related to one of the dependencies that your are using for your example? Can you give us an example that we can re-produce?

Thanks

**Comment by tebruno99** [comment]
Hrm, I don't have any imports but standard library. The problem went away when I switched to Ubuntu but I didn't keep the Manjaro instance around to further testing.

Thanks for the testing, I will reinstall Manjaro to see if I can verify it still happening.

**Comment by tebruno99** [comment]
@mndeveci When you did the Majaro tests did you install sam cli via linuxbrew or by pip3 ?

**Comment by mndeveci** [comment]
@tebruno99 I installed through linuxbrew

**Comment by CoshUS** [comment]
Closing.
Feel free to reopen is there is further information or issue.

**Comment by tebruno99** [comment]
This is now a much wider issue with most distributions moving to the newer 3.32 version of glibc. Confirmed on Fedora 35, Ubuntu 21.10 and latest Arch & Manjaro installs.

We really need Go apps to be built in containers that contain a compatible lambda glibc version.  This issue is not limited to aws-sam-cli.  Any Go binary built on one of these newer distribution builds using glibc 2.32 or later will fail to run on any docker image or linux distro that uses glibc 2.31 or earlier.

**Comment by nathanjisaac** [comment]
I'm on Fedora 33 and I ran into this issue while building with `sam build`. I was able to fix this by passing the `--use-container` flag. 

```shell
sam build --use-container
```

For simplicity, I added it to the make file generated by the hello world example. 

```make
.PHONY: build

build:
	sam build --use-container
```

**Comment by MicahParks** [comment]
This affects me on Ubuntu 21.04.

Using `sam build --use-container` is not supported for Golang Lambdas.
> Build Failed
> Error: We do not support building Go Lambda functions within a container. Try building without the container. Most Go functions will build successfully.

Even if support is added in the future for Golang Lambdas, it won't be able to use it because of this issue: https://github.com/aws/aws-sam-cli/issues/2510

:cry:

**Comment by tebruno99** [comment]
Using AWS SAM 1.37.0 I've been able to use `sam build --use-container` to build, test, and deploy go builds correctly.

**Comment by kaihendry** [comment]
One fix is to pass `CGO_ENABLED=0` to the go build, but that can only be done with the `BuildMethod: makefile`

The Go quickstart UX is pretty dreadful with AWS SAM currently. https://gist.github.com/kaihendry/99b138f7ee41190f781697c6d1122c67

**Comment by kaihendry** [comment]
You're welcome to try my project https://github.com/kaihendry/gotestaws for a sanity test @ivan-pesenti

**Comment by andrewbohm** [comment]
I am running into the same issue @ivan-pesenti is facing.  Anyone get debugging working with vscode?

**Comment by ImDevinC** [comment]
Has anyone figured out a solution here? I have a project I can build/run on Windows without issue, but when trying to do the same on linux (using `sam local start-api`) I keep getting the same glibc error. I'm assuming this is because my OS is using a newer version of GLIBC than the sam docker image supports, but I'm unsure of how to update the image to include the new glibc version. Thanks in advance.

**Comment by jfuss** [comment]
Looking at the latest comments this is resolved by building directly within a container (`sam build --use-container`).

Closing but if there is still an issue, please create a new Github Issue.
