### ISSUE TITLE
Hello World Example Fails to Build with NodeJS 12.x Runtime

### ISSUE THREAD

**Issue by AJStacy** [aws/aws-sam-cli#2298]
### Description

After initializing a new project with the SAM cli for Hello World using Nodejs12.x the project fails to build because it cannot find the template file. I believe the issue is because the template file is name `.yaml` but the build command is looking for a `.yml`.

### Steps to reproduce

1. `sam init`
2. Select choice #1 - AWS Quick Start Templates
3. Select runtime #1 - nodejs12.x
4. Project name: sam-app
5. Template selection #1 - Hello World Example
6. `sam build`

### Observed result

```
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 8, 'exitReason': 'TemplateNotFoundException', 'exitCode': 1, 'requestId': 'd5f7bbbf-860a-4bf2-a067-9e31d4273ceb', 'installationId': 'c879fdfa-2137-4cb9-a114-6fb155221db5', 'sessionId': '23262068-a578-4774-a502-072ada28e975', 'executionEnvironment': 'CLI', 'pyversion': '3.8.6', 'samcliVersion': '1.6.2'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Template file not found at /Users/ndstc/Projects/work/bootcamp/helloWorld/template.yml
```

### Expected result

Expected the template to build a hello world app for deployment.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS Catalina 10.15.7
2. `sam --version`: 1.6.2

**Comment by prenx4x** [comment]
We check for both yaml and yml. Can you try to cd into the new init template you downloaded and then build again?

**Comment by CoshUS** [comment]
Closing. Feel free to reopen if there is more information on this issue.
