### ISSUE TITLE
sam package --s3-bucket <ARN> fails

### ISSUE THREAD

**Issue by Ruben-Sh** [aws/aws-sam-cli#2300]
### Description
When using the SAM CLI package command, the --s3-bucket flag throws an error when attempting to use an ARN. The command works correctly when using just the bucket name. Is there a feature missing here, bug or is this user error from my side?

### Steps to reproduce

Example
$ aws s3 ls | grep case-7490961421$                       
X X case-7490961421

$ sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket arn:aws:s3:::case-7490961421
Error: Unable to upload artifact functions/ referenced by CodeUri parameter of TransformPartFn resource.
Parameter validation failed:
Invalid bucket name "arn:aws:s3:::case-7490961421": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$"

When using the ARN matching regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$" I receive the following error:

$ sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket arn:aws:s3:ap-southeast-2:account number:accesspoint/case-7490961421                   
Error: Unable to upload artifact functions/ referenced by CodeUri parameter of TransformPartFn resource.
An error occurred (NoSuchAccessPoint) when calling the PutObject operation: The specified accesspoint does not exist

### Observed result

$ sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket arn:aws:s3:ap-southeast-2:account number:accesspoint/case-7490961421 --debug

Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
Sending Telemetry: {'metrics': [{'templateWarning': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'ap-southeast-2', 'warningName': 'CodeDeployWarning', 'warningCount': 0, 'requestId': 'x', 'installationId': 'x', 'sessionId': 'x', 'executionEnvironment': 'CLI', 'pyversion': '3.8.6', 'samcliVersion': '1.6.2'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Sending Telemetry: {'metrics': [{'templateWarning': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'ap-southeast-2', 'warningName': 'CodeDeployConditionWarning', 'warningCount': 0, 'requestId': 'x', 'installationId': 'x', 'sessionId': 'x', 'executionEnvironment': 'CLI', 'pyversion': '3.8.6', 'samcliVersion': '1.6.2'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Unable to export
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/lib/package/artifact_exporter.py", line 270, in export
    self.do_export(resource_id, resource_dict, parent_dir)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/lib/package/artifact_exporter.py", line 286, in do_export
    uploaded_url = upload_local_artifacts(resource_id, resource_dict, self.PROPERTY_NAME, parent_dir, self.uploader)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/lib/package/artifact_exporter.py", line 155, in upload_local_artifacts
    return zip_and_upload(local_path, uploader)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/lib/package/artifact_exporter.py", line 173, in zip_and_upload
    return uploader.upload_with_dedup(zip_file, precomputed_md5=md5_hash)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/lib/package/s3_uploader.py", line 134, in upload_with_dedup
    return self.upload(file_name, remote_path)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/lib/package/s3_uploader.py", line 113, in upload
    raise ex
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/lib/package/s3_uploader.py", line 105, in upload
    future.result()
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/botocore/client.py", line 656, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (NoSuchAccessPoint) when calling the PutObject operation: The specified accesspoint does not exist
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'ap-southeast-2', 'commandName': 'sam package', 'duration': 1970, 'exitReason': 'ExportFailedError', 'exitCode': 1, 'requestId': 'dx', 'installationId': 'x', 'sessionId': 'x', 'executionEnvironment': 'CLI', 'pyversion': '3.8.6', 'samcliVersion': '1.6.2'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Unable to upload artifact functions/ referenced by CodeUri parameter of TransformPartFn resource.
An error occurred (NoSuchAccessPoint) when calling the PutObject operation: The specified accesspoint does not exist

### Expected result

Uploading to XXXXXXXXX  3064 / 3064.0  (100.00%)

Successfully packaged artifacts and wrote output template to file packaged.yaml.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Catalina 10.15.7
2. `sam --version`: SAM CLI, version 1.6.2

**Comment by awood45** [comment]
S3 bucket names are globally unique - our input expects the bucket name. If you do not have access to write to the bucket, an appropriate error will be raised.

Closing, let me know if you have any follow-up questions, or a particular reason you strongly wish to use an ARN.

**Comment by Ruben-Sh** [comment]
Thanks for the update @awood45 - as you mention the bucket name is unique, no need for an ARN on my side. 

The error message does suggest an ARN is accepted. Is it possible to update the return message to only mention the expected bucket name regex that is accepted?

Bucket name must match the regex "^[a-zA-Z0-9.-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9-]{1,63}$"

**Comment by ryan-alley** [comment]
Also ran into this today - Bucket name works but ARN does not, which doesn't make a lot of sense, given the error message:

```Invalid bucket name "arn:aws:s3:::573923240433-pipeline-test": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"```

The regex looks incorrect for S3 ARNs.  Also, documentation should be updated:

https://docs.aws.amazon.com/en_us/codedeploy/latest/userguide/tutorial-lambda-sam-package.html

![image](https://user-images.githubusercontent.com/2498670/178541609-38429207-cd60-4a3e-b700-a6ab671301c8.png)

It's not good practice to say `your-S3-bucket` and not say what the expected type is (ARN, name, s3 url, etc...)
