### ISSUE TITLE
pytest not working with sam build --use-container

### ISSUE THREAD

**Issue by benpreisler** [aws/aws-sam-cli#2301]
### Description
pytest 6.0.0 and greater is failing when building in the docker container (when specifying --use-container)

It's trying to retrieve iniconfig==0.0.0 for some reason (which doesn't exist).  pytest does not define a specific version: https://github.com/pytest-dev/pytest/blob/a23666d55494f6960dfc8845757c391b5aedec0b/setup.cfg#L43

it works in versions of pytest less than 6.0.0 because that is when pytest started using iniconfig

Also this wasn't failing a few days ago when I last ran the build and nothing had changed between these (which makes me suspect a change to the lambci/lambda container)

### Steps to reproduce

Create a lambda with a pytest==6.0.0 dependency defined in the requirements file
run sam build --use-container
see failed result

### Observed result

sam build --use-container
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Starting Build inside a container
Collected default values for parameters: {'Env': 'dev'}
Unable to resolve property HostedZoneId: {'Fn::GetAtt': ['Domain', 'RegionalHostedZoneId']}. Leaving as is.
Unable to resolve property DNSName: {'Fn::GetAtt': ['Domain', 'RegionalDomainName']}. Leaving as is.
13 resources found in the template
Found Serverless function with name='PreTrafficHook' and CodeUri='pre_traffic_hook/'
Collected default values for parameters: {'Env': 'dev'}
Unable to resolve property HostedZoneId: {'Fn::GetAtt': ['Domain', 'RegionalHostedZoneId']}. Leaving as is.
Unable to resolve property DNSName: {'Fn::GetAtt': ['Domain', 'RegionalDomainName']}. Leaving as is.
Instantiating build definitions
Same build definition found, adding function (Previous: BuildDefinition(python3.8, pre_traffic_hook/, 400791ac-b830-44b3-9aa0-686fd6794edf, {}, []), Current: BuildDefinition(python3.8, pre_traffic_hook/, 148c2c7d-c92a-47e0-a5d0-146843a63fc5, {}, []), Function: Function(name='PreTrafficHook', functionname='a206081-CodeDeployHook_CF--dev-PreTrafficHook', runtime='python3.8', memory=None, timeout=300, handler='pre_traffic_hook.lambda_handler', codeuri='pre_traffic_hook/', environment={'Variables': {'LAYER_PATH': '/opt/python/lib/python3.8/site-packages/', 'DYNAMO_TABLE': 'MainTable', 'ENV': 'dev'}}, rolearn='arn:aws:lambda:us-east-1:xxxxx:function:TrafficHookRole', layers=[], events=None, metadata=None))
Building codeuri: pre_traffic_hook/ runtime: python3.8 metadata: {} functions: ['PreTrafficHook']
Building to following folder /var/folders/sc/3pymk8_10x9cjn72v75r9qqh0000gn/T/tmp3463j1me

Fetching amazon/aws-sam-cli-build-image-python3.8 Docker container image......
Mounting /Users/benjaminpreisler/code/src/pre_traffic_hook as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /tmp/samcli/source/requirements.txt --dest /tmp/samcli/scratch
Full dependency closure: {py==1.9.0(wheel), pluggy==0.13.1(wheel), attrs==20.2.0(wheel), packaging==20.4(wheel), six==1.15.0(wheel), pyparsing==2.4.7(wheel), toml==0.10.1(wheel), more-itertools==8.5.0(wheel), iniconfig==0.0.0(sdist), pytest==6.0.0(wheel)}
initial compatible: {py==1.9.0(wheel), attrs==20.2.0(wheel), pluggy==0.13.1(wheel), packaging==20.4(wheel), six==1.15.0(wheel), pyparsing==2.4.7(wheel), toml==0.10.1(wheel), more-itertools==8.5.0(wheel), pytest==6.0.0(wheel)}
initial incompatible: {iniconfig==0.0.0(sdist)}
Downloading missing wheels: {iniconfig==0.0.0(sdist)}
calling pip download --only-binary=:all: --no-deps --platform manylinux2014_x86_64 --implementation cp --abi cp38 --dest /tmp/samcli/scratch iniconfig==0.0.0
compatible wheels after second download pass: {py==1.9.0(wheel), pluggy==0.13.1(wheel), attrs==20.2.0(wheel), packaging==20.4(wheel), six==1.15.0(wheel), pyparsing==2.4.7(wheel), toml==0.10.1(wheel), more-itertools==8.5.0(wheel), pytest==6.0.0(wheel)}
Build missing wheels from sdists (C compiling True): {iniconfig==0.0.0(sdist)}
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/iniconfig-1.1.1.tar.gz
compatible after building wheels (no C compiling): {py==1.9.0(wheel), pluggy==0.13.1(wheel), attrs==20.2.0(wheel), iniconfig==1.1.1(wheel), packaging==20.4(wheel), six==1.15.0(wheel), pyparsing==2.4.7(wheel), toml==0.10.1(wheel), more-itertools==8.5.0(wheel), pytest==6.0.0(wheel)}
Build missing wheels from sdists (C compiling False): {iniconfig==0.0.0(sdist)}
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/iniconfig-1.1.1.tar.gz
compatible after building wheels (C compiling): {py==1.9.0(wheel), pluggy==0.13.1(wheel), attrs==20.2.0(wheel), iniconfig==1.1.1(wheel), packaging==20.4(wheel), six==1.15.0(wheel), pyparsing==2.4.7(wheel), toml==0.10.1(wheel), more-itertools==8.5.0(wheel), pytest==6.0.0(wheel)}
Final compatible: {py==1.9.0(wheel), pluggy==0.13.1(wheel), attrs==20.2.0(wheel), iniconfig==1.1.1(wheel), packaging==20.4(wheel), six==1.15.0(wheel), pyparsing==2.4.7(wheel), toml==0.10.1(wheel), more-itertools==8.5.0(wheel), pytest==6.0.0(wheel)}
Final incompatible: set()
Final missing wheels: {iniconfig==0.0.0(sdist)}
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {iniconfig==0.0.0(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {iniconfig==0.0.0(sdist)}
Builder workflow failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {iniconfig==0.0.0(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {iniconfig==0.0.0(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/__main__.py", line 117, in main
    builder.build(
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/builder.py", line 125, in build
    return workflow.run()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 76, in wrapper
    func(self, *args, **kwargs)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 276, in run
    raise WorkflowFailedError(workflow_name=self.NAME, action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: PythonPipBuilder:ResolveDependencies - {iniconfig==0.0.0(sdist)}
Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "PythonPipBuilder:ResolveDependencies - {iniconfig==0.0.0(sdist)}"}}

Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 13493, 'exitReason': 'BuildInsideContainerError', 'exitCode': 1, 'requestId': '73478eb7-6eb7-4b10-95bd-46b4f954ac21', 'installationId': '790ae032-2f3a-4228-9e4b-6fae564734f2', 'sessionId': 'd543e64a-ac31-4343-8fac-89cc32944e31', 'executionEnvironment': 'CLI', 'pyversion': '3.8.6', 'samcliVersion': '1.6.2'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - {iniconfig==0.0.0(sdist)}
Sam build did not run successfully. Aborting sam_full_build.sh

### Expected result

It should correctly build

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Catalina
2. `sam --version`: 1.6.2

**Comment by tanmais** [comment]
We are having the same issue and a release is stuck as a result

**Comment by ColWillis** [comment]
Yes downgrading pytest was a workaround for me:
    install_requires=[
...
      'pytest==5.4.3',
...

**Comment by prenx4x** [comment]
This issue seems fixed as sam-cli requirements have been updated. If problem persists please reopen.
