### ISSUE TITLE
sam package & deploy without using an S3 bucket

### ISSUE THREAD

**Issue by augustoproiete** [aws/aws-sam-cli#2312]
### Describe your idea/feature/enhancement

Currently sam package & deploy require an S3 bucket to store the packaged app and that the deployment be done from that location. Developers that already have an established CI/CD pipeline already have a repository for build artifacts where they'd like store the packaged sam app, and deploy packages from that location

The workaround today is to push artifacts to the developer's repository and during deployment run `sam package` and `sam deploy` just to satisfy the S3 requirement, which is inefficient and has limitations such as having to manually set up S3 buckets with the appropriate permissions as described in #1701.
 
### Proposal

Allow developers to specify an output folder & filename for creating a packaged application as a zip file, and allow developers to deploy from that zip file.

e.g.
```
sam package --output-zip-file my-sam-app.zip
sam deploy --zip-file my-sam-app.zip
```

**Comment by ajhool** [comment]
Previously mentioned in: #1516 

@prenx4x would you mind commenting on #1516 when you have some time? There is support for it but no comments from AWS team yet.

**Comment by sriram-mv** [comment]
Closing this issue as aws sam cli sees packaging and deploying of built artifacts as a non local action. However one can zip up the `.aws-sam/build` directory after running `sam build` and store it as an artifact that can be used for deployments separately.
