### ISSUE TITLE
SAM is installed but command cannot be found

### ISSUE THREAD

**Issue by andreaweb** [aws/aws-sam-cli#2320]
### Description

I've tried installing aws-sam-cli as recommended in the official documentation but it did not work. I've also tried several other methods including npm and pip, but none of them have made the `sam` command available for me.

### Steps to reproduce
I've ran the commands:

```
brew tap aws/tap
brew install aws-sam-cl
```

They finish successfully, but trying to run sam --version afterwards displays:

### Observed result

`Command 'sam' not found, but there are 18 similar ones.`

### Expected result

Should display sam's version instead.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 18.04.5 LTS
2. `sam --version`: when I try reinstalling brew tells me it's the latest version... but `sam --version` still does not work.

**Comment by hawflau** [comment]
I managed to reproduce the same Observed result, will investigate

**Comment by hawflau** [comment]
Running `brew install aws-sam-cli` twice "fixes" the issue as a work-around.
This is the same issue as [here](https://github.com/aws/homebrew-tap/issues/130) and [here](https://github.com/CircleCI-Public/aws-sam-serverless-orb/issues/20)

**Comment by hawflau** [comment]
Further investigation is needed. Meanwhile, a workaround is to run `brew install aws-sam-cli` twice

**Comment by ppottorff** [comment]
You need to symlink it: brew link aws-sam-cli

**Comment by aalaap** [comment]
I had 1.0.0 installed and working fine for months, but after upgrading to the latest (1.10.0) (`brew upgrade aws-sam-cli`), I got this command not found error. As @hawflau mentioned, running `brew install aws-sam-cli` after this fixed it for me.

**Comment by ronald8192** [comment]
Install, uninstall, then install again works for me (Ubuntu 20):

`brew install aws-sam-cli`
`brew uninstall aws-sam-cli`
`brew install aws-sam-cli`

**Comment by krrenjith** [comment]
Issue persist with Homebrew 2.7.1 and brew install twice fixes the issue. During first install getting following logs.

==> Installing aws/tap/aws-sam-cli
==> Pouring aws-sam-cli-1.15.0.x86_64_linux.bottle.tar.gz
🍺 /home/ec2-user/.linuxbrew/Cellar/aws-sam-cli/1.15.0: 3,951 files, 87.9MB
==> No outdated dependents to upgrade!
==> Checking for dependents of upgraded formulae...
==> Reinstalling 1 broken dependent from source:
aws/tap/aws-sam-cli
==> Caveats
==> openssl@1.1

However, the path /home/ec2-user/.linuxbrew/Cellar/aws-sam-cli/1.15.0 did not exist. The actual path getting created was /home/ec2-user/.linuxbrew/Cellar/aws-sam-cli/1.15.0.reinstall

After second run of brew install, /home/ec2-user/.linuxbrew/Cellar/aws-sam-cli/1.15.0 gets created and everything works as expected.

**Comment by xazhao** [comment]
Verified this issue is gone with following environments:
Homebrew: 3.2.10
SAM CLI: 1.29.0
EC2 Ubuntu 18.04.5

If there are further questions, feel free to reopen this.

**Comment by zmanhcong** [comment]
i had the same problem with windows 11, i fixed it by below

1. Try uninstalling and reinstalling the SAM CLI. You can do this by running the following commands:
```
pip uninstall aws-sam-cli
pip install aws-sam-cli
```
2. Check the version of Python you're using. The SAM CLI requires Python 3.6 or later. You can check your Python version by running the command python --version. If you're using an earlier version of Python, you'll need to upgrade to a later version.
