### ISSUE TITLE
Snap appears to be missing from Snap Store

### ISSUE THREAD

**Issue by velovix** [aws/aws-sam-cli#2329]
### Description

#1086 added support for Snap, but it looks like there isn't anything set up to deploy SAM to the Snap store. It would be great to have this as an option, since the only other supported way to install SAM on Linux is using Homebrew.

A dead link to the Snap Store used to be in the README, but was removed at some point.

**Comment by mndeveci** [comment]
Hi @velovix ,

Sorry for the confusion about snapcraft. But we are working on improving our installation and binary distribution at the moment with another approach (which won't require snapcraft nor homebrew). I will be closing this issue for now but you can follow-up about the development in this issue; https://github.com/aws/aws-sam-cli/issues/1424

**Comment by velovix** [comment]
@mndeveci No worries! I look forward to using the new solution.

For others who come across this issue, I currently use pipx to install SAM in an isolated environment:

```
pipx install aws-sam-cli
```
