### ISSUE TITLE
HttpApi event.routeKey differs on local testing

### ISSUE THREAD

**Issue by tsndr** [aws/aws-sam-cli#2345]
### Description

When I run my HttpApi locally and `console.log` the `event` object my `routeKey` is `/auth/login:POST`, but when I do the same thing on AWS Lambda it says `POST /auth/login`.

### Expected result

That the local output of `event.routeKey` also is `POST /auth/login`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Catalina (latest update)
2. `sam --version`: 1.7.0

@awsjeffg

**Comment by awsjeffg** [comment]
Confirmed, here's a sample app that demonstrates the issue:

https://github.com/awsjeffg/gh-issue-2345

**Comment by mndeveci** [comment]
This has been released in [v1.8.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.8.0), resolving
