### ISSUE TITLE
Automatic template.json detection

### ISSUE THREAD

**Issue by tsndr** [aws/aws-sam-cli#2355]
### Describe your idea/feature/enhancement
I'd like to see SAM CLI detect `template.json` automatially just like it does with `template.yaml`/`template.yml`.

#### Example:
If I run `sam validate` with a `template.yaml` file it works.

If I use the JSON syntax I get an error: **SAM Template Not Found**
So I have to type: `sam validate -t template.json` to get it to work.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)
No!

**Comment by mndeveci** [comment]
Resolving as this have been released with [SAM CLI v1.24.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.24.0)
