### ISSUE TITLE
How to trigger S3 with a Queue Event?

### ISSUE THREAD

**Issue by AllanOricil** [aws/aws-sam-cli#2361]
How to trigger S3 with a SQS FIFO Queue Event?

I know I can make s3 dispatch an event to an SQS, but I could not find anywhere how to create a template for that. Is there any reference you can suggest? Or could you post one template here? Thank you in advance

**Comment by qingchm** [comment]
Hey @AllanOricil, Hopefully this is what you're looking for: https://docs.aws.amazon.com/AmazonS3/latest/dev/ways-to-add-notification-config-to-bucket.html#step1-create-sqs-queue-for-notification

**Comment by AllanOricil** [comment]
HI @qingchm what I needed was a cloud formation Template example. After studying the template structure and which events an S3 can dispatch and which services it can trigger, I finally made progress. I will post the template here later. The only limitation I found is that S3 can't work with FIFO Queues, only Standard Queues :/

**Comment by AllanOricil** [comment]
For those who need to do it. This is a sample template where you can dispatch a S3 event to a SQS. It worked really well to me. Just one point is that you can't have two Filters with the same Rule. So if your S3 dispatches a event to a SQS you can't dispatch the same event to a Lambda.

````xml
  SimpleQueue:
    Type: AWS::SQS::Queue

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: ".json"
            Queue: !GetAtt SimpleQueue.Arn
````
