### ISSUE TITLE
Update Gradle in sample java projects

### ISSUE THREAD

**Issue by superwese** [aws/aws-sam-cli#2368]
### Describe your idea/feature/enhancement

`sam build` fails under Java14 with Errors like  java.lang.NoClassDefFoundError
`sam init` installs gradle version gradle-5.1.1-bin.zip with the gradle wrapper
According to:
https://github.com/gradle/gradle/issues/10248#issuecomment-633656326
this is fixed for now

### Proposal
provide an Gradle-wrapper.properties file with a newer gradle version

**Comment by mndeveci** [comment]
Resolving this issue since https://github.com/aws/aws-sam-cli-app-templates repository is already using gradle with 7.3.3 version. https://github.com/aws/aws-sam-cli-app-templates/search?p=1&q=distributionUrl
