### ISSUE TITLE
Cookiecutters in directories

### ISSUE THREAD

**Issue by billyshambrook** [aws/aws-sam-cli#2370]
### Describe your idea/feature/enhancement

Cookiecutter project released a new feature in v1.7 which introduces the ability to organize several templates in one repository or zip file, separating them by directories.

When using the cookie-cutter CLI this requires passing the `--directory` option.

See more information about the feature here https://cookiecutter.readthedocs.io/en/1.7.2/advanced/directories.html

We would like to start organizing our various internal cookie-cutter repos into one using this new feature however this can't be used with AWS SAM as the additional `--directory` option is not available through AWS SAM CLI.

### Proposal

I propose exposing a new `--directory` option in the `sam init` CLI.

**Comment by c2tarun** [comment]
Thanks for raising this feature request.
There are other interesting changes in discussion for init at #3555. We can probably batch this change there. Linking them so that this don't get dropped.

**Comment by jfuss** [comment]
Closing as duplicate of https://github.com/aws/aws-sam-cli/issues/3555
