### ISSUE TITLE
Sam build is adding all dependencies and removing random classes /methods

### ISSUE THREAD

**Issue by pabloiarriola** [aws/aws-sam-cli#2371]
### Description:
I am using the latest version of SAM 1.9.0 with java 8 on a amazon linux 2 workspace. The problem I am having is that when I do a sam build and then sam deploy and try to run my function on lambda it gives errors that x method or class are not found. And the package size is 29.9mb, but when I make mvn package and upload my code manually it does work and the package size is 12.7mb

So this tells that the way sam is parsing my code is different as its adding all the code im telling it to exclude and its even excluding more. It tends to exclude code from AWS libraries like xray, sqs,s3,etc. 

### Steps to reproduce:
1. Sam build
2. Sam deploy

### Observed result:
{
  "errorMessage": "software.amazon.awssdk.core.SdkField$Builder.memberName(Ljava/lang/String;)Lsoftware/amazon/awssdk/core/SdkField$Builder;",
  "errorType": "java.lang.NoSuchMethodError",
  "stackTrace": [
    "software.amazon.awssdk.services.sqs.model.SendMessageBatchRequestEntry.<clinit>(SendMessageBatchRequestEntry.java:47)",
    "gt.com.celera.App.handleRequest(App.java:97)",
    "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
    "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
    "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
    "java.lang.reflect.Method.invoke(Method.java:498)"
  ]
}

### Expected result:
It should send a message to a sqs queue 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Lambda
2. `sam --version`: 1.9.0

`Add --debug flag to command you are running`

**Comment by pabloiarriola** [comment]
And this is the one with xray 

	Exception in thread "Thread-0" java.lang.NoClassDefFoundError: com/amazonaws/xray/handlers/config/AWSServiceHandlerManifest

**Comment by wchengru** [comment]
Hello @pabloiarriola , thanks for reporting this issue. We are trying to investigate it. I was wondering if you could provide us with a minimum template with package which we can reproduce it and identify the root cause. Thanks!
