### ISSUE TITLE
AWS_EXECUTION_ENV is not defined in debug-mode when I invoke the local lambda for nodejs runtime.

### ISSUE THREAD

**Issue by yoshiokimoto** [aws/aws-sam-cli#2384]
### Description:

I've observed that the environment variable `AWS_EXECUTION_ENV` is not set/defined when I run my sample nodejs lambda function with debug mode.
Actually I can see `AWS_EXECUTION_ENV` in my lambda script if I run local lambda docker with non-debug mode (i.e. `sam local invoke`), but the same environment variable is not there if I run in debug mode `sam local invoke -d 5858`.

I suppose the difference between debug and non-debug mode is whether it opens debug port or not, I think it shouldn't affect for which lambda runtime to use in local lambda container, and the environment variable which looks tied with the using lambda runtime. 

I've checked with both nodejs10.x and nodejs12.x runtime, but results are same.

### Steps to reproduce:

1. Prepare a lambda script to run with nodejs runtime, read `AWS_EXECUTION_ENV` via process.env, define the lambda resource in template.yaml to call that sample function.
2. Run that lambda function in non-debug mode `sam local invoke`. You should be able to see `AWS_EXECUTION_ENV`.
3. Run same lambda function in debug mode `sam local invoke -d 5858`, attach the debugger to the local lambda container to step through the code, then check whether you can see `AWS_EXECUTION_ENV`.

### Observed result:

The environment variable `AWS_EXECUTION_ENV` can be seen in non-debug mode as `"AWS_EXECUTION_ENV": "AWS_Lambda_nodejs12.x"` if it runs with nodejs12.x,  but it's not set/defined in debug mode.

### Expected result:

The environment variable `AWS_EXECUTION_ENV` should be set in both mode, it should be  `"AWS_EXECUTION_ENV": "AWS_Lambda_nodejs12.x"` if it runs with nodejs12.x.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

* OS: MacOS Catalina, Ubuntu 20.04
* `sam --version`: `SAM CLI, version 1.8.0`
* `docker --version`: `Docker version 19.03.13, build 4484c46d9d`
* I used the vscode debugger to attach to the debug mode lambda container for step-through debugging.

**Comment by wchengru** [comment]
I can reproduce this issue with nodejs10.x and 12.x.
Also I have tested with python3.8 but this doesn't happen.

**Comment by aahung** [comment]
v1.16.0 is released, please reopen if the issue still persists
