### ISSUE TITLE
Latest Release v1.11.0 Assets Incorrect

### ISSUE THREAD

**Issue by dude051** [aws/aws-sam-cli#2399]
### Description:
The release performed today for v1.11.0 has the assets from v1.10.0 instead. This also is breaking home-brew installs/upgrades which forces the bottle to not be found and forces a source compile to install.

`https://github.com/aws/aws-sam-cli/releases/tag/v1.11.0`

### Steps to reproduce:
brew upgrade aws-sam-cli

### Observed result:
```
Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.

==> Upgrading 1 outdated package:
aws/tap/aws-sam-cli 1.10.0 -> 1.11.0
==> Upgrading aws/tap/aws-sam-cli 1.10.0 -> 1.11.0
==> Downloading https://github.com/aws/aws-sam-cli/releases/download/v1.11.0//aws-sam-cli-1.11.0.sierra.bottle.tar.gz
##O#- #
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "aws-sam-cli"
Download failed: https://github.com/aws/aws-sam-cli/releases/download/v1.11.0//aws-sam-cli-1.11.0.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
....
```

### Expected result:
Upgrade or install of v1.11.0

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 11.0
2. `sam --version`: v.1.10.0

`Add --debug flag to command you are running`

**Comment by al-cheb** [comment]
Windows:
Link is broken - https://github.com/awslabs/aws-sam-cli/releases/latest/download/AWS_SAM_CLI_64_PY3.msi

**Comment by qingchm** [comment]
@al-cheb the windows link is fixed now!
@dude051 I believe there was an error with the released script that caused the warnings. Right now we are working to upload a new version of the brew source, should be up there soon.

**Comment by qingchm** [comment]
@dude051 just published new artifacts, this should fix the issue that you mentioned. Let me know if you experience any difficulties! Closing this issue for now
