### ISSUE TITLE
sam deploy updates ALL lambda functions instead of only those that have really changed

### ISSUE THREAD

**Issue by OK-Apps** [aws/aws-sam-cli#2405]
**Description:**

From what we understand the expected (desired, correct) behaviour of sam deploy 
is that if you have a "sam application" (already deployed once) with multiple several functions and do 
sam deploy
then it will deploy ('update') only those functions that really have changed one that have or if none change it says "nothing to deploy"... 
and this seems indeed to be the observed behaviour case when deploying all the time from from the same machine 
BUT 
when deploying from a machine difference than the one that did the previous deployment - then it deploy (updates) 
everything regardless what changed - even if nothing changed at all (instead of the expected "smart" behaviour)
ALSO
when setting up a CodePipeline in AWS to deploy a "sam application" then 
it always (!!!) updates everything - and never the "smart" (expected, desired, sensible) way
these updates 
are very evident by the fact that the lambda function versions get "bumped up" by 1 - 
which makes the use of CodePipeline CICD effectively unusable for practical PROD-grade purposes 
also noticed that SAM CLI version used inside the CodeBuild in CodePipeline is reported as " 0.17.0"

[Container] 2020/11/15 08:44:59 Running command sam --version
34 | SAM CLI, version 0.17.0

could it also be a part of the problem?

**Steps to reproduce the issue:**
1. via CodePipeline,  have an "Sam application" deployed that consists of 3 simplest "hello, world"-type lambda functions
"AppleFun, "BananaFun" and "OrangeFun
all have "AutoPublishAlias:" to automatically trace ("publish" version in case of update and assign the designate alias (fro example sake - "PRODUCTION") to the newest version 
 
2. notice the versions 

3. Modify the code in just one of the function - for example "AppleFun"

4. Commit code to trigger the Pipeline

**Observed result:**
After Pipeline completes successfully - notice the versions again - can see all lambda functions hav their version increased by 1 , and by inspecting theEvents in the respective stack in CloudFormation can also see that ALL THREE lambda functions have been 'UPDATED'

**Expected result:**
Only the lambda function that actually has been modified would 'UPDATED' be and have its versions increased 
the other two lambda functions should not have any changes in regards to them at all!

**Comment by awood45** [comment]
Can you share a partial template snippet with you `AWS::Serverless::Function` definitions? Feel free to anonymize anything sensitive, I am especially interested in the `CodeUri` values.

**Comment by mingkun2020** [comment]
Closing. Feel free to reopen if there is more information on this issue.

**Comment by aprilmintacpineda** [comment]
This is actually happening to me, in my case I have the following file structure:

```
/ root
... lots of other unrelated files here
| - src <-- all source codes
|   | - functions <-- all my functions
|   | - dependencies <-- lambda layer 
```

If I change something on `src/dependencies` it will deploy all functions again resulting to a very long deployment time, when I really only updated the layer, in this case, the functions will really have to update to point to the latest version of the layer, but can't it just update the settings instead of doing a new round of deployment?

**Comment by CGarces** [comment]
Same issue with
SAM CLI, version 1.22.0
Using this template:
https://github.com/aws-samples/aws-step-functions-rpa/blob/main/template.yaml

**Comment by dfuentes77** [comment]
Similar issue here.  I use AutoPublishAlias:
```
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
```
I change nothing in the code or in the template.yaml for the function itself.  But I change one small value in a cloudwatch alarm, say the threshold from 75 to 80:
```
  MySuccessRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:  
      ...
      Threshold: 80
```
but SAM then wants to deploy a whole new version of the function anyway:
```
CloudFormation stack changeset
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Operation                                       LogicalResourceId                               ResourceType                                    Replacement
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
+ Add                                           MyFunctionVersion0c6c64a82d                     AWS::Lambda::Version                            N/A
* Modify                                        MyFunctionAliaslive                             AWS::Lambda::Alias                              False
* Modify                                        MyFunction                                      AWS::Lambda::Function                           False
* Modify                                        MySuccessRateAlarm                              AWS::CloudWatch::Alarm                          False
- Delete                                        MyFunctionVersion896e431627                     AWS::Lambda::Version                            N/A
```

**Comment by ygorth** [comment]
Similar issue: https://github.com/aws/aws-sam-cli/issues/3236 - I am facing the same issue.
