### ISSUE TITLE
unable to connect to local redis

### ISSUE THREAD

**Issue by CalvinChang-tw** [aws/aws-sam-cli#2431]
### Description:

sam local invoke unable to connect to local redis

### Steps to reproduce:

I have redis listening on 127.0.0.1:6379
my code is something like:
```
const redis = require('redis');
const {REDIS_PORT, REDIS_HOST} = require('../constant');

const connectRedis = async (host) => {
    const client = redis.createClient(REDIS_PORT, REDIS_HOST, {
        no_ready_check: true,
    });
};
```

### Observed result:

"Function 'redisFunction' timed out after 10 seconds "
10 seconds is setting from template

### Expected result:

connect to local redis

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:

`Add --debug flag to command you are running`

**Comment by aoztaskin** [comment]
As SAM processes are run within Docker containers, you can not directly connect to your localhost.

See this issue: https://github.com/aws/aws-sam-cli/issues/318
Work around for Linux: https://github.com/aws/aws-sam-cli/issues/318#issuecomment-527373313
For Mac: https://github.com/aws/aws-sam-cli/issues/318#issuecomment-377770815

**Comment by sriram-mv** [comment]
This is the same discussion at https://github.com/aws/aws-sam-cli/issues/2436, closing this issue to have one thread of conversation
