### ISSUE TITLE
Invalid API Gateway Response Keys: {'base64Encoded'} revisited

### ISSUE THREAD

**Issue by kristofvb** [aws/aws-sam-cli#2434]
SAM CLI still returns Invalid API Gateway Response Keys: {'base64Encoded'} in {'statusCode': 200, 'multiValueHeaders': {'Content-Type': ['application/json']}, 'body': '{"name":"boek","isbn":"d28a6052-f216-4c8b-8a7f-726cc73f9918"}', 'base64Encoded': False}

This has been reported by https://github.com/aws/aws-sam-cli/issues/1193

I think this response is correct. If you test a lambda function via the AWS Lambda console test button you also get a response containing the property named 'base64Encoded' instead of a property named 'isBase64Encoded' as SAM CLI seems to expect in function _invalid_apig_response_keys in local_apigw_service.py

**Comment by jfuss** [comment]
@kristofvb Are you saying that API Gateway is accepting `base64Encoded` as well as `isBase64Encoded`? Their docs clearer state the key is `isBase64Encoded`: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format

If Lambda is returning `base64Encoded` from the console test button, then your function IS returning `base64Encoded` but I would expect API Gateway not to accept it given the key is not `isBase64Encoded`. Which means something in your function is incorrect.

**Comment by kristofvb** [comment]
Well, there are many layers involved so it is hard to judge where the issue really is. [This comment](https://github.com/awslabs/aws-serverless-java-container/issues/262#issuecomment-536061559) suggests the marshalling/unmarshalling is done by `AWS Lambda`. If you run locally I guess `AWS Lambda` is really SAM CLI. All issues I have read about this seem to point to each other.

I think aws-serverless-java really have done [their bit](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyResponse.java#L122) to try and fix this.

**Comment by kristofvb** [comment]
By modifying class `AwsProxyResponse` I can get the valid property `isBase64Encoded` in the response but I cannot get rid of property `base64Encoded` unless the committers of aws-serverless-java are willing to accept a breaking change by removing the offending getter and setter that leads to the inclusion of `base64Encoded` in the response.

The alternative would be for SAM CLI to be forgiving wrt to the occurrence of `base64Encoded` in the response.

See an example response with both properties present:

`Invalid lambda response received: Invalid API Gateway Response Keys: {'base64Encoded'} in {'statusCode': 200, 'multiValueHeaders': {'Content-Type': ['text/html']}, 'body': '...', 'isBase64Encoded': False, 'base64Encoded': False}
`

**Comment by kristofvb** [comment]
@jfuss to come back to my previous remarks, would it be acceptable to log a warning for non-compliant responses instead of throwing a LambdaResponseParseException in this case?

**Comment by mgrandis** [comment]
@kristofvb
Could provide us with a detailed example on how to reproduce this issue?
This would help us investigate.
Thanks!

**Comment by kristofvb** [comment]
@mgrandis have a look at https://github.com/kristofvb/aws-sam-cli-issue-2434

**Comment by mgrandis** [comment]
Thank you!

**Comment by maxedenharter0507** [comment]
Any updates on this? We've got the same problem by setting up an micronaut lambda with sam cli like @kristofvb did it in his example.

**Comment by castasint** [comment]
I'm getting the same error. I am wiring up a spring boot rest service to get the data. The response from the spring controller is correct. But somehow, the SAM CLI is finally giving me the below response. 

I'm on SAM CLI : **SAM CLI, version 1.21.1**

I'll appreciate any help I can get here.

`Invalid lambda response received: Invalid API Gateway Response Keys: {'base64Encoded'} in {'statusCode': 200, 'multiValueHeaders': {'Content-Type': ['application/json'], 'X-Custom-Header': ['application/json']}, 'body': '{"Name":"JOHN DOE"}', 'base64Encoded': False
}
`

**Comment by moelasmar** [comment]
after some investigations and I could not find anything that mention that API gateway will through an error if the lambda response contains unexpected fields. I found that API gateway just ignore any unexpected fields.

**Comment by wchengru** [comment]
As the PR is merged and released, I will close this issue. Please reopen it if you still find this issue in the latest release.
