### ISSUE TITLE
Extra Cookiecutter Project Name in READMEs

### ISSUE THREAD

**Issue by metaskills** [aws/aws-sam-cli#2442]
I noticed that various commands in READMES like this one (https://github.com/aws/aws-sam-cli/blob/develop/samcli/lib/init/templates/cookiecutter-aws-sam-hello-dotnet/%7B%7Bcookiecutter.project_name%7D%7D/README.md) have the `{{ cookiecutter.project_name }}` before the `$` and it did not appear like maybe that was desired?

<img width="1052" alt="Screen Shot 2020-12-02 at 10 14 04 PM" src="https://user-images.githubusercontent.com/2381/100959171-b5622880-34eb-11eb-9a07-ae882e3787d8.png">

**Comment by jfuss** [comment]
@metaskills The `{{ cookiecutter.project_name }}` is suppose to be replaced with the project name you give to `sam init`. That was the generated example looks like the terminal and indicates you need to be in the project directory. Is this not happening?

**Comment by metaskills** [comment]
It is happening and that is my point. Why would you want a README that says run this code:

```shell
mydumbproject$ sam local start-api
mydumbproject$ curl http://localhost:3000/
```

All documentation for shell commands looks simply like this:

```shell
$ sam local start-api
$ curl http://localhost:3000/
```

Maybe someone has their personal sheet to echo the PWD prior to the PROMPT? If so, that's a personal choice. I've never seen standard shell documentation use this format and it gave me pause. But that just might be me.
