### ISSUE TITLE
Simple proxy to support sending non-API events to Lambda Function

### ISSUE THREAD

**Issue by 0xDjole** [aws/aws-sam-cli#2444]
Hey people!

What do you think about simple proxy that can be used to send any kind of event to Lambda functions. 

The goal is to allow people to not deal with CLI as much, but use tools like Postman to send events like DynamoDB streams and test lambda functions.

Also another part of of it is listing default source mappings for different events so people can store them into variables in postman ( Same kind of mapping found when testing lambda functions in AWS Console).

**Comment by jfuss** [comment]
@djole-nikolic Does `sam local start-lambda` work for this use-case? This mimics the invoke endpoint of the Lambda service. So you can send events to your lambda function through HTTP.

**Comment by djole-nikolic** [comment]
@jfuss As far as I know it still wouldn't let you test with postman right? Only supports CLI.

**Comment by jfuss** [comment]
`sam local start-lambda` is the right thing to use for this. You can use Postman, curl, AWS SDK or AWS CLI to invoke the function.

Closing as this is supported already.
