### ISSUE TITLE
Using the build command's --parallel option with --use-container results in numerous pulls of the Docker image.

### ISSUE THREAD

**Issue by brysontyrrell** [aws/aws-sam-cli#2446]
### Description:

I went to use the parallel build option for the first time in a while and `sam` proceeded to pull the latest version of the `amazon/aws-sam-cli-build-image-python3.8` image, but did so for every thread it spawned to perform the build instead of performing the pull/check before launching all the threads.

![Screen Shot 2020-12-03 at 2 37 38 PM](https://user-images.githubusercontent.com/3086245/101085942-c6577c00-3575-11eb-9ad8-c12ca557fc2e.png)

### Steps to reproduce:

- Create a SAM app with multiple Lambda functions defined that need to be built.
- Clear out any cached image of `amazon/aws-sam-cli-build-image-python3.8` in Docker.
-  Run `sam build -u -p`.

### Observed result:

SAM's output shows `docker pull` requests being opened for every build job.

### Expected result:

One `docker pull` is performed prior to launching all of the builds.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 11.0
2. `sam --version`: SAM CLI, version 1.13.1

`Add --debug flag to command you are running`

**Comment by mndeveci** [comment]
This has been released with [v1.14](https://github.com/aws/aws-sam-cli/releases/tag/v1.14.0)
