### ISSUE TITLE
Using ImageConfig Causes SUPERNOVA Launch, Runtime.InvalidEntrypoint Errors 

### ISSUE THREAD

**Issue by metaskills** [aws/aws-sam-cli#2453]
While using the latest version of AWS SAM with `sam init` for a Ruby 2.7 container project I noticed that SAM's `template.yaml` file has this section commented out and mentions how you can override the `CMD` in the Dockerfile. This option was attractive for me for reasons. 

```
ImageConfig:
  Command: ['app.lambda_handler']
```

However, I have found that once you do this in our your `AWS::Serverless::Function` and deploy, your entire function is pretty much broken. Errors will be shown like this in CloudWatch.

```
SUPERNOVA Launch error: Couldn't find valid bootstrap(s): [app.lambda_handler] Entrypoint: [] Cmd: [app.lambda_handler] WorkingDir: [/var/task]
{
  "errorMessage": "RequestId: 68c820b5-b141-4d00-bdda-91acda1c74cf Error: Couldn't find valid bootstrap(s): [app.lambda_handler]",
  "errorType": "Runtime.InvalidEntrypoint"
}
```

Removing `ImageConfig` from `template.yaml` and redeploying will not help!!! The configuration is sticky.

<img width="1105" alt="Screen Shot 2020-12-04 at 4 23 11 PM" src="https://user-images.githubusercontent.com/2381/101216847-3cc7ad00-364e-11eb-9ca6-61bf28f2851f.png">

However, I did learn after a lot of trial and error that I can use the Lambda GUI to remove the `CMD override` and the function will start to work again. So unless I did some really wrong, the `ImageConfig` `Command` option looks to be completely broken, at least for me in Ruby 2.7 runtime. Might be for all runtimes tho? I have not checked.

**Comment by sriram-mv** [comment]
Thanks for Reporting this Issue!

This has been raised with internal service teams and we are looking into the matter internally.

**Comment by sriram-mv** [comment]
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-imageconfig.html

If you look under the syntax section, if you specify an entrypoint along with the command the error should go away.

**Comment by metaskills** [comment]
Thanks! I might avoid the ImageConfig till resolved.  

Also a thought, depending on the resolution time. Maybe adjusting these would help other's avoid the issue. https://github.com/aws/aws-sam-cli-app-templates/blob/master/ruby2.7-image/cookiecutter-aws-sam-hello-ruby-lambda-image/%7B%7Bcookiecutter.project_name%7D%7D/template.yaml#L18-L20

Thanks y'all!!!

**Comment by sriram-mv** [comment]
We have identified an issue with ImageConfig parameter in CFN, where the removing the parameters from the CFN or SAM template is not reflected in the service.Therefore, when ImageConfig is set using Cloudformation or SAM template, it cannot be removed by removing the parameters and deploying the template. We are working to fix this issue. As a workaround, customers who want to remove ImageConfig that was previously set must use the following CLI command to remove ImageConfig. Alternatively, customers can also use AWS Lambda management console or SDK to remove ImageConfig. 
CLI command:
```
aws lambda update-function-configuration --function-name 'foo' --region regionName --image-config '{}'
```

**Comment by sriram-mv** [comment]
@metaskills Yep! https://github.com/aws/aws-sam-cli-app-templates/pull/69

**Comment by sriram-mv** [comment]
https://github.com/aws/aws-sam-cli-app-templates/pull/69 is merged

**Comment by ericmilaneze** [comment]
Hi, I'm facing the same issue as @metaskills, but I'm using .net 5.0. In my CloudFormation yaml script I have this:
`  WebhookCallsFunction:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: [ 'Caas.Functions::Caas.Functions.WebhookCalls::RepassarChamada' ]
      Code:
        ImageUri: !Sub "860615044000.dkr.ecr.us-east-1.amazonaws.com/caas-lambda@${CaasFunctionsDigestParameter}"
      Role: !GetAtt WebhookCallsFunctionRole.Arn`

When I hit "Test" button on GUI, I receive this error in return:
Couldn't find valid bootstrap(s): ...

I don't want to remove the CMD, I need the CMD I put to work.

When I edit the CMD (not changing anything, just clicking Edit and then saving), the test work.

Can someone help me, please?

**Comment by berkcent** [comment]
Facing same issues as @ericmilaneze, but after deploy with CDK. Opening edit tab in console and saving without changes fixed function. 

@sriram-mv, any updates when it might be fixed?

**Comment by jfuss** [comment]
@berkcent This is a bug within Lambda's CloudFormation. I will bring it back up with their team but it is not something we can directly handle. 

Closing this as this is an issue with CloudFormation and not SAM. The workaround is to provide the Entrypoint and Cmd in the template.

**Comment by BR0kEN-** [comment]
@jfuss where to subscribe for the updates on this? This is super implicit. I created an image `FROM public.ecr.aws/lambda/python:3.8` and was planning to use it by two Lambdas so expectedly put different `ImageConfig.Command` (SAM) to each definition and as a result, got the error:

```
IMAGE	Launch error: Couldn't find valid bootstrap(s): [handler_publisher.handle]	Entrypoint: []	Cmd: [handler_publisher.handle]	WorkingDir: [/var/task]
Error: Couldn't find valid bootstrap(s): [handler_publisher.handle] Runtime.InvalidEntrypoint
```

**Comment by gmariano** [comment]
> Hi everyone!
> 
> I also tried with CDK and then I've found what seems to be the solution.
> 
> Looks like there's a bug in CloudFormation that makes the CMD also become the ENTRYPOINT. When we edit and then saving (not changing anything) then this issue disappears.
> 
> My solution was to explicitly set the **ENTRYPOINT** as "**/lambda-entrypoint.sh**". It fixed the issue for me.
> 
> @berkcent, in CDK I did this:
> 
> ```
> new DockerImageFunction(this, "RepassarChamada",
>     new DockerImageFunctionProps
>     {
>         Code = DockerImageCode.FromImageAsset(
>             Directory.GetCurrentDirectory(),
>             new AssetImageCodeProps
>             {
>                 File = "src/Caas.Functions/Dockerfile",
>                 Entrypoint = new string[] { "/lambda-entrypoint.sh" },
>                 Cmd = new string[] { "Caas.Functions::Caas.Functions.WebhookCalls::RepassarChamada" },
>             })
>     });
> ```
> 
> Hope it was helpful!

@ericmilaneze I don't know how you figured it out but you're a genius! I'm using cdk as well and I was stuck there.

**Comment by BR0kEN-** [comment]
@gmariano, there are two ways you can trace the default entrypoint:
- check the Dockerfile (e.g., https://github.com/aws/aws-lambda-base-images/blob/python3.8/Dockerfile.python3.8);
- run `docker image inspect public.ecr.aws/lambda/python:3.8`.

**Comment by gmariano** [comment]
Thank you @BR0kEN-! 
In my case it is a dotnet5.0 lambda, but I see the entrypoint is the same:
https://github.com/aws/aws-lambda-base-images/blob/dotnet5.0/Dockerfile.dotnet5.0
