### ISSUE TITLE
When deploying image-based Hello World app using Windows, see escape characters during image upload

### ISSUE THREAD

**Issue by mark-hirayama** [aws/aws-sam-cli#2454]
### Description:
Using the new SAM CLI that includes container images using my Windows laptop, when I deploy the sample Hello world app it incorrectly displays escape characters while pushing images.

### Steps to reproduce:
1. On Windows laptop, download the latest SAM CLI
2. Run `sam init` and choose the following:
   * Template:  `1 - AWS Quick Start Tempates`
   * Package type:  `2 - Image`
   * Base image:   `5 - amazon/python3.7-base`
   * (etc....)
3. cd into the new project folder
4. run `sam build`
5. run `sam --deploy --image-repository <my-ECR-repo-name> (etc...)`

### Observed result:
 Strange escape characters scroll by for multiple minutes: 
![sam-deploy-output-with-image-based-sample-app](https://user-images.githubusercontent.com/34664502/101220734-0cc2de80-363b-11eb-9238-0b456a58c9e6.png)

### Expected result:
More user-friendly status output

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:  Windows 10
2. `sam --version`:    1.13.1

`Add --debug flag to command you are running`

**Comment by CoshUS** [comment]
Reproduced with SAM CLI 1.13.2. 
Progress bar is also not flushing and overwriting properly.

**Comment by hoffa** [comment]
Need to have `colorama` installed? https://github.com/pallets/click/issues/1458#issuecomment-576455579

**Comment by CoshUS** [comment]
This should be fixed with SAM CLI 1.30.0 release.

**Comment by hoffa** [comment]
Resolved as per ⬆️; closing.
