### ISSUE TITLE
`operationName` missing from `sam local start-api` API Gateway proxy request context

### ISSUE THREAD

**Issue by ramosbugs** [aws/aws-sam-cli#2457]
### Description:

When running a Lambda behind an API Gateway REST API, each request context includes a field called `operationName`. This enables a single Lambda to handle multiple API routes:
https://github.com/aws/aws-lambda-go/blob/5bc50ab1c1dc8f32fce7f7745efcf601f8054fbe/events/apigw.go#L35

Unfortunately, this field isn't being set by `sam local start-api`, which prevents testing Lambdas that depend on `operationName`. The same Lambdas work fine on production AWS.

For clarity, both this issue and #2456 are about missing fields that AWS provides but that `sam local start-api` does not. However, I wasn't able to find any version of the SAM CLI that sets `operationName`, so this one doesn't look like a regression.

### Steps to reproduce:

Check the API request context for the `operationName` field.

### Observed result:

The `operationName` is omitted from the request context JSON blob.

### Expected result:

The `operationName` should contain the API route's operation name (e.g. `ConnectRoute` in the case of https://github.com/aws/aws-sam-cli/blob/3ee79db8a83b7941482fe03315d6162483094e9d/tests/smoke/templates/sar/simple-websockets-chat-app-template.yaml#L29)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS 10.15.7
2. `sam --version`: v1.13.2

**Comment by awood45** [comment]
Able to reproduce
