### ISSUE TITLE
SAM Package Contents/Size

### ISSUE THREAD

**Issue by matthewlynden** [aws/aws-sam-cli#2482]
### Description:
I've noticed the sam package command is zipping my entire workspace repository into a single zip which is uploaded to S3 and fails to deploy due to the unzipped size being larger than the max 262144000 bytes.

What are the minimum artefacts required to deploy and is there a way to limit what sam package includes in its zip?

**Comment by jfuss** [comment]
@matthewlynden SAM Package will zip up the folder which is defined in the template. This is different for each resource but for an example lets look at a Function.

```
...
Type: AWS::Serverless::Function:
Properties:
   CodeUri: path/to/the/source
   ...
```

In this case, SAM will zip of the folder defined by the CodeUri property. If your function does not have this property, it defaults to the current working directory. In many cases this is unexpected, but customers have come to rely on this so we are stuck with that behavior. So one thing you can do is, define the path to where the artifacts are on your machine, and SAM will only zip those up and upload to S3.

Does that help explain what is going on and how to avoid it? If not, providing an example of what you are exactly running into will help understand the issue you might be running into (and if it is a bug or one of those 'unexpected features').

**Comment by matthewlynden** [comment]
@jfuss Thanks! That does make sense. I'm giving that a try but facing some issues.

If I have a function ...

    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: shimd/handlers/update-key.handler

I've specified the CodeUri to point to 'src' which contains all the function code.
How should the Handler be referenced, absolute or relative path from src?

Using npm run build then sam package, I'm now only seeing the template getting uploaded to S3 and no zip.
Running my function I get the following error message:

"errorMessage": "Error: Cannot find module 'validator' Require stack: - /var/task/shimd/utils/validate.js - /var/task/shimd/handlers/get-key.js - /var/runtime/UserFunction.js - /var/runtime/index.js"

**Comment by sriram-mv** [comment]
The handler needs to be referenced directly from the location of the CodeUri, so something like `update-key.handler` should work.

I'm going to close this issue, please comment if this did not solve your issue and I can re-open it.

**Comment by mufumade** [comment]
@jfuss I know this is already closed but I hope you can help me out here. 

So I ran into the same problem today the only difference is that I use a lambda with custom swift runtime. I used [this aws sample project](https://github.com/aws-samples/sessions-with-aws-sam/tree/master/swift-custom-runtime) which has the `codeUri` set to the root folder. This is even the case in the [building custom runtimes tutorial from aws](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-custom-runtimes.html).

Is there a way to reduce the size of `sam package` when using custom runtimes ?
