### ISSUE TITLE
sam package generates 0% compresson zip files on Windows

### ISSUE THREAD

**Issue by balihb** [aws/aws-sam-cli#2511]
### Description:

I switch frequently between Linux and Windows. I was trying to deploy the same Lambda as a Lambda@edge function, but I was getting a size error on Windows (on Linux it is perfectly fine, Cloudfront picks up the function without any problem). When I checked the generated zip file on S3, the one generated on Linux had compression, but the one generated on Windows had the same size as the uncompressed content.

I'm using the exact same code, template and sam.

### Steps to reproduce:

Try to deploy a Lambda@edge function and use it in a Cloudformation, that is bigger, than the max size if it is uncrompressed.

### Observed result:

Error: error updating CloudFront Distribution (): InvalidLambdaFunctionAssociation: The function code size is larger than the maximum allowed size for functions that are triggered by a CloudFront event: 2379039 Max allowed: 1048576 Function: arn:

unzip -lv
show for the Windows compressed file:
 2358203          2358203   0%

the Linux one:
 2355821           601440  75%

(a minor code change causes the slight uncompressed difference)

### Expected result:

Use compression on Windows.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 7
2. `sam --version`: SAM CLI, version 1.15.0

`Add --debug flag to command you are running`

**Comment by G4brym** [comment]
It might be that you don't have zlib available on your computer.
Try importing the `zlib` module inside a python shell with:

```python
import zlib
```

If you have any errors importing it, that would explain the missing compression.
You can try to manually install it using the [zlib.install by horta](https://github.com/horta/zlib.install)

**Comment by balihb** [comment]
I used the latest SAM installer for Windows as described in the documentation.

**Comment by mgrandis** [comment]
The issue may come from the fact that we don't specify the compression level when we zip.

From [utils.py line 196](https://github.com/aws/aws-sam-cli/blob/develop/samcli/lib/package/utils.py#L196):
`zip_file = zipfile.ZipFile(f, "w", zipfile.ZIP_DEFLATED)`

Specifying a value may help:
`zip_file = zipfile.ZipFile(f, "w", zipfile.ZIP_DEFLATED, allowZip64=True, compressionlevel=9)`

**Comment by balihb** [comment]
I know it would require changing the possible template parameters, but it would be great to make the compression level configurable
