### ISSUE TITLE
High cpu usage on deploy

### ISSUE THREAD

**Issue by codeasashu** [aws/aws-sam-cli#2518]
### Description:

Sometimes when I try to deploy using sam-cli, it gets stuck and high CPU usage occurs on the system. Here is a screenshot:

![image](https://user-images.githubusercontent.com/1492350/103742765-5c713d00-5021-11eb-86f4-cea4a74464d0.png)

I have tried waiting 5 mins for the command to give me any kind of output, but had to abort due to heavy CPU consumption.

The profile I am providing is working. The `-t template_file` seems to have no impact. Removing it still hangs the cli.
Adding `--debug` to the original command still doesn't output anything. 

### Steps to reproduce:

The issue is intermittent. It occurs once in 5-6 consecutive deploys. Happens on `deploy`

### Observed result:

No output received. Had to abort

### Expected result:

CLI should tell me where it is stuck at?  Don't be windows please?

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS Big Sur v11.1
2. `sam --version`: SAM CLI, version 1.15.0
`Add --debug flag to command you are running`

**Comment by awood45** [comment]
Failing on a `--guided` deploy and hanging is interesting, you should at least be getting prompts first. Can you try adding the `--debug` flag and telling us what you see the next time this hangs?

**Comment by codeasashu** [comment]
@awood45 The `---debug` made no difference in the output. I still see a blank terminal window.

I noticed that while trying to quit (using <kbd>ctrl</kbd> <kbd>c</kbd>), it is taking sometime to quit as well. Upon doing the ctrl-c 2-3 times did let me quit.

**Comment by codeasashu** [comment]
@awood45 An update here. I see a file in my project dir which I vaguely remember as sam output file in yaml format (I accidently deleted it). It was around 18MB. Deleting it made the cli work faster.  I will try again and see what is filename and why is it so huge. I am closing this until I get back with some more information.
