### ISSUE TITLE
context.get_remaining_time_in_millis() returns different value when running with sam local

### ISSUE THREAD

**Issue by jkoisspincar** [aws/aws-sam-cli#2535]
**Description:**
I've found that `context.get_remaining_time_in_millis()` returns different values depending on whether it is running on AWS or from sam local. For example, with a timeout of 20 seconds in AWS, it will return milliseconds as expected, e.g. 19999. However if run using `sam local invoke`, it produces something like 1609409415355.

**Environment:**
- SAM CLI, version 1.15.0
- Ubuntu 18.04.5 LTS
- Python 3.7 (have not tried with other versions)
- boto3==1.16.41
- botocore==1.19.44

**Steps to reproduce the issue:**
1. Write a simple Lambda function like the one below. I used a timeout of 20 seconds.
2. Invoke it using `sam local invoke`.

**Observed result:**
1609409415355

**Expected result:**
19999

**Comment by hoffa** [comment]
Thanks for reporting this! Seems related to #2519.

**Comment by hoffa** [comment]
Closing in favor of #2510, feel free to reopen if there's reason to believe it's a different issue.
