### ISSUE TITLE
pull amazon/aws-sam-cli-build-image-python3.7 image from the Amazon ECR Public Gallery

### ISSUE THREAD

**Issue by guan840912** [aws/aws-sam-cli#2537]
### Describe your idea/feature/enhancement

pull `amazon/aws-sam-cli-build-image-python3.7` from the Amazon ECR Public Gallery

### Proposal

Wish pull `amazon/aws-sam-cli-build-image-python3.7` from the Amazon ECR Public Gallery

to fix this [issue](https://webcache.googleusercontent.com/search?q=cache:70xnAlzJt14J:https://docs.docker.com/docker-hub/download-rate-limit/+&cd=3&hl=zh-TW&ct=clnk&gl=tw)

**Comment by hoffa** [comment]
Related: #2467.

**Comment by hoffa** [comment]
We now publish build images on the [ECR Public Gallery](https://gallery.ecr.aws/?page=1&searchTerm=sam&verified=verified) (e.g. `public.ecr.aws/sam/build-python3.8`).
