### ISSUE TITLE
sam local invoke <container> throws runtime error

### ISSUE THREAD

**Issue by guy16510** [aws/aws-sam-cli#2541]
### Description:
Hello I was running into difficulties debugging a sam container.
Error:
Mounting <path>/<myfunction> as /var/task:ro,delegated inside runtime container
          File "/var/runtime/bootstrap", line 4
            if [ -z "$AWS_LAMBDA_EXEC_WRAPPER" ]; then
                    ^
        SyntaxError: invalid syntax

### Steps to reproduce:
Python 3.8
SAM CLI, version 0.53.0

 >sam build --container

Now debugging:
> sam local invoke "<myfunction>" -e events/<event>.json --debug-port 5890

Throws error:
        Mounting <path>/<myfunction> as /var/task:ro,delegated inside runtime container
          File "/var/runtime/bootstrap", line 4
            if [ -z "$AWS_LAMBDA_EXEC_WRAPPER" ]; then
                    ^
        SyntaxError: invalid syntax

If I don't include the flag "--debug-port 5890" it works. 

### Expected result:
I expected to be provided a running docker container where I could step through with VS Code.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
OSX

**Comment by aahung** [comment]
0.53.0 is more than half a year old. Can you try the latest sam-cli (1.15) to see if this issue still exists?

**Comment by guy16510** [comment]
Upgrading fixed the issue. Thank you
