### ISSUE TITLE
Upload reports total size as a float

### ISSUE THREAD

**Issue by benkehoe** [aws/aws-sam-cli#2545]
This is super minor, but has bugged me for a long time. For uploads, the total size is display as a float. So you see something like:
```
Uploading to a54f4103ec5f859f76bf2866b670c34a.template  6599 / 13198.0  (50.00%)
```
when obviously the total size cannot be a fractional number of bytes. I expect
```
Uploading to a54f4103ec5f859f76bf2866b670c34a.template  6599 / 13198  (50.00%)
```

The code is here, and I believe just changing the third `%s` to `%d` would fix the problem (though you may as well change the second `%s` to `%d` too). Dunno why `self._size` ends up as a float, but that doesn't seem like it needs fixing.
https://github.com/aws/aws-sam-cli/blob/91d6b12b3e00f51ae34b4e9e24abf37d4d9a3ff9/samcli/lib/package/s3_uploader.py#L242

**Comment by mgrandis** [comment]
This should be fixed with 1.18.0: https://github.com/aws/aws-sam-cli/releases/tag/v1.18.0
