### ISSUE TITLE
Invoke a remote function with a local event.json

### ISSUE THREAD

**Issue by G4brym** [aws/aws-sam-cli#2550]
### Describe your idea/feature/enhancement

I wish SAM CLI could invoke the currently deployed version of a given lambda using a local event.json

This would work just like the `sam local invoke FunctionName -e event.json` the only difference is that it would call the latest deployed version in aws and print the output in the terminal.

This could be used to quickly compare an updated local lambda with the remote one to check if the response is still the same.

### Proposal

Things to consider:
1. The event.json would be optional (just like the local invoke)
2. The documentation should be updated to add the new command

Do you think it makes sense for the cli to be able to do this?
What would be a good starting point for someone to tackle this?
Should the command just be `sam invoke FunctionName` or should it go under another "sub-command"

**Comment by mgrandis** [comment]
@G4brym
Thanks again for this draft contribution.
We have also been thinking along these lines and have some thoughts we hope to share soon.
Before you put too much work into this, give us a little bit of time and we'll get back to you.

**Comment by G4brym** [comment]
Ok, I'm looking forward to your feedback and thoughts
Thanks @mgrandis

**Comment by hnnasit** [comment]
Hi @G4brym, this feature has been released in [SAM CLI version 1.88.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.88.0). You can find more info in the [docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/using-sam-cli-remote-invoke.html). Closing this issue.
