### ISSUE TITLE
SAM deploy doesn't detect Type change for Step Function

### ISSUE THREAD

**Issue by travisagentsync** [aws/aws-sam-cli#2557]
### Description:

When changing the `Type` parameter for `Type: AWS::Serverless::StateMachine` from `EXPRESS` to `STANDARD` or vice versa, the change is not detected or deployed to AWS when `sam deploy` is called.

### Steps to reproduce:

Create template with `Type: AWS::Serverless::StateMachine` and `Type` parameter set to either `EXPRESS` or `STANDARD` and deploy to AWS. Then update the `Type` to the opposite value and deploy again. 

### Observed result:

Error: No changes to deploy. Stack _Name_ is up to date

State machine is still defined with previous type

### Expected result:

State machine defined with new type

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Catalina 10.15.7 (19H15)
2. `sam --version`: SAM CLI, version 1.11.0

`Add --debug flag to command you are running`

**Comment by ssenchenko** [comment]
It's not a SAM problem. You cannot change the type of Step Function once you created it. You need to create a new one.

**Comment by cyberfifi** [comment]
What ghost reported is really valuable feedback from a user. It is not a "problem". But SAM could display a warning to make it more user friendly.
