### ISSUE TITLE
Slack Invitation Link in README has expired

### ISSUE THREAD

**Issue by pratikpc** [aws/aws-sam-cli#2595]
### Description:

The invitation link to Slack in the README.md has expired

https://join.slack.com/t/awsdevelopers/shared_invite/zt-idww18e8-Z1kXhI7GNuDewkweCF3YjA

### Steps to reproduce:

Go to [README](https://github.com/aws/aws-sam-cli#join-the-sam-community-on-slack) and click on Slack Link

### Observed result:
![image](https://user-images.githubusercontent.com/28534575/107148336-9911ba80-6978-11eb-9008-3b951cd17cb9.png)

### Expected result:

Joining the Slack channel

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

Trying to login to Slack with a Google Account.

1. OS:
2. `sam --version`:
3. AWS region:

`Add --debug flag to command you are running`

**Comment by mgrandis** [comment]
@pratikpc Do you get this upon clicking on the link or after submitting your email address?
Upon clicking on the link I get the Slack form with options to continue with Google or enter my email address.

**Comment by pratikpc** [comment]
@mgrandis thank you for asking  
Upon clicking the link, it rerouted me to a login page
![image](https://user-images.githubusercontent.com/28534575/107265037-c9855180-6a69-11eb-8edc-c50b679869af.png)

I pressed Contine with Google  

I pressed it, selected my account and then it rerouted me to a link which said Invitation expired

**Comment by mgrandis** [comment]
Thanks @pratikpc 
Can you try again please? 
We generated a new link and it seems that the URL is the same as before.

**Comment by pratikpc** [comment]
@mgrandis thanks
Works for me now
Even I verified right now
The link is the same as you mention and yet it started working

Weird.

Thanks!!!
