### ISSUE TITLE
Ability to set Ratelimit on httpapi via SAM template

### ISSUE THREAD

**Issue by rockey5520** [aws/aws-sam-cli#2596]
I wish there is a way to set Ratelimit on Httpapi via SAM template

Things to consider:
Not sure about how you would implement this to give points for consideration

**Comment by sriram-mv** [comment]
you can override routesettings here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html

It has the the ability to set ratelimits with both normal and burst limits.
