### ISSUE TITLE
`sam deploy` does not use specified S3 bucket in samconfig.toml

### ISSUE THREAD

**Issue by xirkus** [aws/aws-sam-cli#2599]
### Description:
Attempting to use a previously configured S3 bucket for deployments by specifying the `s3_bucket` parameter in the `samconfig.toml` does not work.

### Steps to reproduce:

1. Create an S3 bucket with the same bucket policy as the SAM CLI's dynamically created default source bucket.
1. Update your `samconfig.toml` to include this new bucket's ARN: `s3_bucket = "arn:aws:s3:::bucket-name"` (although I tried with the bucket name as well)
1. Run `sam build --guided`. 

### Observed result:

Note the `Deployment s3 bucket` in the output provided:

```
Deploying with following values
===============================
Stack name                         : process-lambda
Region                                 : us-east-1
Confirm changeset            : True
Deployment image repository  : 
                                       {
                                           "ProcessFunction": "834609584094.dkr.ecr.us-east-1.amazonaws.com/dev-scrb-process"
                                       }
Deployment s3 bucket         : aws-sam-cli-managed-default-samclisourcebucket-1w6spftg6a31d <<<<
Capabilities                           : ["CAPABILITY_IAM"]
Parameter overrides            : {}
Signing Profiles                    : {}
```

### Expected result:

The `Deployment s3 bucket` should use the supplied `s3_bucket` value configured in the `samconfig.toml` file (either `arn:aws:s3:::bucket-name` or `bucket-name`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:MacOS
2. SAM CLI, version 1.17.0
3. AWS region: us-east-1

**Comment by sriram-mv** [comment]
I'm closing this issue as I could not reproduce it with the latest version of the SAM CLI. Please comment if you are still experiencing this.

**Comment by vincentluan** [comment]
I'm still experiencing this with SAM CLI 1.26.0 on Amazon Linux 2 OS

**Comment by hakiour** [comment]
The issue is still happening on SAM CLI v1.37.0

**Comment by bytesbiter** [comment]
Still facing this issue with SAM CLI v1.55.0

**Comment by warrior8792** [comment]
I believe this still exists in SAM CLI v1.66.0

**Comment by pedroGenio** [comment]
same issue SAM CLI, version 1.73.0

**Comment by Axe--** [comment]
Works fine apparently without the `--guided` flag
