### ISSUE TITLE
cli emulation of node14 isn't updated to cli version 1.17

### ISSUE THREAD

**Issue by tnijboer** [aws/aws-sam-cli#2605]
### Description:
The docker image for lambda node 14 version amazon/aws-sam-cli-build-image-nodejs14.x:latest isn't updated to sam cli 1.17 yet, and therefore nodejs14.x isn't supported as runtime.

### Steps to reproduce:

`# docker run -it amazon/aws-sam-cli-build-image-nodejs14.x:latest sam --version
SAM CLI, version 1.16.0`

### Expected result:
Newest version of 1.17.0 in the cli emulation images.

**Comment by hoffa** [comment]
New images have been released:

```shell
% docker pull amazon/aws-sam-cli-build-image-nodejs14.x
% docker run -it amazon/aws-sam-cli-build-image-nodejs14.x sam --version
SAM CLI, version 1.17.0
```
