### ISSUE TITLE
Support later versions of docker in requirements

### ISSUE THREAD

**Issue by tmicheletto** [aws/aws-sam-cli#2619]
It appears as though the docker requirement is pinned at 4.2.x.

We have a generic cicd build container that we use for all our builds which includes tools like `awscli` and `samcli` and we cannot bump the version of `samcli` to the latest version as the requirement for docker 4.2 conflicts with our requirement for 4.4.1 or later.

### Proposal

Allow docker requirement to be satisfied by later versions e.g. 4.4.1

### Additional Details
https://github.com/aws/aws-sam-cli/blob/develop/requirements/base.txt#L11

**Comment by sriram-mv** [comment]
We can definitely think of going to a later version of docker in the future. However, AWS SAM CLI should be treated as it own binary without having any dependencies on a python interpreter. Have you tried having sam cli in its own virtualenv, this way there should be no version conflicts.

**Comment by tmicheletto** [comment]
Yeah fair point. We could look at setting up a virtual env for the sam cli.

**Comment by wchengru** [comment]
Closed it due to inactive for 7 days. Please feel free to reopen it if you need more helps on it.
