### ISSUE TITLE
Functions are bloated

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws/aws-sam-cli#2626]
### Description:

Runing `sam build` produces `.aws-sam/build` which has pretty much everything in it, and when you do `sam deploy` it deploys the entire source code into the function itself, resulting in a bloated function and slow deployments.

I got around the bloated `sam build` by writing my own builder, I learned that `sam build` is actually not required by `sam deploy` as long as the `template.yaml` and `samconfig.toml` are on the same directory as the source codes.

My folder architecture looks like this:

```
/ root
| - ...lots of other unrelated files
| - src
|   | - dependencies <---- this is a layer AWS::Serverless::LayerVersion
|   | - functions <---- this is where all my functions are
|   |    | - ...sub-folders containing all functions
```

Before:

I run the command `sam build && sam deploy` to deploy, after `sam build` my tree would look like this:

```
/ root
| - ...lots of other unrelated files
| - .aws-sam
|    | - build
|    |    | - login <---- this is one of my functions defined in template.yaml
|    |    |    | - login.js
|    |    |    | - ... all other things that the function does not really need <--- this is the problem
|    |    |    | - dependencies <---- even this layer was somehow added here
|    | - build.toml
| - src
|    | - dependencies <---- this is a layer AWS::Serverless::LayerVersion
|    | - functions <---- this is where all my functions are
|    |    | - ...sub-folders containing all functions
```

Now I don't run `sam build` anymore, I run my own build and the build now looks like this:

```
/ root
| - ...lots of other unrelated files
| - build
|    | - login.js
|    | - ...allOthers.js <---- all of them are  just JS files
|    | - dependencies <---- the layer
|    | - template.yaml
| - src
|    | - dependencies <---- this is a layer AWS::Serverless::LayerVersion
|    | - functions <---- this is where all my functions are
|    |    | - ...sub-folders containing all functions
```

Now I jus do `cd build && sam deploy`.

The catch is, It's still bloated because sam will package the entire `build/` folder and make that the base of the function, so when I download the login function, it would look like this:

```
/ root
| - login.js
| - ...allOthers.js <---- all of them are  just JS files
| - dependencies <---- the layer
| - template.yaml
```

When in reality the function is just the JS code itself, like `login.js`, and nothing else, so it SHOULD look like this:

```
/ root
| - login.js
| - template.yaml
```

**FYI:** The layer is a typical NodeJS layer.

```
/ dependencies
| - nodejs
|    | - package.json
|    | - node_modules
|    | - yarn.lock
|    | - ...all other utilities being used by the functions themselves
```

The convention is that the functions are self-contained, any dependencies they need MUST BE pull from the `dependencies` layer, hence the name.

The deployment time was also reduced by half, what was previously 10 minutes, is now just 5 minutes.

### Steps to reproduce:

- `sam build`
- `sam deploy`
- Go to the function and download it, you'll see that it contains the entire project itself, or whatever is in the `files` of `package.json`.

### Observed result:

Functions are bloated.

### Expected result:

Functions SHOULD NOT BE BLOATED. It should only contain the actual function itself, i.e., `login.js`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: N/A
2. `sam --version`: SAM CLI, version 1.17.0
3. AWS region: N/A

`Add --debug flag to command you are running`

**Comment by sriram-mv** [comment]
If I'm reading this right, you are talking about incremental deploys after the first deploy? only the function code gets deployed if there are changes in the handler code alone, and dependencies are left unchanged.

**Comment by aprilmintacpineda** [comment]
@sriram-mv

> If I'm reading this right, you are talking about incremental deploys after the first deploy?

Yes.

**Comment by Envek** [comment]
Unfortunately, you need to set up layers for dependencies by hand. See [Building layers](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-layers.html) doc for details.

Fortunately, I just published step-by-step guide about this in more in my company's blog: [Serverless TypeScript: A complete setup for AWS SAM Lambdas – Martian Chronicles](https://evilmartians.com/chronicles/serverless-typescript-a-complete-setup-for-aws-sam-lambda).

**Comment by aprilmintacpineda** [comment]
I will try that out. What about the rest of the files? Like, the Login function should really only contain `login.js` since that's the only file it needs, but for reasons that I'm not aware of, it contains the other function files as well, like the `register.js` which should not be there.

**Comment by Envek** [comment]
You either can do it manually with Makefile-based builder:
```make
# Makefile
build-LoginFunction:
	cp login.js "$(ARTIFACTS_DIR)/"
build-RegisterFunction:
	cp register.js "$(ARTIFACTS_DIR)/"
```
or you can use TypeScript feature to transpile every handler separately and TypeScript will build only this file and files on which it depends (imports into itself). See [“Bonus: Put only relevant code into your Lambdas functions”](https://evilmartians.com/chronicles/serverless-typescript-a-complete-setup-for-aws-sam-lambda#bonus-put-only-relevant-code-into-your-lambdas-functions) section at the end of my article for details on how to do that.

**Comment by aprilmintacpineda** [comment]
It worked perfectly! and the deployment is now just 3 minutes from originally more than 10 minutes (33 functions). You are awesome @Envek :bow:

**Comment by Envek** [comment]
Wow, great! I'm super glad about such an improvement (we have much smaller set of functions).

However, there is still plenty of space for improvement. For example, current Makefile isn't optimal and have a lot of duuplications (e.g. `npm install` is repeated for every function to install development dependencies).

If you have any ideas on how to improve it further, please open issue or pull request in my [example app](https://github.com/Envek/aws-sam-typescript-layers-example/) or [my cookiecutter template](https://github.com/Envek/aws-sam-typescript-layers-example/).

**Comment by aprilmintacpineda** [comment]
I was able to further reduce `sam deploy` time to 1 minute and 11 seconds, give or take.

**Comment by JasperGabriel** [comment]
Seems like this is still a problem for 2024. 

Cloning default cookie cutter projects with `sam init` and trying to build/deploy out of box still produces bloated functions.
