### ISSUE TITLE
Self-contained linux pacakge should reside in /opt generally

### ISSUE THREAD

**Issue by Congee** [aws/aws-sam-cli#2628]
This issue lies in between a bug and a feature request.

Thank you for making a standalone Linux installer without Homebrew via https://github.com/aws/aws-sam-cli/pull/2597.

As a convention, self-contained packages go to /opt and /opt/bin [1]. By default, this patch installs aws-sam to /usr/local. However, those directories are usually managed by package managers like apt and yum. I do not recommend providing .deb or .rpm packages just because /usr/local is deemed to host aws-sam files. Because, packages there reference libs and configs from /usr/lib and /usr/share.
https://github.com/aws/aws-sam-cli/blob/05895aa651b55e07ae5b585d932d85262982d1bc/installer/assets/install#L65-L66

You may also consider providing a Snap or Flatpak package (not sure if it's possible because binaries are to be sandboxed)

Again, the above applies to only mainstream Linux distributions. Distributions such as Nix have a different filesystem hierarchy standard [2].

Respekt :heart: to you for providing the -i and -b options for custom installation destination directories.

Reference:
[1] https://unix.stackexchange.com/questions/11544/what-is-the-difference-between-opt-and-usr-loca
[2] https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html

**Comment by ssenchenko** [comment]
This feature didn't get much support. Closing for now
