### ISSUE TITLE
Request for using SAM to create alarm on AWS::Logs::MetricFilter 

### ISSUE THREAD

**Issue by rakesh-saiga** [aws/aws-sam-cli#2639]
### Describe your idea/feature/enhancement

It would be super helpful to be able to create alarm on AWS::Logs::MetricFilter created via SAM template

**Comment by rockey5520** [comment]
I am able to do it, no worries. In case, future, if someone is looking for the same here below, is how I got to create metric filter

  Filter:
    Type: AWS::Logs::MetricFilter
    DependsOn: [ LogGroup ]
    Properties:
      LogGroupName:
        Ref: LogGroup
      FilterPattern: "[...,statusCode=4* || statusCode=5* , id ,dot, os, combined]"
      MetricTransformations:
        -
          MetricValue: "1"
          "DefaultValue": 0
          MetricNamespace: "backend"
          MetricName: !Sub ${ Function }_400_&_500_series_errors

**Comment by sriram-mv** [comment]
Closing this issue as its resolved.
