### ISSUE TITLE
samconfig.toml for all sam sub-commands

### ISSUE THREAD

**Issue by ozbillwang** [aws/aws-sam-cli#2644]
### Description:
Go through the [sam config document](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html), 

>For subcommands, the format of the table header is [environment.command_subcommand.parameters]. That is, delimit the command and subcommand with _ (underscore). For example, for the sam local invoke command, the configuration table header is **[default.local_invoke.parameters].**

I want to make all sub-commands to read `samconfig.toml`,  but don't want to duplicate the setting for each sub-command,  so we need add extra lines, as below

```
version = 0.1

[dev]
[dev.local_invoke.parameters]
[dev.build.parameters]
[dev.deploy.parameters]
stack_name = "helloWorld"
```

But when run below commands, I found the sam cli ignores `local_invoke` setting , can't get parameters properly from dev environment with below command

```
sam local invoke --config-env dev
```

It does work with `sam deploy --config-dev`

So I need confirm if my understanding is proper, if not, how to set the `samconfig.toml` to let SAM cli to read `--config-env` properly.

```
$ sam --version
SAM CLI, version 1.18.1
```

**Comment by sriram-mv** [comment]
@ozbillwang This seems to be working for me.

```
[myenv]
[myenv.local_invoke]
[myenv.local_invoke.parameters]
debug = true
```

```
 sam local invoke HelloWorldFunction --config-env myenv
```

This seems to pick up the configuration that was passed in.

**Comment by ozbillwang** [comment]
Thanks, @sriram-mv 

How can I merge them into one, that I don't have to repeat the key/value setting in same environment?

Something like this?

```
[dev]
[dev.local_invoke]
[dev.build]
[dev.deploy]
[dev.local_invoke.parameters]
[dev.build.parameters]
[dev.deploy.parameters]
debug = true
s3_bucket = xxxx
...

```

**Comment by sriram-mv** [comment]
This looks to be what you are after: https://github.com/aws/aws-sam-cli/pull/2580

**Comment by ozbillwang** [comment]
Thanks
