### ISSUE TITLE
No way to pass additional arguments to delve for Go debugging

### ISSUE THREAD

**Issue by hunterwerlla** [aws/aws-sam-cli#2649]
### Description:
Delve does not support `DEBUGGER_ARGS` or any other way to pass arguments to the debugger. This is important to get around `Version of Delve is too old for this version of Go (maximum supported version 1.14, suppress this error with --check-go-version=false)` errors when trying to debug go 1.15 lambdas with goland 2020.1/2020.2

### Steps to reproduce:
Try passing any DEBUGGER_ARGS to delve. `delveArgs` in `runHandler` does not take any additional arguments from the environment or otherwise.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: mac
2. `sam --version`: 1.18.1
3. AWS region: Didn't get that far

**Comment by ssenchenko** [comment]
Closing as inactive
