### ISSUE TITLE
When delve fails to start in a `local invoke`, sam cli exits 0

### ISSUE THREAD

**Issue by hunterwerlla** [aws/aws-sam-cli#2651]
### Description:
When `delve` exists but fails to start (due to something like `Version of Delve is too old for this version of Go (maximum supported version 1.14, suppress this error with --check-go-version=false)`,  run fails and the container exits, but sam cli exits with code `0`

### Steps to reproduce:
- Use an old version of delve to try to debug a go lambda using the latest version of go (1.16)

**Comment by ssenchenko** [comment]
The team is aware of the request. We do not have an update to share at this time. However, we do tag PRs with issues they solve. Once the team prioritizes and solves it, you will be able to see that link in the issue

**Comment by jfuss** [comment]
Going to close this due to age and activity. Please upgrade to the latest version and if it is still occurring create a new issue.
