### ISSUE TITLE
quiet mode for local invoke

### ISSUE THREAD

**Issue by HP4k1h5** [aws/aws-sam-cli#2653]
### Describe your idea/feature/enhancement

to cut down on noise when running `sam local invoke` one can redirect stderr like
```
sam local invoke TestLambda 2> /dev/null
```

which removes 
```
TestLayer is a local Layer in the template
Building image............
```
from the output. However if `sam` is not up to date you can still get this message. 

```
SAM CLI update available (1.18.2); (1.18.1 installed)
To download: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html
```
on shared runners etc, its not easy to update `sam`.

### Proposal

this problem can be solved a number of ways. 
1) provide a `--quiet` flag for `sam local invoke` to eliminate all non response/error text in the output
2) change https://github.com/aws/aws-sam-cli/blob/223999e6fec448484a8b24668f81ba7c2c214612/samcli/lib/utils/version_checker.py#L92 to use `err=True` parameter
```
click.echo('Hello World!', err=True)
```

**Comment by moelasmar** [comment]
the PR resolving this issue got merged.
