### ISSUE TITLE
Installation with homebrew fails with Error 404

### ISSUE THREAD

**Issue by siliconchris** [aws/aws-sam-cli#2659]
### Description:
Following the installation instructions from 
  https://docs.aws.amazon.com/de_de/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html

leads to the error 
   curl: (22) The requested URL returned error: 404 

### Steps to reproduce:
brew tap aws/tap
==> Tapping aws/tap
Cloning into '/usr/local/Homebrew/Library/Taps/aws/homebrew-tap'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 1078 (delta 36), reused 12 (delta 5), pack-reused 1013
Receiving objects: 100% (1078/1078), 206.85 KiB | 967.00 KiB/s, done.
Resolving deltas: 100% (555/555), done.
Tapped 9 formulae (50 files, 298.5KB).
chris@DeepThought Taps % brew install aws-sam-cli
==> Installing aws-sam-cli from aws/tap
==> Downloading https://github.com/aws/aws-sam-cli/releases/download/v1.18.2//aws-sam-cli-1.19.0.sierra.bottle.tar.gz
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "aws-sam-cli"
Download failed: https://github.com/aws/aws-sam-cli/releases/download/v1.18.2//aws-sam-cli-1.19.0.sierra.bottle.tar.gz

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

`Add --debug flag to command you are running`

**Comment by hawflau** [comment]
Hi @siliconchris 
We were releasing SAM CLI v1.19.0 around 3 hours ago. That might be why you got `Download failed: https://github.com/aws/aws-sam-cli/releases/download/v1.18.2//aws-sam-cli-1.19.0.sierra.bottle.tar.gz`.

The release has been completed. I tried to install SAM CLI just a moment ago and it worked fine. Note that the download path is `https://github.com/aws/aws-sam-cli/releases/download/v1.19.0//aws-sam-cli-1.19.0.sierra.bottle.tar.gz`. Could you please try install again?

**Comment by osjerick** [comment]
This is happening to me too. I've just tried the install:

```bash
brew upgrade aws-sam-cli
==> Upgrading 1 outdated package:
aws/tap/aws-sam-cli 1.18.2 -> 1.19.1
==> Upgrading aws/tap/aws-sam-cli 1.18.2 -> 1.19.1
==> Downloading https://github.com/aws/aws-sam-cli/releases/download/v1.19.0//aws-sam-cli-1.19.1.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404
Error: Failed to download resource "aws-sam-cli"
Download failed: https://github.com/aws/aws-sam-cli/releases/download/v1.19.0//aws-sam-cli-1.19.1.sierra.bottle.tar.gz
```

**Comment by siliconchris** [comment]
I found the source of the errror - the tap has a wrong bottle-config. In file

aws-sam-cli.json

in directory 

/usr/local/Homebrew/Library/Taps/aws/homebrew-tap/bottle-configs

the root-url entry points to v1.18.2 where it should read 1.19.0

if you simply change that entry, all works fine. Closing the issue.

**Comment by siliconchris** [comment]
I found the source of the errror - the tap has a wrong bottle-config. In file

aws-sam-cli.json

in directory 

/usr/local/Homebrew/Library/Taps/aws/homebrew-tap/bottle-configs

the root-url entry points to v1.18.2 where it should read 1.19.0

if you simply change that entry, all works fine. Closing the issue.
