### ISSUE TITLE
requirements/pre-dev.txt missing from 1.19.0 release file on PyPi

### ISSUE THREAD

**Issue by javmorin** [aws/aws-sam-cli#2660]
### Description:
1.19.0 release package is missing `requirements/pre-dev.txt` which is required by the setup.

### Steps to reproduce:
- Download tarball from pypi
- Upack tarball
- execute `python setup.py install`

### Observed result:
```
$ python setup.py install
Traceback (most recent call last):
  File "/home/user/aws-sam-cli/src/aws-sam-cli-1.19.0/setup.py", line 60, in <module>
    extras_require={"pre-dev": read_requirements("pre-dev.txt"), "dev": read_requirements("dev.txt")},
  File "/home/user/aws-sam-cli/src/aws-sam-cli-1.19.0/setup.py", line 21, in read_requirements
    content = read(os.path.join("requirements", req))
  File "/home/user/aws-sam-cli/src/aws-sam-cli-1.19.0/setup.py", line 15, in read
    with io.open(filename, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements/pre-dev.txt'
```

### Expected result:
- Successful install

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Arch Linux
2. `sam --version`: 1.19.0
3. AWS region: N/A

**Comment by mndeveci** [comment]
Thanks @javmorin for reporting this!

We released a new version ([v1.19.1](https://github.com/aws/aws-sam-cli/releases/tag/v1.19.1)) which resolves the issue that you mentioned. I verified it by running the steps as you mentioned;
```
/tmp/sam-cli-tarball/aws-sam-cli-1.19.1
.venv ❯ ../.venv/bin/sam --version
SAM CLI, version 1.19.1
```

Please re-open this issue if you update and see the same problem, or file a new issue if you find other issues. 
Thanks again for reporting this!
