### ISSUE TITLE
sam build --debug fails with a Serverless::LayerVersion

### ISSUE THREAD

**Issue by ppena-LiveData** [aws/aws-sam-cli#2666]
### Description:
When I ran `sam build --debug` for a `template.yaml` with a `Serverless::LayerVersion`, it showed this error (along with other, non-important details) then failed to build:
```python
--- Logging error ---
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/var/lang/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/var/lang/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/var/lang/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
  File "/var/lang/lib/python3.8/site-packages/samcli/lib/build/build_graph.py", line 353, in __str__
    f"LayerBuildDefinition({self.name}, {self.codeuri}, {self.source_md5}, {self.uuid}, "
AttributeError: 'NoneType' object has no attribute 'name'
```

### Steps to reproduce:

1. `sam init` and choose the following:
  - 1 - AWS Quick Start Templates
  - 1 - Zip
  - 2 - python3.8
  - 1 - Hello World Example
2. Edit `template.yaml` to add this to the `Properties` of `HelloWorldFunction`:
```
      Layers:
        - !Ref MyLayer
```
3. Add this to `template.yaml`:
```
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: test-layer
      ContentUri: my_layer
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 and Linux
2. `sam --version`: SAM CLI, version 1.18.2 and 1.19.1 and 1.20.0

### Proposed fix
It appears the problem is that [LayerBuildDefinition.\_\_str__()](https://github.com/aws/aws-sam-cli/blob/5e87f9c2982abec90ab08948cef8de2397cb7669/samcli/lib/build/build_graph.py#L351) tries to print `self.layer.name`, but `self.layer` is `None`, so I just changed `self.layer.name` in the `f` string to this: `self.layer.name if self.layer else None`

**Comment by mndeveci** [comment]
Resolving this issue since it has been released with [SAM CLI v1.24.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.24.0).
