### ISSUE TITLE
Cache Use Hard/Soft Link for Instead of Copying All the Files

### ISSUE THREAD

**Issue by OGoodness** [aws/aws-sam-cli#2688]
### Description
Currently with SAM, you are able to specify a cache, which is nice. But sometimes, using that cache is actually slower than just running a regular `sam build`. SAM copies all the files from the cache, and then writes them in the build directory. This is a lot of I/O operations, and can take forever on old and newer computers, especially if your project runs in node. 

### Proposal
Instead of copying all the files directly, how about you create a symbolic or hard link to each files. This way, there will be less overhead when performing builds, no need to copy the entire file, just create a reference to the associated file. 

Maybe this isn't the default way of doing it, but provide an option to do so. Maybe a parameter you can pass into the `--cached` parameter? 

Things to consider:
1. Speed up builds significantly
2. Saves disk space

### Additional Details
This might introduce issues where, a user decides to manually edit a hard link, and that will effect the original cache. But I think this feature would be a great optional use.

**Comment by rdt712** [comment]
I agree with this. I'm not sure what the solution is, but I've also had a bad experience using a cached build in Node. It takes longer than a normal build and I've never gotten it to work like I would expect at a normal cache to work.

**Comment by CoshUS** [comment]
Thanks for the feedback. For compatibility reasons, symlink might not be the solution as Windows has poor support for it. We will look into other avenues to improve the cached performance.

**Comment by mildaniel** [comment]
Support for this has been released in 1.54.0! You can now use this functionality using the `experimentalBuildPerformance` feature flag!

**Comment by timmattison** [comment]
@mildaniel is there an example of how to use these feature flags? I can find it in the code, and it looks like it can be specified as an environment variable but it would be good to be sure I'm doing it right so I can make a comparison.
