### ISSUE TITLE
Define the Event format for `sam local invoke -e`

### ISSUE THREAD

**Issue by TobyHFerguson** [aws/aws-sam-cli#2704]
### Describe your idea/feature/enhancement

The docs for the  `-e` option to `sam local invoke` talk about an event file, but nowhere does it describe the exact format for this file. It would be good if there was a clear explanation of exactly what the format and syntax of that file was, including any keywords, values etc. etc. 

### Proposal

This is merely documentation - no changes to the product per se

**Comment by wchengru** [comment]
Hi @TobyHFerguson , please refer to this document: https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-concepts.html#gettingstarted-concepts-event
Also, you can use `sam local generate-event` command to generate a JSON file of the event.
Meanwhile, we will make the document more clear on this parameter.

**Comment by sriram-mv** [comment]
Closing this issue as @wchengru has responded with the command for generating events.
