### ISSUE TITLE
Referencing local libraries from parent directory fails quietly

### ISSUE THREAD

**Issue by jyoungs** [aws/aws-sam-cli#2705]
**Description:**

Prior to using SAM, it was common for me to import "internal libraries" into my lambda package by referencing them in the requirements file:

```
/project
  /shared_lib
    /<code>
    /setup.py
  /lambda_1
    /<code>
    /requirements.txt <- this will contain "../shared_lib"
```

When I run `pip install -r lambda_1/requirements.txt -t deployment_package` this will add shared_lib to the deployment_package. 

It seems in sam, this is wholly unsupported. When I run `sam build`, it runs successfully, but the deployment package doesn't actually contain the shared_lib (so it fails at runtime). It appears that sam is using `pip download` instead of `pip install`, which includes the dependencies from shared_lib/setup.py, but not shared_lib itself.

Tangentially: This fails when trying to run in a container (sam build -c), but I care a lot less because at least it fails at build time.

_I have a workaround for this where I reference local packages using layers, but it seems pretty awful that this "works" until runtime._

**Steps to reproduce the issue:**
1. Setup a library at the same level as your SAM lambda (ie. clone [somepackage](https://github.com/bast/somepackage))
2. Add the library reference to your SAM lambda requirements.txt (`../somepackage`)
3. Run sam build

**Observed result:**
- .aws-sam/build/<yourLambdaFunction>/ does not contain `somepackage `

**Expected result:**
- .aws-sam/build/<yourLambdaFunction>/ contains `somepackage `
- OR this fails

**Comment by wchengru** [comment]
I will close one because the question is answered. Please feel free to reopen it if you have more questions.

**Comment by jyoungs** [comment]
> I have a workaround for this where I reference local packages using layers, but it seems pretty awful that this "works" until runtime.

@wchengru  - odd to close an issue as "answered" when the supposed answer was in the issue as it was opened.

You're saying it is not a bug when a command "succeeds" but doesn't actually perform the requested operation? I don't understand why you wouldn't want to improve this. Ideally this would just work, but **at worst** it should fail well before runtime.

**Comment by wchengru** [comment]
Thanks for clarification, @jyoungs.
It's a feature to allow user to load local dependencies rather than downloading all of them. As you said and according to the [document](https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/python_pip/DESIGN.md), we are currently downloading all dependencies. I will retag this as a feature request, and discuss with our team about the next step of it.

**Comment by mndeveci** [comment]
Resolving this issue since SAM CLI already includes the Lambda Builders with following PR https://github.com/aws/aws-lambda-builders/pull/250
