### ISSUE TITLE
Any plans to support SAM on the t4g series of instances

### ISSUE THREAD

**Issue by MaseratiPilot** [aws/aws-sam-cli#2713]
### ARM Binary Support

I'd like to use the SAM CLI on a t4g instance in a remote env to keep things within the AWS (off local system) and for some automated processing thus I need a version of the SAM CLI that work on ARM processors.

Additionally as the laptops move to ARM for MAC, Linux and ChromeOS there might be more and more of a need for ARM binary support for those platforms as well.

**Comment by wchengru** [comment]
Hi @MaseratiPilot , 
Thanks for reporting this! Can you describe the issues you have when installing or running SAM CLI on an ARM computer?

**Comment by MaseratiPilot** [comment]
Can't even install the SAM CLI.

Executable won't even run.

Tom
AWS Professional Architect

**Comment by KyleTryon** [comment]
Hello,
I too am hoping to request ARM support (it looks like x86_64 is the only supported architecture at the moment). This would be used by the [CircleCI AWS SAM Serverless Orb](https://circleci.com/developer/orbs/orb/circleci/aws-sam-serverless) to enable its usage in ARM execution environments on CircleCI (running on Graviton).

Thank you .

**Comment by davenorthcreek** [comment]
cloned from github
ln -s /usr/bin/pip3 /usr/bin/pip
sudo make

`[ec2-user@ip-172-30-2-51 aws-sam-cli]$ sam --version`
`-bash: /usr/local/bin/sam: cannot execute binary file`

**Comment by endymion** [comment]
> cloned from github
> ln -s /usr/bin/pip3 /usr/bin/pip
> sudo make
> 
> `[ec2-user@ip-172-30-2-51 aws-sam-cli]$ sam --version`
> `-bash: /usr/local/bin/sam: cannot execute binary file`

I can't even get that far.  In my case, from an M6g instance, `make` seems happy with itself, but it doesn't seem to have installed anything:

    [ec2-user@ip-172-31-37-179 aws-sam-cli-1.23.0]$ sudo make
    ...
    Successfully installed aws-sam-cli
    [ec2-user@ip-172-31-37-179 aws-sam-cli-1.23.0]$ sam --version
    bash: sam: command not found

I'm working on a Component for an Image Recipe for EC2 Image Builder for installing SAM on a Gravitron2 instance with Amazon Linux 2.  So far, it looks something like:

    name: AWS SAM
    description: IaC DSL for CloudFormation.
    schemaVersion: 1.0
    phases:
      - name: build
        steps:
          - name: SAMInstallStep
            action: ExecuteBash
            inputs:
              commands:
                - sudo yum -y groupinstall "Development Tools"
                - sudo python3 -m ensurepip
                - sudo yum -y install python3-devel
                - sudo yum -y install openssl-devel curl-devel
                - sudo pip3 install awscli --upgrade
                - sudo ln -s /usr/bin/pip3 /usr/bin/pip
                - # clone SAM
                - # sudo make

A Yum package for this would be fantastic.  The NPM package for the CDK is tempting me to switch.

**Comment by endymion** [comment]
The old PIP installation that [apparently](https://www.virtuability.com/posts/2020/08/use-the-raspberry-pi-4-for-aws-development-part-1-installation/) used to work for ARM architectures doesn't work any more.

Here's me attempting to install the AWS SAM CLI on a Gravitron2-based EC2 M6g Amazon Linux 2 instance using PIP:

https://gist.github.com/endymion/a5381dad4987c69bda9ec2141bf2b960

**Comment by jfuss** [comment]
De-duplicating with the "Support ARM intstaller": https://github.com/aws/aws-sam-cli/pull/3216

Closing
