### ISSUE TITLE
how to pin specific aws sam verision in github actions ?

### ISSUE THREAD

**Issue by rakesh-saiga** [aws/aws-sam-cli#2714]
Question:
How does the gihub action file installs SAM here in this https://github.com/aws-samples/aws-sam-github-actions-example ? is this pre-installed on Ubuntu ?

if i want to use a specific aws sam version, how do i do it ?

**Comment by spitzzz** [comment]
Hi @rakesh-saiga - I responded to the issue you opened on the `aws-sam-github-actions-example` - but will also provide my response here for visibility to others. Given this issue is related to the other repository, lets try to have our conversation there instead.

https://github.com/aws-samples/aws-sam-github-actions-example/issues/3

```
To do this you would need to change the image used by the workflow. The current image being used is specified as ubuntu-latest in the workflows here.

Primary workflow: https://github.com/aws-samples/aws-sam-github-actions-example/blob/main/.github/workflows/primary.yml#L8

Secondary workflow: https://github.com/aws-samples/aws-sam-github-actions-example/blob/main/.github/workflows/secondary.yml#L8

SAM is pre-installed on this image, as seen in the documentation here:
https://github.com/actions/virtual-environments/blob/ubuntu20/20210309.1/images/linux/Ubuntu2004-README.md

You could potentially build your own image with the specified version of SAM you would like to use, or create your own custom logic to potentially uninstall/reinstall SAM with a specified version.

Or use a different image that has the specified version of SAM you are trying to use.
```

**Comment by rakesh-saiga** [comment]
Thanks @spitzzz  for the response.
