### ISSUE TITLE
nested stacks vs. --base-dir

### ISSUE THREAD

**Issue by mbradburn** [aws/aws-sam-cli#2721]
### Description:
Are we confident that the current behavior of 'sam build' when building a nested-stack application
is correct when the --base-dir flag is given?  I made an example at https://github.com/mbradburn/sam-example.

In the example there's a top-level template which refers to a nested application in the 'nested' subdirectory.
When 'sam build' is invoked from the directory containing the top-level template, it seems like the default base-dir
is ".", but giving that flag explicitly causes 'sam build' to fail.  I guess you're resolving every template's CodUri's
with respect to the base-dir and disregarding the relative path from the root template to the nested template,
is that intentional?

### Steps to reproduce:
See 'test.sh' in https://github.com/mbradburn/sam-example.git.

### Observed result:
The 'sam build' command fails when an explicit value is given for --base-dir.

### Expected result:
I was expecting CodeUri's in the nested template to be resolved from the base-dir plus the relative
path from the root template to the nested template but maybe this was not a reasonable expectation.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`:SAM CLI, version 1.21.1
3. AWS region: us-west-2

`Add --debug flag to command you are running`

**Comment by aahung** [comment]
It was intentional, according to the doc 

> Resolves relative paths to the Lambda function's source code with respect to this directory. Use this option if the AWS SAM template and your source code aren't in the same directory. By default, relative paths are resolved with respect to the template's location. 

When `--base-dir` is provided, function's `CodeUri` are no longer resolved with respect to template's location. This applies to all functions in all child stacks.

**Comment by mbradburn** [comment]
Thanks for the clarification, I appreciate it!
