### ISSUE TITLE
add deploy --outputs-file option, like AWS CDK

### ISSUE THREAD

**Issue by paulie4** [aws/aws-sam-cli#2722]
### Describe your idea/feature/enhancement

I wish SAM CLI would have an `--outputs-file` optional CLI argument for `sam deploy`, like the one `cdk deploy` has, see [the CDK docs](https://docs.aws.amazon.com/cdk/latest/guide/cli.html#w109aac23b7c33c13). Right now, it only prints the outputs in an ASCII table, mixed in with all the other stuff that goes to stdout, which of course is not machine readable, forcing a user to have to write a separate program to query CloudFormation to get the outputs.

**Comment by Raaghu** [comment]
👍🏽

**Comment by jaymecd** [comment]
looking forward, faced today with same request.

**Comment by domfp13** [comment]
any update on this?

**Comment by oharkins** [comment]
Any update on this? I could really use this as well!

**Comment by mildaniel** [comment]
We will soon be releasing a new command called `sam list` which will have a sub-command called `stack-outputs`. This will allow you to output your CloudFormation stack outputs in a table format or in JSON format. 

Pull request: https://github.com/aws/aws-sam-cli/pull/4587

**Comment by mildaniel** [comment]
This feature has now been released in version 1.72.0!
