### ISSUE TITLE
"sam local invoke --debug-args" prints spurious "unrecognized arguments" warning

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-sam-cli#2723]
### Description:

Since SAM CLI 1.20 we are now seeing this warning:

    Ignoring unrecognized arguments: ['/tmp/lambci_debug_files/py_debug_wrapper.py', '--listen', '0.0.0.0:5858', '--wait-for-client']. Only "-delveAPI" is supported.

### Steps to reproduce:

Appears to happen with any `sam local invoke` invocation that gives `--debug-args`. 

Example:

```
sam local invoke --debug HelloWorldFunction --template /tmp/aws-toolkit-vscode/vsctk9OTnN7/output/template.yaml --event /tmp/aws-toolkit-vscode/vsctk9OTnN7/event.json --env-vars /tmp/aws-toolkit-vscode/vsctk9OTnN7/env-vars.json -d 5858 --debugger-path /codebuild/output/src710492448/src/github.com/aws/aws-toolkit-vscode/resources/debugger --debug-args /tmp/lambci_debug_files/py_debug_wrapper.py --listen 0.0.0.0:5858 --wait-for-client
```

### Observed result:

The local invoke seems to work, but sam cli prints this warning:

    Ignoring unrecognized arguments: ['/tmp/lambci_debug_files/py_debug_wrapper.py', '--listen', '0.0.0.0:5858', '--wait-for-client']. Only "-delveAPI" is supported.

### Expected result:

Don't print spurious warning.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. `sam --version`: 1.20, 1.21
3. AWS region: all

**Comment by aahung** [comment]
released in 1.22.0
