### ISSUE TITLE
Issue when use sam deploy with tags

### ISSUE THREAD

**Issue by esteban1983cl** [aws/aws-sam-cli#2769]
### Description:
Unable to run sam deploy when use tags

### Steps to reproduce:
Use docker image python-3.8.8-alpine-3.13 

Execute this command: 

```shell
sam deploy --template-file ./templates/${CI_ENVIRONMENT_NAME}/package.yaml --stack-name AWSConfigEventListener --capabilities CAPABILITY_IAM --no-confirm-changeset --s3-bucket ${BUCKET_NAME} --region $AWS_REGION --tags $TAGS
```

where the $TAGS are:

```shell
ambiente=staging pais=cl ceco=cgo1007324 cuenta=xxxxxxxxx proyecto="Plataformas TxD" aplicacion="DevOps Tools" nombre=AWSConfigEventListener Name=AWSConfigEventListener propietario=esteban.avendano@xxxxxx.cl tribe="Arquitectura y Plataforma" epm=opex ApplicationName="Plataformas TxD" BusinessUnit=SHARED
```

### Observed result:

Usage: sam deploy [OPTIONS]
Try 'sam deploy -h' for help.
Error: Invalid value for '--tags': ('ambiente=staging', 'pais=cl', 'ceco=cgo1007324', 'cuenta=xxxxxxx', 'proyecto="Plataformas', 'TxD"', 'aplicacion="DevOps', 'Tools"', 'nombre=AWSConfigEventListener', 'Name=AWSConfigEventListener', 'propietario=esteban.avendano@xxxxxx.cl', 'tribe="Arquitectura', 'y', 'Plataforma"', 'epm=opex', 'ApplicationName="Plataformas', 'TxD"', 'BusinessUnit=SHARED') is not in valid format. It must look something like 'KeyName1=string KeyName2=string'

### Expected result:
Deploy succesfull

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux Alpine 3.13
2. `sam --version`: SAM CLI, version 1.21.1
3. AWS region: us-east-1 

`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
the issue in supporting tag values that have spaces like:
proyecto="Plataformas TxD"
work around is to replace these spaces with underscore, it will work.

**Comment by esteban1983cl** [comment]
> the issue in supporting tag values that have spaces like:
> proyecto="Plataformas TxD"
> work around is to replace these spaces with underscore, it will work.

But I need spaces, what can I do ?

**Comment by moelasmar** [comment]
sorry I was mistaken, the issue is not in sam, sam can handle the spaces in tags values.
The issue in how $TAGS environment variable value got passed to sam  
if you change the command to be as following, it will work:

```
sam deploy --template-file ./templates/${CI_ENVIRONMENT_NAME}/package.yaml --stack-name AWSConfigEventListener --capabilities CAPABILITY_IAM --no-confirm-changeset --s3-bucket ${BUCKET_NAME} --region $AWS_REGION --tags "$TAGS"

```

**Comment by moelasmar** [comment]
Please let me know if this solves the issue

**Comment by esteban1983cl** [comment]
> Please let me know if this solves the issue

Hi Mohamed, I tried this before and I get stuck my job in this step. Additionally I tried different combinations like with not success results:

proyecto=\"Plataformas TxD\"
proyecto="Plataformas\ TxD"

Thanks.

**Comment by moelasmar** [comment]
did you try to set the tags environment variable like this
```--tags "$TAGS"```

as I tried in my side and it was working fine

**Comment by moelasmar** [comment]
these are the steps I did:
```
export TAGS='ambiente=staging pais=cl ceco=cgo1007324 cuenta=xxxxxxxxx proyecto="Plataformas TxD" aplicacion="DevOps Tools" nombre=AWSConfigEventListener Name=AWSConfigEventListener propietario=esteban.avendano@xxxxxx.cl tribe="Arquitectura y Plataforma" epm=opex ApplicationName="Plataformas TxD" BusinessUnit=SHARED'
```
then when I run the following command, I got the error
```
sam deploy -t template.yaml --tags $TAGS
Error: Invalid value for '--tags': ('ambiente=staging', 'pais=cl', 'ceco=cgo1007324', 'cuenta=xxxxxxxxx', 'proyecto="Plataformas', 'TxD"', 'aplicacion="DevOps', 'Tools"', 'nombre=AWSConfigEventListener', 'Name=AWSConfigEventListener', 'propietario=esteban.avendano@xxxxxx.cl', 'tribe="Arquitectura', 'y', 'Plataforma"', 'epm=opex', 'ApplicationName="Plataformas', 'TxD"', 'BusinessUnit=SHARED') is not in valid format. It must look something like 'KeyName1=string KeyName2=string'
```
But when I executed as following, deployment done successfully 
```
sam deploy -t template.yaml --tags "$TAGS"
.....
Successfully created/updated stack - sam-app-test-parameters in us-east-1
```

**Comment by esteban1983cl** [comment]
Hi, I said when I use "$TAGS" my pipeline job get stuck. 
The docker images that I'm using are alpine or debian (ubuntu) based with same results.

But the same in my command line in OSX works perfect.
So, some recommendation about operative system or shell configuration for instance ?

**Comment by wchengru** [comment]
Hi @esteban1983cl, can you please try adding the `tags` option into the toml config file? In `samconfig.toml` file, add the following to the end of it. It won't be dependent on OS.
`tags = 'ambiente=staging pais=cl ceco=cgo1007324 cuenta=xxxxxxxxx proyecto="Plataformas TxD" aplicacion="DevOps Tools" nombre=AWSConfigEventListener Name=AWSConfigEventListener propietario=esteban.avendano@xxxxxx.cl tribe="Arquitectura y Plataforma" epm=opex ApplicationName="Plataformas TxD" BusinessUnit=SHARED'`

`sam deploy --debug` will show the command line parameters:

`--tags={'ambiente': 'staging', 'pais': 'cl', 'ceco': 'cgo1007324', 'cuenta': 'xxxxxxxxx', 'proyecto': 'Plataformas TxD', 'aplicacion': 'DevOps Tools', 'nombre': 'AWSConfigEventListener', 'Name': 'AWSConfigEventListener', 'propietario': 'esteban.avendano@xxxxxx.cl', 'tribe': 'Arquitectura y Plataforma', 'epm': 'opex', 'ApplicationName': 'Plataformas TxD', 'BusinessUnit': 'SHARED'}`

**Comment by xazhao** [comment]
Closing because it has been inactive for 2 weeks. Feel free to reopen it if you have any other questions.
