### ISSUE TITLE
Print Outputs even when no changes to deploy

### ISSUE THREAD

**Issue by SamuelCook** [aws/aws-sam-cli#2770]
### Describe your idea/feature/enhancement

Our CI pipeline reads the values contained in the Outputs section to discover the IDs and URIs of deployed resources, and uses these to perform automated testing.

However, when `sam deploy` detects that no changes have been made to the stack since the last deployment, it omits the Outputs section and prints only
```
No changes to deploy. Stack <stackname> is up to date.
```

The omission of these values means we either have to store them externally for each branch and retrieve them on future builds in which no changes have been deployed, which is fragile and prone to error, or to fail the build, which is inefficient and requires manual intervention. Currently we fail the build.

This is especially irritating in the case where a commit only adds new automated tests - the stack would not be deployed, no outputs are communicated, so the new tests are not run.

### Proposal

It would be very useful always to include the stack Outputs in this message, even when no changes to the deployed stack are required.

This would allow the CI environment to consume these outputs and perform tests on the already-deployed stack.

**Comment by sriram-mv** [comment]
There is now a dedicated command for this.

Its called `sam list` and you get outputs with `sam list stack-outputs`
