### ISSUE TITLE
Typo in the generated README files with `sam init`

### ISSUE THREAD

**Issue by redouane-dev** [aws/aws-sam-cli#2774]
In the README file generated with `sam init`, in the section **Deploy the sample application**, there is a typo:
> ...To deploy an AWS CloudFormation stack which creates or _modified_ IAM roles...

Should be
> ...To deploy an AWS CloudFormation stack which creates or _modifies_ IAM roles...

**Comment by moelasmar** [comment]
PR got merged, and waiting for release

**Comment by redouane-dev** [comment]
Thanks a lot 😊

**Comment by aahung** [comment]
released in 1.22.0
