### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by mbacchi** [aws/aws-sam-cli#2776]
### Describe your idea/feature/enhancement

Python 3.9 is the system Python version on Fedora 33 and above, and has been GA since 10/2020. Python 3.9 should be supported by aws-sam-cli.

### Proposal

Add details of how to add this to the product.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

**Comment by sapessi** [comment]
AWS Lambda [doesn't support Python3.9 today](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#w305aac35c29) as a function runtime, so there is no reason to include it as part of the SAM Specs. However, I agree that the SAM CLI should work correctly on machines running Python 3.9 as the default runtime. Are you getting errors when trying to run the SAM CLI?

**Comment by ashkue** [comment]
I do not have errors running SAM CLI on Python 3.9, however since SAM CLI is managed by Homebrew on my laptop it pulls python3.8 as a dependency. And right now it is last package among my list that requires python3.8

**Comment by baali** [comment]
I have an error when I try to build for python3.8 runtime with a machine having just Python3.9:

```
% sam build
Building codeuri: api/hello_world runtime: python3.8 metadata: {} functions: ['HelloWorldFunction']

Build Failed
Error: PythonPipBuilder:Validation - Binary validation failed for python, searched for python in following locations  : ['.direnv/python-venv-3.9.6/bin/python', '/usr/bin/python'] which did not satisfy constraints for runtime: python3.8. Do you have python for runtime: python3.8 on your PATH?
```

**Comment by jlgoolsbee** [comment]
As of yesterday, Python 3.9 is a valid runtime for AWS Lambda: https://aws.amazon.com/blogs/compute/python-3-9-runtime-now-available-in-aws-lambda/

Will this issue track work to add the python3.9 runtime support, or should this issue remain specific to potential non-runtime issues related to Python 3.9?

**Comment by jfuss** [comment]
SAM CLI supports Python3.9 (as installation and runtime). Looks like some responses here are about Homebrew. We track those issues here: https://github.com/aws/homebrew-tap/issues. I am not sure what the concern is about Py3.8 being used though, as it is still supported version.

It is unclear what the original purpose of this was, given we support Python versions greater than 3.6 (according to our setup.py: https://github.com/aws/aws-sam-cli/blob/develop/setup.py#L57

**Comment by awood45** [comment]
Closing
