### ISSUE TITLE
Working examples of using CORS with Lambdas that respond to HttpAPI events

### ISSUE THREAD

**Issue by xirkus** [aws/aws-sam-cli#2778]
### Describe your idea/feature/enhancement

I wish the documentation had a working example of a Lambda function with CORS. Seeing as a Lambda responding to an HttpAPI event _CANNOT_ function without CORS being enabled, this is kind of essential to get a working example.

### Proposal

There should be two examples:

1. One where the `Type: Api` Event for a function supports CORS.
2. Another example of the resources/configuration required to explicitly declare an working HttpAPI with the appropriate CORS/permissions to invoke the Lambda.

Things to consider:
1. Not sure this will require updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model), but given the challenges I encountered trying to get this to work, most likely.

### Additional Details

How about having the Sessions with SAM guys talk about this?

**Comment by ssenchenko** [comment]
Closing as an inactive
