### ISSUE TITLE
sam build Error: CustomMakeBuilder:Resolver - Path resolution for runtime: provided of binary: make was not successful

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws/aws-sam-cli#2782]
### Description:

I'm building my app with SemaphoreCI, using this docker container that I created https://hub.docker.com/repository/docker/aprilmintacpineda/aws-sam-cli-deploy-nodejs this docker container worked perfectly before, but that was before I created my own `Makefile`, when I started using `Makefile`, `sam build` started to give me this error: `https://hub.docker.com/repository/docker/aprilmintacpineda/aws-sam-cli-deploy-nodejs`, but I have tried building this with GitHub actions and was able to successfully build it, I'm guessing it has to do with the docker container, possibly a missing component.

### Steps to reproduce:

Use my Docker file to build AWS Sam with custom Makefile that looks like this:

```makefile
.PHONY: build-fn1 build-fn2 build-fn3

build-fn1:
	cp fn1.js "${ARTIFACTS_DIR}/fn1.js"

build-fn2:
	cp fn2.js "${ARTIFACTS_DIR}/fn2.js"

build-fn3:
	cp fn3.js "${ARTIFACTS_DIR}/fn3.js"

build-my-layer:
	mkdir -p "$(ARTIFACTS_DIR)/nodejs"
	cp -r . "$(ARTIFACTS_DIR)/nodejs/"
	yarn --production --prefer-offline --cwd "$(ARTIFACTS_DIR)/nodejs/"
```

### Observed result:

Written above.

### Expected result:

Not sure.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: ubuntu
2. `sam --version`:SAM CLI, version 1.21.1
3. AWS region: N/A

`Add --debug flag to command you are running`

**Comment by aprilmintacpineda** [comment]
Fixed it on the container.

**Comment by CITGuru** [comment]
@aprilmintacpineda Please how did you fixed this.

**Comment by RaymondCarlaw** [comment]
@aprilmintacpineda I would also like to know

**Comment by aprilmintacpineda** [comment]
I installed `make` on the container

**Comment by RaymondCarlaw** [comment]
Thank you, I'm on a windows machine and not using containers. Once I made make available in the path, everything worked fine, didn't realise it was referring to the make binary.

**Comment by ledangvu** [comment]
I run this on WSL2, ubuntu. When I got this error **sam build Error: CustomMakeBuilder:Resolver - Path resolution for runtime: provided of binary: make was not successful**, I installed **make** on ubuntu using the command
`sudo apt-get install -y make`

**Comment by LuizPelegrini** [comment]
I used the command in windows

```bash
sam build --use-container
```

and it worked, it took quite some time to build in my machine though
