### ISSUE TITLE
Layer is an Invalid Layer Arn, when passing it to a nested Serverless Application

### ISSUE THREAD

**Issue by JohanZackrisson** [aws/aws-sam-cli#2783]
### Description:

When passing a !Ref to a AWS::Serverless::LayerVersion to a nested AWS::Serverless::Application, sam build returns:
`Error: Layer is an Invalid Layer Arn.`
when using version 1.21.1

This does not happen in version 1.19.1.

I've minimized a test case, which can be found at:
https://github.com/JohanZackrisson/aws-sam-cli-bug

When passing in a arn string instead of a !Ref, it builds.

### Steps to reproduce:

In the main folder do:
**Non working test:**
`pip3 install aws-sam-cli -Iv aws-sam-cli==v1.21.1`
`sam build`

**Working test:**
`pip3 install aws-sam-cli -Iv aws-sam-cli==v1.19.1`
`sam build`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS 11.2.3
2. `sam --version`: 1.21.1
3. AWS region: eu-west-1

**Comment by aahung** [comment]
Thanks for reporting, it is fixed in #2760 and to be released.

BTW, since 1.20.0, `sam build` will start to build functions/layers in nested stacks as well, make sure your functions can be built (I see in your example, the lambda folder does not contain a `package.json`, `sam build` might fail building that function).

**Comment by JohanZackrisson** [comment]
Thanks for the feedback. Looking forward to the next release. :)

**Comment by aahung** [comment]
@JohanZackrisson you are welcome. You can try out our nightly build available at https://github.com/aws/aws-sam-cli/releases to see if it resolves your problem.

**Comment by aahung** [comment]
released in 1.22.0
