### ISSUE TITLE
python3.8 hello world image deployment fails with "Code signing is not supported for functions created with container images"

### ISSUE THREAD

**Issue by saschalippert** [aws/aws-sam-cli#2786]
### Description:
deployment of python 3.8 hello world image example fails due to signing issue, although no signing is configured

### Steps to reproduce:
SAM CLI, version 1.21.1

sam init with python3.8 hello world image example
sam build && sam deploy --guided

### Observed result:

`CREATE_FAILED            AWS::Lambda::Function    HelloWorldFunction       Resource handler       
                                                                           returned message:      
                                                                           "Code signing is not   
                                                                           supported for          
                                                                           functions created with 
                                                                           container images.      
                                                                           (Service: Lambda,      
                                                                           Status Code: 400,      
                                                                           Request ID: 33964ed6-6 
                                                                           59f-4990-a682-f06093b4 
                                                                           f9ab, Extended Request 
                                                                           ID: null)"             
                                                                           (RequestToken: 147693a 
                                                                           b-1226-f8f1-759e-6bb7a 
                                                                           85d95cc,               
                                                                           HandlerErrorCode:      
                                                                           InvalidRequest)  `

### Expected result:
deployment successful

**Comment by jfuss** [comment]
@saschalippert Can you share your template? If needed, please redact anything. What I am more interested in is:
1) What is the Global's section of your template?
2) What is the function definition for the failed resource?
3) What is the command you are running to deploy this application?

**Comment by saschalippert** [comment]
@jfuss 
I got the issue with the demo app as well - so it is nothing special:
https://gist.github.com/saschalippert/5f26a0391b893b2cdc333e3c0d7459ab

The issue occurs either using "sam deply" or "sam deploy --guided"

Full sam deploy log:
https://gist.github.com/saschalippert/6d416eccd873f8e72dbc0e66e629b159

samconfig:
https://gist.github.com/saschalippert/1289f18ab81fbaad74810ac208ba8553

Manual lambda deployment (via web interface) of the uploaded container image by sam still works still fine.

**Comment by saschalippert** [comment]
Btw sam worked fine for me since december 2020. The issue started to occur last weekish. I did not update the sam or aws client directly. But I cannot rule out that a dependency upgrade is causing it.

**Comment by jfuss** [comment]
@saschalippert Thank you for sending the above data. Nothing seems off in what you have. Looking at the error again, this error is coming from AWS Lambda's service. SAM shouldn't be adding any configuration to the template (enabling signing), so this should just work. 

My guess is that something might have happened on Lambda's server side. Are you still getting this error?

**Comment by saschalippert** [comment]
@jfuss i tested it again. looks like aws resolved the issue on their side.

ill close this issue for now
