### ISSUE TITLE
Be able to share sam build makefile targets and artifacts for multiple functions in one template

### ISSUE THREAD

**Issue by mikebroberts** [aws/aws-sam-cli#2790]
Typically when building an application I have several Lambda functions, and often times many if not all of them share a distribution artifact. If I'm making a regular Node app with no special build considerations then sam build will create one artifact for all the functions with the same code URI, and even better that artifact is cached and won't require a code-change-deployment if no actual code has changed. So far, so good.

The problem comes if I want to tweak the build process, which I often do. Makefile support exists now, which is fine, however as far as I can tell if you want to use a makefile for multiple functions in the same template then (a) you have to have a separate make target per function and (b) the artifact cannot be shared across those functions. Which means if you have 10 functions in a template then you can end up building the same artifact 10 times. Which is far from optimal for non-trivial build processes.

Have I missed something? If not, please can sam build's support in this regard be improved?

On almost any project of any significance I almost always end up writing a build.sh script to create a zip file myself. Would be great if sam build meant I didn't have to do that any more.

**Comment by CoshUS** [comment]
By using makefile, it introduces the flexibility to produce different artifacts for the same Code URI. SAM CLI cannot make the assumption like other languages and thus produces artifacts for each function.
Closing. Let me know if there are other issues.
