### ISSUE TITLE
Pythonpipbuilder: resolve dependencies - list index out of range

### ISSUE THREAD

**Issue by pabloiarriola** [aws/aws-sam-cli#2796]
**Description:**
I am trying to use sam build with the following requirements but its throwing the error: Pythonpipbuilder: resolve dependencies - list index out of range  

- pyotp
- ulid-py
- aws_encryption_sdk
- boto3
- requests
- attrs
- cryptography

**Steps to reproduce the issue:**
1. Create a virtual env.
1. Activate virtual env in a terminal
2. pip install -r requirements.txt
4. sam build 

**Observed result:**
Build Failed
Error: PythonPipBuilder:ResolveDependencies - list index out of range

**Expected result:**
Build Succeeded

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Amazon Linux 2 Workspace 
Python3.8

**Comment by sriram-mv** [comment]
Do you have latest version of pip? I was not able to reproduce this with the listed requirements, also you do not need to install requirements with pip before running sam build. sam build will take of pulling the dependencies as specified on the manifest which is requirements.txt
