### ISSUE TITLE
brew cleanup gives warning "Calling `cellar` in a bottle block is deprecated!"

### ISSUE THREAD

**Issue by mrichman** [aws/aws-sam-cli#2803]
Using homebrew 3.1.0 on macOS 10.15.7. Ran `brew cleanup` and got this message:

```bash
$ brew cleanup

Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli.rb:19

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli.rb:20

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli.rb:21

brew cleanup  29.96s user 8.42s system 98% cpu 38.833 total
```

Error seems to be here: https://github.com/aws/homebrew-tap/blob/master/Formula/aws-sam-cli.rb#L19

**Comment by davivcgarcia** [comment]
I'm seeing this behavior with `aws-sam-cli` installed on version `1.22.0`.

**Comment by michaelbrewer** [comment]
It is related to HomeBrew 3 deprecation.

**Comment by softprops** [comment]
seeing this as well

**Comment by yeukfei02** [comment]
#2809 same issue

**Comment by jfuss** [comment]
This is being tracked in the homebrew repo (where the formula is). There is a PR open for fixing it already: https://github.com/aws/homebrew-tap/pull/188 and links to an issue in that github reop. Cross posting here so we have a pointer but leaving this open until its fixed, so we have something tracking on the SAM CLI repo. 

Further updates will be in the homebrew repo.

**Comment by jfuss** [comment]
https://github.com/aws/homebrew-tap/pull/188 was merged that addresses this. Closing

**Comment by silfers** [comment]
Hello, I get this same message when trying to install a package. I have just installed homebrew. Any idea on how to fix it?

**Comment by AsadAli-BB** [comment]
Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead. 
i have not get right answer yet.
![Screenshot 2021-05-16 at 9 10 57 AM](https://user-images.githubusercontent.com/68729728/118385674-8b7c6880-b62a-11eb-9a0c-7297b975cc52.png)

**Comment by AlviseFeliu** [comment]
Hello good afternoon;

I have an error & i dont know how to solve it:

Error: shellcheck: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/shellcheck.rb:10

**Comment by jackystd** [comment]
> Hello good afternoon;
> 
> I have an error & i dont know how to solve it:
> 
> Error: shellcheck: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
> Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/shellcheck.rb:10

Same error whih me.

**Comment by adriangc24** [comment]
I have same error :(

**Comment by AsadAli-BB** [comment]
Ok Got it

**Comment by xwan-robinhood** [comment]
i have same error :(

**Comment by joex92** [comment]
now what? how is this solved? at least someone post how to solve it...

**Comment by Exantria** [comment]
now what?

`brew style --fix
Inspecting 1089 files
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

1089 files inspected, no offenses detected
Error: shellcheck: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/shellcheck.rb:10`

**Comment by jithrk1392** [comment]
> **SOLUTION**
> Reinstall [Homebrew](https://brew.sh/)
> just run the installation script, wait for it to finish and it's done...

this did not help.

**Comment by aktivia32** [comment]
it helps for me:

> brew update-reset
