### ISSUE TITLE
API Gateway headers being transformed

### ISSUE THREAD

**Issue by knuese** [aws/aws-sam-cli#2814]
When running `sam local start-api` and sending request via Postman, I noticed that the SAM version of the API is making changes to the headers that do not occur in API Gateway. For example, if I send a header like `x-abc-some_thing`, what I end up getting on the event is `X-Abc-Some-Thing`. This doesn't occur with an actual API Gateway deployed to AWS (I get `x-abc-some_thing` without changing any settings). The capitalization is not an issue because according to HTTP specs headers should be handled in a case-insensitive manner, however the change from the underscore to the hyphen makes fetching this header value difficult -- I essentially would need a workaround in the code for when the API is run via SAM CLI.

**Comment by jfuss** [comment]
Please see https://github.com/aws/aws-sam-cli/issues/621#issuecomment-418373900

This is happening from Flask and not something we can handle without re-writing the local servers locally. 

Closing as wontfix (same as other issue).
