### ISSUE TITLE
Make stack name default to `cwd` instead of `sam-app` when running `sam deploy --guided`

### ISSUE THREAD

**Issue by ljacobsson** [aws/aws-sam-cli#2817]
### Describe your idea/feature/enhancement
When running `sam deploy --guided` you are more likely to want to name your stack after the current working directory than `sam-app`

**Comment by jfuss** [comment]
@ljacobsson Thanks for the issue. I understand the default may not be ideal for you but you can override this value today by either providing `--stack-name` or giving a different stack name during the guided flow. `cwd` may not always be accurate, as you can run commands outside of the directory of your project.

Given that, I am going to close this as we will keep the default name and suggest to override it.
