### ISSUE TITLE
How to run multiple SAM versions in an environment.

### ISSUE THREAD

**Issue by oguzhanaygn** [aws/aws-sam-cli#2818]
Hi,
I'm trying to create base environment for lambda deployments. Some of lambda functions have very old runtimes, and some of them are very new. In my basic understanding of SAM CLI, I can't cover nodejs runtime (very old) and nodejs14.x runtime (new) at the same time for a single SAM CLI version. Basically, I'm trying to switch between SAM versions but I'm afraid there is no option like this. I think it would be cool to have a possibility like this.

Thanks a lot.

**Comment by jfuss** [comment]
SAM CLI will remove support following the runtime being depreciated. Older runtimes that are still supported in AWS Lambda are supported within SAM CLI. If you are referring to an older (no longer supported version), then you will have to use an older version of SAM CLI.
