### ISSUE TITLE
Process custom global transform macros

### ISSUE THREAD

**Issue by brandonryan** [aws/aws-sam-cli#2819]
### Describe your idea/feature/enhancement
As far as I can tell, `sam local start-api` ignores the `Transforms` section of the template. This is problematic for anybody trying to do template transforms before the serverless transform because sam wont understand custom resources or template syntax supported by the transform.  
In my example, I have a transform that replaces `:latest` in a layer arn with the latest version of that layer. Sam doesn't run the transform, so it gives me an invalid layer error.

### Proposal
I would like if sam local could run the transforms before trying to parse resources from the template. 

_This may be out of scope of sam-cli, but I couldn't find an issue for it, and wanted to at least have a discussion about it._

Things to consider:
1. Supporting transforms that happen after serverless transform seems impossible because as far as i can tell sam local doesnt actually run the serverless transform, it just picks up on the serverless resources.

**Comment by CoshUS** [comment]
SAM CLI only supports SAM transformation by translating the template with the SAM library.
Transforming with other custom transformations will require going through CFN and outside the scope of local and SAM CLI.
If you want full fidelity testing, I would recommend trying out the new `sam sync` beta feature. 
Let us know if there are other gaps in this RFC or a separate issue: https://github.com/aws/aws-sam-cli/issues/3264
`sam sync` documentation: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/accelerate-getting-started.html
