### ISSUE TITLE
npm install is very slow

### ISSUE THREAD

**Issue by kigawas** [aws/aws-sam-cli#2822]
Compared to Python, npm install via sam build --use-container is astonishingly slow.

It's even slower than npm install directly

**Comment by aahung** [comment]
How much slower and do you have many dependencies? `npm install` directly is faster than in docker container should be expected because `npm install` directly could benefit from npm cache

**Comment by kigawas** [comment]
> How much slower and do you have many dependencies? `npm install` directly is faster than in docker container should be expected because `npm install` directly could benefit from npm cache

Part of package.json
```json
  "dependencies": {
    "@openzeppelin/contract-loader": "^0.6.1",
    "@openzeppelin/upgrades": "^2.8.0",
    "aws-sdk": "^2.760.0",
    "bignumber.js": "^9.0.0",
    "ethereumjs-tx": "^2.1.2",
    "ethereumjs-util": "^7.0.10",
    "js-sha3": "^0.8.0",
    "pg": "^8.3.3",
    "proxy-agent": "^3.1.1",
    "quorum-js": "^0.3.6",
    "uuid": "^8.3.1",
    "web3": "^1.3.5",
    "web3-utils": "^1.3.5"
  },
  "devDependencies": {
    "@openzeppelin/cli": "^2.8.2",
    "eslint": "^7.24.0",
    "eslint-config-node": "^4.1.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-node": "^11.1.0",
    "ganache-cli": "^6.10.2",
    "truffle": "^5.3.2"
  }
```

It takes at least five minutes :(

**Comment by aahung** [comment]
These packages you posted are quite heavy. I tested it using docker and non-docker  (node 12) with your dependency list:

It took more than nearly 2 mins to finish in both cases and I did not spot a difference. The machine I tested is quite powerful, so if you have slower CPU, disk or network, it should take longer.

If you continue to spot huge difference between your non-docker and docker env (please make sure you clean your `node_modules` folder and run `npm cache clean --force` before doing test), please open a new issue with testing environment details and results
