### ISSUE TITLE
Unable to build example created by sam init | NPM Failed: npm ERR! code ENOLOCAL

### ISSUE THREAD

**Issue by Allirix** [aws/aws-sam-cli#2823]
I can't get the basic "sam init" function to run on my Windows Parallels machine on my Mac

I select these options: 

    -----------------------
    Generating application:
    -----------------------
    Name: node-test
    Runtime: nodejs14.x
    Dependency Manager: npm
    Application Template: hello-world
    Output Directory: .

I then cd into the application

    cd node-test

![image](https://user-images.githubusercontent.com/20376940/115665557-cd492480-a386-11eb-8572-60b0bf0cc1f1.png)

And try running the build command

    sam build

And I get this error:

    `Building codeuri: Z:\Documents\entrago_projects\AWS\Lambda\sam-app\hello-world runtime: nodejs10.x metadata: {} functions: ['HelloWorldFunction']
    Running NodejsNpmBuilder:NpmPack
    
    Build Failed
    Error: NodejsNpmBuilder:NpmPack - NPM Failed: npm ERR! code ENOLOCAL
    npm ERR! Could not install from "..\..\..\..\..\..\Mac\Home\Documents\entrago_projects\AWS\Lambda\sam-app\hello-world" as it does not contain a package.json file.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\davidhampton\AppData\Roaming\npm-cache\_logs\2021-04-22T06_12_24_725Z-debug.log `

### My versions

    Z:\>npm --v
    6.14.12
    
    Z:\>sam --version
    SAM CLI, version 1.22.0
    
    Z:\>aws --version
    aws-cli/2.1.39 Python/3.8.8 Windows/10 exe/AMD64 prompt/off
    
    Z:\>docker --version
    Docker version 20.10.5, build 55c4c88

**Comment by aahung** [comment]
The path "..\..\..\..\..\..\Mac\Home\Documents\entrago_projects\AWS\Lambda\sam-app\hello-world" in your log is strange, can you cd into this path using CLI and check what is in there?
