### ISSUE TITLE
sam local start-api gives wrong notion of memory usage

### ISSUE THREAD

**Issue by Girija-Shankar-Swain** [aws/aws-sam-cli#2828]
### Description:

`sam local start-api` gives wrong notion of memory usage. Let's say Docker desktop is allocated 2GB of memory and AWS Lambda is configured with a memory setting of 4096 MB. When you run the command to start the local api using `sam`, the api runs successfully. When you access the api, sam logs as if the lambda function consumed 4GB of RAM. This is not possible as the Docker desktop was only allocated 2GB of memory. `docker stats` also confirms that the container was allocated 2GB of memory.

### Steps to reproduce:

1. Create a new SAM project using the SAM CLI  with Nodejs 14.x runtime, packaging type Zip and the hello-world template
`sam init -r nodejs14.x -p Zip  --app-template hello-world -n sam-local-memory-issue`
2. Now add the `MemorySize: 4096` in the `HelloWorldFunction` properties in the `template.yaml` file
3. Ensure your Docker Desktop is allocated 2GB of memory (Docker Desktop -> Preferences.. -> Resources -> Memory. Set this to 2GB -> Apply and restart)
4. Start the local api with pre-warmed mode (The issue happens irrespective of the mode, but the Eager mode keeps the container running and allows to check the actual memory usage) `sam local start-api --warm-containers EAGER`
5. Run `docker stats` to see the memory allocated to the container (Should be close to 2GB)
6. Access the local api `curl http://localhost:3000/hello`
7. Observe the logs after the response has been sent which prints the function consumed the allocated 4096 MB.

### Observed result:

Init Duration: 1.03 ms  Duration: 8038.39 ms    Billed Duration: 8100 ms        Memory Size: 4096 MB    Max Memory Used: 4096 MB

How does the lambda function get 4GB while docker was allocated only 2GB.

### Expected result:

The logs should specify the actual memory that was allocated to the Lambda function or `sam local start-api` should complain about the memory allocated to Docker Desktop is not sufficient for the Lambda to run.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS 11.2.3
2. `sam --version`: SAM CLI, version 1.21.1
3. Docker desktop version: 3.3.1
4. `docker version` 
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true
Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by awood45** [comment]
The short answer is that the memory value there isn't actual memory consumed, it's a stub value that is provided by the Lambda emulation code. See this line: https://github.com/aws/aws-lambda-runtime-interface-emulator/blob/00d793b74124ebabf38da49fe3a34645e6168b5f/cmd/aws-lambda-rie/handlers.go#L48

We rely on the Lambda emulator for that output value, though I can imagine that local testing may not always match the values you would get running on Lambda itself. I would generally recommend running memory usage tests on AWS infrastructure rather than locally.

Going to close this here, if you want to open this as a feature request in the https://github.com/aws/aws-lambda-runtime-interface-emulator repo you should absolutely feel free to do so.
