### ISSUE TITLE
Please support passing --parameter-override to sam package

### ISSUE THREAD

**Issue by FieryCod** [aws/aws-sam-cli#2835]
### Describe your idea/feature/enhancement

I'm making a framework which utilizes AWS SAM. One of it's features is that user can change runtime at any point, therefore I would like to send override parameters to `sam package` command.

### Proposal
Support passing `--parameter-overrides` to `sam package`. It should not be troublesome since it's working the same way with `sam invoke` and `sam local start-api`.

**Comment by aahung** [comment]
The "packaged template" is generic. It means the packaged template can be used with any parameter values and parameters are only set when a template is deploy on CloudFormation.

This is different from `sam invoke` and `sam local` where we try to "mimic" a situation these functions/api-gateway are already deployed.

**Comment by FieryCod** [comment]
@aahung `sam package` sends the code to s3 and rewrites template.yml, so that s3 uri is included. Seems to me that "packaged template" is not generic, since it has strict coordinates to applications sources. 

When using reference to CodeUri parameter code cannot be packed and send to s3, therefore what are the alternatives?

**Comment by aahung** [comment]
Yeah, "packaged template" is generic in terms of the template parameters which can be assigned any values, not in terms of application source code. 

I am gonna close this issue and continue the discussion on your specific use case in #2836.
