### ISSUE TITLE
Allow users to use a path in 'Handler' for Go lambdas

### ISSUE THREAD

**Issue by JadenSimon** [aws/aws-sam-cli#2844]
### Describe your idea/feature/enhancement

SAM CLI should extract a path from the `Handler` property in SAM templates and use that as the `CodeUri`. 
Other languages support this, so you could write:

>Handler: "my/path/to/handler/app.handler"

Without a `CodeUri` and it will run fine.

While for Go you must always put the path to your source code in `CodeUri`:

>CodeUri: "my/path/to/handler" 
>Handler: "mybinary" # this just refers to the compiled binary name, so it can be anything

Otherwise SAM CLI will fail to build.

### Proposal

Add a special case for Go (or any other compiled language) to get the working directory from the Handler property before building. This gives flexibility in what both fields may refer to, i.e. `CodeUri` might refer to the location of the manifest file and `Handler` is the relative path to the lambda function.

**Comment by ssenchenko** [comment]
Thanks for the feature request! We have a [roadmap](https://github.com/aws/aws-sam-cli/wiki/SAM-CLI-Roadmap) here, but we also try to take in popular feature requests based on 👍🏽 from the community. We will be adding this to our intake for prioritization.

**Comment by sriram-mv** [comment]
Closing issue as the PR has been released.
