### ISSUE TITLE
OPTIONS should automatically be responded to when using `start-lambda`

### ISSUE THREAD

**Issue by shadow-light** [aws/aws-sam-cli#2851]
**NOTE This is about executing lambda directly WITHOUT using API Gateway**

### Description:

The lambda service normally automatically handles OPTIONS requests without any user configuration, such as with the example below.

However `start-lambda` rejects OPTIONS requests with a 405.

### Steps to reproduce:

Run `sam local start-lambda` with any function and do a POST request to it.

### Observed result:

![image](https://user-images.githubusercontent.com/42055707/116964736-901e5400-acef-11eb-91b2-a2de9116640e.png)

### Expected result:

See example from actual lambda endpoint

![image](https://user-images.githubusercontent.com/42055707/116964488-0078a580-acef-11eb-8727-ccf79fe2353b.png)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Debian
2. `sam --version`: 1.23.0
3. AWS region: any

**Comment by c2tarun** [comment]
Hi @shadow-light,

Thanks for reporting this issue. However, I am not sure that I understand the issue correctly. The `OPTIONS` response which you get is returned by the Lambda Service and not the Lambda function. SAM CLI is trying to mimic Lambda Function Invocation by the service and not the Lambda Service itself. As far as I understand Lambda Function only understands event and not the request method.

May be if you explain your use-case a bit around why you want to make an OPTION request to `local start-lambda` I can understand the problem better.

Thanks
Tarun

**Comment by jfuss** [comment]
Closing due to no response. If this is still needed/wanted, please update SAM CLI first to verify it has not already been fixed. If that doesn't resolve the issue, please create a new issue.
