### ISSUE TITLE
Add --hide-parameters flag on CLI deploy command

### ISSUE THREAD

**Issue by allanchua101** [aws/aws-sam-cli#2866]
At the time of this request writing, SAM `deploy` command is logging parameters provided to it prior to execution. This is good when a developer is diagnosing issues or testing values passed to the CLI. However, it is counter intuitive from a security point of view for large enterprises because the logged parameters could contain sensitive information. (E.G API keys fetched from secrets manager or parameter store)

### Proposal

I propose that we either:

- Add a `--hide-parameters` flag to skip logging logic of parameters
- Add a `--silent` flag to optionally stop generation of logs during deployment process

### Benefits of change

- Sensitive values are not exposed from CI/CD logs
- Developers can hide parameters they pass during demo sessions

**Comment by jfuss** [comment]
Looking at the code, we respect the `NoEcho` Property on Parameters: https://github.com/aws/aws-sam-cli/blob/6dc1a5666b8662734cb2aca8581ed11444d724cf/samcli/commands/deploy/deploy_context.py#L153-L165 for the table called out in this issue. 

The recommendation is to follow how CloudFormation handles these so your keys or sensitive info is not displayed with SAM CLI but also with CloudFormation. 

Action here is to define you Parameters with `NoEcho: true`.
