### ISSUE TITLE
Can anyone please suggest how to include new environment parameters in template for dev

### ISSUE THREAD

**Issue by vithyavani-bit** [aws/aws-sam-cli#2870]
### Describe your idea/feature/enhancement

Can anyone please suggest how to include new environment parameters in template for dev(backend domain) I followed the following steps 1.Created backend Domain name request for dev 2.Created and uploaded SSL certificates into ACM 3.Now need to add those new environment parameters in template(yaml) Azure devops   

### Proposal

Add details of how to add this to the product.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

**Comment by aahung** [comment]
Hi @vithyavani-bit Can you describe what your question is? "how to include new environment parameters in template for dev" is quite vague. What you are trying to do?

**Comment by vithyavani-bit** [comment]
Created new domain name request for backend domain in dev environment
So I need to add these new environment parameters to master template how to add it

**Comment by aahung** [comment]
> Created new domain name request for backend domain in dev environment
> So I need to add these new environment parameters to master template how to add it in Azure devops portal(yaml)

Seems you are asking about a specific use case (domain name or Azure devops portal), which is not relevant to AWS SAM CLI. I am closing this issue. A better place to ask might be [AWS developer forum](https://forums.aws.amazon.com/index.jspa), StackOverflow or contact AWS support.
