### ISSUE TITLE
ResolveDependencies Error: greenlet (1.1.0), numpy (1.20.3), sqlalchemy (1.4), protobuf (3.17.1)...

### ISSUE THREAD

**Issue by palashjain21** [aws/aws-sam-cli#2888]
### Description:

We are trying to deploy our project using aws-sam which includes "greenlet" library. Previously, we configured it to greenlet version 1.0.0 and it was working. But after 6th May whengreenlet developers released a new patch to 1.1.0, we are not able to deploy due to PythonPip Dependencies error:
Running PythonPipBuilder:ResolveDependencies
Error: PythonPipBuilder:ResolveDependencies - {greenlet==1.1.0(wheel)}

### Expected result:

Build Successful
Please fix this issue or let us know if there is no change

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS or Linux
2. If using SAM CLI, `sam --version`: 1.23.0
3. AWS region: eu-west-2

`Add --debug flag to any SAM CLI commands you are running`

**Comment by jfuss** [comment]
Looking at PyPI, this seems to be related to https://github.com/aws/aws-lambda-builders/issues/233. More specifically, `sam build` support to download the new `.whl` formats from PEP 600.

**Comment by aahung** [comment]
Tested the following with update-lambda-builder-1.4.0 (next version of SAM CLI will use this version)
```
numpy==1.20.3
greenlet==1.1.0
sqlalchemy==1.4.15
protobuf==3.17.1
```

**Comment by aahung** [comment]
# Current workaround

Use these in your requirements.txt:

```
numpy<1.20.3
sqlalchemy<1.4
greenlet<1.1.0
protobuf<3.16.0
```

**Comment by aahung** [comment]
[AWS SAM CLI v1.24.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.24.0) has been released
