### ISSUE TITLE
sam should only deploy a new version if code or relevant config has changed

### ISSUE THREAD

**Issue by dfuentes77** [aws/aws-sam-cli#2890]
### Description:
I have a function described in template.yaml.  I have AutoPublishAlias w/ Provisioned Concurrency enabled.  I deploy and stack and it creates and completes.  I add a cloudwatch alarm to template.yaml.  I deploy and the changeset says it's going to deploy a version of the lambda, even though nothing changed for the code or config.  I deploy and it creates the new version of the lambda and adds the alarm.  I remove the alarm from template.yaml, and deploy and it yet again wants to deploy a new version of the lambda, while also removing the alarm.

### Expected result:
If the code or config for the lambda doesn't change, no new version should be deployed.  Just make changes to the other resources in template.yaml as needed.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:  macOS Big Sur 11.3.1
2. `sam --version`:S AM CLI, version 1.23
3. AWS region: us-west-2

**Comment by aahung** [comment]
Does your function's `CodeUri` contain files other than code?

**Comment by dfuentes77** [comment]
It’s set to `.` and includes all py files, requirements.txt, Pipfile*, template.yaml, samconfig.toml and the gitignored build directory that SAM creates

**Comment by aahung** [comment]
That's why, `sam deploy` will package all these files and upload to lambda, causing redeployment every time you change the template file. You can create a folder and put your "all py files, requirements.txt, Pipfile*" in it to avoid this

**Comment by dfuentes77** [comment]
Thanks!  That fixed it.  I might have missed it but is there any documentation that points that out.  I just noticed that when you do a `sam init` it does create the separate`src` directory.   But since this was an existing single lambda, we just thought to add the template.yaml and samconfig.toml in the same directory.  Maybe sam could prompt the user to move source code to a separate directory, as a best practice.

**Comment by aahung** [comment]
> Maybe sam could prompt the user to move source code to a separate directory, as a best practice.

Thanks for the suggestion. We are also exploring other options like excluding certain directories and files in `CodeUri`, like `template.yaml` in your case. 

I am closing this for now. Please let us know if you experience further issues.
