### ISSUE TITLE
hybrid-local mode for functions that depend on templated resources

### ISSUE THREAD

**Issue by JordonPhillips** [aws/aws-sam-cli#2922]
(I looked for a similar feature request, but didn't see one)

### Describe your idea/feature/enhancement

I have an issue similar to #2896 where I have a lambda function that depends on external resource whose name is passed in as an environment variable. Having to separately deploy and then figure out what all the resolved environment variables map to is a real pain, so I would like a hybrid mode that handles this for me.

### Proposal

Introduce `sam hybrid-local` (or `--hybrid` to `sam local`). When used, this will first deploy the stack. It will then run local operations as normal, with any dynamic parameters - particularly environment variables - resolved locally.

#### Alternative

Introduce a `--deployed-resources` parameter to `sam local` which takes a deployed stack name to pull dynamic parameters from. This has the downside of introducing a risk of drift between the deployed stack and the local stack under test.

**Comment by hawflau** [comment]
Hey @JordonPhillips sorry for delayed response, and thanks for the proposal. 

We are working on adding a new set of features of the SAM CLI that might address your use case. You can read this [RFC](https://github.com/aws/aws-sam-cli/issues/3264) for details. 

If you would like to try these features out in Beta, here are the [instructions](https://github.com/aws/aws-sam-cli/wiki/How-to-Start-Using-sam-sync) to get it running! Please give it a spin and give us feedback on how we can improve this feature.

**Comment by jfuss** [comment]
Our solution for things like this is to use SAM Accelerate (`sam sync`) command to test your functions on the cloud. 

Closing as `sam sync` would be our solution to testing when you need other cloud resources.
