### ISSUE TITLE
sam local invoke executes with AWS CLI profile instead of provided IAM role

### ISSUE THREAD

**Issue by AbeGellis** [aws/aws-sam-cli#2930]
### Description:
A developer on our sam project attempted to build and locally invoke a Function resource. The (Python 3.8) function in question calls [list_users](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp.html#CognitoIdentityProvider.Client.list_users). Her IAM user role does not have the appropriate permissions; however, the ARN of a role that _does_ was provided in the function's Role in the project's template.yaml. This role has been used in other functions and seems to be correctly associated with them on deployment.

Her local invocation failed, however, with the following error:
`An error occurred (AccessDeniedException) when calling the ListUsers operation: User: [her IAM user ARN] is not authorized to perform: cognito-idp:ListUsers on resource: [the user pool ARN]`

### Steps to reproduce:
Using the IAM console, create an IAM role with the appropriate permissions for a Lambda function to assume it and to call list_users on a user pool. Create an IAM user without those permissions.
Sign into the AWS CLI as the IAM user without list_users.
Add a function to a sam project and pass the ARN of the list_users role as its Role parameter.
`sam build` and `sam local invoke` that function.

### Observed result:
AccessDeniedException

### Expected result:
The function should execute with the provided role

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: OS X Big Sur version 11.1
2. `sam --version`: 1.23.0
3. AWS region: us-east-1

I am aware that it's not the _best_ practice to grant developers the ability to assume permissions through Lambda functions that they wouldn't be granted normally. In this case, I am not concerned with the scope of access but concerned that a more-permissive IAM user role might let a function with a restrictive IAM role work locally but hit AccessDeniedException on deployment.

**Comment by zhan9san** [comment]
@AbeGellis 

Could you please try the following solution?
It seems there is no need to introduce any change in `sam` but `aws config`

1. Please ensure the aws config is in the following format.
  
  ```bash
  $ cat ~/.aws/config
  
  [profile user-without-list-users-permission]
  region=us-west-2
  
  [profile lambda]
  role_arn = role_arn = arn:aws:iam::123456789012:role/lambda-execution-role-with-list-users-permission
  source_profile = user-without-list-users-permission
  region=us-west-2
  ```
2. Test

  ```bash
  sam local invoke --profile user-without-list-users-permission
  ```

Reference:
[Specifies the Amazon Resource Name (ARN) of an IAM role that you want to use to perform operations requested using this profile.](https://docs.aws.amazon.com/sdkref/latest/guide/setting-global-role_arn.html)

**Comment by AbeGellis** [comment]
Apologies for the delay.

I reproduced the config and credentials files as described. Previously, the profile for `user-without-permissions` had no IAM definition; I created one with no role and no added permissions except for the necessary STS:AssumeRole and added its access key id and secret key to `credentials`. I also updated the role my function resource is using to add my organization's AWS account to its Trusted Entities so that the `lambda` profile in config would be able to assume it.

Now, when I call `sam local invoke [FUNCTION_THAT_DEFINITELY_REQUIRES_PERMISSIONS] --profile user-without-permissions` I get an appropriate error:
```An error occurred (AccessDeniedException) when calling the ListUsers operation: User: arn:aws:iam::[ACCOUNT ID]:user/dummy-nopermissions is not authorized to perform: cognito-idp:ListUsers on resource: arn:aws:cognito-idp:us-east-1:[ACCOUNT ID]:userpool/[USER POOL ID] because no identity-based policy allows the cognito-idp:ListUsers action```

The `lambda` profile now seems to function correctly / identically to my default profile.

This seems like a useful setup to test the permissions boundaries of various Lambda-assumable roles but requires that they also be made assumable by IAM users. Additionally, I would need to deliberately set up a profile for every distinct role used by my function resources and specify the matching profile when locally invoking them. Is there a way for local invocation to bypass this and simply assume the roles specified for each function?

**Comment by zhan9san** [comment]
> Is there a way for local invocation to bypass this and simply assume the roles specified for each function?

If I understood correctly, you are saying making users assume '[FUNCTION_THAT_DEFINITELY_REQUIRES_PERMISSIONS]' directly without setting up 'Trusted Entities'.

This is against the principle of AWS IAM.

Correct me if I say anything wrong

**Comment by AbeGellis** [comment]
Not assume the role of the function, but assume the IAM role assigned to that function. I wouldn't say that Trusted Entities should be ignored or flaunted, although I'm not sure what the alternative is, short of prompting the user to add their IAM user to the Trusted Entities of the given role.

My concern is that the discrepancies between developer profile permissions and execution role permissions can lead to incorrect role permissions on deployed resources. In my original example, the developer in question was able to execute those functions in the Lambda console, but not locally invoke them. This enabled her to access permissions that her IAM user had not granted, but also restricted her from accessing permissions granted to her IAM role but not the function. Ideally, this behavior would be something that `sam local` could replicate in some way.

I understand if this is not doable because it compromises the principles of AWS IAM security, or because it would be more of a feature add than a fix. I opened this ticket because the current disregard for the execution role in testing worked against my expectations, having migrated a project to SAM from ad-hoc Lambda scripts edited directly in the console.

**Comment by ssenchenko** [comment]
Closing it as the solution cannot be provided now in a form of fix.
