### ISSUE TITLE
Can not install on MACOS with Homebrew

### ISSUE THREAD

**Issue by xpdable** [aws/aws-sam-cli#2936]
### Description:

Cannot install on macos with homebrew

### Steps to reproduce:

```brew install aws-sam-cli```

### Observed result:

```
Already downloaded: /Users/xiaopeng/Library/Caches/Homebrew/downloads/57e1dc36a7f872c6ce017b6217d933fa0549ceff3fec4d4cf2c7c9fd3ec8e711--aws-aws-sam-cli-v1.23.0-0-g2ce6ee0.tar.gz
==> Installing dependencies for aws/tap/aws-sam-cli: python@3.8
==> Installing aws/tap/aws-sam-cli dependency: python@3.8
==> ./configure --prefix=/usr/local/Cellar/python@3.8/3.8.6_2 --enable-ipv6 --datarootdir=/usr/local/Cellar/python@3.8/3.8.6_2/share --datadir=/usr/local/Cellar/python@3.8/3.8.6_2/share --enable-framework=/
==> make
Last 15 lines from /Users/xiaopeng/Library/Logs/Homebrew/python@3.8/02.make:
    self.run_command(cmd_name)
  File "/private/tmp/python@3.8-20210607-36941-1jycbwh/Python-3.8.6/Lib/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/private/tmp/python@3.8-20210607-36941-1jycbwh/Python-3.8.6/Lib/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/private/tmp/python@3.8-20210607-36941-1jycbwh/Python-3.8.6/Lib/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "./setup.py", line 320, in build_extensions
    self.detect_modules()
  File "./setup.py", line 1695, in detect_modules
    self.detect_readline_curses()
  File "./setup.py", line 930, in detect_readline_curses
    (tuple(int(n) for n in dep_target.split('.')[0:2])
AttributeError: 'int' object has no attribute 'split'
make: *** [sharedmods] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

Traceback (most recent call last):
	22: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/build.rb:223:in `<main>'
	21: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/build.rb:134:in `install'
	20: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/utils.rb:530:in `with_env'
	19: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/build.rb:139:in `block in install'
	18: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/formula.rb:1210:in `brew'
	17: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/formula.rb:2201:in `stage'
	16: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	15: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/resource.rb:91:in `stage'
	14: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/resource.rb:116:in `unpack'
	13: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/resource.rb:197:in `mktemp'
	12: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	11: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	10: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	 9: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/resource.rb:121:in `block in unpack'
	 8: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/formula.rb:2221:in `block in stage'
	 7: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/utils.rb:530:in `with_env'
	 6: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/formula.rb:2222:in `block (2 levels) in stage'
	 5: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/formula.rb:1217:in `block in brew'
	 4: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/build.rb:171:in `block (2 levels) in install'
	 3: from /Users/xiaopeng/workspace/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@3.8.rb:137:in `install'
	 2: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/formula.rb:2008:in `system'
	 1: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/formula.rb:2008:in `open'
/Users/xiaopeng/workspace/homebrew/Library/Homebrew/formula.rb:2072:in `block in system': Failed executing: make (BuildError)
	9: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/brew.rb:155:in `<main>'
	8: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/brew.rb:167:in `rescue in <main>'
	7: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/exceptions.rb:474:in `dump'
	6: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/exceptions.rb:420:in `issues'
	5: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/exceptions.rb:424:in `fetch_issues'
	4: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/utils/github.rb:317:in `issues_for_formula'
	3: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/utils/github.rb:298:in `search_issues'
	2: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/utils/github.rb:415:in `search'
	1: from /Users/xiaopeng/workspace/homebrew/Library/Homebrew/utils/github.rb:223:in `open_api'
/Users/xiaopeng/workspace/homebrew/Library/Homebrew/utils/github.rb:280:in `raise_api_error': curl failed!   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current (GitHub::Error)
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.github.com:443
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS Big Sur 11.4
2. `sam --version`: n/a
3. AWS region: cn-north-1

`Add --debug flag to command you are running`

Tried with python3.7/3.8/3.9 same error

**Comment by c2tarun** [comment]
Hi @xpdable ,

Can you please also share the version of homebrew you are using? Also if you are not using later version can you please ensure that you are getting same error with latest version as well.

Thanks

**Comment by josephShield** [comment]
I am having this issue as well, I am running the latest version of homebrew.
$ brew --version
Homebrew 3.1.10
Homebrew/homebrew-core (git revision f81ea3789e; last commit 2021-06-07)
Homebrew/homebrew-cask (git revision 77919f664f; last commit 2021-06-07)

When I try to install:
`$ brew install aws-sam-cli
==> Installing aws-sam-cli from aws/tap
==> Downloading https://github.com/aws/aws-sam-cli/releases/download/v1.24.0//aws-sam-cli-1.24.1.sierra.bottle.tar.gz
##O#- #
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "aws-sam-cli"
Download failed: https://github.com/aws/aws-sam-cli/releases/download/v1.24.0//aws-sam-cli-1.24.1.sierra.bottle.tar.gz`

I assume the path is wrong `.../v11.24.0//...` with the double slash

**Comment by c2tarun** [comment]
> I am having this issue as well, I am running the latest version of homebrew.
> $ brew --version
> Homebrew 3.1.10
> Homebrew/homebrew-core (git revision f81ea3789e; last commit 2021-06-07)
> Homebrew/homebrew-cask (git revision 77919f664f; last commit 2021-06-07)
> 
> When I try to install:
> `$ brew install aws-sam-cli ==> Installing aws-sam-cli from aws/tap ==> Downloading https://github.com/aws/aws-sam-cli/releases/download/v1.24.0//aws-sam-cli-1.24.1.sierra.bottle.tar.gz ##O#- # curl: (22) The requested URL returned error: 404 Error: Failed to download resource "aws-sam-cli" Download failed: https://github.com/aws/aws-sam-cli/releases/download/v1.24.0//aws-sam-cli-1.24.1.sierra.bottle.tar.gz`
> 
> I assume the path is wrong `.../v11.24.0//...` with the double slash

Hey @josephShield, we were going release when you got the error. Can you please retry? If you still get the same error please follow following steps:

```
brew uninstall aws-sam-cli
brew untap aws/tap
brew tap aws/tap
brew install aws-sam-cli
```

Brew sometimes caches the bad version of the formula and only way I could find to clean it up is by uninstalling and clearing the tap.

**Comment by josephShield** [comment]
Those steps worked and resolved my issues, many thanks @c2tarun !

**Comment by xpdable** [comment]
Ok thanks guys. My brew version:
```
brew --version
Homebrew 2.7.0
Homebrew/homebrew-core (git revision 3b76b9; last commit 2021-06-07)
Homebrew/homebrew-cask (git revision 07903a; last commit 2020-12-22)
```

**Comment by xpdable** [comment]
now I work around with `pip install aws-sam-cli`

**Comment by etishka** [comment]
I got the following error message:
```
curl: (22) The requested URL returned error: 503 
Error: Failed to download resource "aws-sam-cli"
Download failed: https://github.com/aws/aws-sam-cli/releases/download/v1.24.1//aws-sam-cli-1.24.1.sierra.bottle.tar.gz
```
notice double slash in the URL

**Comment by mndeveci** [comment]
This issue happens during our releases, we were updating version of the SAM CLI without actually putting the file in place, which was causing couple of minutes outage in terms of installing it through brew. If you look at the errors the location is `1.24.0` but the version at the filename is `1.24.1`. This was causing the failures for a limited time.
`https://github.com/aws/aws-sam-cli/releases/download/v1.24.0//aws-sam-cli-1.24.1.sierra.bottle.tar.gz`

I tried to install and upgrade SAM CLI through brew, and it was succeeded. @etishka  can you confirm that you can install or upgrade SAM CLI now?

Btw; we will be addressing this issue with the upcoming releases.

Thanks!

**Comment by sidharthvijayakumar** [comment]
> > I am having this issue as well, I am running the latest version of homebrew.
> > $ brew --version
> > Homebrew 3.1.10
> > Homebrew/homebrew-core (git revision f81ea3789e; last commit 2021-06-07)
> > Homebrew/homebrew-cask (git revision 77919f664f; last commit 2021-06-07)
> > When I try to install:
> > `$ brew install aws-sam-cli ==> Installing aws-sam-cli from aws/tap ==> Downloading https://github.com/aws/aws-sam-cli/releases/download/v1.24.0//aws-sam-cli-1.24.1.sierra.bottle.tar.gz ##O#- # curl: (22) The requested URL returned error: 404 Error: Failed to download resource "aws-sam-cli" Download failed: https://github.com/aws/aws-sam-cli/releases/download/v1.24.0//aws-sam-cli-1.24.1.sierra.bottle.tar.gz`
> > I assume the path is wrong `.../v11.24.0//...` with the double slash
> 
> Hey @josephShield, we were going release when you got the error. Can you please retry? If you still get the same error please follow following steps:
> 
> ```
> brew uninstall aws-sam-cli
> brew untap aws/tap
> brew tap aws/tap
> brew install aws-sam-cli
> ```
> 
> Brew sometimes caches the bad version of the formula and only way I could find to clean it up is by uninstalling and clearing the tap.

thanks this worked
