### ISSUE TITLE
Virustotal.com flags malware "Trojan/Generic.ASELF.3D543" in aws-sam-cli-linux-x86_64.zip

### ISSUE THREAD

**Issue by volkert-fastned** [aws/aws-sam-cli#2937]
### Description:
Versions `v1.24.0` and `v1.23.0` of `aws-sam-cli-linux-x86_64.zip` are flagged with malware `Trojan/Generic.ASELF.3D543` when scanned on Virustotal.com. Granted, it's flagged by only one of the many engines that are used to scan the files, so it's probably a false positive. but it might be a good idea to look into it anyway. Maybe this can be sorted out with them somehow?

### Steps to reproduce:
* Download `aws-sam-cli-linux-x86_64.zip` from https://github.com/aws/aws-sam-cli/releases (either version `v1.24.0` or `v1.23.0`, I haven't tested any other versions)
* Browse to https://www.virustotal.com
* Upload the ZIP file

### Observed result:

![Screenshot 2021-06-07 at 14-17-07 VirusTotal](https://user-images.githubusercontent.com/47151527/121015390-3d770280-c79b-11eb-989c-85223c4dcbb8.png)

### Expected result:
No malware should have been detected.

**Comment by mndeveci** [comment]
Thank you for raising this issue, team are investigating and treating this with high priority.

**Comment by jfuss** [comment]
Closing as latest versions are no longer being flagged.
