### ISSUE TITLE
arm64 build missing

### ISSUE THREAD

**Issue by seemantk-schweitzer** [aws/aws-sam-cli#2944]
Hello,

in trying to use the t4g.large instance type on AWS, one sees that that is an arm64 cpu, and is supported by Amazon Linux 2.  the downloads section of this repository, however, contains no builds for that cpu architecture.  Is this something planned or a no-go/

**Comment by mndeveci** [comment]
Hi @seemantk-schweitzer ,

We are not actively working on this right now, but did you try to install with `pip` and see if that works as a workaround for now?

Thanks

**Comment by seemantk-schweitzer** [comment]
hi @mndeveci! thank you for your patience with my latency in responding here.  I just now finally had a chance to try it via pip install and it worked like a charm. Thank you.
