### ISSUE TITLE
sam deploy --guided / "bootstrap" - S3 bucket not compliant with AWS Foundational Security Best Practices standard.

### ISSUE THREAD

**Issue by ackjewtn** [aws/aws-sam-cli#2948]
### Describe your idea/feature/enhancement

When bootstrapping an account for the first time, e.g running `sam deploy --guided` for the first time, the S3 bucket created is not set up according to the best practices defined https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html. Causing Security Hub to complain about S3.4 and S3.5.

### Proposal

Modify the CloudFormation stack defined in `samcli/lib/bootstrap.py` to create the S3 bucket with all the necessary properties. 

I've already forked and fixed this and can create a PR if this solution is acceptable. Link to commit: https://github.com/ackjewtn/aws-sam-cli/commit/d0940fe7bdf2dd475b4fece991feb8ae8953c0b6

### Additional Details
S3 bucket created with SAM CLI 1.24.1
<img width="1588" alt="current" src="https://user-images.githubusercontent.com/12695823/121690053-a75a1980-cac5-11eb-8807-4d6dd3099b41.png">

S3 bucket created with my change:
<img width="1581" alt="forked" src="https://user-images.githubusercontent.com/12695823/121689896-7bd72f00-cac5-11eb-874a-c83102a5c999.png">

**Comment by mndeveci** [comment]
Hi @ackjewtn ,

Thanks for informing this issue and working on the fix. I think the fix looks OK, can you raise a PR so that we can review it?

Thanks!

**Comment by ackjewtn** [comment]
Hello @mndeveci 

PR raised :)

**Comment by jfuss** [comment]
Responding to clear our 'maintainer/need-followup` label. Issues will be flagged (label added) if the last comment is not from a maintainer. Please follow the PR linked #2953 for updates. 

At the moment, just waiting to speak with the team tomorrow to make sure there was nothing previously blocking the PR (seems like just missing a second review).

**Comment by moelasmar** [comment]
The PR is released in SAM CLI V 1.37.0
