### ISSUE TITLE
sam deploy: support OnFailure

### ISSUE THREAD

**Issue by pjungermann** [aws/aws-sam-cli#2971]
### Describe your idea/feature/enhancement

At aws-cli, you can use the optional `--on-failure` argument at e.g., the `aws cloudformation create-stack` command. The default behavior (when not set/`None`) is `ROLLBACK`.

In the case of a rollback, stack will end up in state ROLLBACK_COMPLETE which requires to delete the stack first in order to attempt another deployment.

Adding the option, will allow users to customize the behavior and e.g., choose `DELETE` to directly delete the stack to not require a (manual) delete.

Additionally, aws-cli supports `[--disable-rollback | --no-disable-rollback]. 
You can specify either `OnFailure` or `DisableRollback`, but not both. 

### Proposal

Add the optional argument `--on-failure DO_NOTHING|ROLLBACK|DELETE` to the `sam deploy` command which then results in adding this config at `Deployer.create_changeset` (`kwargs`).

**Comment by jfuss** [comment]
@pjungermann Thanks for the feature request. Seems like a good addition to `sam deploy` command. 

Updating labels.

**Comment by mildaniel** [comment]
Support for this has been released in 1.54.0! Resolving.
