### ISSUE TITLE
OSX brew install specific version

### ISSUE THREAD

**Issue by GregTurner** [aws/aws-sam-cli#2986]
### Describe your idea/feature/enhancement

I wish I could specify a specific version of SAM CLI so that I don't have to worry about breaking changes.

### Proposal

brew install aws-sam-cli@1.24.1

**Comment by qingchm** [comment]
Hey there you can install previous versions with pip using commands like: pip3 install aws-sam-cli==1.24.0, currently we don't support installing previous versions using brew, if that's a strong preference we can view this as a feature request!

**Comment by GregTurner** [comment]
Thanks, I didn't even see the pip3 way!  All our engineers use OSX Big Sur and pip3 ships with by default.  In other words, we'll switch to the pip3 way and you can forgot about a pinned brew version.

**Comment by GregTurner** [comment]
(feel free to close)

**Comment by qingchm** [comment]
@GregTurner Actually we do not recommend specifically using pip as the default installation tool as it can lead to messy installations, maybe look at pipx as your solution here ;) we are currently working on pyinstaller for Mac which will hopefully be the ideal solution for your problem here!
