### ISSUE TITLE
Unable to resolve secrets when running sam local invoke.

### ISSUE THREAD

**Issue by devpresleycobb** [aws/aws-sam-cli#2987]
### Description:
When running sam local invoke if you are resolving secrets from secrets manager you do not get the secret you get the string placed in the template.yaml. When the function is deployed the string is resolved to it's actual secret value. Preferably invoking locally would give me the secret value im looking for.

### Steps to reproduce:
1. Create a secret in secrets manager
2. Add said secret to your template.yaml like this for example: WSS_ENDPOINT: '{{resolve:secretsmanager:prod/wss/api:SecretString:endpoint}}'
3. Make sure to attempt to print out the environment variable.
4. run sam local invoke.

### Observed result:
The print statement shows '{{resolve:secretsmanager:prod/wss/api:SecretString:endpoint}}'

### Expected result:
The print statement should show wss://ldjslf382.execute-api.us-west-2.amazonaws.com/production

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. Windows:
2. `SAM CLI, version 1.24.0`:
3. AWS region: us-east-1

`Add --debug flag to command you are running`

**Comment by CoshUS** [comment]
Hey @devpresleycobb,
Thanks for the feedback. SAM CLI does not resolve remote resources for local invoke and adding support for each individual use case would be unmanageable. However, we are working on facilitating testing your project directly in the cloud with extremely fast local to remote syncs.
We would love to hear your opinion in our RFC for this new project: https://github.com/aws/aws-sam-cli/issues/3264
