### ISSUE TITLE
add support for NodejsFunction constructs

### ISSUE THREAD

**Issue by Andrapyre** [aws/aws-sam-cli#2988]
### Describe your idea/feature/enhancement

It would be a gamechanger if sam-cdk would fully support NodeJsFunction lambda constructs. 

### Things to consider: 
I would be happy to contribute to developing this solution, but I don't know the SAM product well enough to generate an initial proposal.

**Comment by CoshUS** [comment]
Thanks for the feedback. We will look into this for our CDK support.

**Comment by moelasmar** [comment]
The new released SAM CLI 1.37.0 supports `NodeJsFunction` construct.
