### ISSUE TITLE
AWS SAM go 1.6 "embed" https://golang.org/pkg/embed/

### ISSUE THREAD

**Issue by rockey5520** [aws/aws-sam-cli#2995]
### SAM supporting go 1.6 would be much helpful

We need to utilize some of the new features coming in go latest version such as "embed"

I wish the SAM would be able to build my code with go 1.6 features

**Comment by CoshUS** [comment]
SAM CLI builds your function with the Go SDK you installed locally. Can you elaborate a bit more on your issue and use case?

**Comment by rockey5520** [comment]
Sure, I was trying to use the embed feature (https://pkg.go.dev/embed) introduced in go 1.16. application is failing to build (sam build) when run on github actions

**Comment by jfuss** [comment]
SAM CLI uses whatever Go version is installed on your machine. If you need language features of a specific version, make sure the system you are building on has that version.

Closing
