### ISSUE TITLE
sam-beta-cdk support for typescript lambda functions - aws-lambda-nodejs

### ISSUE THREAD

**Issue by gommich** [aws/aws-sam-cli#3033]
**The feature:**
Would it be possible to add support for sam-cdk-beta to bundle typescript lambda functions using @aws-cdk/aws-lambda-nodejs (NodejsFunction) ?

**What I've tried:**
I have tried to use the @aws-cdk/aws-lambda-nodejs library to compile typescript functions as opposed to the @aws-cdk/aws-lambda library. However, what I notice is that when I run:

`sam-beta-cdk build` 

the assets for a @aws-cdk/aws-lambda-nodejs (NodejsFunction) function only produce an index.js asset in the .aws-sam/cdk-out/asset.xxxxxxxxxxxxx/ directory but package.json also needs to be in there for the function to be build properly.  If I manually add package.json from the function in question, then I can run 

`cdk deploy -a .aws-sam/build`

and the stack will deploy correctly. 

I'm not entirely sure if the solution would be as simple as adding package.json to the assets directory for a particular stack, but It seemed to work. Perhaps this is a feature I should request in the main aws-cdk repository. Please let me know if there's something I'm missing in my approach to creating typescript lambda functions.

**Comment by moelasmar** [comment]
thanks @gojko for reporting this issue, we are already tracking this as an internal task.

**Comment by LeoLapworthKT** [comment]
@moelasmar is there any update on this? - I had local development working on existing main
releases of sam/cdk before switching from plain lambda to lambdaNode cdk constructs a while ago and only just finding that it has broken this

Many thanks

**Comment by falnyr** [comment]
@mildaniel Thanks for pushing the https://github.com/aws/aws-lambda-builders/pull/307 over the line. What needs to be done on the SAM CLI side for this to work? Can we help out?

**Comment by mildaniel** [comment]
This is something we are currently working on, please keep an eye out for updates!

**Comment by phlcastro** [comment]
any ETA? or workaround we can do while we wait for it? thanks

**Comment by meg2208** [comment]
Is this still in the pipeline or currently available?

**Comment by mildaniel** [comment]
Hey all, we now support TypeScript in AWS SAM CLI natively through [esbuild](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build-typescript.html). In terms of CDK support, the [GA version](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-cdk-getting-started.html) of this feature is different than the beta. Please try that and report back if similar issues exist.
