### ISSUE TITLE
aws-sam-cli brew install issue on big_sur sha256 mismatch

### ISSUE THREAD

**Issue by jajainpanw** [aws/aws-sam-cli#3070]
==> Installing aws-sam-cli from aws/tap
==> Downloading https://ghcr.io/v2/homebrew/core/gdbm/manifests/1.20
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/c27d8af232565f7f16e912a20505b0d5ff83f6782835b9492840213cbf5fa5d2--gdbm-1.20.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gdbm/blobs/sha256:ea88ce09e9344
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/039ddb2682e5b93b3cd0ad30e130b5eab5bdb193e9e8d0239c9556958ccd992b--gdbm--1.20.big_sur.bottle.tar.gz
Error: SHA256 mismatch
Expected: ea88ce09e934407b1c7dfcc1b74e2d4f1b409f8264b4475b816369a129c6cd25
  Actual: 8c59b62431cfac465242e857fd97fff0ef429716cdaa3ba3ab0623aebb301bc2
    File: /Users/jajain/Library/Caches/Homebrew/downloads/039ddb2682e5b93b3cd0ad30e130b5eab5bdb193e9e8d0239c9556958ccd992b--gdbm--1.20.big_sur.bottle.tar.gz
To retry an incomplete download, remove the file above.
M-C02FRBLWMD6M:~ jajain$ vi /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/bottle-configs/aws-sam-cli.json
M-C02FRBLWMD6M:~ jajain$ 

M-C02FRBLWMD6M:~ jajain$ brew --version
Homebrew 3.2.2
Homebrew/homebrew-core (git revision cf82db6c42; last commit 2021-07-18)

M-C02FRBLWMD6M:~ jajain$ uname -a
Darwin M-C02FRBLWMD6M 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64
M-C02FRBLWMD6M:~ jajain$

**Comment by jajainpanw** [comment]
cat /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/bottle-configs/aws-sam-cli.json


{
    "version": "1.26.0",
    "url": "https://api.github.com/repos/aws/aws-sam-cli/tarball/v1.26.0",
    "sha256": "1bf2226b222cc055bcdc3fe714947f364ed086c1e99976eeefa90fc624522583",
    "name": "aws-sam-cli",
    "bin": "sam",
    "bottle": {
        "root_url": "https://github.com/aws/aws-sam-cli/releases/download/v1.26.0/",
        "sha256": {
            "sierra": "a9c061611fca605df4a79d7b2f027c9678b84c9b442cc2e0285c6e2050134f7d",
            "linux": "bab890b8725ca1cbf8317d8a837a6b0be55a392cb6d98361af6ce581518497a0"
        }
    }
}

**Comment by moelasmar** [comment]
Hello @jajainpanw,
I can see that the bottle hash in your comment is the same as the hash exist in [the release page](https://github.com/aws/aws-sam-cli/releases/tag/v1.26.0) 
`a9c061611fca605df4a79d7b2f027c9678b84c9b442cc2e0285c6e2050134f7d`

Could you please clarify which hash value you this is mismatching?

**Comment by jajainpanw** [comment]
Hi,

I dont understand the infra so cant comment on where this data is coming from. 

Downloading https://ghcr.io/v2/homebrew/core/gdbm/blobs/sha256:ea88ce09e9344. <<====
Error: SHA256 mismatch
Expected: ea88ce09e934407b1c7dfcc1b74e2d4f1b409f8264b4475b816369a129c6cd25
Actual: 8c59b62431cfac465242e857fd97fff0ef429716cdaa3ba3ab0623aebb301bc2.  <<===

Thanks

**Comment by moelasmar** [comment]
ok it is clear now, it seems this issue is related to some of the dependency libraries (gdbm)

**Comment by moelasmar** [comment]
Hi @jajainpanw 
Could you please try to remove this file 
`/Users/jajain/Library/Caches/Homebrew/downloads/039ddb2682e5b93b3cd0ad30e130b5eab5bdb193e9e8d0239c9556958ccd992b--gdbm--1.20.big_sur.bottle.tar.gz`
and retry to install sam-cli again.

**Comment by jajainpanw** [comment]
Hi @moelasmar 
Did a lot more this time but failed at the end.. 


=> Downloading https://ghcr.io/v2/homebrew/core/python/3.8/blobs/sha256:89be873
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://github.com/aws/aws-sam-cli/releases/download/v1.26.0//aw
==> Downloading from https://github-releases.githubusercontent.com/92205085/d906
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: a9c061611fca605df4a79d7b2f027c9678b84c9b442cc2e0285c6e2050134f7d.    <<===
  Actual: 3cea8900919bdedee5000f5ccc6c65b6053cca523022ac4f8233f144790d1937.   <<===
    File: /Users/jajain/Library/Caches/Homebrew/downloads/ca1eb601ec6cb0a98e30b541e10b02d6343bcdc691adcaf33d0fa80f75645aa9--aws-sam-cli-1.26.0.sierra.bottle.tar.gz
To retry an incomplete download, remove the file above.
M-C02FRBLWMD6M:sam-app1 jajain$

**Comment by jajainpanw** [comment]
full log

M-C02FRBLWMD6M:sam-app1 jajain$ brew install aws-sam-cli
==> Installing aws-sam-cli from aws/tap
==> Downloading https://ghcr.io/v2/homebrew/core/gdbm/manifests/1.20
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/c27d8af232565f7f16e912a20505b0d5ff83f6782835b9492840213cbf5fa5d2--gdbm-1.20.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gdbm/blobs/sha256:ea88ce09e934407b1c7dfcc1b74e2d4f1b409f8264b4475b816369a129c6cd25
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/039ddb2682e5b93b3cd0ad30e130b5eab5bdb193e9e8d0239c9556958ccd992b--gdbm--1.20.big_sur.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/manifests/2.5.1
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/f367c2ee08c56b88be0662703a8e4275f8657608a268c8c44e845154b0cea543--mpdecimal-2.5.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/blobs/sha256:255b6226cdcfaf0d40167012593e863e73dfed2884c10e7fc3eb4018e81712df
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/7a713d7515bcb7f82a8513288e409415e6a73138d89788bfa127be0540e1886b--mpdecimal--2.5.1.big_sur.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/1.1/manifests/1.1.1k
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/2efe91096994c33489c066631735a35cc3863cae64fc2ad5b305675fe9d24fed--openssl@1.1-1.1.1k.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/1.1/blobs/sha256:17d94c51ddfa8364baed5f3a754063e1ca75f807194f68d0b976619cf4e69c1a
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/bb270b9867427c49afbdb98f1dcb4accd99bf2517be61686f9c314007ff77849--openssl@1.1--1.1.1k.big_sur.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/readline/manifests/8.1
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/b37133a77c8680447162faf218b59fb36ee5d3e1926fbbff244e43581ab9128a--readline-8.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/readline/blobs/sha256:2cc3a9582e3c7e21eb3c2c8964abd33e9720fb4a9588c626d8424ff8cc9b1aed
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/f49b6ac0f3ac1b67953c3d559505d1f8d76e3e8fc12c0816ef70a4a01c3af9fa--readline--8.1.big_sur.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.36.0
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/f624e7fc68307d01f25a03c15c0a84ff3b65d4d984d85616e4181a685efd0548--sqlite-3.36.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/blobs/sha256:2c9c5f05c16c1fa972fc49c4b2705d7877b99640b6bb0b3908333e17f63dd71b
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/c27cd6f405f31a0171c05374d0dc9c4281f577e1822b52f5914cb2f40b647a7b--sqlite--3.36.0.big_sur.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/tcl-tk/manifests/8.6.11_1
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/f5f8f7d194b3a887b4c2af74ee0b185e08ad3152da55967646891ed86b6146b5--tcl-tk-8.6.11_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/tcl-tk/blobs/sha256:d9ffd39a32e602515594c4658aaab20224d9d57eeffa3aa10028736ff64ad40b
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/273605f332c8eb62fce0ed2c456db7e0f1a3e12cfc9f8e52cf6fd86a0f71e71c--tcl-tk--8.6.11_1.big_sur.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/xz/manifests/5.2.5
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/9447dbb900ef03dd46277002d89d92c65920edee6c60ea22c33be6cf99d01dc6--xz-5.2.5.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/xz/blobs/sha256:4fbd4a9e3eb49c27e83bd125b0e76d386c0e12ae1139d4dc9e31841fb8880a35
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/4aad911c8d5177a6e82f86c173926ed06886152fd1db8ba3648558b52d38bd82--xz--5.2.5.big_sur.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.8/manifests/3.8.11
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/292d996f15bb775f027a0cb009dfea8e17dfa91533586664aadee7fa35bf48b1--python@3.8-3.8.11.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.8/blobs/sha256:89be87388c1e29e0746891417c13d79d71294ddb78d494f1951d75109644d2cc
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/08a200ed316f9c1b4e1517434201b285f0a784e8ebc5fca6f65e34aba9515387--python@3.8--3.8.11.big_sur.bottle.tar.gz
==> Downloading https://github.com/aws/aws-sam-cli/releases/download/v1.26.0//aws-sam-cli-1.26.0.sierra.bottle.tar.gz
Already downloaded: /Users/jajain/Library/Caches/Homebrew/downloads/ca1eb601ec6cb0a98e30b541e10b02d6343bcdc691adcaf33d0fa80f75645aa9--aws-sam-cli-1.26.0.sierra.bottle.tar.gz
Error: SHA256 mismatch
Expected: a9c061611fca605df4a79d7b2f027c9678b84c9b442cc2e0285c6e2050134f7d
  Actual: 3cea8900919bdedee5000f5ccc6c65b6053cca523022ac4f8233f144790d1937
    File: /Users/jajain/Library/Caches/Homebrew/downloads/ca1eb601ec6cb0a98e30b541e10b02d6343bcdc691adcaf33d0fa80f75645aa9--aws-sam-cli-1.26.0.sierra.bottle.tar.gz
To retry an incomplete download, remove the file above.
M-C02FRBLWMD6M:sam-app1 jajain$

**Comment by qingchm** [comment]
@jajainpanw Hey there is this still a persisting issue for you? If so please let us know to help!

**Comment by wchengru** [comment]
I will close this issue because the latest version 1.37.0 has been released. Please reopen it if the problem still exists.
