### ISSUE TITLE
local start-api works with python lambda but not java

### ISSUE THREAD

**Issue by hoovertegan** [aws/aws-sam-cli#3071]
### Description:
I have a project that has 5 lambdas that work with api gateway. One of those lambdas is in python while the rest are in java. 
After running sam local start-api when I try to hit the python lambda, it works beautifully. But when I hit any of the Java lambdas, it gives me 
````[There was an error retrieving the questions: com.amazonaws.services.rdsdata.model.AWSRDSDataException: The security token included in the request is invalid. (Service: AWSRDSData; Status Code: 403; Error Code: UnrecognizedClientException; Request ID: 1234; Proxy: null)]````
I have my credentials located in a credentials file in my /.aws folder. Any suggestions would be helpful! 
All these lambdas work when deployed. This is only an issue when running sam local start-api

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. Windows 10
2. `sam --version`: 1.26.0
3. AWS region: us-east-2

`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
could you please share your project with us, and a detailed steps to reproduce the issue.

**Comment by hoovertegan** [comment]
The project is proprietary so I can not. The error only occurs on our Java lambdas and not our python one. Does the Java 8 runtime pull aws credentials differently than python?

**Comment by moelasmar** [comment]
it should not, we pass the aws credentials as environment variables for the created docker container.
is it possible to share a small version of your template, and the Java code to investigate it.

**Comment by moelasmar** [comment]
can I ask you to log in all the environment variables in your Python and Java code so we can see what is the difference between both of them.

in python you can use something like 
```
import os
print(os.environ)
```
and in java
```
    Map<String, String> env = System.getenv();
    env.forEach((k, v) -> System.out.println(k + ":" + v));
```

**Comment by xazhao** [comment]
Closing this issue since it has been inactive for 23 days. If you still have other questions, feel free to reopen this issue or create another issue.
