### ISSUE TITLE
Deduplicated build is still not fast

### ISSUE THREAD

**Issue by yskkin** [aws/aws-sam-cli#3093]
### Describe your idea/feature/enhancement
I have ~10 lambdas written in JS.
These lambdas share CodeUri, Runtime and Metadata and thus dedeplicated build is enabled.

`sam build`ing my project is still slow.

This is last output of `sam build --debug`:

```
2021-07-21 12:17:46,950 | Copying artifacts from /path/to/repo/.aws-sam/build/func1 to /path/to/repo/.aws-sam/build/func2
2021-07-21 12:17:56,472 | Copying artifacts from /path/to/repo/.aws-sam/build/func1 to /path/to/repo/.aws-sam/build/func3
```

Copying built lambda took 10 seconds due to large node_modules dependency.
Copying 10 lambdas took 90 seconds.

### Proposal

Symlinking instead?

**Comment by aahung** [comment]
Wonder is it feasible to use symlink in this case. Need to investigate whether `local invoke` and other SAM CLI features can handle symlinks or not.

**Comment by mildaniel** [comment]
The fix has been released in 1.54.0! Resolving. You can now use this functionality using the `experimentalBuildPerformance` feature flag!

**Comment by yskkin** [comment]
Saw significant build performance improvement with `sam build --beta-features`. Thanks ❤️

**Comment by having-fun-serverless** [comment]
@mildaniel why aren't you promoting this beta feature to be released?
