### ISSUE TITLE
secrets.AWS_ACCESS_KEY_ID not shown in pipeline bootstrap

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sam-cli#3130]
`sam pipeline init --bootstrap` following https://aws.amazon.com/blogs/compute/introducing-aws-sam-pipelines-automatically-generate-deployment-pipelines-for-serverless-applications/

### Description:
No idea how to fill in secrets.AWS_ACCESS_KEY_ID

### Steps to reproduce:
`sam pipeline init --bootstrap`

### Observed result:
https://github.com/kaihendry/sam-pipeline-test

### Expected result:
Show the credentials to put into https://github.com/kaihendry/sam-pipeline-test/settings/secrets/actions

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. `sam --version`: SAM CLI, version 1.27.2
3. AWS region: ap-southeast-1

`Add --debug flag to command you are running`

**Comment by sriram-mv** [comment]
@kaihendry if I understand correctly, is it that the SAM CLI does not showcase what is expected from users? or its about the education aspect of a guided workflow that could be better?

**Comment by kaihendry** [comment]
I think the guided workflow is setting up the workflow, which requires secrets to run. It doesn't show those secrets so you can add then, so I am wondering how on earth are people supposed to know what to do?

**Comment by c2tarun** [comment]
@kaihendry, credentials are only shown if a user is created by the bootstrap flow. There are situation where user will not be created:
1. If a user arn is provided.
2. If a user is found by a previous bootstrap.

User credentials are also saved in Secrets Manager so you can get those credentials from there. Please let me know if this helps?

**Comment by kaihendry** [comment]
Ah! I see it in https://ap-southeast-1.console.aws.amazon.com/secretsmanager/ ... thank you. That wasn't obvious to me. 

Especially for someone more familiar with SSM Parameter Store
