### ISSUE TITLE
Cache is missed when building Layer inside a container

### ISSUE THREAD

**Issue by Macok** [aws/aws-sam-cli#3133]
### Description:
When a Layer is built using `--use-container` option and any `--container-env-var` are passed, the cache is always missed.
This was already fixed by @mndeveci here: https://github.com/aws/aws-sam-cli/pull/2943, but only for Lambda Functions, while the same problem exists for layers.

### Steps to reproduce:

Run below command twice to build any Layer (it will work fine in case of Functions) and see that the cache is not valid.
`sam build --cached --use-container --container-env-var FOO=BAR`

### Observed result:

Cache is missed.

### Expected result:

Cache should be hit.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. `sam --version`: SAM CLI, version 1.27.2
3. AWS region: N/A

### Why does this happen?
Just like in case of https://github.com/aws/aws-sam-cli/pull/2943, a dictionary of env variables is being passed to the build function by `DefaultBuildStrategy.build_single_layer_definition`. Additional `LAMBDA_BUILDERS_LOG_LEVEL` variable is added to the dictionary, causing cache miss. We need to make a deepcopy of this dictionary, just like in `DefaultBuildStrategy.build_single_function_definition`.

I'm happy to work on a fix as soon as someone confirms my observations.

**Comment by sriram-mv** [comment]
@Macok sounds like a very good contribution to take on.

**Comment by Macok** [comment]
Awesome, I'll submit a PR later this week.

**Comment by Macok** [comment]
Done, waiting for review: #3139
