### ISSUE TITLE
Building samcli from src breaks

### ISSUE THREAD

**Issue by kingram6865** [aws/aws-sam-cli#3150]
### Description:

I'm attempting to bypass #3149  by compiling from scratch.
Fortunately, lacking instructions, I was able to do that, however, this build script is fraught with difficulties, namely that it demands yum. What if apt is the primary package installer?

Also, what if you have to run the script again? Itt should check to see what's installed before presuming to download and install things.

### Steps to reproduce:

1. clone the repo onto any Debian-based linux server
2. cd to sam-installation/aws-sam-cli-src/installer/pyinstaller
3. execute build-linux.sh
4. Watch the sparks fly

### Observed result:

```
if test "xupgrade" != "xno"  ; then \
        case upgrade in \
                upgrade) ensurepip="--upgrade" ;; \
                install|*) ensurepip="" ;; \
        esac; \
        LD_LIBRARY_PATH=/PUBLIC/DOWNLOADS/sam-installation/aws-sam-cli-src/installer/pyinstaller/.build/Python-3.7.9 ./python -E -m ensurepip \
                $ensurepip --root=/ ; \
fi
Looking in links: /tmp/tmp12p538si
Requirement already up-to-date: setuptools in /usr/local/lib/python3.7/site-packages (47.1.0)
Requirement already up-to-date: pip in /usr/local/lib/python3.7/site-packages (20.1.1)
Installing Python Libraries
python3: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory


```
The library exists in 

```
$ find ./ -iname 'libpython3.7*'
./.build/Python-3.7.9/libpython3.7m.so.1.0
./.build/Python-3.7.9/libpython3.7m.so
./.build/Python-3.7.9/libpython3.7m.a

```

### Expected result:

A compiled and ready to install samcli

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu server 20.04
2. `sam --version`: N/A
3. AWS region: N/A

`Add --debug flag to command you are running`

**Comment by kingram6865** [comment]
I've managed to figure out the problem. All me. Working to late, lack of sleep => not so smart.

**Comment by cpilson** [comment]
> I've managed to figure out the problem. All me. Working to late, lack of sleep => not so smart.

What was the resolution?
