### ISSUE TITLE
[sam-beta-cdk] (CDK Pipelines): Template does not have any APIs connected to Lambda functions

### ISSUE THREAD

**Issue by joekendal** [aws/aws-sam-cli#3155]
### CDK Pipelines

Let's say we are using CDK Pipelines:
```
$ cdk ls
MyPipeline
MyPipeline/Dev/MyStack
MyPipeline/Prod/MyStack
```

SAM CLI does not work with CDK Pipelines as when you try to use the CLI on the artifacts:

```
$ sam-beta-cdk build
Synthesizing CDK App

Build Succeeded
...
```
```
$ sam-beta-cdk local start-api
```
you get:

`Error: Template does not have any APIs connected to Lambda functions`

### Proposal

Have it traverse all assembly artifacts to find the CFN resources.

**Comment by hawflau** [comment]
Hey @joekendal, thanks for reporting the issue! Would you be able to provide more info (e.g. your CDK app code) for us to reproduce the issue?

**Comment by CoshUS** [comment]
Closing as no information was provided by requester.
