### ISSUE TITLE
`sam build` fails with gradle, not compatible with gradle >=6.1.1 for Kotlin usage

### ISSUE THREAD

**Issue by caladev** [aws/aws-sam-cli#3178]
### Description:
It appears that when doing `sam init` to create a new sam project, when choosing the gradle build tool it is generating a really old version of the gradle wrapper (5.1.1) from January 2019 as per https://gradle.org/releases/ 

Could I please ask if it could be considered that the gradle wrapper be updated to the latest stable version (eg. 6.x or 7.x) so it is compatible for use with the Kotlin language.

### Steps to reproduce:
I created a new template from quick start, with the Image package type, with amazon/java11-base and gradle dependency manager.

I made the following changes to the generated code:

* Renamed `build.gradle` into a `build.gradle.kts` so I can use the Kotlin DSL. 
* In my `build.gradle.kts` I added the Kotlin plugin as follows:

```
plugins {
    kotlin("jvm") version "1.5.21"
}
...
```

* I updated the Dockerfile where it has `COPY build.gradle gradlew ./` I modified it to` COPY build.gradle.kts gradle.properties settings.gradle.kts gradlew ./`

### Observed result:
```
An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.jvm', version: '1.5.21']
> Failed to apply plugin [id 'org.jetbrains.kotlin.jvm']
   > The current Gradle version 5.1.1 is not compatible with the Kotlin Gradle plugin. Please use Gradle 6.1.1 or newer, or the previous version of the Kotlin plugin.
```

Attempt to fix: 
By manually changing the gradle wrapper to 6.1.1 as the output suggests (changing the version in `/samcliapp/myfunction/gradle/gradle-wrapper.properties`) results in a successful local gradle build, but a broken `sam build --debug` when using the `Image` package type, output as follows:

```
Building image for myfunction function
Setting DockerBuildArgs: {} for myfunction function
Step 1/16 : FROM public.ecr.aws/lambda/java:11 as build-image
 ---> d5c90c84cabb
Step 2/16 : ARG SCRATCH_DIR=/var/task/build
 ---> Using cache
 ---> 461565bf8c7e
Step 3/16 : COPY src/ src/
 ---> Using cache
 ---> 147eb0b9c972
Step 4/16 : COPY gradle/ gradle/
 ---> Using cache
 ---> 647b7ebe0980
Step 5/16 : COPY build.gradle.kts gradle.properties settings.gradle.kts gradlew ./
 ---> 8d945f26d8b0
Step 6/16 : RUN mkdir build
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 85f77b23aac9
 ---> 90da63f25a94
Step 7/16 : COPY gradle/lambda-build-init.gradle ./build
 ---> f3cfed8a9816
Step 8/16 : RUN ./gradlew --project-cache-dir $SCRATCH_DIR/gradle-cache -Dsoftware.amazon.aws.lambdabuilders.scratch-dir=$SCRATCH_DIR --init-script $SCRATCH_DIR/lambda-build-init.gradle build
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 031684df27a0
Downloading https://services.gradle.org/distributions/gradle-6.1.1-bin.zip
............................................................................................

Welcome to Gradle 6.1.1!

Here are the highlights of this release:
 - Reusable dependency cache
 - Configurable compilation order between Groovy/Kotlin/Java/Scala
 - New sample projects in Gradle's documentation

For more details see https://docs.gradle.org/6.1.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not open cache directory 8roygttxgwdrnyip8w45payt7 (/root/.gradle/caches/6.1.1/gradle-kotlin-dsl/8roygttxgwdrnyip8w45payt7).
> Path in JarFileSystem must contain a separator: /root/.gradle/wrapper/dists/gradle-6.1.1-bin/4i3ntwqiazourd86epxcz427c/gradle-6.1.1/lib/failureaccess-1.0.1.jar!/

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 20s

Build Failed
```

### Expected result:
`sam build` should succeed.

Having read over the [gradle design document](https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/java_gradle/DESIGN.md) it seems this is not so straight forward with gradle. My best guess is that there is a breaking change in the generated gradle 5.1.1 wrapper that worked with the generated `lambda-build-init.gradle` [see here where it's coming from](https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/java_gradle/resources/lambda-build-init.gradle) that refers to `File` operations, that may have breaking changes in the newer versions of Gradle, although I'm not expert on gradle itself. Googling for `Path in JarFileSystem must contain a separator` doesn't warrant many results so I don't know what to search for now.

I also tried refactoring my `build.gradle.kts` back to a `build.gradle` with the same dependencies but with Groovy instead of the Kotlin DSL and the same thing occurs, so I don't think it is the usage of `build.gradle.kts` that is the issue. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 11.5.2
2. `sam --version`: 1.27.2
3. AWS region: ap-southeast-2

**Comment by caladev** [comment]
@dagnir I noticed you authored https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/java_gradle/DESIGN.md would be great to hear your opinion

**Comment by caladev** [comment]
After further investigation, to resolve the issue of `Path in JarFileSystem must contain a separator` I added the following to my `build.gradle.kts`:

```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

...

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "11"
}

```

I think it will still be worth revisiting the initial ask of updating `sam build` when using gradle to use something way newer than 5.1.1 by default.

**Comment by ssenchenko** [comment]
Thank you for posting a work-around! We've added this issue to our queue

**Comment by jfuss** [comment]
Seems like we have bumped gradle recently: https://github.com/aws/aws-sam-cli-app-templates/blob/master/java11/cookiecutter-aws-sam-hello-java-gradle/%7B%7Bcookiecutter.project_name%7D%7D/HelloWorldFunction/gradlew

If this is still an issues, please create an issue under https://github.com/aws/aws-sam-cli-app-templates as that is were all our examples live now.
