### ISSUE TITLE
Apple M1: thread 'main' panicked at 'attempt to divide by zero'

### ISSUE THREAD

**Issue by tolumide-ng** [aws/aws-sam-cli#3187]
### Description:
I experience this error: `thread 'main' panicked at 'attempt to divide by zero'` when I try to access an endpoint on the function.

### Steps to reproduce:
Run `sam-beta-cdk local start-api -p <PORT> --skip-pull-image --warm-containers EAGER --debug`

### Observed result:
```
2021-08-20 09:00:27,794 | Found one Lambda function with name '<FUNCTION_NAME>'
2021-08-20 09:00:27,794 | Invoking Container created from <FUNCTION_NAME>
2021-08-20 09:00:27,794 | Environment variables overrides data is standard format
2021-08-20 09:00:27,814 | Reuse the created warm container for Lambda function '<FUNCTION_NAME>'
2021-08-20 09:00:27,821 | Lambda function '<FUNCTION_NAME>' is already running
2021-08-20 09:00:27,822 | Starting a timer for 10 seconds for function '<FUNCTION_NAME>'
START RequestId: <REQUEST_ID> Version: $LATEST
thread 'meter_probe' panicked at 'Unable to read /proc for agent process: InternalError(bug at /local/p4clients/pkgbuild-QP4Aq/workspace/build/AWSLogsLambdaInsights/AWSLogsLambdaInsights-1.0.115.0/AL2_x86_64/DEV.STD.PTHREAD/build/private/cargo-home/registry/src/-c477fb05a7ac3d62/procfs-0.7.9/src/process/stat.rs:300 (please report this procfs bug)
Internal Unwrap Error: Internal error: bug at /local/p4clients/pkgbuild-QP4Aq/workspace/build/AWSLogsLambdaInsights/AWSLogsLambdaInsights-1.0.115.0/AL2_x86_64/DEV.STD.PTHREAD/build/private/cargo-home/registry/src/-c477fb05a7ac3d62/procfs-0.7.9/src/lib.rs:285 (please report this procfs bug)
Internal Unwrap Error: NoneError)', src/inputs/memory.rs:59:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'attempt to divide by zero', src/inputs/memory.rs:44:32
```

### Expected result:
`Return appropriate result from the endpoint`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Big Sur v11.5.1
2. `sam --version`: SAM CLI, version 1.22.0.dev202107140310
3. AWS region: eu-central-1

`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
Could you please share some more details about the CDK project you used in testing. If it possible to share it with us through github will be helpful in investigation.

**Comment by tolumide-ng** [comment]
The cdk project is Graphql based. I don't think I can share it 🥺

**Comment by NicolaiSchmid** [comment]
I'm facing the same issue at v1.29.0, also on M1

**Comment by ssenchenko** [comment]
It's not enough info for reproducing and investigating the issue. Closing for now.

**Comment by kitsunde** [comment]
@ssenchenko 

This seem to happen across AWS lambda projects that include `LambdaInsightsExtension`. Also see this issue: https://github.com/aws/aws-sam-cli/issues/2469#issuecomment-985550710

We have the same issue on M1 macOS and are working around it by detecting the dummy account `123456789012` and not including the insights layer on local incoke.

```yaml
Conditions:
  IsLocal: !Equals [123456789012, !Ref AWS::AccountId]
```

Then

```yaml
Layers;
  - !If [!Ref IsLocal, "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:18", !Ref AWS::NoValue]
```

This happens when running:

```
sam local invoke MyFunction
```

Log:

```
Mounting /Foo/src as /var/task:ro,delegated inside runtime container
START RequestId: 58aa7e5d-12c9-4296-981a-08aaf62acb65 Version: $LATEST
thread 'meter_probe' panicked at 'Unable to read /proc for agent process: InternalError(bug at /local/p4clients/pkgbuild-Y79dR/workspace/build/AWSLogsLambdaInsights/AWSLogsLambdaInsights-1.0.135.0/AL2_x86_64/DEV.STD.PTHREAD/build/private/cargo-home/registry/src/-83179af10ac8becc/procfs-0.11.1/src/process/stat.rs:310 (please report this procfs bug)
Internal Unwrap Error: Internal error: bug at /local/p4clients/pkgbuild-Y79dR/workspace/build/AWSLogsLambdaInsights/AWSLogsLambdaInsights-1.0.135.0/AL2_x86_64/DEV.STD.PTHREAD/build/private/cargo-home/registry/src/-83179af10ac8becc/procfs-0.11.1/src/lib.rs:257 (please report this procfs bug)
Internal Unwrap Error: NoneError)', src/inputs/memory.rs:59:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'attempt to divide by zero', src/inputs/memory.rs:44:32
```

**Comment by zyks** [comment]
Any news regarding the issue? It has not been solved, I'm still facing it on M1.

To reproduce the issue you just have to invoke any lambda locally with Lambda Insights turned on

**Comment by mo2menelzeiny** [comment]
Actually I think this is the expected behaviour, if you're on Apple M1 you should use the arm64 as it pulls the appropriate images to your docker engine, so the extension version for would be: `arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension-Arm64:2`

**Comment by oscarrodar** [comment]
This is currently happening to me as well.
