### ISSUE TITLE
exclude flag in `sam build` which will exclude a particular resource

### ISSUE THREAD

**Issue by nagmesh** [aws/aws-sam-cli#3189]
### Describe your idea/feature/enhancement
I have templates which have over 10 functions and as application grows the number of functions grows as well.

Provide a clear description. Ex. I wish SAM CLI would [...]
I want SAM CLI to leave specific resources while doing a build. I have lambda functions which I do not want sam cli to build but scan the rest of the resources 
### Proposal

Add details of how to add this to the product.

Add an exclude flag with comma separated values of resources to exclude
When SAM scans in the [iterator](https://github.com/aws/aws-sam-cli/blob/develop/samcli/lib/build/app_builder.py#L110) remove the excluded values before starting the build.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

**Comment by ssenchenko** [comment]
To be sure, are you asking about having partial build? If your lambdas have interdependencies they need to be build together. If they don't have dependencies you can split them into separate projects and build smaller projects.

**Comment by nagmesh** [comment]
Currently, I can build sam resource specifically using `sam build $LOGICAL_RESOURCE_NAME`
However, I want sam to only exclude one resource in my template and build the rest.

**Comment by ssenchenko** [comment]
We have a [roadmap](https://github.com/aws/aws-sam-cli/wiki/SAM-CLI-Roadmap) here, but we also try to take in popular feature requests based on 👍🏽 from the community. If this issue gets some votes we will be adding this to our intake for prioritization.

**Comment by mndeveci** [comment]
This is been released with [SAM CLI v1.51.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.51.0)
