### ISSUE TITLE
Sensible strategy for uninstalling and managing installed versions of SAM CLI

### ISSUE THREAD

**Issue by specious** [aws/aws-sam-cli#3191]
I followed the entire discussion in #1424 which centered on the various options for the installation procedure. Eventually a custom installer was produced, which allows upgrading or downgrading after downloading a different release bundle and running its installer. However, I haven't been able to find any mention of how to completely remove the installation.

What's the currently recommended procedure for performing a clean uninstall?

**Comment by specious** [comment]
By looking at the install script, it looks like this will essentially do it:
```
rm /usr/local/bin/sam
rm -rf /usr/local/aws-sam-cli
```
However, this is somewhat obscure as well as unreliable.

It seems like a provision for a clean uninstall in the general case would be appreciated by more than a few users.

**Comment by specious** [comment]
Also, it looks like versions are installed alongside each other when using `install -u`, with the last one installed being set as `current`:
```
$ ls -l /usr/local/aws-sam-cli

total 7
drwxr-xr-x 4 root root 3488 Aug 20 23:19 1.27.2
drwxr-xr-x 4 root root 3488 Aug 20 23:17 1.29.0
lrwxrwxrwx 1 root root   29 Aug 20 23:19 current -> /usr/local/aws-sam-cli/1.29.0

$ ls -l /usr/local/bin/sam

lrwxrwxrwx 1 root root   38 Aug 20 23:19 sam -> /usr/local/aws-sam-cli/current/bin/sam
```

It seems like there should be an officially recommended approach to version management.

**Comment by specious** [comment]
Also, it seems like the `current` symlink should be relative rather than absolute:
```
current -> 1.29.0
```

**Comment by CoshUS** [comment]
Thanks for the feedback. For uninstallation, we have documentation around the process: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html

Closing. Let me know if there are other issues.
