### ISSUE TITLE
sam package ignores image_repositories in samconfig.toml

### ISSUE THREAD

**Issue by agutierrezl** [aws/aws-sam-cli#3200]
### Description:
I'm creating a pipeline to deploy a serverless application using SAM. As part of the pipeline, I execute `sam package` command and it fails stating the options `--image-repository or --image-repositories are missing` despite the fact I'm passing the `--config-file prod-samconfig.toml ` option containing the image-repositories. For some reason, it ignores the `--config-file` option rising the error.
```
[Container] 2021/08/24 14:19:43 Running command sam package --template-file ./.aws-sam/build/template.yaml --config-file prod-samconfig.toml
258 | Usage: sam package [OPTIONS]
259 | Try 'sam package -h' for help.
260 |  
261 | Error: Missing option '--image-repository' or '--image-repositories'
262 |  
263 | [Container] 2021/08/24 14:19:44 Command did not exit successfully sam package --template-file ./.aws-sam/build/template.yaml --config-file prod-samconfig.toml exit status 2
264 | [Container] 2021/08/24 14:19:44 Phase complete: BUILD State: FAILED
265 | [Container] 2021/08/24 14:19:44 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: sam package --template-file ./.aws-sam/build/template.yaml --config-file prod-samconfig.toml. Reason: exit status 2
```

### Steps to reproduce:
````
sam --version
SAM CLI, version 1.29.0
````
````
sam package --template-file ./.aws-sam/build/template.yaml --config-file prod-samconfig.toml
Usage: sam package [OPTIONS]
Try 'sam package -h' for help.

Error: Missing option '--image-repository' or '--image-repositories'
````
````
cat prod-samconfig.toml | grep repositories
image_repositories = ["UsersFunction=XXXXXXXXX.dkr.ecr.eu-central-1.amazonaws.com/my-api"]
````

### Observed result:

```
sam package --template-file ./.aws-sam/build/template.yaml --config-file prod-samconfig.toml --debug
Usage: sam package [OPTIONS]
Try 'sam package -h' for help.

Error: Missing option '--image-repository' or '--image-repositories'
```

### Expected result:
I expect that sam cli uses the specified config-file with all the configuration parameters instead of rising a missing options error when the option is in the config-file

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: WIN10 and also using code build with the image aws/codebuild/standard:5.0
2. `sam --version`: SAM CLI, version 1.29.0
3. AWS region: eu-central-1

**Comment by sriram-mv** [comment]
What does your full prod-samconfig.toml file look like, do you have image_repositories defined under the "package" section or the "deploy" section?

**Comment by sriram-mv** [comment]
if you add entry like below for `package`
```
version = 0.1
[default]
[default.package]
[default.package.parameters]
stack_name = "xxxx"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = ["UsersFunction=XXXXXXXXX.dkr.ecr.eu-central-1.amazonaws.com/my-api"]
```

This should work.

the configuration files work by having a section per command, and each command has a set of parameters.

**Comment by solarmosaic-kflorence** [comment]
@sriram-mv this should not be closed. I ran into this using `sam deploy`:

The `samconfig.toml`:
```toml
version = 0.1

[default.build.parameters]
parameter_overrides = [
  "BuildVersion=SNAPSHOT",
  "FunctionName=kubernetes-deployer"
]

[default.local_invoke.parameters]
parameter_overrides = [
  "ClusterName=docker-desktop"
]

[default.package.parameters]
image_repository = "<REDACTED>"

[default.deploy.parameters]
image_repository = "<REDACTED>"
stack_name = "kubernetes-deployer-3057"
```

The command:
```
sam deploy \
  --config-env default \
  --profile default \
  --region us-east-1 \
  --stack-name kubernetes-deployer-3057 \
  --template-file .aws-sam/build/packaged.yaml
```

Results in: `Error: Missing option '--image-repository', '--image-repositories', or '--resolve-image-repos'`.

The same thing happens if I don't provide `--stack-name`: `Error: Missing option '--stack-name', 'sam deploy --guided' can be used to provide and save needed parameters for future deploys.`

```
sam --version
SAM CLI, version 1.37.0
```
