### ISSUE TITLE
When testing locally with sam local start-api... somes properties name got their first letter Capitalize ?!

### ISSUE THREAD

**Issue by stevesirois** [aws/aws-sam-cli#3208]
### Description:
I'm coding a Lambda function that need to extract some claims from a JWT token. When the code is deploy on AWS, everything is fine but locally I got an error concerning the access to that token. The problem raise from the fact that locally, in the event object, the property read "Authorization" instead of "authorization". So the token is no more accessible with this annotation : event.headers.authorization ( this is now undefined in nodejs)

### Steps to reproduce:
Simply create a Lamdba with sam template using hello world, start it locally then use a tool like Postman and add Bearer Token Authorization to a simple GET REST call. In the code, simply send to the console the event object. 

### Observed result:
When deploy on AWS --> console.info(event)
...
accept: '*/*',
'accept-encoding': 'gzip, deflate',
authorization: 'Bearer eyJraWQiOiJkWk0xe ... Q7zjKbuYFxkb1wvXwlO2',
'cache-control': 'no-cache',
'content-length': '0',
 ....
When running locally ( sam local start-api )  --> console.info(event)
...
START RequestId: d3e77593-5853-419a-86c8-d89f8b3041e0 Version: $LATEST
    Authorization: 'Bearer eyJraWQiOiJkWk0xe ... Q7zjKbuYFxkb1wvXwlO2',
    isBase64Encoded: false
...
### Expected result:
No capital 'A' but all lowercase property name
authorization: 'Bearer eyJraWQiOiJkWk0xe ... Q7zjKbuYFxkb1wvXwlO2'

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20.04.2 LTS
2. SAM CLI : 1.29.0
3. AWS region: ca-central-1

### Additional comments

I also tried it in debug mode in VS Code and in the launch.json, I added a headers section in the api, all lowercase. But when it run, the output of the object show a capital A for Authorization. I also realized that other property like accept ou origin got the same treatment. I also tried to JSON.parse the object to see if it "normalize" it but it's the same result... AWS all lowercase, local sam get is first letter in uppercase. I also tried a direct invocation with sam local invoke with a event.json file, but this time it keep it in lowercase!? So this behaviour seems only affecting the api invocation.

**Comment by prenx4x** [comment]
Hello,
As per RFC 2616 headers are not case sensitive. This is discussed in depth in previous issue https://github.com/aws/aws-sam-cli/issues/1860.
Can you make changes to your code to reference headers in a case insensitive way?
Thanks.
