### ISSUE TITLE
Add Support Disable Rollback Flage

### ISSUE THREAD

**Issue by marcato15** [aws/aws-sam-cli#3228]
It'd be nice if SAM supported the new Rollback Failure options that were announced this week and detailed here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stack-failure-options.html

Could we add a flag to the SAM commands that includes `--disable-rollback`?

**Comment by awood45** [comment]
This is a good shoutout, absolutely.

**Comment by jfuss** [comment]
This has been released. You can add `--disable-rollback` or 1--no-disable-rollback` to `sam deploy`.

Closing
