### ISSUE TITLE
sam-beta-cdk fails to deploy if 2 lambda function inside different constructs have the same id

### ISSUE THREAD

**Issue by Jahor** [aws/aws-sam-cli#3241]
### Description:
If stack consists of multiple constructs, each containing lambda function with code from an asset, deploy fails if construct id of those functions are the same (even though IDs in the final CF template are not)

### Steps to reproduce:
1. Create cdk project
2. In stack code add 2 construct classes each with lambda function with asset-based code. Both lambda functions to have id='Handle', for example
3. Instantiate those constructs in stack with different Ids
4. build and deploy 
(see attached example [ntl.zip](https://github.com/aws/aws-sam-cli/files/7108838/nlt.zip))

### Observed result:
```
File with same data already exists at NestedLambdaTestStack/31e1577957b1dd9b510c25704b66ccfc, skipping upload
File with same data already exists at NestedLambdaTestStack/31e1577957b1dd9b510c25704b66ccfc, skipping upload

	Deploying with following values
	===============================
	Stack name                   : NestedLambdaTestStack
	Region                       : ap-southeast-2
	Confirm changeset            : False
	Deployment s3 bucket         : aws-sam-cli-managed-default-samclisourcebucket-*****
	Capabilities                 : ["CAPABILITY_IAM"]
	Parameter overrides          : {}
	Signing Profiles             : {}

Initiating deployment
=====================
File with same data already exists at NestedLambdaTestStack/12f2f8025c61eaaa8c8258dbdae558b6.template, skipping upload
Error: Failed to create changeset for the stack: NestedLambdaTestStack, An error occurred (ValidationError) when calling the CreateChangeSet operation: Parameters: [AssetParameters377db0f279234f8c4fd398e174645c6adf108ca3aef5f39b4721c6c6f49e9332S3BucketB26E2755, AssetParameters377db0f279234f8c4fd398e174645c6adf108ca3aef5f39b4721c6c6f49e9332ArtifactHashA2721B1A, AssetParameters377db0f279234f8c4fd398e174645c6adf108ca3aef5f39b4721c6c6f49e9332S3VersionKey760FDE6C] must have values
```

### Expected result:
Succesful deployment

### Additional environment details 
1. OS: MacOS 11.5.2 (20G95)
2. `sam-beta-cdk --version`: SAM CLI, version 1.29.0.dev202108311500
3. `cdk --version`: 1.121.0 (build 026cb8f)
4. AWS region:  ap-southeast-2

**Comment by aahung** [comment]
Thanks for reporting it

**Comment by hawflau** [comment]
@Jahor Thanks for reporting the issue. I've confirmed it's a bug and we will prioritize fixing it.

**Comment by moelasmar** [comment]
This issue is working fine in the new released CDK support, but we do not support deploying CDK applications using `sam` and you can use `cdk deploy` instead.

Can I ask if you have a special use case to use `sam deploy` instead of `cdk deploy`
