### ISSUE TITLE
Invalid lambda response received: Lambda response must be valid json

### ISSUE THREAD

**Issue by debragail** [aws/aws-sam-cli#3260]
Close the issue since we released two options `--container-host` and `--container-host-interface`. In short, if you would like to run SAM CLI in a docker container on macOS or Windows, use `--container-host` with value `host.docker.internal` will have SAM CLI work properly.

_Originally posted by @xazhao in https://github.com/aws/aws-sam-cli/issues/2436#issuecomment-827950506_

This error is happening with just the sam cli on mac os for me and i'm not using a docker container when running these commands, i am running on my local machine without docker.

**Comment by xazhao** [comment]
Hey @debragail, could you use the template and add some details so that we can know more about the issue? Thanks!

**Comment by debragail** [comment]
> Hey @debragail, could you use the template and add some details so that we can know more about the issue? Thanks!

Where's the template

**Comment by aahung** [comment]
> Where's the template

The Github issue template: https://github.com/aws/aws-sam-cli/issues/new?assignees=&labels=&template=Bug_report.md&title=

**Comment by CoshUS** [comment]
Closing as this issue is inactive.
Feel free to leave more information below and I can reopen this issue.
