### ISSUE TITLE
[Exploration] Creating Integration Tests

### ISSUE THREAD

**Issue by praneetap** [aws/aws-sam-cli#3266]
Currently, it can be challenging to write reliable integration tests against serverless applications.
We want to explore ways this process can be made easier using SAM CLI (Serverless Application Model Command Line Interface), and need your feedback. Here are a few ideas we are thinking about - 

* Manage timeouts and retries for tests targeting event driven applications
* Optimize test execution time
* Auto generate test payloads for a set of AWS services

Please feel free to drop your ideas/requests pertaining to integration testing in the comments. Specifically, what are the sticky issues you run into when writing tests for serverless applications on AWS? Do the ideas above accurately address the pain points?

**Comment by kaihendry** [comment]
With https://aws.amazon.com/blogs/compute/getting-started-with-serverless-for-developers-part-4-local-developer-workflow/ in mind we need the input and output to build regression tests.

<img src="https://d2908q01vomqb2.cloudfront.net/1b6453892473a467d07372d45eb05abc2031647a/2021/04/19/Screenshot-2021-04-19-at-11.12.38.png">

Would be good to somehow quickly get a real input event from an existing function for creating local tests. Currently this is a rather **painful process** to console.log / stringify the incoming event and somehow extract it into a local JSON file.  We don't want a sample event via `sam local generate-event`, that lacks the context of what we want to test.

Furthermore if the process makes network calls etc, it would be good if the tool (e.g. aws-sam-cli) could identify these dependencies that need to be mocked...

**Comment by Leigh-M** [comment]
For integration & e2e testing, usually need to spin up a full test stack and with controlled inputs test the outputs; to avoid having to spin up full test stack would be great if there was an ‘in-memory’ representation of the stack for speed, could be controlled via Jest or Mocha & use regular TDD workflow and SAM.

**Comment by jfuss** [comment]
Moved to Discussions: https://github.com/aws/aws-sam-cli/discussions/4691

Closing
