### ISSUE TITLE
[Tracking issue] SAM CLI Roadmap

### ISSUE THREAD

**Issue by praneetap** [aws/aws-sam-cli#3267]
We published the [SAM CLI roadmap](https://github.com/aws/aws-sam-cli/wiki/SAM-CLI-Roadmap). Please feel free to leave comments/requests regarding the roadmap in this issue.

**Comment by jfuss** [comment]
We moved this to Discussions and dedup with https://github.com/aws/aws-sam-cli/discussions/4689

Closing
