### ISSUE TITLE
Pretty print option for sam local invoke output

### ISSUE THREAD

**Issue by buildbreakdo** [aws/aws-sam-cli#327]
A nice-to-have would be a pretty print option that could be passed to sam local invoke.

**Comment by jfuss** [comment]
@buildbreakdo What do you mean by pretty print? Can you give us an example to help us understand what you are looking for in the output.

**Comment by seanlindo** [comment]
@jfuss Any output coming from SAM CLI (v1.2.0) is presented on a single line. This makes working with and inspecting JSON of any consequence difficult.

**Comment by tdreid92** [comment]
I've noticed this only applies when I updated my function's Event Source from API to HttpApi. Could be missing something still though. The header response contains the application/json content-type still.

**Comment by tdreid92** [comment]
Update: Forgot I needed to `JSON.stringify` after lambda proxy integration . Works fine now! 👌

**Comment by AndrewZelaya** [comment]
> Update: Forgot I needed to `JSON.stringify` after lambda proxy integration . Works fine now! 👌

However, it doesn't seem possible to space out the output. Example JSON.stringify(object, null, 2) does not result in a human-readable output.

**Comment by julianpitt** [comment]
I've been able to get a pretty print output by combining tail and jq using the following command. This only works when you return a json object as a response from the function.

```
sam invoke local ApiStack searchFunction | tail -1 | jq
```

I can then use jq filters to view the information I need from the responses while developing locally.

**Comment by sriram-mv** [comment]
Closing this issue as piping the output to jq gives you the same results.
