### ISSUE TITLE
Sam invoke not able to find the build temple in built folder.

### ISSUE THREAD

**Issue by risingdivik** [aws/aws-sam-cli#3271]
### Description:

I am trying to Debug using vs code and aws toolkit .. when i click on debug it builds it successfully but when it calls sam invoke it tries to search it the built folder but not able to find there.

### Steps to reproduce:

Vscode Debug
Os Windows

### Observed result:

Attached screenshot
![Screenshot_20210914-033639](https://user-images.githubusercontent.com/90655434/133163182-dd6e1b6e-ed25-4b23-8a3d-a111856ea264.jpg)

### Expected result:

I should be able to debug.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

`Add --debug flag to command you are running`

**Comment by risingdivik** [comment]
I tried it running manually using console, so there i got error as unable to find template.

**Comment by aahung** [comment]
@risingdivik can you fill the missing information to help us better understand your issue?

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

Besides, can you run and see what it outputs?
```
sam build --debug
# or
sam build --use-container --debug

# then
sam local invoke --debug
```

**Comment by risingdivik** [comment]
SAM CLI, version 1.31.0
OS:Windows
AWS region: eu-central-1

**Comment by risingdivik** [comment]
I am getting this in info...
Built Template   : ..\..\Users\divi\AppData\Local\Temp\aws-toolkit-vscode\vsctkINCgrY\output\template.yaml

But no template is getting generated at this path..

This is the verbose info
SAM: command exited (code: null): PID 18212: [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd local invoke --debug deleteGroupFunction --template C:\Users\divi\AppData\Local\Temp\aws-toolkit-vscode\vsctkINCgrY\output\template.yaml --event C:\Users\divi\AppData\Local\Temp\aws-toolkit-vscode\vsctkINCgrY\event.json --env-vars C:\Users\divi\AppData\Local\Temp\aws-toolkit-vscode\vsctkINCgrY\env-vars.json -d 5858 --skip-pull-image]

**Comment by aahung** [comment]
It could be potentially the aws-toolkit-vscode somehow didn't invoke sam build properly.
I am moving this issue to https://github.com/aws/aws-toolkit-vscode

**Comment by aahung** [comment]
I wasn't be able to transfer the issue. Can you open one in https://github.com/aws/aws-toolkit-vscode? I am closing this one.
