### ISSUE TITLE
SAM CLI should save cfn outputs for later reference

### ISSUE THREAD

**Issue by richardhboyd** [aws/aws-sam-cli#3278]
### Describe your idea/feature/enhancement

When I deploy a SAM App and it has CFN outputs, it would be nice if SAM stored those values in something like the `samconfig.toml` file. I often find that when I come back to working on a project I'd like to be able to reference the APIGW endpoint without having to some kind of no-op (ish) deployment to force outputting the CFN outputs.

### Proposal

Add details of how to add this to the product.

I'm more of an "ideas person", I'll leave the implementation to you experts.

**Comment by hoffa** [comment]
Thanks for the feedback! I'll close this in favor of the existing https://github.com/aws/aws-sam-cli/issues/2813 which seems to cover the request.
