### ISSUE TITLE
SAM CLI breaks at /var/runtime/index.js every time I invoke my function

### ISSUE THREAD

**Issue by ikamal-pxl** [aws/aws-sam-cli#3284]
### Description:

I created the configurations to be able to invoke my lambda function directly using sam cli. The configuration copy is attached below (using code lens).

![Screen Shot 2021-09-16 at 2 05 15 PM](https://user-images.githubusercontent.com/85840632/133609523-eb556a41-09dd-4602-bfde-3d1a00af7e05.png)

When I click F5 or press the run button to debug my function it breaks every time in a file that is not in my project called index.js created in the runtime (/var/runtime/index.js) (I believe it's related to sam cli debugging feature).

This stall my development process as I expect it breaks directly at the break point I put in the code.

### Steps to reproduce:

1. Run sam init
2. Choose option 1 (1 - AWS Quick Start Templates)
3. Choose option 2 (2 - Image (artifact is an image uploaded to an ECR image repository)
4. Choose option 1 (1- amazon/nodejs14.x-base)
5. Go to app.js file then click on code lens option (add debug configuration
![Screen Shot 2021-09-16 at 2 15 55 PM](https://user-images.githubusercontent.com/85840632/133610636-35c4487a-bf49-40e8-820e-973a876fa0c8.png)
5. Go to run and debug in VS code then select the function configuration you just created and then click run button
![Screen Shot 2021-09-16 at 2 18 58 PM](https://user-images.githubusercontent.com/85840632/133611121-7cd2f81c-8a76-48a5-9117-7efe326219ab.png)

### Observed result:

It breaks at an breakpoint that does not exist
![Screen Shot 2021-09-16 at 2 02 16 PM](https://user-images.githubusercontent.com/85840632/133611205-c99af67c-1df4-4d6b-9fcd-abfa09ca1059.png)

### Expected result:

To break at the breakpoint that I put by myself in the code

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
1. OS: MacOs Big Sur version: 11.5.1
2. `sam --version`: SAM CLI, version 1.31.0
3. AWS region: US East

**Comment by pkhafizov** [comment]
Use "debugger" in your code instead breakpoint.
```
exports.handler = async (event, context) => {
  debugger
  console.log('event',event.body);
  return {
    statusCode: 200,
    body: JSON.stringify({
      event: event,
      context: context
    })
  }
};
```

**Comment by ikamal-pxl** [comment]
The same issue still arises. 
Debugging the sam application was one of the saddest days in my life. I finally created my own invokes, and like is much easier now.
Thank you for your reply.

**Comment by mndeveci** [comment]
Hi @ikamal-pxl, sorry for the experience. When I tested it, it stops in a different file first (`index.js`), and when I click `Continue(F5)` it stops at the debug point that I set in my code.

Can you confirm that continuing is also working for you? Meanwhile, we will be investigating further to fix the issue.

**Comment by jfuss** [comment]
@ikamal-pxl In your launch config you need to specify `"stopOnEntry": false`. https://github.com/aws/aws-sam-cli/pull/704 has some additional info on this.

**Comment by torresxb1** [comment]
Closing as there hasn't been more information provided. Please reopen if you still encounter the issue.

**Comment by ryancabanas** [comment]
I have this same issue and if I add `"stopOnEntry": false` it states that the property is not allowed for this configuration.
