### ISSUE TITLE
Caching of specific resource builds

### ISSUE THREAD

**Issue by osaund** [aws/aws-sam-cli#3291]
### Describe your idea/feature/enhancement

If you specify a specific resource within `sam` with cache enabled 

```shell
sam build MyHandler --cached
``` 

`sam` will not persist a `build.toml` which means it can not make use of cached builds on subsequent builds.

Tools like Pycharm always require you to select a specific resource and it always provides it to the `sam build` command and thus you cannot make use of cache.

### Proposal

Update sam to allow caching of specific resources

**Comment by CoshUS** [comment]
For reference, this is being solved in the beta accelerate branch: https://github.com/aws/aws-sam-cli/commit/87034c2368a3cdd0ef32399bcf51950b2bb3fbbb#diff-3ba570604bcbf654b23f5f7a9760adad8e989919639a3190ea31e7bef2cb42f3

**Comment by qingchm** [comment]
@osaund Have you tried out our latest SAMCLI versions? I think building with --beta-features flag on will give you a brand new caching experience! Let me know if that realizes what you want!

**Comment by super132** [comment]
[SAM Accelerate](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/accelerate.html) feature is now GA, which includes the cached build feature. I'm closing this issue now and please feel free to submit a new issue if you have found issues or problems regarding to the cached build. Thanks.
