### ISSUE TITLE
RequestContextV2 is missing some fields

### ISSUE THREAD

**Issue by vp89** [aws/aws-sam-cli#3304]
Missing values appear to be (this is a real event echo'd and compared with Wireshark captured local SAM submitted event:

`
{
  "stage": "$default",
  "time": "26/Sep/2021:02:59:48 +0000",
  "timeEpoch": 1632625188400,
  "domainName": "123ypbcjy1.execute-api.us-east-1.amazonaws.com",
  "domainPrefix": "123ypbcjy1"
}
`

`stage` always seems to arrive as null, the other 4 are missing when running locally.

This appears to break the Rust Lambda Runtime which is very strict, when trying to test locally using SAM:

https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-http/src/request.rs#L121-L145

**Comment by CoshUS** [comment]
Hey @vp89,
Can you provide more detailed information on this issue with the [issue template](https://github.com/aws/aws-sam-cli/issues/new?assignees=&labels=&template=Bug_report.md&title=)?
Is `RequestContextV2` from Lambda Power Tools? How is your project structured?

**Comment by vp89** [comment]
The code that produces this request context value is here:

https://github.com/aws/aws-sam-cli/blob/126bfeb4966ce6bf9fe86b8ceb587c35bd55acdc/samcli/local/events/api_event.py#L289-L337

**Comment by vp89** [comment]
@CoshUS have you had a chance to look at the PR? Currently this bug breaks SAM-CLI local testing of Rust Lambdas that use API Gateway V2 events.

**Comment by vp89** [comment]
@owen I was going to add that but erred on the side of only adding defaults in the code for things that can't be provided via template.yaml. I was able to work around the empty stage by specifying one in my template.yaml but I dont know if that is the "right" solution 🤷

**Comment by hawflau** [comment]
@vp89 Thanks for the PR! I've reviewed and thought we could just default to `"$default"` for the stage name if it is `None`, as this seems to match the behaviour of API Gateway.

**Comment by moelasmar** [comment]
The fix was released in sam version 1.34.
