### ISSUE TITLE
SAM Accelerate support for nested stacks

### ISSUE THREAD

**Issue by praneetap** [aws/aws-sam-cli#3305]
### Describe your idea/feature/enhancement
SAM CLI just launched [SAM Accelerate](https://github.com/aws/aws-sam-cli/issues/3264), and this issue is to track adding support for nested stacks with `sam sync --watch`

**Comment by revmischa** [comment]
This would be a godsend for our application! I want to use nested stacks in my SAM/CDK app and not have to wait for a full nested stack deployment every time I make a code change. This is especially important given [this comment](https://github.com/aws/aws-sam-cli/pull/2491#issuecomment-927440181): 
> Ultimately, we feel that testing against a real environment in the cloud is the best way to ensure that the results are accurate and include all pieces of the equation

**Comment by kjones** [comment]
I'm also a heavy user of nested stacks and AppSync. Big +1 for this.

**Comment by kjones** [comment]
Tried out sam sync/watch yesterday just to see what would happen. Errors all over the place. I'm probably using every currently unsupported  use case right now. 
- 20 nested stacks
- AppSync
- Cognito
- .NET Lambda Functions x 20
- Custom resource in Python
- DynamoDB & Streams
- HttpApi x 3
- SQS
- EventBridge
- CloudWatch Alarms
- QLDB
- Route53 HostedZone, RecordSet
- ACM SSL Certificate
- CloudFront
- S3

I guess I could break this into multiple stacks along the lines of resources that tend to be static vs. all the Lambda Function related resources. But hey, one `sam deploy` and a developer has a completely new backend in < 10 mins. If anyone at AWS is interested in working directly with me please feel free contact me. Email should be available on my GitHub profile.

**Comment by ConnorKirk** [comment]
In the mean time, would it be possible to add a warning to the command if it detects `sam sync` is being used with nested stacks? I naively tried to use it without reading the caveats. A warning might save future people from the same fate.

**Comment by praneetap** [comment]
This is a feature we are currently working on, please keep an eye out for updates!

**Comment by praneetap** [comment]
@revmischa @ConnorKirk @kjones We have launched support for nested stacks in the last release, it's still not feature complete as we are verifying all the edge cases. Please feel free to try it out and let us know how it works for you. Thanks for the feedback as always!

**Comment by praneetap** [comment]
This is now complete and generally available. Closing this issue, thank you!
