### ISSUE TITLE
Error when using Sam pipeline init

### ISSUE THREAD

**Issue by RobinVds** [aws/aws-sam-cli#3310]
### Description:
When I follow the `sam pipeline init --bootstsrap` setup the resulting yaml files are not working properly. I've tried both github actions as CodePipeline.

For github actions the error I receive is in the deploy-testing step when we try to deploy to the testing account:
```
	SAM CLI now collects telemetry to better understand customer needs.

	You can OPT OUT and disable telemetry collection by setting the
	environment variable SAM_CLI_TELEMETRY=0 in your shell.
	Thanks for your help!

	Learn More: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html

Usage: sam deploy [OPTIONS]
Try 'sam deploy -h' for help.

Error: Only one of the following can be provided: '--image-repositories', '--image-repository', or '--resolve-image-repos'. Do you have multiple specified in the command or in a configuration file?
Error: Process completed with exit code 2.
```

For CodeBuild I get an error when trying to deploy the pipeline to aws, when I run `sam deploy -t codepipeline.yaml --stack-name <stack-name> --capabilities=CAPABILITY_IAM`

I get the following error:
```
Usage: sam deploy [OPTIONS]
Try 'sam deploy -h' for help.

Error: Incomplete list of function logical ids specified for '--image-repositories'. You can also add --resolve-image-repos to automatically create missing repositories.
```

### Steps to reproduce:

1. `sam init --bootstrap` (with image)
2. Trigger resulting actions or deploy resulting pipeline

### Observed result:

Result is identical to errors showed above.

### Expected result:

I could adjust the commands but I would expect these to work properly without me needing to adjust things. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`:SAM CLI, version 1.31.0
3. AWS region: eu-central-1

`Add --debug flag to command you are running`

**Comment by tjmcewan** [comment]
Can't speak for @RobinVds, but I observed the `Only one of the following...` issue after setting up a multi-account gitlab-ci pipeline in an app that had a `samconfig.toml` file with an `image_repositories` key.

The solution in my case was to delete the `samconfig.toml` as the repository config was now specified in the `.gitlab-ci.yml` as `TESTING_IMAGE_REPOSITORY` and `PROD_IMAGE_REPOSITORY`.

HTH.

**Comment by toddmackenzie78** [comment]
I confirm. For subsequent deployment, both commands do not work unless you delete the x.toml file generated from the initial deployment. After this, the second command works. Use the same sam app name as your initial deployment (x-sam-app). The third, fourth, or fifth subsequent deployments allow the first command to work.  

`sam deploy`
`sam deploy --guided`
