### ISSUE TITLE
Support equivalent of --no-execute-changeset via samconfig

### ISSUE THREAD

**Issue by mokele** [aws/aws-sam-cli#3313]
### Describe your idea/feature/enhancement

There is no way to _not_ execute a changeset while also _not_ confirming the changeset interactively without requiring cli options (i.e. no possible via `samconfig.toml`).

Via CD tooling where a changeset needs to be approved non-interactively and as a separate process to changeset creation it is not currently possible to do this via `samconfig.toml`.

**Workaround:** use cli option `--no-execute-changeset` – however some developers would prefer to keep all related config for this in sam configuration files rather than spread between both sam configuration and cli options.

### Proposal

Add `execute_changeset = true | false` (default `true` to maintain existing behaviour and align with default cli behaviour where the negative flag `--no-execute-changeset` has to be added for the `false` case to take affect)

Things to consider:
* don't think this has any considerations, as it would be backwards compatible with existing behaviour where it is omitted, and aligns the cli tool options of `--(no-)confirm-changeset` and `--(no-)execute-changeset` with that of sam config

### Additional Details

no additional details

**Comment by hawflau** [comment]
Hey @mokele Thanks for suggestion! We will look into adding this support.

**Comment by sriram-mv** [comment]
You can do this today. The configuration file is just straight mapping to cli parameters themselves.

just add the following to your samconfig.toml

Just want to view the changeset.
```
[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
no_execute_changeset = true
```
