### ISSUE TITLE
[1.33.0] Build gets stuck when using Architectures: ["arm64"]

### ISSUE THREAD

**Issue by imduchy** [aws/aws-sam-cli#3331]
### Description:

We've upgraded to aws-sam-cli 1.33.0 in order to take advantage of the new Graviton process when using Lambda functions. After setting `Architectures: ["arm64"]` in `AWS::Serverless::Lambda`, the sam build command gets stuck and won't finish.

```
2021-10-01 11:31:17,329 | Building codeuri: /home/org.com/user/source/our-project/a-service runtime: python3.9 metadata: {} architecture: arm64 functions: ['LogicalIdOfFunction']
2021-10-01 11:31:17,329 | Waiting for async results
2021-10-01 11:31:17,329 | Building to following folder /home/org.com/user/aws-sam-generated-artifacts/ireland/a-service/LogicalIdOfFunction

Fetching public.ecr.aws/sam/build-python3.9:latest-arm64 Docker container image......
2021-10-01 11:31:18,717 | Mounting /home/org.com/user/source/our-project/a-service as /tmp/samcli/source:ro,delegated inside runtime container
```

These are the last lines of output. After that, no more logs are generated and `sam build` gets stuck.

### Steps to reproduce:

1. Upgrade to `aws-sam-cli: 1.33.0`
2. Define a `AWS::Serverless::Function` with `Architectures: ["arm64"]`
3. Run `sam build --use-container --parallel ...`

### Observed result:

sam build gets stuck (see the log output above)

### Expected result:

sam build executes as expected

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 18.04.5 LTS
2. `sam --version`: 1.33.0
3. AWS region: ireland

`Add --debug flag to command you are running`

**Comment by c2tarun** [comment]
Hi @Duchynko,

Thanks for reporting this issue. I am able to reproduce this issue on Ubuntu 18.04 instance with following template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - arm64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
```

I'll update with more details as I find them.

**Comment by piersf** [comment]
@c2tarun the same behavior is seen also on `Red Hat Enterprise Linux release 8.4 (Ootpa)`

**Comment by c2tarun** [comment]
@Duchynko and @piersf,
In order for multiarchitecture to work with docker we have to enable a setting. I enabled this by running `docker run --rm --privileged multiarch/qemu-user-static --reset -p yes` and now I am able to build `arm_64` lambdas locally. Can you please try it?

**Comment by piersf** [comment]
Will try this soon. Question: do we have to do this every time before running a build with SAM CLI, or how would that work?

**Comment by Duchynko** [comment]
@c2tarun that has worked, thanks a lot! 👍🏼 

It might be a good idea to have this documented (perhaps in your README).

**Comment by c2tarun** [comment]
> Will try this soon. Question: do we have to do this every time before running a build with SAM CLI, or how would that work?

We are working on updating our documentation with more clarity. However I had to do it only once on my machine, so I am assuming you have to do it once per docker install.

> It might be a good idea to have this documented (perhaps in your README).

Glad to know it worked, we are working on updating our documentation.

Thanks

**Comment by movaid7** [comment]
> @Duchynko and @piersf, In order for multiarchitecture to work with docker we have to enable a setting. I enabled this by running `docker run --rm --privileged multiarch/qemu-user-static --reset -p yes` and now I am able to build `arm_64` lambdas locally. Can you please try it?

@c2tarun Sorry for the silly question but how would I configure docker when using `sam build --use-container` as part of a GitHub Actions workflow?
![image](https://user-images.githubusercontent.com/12106703/136005628-8b3acb0a-3f31-4c01-b7c6-b65300b456a3.png)

**Comment by mgrandis** [comment]
We had updated our doc but only on this page:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html

We will be looking at making it more visible.
Thanks!

**Comment by mgrandis** [comment]
@movaid7 
Have you tried adding a step before the sam build one?
Like so:
```
# docker setup
- name: Setup Docker for cross architecture build
  run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
```

**Comment by movaid7** [comment]
@mgrandis 
Just gave that a shot but it still seems to be getting stuck on the `sam build` step.

![image](https://user-images.githubusercontent.com/12106703/136027373-b00b71c1-f45b-4561-9699-a3a84dd608cc.png)

**Comment by piersf** [comment]
@movaid7 thank you for your reply and for providing a solution!

Without knowing how the internals of SAM are set up in order to work with ARM architecture, I have to say that it is unfortunate to see that we need to run a privileged container. Some users might not have permission to run such containers .  I'd expect SAM not to require such privileges.

I assume that AWS maintains this image since it is mentioned in the SAM's public documentation but I can see that the image comes from a GitHub repository https://github.com/multiarch/qemu-user-static?

Can you provide a bit more information about what does the container from this image do?

Thank you,

**Comment by qingchm** [comment]
@movaid7 Hey for your question we do have very different images tagged with latest (or latest-x86_64) and latest-arm64 to support different architectures. So when you see this message it is pulling the right image that is set up for arm64. Can you specify more information on your execution, maybe the docker version? If you are still seeing this problem we will try to help you with that but so far I couldn't exactly understand the root cause of your issue and could not yet reproduce it!

**Comment by engrun** [comment]
Stumbled upon this today. Unable to build with from Github Actions with  architecture set to arm64. 

Reverting back to x86_64 fixes the problem. 
However, it would be nice to be able to build SAM applications with arm64 from github

**Comment by txjmb** [comment]
Getting this issue on SAM CLI in 2022.  Version 1.46.0.  Simply hangs at the `Mounting /path/to/function as /tmp/samcli/source:ro,delegated inside runtime container` step.

**Comment by txjmb** [comment]
Output from sam build --use-container --debug:

`Fetching public.ecr.aws/sam/build-python3.9:latest-arm64 Docker container image......
2022-04-22 15:45:02,303 | Mounting /path/to/function as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'`

Gets here and hangs indefinitely...

**Comment by txjmb** [comment]
For those experiencing this..  It may simply be that building in the container is atrociously slow due to QEMU emulation being required.  To confirm and monitor progress:  `sam build --use-container --debug` will help troubleshoot if it is truly hanging or simply taking a long time to compile dependencies on emulated ARM.

**Comment by txjmb** [comment]
Since this appears to be due to extremely slow compilation in emulation, what would be great is if AWS would integrate CodeBuild into the sam build pipeline so that build/compilation could be done on native ARM64 machine in AWS infrastructure.

**Comment by txjmb** [comment]
I can confirm that this does simply lock up sometimes.  I have a fairly simple Python 3.9 Lambda that uses only the following libraries in requirements.txt:

`smart_open
sqlalchemy
pandas
pangres
anyio
aiohttp
asyncpg
uvloop
boto3`

When run with `sam build --use-container --debug` it never finishes.  Even after days.

**Comment by imduchy** [comment]
@sriram-mv I see you closed the issue as "completed". Could you please provide more information about how was the issue solved? Thank you!

**Comment by aleguern** [comment]
Has anyone worked this out ?

**Comment by luis30n** [comment]
> For those experiencing this.. It may simply be that building in the container is atrociously slow due to QEMU emulation being required. To confirm and monitor progress: `sam build --use-container --debug` will help troubleshoot if it is truly hanging or simply taking a long time to compile dependencies on emulated ARM.

Hi! Thanks for the information. How slow may this be?

**Comment by jeremiahlukus** [comment]
I am unable to build arm64 in GHA does using the latest sam cli version. `SAM CLI, version 1.117.0` 

I have `docker run --rm --privileged multiarch/qemu-user-static --reset -p yes` right before my build but it still errors

**Comment by vuvandinh2000** [comment]
@mgrandis 
Using arm64 with your solution in Github Actions takes me longer time (>2 mins) to complete rather than using x86_64 (50s). Do you have any solution to speed up?
```yml
- name: Setup Docker for cross architecture build
  run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
- name: Build SAM Application
  run: sam build --use-container --template ${SAM_TEMPLATE}
```

**Comment by luis30n** [comment]
> @mgrandis Using arm64 with your solution in Github Actions takes me longer time (>2 mins) to complete rather than using x86_64 (50s). Do you have any solution to speed up?
> 
> ```yaml
> - name: Setup Docker for cross architecture build
>   run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
> - name: Build SAM Application
>   run: sam build --use-container --template ${SAM_TEMPLATE}
> ```

I don't think there's a solution for that. Maybe you could improve efficiency by caching part of the build or using a GH self hosted runner with arm arch as well so that you don't need QEMU

**Comment by vuvandinh2000** [comment]
@luis30n I removed `--use-container` that significantly sped up the building step (from 2 mins down to 20s). Does it have any risk? (As I know, GH will build my SAM App in their x86_64 machine)
```yml
- name: Build SAM Application
  run: sam build --template ${SAM_TEMPLATE}
```

**Comment by luis30n** [comment]
@vuvandinh2000 I'm only talking from experience having dealt with the same issues, not trust me too much :) 
not sure on the implications of not using --use-container. Have you tested the result? According to sam docs:

> -use-container, -u
If your functions depend on packages that have natively compiled dependencies, use this option to build your function inside a Lambda-like Docker container.

so if it still works I guess it's alright...but I doubt it would

**Comment by vuvandinh2000** [comment]
@luis30n I think we can still use without `--use-container` when and only when all dependencies on our function app will compile to the same output in both x86_64 & arm64.
For example in Python, lib like `pytorch`, `numpy` were partially written by C/C++ that depends on target architecture to build while lib like `requests`, `pydantic` were written by pure Python so should be compiled to the same output in both.

**Comment by vuvandinh2000** [comment]
Maybe GH didn't have any arm arch runners, so I will use cache. Thank you so much.

**Comment by luis30n** [comment]
> Maybe GH didn't have any arm arch runners, so I will use cache. Thank you so much @luis30n

Let me know how that caching goes! I have not implemented myself in my use case because the job does not run that often to take care of this efficiency improvement in the CI.
GH does not provide ARM github-hosted runners but you _could_ (with all the trouble it takes) host your own infra where the CI runs and use self-hosted runners in ARM...

**Comment by jeremiahlukus** [comment]
At the point it’s better to have GHA trigger a code build.
