### ISSUE TITLE
Cannot build from source under Ubuntu 20.04

### ISSUE THREAD

**Issue by cpilson** [aws/aws-sam-cli#3334]
### Description:

I'm following instructions in `./installer/pyinstaller/Instruction.md`

I do have to `chmod +x ./installer/pyinstaller/build-linux.sh`

When I build inside the CentOS 7 image, per the instructions, I see that `libpython3.7-dev` is not provided. I've installed this on my host machine, and also installed this inside the CentOS docker image, no luck `yum install libpython3.7-dev.x86_64`.

### Steps to reproduce:

```shell
docker run --mount type=bind,src="{Absolute path to AWS SAM CLI source}",dst="/aws-sam-cli" -it quay.io/pypa/manylinux2014_x86_64
cd aws-sam-cli
chmod +x ./installer/pyinstaller/build-linux.sh
./installer/pyinstaller/build-linux.sh aws-sam-cli-linux-x86_64.zip
```

### Observed result:

Initially, an error saying that `libpython3.7` couldn't be found.

After running `yum install libpython3.7-dev.x86_64` in the container, I see `ERROR: No matching distribution found for pyrsistent==0.17.3`

### Expected result:

Looks like a ZIP file should come out of this?

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: docker container for CentOS 7, per build instructions.
2. `sam --version`: N/A
3. AWS region: N/A

`Add --debug flag to command you are running`

**Comment by mndeveci** [comment]
Thanks for raising this issue @cpilson. Current process stuck in couple of places as you mentioned. I tested this PR: https://github.com/aws/aws-sam-cli/pull/3355 and I was able to build zip file successfully under `/aws-sam-cli/.build/output` inside the container, and in `./aws-sam-cli/.build/output` in my local folder.

Once that is merged you should be able to build the executable.
