### ISSUE TITLE
sam-local inside CodeBuild Docker container

### ISSUE THREAD

**Issue by neo-headz** [aws/aws-sam-cli#334]
I have a fairly simple use-case. I want to run aws-sam-local as part of ci/cd. I use aws codebuild for building my backend. I would like run sam-local in the background as part of a post build process. Therefore, I can run integration tests against the local server and possibly fail the build before deploying.

 I don't have any issue running the NPM installed sam-local CLI in the foreground simply with:
 `sam local start-api --env-vars ./src/config/env/test.json`

But when I try to use something like nohup per https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-background-tasks.html with the CLI, I get `Connection refused` 

I also don't have any issues running the https://github.com/cnadiminti/docker-aws-sam-local container in the foreground with the privileged flag set in my CodeBuild container.  However, if I use the `-d` parameter of Docker I get `Connection reset by peer`
Buildspec.yaml example: 
```
 - docker run -d -t
    -v /var/run/docker.sock:/var/run/docker.sock
    -v $(pwd):/var/opt
    -p 3000:3000
    cnadiminti/aws-sam-local
    local start-api --env-vars ./config/env/local.json --docker-volume-basedir $(pwd) --host 0.0.0.0
```

Maybe I'm thinking about this the wrong way but it seems like running aws-sam-local in a container within my CodeBuild process and hitting the local server with my integration test suite would be suitable. I'm aware of the drawbacks of using Docker in Docker.

**Comment by michaelj-smith** [comment]
I've had trouble even getting started with sam local inside CodeBuild. Do you use the NodeJS CodeBuild image, or a custom image with SAM already installed?

**Comment by headz68** [comment]
@michaelj-smith I'm using the AWS image`aws/codebuild/nodejs:6.3.1` with the privileged flag checked.

**Comment by piotrkubisa** [comment]
Not so long ago I created [localci](https://github.com/piotrkubisa/localci) to run CodeBuild locally using official [AWS Docker images](https://github.com/aws/aws-codebuild-docker-images) to help me inspect some problems during AWS CodeBuild runtime. You may try it or just run CodeBuild's Docker images locally and try out to resolve your issue - they are well-documented and easy to play with.

Personally, after 4 months of using `sam-local` I cannot recommend it to rely on it during some functional/postman tests in `start-api` mode. I'd rather go with mocking event payload (from API Gateway) and invidually call all methods which requires such functional testing. In my humble opinnion, there is still a lot of differences if you do a `curl` request to real deployment on API Gateway with AWS Lambda and `aws-sam-local` which mimics them.

**Comment by Dlozitskiy** [comment]
@headz68, I started looking into the same usage pattern and wondering what if you chain two CodeBuild actions in the pipeline, one is the actual code build using aws/codebuild/nodejs:6.3.1 container and the other one is code test using docker-aws-sam-local container. If latter stage passes you'll have your artefacts from the first stage ready to be deployed by CodeDeploy?

**Comment by jfuss** [comment]
Closing. Docker in Docker is not something we currently support. Please run same outside of docker to use sam local or sam build --use-container.
