### ISSUE TITLE
Deep integration with development tools: Visual Studio Code

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sam-cli#3351]
![image](https://user-images.githubusercontent.com/765871/136747952-311e5ab4-40ba-4942-8bce-7e4ce80dc95d.png)

### Description:

VS code suggesting AWS Batch documentation

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Archlinux

**Comment by jfuss** [comment]
Closing given no response to follow up quesitons
