### ISSUE TITLE
--no-progressbar option does not suppress ECR image upload progress

### ISSUE THREAD

**Issue by brokenthumbs** [aws/aws-sam-cli#3358]
### Description:

When using `sam deploy --image-repository [ecr_uri]` and the `--no-progressbar` option, the progress bar shows when uploading images to ECR.

### Steps to reproduce:

Use `sam deploy` CLI, providing `--image-repository` or `--resolve-image-repos` with `--no-progressbar` and view output which shows progress for uploading image to ECR.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`: SAM CLI, version 1.30.0
3. AWS region: 

`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
The PR is released in SAM CLI V 1.37.0
