### ISSUE TITLE
Apache Kafka event source for local development

### ISSUE THREAD

**Issue by bep0st** [aws/aws-sam-cli#3380]
### Describe your idea/feature/enhancement

I wish SAM CLI would add a new kafka event source to trigger a lambda function locally. The idea is to set a breakpoint in the FunctionHandler() which should be hit if I create a new message in kafka which runs in a local docker container on windows. Also it would be great if you would extend the payload generator at https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-generate-event.html

### Proposal

Add a new event source type to the existing once described at https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventsource.html

### Additional Details
There is already the event source type "MSK" described at https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-msk.html which only seems to work with AWS and not within a local environment

**Comment by CoshUS** [comment]
Thanks for the feature request! We have a [roadmap](https://github.com/aws/aws-sam-cli/wiki/SAM-CLI-Roadmap) here, but we also try to take in popular feature requests based on 👍🏽 from the community. We will be adding this to our intake for prioritization.

**Comment by bep0st** [comment]
Hello everyone
It seems that my requested feature has been implemented (see https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-selfmanagedkafka.html)

Thanks for your support.

Cheers
bep0st

**Comment by jfuss** [comment]
Given last comment, this was solved (and added to SAM Spec).

Closing

**Comment by mostrovoi** [comment]
Still missing the payload generator for MSK :)
