### ISSUE TITLE
Sam build --use-container vs without LAMBDA_TASK_ROOT env variable.

### ISSUE THREAD

**Issue by pankajagrawal16** [aws/aws-sam-cli#3407]
### Description:

Referring to the issue https://github.com/aws-samples/cookiecutter-aws-sam-powertools-java/issues/252. It looks like when using `sam build` command without `--use-container`, `LAMBDA_TASK_ROOT` env is not set. 

While when we use `sam build --use-container` env var `LAMBDA_TASK_ROOT` is set to `/var/task`. This inconsistent behavior makes some of the specifics of AWS Xray sdk works differently when building with or without container option. 

Why does sam build has different behavior ?

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:  SAM CLI, version 1.29.0
3. AWS region: all

`Add --debug flag to command you are running`

**Comment by CoshUS** [comment]
`--use-container` uses Lambda emulation images to build functions. These images emulate Lambda execution environment which contains its related env vars.  https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html

**Comment by pankajagrawal16** [comment]
Which makes sense, but can't sam build command also set same environment variables to have consistent behaviour?

**Comment by CoshUS** [comment]
My concern is that this will break existing use cases where the build process should have exactly the same env vars as the host. It also blurs the difference between with and without `--use-container`, one should be exactly the same as Lambda execution environment while the other is managed by the user.

**Comment by jfuss** [comment]
You can use `--build-image` as a way to define a better environment for your use case. 

Closing
