### ISSUE TITLE
installer doesn't work

### ISSUE THREAD

**Issue by zhan9san** [aws/aws-sam-cli#3416]
### Description:

 
Following instructions in `./installer/pyinstaller/Instruction.md`
But the script exited with error when I run
`sh ./installer/pyinstaller/build-linux.sh aws-sam-cli-linux-x86_64.zip`

This issue was firstly found in #3334, and fixed in #3355 .
Recently, I found the change was reverted in #3393.

I tried to verify this issue with latest quay.io/pypa/manylinux2014_x86_64 image, but test failed again.

Did I do something wrong?
Could you please kindly share some more details on #3393 ?

### Steps to reproduce:

```
docker run --mount type=bind,src="{Absolute path to AWS SAM CLI source}",dst="/aws-sam-cli" -it quay.io/pypa/manylinux2014_x86_64
cd aws-sam-cli
sh ./installer/pyinstaller/build-linux.sh aws-sam-cli-linux-x86_64.zip
```

### Observed result:

```log
...IGNORE BEFORE...
Looking in links: /tmp/tmp5n_tela6
Processing /tmp/tmp5n_tela6/setuptools-47.1.0-py3-none-any.whl
Processing /tmp/tmp5n_tela6/pip-20.1.1-py2.py3-none-any.whl
Installing collected packages: setuptools, pip
Successfully installed pip-20.1.1 setuptools-47.1.0
+ cd ..
+ echo 'Installing Python Libraries'
Installing Python Libraries
+ python3 -m venv venv
python3: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

### Expected result:

Exit without error

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 18.04.6 LTS
2. `sam --version`: N/A
3. AWS region: N/A
4. Build Image: quay.io/pypa/manylinux2014_x86_64:latest
  ```
  [
      {
          "Id": "sha256:e47d9a8749735cb48915c109fd4c8b98e740de6e20c76346b728d41c7e58c2c5",
          "RepoTags": [
              "quay.io/pypa/manylinux2014_x86_64:latest"
          ],
          "RepoDigests": [
              "quay.io/pypa/manylinux2014_x86_64@sha256:012a15a28de1377c716577f109cbc40ffa3477498e2fdb0409e3b69b852b705e"
          ],
          "Parent": "",
          "Comment": "buildkit.dockerfile.v0",
          "Created": "2021-10-26T15:54:08.731072347Z",
  ```

`Add --debug flag to command you are running`

**Comment by CoshUS** [comment]
https://github.com/aws/aws-sam-cli/pull/3420 Merged.
