### ISSUE TITLE
(SAM Pipelines) | "Error: Template file not found" during build-and-package for Github Actions

### ISSUE THREAD

**Issue by johnbiiibs** [aws/aws-sam-cli#3422]
### Description:
Getting an `Error: Template file not found at /home/runner/work/sam-pipeline-test/sam-pipeline-test/template.yaml` when setting up **sam pipelines** for Github Actions during the **build-and-package** phase.

Tried the following solution as described in issue: https://github.com/aws/aws-sam-cli/issues/3138 ; but the issue still persists.

### Steps to reproduce:
- https://aws.amazon.com/blogs/compute/introducing-aws-sam-pipelines-automatically-generate-deployment-pipelines-for-serverless-applications/
- https://www.antstack.io/blog/sam-pipeline-github-actions/

### Observed result:
`Starting Build inside a container`
`Error: Template file not found at /home/runner/work/sam-pipeline-test/sam-pipeline-test/template.yaml`
`Error: Process completed with exit code 1.`

![image](https://user-images.githubusercontent.com/1129876/139441617-eb93551d-a84a-49c2-8ec6-3c56a1251b1a.png)

https://github.com/johnbiiibs/sam-pipeline-test/runs/4046581246

### Expected result:
Successful build

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 11.5.2
2. `sam --version`: SAM CLI, version 1.34.1
3. AWS region: ap-southeast-1

**Comment by CoshUS** [comment]
Hey @johnbiiibs,
How was `template.yml` generated? Is it from `sam init` or was it created manually?

**Comment by johnbiiibs** [comment]
Hi @CoshUS!

Generated it using `sam init`. However, when I try it now, it generates `template.yaml` properly.

Seems like it was already fixed yesterday with this PR:
https://github.com/aws/aws-sam-cli-app-templates/pull/147

I think I can close this one as it seems like it was an issue with the `aws-sam-cli-app-templates` repo.

Thank you!
