### ISSUE TITLE
[sam-beta-cdk] sam build with the use of CDK_DEFAULT_REGION env variable always sets a value

### ISSUE THREAD

**Issue by rupe120** [aws/aws-sam-cli#3428]
### Description:
When using the pattern `env=core.Environment(account=os.getenv('CDK_DEFAULT_ACCOUNT'), region=os.getenv('CDK_DEFAULT_REGION'))` to initialize stack instances with an empty default config profile,  `sam-beta-cdk build` defaults the region to `us-east-1` instead of `unknown-region`

This compounds problems of the `sam-beta-cdk build` ignoring the `--profile` switch: https://github.com/aws/aws-sam-cli/issues/3427

### Steps to reproduce:
1. `sam-beta-cdk init --project-type cdk`
2. Ensure that the the default profile in the config has no region
3. Uncomment the `env=core.Environment(account=os.getenv('CDK_DEFAULT_ACCOUNT'), region=os.getenv('CDK_DEFAULT_REGION'))` in `app.py`
4. `sam-beta-cdk build`

### Observed result:
The `environment` property for the resource in the `manifest.json` file has the  value `aws://unknown-account/us-east-1`

### Expected result:
The `environment` property for the resource in the `manifest.json` file should have the  value `aws://unknown-account/unknown-region`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10.0.19042 Build 19042
2. sam --version: SAM CLI, version 1.29.0.dev202108311500
3. AWS region: us-west-2

`Add --debug flag to command you are running`

**Comment by CoshUS** [comment]
So sorry you encountered a bug! Thanks for reporting the issue, we will be investigating it further.

**Comment by moelasmar** [comment]
Thanks for raising this issue. 
	
`sam-beta-cdk` actually do not send any profile related parameters or setting environment variables before calling `cdk synth`, I need to investigate more to know why `us-east-1` was used as a default region here. Can I ask you to try `cdk synth` on this project, and let us know if it will generate the same environment property in manifest.json or not.

Also, as a work around, you can run `cdk synth` first with whatever parameters you want, then you can run `sam-beta-cdk build --cdk-app <path to the directory that contains the output cloud asembly like ./cdk.out>` ... this should help you to fix this issue.

**Comment by rupe120** [comment]
> Thanks for raising this issue.
> 
> `sam-beta-cdk` actually do not send any profile related parameters or setting environment variables before calling `cdk synth`, I need to investigate more to know why `us-east-1` was used as a default region here. Can I ask you to try `cdk synth` on this project, and let us know if it will generate the same environment property in manifest.json or not.
> 
> Also, as a work around, you can run `cdk synth` first with whatever parameters you want, then you can run `sam-beta-cdk build --cdk-app <path to the directory that contains the output cloud asembly like ./cdk.out>` ... this should help you to fix this issue.

I tried the --cdk-app switch for sam-beta-cdk build and for some reason it made the build command take almost take almost an hour, while my work around runs in just over 3 minutes. There seems to be a bug with that switch.

**Comment by ssenchenko** [comment]
If you think there is a bug with `--cdk-app` switch, can you please submit a new issue according to the template so we can reproduce it?

Closing this issue.

**Comment by rupe120** [comment]
The inconsistency of the region setting is still a separate issue. Why close this bug?
