### ISSUE TITLE
[Security] AWS SAM CLI for Linux x86_64 is flagged as malicious

### ISSUE THREAD

**Issue by kevinadhiguna** [aws/aws-sam-cli#3430]
### Description:

Hi, I tried to install the AWS SAM CLI on Linux x86_64 but somehow it is considered malicious by a number of security vendors in [virustotal](https://virustotal.com).

### Steps to reproduce:

1. Go to [Installing the AWS SAM CLI on Linux](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html).

2. In the **Step 4: Install the AWS SAM CLI**, choose **x86_64**.

3. Download the ZIP file by clicking red-lined one below :
![image](https://user-images.githubusercontent.com/43397636/139563403-dad30d94-4738-4661-b489-727aa87bc4b4.png)

4. Go to [virustotal](https://virustotal.com), upload the ZIP file, and scan it.

5. See the scan result that indicates the ZIP file is (potentially) malicious.
![aws-sam-cli-flagged-malicious](https://user-images.githubusercontent.com/43397636/139563431-5037d915-ca9e-4012-9ef6-3b15b7375ed3.png)

### Observed result:

The AWS SAM CLI ZIP file was [flagged as malicious by a number of scanners in virustotal](https://https://www.virustotal.com/gui/file/51f8e072922021a488edfd362f53c2d2c5940017375da52371f50acc2a9247dd?nocache=1).

If the link is broken, it would be nice if you scan it again by yourself (nevertheless, the scan result is shown above). I did no modification to the AWS SAM CLI ZIP file at all as I immediately scanned the ZIP file after downloading it.

### Expected result:

Not flagged as malicious as I downloaded from [GitHub - AWS SAM CLI release](https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip) since I was asked to do so in [Install the AWS SAM CLI on Linux](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html).

Also, I would appreciate if you tell me why it happened (was considered malicious).

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: AWS SAM CLI for Linux x86_64

**Comment by CoshUS** [comment]
Related issue: https://github.com/aws/aws-sam-cli/issues/2937

**Comment by jfuss** [comment]
This has been addressed. Closing.
