### ISSUE TITLE
Please allow SAM to support the AWS Credentials Profiles from the AWS CLI

### ISSUE THREAD

**Issue by barkermn01** [aws/aws-sam-cli#3433]
### Describe your idea/feature/enhancement
I would like it if SAM could accept an argument to tell it what AWS CLI profile/credentials to use instead of having to use an extension in VS code that allows me to change default based on other profiles.

### Proposal

Would like it if SAM could work like the AWS CLI to accept a profile

```
sam deploy --profile=Profile1
```

Things to consider:
1. Will require documentation that it is able to do this

### Additional Details
The reason I ask for this is I have just tried to deploy work to another AWS account from the one I had originally been working in for a client, to another client and see that I have to have an extension or script to copy the profile I want to use into the default profile for it to work with sam is not just annoying it's also a problem as someone could quite easily accidentally publish a whole Cloud Formation for one to someone else's AWS account, purely because they forgot to switch the default profile over

**Comment by CoshUS** [comment]
Hey @barkermn01,
SAM commands do support `--profile` option. https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html

**Comment by barkermn01** [comment]
Hrm, strange it did not work for me yesterday when I posted this I added `--profile=Company2ProfileName` and I still got an ECR permissions error because it was publishing to Company2's ECR using Credentials of Company 1, however, I did get a noticing saying to update and ran the installer after I finished working and this does appear to be working again, 

P.S the documentation for SAM is appalling so thanks for linking it :D

Would also be good if the profileName could be asked for and supplied in the config.toml file so as a company we can just write a script that add the profile to there AWS CLI and then the toml coming from our Repo will just tell it to use that profile and if it's not there error about trying to use a missing profile (which I assume will already be in there)

But as a side note, why are TOML and YAML files being mixed in the same python application purely to waste resources?

**Comment by CoshUS** [comment]
You can specify --profile in the samconfig.toml file.
```
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
profile = "abc"
```

**Comment by CoshUS** [comment]
TOML is the preferred format for configurations as it offers simpler syntax for human editing.

**Comment by ericbn** [comment]
To define a global profile for all commands:
```toml
version = 0.1

[default.global.parameters]
profile = "my-profile"
```
