### ISSUE TITLE
SQS VisibilityTimeout property not set in created queue

### ISSUE THREAD

**Issue by cap10morgan** [aws/aws-sam-cli#3435]
### Description:
When you are creating an SQS queue in your SAM template, its VisibilityTimeout property needs to be set to something longer than your Lambda function timeout or there will be an error on deploy.

However, setting the VisibilityTimeout in the SAM template does not affect the created queue (which still gets the default 30s timeout).

### Steps to reproduce:
Put this resource in a SAM template:

```yaml
MyQueue:
  Type: AWS::SQS::Queue
  Properties:
    VisibilityTimeout: 360
```

Run `sam deploy`

### Observed result:
Created queue has a 30s visibility timeout and (assuming you set a longer timeout on a lambda function sourcing events from this queue) you'll get the following error:

```
CREATE_FAILED                      AWS::Lambda::EventSourceMapping    MyEventSourceMapping   Resource handler returned
                                                                      SQS                                message: "Invalid request
                                                                                                         provided: Queue visibility
                                                                                                         timeout: 30 seconds is less than
                                                                                                         Function timeout: 60 seconds
                                                                                                         (Service: Lambda, Status Code:
                                                                                                         400, Request ID: f69a8f70-d893-4
                                                                                                         3c8-bfc2-c2f9dc53c93b, Extended
                                                                                                         Request ID: null)"
                                                                                                         (RequestToken: dea85029-c702-a1e
                                                                                                         8-747f-ac914149439b,
                                                                                                         HandlerErrorCode:
                                                                                                         InvalidRequest)
```

### Expected result:
Created queue's visibility timeout is 360s and `sam deploy` succeeds.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 12.0.1
2. `sam --version`: `SAM CLI, version 1.34.1`
3. AWS region: us-west-2

**Comment by CoshUS** [comment]
Seems like the template is not updated when you use deploy. Did you run `sam build` before `sam deploy`?

**Comment by cap10morgan** [comment]
> Seems like the template is not updated when you use deploy. Did you run `sam build` before `sam deploy`?

I did not. It didn't seem like that was necessary for changes to just the `template.yml` file, but it looks like it is. There's something counterintuitive about that to me, but maybe it's just me. Like, if I had changed my code, then sure, `sam build` is needed. But for the AWS resources in `template.yml`, why is a build needed to pick those up? And/or should a build be run automatically on deploy so you aren't deploying something stale?

**Comment by CoshUS** [comment]
`deploy` defaults to the template inside of `.aws-sam/build` folder. The template may change after sam build due to the possibility of including APIGW definition files into the template directly.
Closing this issue, but I'll bring up this UX conversation with the team on automatically building before deploying.
