### ISSUE TITLE
API gateway debugger attach refused

### ISSUE THREAD

**Issue by johanbjorn** [aws/aws-sam-cli#3447]
### Description:
I have defined lambda functions in cdk(python) stack using the _lambda.DockerImageFunction construct. This lambda function is fronted by an api-gateway. 

I'm able to invoke this function locally via the API gateway. However, when I try this in debug model I get an error saying:  

"Visual Studio Code
connect ECONNREFUSED 127.0.0.1:5858 "  

### Steps to reproduce:
1/ clone this public repo: https://github.com/johanbjorn/helloworld
2/ cd helloworld
3/ code . (to start vscode)
4/ python3 -m venv .venv (from bash terminal in vscode, from {workspace} folder)
5/ source .venv/bin/activate
6/ python3 -m pip install -r requirements.txt
7/ sam-beta-cdk build --use-container
8/ sam-beta-cdk local start-api --debug-port 5858 
9/ optioal non-debug call to api: curl http://127.0.0.1:3000/hello
10/ start debugging: debug icon leftmost vertical menu ->select 'Debug(via API GW) hello world from dropdown
11/ click play icon
12/ error message

### Observed result:
vscode diaglog box saying: 
"Visual Studio Code
connect ECONNREFUSED 127.0.0.1:5858 "  

### Expected result:
Debugger should attach to process and start debugging session

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu: 20.04 via WSL 2
2. `sam --version`: sam-beta-cdk --version : SAM CLI, version 1.29.0.dev202108311500
3. AWS region: eu-central-1

VSCode: 1.61.2
Python: 3.8.10
node -v: v16.3.0
npm -v: 8.1.0
Docker Desktop 4.1.1 (69879) 

[System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
10     0      19042  0

**Comment by CoshUS** [comment]
Hey @johanbjorn,
You mentioned you are running SAM CLI with Ubuntu in WSL 2. Are you running both VSCode and SAM CLI in the VM or only SAM CLI while running VSCode on the host?

**Comment by johanbjorn** [comment]
Thank you @CoshUS I'm running both VSCode and SAM CLI in the VM. I open workspace via linux as described here https://code.visualstudio.com/docs/remote/wsl#_open-a-remote-folder-or-workspace.

**Comment by gindulis** [comment]
Having the same issue, unable to connect to the debugger ```Failed to connect to 127.0.0.1 port 5890: Connection refused```

**Comment by jfuss** [comment]
In the original example, there is no debugger configured within the Lambda function code. In order for VSCode to (remote) debug, the function needs to integrate with a Python debugger first (debugpy). You can follow https://code.visualstudio.com/docs/python/debugging#_debugging-by-attaching-over-a-network-connection or https://github.com/microsoft/debugpy#enabling-debugging.

Alternatively, you can use the AWS Toolkit for VSCode which will handle some of this for you: https://aws.amazon.com/visualstudiocode/

**Comment by bedgar** [comment]
I solved this by opening an internet facing tunnel into my debug port, and then connecting the debugger to that internet facing host.  There is probably a better way, but this is the best I've come up with so far.

In a terminal after installing ngock (mac):
`ngrok tcp 3001`

Then in your code:
```
import pydevd_pycharm
pydevd_pycharm.settrace('X.tcp.ngrok.io', port=10057, stdoutToServer=True, stderrToServer=True)
```
