### ISSUE TITLE
Option to force build even if npm package is deprecated

### ISSUE THREAD

**Issue by jchirschy** [aws/aws-sam-cli#3466]
Hello,

Is it possible to force build even if a npm package is deprecated ?
It would be nice if there was an option for allowing this kind of build.

Sincerily

**Comment by wchengru** [comment]
Hi @jchirschy , the version of the npm package is specified in the `package.json` file. SAM CLI is using npm to build Nodejs project. If the version is deprecated, NpmInstall will WARN it but the package is still be able to install.

**Comment by xazhao** [comment]
Closing because it has been inactive for 2 weeks. Feel free to reopen it if you have any other questions.
