### ISSUE TITLE
"sam local start-api" should use HTTP/1.1

### ISSUE THREAD

**Issue by Rabadash8820** [aws/aws-sam-cli#3515]
### Describe your idea/feature/enhancement

It would be nice if `sam local start-api` responses used HTTP/1.1. I ran into this idea while trying to test my API locally with Postman. Requests keep failing there with the console message `Error: Parse Error: Expected HTTP/`, even though the local server output shows a successful response and `curl` requests also work correctly. After some googling, it appears that Postman cannot handle HTTP/1.0 responses. Frankly, I'm annoyed with Postman for not being able to support different HTTP versions (and [others](https://github.com/postmanlabs/postman-app-support/issues/6242) [have](https://stackoverflow.com/questions/20359149/how-can-you-set-the-http-protocol-version-in-postman) already opened tickets with Postman to resolve that), but I see no reason why SAM CLI should use such an ancient version of the protocol either. HTTP/1.1 or /2 would be preferrable (though I think /2 would also break Postman 😬). I believe this is happening because `sam local start-api` uses Flask internally (v1.1.2, at time of this writing), which apparently defaults to using HTTP/1.0

### Proposal

The `sam local start-api` command handler should configure its internal Flask instance to use HTTP/1.1. Based on [this SO post](https://stackoverflow.com/questions/59027260/make-flask-return-response-header-http1-1-instead-http1-0) and a quick search through SAM CLI's source, I think you would just need to add the following line to the [`LocalApigwService.create`](https://github.com/aws/aws-sam-cli/blob/2b2a921172a22f43ef8580eb8ad0be1558e9cb7d/samcli/local/apigw/local_apigw_service.py#L154) method:

```python
WSGIRequestHandler.protocol_version = "HTTP/1.1"
```

I would have opened a PR for this, but I'm not very familiar with Python.

This would not require any updates to the SAM Spec, though it wouldn't hurt to add a warning to the docs about what HTTP version `sam local start-api` uses.

**Comment by xazhao** [comment]
Hi Dan! Thanks for your proposal. I quickly searched in Flask doc and didn't find anything related to http version. I have created an internal task to keep track of this and I will be discussing this with the team.

**Comment by Rabadash8820** [comment]
Sounds good @xazhao thanks! I wasn't able to find much documentation on this either, I just know that SAM uses Flask and `sam local start-api` is currently returning an HTTP/1.0 response 😛

**Comment by mildaniel** [comment]
This issue has now been resolved in version 1.56.1. I will close this issue but please re-open if required.
