### ISSUE TITLE
Sam Local Containers Use ReservedConcurrentExecutions

### ISSUE THREAD

**Issue by crc-sstubbs** [aws/aws-sam-cli#3526]
### Run N containers depending on what is specified in ReservedConcurrentExecutions in the SAM template

It would be great if SAM local using docker would respect ReservedConcurrentExecutions. So for example:
`ReservedConcurrentExecutions: 10` would allow 10 containers concurrently. Currently it seems to always run maximum 4 at the same time. Running containers without --warm-containers is already slow which has been mentioned in this issue https://github.com/aws/aws-sam-cli/issues/2920. If we have more than 4 concurrent requests it means we pay the slow startup penalty more frequently which is not great. 

Perhaps there is another way to increase this. I would appreciate to know if there is in the interim but ideally this should be in the SAM template in my opinion.

**Comment by ssenchenko** [comment]
`ReservedConcurrentExecutions` is a setting for Lambda which you use in production or, generally speaking, any cloud-based environment, where the capacity is quite different from a local environment which can often be a single laptop. Setting default number of concurrent containers to run locally to `ReservedConcurrentExecutions` would not be a great feature for many users.
