### ISSUE TITLE
sam pipeline guidance & feature idea

### ISSUE THREAD

**Issue by paulthorburn** [aws/aws-sam-cli#3528]
Hello,

I have been testing 'sam pipeline' to deploy my first app and it works great, my question is I would like to use the same 'dev' account for several projects. When i run 'sam pipeline init --bootstrap' on my second project it seems to detect the resources the IAM user/roles/s3buckets that already exists I just want to make sure I am not going to overwrite anything from my first project before I proceed with setting anything up.

The other issue i am facing is I am not really understanding how to use the pipelines at scale (several projects in my case). All the switches for 'sam pipeline init and sam pipeline bootstrap' seem to tie the initial IAM creations to deployment stages.

### Describe your idea/feature/enhancement

Wouldn't it be better to have the sam pipeline initialization be treated as 3 parts
1) Create the 'aws-sam-cli-managed-dev-pipeline-resources' which is just IAM user, IAM Role, CloudFormationExecutionRole
2) Creation of the Stage 1 resources including artifacts bucket\ecr repo
3) Creation of the Stage 2 resources including artifacts bucket\ecr repo

That way I can easily 
1) Have seperate artifacts bucket \ ecr repo per project
2) Reuse the same credentials across several projects and even setup a 'SAM Deployment' AWS Account with 1 IAM user\access key and a Github Organizational secret which i can then easily cycle every 30,60 days rather than having several projects with several different iam users and secrets.

### Proposal
**sam pipeline bootstrap** - should not ask for stages, artifacts buckets, ECR image repository those should part of the stage 1 and 2 setups

**sam pipeline init --bootstrap** - ask if you would like to setup the IAM user or use an existing one and then proceed to Stage 1 setup where it creates the s3 bucket\ECR image for that project rather than sharing resources?

**Comment by ssenchenko** [comment]
Thanks for the feature request! We have a [roadmap](https://github.com/aws/aws-sam-cli/wiki/SAM-CLI-Roadmap) here, but we also try to take in popular feature requests based on 👍🏽 from the community. If this issue gets more support from the community we will add it to our intake for prioritization.

**Comment by aahung** [comment]
Hi @paulthorburn 

`sam pipeline bootstrap` will create a dedicated CloudFormation stack for each stage (with name `aws-sam-cli-managed-<stage-name>-pipeline-resources`) and the S3 buckets or ECR repos are not shared. It should be fine if you want to use the same account for multiple projects and not share bucket/ECR repo as long as the stage names are unique.

**Comment by paulthorburn** [comment]
@aahung Thanks for the clarification I was clearly over thinking it. I had called my stage "dev" on both my projects so it was reusing the same resources. Simple just renaming it "project2-dev" created separate resources as you suggested.

Thanks again!
