### ISSUE TITLE
Arn for invoke a local running lambda in Sam-Beta-Cdk from a step function (state machine)

### ISSUE THREAD

**Issue by ET-CS** [aws/aws-sam-cli#3540]
Hi,

I'm running an hello-world lambda from a Cdk using SAM-BETA-CDK.

```
new CdkStack(app, 'CdkStack', {});

...

new lambda.Function(this, 'MyFunction', {
      ...
});
```

running the lambda using:
```
sam-beta-cdk local start-lambda
```

and It's starting successfully:
```
Starting the Local Lambda Service. You can now invoke your Lambda Functions defined in your template through the endpoint.
2021-12-21 12:30:41  * Running on http://127.0.0.1:3001/ (Press CTRL+C to quit)
```

I'm using step functions running locally (https://docs.aws.amazon.com/step-functions/latest/dg/sfn-local.html)
And I'm trying to create a simple step to invoke the lambda running locally

1. Starting a step function server:
```
java -jar StepFunctionsLocal/StepFunctionsLocal.jar --lambda-endpoint http://localhost:3001
```

2. creating a state machine:

```
aws stepfunctions --endpoint http://localhost:8083 create-state-machine --definition "{  \"Comment\": \"A Hello World example of the Amazon States Language using an AWS Lambda Local function\",  \"StartAt\": \"HelloWorld\",  \"States\": {    \"HelloWorld\": {      \"Type\": \"Task\",      \"Resource\": \"arn:aws:lambda:us-east-1:123456789012:function:MyFunction\",      \"End\": true    }  }}}}" --name "HelloWorld" --role-arn "arn:aws:iam::012345678901:role/DummyRole"
```

and execute the state machine:

```
aws stepfunctions --endpoint-url http://localhost:8083 start-execution --state-machine-arn arn:aws:states:us-east-1:123456789012:stateMachine:HelloWorld
```

I see the state machine calling the SAM server but I get an error from SAM about MyFunction not found:
```
Synthesizing CDK App
Starting the Local Lambda Service. You can now invoke your Lambda Functions defined in your template through the endpoint.
2021-12-21 12:30:41  * Running on http://127.0.0.1:3001/ (Press CTRL+C to quit)
MyFunction not found. Possible options in your template: ['CdkStack/MyFunction']
2021-12-21 12:34:18 127.0.0.1 - - [21/Dec/2021 12:34:18] "POST /2015-03-31/functions/MyFunction/invocations HTTP/1.1" 404 -
```

This is the log from the state-machine server:
```
WARNING: All illegal access operations will be denied in a future release
←[0;31m2021-12-21 12:34:18.356: arn:aws:states:us-east-1:123456789012:execution:HelloWorld:efa47cf6-ac97-48ab-9446-654c6d1dacc8 : {"Type":"LambdaFunctionFailed","PreviousEventId":4,"LambdaFunctionFailedEventDetails":{"Error":"Lambda.AWSLambdaException","Cause":"Function not found: arn:aws:lambda:us-west-2:012345678901:function:MyFunction (Service: AWSLambda; Status Code: 404; Error Code: ResourceNotFound; Request ID: null; Proxy: null)"}}
←[0m←[0;31m2021-12-21 12:34:18.359: arn:aws:states:us-east-1:123456789012:execution:HelloWorld:efa47cf6-ac97-48ab-9446-654c6d1dacc8 : {"Type":"ExecutionFailed","PreviousEventId":5,"ExecutionFailedEventDetails":{"Error":"Lambda.AWSLambdaException","Cause":"Function not found: arn:aws:lambda:us-west-2:012345678901:function:MyFunction (Service: AWSLambda; Status Code: 404; Error Code: ResourceNotFound; Request ID: null; Proxy: null)"}}
←[0m
```

I've tried to figure out the correct ARN to run this locally:

* arn:aws:lambda:us-east-1:123456789012:function:CdkStack\MyFunction
* arn:aws:lambda:us-east-1:123456789012:function:CdkStack/\MyFunction
* arn:aws:lambda:us-east-1:123456789012:function:CdkStack:MyFunction
* arn:aws:lambda:us-east-1:123456789012:function:CdkStack@MyFunction
* arn:aws:lambda:us-east-1:123456789012:function:CdkStack-MyFunction
* arn:aws:lambda:us-east-1:123456789012:CdkStack:MyFunction
* arn:aws:lambda:us-east-1:123456789012:CdkStack/MyFunction

but haven't found any correct way for the Arn.

Any suggestion? Is it possible to do what I'm doing?
As in the original documentation - https://docs.aws.amazon.com/step-functions/latest/dg/sfn-local-lambda.html
The example is using SAM and not SAM-CDK-BETA, which probably mean that the lambda name is just `MyFunction` and not `CdkStack/MyFunction`

Any help will be appreciated :)
Thanks!
Etay.

**Comment by c2tarun** [comment]
A new version of sam-cli was released yesterday which have few improvements around CDK. Before we dive into this issue, can you please confirm if you are experiencing this issue with latest version of sam-cli?

**Comment by moelasmar** [comment]
I verified that your use case will work using the new release.
