### ISSUE TITLE
Error when trying to debug: `Must be absolute: file:///var/runtime/Runtime.js`

### ISSUE THREAD

**Issue by fdbatista** [aws/aws-sam-cli#3557]
Hi team.

I am trying to debug an AWS SAM CLI app top of NodeJS.
It all worked fine one week ago, when it suddenly stopped.

I use Jetbrains WebStorm and I am running this command:
`sam local start-api -d 9003 --docker-network db-rebuild_default` because my DB is running on a Docker container, so my Lambda functions need access to it.

First time I send a request via Postman, the breakpoint gets hit correctly. But only the first time.
After that I always get the same error when trying to debug:

![image](https://user-images.githubusercontent.com/11459171/139750426-6aca74a1-9053-40a6-9681-3deb73b0a311.png)

Any ideas?

Environment:
- aws-cli/1.20.44 Python/3.8.5 Linux/5.4.0-72-generic botocore/1.21.44
- SAM CLI, version 1.31.0

**Comment by hoffa** [comment]
Are you still having this issue? What is the Node.js runtime version you're using? At a glance that error doesn't seem to be coming from SAM CLI (but `/var/runtime/Runtime.js` does exist in the build images); is there any way to get more information on where that error comes from?

**Comment by jfuss** [comment]
Closing given no response

**Comment by lup-** [comment]
It can happen if debugger can't resolve breakpoint (for example when some file was deleted or renamed). Clearing breakpoint list helped to resolve issue
