### ISSUE TITLE
SAM/CDK temporal directory mismatch

### ISSUE THREAD

**Issue by teimatinimarin** [aws/aws-sam-cli#3562]
SAM CLI stores files in .aws-out/.cdk-out directory. 
CDK CLI stores files in cdk-out directory.

Would it be any way to either update the directory between these 2 tools or be able to specify the target directory by specifying a flag in CLI?

**Comment by c2tarun** [comment]
Hi @teimatinimarin, SAM CLI's CDK support went into GA yesterday with some changes around `.cdk-out` directory. Now sam-cli won't run cdk but user will have to run and provide the path. This should solve your problem. Please let us know if you have more questions.
