### ISSUE TITLE
Please support minikube as an alternative to Docker Desktop

### ISSUE THREAD

**Issue by mmindenhall** [aws/aws-sam-cli#3566]
### Describe your idea/feature/enhancement

In August 2021 [Docker announced](https://www.docker.com/blog/updating-product-subscriptions/) that the Docker Desktop application would no longer be free for most corporate users.  At my employer most engineers don't use Docker at all _except_ when using `sam local invoke`.

It would be greatly appreciated if SAM CLI could be made to work with [minikube](https://minikube.sigs.k8s.io/docs/) as an alternative to Docker Desktop.  Minikube is easy to install, runs on Mac/Linux/Windows, and contains a docker daemon/engine.  When minikube is "paused", it frees up resources used by the embedded kubernetes cluster, but leaves the docker engine running.  Therefore if `sam local invoke` could be made to work with minikube, it would be much less resource intensive than running Docker Desktop.

In theory the following should work (which I have done on my Mac).

1. Fully uninstalled the Docker Desktop app
1. `brew install hyperkit minikube docker`
2. `minikube start`
3. `eval $(minikube docker-env)` (exports DOCKER_HOST and other env vars)
4. Attempted to run `sam local invoke` on a stack containing a Lambda function

The local invoke unfortunately does not succeed.  The output looks like this:

```
...
Reading invoke payload from stdin (you can also pass it from file with --event)
Invoking index.handler (nodejs14.x)
BlahBlahLambdaLayer15607B5A is a local Layer in the template
Building image........................
Skip pulling image and use local one: samcli/lambda:nodejs14.x-x86_64-c35a66a12aa51442874957628.

Mounting /Users/***/ggit/lambda-template/dist/src as /var/task:ro,delegated inside runtime container
No response from invoke container for BlahBlahLambda334A3D3E
```

### Proposal

- Investigate the failure when using `sam local invoke` with minikube.
- Implement a fix
- Document anything new required of the end user (e.g., a new CLI option for `sam local invoke`)

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)
    - I don't think this will require any changes to the SAM Spec, but may require a new CLI option for `sam local invoke`

### Additional Details
None.

**Comment by mmindenhall** [comment]
Some good new folks!  We got minikube working as an alternative to Docker Desktop on the Mac for running `sam local invoke`.  I want to document this here for anyone who lands here looking for help.

### Uninstall Docker Desktop
If installed via a homebrew cask:
```
brew uninstall docker
```
If installed manually:
1. Click on the docker icon in your toolbar and select “Preferences”
1. Click on the troubleshooting icon (upper right, looks like a bug)
1. Click “Uninstall”
1. Move the Docker app in your Applications folder to the trash

### Install hyperkit, minikube, and docker cli
```
brew install hyperkit minikube docker
```

### Start minikube
A couple of things to note:
1. minikube needs to be started with a file mount in order to access your Lambda code and dependencies.  In my case, all of my Lambda functions are in git repos, so I just mounted the folder where I have checked out all of my git repos.
2. minikube must be started with kubernetes _enabled_.  However, after it's started it can be paused (`minikube pause`).  This will leave the docker engine running, but pauses all of the internal kubernetes services.  Do not start minikube with the `--no-kubernetes` option, as this will not work.

Here are the steps I took:

```
# change "my-repos" to the location of your repos (or single function)
minikube start \
  --mount \
  --mount-string "/Users/$(id -un)/my-repos:/Users/$(id -un)/my-repos"

# export environment variables in your terminal
eval $(minikube docker-env)

# pause to conserve resources
minikube pause
``` 

### Run your `sam local invoke`
You need to add two additional CLI options to your sam local invoke command (wherever it is defined).  These are:
1. `--container-host <minikube ip>`. 
1. `--container-host-interface 0.0.0.0`

```
# use $(minikube ip) to grab the right address
sam local invoke --container-host $(minikube ip) --container-host-interface 0.0.0.0 ...
```

**Comment by c2tarun** [comment]
Thank you for your contribution! We really appreciate this documentation. Until we come up with a better solution we'll be referencing our users to this post.

**Comment by M3Tr01T** [comment]
Has anyone being able of using this solution to debug? I'm not able to figure out how to do it.

**Comment by jfuss** [comment]
We currently only support tools that are compatible with the Docker API, as that is the underlying tech we built on (through Docker support). At this time, we are not planning to directly support minikube but this can be achieved though https://github.com/aws/aws-sam-cli/issues/3566#issuecomment-1005994806.

Closing
