### ISSUE TITLE
SAM-cli cannot be used to run functions build with CDK in a Pipeline  

### ISSUE THREAD

**Issue by matdumsa** [aws/aws-sam-cli#3572]
Wanted to give a shot today to the [new feature](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-cdk.html) I was eagerly waiting for allowing me to run locally my CDK defines lambdas using sam-cli.

I tried starting them and got the following error message:

```
The resource AWS::Lambda::Function '[hidden]' has specified S3 location for Code. It will not be built and SAM CLI does not support invoking it locally.
```

My lambda.Function in cdk is defined using a lambda.CfnParametersCode since it's built in a pipeline. Basically I have an aws CodeBuild project building my source code and moving it through an aws CodePIpeline project. It essentially builds everything sends it to s3 and then synthesize it to alpha and production. That choice seems to limit my ability to use sam-cli to run locally. Is there a different design available to benefit from CI/CD and running locally using sam-cli? I know the CDK have released more pipeline high-level constructs but under the hood they properly use something similar.

I currently work around this (and have been running locally my lambdas for 1+ years) creating a fake sam.yml file that describes my function just for the sake of running them locally, I'd like to get rid of that extra concept however. The most painful thing is that whenever I add a new resource to my Lambda accessible through an environment variable I have to (1) deploy my changes to production and (2) update my yml file w/ the resource before I can run locally introducing a bit of latency in the dev cycle.

**Comment by moelasmar** [comment]
thanks @matdumsa for raising this issue. I will investigate this issue, and update you.

**Comment by moelasmar** [comment]
Hello @matdumsa, 
I created [this sample CDK app](https://github.com/moelasmar/lambda_from_cfn_parameters) to test your use case based on my understanding.

The issue in your use case is CDK will know your lambda function source code during deployment in pipeline, and so when you run `cdk synth` locally the generated templated does not contain any information about the source code.

But you can resolve this issue by adding the assets' metadata property to your Lambda function, and so `SAM` will be able to know the source code path, and so you can run `sam build` and `sam invoke` commands without any issue.

This snippet shows an example for Lambda function with `code: lambda.CfnParametersCode`, and added Assets' metadata properties.
https://github.com/moelasmar/lambda_from_cfn_parameters/blob/cd0ecf973dd2d7ecc0d7a90a31ef468b6cd9e52e/lib/test-stack.ts#L21-L29

and these are the steps to do the local testing:
```
npm install
npx aws-cdk synth PipelineStack --no-staging
cd cdk.out
sam build -t LambdaStack.template.json
sam local invoke
```

I hope this can help you to fix your issue. Please let me know if you still have issues.
