### ISSUE TITLE
[Announcement] Deprecating AWS SAM CLI on Python3.6

### ISSUE THREAD

**Issue by mndeveci** [aws/aws-sam-cli#3583]
**NOTE: If you are installing AWS SAM CLI with Homebrew, Native Linux Installer or through MSI, you are not impacted by this change.**

As of now, AWS SAM CLI can be installed or used as a library within python3.6, python3.7, python3.8 and python3.9 versions. However, python3.6 has reached its end of life by December 23th, 2021.

### What is deprecation schedule?

AWS SAM CLI will not work on python3.6 environments by February 28th, 2022.

### Will this impact my AWS Lambda functions using python3.6?

No, AWS Lambda functions which is using python3.6 as runtime will not be affected by this change. For more information about supported runtimes, please check https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

### Am I impacted by this deprecation?

If you are installing AWS SAM CLI with Homebrew, Native Linux Installer or through MSI, you are not impacted by this change. Following use cases will be impacted by this change;

* If you are using python3.6 and installing AWS SAM CLI through pip install
* If you are using aws-sam-cli as a library and you are building your application with python3.6

**Comment by hawflau** [comment]
We have dropped support for Python3.6 starting in SAM CLI v1.42.0.
Closing.
