### ISSUE TITLE
[Announcement] Runtime Deprecation at SAM CLI v1.39.0

### ISSUE THREAD

**Issue by mndeveci** [aws/aws-sam-cli#3584]
**SAM CLI will stop supporting `python2.7`, `ruby2.5`, `dotnetcore2.1`, `nodejs10` as of version 1.39.0.**

These runtimes are no longer supported by AWS Lambda, and they are on the deprecation path. Users are not able to deploy/update these functions anymore.

### What is deprecation schedule?

With the SAM CLI v1.39.0, it will no longer allow customers to use deprecated runtimes within the CLI.

### Am I impacted by this deprecation?

You are impacted by this if you are still using one of the following runtimes; `python2.7`, `ruby2.5`, `dotnetcore2.1`, `nodejs10`. The recommendation is to upgrade these runtimes to a newer version which is supported by AWS Lambda.

For more information about supported runtimes by AWS Lambda, please check https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

**Comment by sliedig** [comment]
You should probably include Python 3.6 as this has also reached EOL. https://www.python.org/dev/peps/pep-0494/#lifespan

**Comment by mndeveci** [comment]
> You should probably include Python 3.6 as this has also reached EOL. https://www.python.org/dev/peps/pep-0494/#lifespan

We will once Lambda announces their deprecation timeline for python3.6 [in here](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html).

**Comment by mildaniel** [comment]
These runtimes have now been deprecated in v1.39.0.
