### ISSUE TITLE
Unable to publish with AWS::CloudFront::ResponseHeadersPolicy

### ISSUE THREAD

**Issue by jplock** [aws/aws-sam-cli#3591]
### Description:

Receiving this error when trying to publish a template that contains a response headers policy:

```
Publish Failed
Error: The template contains unsupported resource types. [AWS::CloudFront::ResponseHeadersPolicy]
Please follow the instructions in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html
```

### Steps to reproduce:

try to run `sam publish` using this template - https://github.com/smoketurner/sam-cdn/blob/master/template.yml

### Observed result:

```
Publish Failed
Error: The template contains unsupported resource types. [AWS::CloudFront::ResponseHeadersPolicy]
Please follow the instructions in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html
```

### Expected result:

Publish was successful

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. If using SAM CLI, `sam --version`: 1.37.0
3. AWS region: us-east-1

`Add --debug flag to any SAM CLI commands you are running`

**Comment by hawflau** [comment]
Transferring to SAM CLI as it's related to `sam publish`.

@jplock Thanks for raising the issue. After some investigation, I found the error was returned from an api call to Serverless App Repo to publish the application. I have cut an internal ticket to the relevant team to look into issue.

**Comment by hawflau** [comment]
@jplock Speaking with team, I'd also suggest you to reach out to [AWS Support Forum for SAR](https://forums.aws.amazon.com/forum.jspa?forumID=287). For your reference, you can find the supported resources of SAR [here](https://docs.aws.amazon.com/serverlessrepo/latest/devguide/list-supported-resources.html)

Closing as there is nothing we can do on the SAM CLI side

**Comment by jplock** [comment]
@hawflau I opened a similar [issue](https://github.com/aws/serverless-application-model/issues/2052) in June of last year and @c2tarun was able to get this resolved

**Comment by jplock** [comment]
This has now been resolved
