### ISSUE TITLE
[Announcement] Impact of Docker Desktop Licensing changes on SAM CLI

### ISSUE THREAD

**Issue by praneetap** [aws/aws-sam-cli#3595]
### Impact of Docker Desktop Licensing changes on SAM CLI

We are [adding a feature](https://github.com/aws/aws-sam-cli/pull/3706) in SAM CLI which will enable users to run tools that are Docker CLI and Docker Engine compatible (like [Rancher Desktop](https://rancherdesktop.io/) or [Colima](https://github.com/abiosoft/colima)) with SAM CLI.

#### Why are we making changes?

With the change in [Docker licensing](https://www.docker.com/blog/updating-product-subscriptions/), a Docker subscription is needed for commercial usage of Docker Desktop start from January 31st, 2022. The licensing and distribution terms for Docker Engine and Docker CLI are not changing.

#### Am I impacted?

**If you are a Linux user, you are NOT impacted.** You can install Docker Engine and Docker CLI to run the commands below.

If you are a Mac/Windows user: 
If the Docker Desktop is not installed in MacOS or Windows, the following commands and options will not work:

* sam build --use-container
* sam build when you specify a Dockerfile and OCI Image as your packaging format
* sam local invoke
* sam local start-api
* sam local start-lambda

#### What can I do if I do not have a Docker Desktop License?
You can take a look at tools that are Docker CLI and Docker Engine compatible (like [Rancher Desktop](https://rancherdesktop.io/) or [Colima](https://github.com/abiosoft/colima)), or alternatively you can install Docker CLI and Docker Engine inside a virtual machine with Linux system.
If you choose to go with Rancher Desktop, you should select `dockerd` under `Container Runtime` in the Kubernetes Settings.

#### SAM CLI changes

[With this feature](https://github.com/aws/aws-sam-cli/pull/3706), users can plug-in tools that are Docker CLI and Docker engine compatible (like [Rancher Desktop](https://rancherdesktop.io/) or [Colima](https://github.com/abiosoft/colima)).
Please comment on this issue if you have any feedback.

**Comment by Grenguar** [comment]
I think this could be a useful feature, thanks!

**Comment by jwalsh2me** [comment]
I also agree this can be a great alternative for Mac users instead of buying a Docker desktop license just to use Sam.

**Comment by projected1** [comment]
Where does it say that Linux users are not impacted? @praneetap

**Comment by paulmowat** [comment]
As mentioned, definitely useful to avoid having to get docker license just for debugging SAM applications.

**Comment by nicosuerohynds** [comment]
Very useful feature. Please let us know once you have a more clear idea of when this feature could be implemented. Cheers.

**Comment by ericlink** [comment]
It would be fantastic if whatever is needed to enable Podman support could accomodate https://rancherdesktop.io/ as well.

**Comment by ashutoshtripathi** [comment]
Sam should support multiple containerization tools instead of only docker.

**Comment by gregorybosch** [comment]
we are trying to leverage colima for dev.  Would be nice to get a little support for multiple containerization tools.  We have been able to migrate about 90% of our development workflow to this tool without having to change much of anything outside of the docker host.  Unfortunately we are getting very inconsistent results with sam local invoke.  Seeing "No response from invoke container", logs show port setup and tear down.  You can see the emulator spin up for a second and then disappear.  Cannot figure out for the life of me what is going on.

**Comment by gustavdong** [comment]
> 

I'm having the same issue with Colima and SAM Local Invoke, any luck that you have it working now?

**Comment by gustavdong** [comment]
@praneetap Thanks very much for this update! Do you have any estimated timeframe for this Podman supporting feature?

**Comment by praneetap** [comment]
Hello! Thank you all for your patience. I just updated the issue with our latest plans. You can track the tagged issue to know when it makes release, we expect it to go out in about a week.

**Comment by torresxb1** [comment]
@gregorybosch @gustavdong The PR linked in the updated issue (https://github.com/aws/aws-sam-cli/pull/3706) should resolve your issues with Colima. We'll include this in our next release.

**Comment by gustavdong** [comment]
@torresxb1 thanks very much for the update!

**Comment by torresxb1** [comment]
Hi @gustavdong and others, sorry for the delay. Unfortunately we caught a regression in our tests before releasing, so we decided to revert until we fixed that. The re-implementation with the fix should be coming in the next couple of weeks. I'll post the updates here.

**Comment by praneetap** [comment]
This is now released with 1.47.0. Thanks all!

**Comment by gustavdong** [comment]
> 

Hi @jwalsh2me , for `colima` you can add this to your bash_profile `
export DOCKER_HOST="unix://$HOME/.colima/docker.sock"`

**Comment by gregorybosch** [comment]
I am seeing a lot of issues with this build.  The debugger is never able to
find my handler.  Using a compressed file (.zip) to load function into
runtime the function never shows up under /var/task.  Second, when the
startup fails the docker images remain running and never clean up.

**Comment by gregorybosch** [comment]
never mind..i forgot that I needed to map to /private/var/folders along
with the source folder on colima.  all good.

Thanks, seems to be working a lot more consistently.

Greg

**Comment by jwalsh2me** [comment]
Thanks @gustavdong and @torresxb1, I had that in the ~.zshrc.  What it was missing is the docker-credentials helper.  I found this in a search and it solved my problem: [https://cri.dev/posts/2020-07-06-How-to-solve-Docker-docker-credential-desktop-not-installed-or-not-available-in-PATH/](Blog Posting).   I am not sure what introduced it but I did have a misspelling in my config.json for docker it was `credsStore` instead of `credStore`.  Thanks for the help and hopefully this might help someone else who hits this error!

**Comment by ISimionEndava** [comment]
> Hi everybody, sorry again for the delays! As @praneetap mentioned, #3831 went out with the release of version 1.47.0, and it should unblock you from trying out Docker Desktop alternatives that use the Docker runtime. We don't officially endorse any specific alternative but I've personally tried Colima and Rancher Desktop with the `dockerd` option. Please let us know if you face any issues.

Did it work with Rancher Desktop? I am struggling to make it work. For some reason, my `requirements.txt is not found`.

**Comment by carlnc** [comment]
For the rancher users ... 
```
export DOCKER_HOST="unix://$HOME/.rd/docker.sock"
```

**Comment by ISimionEndava** [comment]
> 

Hi, could you please clarify where in Rancher I can find Administrator Access? I am trying your second solution, but on Rancher Desktop, it seems I do not have that option. I am running Rancher Desktop on a Windows machine.

**Comment by carlnc** [comment]
@ISimionEndava 

![image](https://github.com/aws/aws-sam-cli/assets/7519153/7216e066-a92e-43bb-9461-7db601cfafa9)

When Rancher starts, it will probably ask for the admin password ... every time.

**Comment by ISimionEndava** [comment]
@carlnc Thank you for the specific picture, strange enough I do not have that option on Rancher Desktop on a Windows System, it might be it is only available for Linux and MacOS.

**Comment by ron-matsliah** [comment]
To make sam CLI work with Rancher desktop, you can add the following to the override config file (on Mac it located under ~/Library/Application\ Support/rancher-desktop/lima/_config/override.yaml)
``
mountType: 9p
mounts:
  - location: "/private/var/folders/"
    9p:
      securityModel: mapped-xattr
      cache: "mmap"
  - location: "~"
    9p:
      securityModel: mapped-xattr
      cache: "mmap"
``

**Comment by svolotin** [comment]
> > @ron-matsliah Cannot find this file on a Windows System unfortunately :(
> 
> See here https://docs.rancherdesktop.io/how-to-guides/provisioning-scripts/ Btw you will need to verify what sam is trying to mount to the container, on mac its /private/var/folders Its on the output of the sam local command

i'm new to windows and unfortunately need to use windows in a project.

how to write a .start -file to windows which configures that mountType and mounts?
