### ISSUE TITLE
Latest Python 3.6 emulation image is broken

### ISSUE THREAD

**Issue by rli** [aws/aws-sam-cli#3610]
### Description:
`/var/runtime/awslambda/bootstrap.py` does not exist.
Both SAM CLI and the toolkits take a dependency on this bootstrap location for Python 3.6

https://github.com/aws/aws-sam-cli/blob/3df595785b29080895e351aed441f8655161c420/samcli/local/docker/lambda_debug_settings.py#L147-L150

https://github.com/aws/aws-toolkit-jetbrains/blob/5a4dfecc9c8fe30d1fa2f3a0189d7501dc85f96f/jetbrains-core/src/software/aws/toolkits/jetbrains/services/lambda/python/PythonDebugSupport.kt#L75-L80

https://github.com/aws/aws-toolkit-vscode/blob/6f1eabb347712447fdc82a6a533bbb5289fdb1f1/src/shared/sam/debugger/pythonSamDebug.ts#L248-L249

### Steps to reproduce:
```
$ docker run --rm -it --entrypoint bash public.ecr.aws/sam/emulation-python3.6:latest
bash-4.2# file /var/runtime/awslambda/bootstrap.py
/var/runtime/awslambda/bootstrap.py: cannot open `/var/runtime/awslambda/bootstrap.py' (No such file or directory)


$ docker run --rm -it --entrypoint bash public.ecr.aws/sam/emulation-python3.6:2022-01-11
bash-4.2# file /var/runtime/awslambda/bootstrap.py
/var/runtime/awslambda/bootstrap.py: Python script, ASCII text executable
```

### Observed result:
```
$ sam local invoke -d5555
[...]
/var/lang/bin/python3.6: can't open file '/var/runtime/awslambda/bootstrap.py': [Errno 2] No such file or directory
01 Feb 2022 00:17:53,886 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 2 InvokeID=
/var/lang/bin/python3.6: can't open file '/var/runtime/awslambda/bootstrap.py': [Errno 2] No such file or directory
```

### Expected result:
`/var/runtime/awslambda/bootstrap.py` to exist

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
```
$ sam --info
{
  "version": "1.37.0"
}
```

**Comment by moelasmar** [comment]
Thanks @rli for reporting this issue. This issue is fixed, and verified.
