### ISSUE TITLE
sam deploy --config-env test --template-file .aws-sam/build/template.yaml

### ISSUE THREAD

**Issue by zerkowsm** [aws/aws-sam-cli#3629]
### Description:
It is impossible to apply both ```--config-env``` and ```--template-file``` into the ```sam deploy``` command. ```samconfig.toml``` in such case is being ignored.

### Steps to reproduce:
Execute: ```sam deploy --config-env test --template-file .aws-sam/build/template.yaml```
with having ```samconfig.toml``` as below:

```
[test.global.parameters]
stack_name = "some-stack-name"

[test.build.parameters]

[test.deploy.parameters]
region = "eu-west-1"
```
### Observed result:
```Error: Missing option '--stack-name', 'sam deploy --guided' can be used to provide and save needed parameters for future deploys.```

### Expected result:
Stack name and other parameters should be picked up from ```samconfig.toml``` file.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 12.1 (21C52)
2. `sam --version`: SAM CLI, version 1.37.0
3. AWS region: any

**Comment by moelasmar** [comment]
Thanks @zerkowsm for sending us this question.

The default behavior of `sam deploy` command is to look for a toml file named `samconfig.toml` in the same path of the provided template file. 

So, to fix this issue, you can either copy the `samconfig.toml` file to the directory contains your template file.
```
$ cp samconfig.toml .aws-sam/build/
$ tree -a .aws-sam/build/
.aws-sam/build/
├── samconfig.toml
└── template.yaml
$ sam deploy --config-env test --template-file .aws-sam/build/template.yaml
``` 
or you can add `--config-file` option, and set its value the path of your toml configuration file as an relative path to the template file.
```
# let's say this your current dir structure
$ tree -a
.
├── .aws-sam
│   ├── build
│   │   └── template.yaml
│   └── build.toml
└── samconfig.toml
$ sam deploy --config-env test --template-file .aws-sam/build/template.yaml --config-file ../../samconfig.toml
```
I hope this answers your question.

**Comment by zerkowsm** [comment]
If that answers my question, you ask?;) It works as a charm. Thanks for providing so informative answer!

I wish it was so clear after reading https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html.
I know there is this note:

```Note: If you specify this option, AWS SAM deploys only the template and the local resources that it points to.```

next to the `-t, --template-file, --template PATH` Option column. But I read it a bit differently, apparently.

Thanks again, @moelasmar!
