### ISSUE TITLE
Feedback on SAM Pipelines

### ISSUE THREAD

**Issue by praneetap** [aws/aws-sam-cli#3633]
In 2021, we launched [sam pipelines](https://aws.amazon.com/blogs/compute/introducing-aws-sam-pipelines-automatically-generate-deployment-pipelines-for-serverless-applications/) which helps you create cross-account and cross-region pipelines that follow AWS' best practices. To help build better integrations with CI/CD systems, we launched [CI container images](https://aws.amazon.com/about-aws/whats-new/2021/06/new-tools-to-simplify-continuous-integration-systems/) and [setup-sam GitHub Actions](https://aws.amazon.com/about-aws/whats-new/2021/06/configure-github-actions-workflows-with-new-github-action-for-building-serverless-applications/). 
[SAM CLI Roadmap can be found here](https://github.com/aws/aws-sam-cli/wiki/SAM-CLI-Roadmap).
Please leave your feedback on this feature in this issue.

**Comment by ookadoo** [comment]
Are there any plans to implement Azure Devops pipelines/release pipelines?

**Comment by praneetap** [comment]
Hi @ookadoo! We can take that in as a feature request. Thanks!

**Comment by jfuss** [comment]
Moved to Discussions: https://github.com/aws/aws-sam-cli/discussions/4688

Closing
