### ISSUE TITLE
[Announcement] Java Build Changes

### ISSUE THREAD

**Issue by mndeveci** [aws/aws-sam-cli#3639]
With the SAM CLI release 1.38.0, we will have some changes in how we build Java functions and layers. These changes will not be set as default until April 1st, 2022, so please test it out with `SAM_CLI_BETA_MAVEN_SCOPE_AND_LAYER=1 sam build` and let us know of any issues or improvements about it by commenting on this issue.

## Am I impacted by this change?

You might be impacted by this change if you have;

* Functions which is using Maven for project/dependency management and you have a dependency with `provided` scope.
* Any Layer definition which has a java compatible runtime (including both Gradle and Maven) and uses SAM CLI to build itself.

## What are the changes?

* **Maven projects will use runtime scope for bundling dependencies.** As of now, Java Maven projects are using `compile` scope for bundling dependencies, which includes dependencies with `provided` scope. With this change we will start using `runtime` scope which will only include dependencies that is required during runtime. Please check following page for more information about scope definition of maven dependencies (https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-scope)
* **Java Layers does not support loading `.class` files from bundled ZIP.** For that reason Maven and Gradle projects will only include JAR output of the source code (as well as dependencies). That change will only affect how we are building Layers. Functions will stay the same as loading `.class` files is a valid option for it.

In order to validate that these changes won’t be affecting your project, please run `SAM_CLI_BETA_MAVEN_SCOPE_AND_LAYER=1 sam build` and confirm that your functions and layers are built and working as expected.

If you encounter any issues or have some questions, please comment in this issue.

**Comment by praneetap** [comment]
> `SAM_CLI_BETA_MAVEN_SCOPE_AND_LAYER=1 sam build` works as expected.
> Thanks 👍🏼

Happy to hear it @RajasGujarathi !

**Comment by screamndigit** [comment]
Finally! i can remove my Makefiles that filtered out all the dependencies i already had in my layer.  
Switching to `BuildMethod: java11` is working perfectly.

**Comment by RajasGujarathi** [comment]
`SAM CLI, version 1.50.0`

Using `sam build` displays the message

> Test the latest build changes for Java runtime 'SAM_CLI_BETA_MAVEN_SCOPE_AND_LAYER=1 sam build'. These changes will replace the existing flow on 1st of April 2022. Check https://github.com/aws/aws-sam-cli/issues/3639 for more information.

Was wondering by when this feature will be set as **default**.

This will help us in effectively planning to upgrade our deployment scripts

**Comment by mndeveci** [comment]
This is been released with [SAM CLI v1.51.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.51.0)

**Comment by shaktiks** [comment]
How to turn off this default option and revert to old option?

**Comment by chace86** [comment]
> How to turn off this default option and revert to old option? I have jar that we are including with the function with system scope and now it is not working.

Rollback to previous version you were using?

**Comment by chace86** [comment]
This was a timely update. Moving from 1.50 to 1.51 immediately solved the issue of building common library source code I have! Thank you!
