### ISSUE TITLE
sam local start-api / requirements.txt support

### ISSUE THREAD

**Issue by a-dawg** [aws/aws-sam-cli#3640]
### Description:
I am trying to test locally a python 3.8 lambda function with sam cli
It turns out that it does not include my python modules that are in the same src/myfunction
├── app.py
├── __init__.py
└── requirements.txt
requirements.txt
```
boto3
dynamodbgeo
```
### Steps to reproduce:
```sam build -u
sam local start-api -t template.yaml -p 3001  --parameter-overrides Table=mytable Env=AWS_SAM_LOCAL --warm-containers EAGER
```
Indeed the modules are not installed inside the container

### Observed result:
```
Invalid lambda response received: Invalid API Gateway Response Keys: {'stackTrace', 'errorMessage', 'errorType'} in {'errorMessage': "Unable to import module 'app': No module named 'dynamodbgeo'", 'errorType': 'Runtime.ImportModuleError', 'stackTrace': []}
```

### Expected result:
the function runs normally with the deps

sam version:  1.16

Overall questions how to test with the deps, I do not wish to use the invokefunction here, I need a local listener

**Comment by a-dawg** [comment]
in order to solve this you can download the python modules in the src/myfunction directory with pip3 install -r requirements.txt -t .

**Comment by Maunte** [comment]
Not sure why this was closed...this is very annoying.  The workaround suggested by @a-dawg works, but then you need to ignore/cleanup a mess of dependencies.  The experience should be the same as _sam local invoke_:  Dependencies should be read from the .aws-sam automatically.
