### ISSUE TITLE
Different behavior of "sam local start-api" when called as uri or from the react application

### ISSUE THREAD

**Issue by olisis** [aws/aws-sam-cli#3672]
Hello,.

1. If I call an endpoint from REACT application published on S3, I get response like

["Data1", "Data2"]

2. If I call exactly the same endpoint locally (sam local start-api) from REACT application in my local dev env.

If I call api in a browser http://127.0.0.1:8000/data/, the browser returns error in the console
net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
and 
"Network" -> "Response" shows 
"Failed to load response data. No data found for resource with given identifier"

However in the same time, in sam console I can see both the data and correct status are returned by lambda:

{'statusCode': 200, 'headers': {'x-amzn-requestid': '375fafda-8c06-4d48', 'content-type': 'application/json', 'content-length': '468', 'date': 'Sat, 19 Feb 2022 21:03:47 GMT', 'Access-Control-Allow-Origin': '*'}, 'body': '["Data1", "Data2"]', 'isBase64Encoded': 'false'}
END RequestId: e7969c5e-e0db-47a6-8c42
REPORT RequestId: e7969c5e-e0db-47a6-8c42 Init Duration: 0.20 ms  Duration: 515.01 ms     Billed Duration: 516 ms Memory Size: 256 MB     Max Memory Used: 256 MB
2022-02-19 22:03:47 127.0.0.1 - - [19/Feb/2022 22:03:47] "GET /ref_data/types HTTP/1.1" 200 -

The same output coming if I use curl http://127.0.0.1:8000/data/ or access http://127.0.0.1:8000/data/ with browser - everything is working correctly excluding trying to call this uri from locally running REACT app (which actually triggers the correct lambda execution according sam log, but get an empty response).

**Comment by mndeveci** [comment]
Thanks for reporting this issue. This might be related to development server of the react app. Can you provide us a minimal example with steps to re-produce so that we can investigate the issue further?

**Comment by jfuss** [comment]
Closing give no response. Please re-open or create a new issue (closed issues are hard to track) if you still need help.
