### ISSUE TITLE
ERPNEXT 13 Installation  Easy install error URGENT !!!!

### ISSUE THREAD

**Issue by Alialhaj77** [aws/aws-sam-cli#3673]
I have tried to install ERPnext 13 more than 20 times , using all the tutorials but no good result ,
when I use Easy install [ sudo python3 install.py --verbose --production --user [USER] --mariadb-version 10.5 --frappe-branch version-13 --erpnext-branch version-13 ]
I got error , return none zero status 2

Could you please help me out

the whole result

fatal: [localhost]: FAILED! => {
"changed": true,
"cmd": [
"bench",
"init",
"/home/frappe/frappe-bench",
"--frappe-path",
"https://github.com/frappe/frappe",
"--frappe-branch",
"version-13",
"--python",
"python3"
],
"delta": "0:00:00.378029",
"end": "2022-02-20 10:45:29.953302",
"invocation": {
"module_args": {
"_raw_params": "bench init /home/frappe/frappe-bench --frappe-path https://github.com/frappe/frappe --frappe-branch version-13 --python python3",
"_uses_shell": false,
"argv": null,
"chdir": null,
"creates": "/home/frappe/frappe-bench",
"executable": null,
"removes": null,
"stdin": null,
"stdin_add_newline": true,
"strip_empty_ends": true,
"warn": true
}
},
"msg": "non-zero return code",
"rc": 1,
"start": "2022-02-20 10:45:29.575273",
"stderr": "Traceback (most recent call last):\n File "/usr/bin/bench", line 33, in \n sys.exit(load_entry_point('frappe-bench', 'console_scripts', 'bench')())\n File "/usr/bin/bench", line 22, in importlib_load_entry_point\n for entry_point in distribution(dist_name).entry_points\n File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution\n return Distribution.from_name(distribution_name)\n File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name\n raise PackageNotFoundError(name)\nimportlib.metadata.PackageNotFoundError: frappe-bench",
"stderr_lines": [
"Traceback (most recent call last):",
" File "/usr/bin/bench", line 33, in ",
" sys.exit(load_entry_point('frappe-bench', 'console_scripts', 'bench')())",
" File "/usr/bin/bench", line 22, in importlib_load_entry_point",
" for entry_point in distribution(dist_name).entry_points",
" File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution",
" return Distribution.from_name(distribution_name)",
" File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name",
" raise PackageNotFoundError(name)",
"importlib.metadata.PackageNotFoundError: frappe-bench"
],
"stdout": "",
"stdout_lines": []
}

PLAY RECAP *****************************************************************************************************************************************************************
localhost : ok=67 changed=17 unreachable=0 failed=1 skipped=62 rescued=0 ignored=0

Traceback (most recent call last):
File "install.py", line 497, in
install_bench(args)
File "install.py", line 278, in install_bench
run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
File "install.py", line 413, in run_playbook
success = subprocess.check_call(args, cwd=playbooks_folder, stdout=log_stream, stderr=sys.stderr)
File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2.

**Comment by jfuss** [comment]
@Alialhaj77  This doesn't appear related to AWS SAM CLI but instead `frappe-bench`.

Did you cut this to the wrong repo? If not, what is the issue with AWS SAM CLI you are running into?

**Comment by florentdp** [comment]
I am running into the same issue, waiting for an update!

**Comment by mndeveci** [comment]
Sorry but seems like this issue is not related to AWS SAM CLI.

Please add a comment or create a new issue with steps to re-produce. And please also mention which part of your workflow you are using AWS SAM CLI.

Thanks!
