### ISSUE TITLE
sam sync custom CF stack names 

### ISSUE THREAD

**Issue by fsmed** [aws/aws-sam-cli#3686]
### Describe your idea/feature/enhancement
The sam sync command creates a stack named `aws-sam-cli-managed-default`, this doesn't work in an environment with restrictive IAM permissions.

### Proposal

Add an option to define stack name or the ability to prefix the stack name.

**Comment by fsmed** [comment]
Might be related to https://github.com/aws/aws-sam-cli/issues/3537

From debug output:
2022-02-24 11:15:53,671 | Managed S3 stack [aws-sam-cli-managed-default] not found. Creating a new one.

So I guess the stack is for the S3 bucket.

**Comment by mingkun2020** [comment]
Thanks for the feature request! We have a [roadmap](https://github.com/aws/aws-sam-cli/wiki/SAM-CLI-Roadmap) here, but we also try to take in popular feature requests based on 👍🏽 from the community. We will be adding this to our intake for prioritization.

**Comment by mndeveci** [comment]
Thanks for the feedback @fsmed , this is indeed related to #3537. I am resolving this one and we can continue discussion on the other one.
