### ISSUE TITLE
Mounting docker container image stuck

### ISSUE THREAD

**Issue by liadt-neosec** [aws/aws-sam-cli#3712]
Hi,
I'm using `aws-sam-cli`, version 1.40.1, to build my AWS Lambda through a GitHub action.
while running this command:
`sam build --template ${SAM_TEMPLATE} --use-container --base-dir ./lambda --debug`
which usually took me about 1 minute more or less, it now takes almost 3 hours, and it doesn't show any errors and stuff.
It happened already 3 times, starting from 3.3.22

Here is the process it's getting stuck on:
2022-03-03 15:29:42,720 | Mounting /home/runner/work/..... as /tmp/samcli/source:ro,delegated inside runtime container

Unfortunately, I don't have any more traceback and stuff to show, because there isn't. 

Environment:
Ubuntu 20.04
1.40.1
us-east1

 Thank you :)

**Comment by jfuss** [comment]
@liadt-neosec I am not sure how to debug this for you. In my experience, this is usually a docker sharing issue or docker mounting issue. SAM CLI just interacts with docker and waits for it return back. 

Are you using https://github.com/aws-actions/setup-sam?

**Comment by liadt-neosec** [comment]
@jfuss Yes, I do use setup-sam: 
` - uses: aws-actions/setup-sam@v1`
The issues still exist, it even takes now about 3 and a half hours (instead of 2:45h),
is this can be a cache issue maybe? something related to the docker or the machine it is running on?

**Comment by liadt-neosec** [comment]
**update 
I found the issue, it's not related to `aws-sam-cli`.
It started to happen to me when I added to `requirments.txt` a few packages, that had a versions conflicts in them,
pip had to resolve this dependencies issue, and it took it between 3 to 4 hours each time.

thank you for trying to help :)
I'm closing this issue.
