### ISSUE TITLE
SAM cli version - official AWS site out of date and github docs unhelpful to get latest version

### ISSUE THREAD

**Issue by Leigh-M** [aws/aws-sam-cli#3727]
### Description:
sam cli is more difficult to update to the latest version (Linux Ubuntu 21.10) than it should be - missing step in docs.

On Linux when using sam cli we are prompted regularly with:  `SAM CLI update available (1.40.1); (1.36.0 installed)`

However when you do using the installer found here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html   ie, download the zip, unzip it.

And run the install with the update flag: `sudo ./install --update`

Then it returns `Found same AWS SAM CLI version: /usr/local/aws-sam-cli/1.36.0. Skipping install.`

The only way I can force this to update, is to delete everything existing in the SAM folder, ie I remove:
aws-sam-cli-src
dist
install
THIRD-PARTY-LICENSES

Then try the `sudo ./install --update` and it does indeed update correctly..

This is very frustrating as the update does not appear to work out of the box for me, without deleting the existing source folders

Thanks

**Comment by CoshUS** [comment]
@Leigh-M 
Thanks for the feedback. SAM CLI linux installer will skip installation if the current installed version is the same as the installer.
Did you download the 1.40.1 zip file when you run `sudo ./install --update`?

**Comment by Leigh-M** [comment]
Hi @CoshUS yes of course - that’s my point it definitely doesn’t update out of the box for me on Ubuntu 21.10. I’ll check it again on a different machine so 2x examples to verify, probably when 1.40.2 is released. Will update this ticket with more info then thanks

**Comment by mndeveci** [comment]
As it is been mentioned, you need to download up-to-date installer and run `sudo ./install --update` with it. 

Please let us know if you have further questions.
