### ISSUE TITLE
On 'deployOptionally save stack ou

### ISSUE THREAD

**Issue by jeff-wishnie** [aws/aws-sam-cli#3730]
### Describe your idea/feature/enhancement

When using sam deploy in a monorepo or ci pipeline, stack outputs containing resource identifiers may be needed as inputs to further build and deploy steps. Parsing the stdout of the sam command is awkward and brittle (the output may change) and running additional aws cli describe-stack` command is unneccesary as sam already has the necessary data.

### Proposal

Adds an optional argument to deploy and sync commands so save stack outputs into a local YAML or JSON file.

e.g. 
`> sam deploy --stack-outputs-file stack-outputs.json`

### Additional Details
This is related to #2770 but a slightly different issue. #2770 is about when outputs are printed to stdout. This issue is not about _when_ to output the information, but providing the option to output it in an additional format. 

Here is a draft PR of the working functionality: #3729 -- it is a straightforward addition and very little code.

The PR passes linting and type checks, but I've not bothered updated tests yet. Would like feedback first!

**Comment by qingchm** [comment]
Thanks for the request! I believe this is a valid request, and we will consider the possibility of having a command to output the deployment output for you. Appreciate the input and look forward to having you supported!

**Comment by sriram-mv** [comment]
There is a new command called `sam list stack-outputs --output json`. You can save the contents of the outputs to a file by redirecting that.
