### ISSUE TITLE
`sam local invoke --env-vars` not works when Custom runtime

### ISSUE THREAD

**Issue by overheat** [aws/aws-sam-cli#3744]
### Description:

I follow [invoke function locally](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-invoke.html#serverless-sam-cli-using-invoke-environment-file) and env.json like this:
```
{
  "Parameters": {
    "TABLE_NAME": "localtable",
    "BUCKET_NAME": "testBucket",
    "STAGE": "dev"
  }
}
```

`sam local invoke --env-vars` not works when Custom runtime. Specific [aws-lambda-rust-runtime](https://github.com/awslabs/aws-lambda-rust-runtime)

### Steps to reproduce:

```
sam local invoke rust-lambda \
--event functions/json/response.json \
--env-vars functions/json/env.json \
--template ./cdk.out/Cdkv2SamLambdaRustStack.template.json
```

### Observed result:

```
thread 'main' panicked at 'Missing STAGE env var: NotPresent', src/main.rs:98:48
```
But aws console(Custom runtime on Amazon Linux 2) works, after I deploy lambda to aws cloud.
```
Response
{
  "msg": "devOK!",
  "req_id": "4fe63032-6b54-4922-92ab-fc42a3c500bb"
}
```

### Expected result:

Should be similar with aws console (cloud)
```
Response
{
  "msg": "devOK!",
  "req_id": "4fe63032-6b54-4922-92ab-fc42a3c500bb"
}
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20.04 X86_64
2. `sam --version`: SAM CLI, version 1.40.1
3. AWS region: us-west-2

`Add --debug flag to command you are running`

**Comment by overheat** [comment]
`{FunctionName: {key:value}}` format also failed.

**Comment by CoshUS** [comment]
Hey @overheat,
Thanks for the report. Can you also provide your project structure and template?

**Comment by overheat** [comment]
> Hey @overheat, Thanks for the report. Can you also provide your project structure and template?

Thanks for your reminder, I found that no env var in the template file.
