### ISSUE TITLE
SAM Deploy suddenly stopped working because of error: Unrecognized resource types: [AWS::CloudFormation::UluruResourceV2]

### ISSUE THREAD

**Issue by fernlop** [aws/aws-sam-cli#3768]
sam deploy isn't working anymore for me and fails in the "Initiating deployment" stage. 
I receive this error:

> Error: Failed to create/update the stack: Schedules, An error occurred (ValidationError) when calling the GetTemplateSummary operation: Template format error: Unrecognized resource types: [AWS::CloudFormation::UluruResourceV2]

Everything was working a few hours ago and I even tried it on my laptop, which wasn't powered on for more than a week, and it didn't work there too. So I assume this isn't an error on my side. 

After taking more research, the **GetTemplateSummary operation** received the current template from aws and does something (maybe compare?) with it. 

My sam version is: 1.41.0 (updated today)

**Comment by dacgray** [comment]
Getting the same.

**Comment by jaxdj2012** [comment]
same issue here across all the environments

**Comment by stepiro** [comment]
Same issue here.

**Comment by SBMagar** [comment]
Same issue here too

**Comment by othmar-weber** [comment]
+1

**Comment by mako9** [comment]
+1

**Comment by kojikoji39** [comment]
+1

**Comment by dacgray** [comment]
Now working for me on eu-central-1.

Recommend sitting tight if you're still getting the error.

**Comment by SBMagar** [comment]
Yep, It's working for eu-central-1 now.

**Comment by kojikoji39** [comment]
me, too!

**Comment by fernlop** [comment]
It is fixed now.

**Comment by IsaacMurtagh** [comment]
I was getting this because my samtoml config was using an AWS profile, where as my sync command I forgot to set the profile.
