### ISSUE TITLE
Slow start times when connected to network

### ISSUE THREAD

**Issue by smiffy6969** [aws/aws-sam-cli#3782]
### Description:
Slow start times when connected to network. SAM takes ages to start, 3sec before running and stopping, 2sec when using EAGER or lazy (after inital 3sec). This is a big issue when testing endpoints with say mocha, the slow startup times mean testing takes ages. I can load EAGER or LAZY but they are not much better. Seen this since the last year or so, and today by chance i happened to have my wifi turned off on my laptop and low and behold my tests blasted through in ms each. The loading is super fast when wifi is turned off and not connected to the internet.

### Steps to reproduce:
Hit lambda locally with sam local started normally, EAGER or LAZY and note time.
Repeat with no network connect to outside world to see way better times.

### Observed result:
Faster load times by a mile

### Expected result:
ermmmm 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
Ubuntu LTS 20.04 on dell xps13 but also noted in earlier versions of ubuntu and on various other systems and laptops some running windows (this has been a problem for a long while for SAM)

**Comment by hawflau** [comment]
Hey thanks for reporting the issue. We will look into it further.

**Comment by torresxb1** [comment]
Hi, are you still experiencing this issue? If so, could you provide us with a sample project and steps to reproduce?

**Comment by smiffy6969** [comment]
After much much digging, turns out if you don't have a config setup with an account, load times are super slow. I would guess its to do with aws resource connectivity thats doing this when no config set. I don't see why it should be this way, you may want to run SAM local with no aws creds loaded. After adding in my aws creds it dramatically changed the load times for hitting SAM endpoints.

Would be good to omit connections to AWS if no creds set, so that some dev's, juniors can run without any creds set on AWS config, but no biggy i suppose.

regards

Paul

**Comment by torresxb1** [comment]
Interesting, thanks for digging into this and providing more context! Let me bring this up with the team.

**Comment by torresxb1** [comment]
Hi @smiffy6969, I brought this up to the team but we're not immediately sure why credentials would slow this down. My own brief testing with our sample projects/templates didn't seem to show some difference in speed. If you could provide us with some sample project that displays this behaviour, it would really help us in digging into the root cause.

**Comment by moelasmar** [comment]
Closing given no response
