### ISSUE TITLE
--resolve-image-repos to create ECR repo with tags

### ISSUE THREAD

**Issue by joshuachoi0508** [aws/aws-sam-cli#3786]
Hello,

currently --resolve-image-repos creates an ECR repo without tags given in the command. For an example, 

```
sam deploy --stack-name example-stack \
--resolve-image-repos \
--capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_IAM CAPABILITY_NAMED_IAM \
--no-fail-on-empty-changeset \
--template-file ./.aws-sam/build/template.yaml \
--resolve-s3 \
--tags "Name=example-tag"
```

will create all the resources in the main stack with the name: example-tag but the companion stack and the ECR repository inside of it will be created without the tag. It would be nice for the companion stack to get the tags as well. Alternately, it'd be nice if we could create define a ECR repo in the template and use that repo in the imageUri property.

**Comment by hawflau** [comment]
Thanks for the feature request! We have a [roadmap](https://github.com/aws/aws-sam-cli/wiki/SAM-CLI-Roadmap) here, but we also try to take in popular feature requests based on 👍🏽 from the community. We will be adding this to our intake for prioritization.

**Comment by sriram-mv** [comment]
Tracking under a larger umbrella of features in #3503
