### ISSUE TITLE
sam build can't find package org.apache.logging.log4j.core.util

### ISSUE THREAD

**Issue by umshreyas** [aws/aws-sam-cli#3812]
### Description:
I am trying to use sam build to build one of my lambda's locally. I am using gradle build system. 
I run ./gradlew build, my project builds fine. However when i try to do sam build, i get the package not found error.
Using IntelliJ. Not entirely sure if it's an issue with my build.gradle file, i suspect that's not the case since .gradlew build runs fine.
The issue occurs only with sam build.

### Steps to reproduce:
sam build command. I'm running sam build command in a directory which has the template.yaml file which is of type 
Type: AWS::Serverless::Function 

### Observed result:
 File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 302, in run
    action.execute()
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/java_gradle/actions.py", line 30, in execute
    self._build_project(init_script_file)
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/java_gradle/actions.py", line 56, in _build_project
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Gradle Failed: /Users/smegalamane/Desktop/Shreyas/dev/licensing-operations/lambda/java/atr-load-automation/src/main/java/com/tableau/atr_load_pre_processor/FlattenLoadConfigFile.java:18: error: package org.apache.logging.log4j.core.util does not exist
import org.apache.logging.log4j.core.util.StringBuilderWriter;

### Expected result:
sam build should have found the log4j package.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`: 1.46.0
3. AWS region: us-west-2

`Add --debug flag to command you are running`

**Comment by mndeveci** [comment]
Thanks for the issue.

Can you share more details of your gradle file, so that we can re-produce it on our side?

I've tried with our Hello World examples, and tried to import `org.apache.logging.log4j.core.util.StringBuilderWriter`. If I run `sam build` it failed. But if I add `implementation 'org.apache.logging.log4j:log4j-core:2.17.2'` dependency, it worked without errors.


```
plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.amazonaws:aws-lambda-java-core:1.2.1'
    implementation 'com.amazonaws:aws-lambda-java-events:3.11.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.17.2'
    testImplementation 'junit:junit:4.13.2'
}

sourceCompatibility = 1.8
targetCompatibility = 1.8
```

**Comment by umshreyas** [comment]
Please see my gradle file below.
```
plugins {
    id 'java'
}

sourceCompatibility = 11
targetCompatibility = 11

dependencies {
    implementation (
            'com.amazonaws:aws-lambda-java-core:1.2.0',
            'com.amazonaws:aws-java-sdk-s3:1.11.129',
            'org.json:json:20171018',
            'com.google.guava:guava:19.0',
            'com.google.code.gson:gson:2.8.9',
            'org.apache.logging.log4j:log4j-core:2.17.2',
            // JAX-B dependencies for JDK 9+
            "jakarta.xml.bind:jakarta.xml.bind-api:2.3.3",
            "org.glassfish.jaxb:jaxb-runtime:2.3.3",
            'junit:junit:4.12',
    )
    testImplementation (
            'junit:junit:4.12',
            'org.mockito:mockito-all:1.10.19'
    )
}
```
When i add the log4j implementation i get this error. 
General error during conversion: Unsupported class file major version 61.

My gradle JVM is Gradle is Amazon Corretto Version 16.0.2

**Comment by umshreyas** [comment]
I guess the issue is due to me using gradle version 7.1.1 as compared to using 7.3.3 in the hello world example. 

I will upgrade my gradle version and hopefully that should resolve my build error.

Thanks a lot for your help. @mndeveci
