### ISSUE TITLE
API method to Activate AWS user-defined "cost allocation tags"

### ISSUE THREAD

**Issue by sindhu890** [aws/aws-sam-cli#3822]
There doesn't seem to be any way of activating the newly created tags by api/cli calls . So I still need to log into my payer account and manually click a button or two to activate the tags.

**Comment by moelasmar** [comment]
@sindhu890 .. could you please explain more what is the issue. Are these tags are added by SAM CLI tool?

**Comment by sindhu890** [comment]
Oh looks like I opened under different section.
