### ISSUE TITLE
Wrong debug message for the nested stacks

### ISSUE THREAD

**Issue by stavros-zavrakas** [aws/aws-sam-cli#3826]
### Description:
The debug message regarding the stacks when we start the `sam local start-api --debug` is wrong. The message should be:
0 stacks found in the template

but instead the we see this log message:
87 stacks found in the template

This behaves like that because the `sam_stack_provider.py` is printing the length of the resources rather than the length of the stacks.

### Steps to reproduce:
Start a local api with this:
`sam local start-api --debug`

### Observed result:
87 stacks found in the template

### Expected result:
0 stacks found in the template

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS BigSur
2. `sam --version`: 1.46.0
3. AWS region: N/A

`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
Thanks @stavros-zavrakas for raising this issue, and for your contribution

**Comment by mingkun2020** [comment]
Thanks @stavros-zavrakas for raising this issue and the pr LGTM!

**Comment by mndeveci** [comment]
This feature is been released with SAM CLI v1.48.0.
