### ISSUE TITLE
Github Action for `sam deploy` is marked complete without the execution of the command being completed

### ISSUE THREAD

**Issue by dalmia** [aws/aws-sam-cli#3843]
Hi there! 👋 

I'm trying to use SAM CLI as part of a Github Action to deploy my changes to a Production Environment. However, the run corresponding to `sam deploy` is being marked as complete even though the `sam deploy` command is still running (as shown in the image below).

<img width="758" alt="165531669-ca99a35e-90f2-4af0-9861-95adba43e1a0" src="https://user-images.githubusercontent.com/13185699/166910866-34d45fc5-9201-49f4-8b15-cbe29c4296c3.png">

When I run the same command locally, there are a bunch of other things that happen after the step where `sam deploy` command is being marked as complete in the image above. The image below shows a few of those steps.

<img width="869" alt="Screenshot 2022-04-27 at 7 11 28 PM" src="https://user-images.githubusercontent.com/13185699/165532192-9cef7dd2-2fe2-4955-b739-d9c31bbc84af.png">

Only after the command has been fully executed does the deployment actually get completed. So, in my case, even though the Github Action is being marked as succeeded, the deployment doesn't actually happen.

You can find one such run here: https://github.com/avantifellows/quiz-backend/runs/6194073101?check_suite_focus=true

Am I missing something?

**Comment by jfuss** [comment]
@dalmia I am not sure why that would be happening. We don't exit the command so the process should still be running. 

You setup looks sane to me.
1) Does this happen all the time?
2) Did this ever work in the past?

**Comment by dalmia** [comment]
Hey @jfuss. Thanks for responding and having a look.

1. Yes, it is happening all the time now.
2. Yes, [this](https://github.com/avantifellows/quiz-backend/runs/6193368442?check_suite_focus=true) is one such run.

Since it ran once before, I believe that it has to do with something on my side. But since no errors are being thrown, I am finding it hard to debug what has gone wrong.

Thanks again for all your help and your time!

**Comment by heretic1321** [comment]
Thanks a lot for raising this issue, I was also having the same issue but now its resolved, and I am getting some other issue now, 
![image](https://user-images.githubusercontent.com/97227277/227730726-5aaf6e6a-00ae-4059-90d7-7273741eefdf.png)

I have a hunch that I am not storing the Mongo Auth Credential secret in the right format which it should go by. Currently its been stored something like this - 

### MONGO_AUTH_CREDENTIALS
Value
"mongodb+srv://********************/?retryWrites=true&w=majority"

If anyone can help me know the correct format or any other issue for which I am getting the error would be really helpful

**Comment by prateek-logiciel** [comment]
@heretic1321 --parameter-overrides MongoAuthCredentials=${{ MONGO_AUTH_CREDENTIALS }}
