### ISSUE TITLE
Enable X-Ray tracing of API Gateway when sam init with Tracing option

### ISSUE THREAD

**Issue by Tak1wa** [aws/aws-sam-cli#3850]
### Describe your idea/feature/enhancement

Enable X-Ray tracing of API Gateway when sam init with Tracing option

### Proposal

I tried X-Ray Tracing. This is a great feature!  
Release 1.48.0 --Sam Init Support for XRay Tracing

This feature makes Globals --Functions --Tracing Active.  
Globals --Api --TracingEnabled is not set at all, but if it is also set, API Gateway X-Ray tracing will also be enabled.

**Comment by jfuss** [comment]
@Tak1wa Thanks for the issue. This sounds like a good idea and we could even expand it to Step Functions as well. 

The file that would need to be modified is https://github.com/aws/aws-sam-cli/blob/develop/samcli/lib/init/template_modifiers/xray_tracing_template_modifier.py.

We are happy to look at a PR for this addition.

**Comment by Tak1wa** [comment]
@jfuss 

Thank you for reply.

I am considering how to implement it.
Unfortunately, Step Functions doesn't seem to support the global section.
The base code is a mechanism for injecting parameters into the global section. Therefore, I think it is better to carefully consider whether to support Step Functions.

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html

**Comment by mndeveci** [comment]
This is been released with [SAM CLI v1.51.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.51.0)
