### ISSUE TITLE
Support publishing of SAM-CLI to Windows Package Manager

### ISSUE THREAD

**Issue by vedantmgoyal2009** [aws/aws-sam-cli#3863]
### Describe your idea/feature/enhancement

Windows now has an official package manager aka WinGet. There's a [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository maintained by the community and there, the SAM-CLI package is currently updated by the automation or moderators. Most of the times when automation is having issues or is under maintenance mode, it is left outdated unless someone manually looks at and updates the package manifests.

### Proposal

Add details of how to add this to the product.

Using a GitHub workflow which can auto-generate manifests and submit them at winget-pkgs repository through a PR. The PR will be approved by moderators and merged.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model): No

### Additional Details

There's already a pull request which adds an action that is triggered when a GitHub release (not a draft/pre-release) is published, and it automatically generates manifests for the new version and submits them at winget-pkgs repository using a personal access token (PAT). It can be re-opened and merged ;)

- https://github.com/aws/aws-sam-cli/pull/3858

cc @jfuss

**Comment by jfuss** [comment]
@vedantmgoyal2009 What does WinGet give us over what we already distribute with an MSI? Does WinGet have data on how often this package is used?

Typically, we do not use Github Workflow to publish artifacts and instead have our own system to do the upload and artifact generation. Which would require work on the team to build this.

**Comment by vedantmgoyal2009** [comment]
> What does WinGet give us over what we already distribute with an MSI?

WinGet is an official package manager for Windows, the same as `apt` for Linux and `yum` for RedHat Linux. It is an open-source project, and the source code of it can be found at [microsoft/winget-cli](https://github.com/microsoft/winget-cli).

> Does WinGet have data on how often this package is used?

I'm not an MS employee so I don't have access to telemetry data. You can ask about it from the maintainers of WinGet listed [here](https://github.com/microsoft/winget-pkgs/issues/15674#:~:text=Windows%20Package%20Manager%20administrators).

> Typically, we do not use Github Workflow to publish artifacts and instead have our own system to do the upload and artifact generation. Which would require work on the team to build this.

I don't know much about the internal build system you use to build the project, but if it can run GitHub workflows the same way GitHub runs, then you can go ahead.

BTW, the current workflow that the PR mentioned above adds to the repository does not need any modification to the build system. It automatically triggers as soon as a new GitHub **release** (not a draft/pre-release) is published and the action would create a PR at [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) to submit the manifests for new version.
