### ISSUE TITLE
Node 16 support

### ISSUE THREAD

**Issue by michaelbrewer** [aws/aws-sam-cli#3871]
### Describe your idea/feature/enhancement

I would like to provision AWS Lambda node 16 runtime

### Proposal

Add details of how to add this to the product.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

### Additional Details

- https://github.com/aws/aws-lambda-base-images/issues/14#issuecomment-1120864028

**Comment by michaelbrewer** [comment]
i see that it is already out :)  https://github.com/aws/aws-sam-cli/releases/tag/v1.49.0

**Comment by jfuss** [comment]
Already supported.

Closing
