### ISSUE TITLE
Feature request: ARM64 SAM CLI Binary

### ISSUE THREAD

**Issue by driverpt** [aws/aws-sam-cli#3908]
### Describe your idea/feature/enhancement
We require ARM64 build of `sam-cli`

Currently we just fetch the file from `https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip` and install it according to the instructions

### Proposal
Add an `aarch64` artifact so we can install on ARM Images

### Additional Details
We need to build GraalVM Image in `aarch64`, since GraalVM does not generate cross-platform code. And we want to deploy to Lambda using SAM CLI

**Comment by mingkun2020** [comment]
Thanks for the feature request! We have a [roadmap](https://github.com/aws/aws-sam-cli/wiki/SAM-CLI-Roadmap) here, but we also try to take in popular feature requests based on 👍🏽 from the community. We will be adding this to our intake for prioritization.

**Comment by bjonnh-work** [comment]
It would be useful for developers on Apple ARM hardware as well.

**Comment by qingchm** [comment]
@bjonnh-work Hi there I'm glad to inform you that ARM on Mac is now supported! In the release artifacts please find the pkg artifact related to ARM and install it following any of the options listed on https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html MacOS section. @driverpt I don't see why we shouldn't try to provide a native installer to Linux ARM either. So I will try to get this onto our agenda, based on the fact that we get some up-votes for this summed up here. Feel free to track this issue and engage me for any updates

**Comment by bjonnh-work** [comment]
Thank you @qingchm that's deeply appreciated.

**Comment by driverpt** [comment]
Hello @qingchm , thank you for all your efforts on this one. I have one extra request, sorry to be always asking, but, can you add a consistent install experience between x86 and arm? According to the documentation they are different

**Comment by qingchm** [comment]
@driverpt No worries also feel free to poke me on this! Can you explain for a bit how the installation experience differs between x86 and arm for you? If it's about the Mac system, I believe the installation experience would be the same as we provide native installers for both. On linux systems I do see the gap here as we already have native installers out for x86 but not yet for arm. Once the native installer is released for linux arm the documentation will be consistent! Let me know if there's anything for us to improve on before that gets implemented!

**Comment by metaskills** [comment]
I require a linux arm64 build. This is required for CI/CD pipelines and devcontainer features. We script the install [1] and I was hoping we could do what Microsoft does [2] with the AWS CLI.

1. https://github.com/customink/codespaces-features/tree/main/src/sam-cli
2. https://github.com/devcontainers/features/blob/main/src/aws-cli/install.sh#L122

IMO, this should have been done already. Not everyone has Python on their system when needing this tool. Was a huge disappointment to find this was not already available.

**Comment by teq0** [comment]
This feature request has been open for 18 months, any updates?

**Comment by hnnasit** [comment]
Hi all, native installer support for Linux Arm64 has been released in [SAM CLI 1.104.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.104.0). More details can be found in the [docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html). Resolving this issue!
