### ISSUE TITLE
sam build failing with gyp Err! find python

### ISSUE THREAD

**Issue by Krishman23** [aws/aws-sam-cli#3918]
I was able to do the node application with `npm install`, and create node_modules folder. But same application fails with below error when running `sam build`.

Building codeuri: /home/ec2-user/xslt-transform/xslt-transform runtime: nodejs14.x metadata: {} architecture: x86_64 functions: ['XsltTransformFunction']

Running NodejsNpmBuilder:NpmPack

Running NodejsNpmBuilder:CopyNpmrcAndLockfile

Running NodejsNpmBuilder:CopySource

Running NodejsNpmBuilder:NpmInstall

 

Build Failed

Error: NodejsNpmBuilder:NpmInstall - NPM Failed: npm WARN config production Use `--omit=dev` instead.

npm ERR! code 1

npm ERR! path /home/ec2-user/xslt-transform/.aws-sam/build/XsltTransformFunction/node_modules/java

npm ERR! command failed

npm ERR! command sh -c node-gyp rebuild

npm ERR! gyp ERR! find Python

npm ERR! gyp ERR! find Python checking Python explicitly set from command line or npm configuration

npm ERR! gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/lib64/python2.7"

npm ERR! gyp ERR! find Python - "/usr/lib64/python2.7" is not in PATH or produced an error

npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON

npm ERR! gyp ERR! find Python checking if "python3" can be used

npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error

npm ERR! gyp ERR! find Python checking if "python" can be used

npm ERR! gyp ERR! find Python - executable path is "/usr/bin/python"

npm ERR! gyp ERR! find Python - version is "2.7.18"

npm ERR! gyp ERR! find Python - version is 2.7.18 - should be >=3.6.0

npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED

npm ERR! gyp ERR! find Python

npm ERR! gyp ERR! find Python **********************************************************

npm ERR! gyp ERR! find Python You need to install the latest version of Python.

npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,

npm ERR! gyp ERR! find Python you can try one of the following options:

npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"

npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)

npm ERR! gyp ERR! find Python - Set the environment variable PYTHON

npm ERR! gyp ERR! find Python - Set the npm configuration variable python:

npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"

npm ERR! gyp ERR! find Python For more information consult the documentation at:

npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation

**Comment by mingkun2020** [comment]
Thanks @Krishman23 for reporting the issue, do you provide an simple example code and template for us to investigate?

**Comment by Krishman23** [comment]
Hi, 
I had created a git project for sample, 
https://github.com/Krishman23/xslt-transform
Above error was observed then I created new linux EC2 instance. 
When I run sam build, from windows:
 I get "Invalid ELF Header" while running the deployed application in lambda

**Comment by hawflau** [comment]
Hey @Krishman23, I couldn't replicate the exact error you got, but I got `sam build` ran successfully in my Amazon Linux 2 EC2 instance after I installed JDK and Development Tools/Build Tools. In your case, it seems Python is required (by node-gyp) but wasn't installed properly. Please see [here](https://www.npmjs.com/package/node-gyp) to check the prerequisite for node-gyp.

**Comment by sriram-mv** [comment]
I'm going ahead and closing this issue as per @hawflau's comment, Please feel free to comment if this is not the case.
