### ISSUE TITLE
"sam deploy" does not execute when --tags parameter is added

### ISSUE THREAD

**Issue by CloudAndContainer** [aws/aws-sam-cli#3926]
### Description:
This command deployed successfully, 
sam deploy --template-file target/sam.yaml --profile dev --region us-east-1 --stack-name api-stack --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --s3-bucket artifactory --s3-prefix sam --parameter-overrides Environment=test

This command is hung, 
sam deploy --template-file target/sam.yaml --profile dev --region us-east-1 --stack-name api-stack --tags repo=github.com/test-repo/api-stack  repo_owner=test  --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --s3-bucket dibh-artifactory --s3-prefix sam --parameter-overrides Environment=test

### Steps to reproduce:
Add --tags parameter to the existing template and the sam deploy gets struck.  The deployment is made through Bamboo CI pipeline. 

### Observed result:
Tried adding --debug flag to the sam deploy command, but there are no results. 

### Expected result:
Stack to be deployed without getting struck and tags are added to the stack. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
1. OS: 
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
3. `sam --version`: 1.48.0
4. AWS region: us-east-1

**Comment by moelasmar** [comment]
Hello,
I am not able to reproduce this issue on Mac or Ubuntu using a sample Hellow-world application. Can you share your project on github, so I can retry to reproduce the issue on it.

If not possible, please try to update SAM CLI to the latest version, and rerun the same deploy command with `--debug` option and share the logs with us.

**Comment by moelasmar** [comment]
can you share the logs with us ?

**Comment by CloudAndContainer** [comment]
There are no logs post the below command, (No timeouts or error messages, also upon checking the cloudtrail logs the api calls are also not even triggered)
 
sam deploy --template-file target/sam.yaml --profile dev --region us-east-1 --stack-name api-stack --tags repo=github.com/test-repo/api-stack repo_owner=test --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --s3-bucket dibh-artifactory --s3-prefix sam --parameter-overrides Environment=test

Still in progress and 
<img width="248" alt="image" src="https://user-images.githubusercontent.com/53657014/171457178-5ca5dbcb-8f9d-47d4-b5df-c92f32506504.png">

**Comment by moelasmar** [comment]
could you try to run the command as following:
```
sam deploy --template-file target/sam.yaml --profile dev --region us-east-1 --stack-name api-stack --tags "repo=github.com/test-repo/api-stack repo_owner=test" --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --s3-bucket dibh-artifactory --s3-prefix sam --parameter-overrides Environment=test
```

put the tags property value between `"`

**Comment by CloudAndContainer** [comment]
I left the build overnight for testing and I see the build got succeeded after 12 hours. 

<img width="276" alt="image" src="https://user-images.githubusercontent.com/53657014/171543562-d672271b-7d23-4b9d-b456-ff665bb0364d.png">

Is there any way to track why it took so long to deploy ? I tried to check Cloudtrail logs, but there were no API calls made when the build was in progress. I retriggered the build again to check if the second time deployment is faster, but its struck again.

**Comment by moelasmar** [comment]
from the snapshot you shared, it seems for a reason the command did not do anything for around 11 hours (or at least before it start communicating with AWS), which is very weird. I do not have a specific reason for that.
My understanding is when you try the same command without tags, everything went smooth. Can I ask you to try adding only one tag to the command, and see what will happen.

Also, could you please give us some info about the OS where this command got executed

**Comment by moelasmar** [comment]
Hello @CloudAndContainer, do you have any updates about this issue?

**Comment by CloudAndContainer** [comment]
Hi @moelasmar , When I try with one tag, the deployment is quick as expected. 

Command - sam deploy --template-file target/sam.yaml --profile dev --region us-east-1 --stack-name api-stack --tags repo_owner=test --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --s3-bucket dibh-artifactory --s3-prefix sam --parameter-overrides Environment=test

<img width="300" alt="image" src="https://user-images.githubusercontent.com/53657014/171977927-92f7d458-e143-41f9-afba-e50e4bdd53e3.png">

OS:
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by moelasmar** [comment]
thanks @CloudAndContainer .. did you try to put the 2 tags between double quotes. To be something like `--tags "repo=github.com/test-repo/api-stack repo_owner=test"`

**Comment by CloudAndContainer** [comment]
I tried the below command as you mentioned and it got struck deploying again, 

sam deploy --template-file target/sam.yaml --profile dev --region us-east-1 --stack-name api-stack --tags "repo=github.com/test-repo/api-stack repo_owner=test" --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --s3-bucket dibh-artifactory --s3-prefix sam --parameter-overrides Environment=test

**Comment by moelasmar** [comment]
@CloudAndContainer  .. We need to test the deploy command with `--debug` option, we need to know where exactly does SAM CLI freeze. The debugging logs may help us to detect the issue. Could you please run the following command
```
sam deploy --template-file target/sam.yaml --profile dev --region us-east-1 --stack-name api-stack --tags 'repo=github.com/test-repo/api-stack repo_owner=test' --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --s3-bucket dibh-artifactory --s3-prefix sam --parameter-overrides Environment=test --debug
```

**Comment by CloudAndContainer** [comment]
@moelasmar I already tried adding --debug flag to the sam deploy command, but there are no results, its still struck. I guess my issue is closely related to https://github.com/aws/aws-sam-cli/issues/1845.

I removed the long tag - _repo=github.com/test-repo/api-stack_ and replaced it with another short tag, it executed faster without any issues.

**Comment by jfuss** [comment]
@CloudAndContainer I am trying to debug locally now but I am seeing the right values getting passed to CloudFormation. I thought it might be our parser or a code error somewhere but so far, I haven't been able to get the result you are seeing.

**Comment by jfuss** [comment]
@CloudAndContainer For the instance you are running these commands on, what is the memory, CPU, etc on it? I wonder if our "regex parser" is consuming a lot of cycles because I can't repro the stalling or the combining of values you are seeing in https://github.com/aws/aws-sam-cli/issues/3926#issuecomment-1154138569. 

How are you installing SAM CLI as well? Do you know what python version you are using, if not using our linux installer?

**Comment by sriram-mv** [comment]
I can only see the stall happening if one provided a really long tag which did not follow the {A}={B} format. but your particular tags seem to go through fine on my testing as well.

**Comment by qingchm** [comment]
@CloudAndContainer To help you diagnose better it would be better if the full logs of the --debug run can be provided and if possible identify after which line it started getting stuck?

**Comment by jfuss** [comment]
Closing given no response
