### ISSUE TITLE
Bug: "DepLayer doesn't have any versions in remote"  -  layer versions / SyncFlow issue when using sam sync

### ISSUE THREAD

**Issue by Leigh-M** [aws/aws-sam-cli#3945]
After upgrading to SAM 1.51.0  -  I am seeing a stack error across all my stacks to do with missing dependency layer versions: 

After initially running it syncs initially.. then you make some changes which you expect to be uploaded to AWS but fails with:
    "Syncing Layer externalJobsLoadingAPIHandler44912949DepLayer..." 
    "DepLayer doesn't have any versions in remote"  

### Steps to reproduce:
`sam sync --watch --stack-name external-jobs-loader --region eu-west-1 --parameter-overrides EnvType=dev --debug`

### Observed result:
```
2022-06-07 16:31:00,657 | SyncFlow [Lambda Function externalJobsLoadingAPIHandler]: Finished
2022-06-07 16:31:00,710 | Finished syncing Lambda Function externalJobsLoadingAPIHandler.
2022-06-07 16:31:00,814 | SyncFlow [Layer externalJobsLoadingAPIHandler44912949DepLayer]: Setting Up
2022-06-07 16:31:00,820 | Syncing Layer externalJobsLoadingAPIHandler44912949DepLayer...
2022-06-07 16:31:01,121 | Code sync encountered an error.
Traceback (most recent call last):
  File "samcli/lib/sync/sync_flow_executor.py", line 335, in _sync_flow_execute_wrapper
  File "samcli/lib/sync/sync_flow.py", line 307, in execute
  File "samcli/lib/sync/flows/auto_dependency_layer_sync_flow.py", line 72, in set_up
samcli.lib.sync.exceptions.NoLayerVersionsFoundError: external-jobs-lodcdd4f9b-externalJobsLoadingAPI44912949-DepLayer doesn't have any versions in remote.
```

I did also see a new yellow warning:  "CodeTrigger not created as CodeUri or DefinitionUri is missing for externalJobsLoaderApi" - so there appears to be requirement for DefinitionUri  applied to an API provisioned in my template.yaml? 

But this dependency/ S3 URI should be controlled by SAM I understand.. ?

1. OS:   Ubuntu Linux 22.04
2. If using SAM CLI, `sam --version`:  1.51.0
3. AWS region:  eu-west-1

**Comment by mndeveci** [comment]
Thanks for reporting this issue @Leigh-M 

Can you provide us an example template that we can re-produce the issue?

In the meantime, you can also use `sam sync` with `--no-dependency-layer` flag, which won't create Auto Dependency Layer.

**Comment by Leigh-M** [comment]
I will try to put a minimal template.yaml together today yes. To clarify
(again) the issue is that in SAM v1.51.0 the auto dependency layer is not
being created (when not adding the —no-dependency-layer flag), but then SAM
tries to reference resources it expects to be in the auto dependency layer
and errors.

**Comment by mndeveci** [comment]
If you have no dependencies for your function, you might encounter this problem. Please let us know if your use case is something else.

In the meantime, we will be working on a change to fix this beahviour.

**Comment by Leigh-M** [comment]
Hi @mndeveci after 1.52 this appears to be running correctly, I'd need to do some more digging to understand it and reproduce the issue on 1.51 but OK to close for now - will re-open when/ if I can reproduce.

**Comment by chris-armstrong** [comment]
I'm seeing this bug on aws-sam-cli 1.52 on a function in a nested stack when it goes to update the function after a change.

```
Infra sync completed.
Syncing Lambda Function FinalisePolicyFunction...
Building codeuri: /Users/chris/dev/honeycomb/services/api/src/functions/policy-migration/finalise_policy runtime: nodejs14.x metadata: {'BuildMethod': 'esbuild', 'BuildProperties': {'SourceMap': True, 'External': ['chrome-aws-lambda'], 'Target': 'es2020', 'EntryPoints': ['index.ts'], 'Loader': ['.proto=text']}} architecture: x86_64 functions: ['FinalisePolicyFunction']
package.json file not found. Bundling source without dependencies.
Running NodejsNpmEsbuildBuilder:EsbuildBundle
Finished syncing Lambda Function FinalisePolicyFunction.
Syncing Layer FinalisePolicyFunctiond64df8afDepLayer...
Code sync encountered an error.
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/lib/sync/sync_flow_executor.py", line 335, in _sync_flow_execute_wrapper
    dependent_sync_flows = sync_flow.execute()
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/lib/sync/sync_flow.py", line 307, in execute
    self.set_up()
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/lib/sync/flows/auto_dependency_layer_sync_flow.py", line 72, in set_up
    raise NoLayerVersionsFoundError(layer_name)
samcli.lib.sync.exceptions.NoLayerVersionsFoundError: honey-api-review7360ba85-FinalisePolicyFunctiond64df8af-DepLayer doesn't have any versions in remote.
```

**Comment by mndeveci** [comment]
This is still a valid bug, if you have a function with no dependencies. For a workaround, please use `sam sync` with `--no-dependency-layer` option until the next version is shipped.

**Comment by andyeff** [comment]
Hi @mndeveci am I right in thinking that if I have a sam app with two lamdba functions, one of which has no dependencies, one that does - I should (for now) work on one at a time, using `sam sync` with `--no-dependency-layer` for the no-deps function, and then a regular sam sync for the function that does have a dep?

**Comment by andyeff** [comment]
Ah, disregard, it seems using `--no-dependency-layer` lets me work on both functions fine, there's no issue with the function that has a dependency included in it.

**Comment by mndeveci** [comment]
@andyeff for same stack, I would recommend using `--no-dependency-layer` for all of the functions there which I believe you are doing now.

**Comment by qingchm** [comment]
I believe that this is fixed in the new 1.53.0 release. Please have a try and if you still have any questions or issues feel free to re-open the issue!

**Comment by Leigh-M** [comment]
Thanks Mehmet. There are dependencies but there will be many projects that
require custom builds (eg webpack’ing React front-ends or if you require
more fine-grained control on build or for speed or existing ci-cd workflows)
devs may need other bundlers so CodeUri would be for eg: /dist/someHandler
rather than source code so it’s pre-built even if it appears there are no
dependencies - so I guess flexibility to accommodate when build step/
bundling already done. I’ll try to create a minimal project but I think you
understand the use-case/ issue already.

Thanks for looking into this I am sure there’ll be many projects that are
pre-built so just need /dist folder syncing correctly - perhaps there is
already a flag to set this in MetaData but it is adding complexity/ time on
config to require it.

**Comment by mndeveci** [comment]
@Leigh-M thanks for your comments and we will appreciate an example so that we can investigate the issue further. Once you have that ready, please feel free to open a new GH issue.
