### ISSUE TITLE
SAM Local API with hot reloading for CDK

### ISSUE THREAD

**Issue by AlessandroVol23** [aws/aws-sam-cli#4000]
Hi 👋🏼 

I am building a CDK app with API Gateway and one lambda function. The lambda function simply holds an Apollo GraphQL Server but that doesn't matter (I think). 

I want the opportunity to start the API Gateway locally and send events to the `localhost`. This is possible with `sam local start-api -t ./cdk.out/assembly-STACK/STACK.template.json`.

But hot reloading is not working since the CloudFormation template is not updating for each save. `cdk synth` takes too much time to be really feasible as a local dev experience. 

How are people currently solving this? 

I know that it is also an opportunity to simply use `cdk watch` and don't use localhost at all but unfortunately the time it takes to synthesize + update the lambda function is still to long. 

Any suggestions on how to solve that? 

Thanks ✌🏼

**Comment by moelasmar** [comment]
Hi @AlessandroVol23, 
Could you please let us know the Lambda function construct you are using in the CDK application?
Also, if it is possible, could you please share the synthesized template with us.

**Comment by jfuss** [comment]
Closing given the no response to follow up questions. If you come back to this, feel free to re-open or create a new issue and link (as we don't tend to monitor closed issues).
