### ISSUE TITLE
Bug: sam delete missing s3-prefix

### ISSUE THREAD

**Issue by iamnotadamkr** [aws/aws-sam-cli#4010]
### Description:
In the newest version of SAM CLI (1.52.0) it is still impossible to use s3-prefix parameter.

### Steps to reproduce:
sam delete --stack-name stack --s3-prefix folder --region us-east-1 --no-prompts

### Observed result:
Error: no such option: --s3-prefix
Error: Process completed with exit code 2.

### Expected result:
It was expected that with s3-prefix option set, related folder will be removed, but s3 bucket will be preserved.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: ubuntu-20.04, executed in github actions
2. `sam --version`: 1.52.0
3. AWS region: us-east-1

`Add --debug flag to command you are running`

**Comment by hawflau** [comment]
Hey, thanks for reporting. `--s3-prefix` for `sam delete` was not released in v1.52.0, as the original PR was reverted. In the v1.52.0 release note, the "What's Changed" section contains both the original [PR](#3915) and the [revert](#3954). Sorry for the confusion caused.

The new [PR](#3969) will be released in the upcoming SAM CLI version.
