### ISSUE TITLE
Bug: Incorrect required parameter combinations for `no-interactive` Flag

### ISSUE THREAD

**Issue by kmfischer3** [aws/aws-sam-cli#4012]
### Description:

There is a discrepancy between the required parameter combinations for the `no-interactive` flag and the SAM CLI output from using that flag.

According to the CLI output, one of the following parameter combinations must be used with the `no-interactive` flag:
- `--name` and `--location`
- `--name` `--package-type` and `--base-image`
- `--name` `--runtime` `--dependency-manager` and `--app-template`

However, when I use the first option, I still get an error:

```
$ sam init --no-interactive --name hello --location sam-init-template
Usage: sam init [OPTIONS]

Error: Missing parameter --dependency-manager
```

Strangely, even if I _do_ provide the requested flag, it's still not happy because then my flags don't match one of the accepted combinations:

```
$ sam init --no-interactive --name hello --location sam-init-template --dependency-manager npm
Error: You must not provide both the --location and --dependency-manager parameters.
...
```

### Steps to reproduce:

1. Start with a template (I'm using a cookiecutter template similar to [this](https://github.com/aws-samples/cookiecutter-aws-sam-python)) named `sam-init-template` in your current working directory
2. run `sam init --no-interactive --name hello --location sam-init-template`

### Observed result:

`Error: Missing parameter --dependency-manager`

### Expected result:

The CLI should accept the required parameter combination `--name` and `--location` without needing `--dependency-manager`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS Monterey 12.4
4. `sam --version`: 1.51.0
5. AWS region: N/A

`Add --debug flag to command you are running` 
N/A

**Comment by kmfischer3** [comment]
Hey @hawflau sorry for not being clear - I _want_ the `no-interactive` flag because I want the disable interactive prompting for the init parameters.

I'm trying to automatically test the `sam init` process for our custom template, so I don't want any prompts.

Thanks :)

**Comment by hawflau** [comment]
Right, it makes sense.

The limitation about `--no-interactive` and `--dependency-manager` was introduced in the #2463. I'm not sure if it was a miss or something. But I think we need to revisit and fix it.

**Comment by qingchm** [comment]
Hey @kmfischer3 does the solution suggested above help?

**Comment by torresxb1** [comment]
Closing as a workaround was provided. Team will track improving the clarity of the messaging.
