### ISSUE TITLE
[Feature Request] Integrate CodeBuild local agent

### ISSUE THREAD

**Issue by alexcasalboni** [aws/aws-sam-cli#402]
**Description:**

What about integrating the new [CodeBuild local agent](https://github.com/aws/aws-codebuild-docker-images) into sam-local? 

It could make it easier for a serverless developer to test/debug a buildspec file locally.

Since sam-local already requires Docker, it could also make it a bit more transparent so that you don't need to be a "Docker expert" at all.

**Suggested behaviour**:

```bash
sam build --image ruby:2.3.1
```

The command should take care of the following steps:

```bash
# build docker image
docker build -t aws/codebuild/ruby:2.3.1 .
# pull agent image
docker pull amazon/aws-codebuild-local:latest --disable-content-trust=false
# run buildspec
docker run -it -v /var/run/docker.sock:/var/run/docker.sock -e "IMAGE_NAME=aws/codebuild/ruby:2.3.1" -e "ARTIFACTS=/home/ec2-user/environment/artifacts" -e "SOURCE=/home/ec2-user/environment/sample-web-app" amazon/aws-codebuild-local
```

(more detailed instructions [here](https://aws.amazon.com/blogs/devops/announcing-local-build-support-for-aws-codebuild/))

**Comment by sanathkr** [comment]
This is a good idea! I will keep the issue open here to gather feedback.
