### ISSUE TITLE
AWS Serverless Application Model init error on Pycharm

### ISSUE THREAD

**Issue by utkucanaytac** [aws/aws-sam-cli#4028]
### Description:

trying to create a new AWS Serverless Application on Pycharm but i am getting this error:

Could not execute `sam init`!: [Cloning from https://github.com/aws/aws-sam-cli-app-templates (process may take a moment),
Error: Unstable state when updating repo. Check that you have permissions to create/delete files

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

Details:

OS:Windows 10 , x64
Version: Python 3.9, SAM CLI- 1.53.0
IDE: Pycharm 2022.1.3 Pro Edition
Git Version 2.37

`Add --debug flag to command you are running`

**Comment by hawflau** [comment]
Hi @utkucanaytac, as the error message suggested, could you please check if you have permission to the path that you want create the project?

Also, it might be worth checking if you have enabled long path in your Windows registry. See #3946 for details

**Comment by hawflau** [comment]
Could you also try the workaround mentioned [here](https://github.com/aws/aws-sam-cli/issues/1891#issuecomment-997204295)?

**Comment by utkucanaytac** [comment]
Thank you very much. Yes, the problem was with "AWS SAM" path.
I also added the solution in stackoverflow and referanced you guys! Thank you

Mentioned here : https://stackoverflow.com/questions/72827644/aws-serverless-application-model-init-error-on-pycharm/72842394#72842394

**Comment by hawflau** [comment]
Sounds good. I did a bit more investigation - it is required to opt in to remove the `MAX_PATH` limitation. Please follow [here](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#enable-long-paths-in-windows-10-version-1607-and-later) for the instructions.

Closing as this seems not an issue anymore. Please re-open if there's still any
