### ISSUE TITLE
Connect local Redis to SAM 1.53

### ISSUE THREAD

**Issue by MartynCastagno** [aws/aws-sam-cli#4042]
Hello, I'm learning to use lambda functions with AWS SAM and I am interested in connecting my service to Redis. My application is running on port 8080 and the database on 6379, but when I create my client and start the service, the terminal indicates that the connection is refused.

How could I get the connection to be established correctly?

I understand or have seen that you have to create a network, but I'm not using a container or anything (that I know of).

I execute as follows:
sam build --cached --beta-features && sam local start-api --port 8080

Redis: 
redis-server 
redis-cli (for authorize)

**Comment by mndeveci** [comment]
I've tried to re-produce your issue by trying to call a simple local web service. I've tried calling `localhost` or `127.0.0.1` but none of the succeeded. But, if you try to change the ip address to the one which your computer gets from your router, then it should work.

**Comment by moelasmar** [comment]
@MartynCastagno ... Could you please let us know if you still have this issue, or [this comment](https://github.com/aws/aws-sam-cli/issues/510#issuecomment-554687309) helps you to resolve it?

**Comment by jfuss** [comment]
Closing given no response
