### ISSUE TITLE
invalid bind mount spec : invalid mode: ro,delegated

### ISSUE THREAD

**Issue by ashish41588** [aws/aws-sam-cli#4046]
Description:
 Encountering the below error when trying to invoke lambda locally using 

- sam local invoke

docker.errors.APIError: 500 Server Error: Internal Server Error ("invalid bind mount spec "/c/Users/habsa9/vs-code-workspace/annuity-electronic-inbound/lambda:/var/task:ro,delegated": invalid mode: ro,delegated")

### Steps to reproduce:
Create a lambda fucntion template using 
- sam init
- create a lambda folder
- write your lambda handler inside lambda folder
- create the template.yml file accordingly 
- Run sam local invoke command and you will find below error

docker.errors.APIError: 500 Server Error: Internal Server Error ("invalid bind mount spec "/c/Users/habsa9/vs-code-workspace/annuity-electronic-inbound/lambda:/var/task:ro,delegated": invalid mode: ro,delegated")

### Observed result:
docker.errors.APIError: 500 Server Error: Internal Server Error ("invalid bind mount spec "/c/Users/habsa9/vs-code-workspace/annuity-electronic-inbound/lambda:/var/task:ro,delegated": invalid mode: ro,delegated")

### Expected result:
events should be triggered at lambda_handler function

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows
2. `sam --version`: SAM CLI, version 1.53.0
3. AWS region: N Virginia

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
This looks similar to https://github.com/aws/aws-sam-cli/issues/1151.

What docker version are you trying to run? From the other issue, looks like you might be running a very old version and therefore would need to update docker.

**Comment by ashish41588** [comment]
I am using below docker version 17.03.1 But as per #1151 it says this should work in all versions above dockerV17+

**Comment by jfuss** [comment]
@ashish41588 So this is coming from docker itself, not something we directly control. Can you update Docker and see if that resolves the issue? 

We should provide a better error message, at the very least.

**Comment by moelasmar** [comment]
@ashish41588 .. Did you try to update your Docker, Please let us know if it helps to resolve your issue or not.

**Comment by ashish41588** [comment]
Let me check and will update you

Thanks,
Ashish

**Comment by jfuss** [comment]
Closing given no response. Please re-open or create a new issue (closed issues are not tracked) if upgrading Docker did not solve the problem.
