### ISSUE TITLE
Bug: config file isn't found

### ISSUE THREAD

**Issue by ben-elsen** [aws/aws-sam-cli#4073]
### Description:
The sam sync --watch command doesn't pick up the samconfig.toml file and therefore the sync fails because he doesn't find the parameters. Also passing along the config file manualy doesn't work. He just ignores it or doesn't find the file.

### Steps to reproduce:
Have a repository with a samconfig.toml file, parameter_overrides option in it and some parameters defined in a template. Run 
`sam sync --watch --stack-name core-api-network-stack-dev -t sam.yml`

### Observed result:
See output file added as attachement.
[debug output.txt](https://github.com/aws/aws-sam-cli/files/9158025/debug.output.txt)

### Expected result:
Picking up the parameters from the config file. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: max OS Monterey 12.4
2. `sam --version`: 1.53.0
3. AWS region: eu-west-1

`Add --debug flag to command you are running`
[debug output.txt](https://github.com/aws/aws-sam-cli/files/9158025/debug.output.txt)

**Comment by qingchm** [comment]
Thanks for opening the issue, taking a look

**Comment by qingchm** [comment]
@ben-elsen Hi there I just confirmed that samconfig works fine with sync. With your original samconfig I would encourage you to add a new section like this:
```
[default.sync]
[default.sync.parameters]
stack_name = "samconfig-test"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "myFuncBucket='something'"
```
Note that the build/deploy configs and sync configs are different things. So I suspect that you were using the build/deploy configs and expected that to be read for sync. The mitigation here would be to have the sync configs set up. Let me know if you have any other questions!

**Comment by ben-elsen** [comment]
hi @qingchm thanks for pointing that out! Works like a charm now!
