### ISSUE TITLE
Sam bulid change all function in stack while using sam build with use container paramether

### ISSUE THREAD

**Issue by dzienki** [aws/aws-sam-cli#4084]
### Description:

I use my steps in jenkins to build and deploy lambda functions using sam CLI, when i use 
`sam build --parallel`
evrything is fine but when i use 
`sam build --parallel -u`
every image, not only changed are pushed to ECR and lambdas are function to this new ones. 
This bug causes a lot of trasch in ECR

### Expected result:

I expected that when i build functions using `-u` paramether not all fuction in stack will be puhsed and modified

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20
3. `sam --version`: SAM CLI, version 1.23.0
4. AWS region: eu-central-1

**Comment by sriram-mv** [comment]
Could you go into a bit more detail, what does your template look like? are you building image based lambda functions?

**Comment by dzienki** [comment]
`AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for SampleAwsImagesApi

Globals:
  Function:
    Timeout: 60
  Api:
    BinaryMediaTypes:
      - image~1*png
      - image~1*jpeg
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Origin, X-Requested-With, Content-Type, Accept, Authorization, authorizationToken'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod2
      Auth:
        # DefaultAuthorizer: MyLambdaTokenAuth
        Authorizers:
          MyLambdaTokenAuth:
            FunctionArn: !GetAtt AuthFunction.Arn
            Identity:
              Header: authorizationToken
              ReauthorizeEvery: 100
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Role: arn:aws:iam::***
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: MyLambdaTokenAuth
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hello_world
      DockerTag: lambda
  AddLogoFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Role: arn:aws:iam::****
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /addLogo
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: MyLambdaTokenAuth
    Metadata:
      Dockerfile: ./add_logo/Dockerfile
      DockerContext: ./
      DockerTag: lambda`

**Comment by jfuss** [comment]
@dzienki I would need to dig deeper but my recollection is that we rely on `docker` to decide if it needs a rebuild and we use a deterministic hash to see if the image was updated or needs to be uploaded.

Does this happen on every run? Or only going between using `-u`?

**Comment by dzienki** [comment]
@jfuss It starts when i change mu Jenkins pipeline using -u, when i remove it build without -u also deploy all images but the second one without -u works fine and modify only changed function

**Comment by mndeveci** [comment]
@dzienki apologies for a late response here, but if all of your functions are Image type (`PackageType: Image`) then you don't need to use `-u` (`--use-container`) parameter at all since your functions is basically a `Dockerfile` and a container will be build by docker. 

`-u` flag (building in container) is useful if you have a Zip type function (you don't need to setup language/SDK on host  machine and it is useful for some native dependencies).

**Comment by moelasmar** [comment]
Closing given no response. Please re-open or create a new issue if you still facing the same problem.
