### ISSUE TITLE
Node.js esbuild support for --main-fields properties

### ISSUE THREAD

**Issue by santiperone** [aws/aws-sam-cli#4093]
### Describe your idea/feature/enhancement

When running the beta features for esbuild, I noticed large bundle sizes for functions using aws-sdk v3 packages. 
After some further research, I found this thread: https://github.com/aws/aws-sdk-js-v3/issues/3023 which points out to specifying --main-fields=module,main when bundling with the sdk to allow for better tree shaking. This made my bundle go from:
![image](https://user-images.githubusercontent.com/69366194/182438259-3c59cd86-2c72-4f10-9f2d-757edc7be01b.png)
to:
![image](https://user-images.githubusercontent.com/69366194/182438291-733010ec-eb90-4ece-a411-2e98c21c42b6.png)

### Proposal

Add the ability to set this property in the template, to allow for lower sizes bundles. It could be added as an additional properti inside the "BuildProperties"

**Comment by jfuss** [comment]
@santiperone Thanks for the report. I connected with @mildaniel who is working on the ESBuild integration. I think this is an easy change for us to support.

**Comment by lucashuy** [comment]
Thanks for opening this suggestion! The `MainFields` property is now available in SAM CLI release 1.56.0 under the `BuildProperties` section. Please refer the documentation for more details: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build-typescript.html
