### ISSUE TITLE
无法使用‘sam init’创建模板

### ISSUE THREAD

**Issue by LeoProgrammer** [aws/aws-sam-cli#4100]
When I use sam init and select 'AWS Quick Start Templates', it prompts me 'Unstable state when updating repo. Check that you have permissions to create/delete files in C:\Users\patton.zhang\AppData\Roaming\AWS SAM directory or file an issue at https://github.com/aws/aws-sam-cli/issues'

**Comment by jfuss** [comment]
@LeoProgrammer Do you have permission to create/delete files at that location?

**Comment by qingchm** [comment]
Can you check on this to see if this is a windows [max path issue](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#enable-long-paths-in-windows-10-version-1607-and-later)? Also #4031 might contain some useful conversations that can unblock you @LeoProgrammer

**Comment by jfuss** [comment]
Closing given no response.
