### ISSUE TITLE
Feature request: Support pipeline template manifests in custom locations

### ISSUE THREAD

**Issue by kfr2** [aws/aws-sam-cli#4107]
### Describe your idea/feature/enhancement

It would be tremendously helpful if `sam pipeline init` would be able to parse a pipeline template manifest (like it does for https://github.com/aws/aws-sam-cli-pipeline-init-templates/blob/main/manifest.yaml) when passed a custom Git location. This would allow for users to store their various pipelines in one Git repository rather than having to maintain a large number of them.

### Proposal

If a user passes a custom Git location which does not contain a manifest, nothing changes and the operation proceeds like it currently does. However, if the Git location *does* contain a manifest, the user will be prompted to choose which pipeline to initialize based on the list contained within the document.

**Comment by jfuss** [comment]
@kfr2 Thanks for the issue and PR. Looks like the team is already reviewing it :)

**Comment by mildaniel** [comment]
A fix has been released in version 1.56.0 on 09/01. Closing this issue, please re-open if it persists.
