### ISSUE TITLE
Bug: sam sync does not take stack-name and region from samconfig.toml

### ISSUE THREAD

**Issue by kozmaz87** [aws/aws-sam-cli#4131]
### Description:

Even though --config-env is selected that defines --stack-name and --region those 2 parameters are required regardless. This makes automating anything using this tool just that bit more tedious one has to wrap the sync command into another script to fill in the parameters from the toml file. 

NOTE: I noticed that other commands do not define required=True at the --stack-name yet sync does. This also breaks sam cli's interface consistency.

### Steps to reproduce:

Create a configuration in the samconfig.toml file that defines region and stack-name
try `sam sync --config-env <env_name_here> --watch`

### Observed result:

It will bully you to provide --region and --stack-name even though those are provided in the toml file

Unfortunately I can't provide you with output because there is sensitive information in it in --debug mode unfortunately. Just try reproducing it.

### Expected result:

I expect sync to follow the rest of the command in the configuration selection parameters. Be consistent and DRY.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: SAM CLI, version 1.53.0
3. AWS region: eu-west-1

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
@kozmaz87 Can you provide an example of your `samconfig.toml`? Will help me reproduce what you are seeing without guessing at your setup.

> NOTE: I noticed that other commands do not define required=True at the --stack-name yet sync does. This also breaks sam cli's interface consistency.

Not sure I understand this. Other commands do require `--stack-name`, I.E: deploy, logs, delete. What each command requires also depends on what the command does. So it can be the case (with any option) that in one command an option is required but in another it is not.

**Comment by kozmaz87** [comment]
I will clean out the "sensitive"(not passwords but corporate stuff) from the config and the debug output and you will see that the stack_name does not get populated from the samconfig.toml file only in the sync command. Deploy populates it correctly and therefore the command line argument is not necessary. For the very same environment for the sync command the stack_name and region does not get populated from the toml file for some reason.

Once I cleaned it up I will post you a comment. Please bear with me, I will get to it eventually.

**Comment by lucashuy** [comment]
Hi, I am not able to reproduce your results with this `samconfig.toml` file:
```
$ cat samconfig.toml
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
[otherenv.sync]
[otherenv.sync.parameters]
stack_name = "py38-helloworld"
s3_bucket = <bucket>
s3_prefix = "py38-helloworld"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
```
```
sam sync --watch --config-env otherenv
```

Deploy uses the parameters under `[<env>.deploy]` while sync related commands use `[<env>.sync]`. Can you try adding `[<env>.sync]` and `[<env>.sync.parameters]` to your config file? If that does not work, are you able to provide a sanitized config file here for us to replicate?

**Comment by kozmaz87** [comment]
Aaaaah that is the reason... so the .deploy is why it ignores it... man, this was not obvious to me. I did not realize that the 2nd part corresponded to the command. I thought they just meant where the deployment is meant to be... I must have missed this bit in the docs.... Thank you. I will give it a try

**Comment by kozmaz87** [comment]
So do I have a way to make this DRY or do I have to repeat everything twice if I need something to be deployed but have the ability to be used with sync as well? Is there ever a case where you would want the 2 to be in separate regions?

**Comment by lucashuy** [comment]
With the `samconfig.toml`, you are able to specify global level (`[default.global.parameters]`) set of parameters that will be shared across different commands. So for the example case you mentioned, you can have your region, stack name and other parameters in at the global level. Then you can override parameters by providing the tables for each command and environment. More info about the config file can be found here:

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html

**Comment by kozmaz87** [comment]
Thanks for the hint... I have been using global defaults but that unfortunately would still require me to repeat the stack name twice and all the parameter overrides a deployment needs to function...

**Comment by lucashuy** [comment]
Thanks for raising your concerns. We are currently seeking feedback on configuring environments in SAM CLI, would you like to connect with [our product manager](https://twitter.com/praneetaprakash) to give some more details? Additionally t those reading, +1s will help us prioritize this feature.

**Comment by sriram-mv** [comment]
I would like to track this issue under https://github.com/aws/aws-sam-cli/issues/2253 as they share similar roots.

**Comment by oshaughnessy** [comment]
> Thanks for the hint... I have been using global defaults but that unfortunately would still require me to repeat the stack name twice and all the parameter overrides a deployment needs to function...

I found this issue while looking for reasons that my `default.global.parameters` seem like they need to be repeated in each config-env. E.g. if I pass `--config-env dev` to `sam build` or `sam deploy`, then I need to specify `stack_name` in my `dev.build.parameters` section of the samconfig file. Just defining it in `default.global.parameters` is not sufficient. Running the command in debug mode, I don't think the `default` parameters are being read at all. Is that intentional?
