### ISSUE TITLE
Error: Unstable state when updating repo. Check that you have permissions to create/delete files in C:\Users\{Name}\AppData\Roaming\AWS SAM directory or file an issue at https://github.com/aws/aws-sam-cli/issues

### ISSUE THREAD

**Issue by NoIdeawhatIamdoing123** [aws/aws-sam-cli#4143]
I do not want to use the directory mentioned, how do I change it to use something more appropriate?

**Comment by jfuss** [comment]
@NoIdeawhatIamdoing123 We do not give control to this. `AppData` location is common for applications (not just SAM CLI) to put data for the application on Windows and is not unique to us. To use `sam init` please check permissions in this location so SAM CLI and download, store, and delete the App Templates used.

**Comment by petro2050** [comment]
I have this issue as well. I ran VSCode as an administrator, but it still failed.

**Comment by petro2050** [comment]
looks like https://github.com/aws/aws-sam-cli/issues/4031#issuecomment-1183633630 solved the issue for me.

**Comment by sriram-mv** [comment]
Closing as this issue looks be to a duplicate of the other mentioned issue #4031
