### ISSUE TITLE
Bug: "disable rollback" message is unclear / deployment fails

### ISSUE THREAD

**Issue by JoshMcCullough** [aws/aws-sam-cli#4164]
### Description:

```
CloudFormation stack changeset
-----------------------------------------------------------------------------------------------------------------------------------------
Operation                          LogicalResourceId                  ResourceType                       Replacement                      
-----------------------------------------------------------------------------------------------------------------------------------------
* Modify                           FunctionEvery2HoursPermission      AWS::Lambda::Permission            True                             
* Modify                           FunctionEvery2Hours                AWS::Events::Rule                  True                             
* Modify                           Function                           AWS::Lambda::Function              False                            
-----------------------------------------------------------------------------------------------------------------------------------------

CloudFormation events from stack operations (refresh every 0.5 seconds)
-----------------------------------------------------------------------------------------------------------------------------------------
ResourceStatus                     ResourceType                       LogicalResourceId                  ResourceStatusReason             
-----------------------------------------------------------------------------------------------------------------------------------------
UPDATE_IN_PROGRESS                 AWS::Lambda::Function              Function                           -                                
UPDATE_COMPLETE                    AWS::Lambda::Function              Function                           -                                
UPDATE_FAILED                      AWS::Events::Rule                  FunctionEvery2Hours                Replacement type updates not     
                                                                                                         supported on stack with disable- 
                                                                                                         rollback.                        
UPDATE_IN_PROGRESS                 AWS::CloudFormation::Stack         pull-dcop-nvg                      Replacement type updates not     
                                                                                                         supported on stack with disable- 
                                                                                                         rollback.                        
UPDATE_ROLLBACK_COMPLETE           AWS::Events::Rule                  FunctionEvery2Hours                Rollback succeeded for the       
                                                                                                         failed resources.                
UPDATE_FAILED                      AWS::CloudFormation::Stack         pull-dcop-nvg                      The following resource(s) failed 
                                                                                                         to update:                       
                                                                                                         [FunctionEvery2Hours].           
-----------------------------------------------------------------------------------------------------------------------------------------
```

Note the message:

> Replacement type updates not supported on stack with disable-rollback.

As far as I know, I do not have disable-rollback specified/set. I've had the stack rollback during deployment many times, so I know that is/was working. I've tried supplying the CLI argument `--no-disable-rollback` and then `--disable-rollback`, thinking maybe the message was written backwards. But every time I get the same output.

### Steps to reproduce:
Unclear. Perhaps any changes which would require "replacement" of a resource?

### Observed result:
Error message is unclear / does not provide a solution, and deployment fails:

> Replacement type updates not supported on stack with disable-rollback.

### Expected result:
A clear error message, and/or for the deployment to succeed.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Manjaro Linux
2. `sam --version`: 1.55.0
3. AWS region: GovCloud

**Comment by jfuss** [comment]
@JoshMcCullough The error "Replacement type updates not supported on stack with disable-rollback." is not something SAM CLI controls and comes directly from the service. In your case, I think it is from CloudFormation. 

Does `aws cloudformation describe-stacks --stack-name <STACKNAME>` return that the stack has `DisableRollback` set to `True`?

**Comment by JoshMcCullough** [comment]
Sorry for the delay -- yes, `DisableRollback: true`. I don't quite follow what the message is indicating, though. I'll try updating my `samconfig.toml` to set `disable_rollback = false` and go from there. Thanks.

**Comment by mndeveci** [comment]
Resolving this issue now, please let us know if you are still experiencing it.

**Comment by JoshMcCullough** [comment]
Thanks!

**Comment by victornor** [comment]
I'm still experiencing this issue.
sam deploy gives me the error:

> Replacement type updates not supported on stack with disable-rollback.

This happens after modifying a AWS::Serverless::Function in my .yaml template.
Specifically after adding an  extra HttpApi resource to the Events

The deployed function looks like this:

> SomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: '2.0'
            Path: /v2/{proxy+}
            Method: ANY
        RootResource:
          PayloadFormatVersion: '2.0'
          Type: HttpApi
          Properties:
            Path: /v2
            Method: ANY

After changing to this (addition of a swagger route), i can no longer deploy.

> SomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: '2.0'
            Path: /v2/{proxy+}
            Method: ANY
        RootResource:
          PayloadFormatVersion: '2.0'
          Type: HttpApi
          Properties:
            Path: /v2
            Method: ANY
        SwaggerResource:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: '2.0'
            Path: /docs/{proxy+}
            Method: ANY

**Comment by TimeLord2010** [comment]
I'm also facing this
