### ISSUE TITLE
"PackageType" and its "Metadata" are not specified in the SAM spec

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-sam-cli#4223]
This issue was inspired by this question: https://github.com/aws/aws-lambda-base-images/issues/61

> where are the docs for the Metadata section?

I found https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build.html 

But the SAM CLI `Metadata` spec is not specified in in the SAM spec: https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md

`PackageType` also is not in that SAM spec document.

Why was `Metadata` used instead of formally extending the spec? This might create problems for validators (which affects LSP and other code authoring tools).  [Metadata](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html) can contain arbitrary data, but its contents are required for `PackageType: Image`?

**Comment by mndeveci** [comment]
I don't know the reason why `Metadata` was used, but I can try to explain why it is not part of the SAM Transform project at all.

These properties are only used within SAM CLI and they have no value on SAM Transform side. They are only used during `sam build` and it is not affecting any package or deploy step. It also won't create (or alter) any CFN resources. For that reason, these properties are not part of SAM Transform, but they are only used in SAM CLI to add additional information for function's build step.
