### ISSUE TITLE
Bug: Using SAM with Windows MINGW64 or Git Bash

### ISSUE THREAD

**Issue by ZachThomasAU** [aws/aws-sam-cli#4241]
### Description:
When a user uses the Windows installer, SAM is installed through a file titled **sam.cmd**, and that file's directory is added to PATH. This works fine if a Windows user is using either Powershell or cmd as their default/preferred terminal application, as both applications will read the input `sam --version` as `sam[.cmd] --version`. 

However if the user is using Git Bash, or some other bash terminal in windows, which I imagine is a pretty common occurrence for command line developers, you'll hit either a "command not found" or "No such file or directory" error, depending on your preferred application. To use SAM CLI a Bash user will need to instead run `sam.cmd --version` to get the desired result.

This is not always a feasible workaround - especially if users are accessing SAM CLI by running scripts designed for many team members who use Linux, Mac and Windows devices. Specifying the application to run SAM CLI, or scripts that use SAM CLI in is not always realistic, and I suppose in some cases not possible.

Given this, I would imagine it makes sense to instead install **sam.cmd** as a compiled executable **sam.exe**. This way, no matter what terminal application a Windows user uses, they can use the command `sam` to access the SAM CLI. This is, for example, the approach used by AWS CLI V2 to ensure Powershell, cmd and Bash Windows users can all use the same command `aws` to access the AWS CLI.

### Steps to reproduce:
- Install the AWS SAM CLI for Windows 64 bit (or, presumably, 32 Bit).
- Open a terminal using git bash.
- Run `sam --version`.

### Observed result:
```
bash: sam: command not found
```

### Expected result:
```
SAM CLI, version 1.57.0
```
(Or a newer version if you're checking this at a later date)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows
2. `sam --version`: 1.57.0
3. Use a Windows terminal application that is not either cmd or Powershell.

**Comment by sriram-mv** [comment]
Thanks for the report! Does adding an alias to sam.cmd help with mitigation, while we triage this interally.

**Comment by ZachThomasAU** [comment]
Yeah, of course, that's my current workaround for my local environment.

**Comment by sriram-mv** [comment]
I'm going to close this issue since this is tracked under: https://github.com/aws/aws-sam-cli/issues/3589
