### ISSUE TITLE
Bug: Sam CLI is uploading Typescript files instead of the esbuild compiled Javascript

### ISSUE THREAD

**Issue by MattBidewell** [aws/aws-sam-cli#4244]
### Description:

When using Typescript with EsBuild the Typescript is deployed to Lambda instead of the compiled JS.
(hopefully its something I've missed)

### Steps to reproduce:

- Clone [this example repo](https://github.com/MattBidewell/cloudformation-test) 
- Build the project
    - `sam build` 
    - This should build the project and put the compiled resources into the `.aws-sam` folder
    - Note the NodeFunc has compiled to minified JS. 
- Deploy the project
    - `sam deploy -t template.yaml --guided`
- Try test the NodeFunc and you should get the error - `"Error: Cannot find module 'app`
- Export the function to see that Lambda contains the Typescript code instead of the JS code.

### Observed result:

Lambda is consisting of the Typescript code instead of the Javascript code.

### Expected result:

I would expect the Javascript files to be uploaded instead of the Typescript code

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac 12.6
2. `sam --version`: SAM CLI, version 1.56.1
3. AWS region: eu-west-2

**Comment by sriram-mv** [comment]
From the steps listed, do you see if the same issues if you did `sam deploy --guided` alone, without having to specify the template.yaml. If the template.yaml is not specified it will pick up the `.aws-sam/build/template.yaml` directly.

**Comment by MattBidewell** [comment]
@sriram-mv hey! That deployed the compiled code. Thanks!

**Comment by MattBidewell** [comment]
I believe this was just the way I was using the tooling and as such I'm going to close the bug ticket.
