### ISSUE TITLE
Bug: sam local start-api doesn't recognize parameter_overrides in toml files

### ISSUE THREAD

**Issue by tunesmith** [aws/aws-sam-cli#4246]
### Description:
sam local start-api doesn't recognize parameter_overrides in toml files.

### Steps to reproduce:
This works:

`sam local start-api --parameter-overrides key1="val1" key2="val2"`

This doesn't work:

`sam local start-api --config-file sam-configs/qa.toml`

where sam-configs/qa.toml is:

```
version = 0.1

[default.deploy.parameters]
[...]
parameter_overrides = [
    "key1=val1",
    "key2=val2",
]
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`: 1.56.0
3. AWS region: us-east-1

**Comment by sriram-mv** [comment]
parameter_overrides="ParameterKey=Key,ParameterValue=Value ParameterKey=Key2,ParameterValue=Value2"

should be a format that works, I just dug this up from our integration tests.

**Comment by tunesmith** [comment]
@sriram-mv that syntax doesn't work either. Can you reopen the issue?

This doesn't work:

`sam local start-api --config-file sam-configs/qa.toml`

where sam-configs/qa.toml is:

```
version = 0.1

[default.deploy.parameters]
[...]
parameter_overrides="ParameterKey=Key,ParameterValue=Value ParameterKey=Key2,ParameterValue=Value2"
```

**Comment by tunesmith** [comment]
@sriram-mv Can we reopen this issue?

**Comment by tunesmith** [comment]
Re-created as https://github.com/aws/aws-sam-cli/issues/4348 since I don't think closed issues are being monitored.
