### ISSUE TITLE
how to check permission to create/delete in git? unstable repo

### ISSUE THREAD

**Issue by collegestudies** [aws/aws-sam-cli#4262]
Cloning from https://github.com/aws/aws-sam-cli-app-templates (process may take a moment)
Error: Unstable state when updating repo. Check that you have permissions to create/delete files in C:\Users\aakas\AppData\Roaming\AWS SAM directory or file an issue at https://github.com/aws/aws-sam-cli/issues

**Comment by sriram-mv** [comment]
I'm going to close this issue in favor of https://github.com/aws/aws-sam-cli/issues/4031. That issue has suggestions on how to get past errors mentioned here.
