### ISSUE TITLE
All upload skipped, but changeset created with modifications

### ISSUE THREAD

**Issue by roundrobinjp** [aws/aws-sam-cli#4266]
Hi
We are using SAM to deploy API gateway, Lambda functions and a Layer.
We are facing an issue while doing this.

Workflow:

1. Developer A modifies something
2. Developer A runs sam deploy
3. Developer A pushes his changes to git
4. Developer B pulls changes from git
5. Developer B runs sam deploy without changing anything

In the above step 5, Developer B runs sam deploy without changing anything.
While doing this he gets a number of messages like this (which is okay):

`File with same data already exists at aaaaa/bbbbbbbbbbbbbbbbbbbbb, skipping upload`

**Even though all uploads are skipped like this, still a changeset is created and shows a lot of changes.**

Why does this happen and how do we avoid such unnecessary changes to appear in the changeset?

**Comment by sriram-mv** [comment]
On `Developer B runs sam deploy without changing anything` , are they running a build before deploying?

**Comment by roundrobinjp** [comment]
> 

No. Neither Developer A, nor Developer B runs a build before deploying.

**Comment by sriram-mv** [comment]
Does that mean both developers are committing their built artifacts within .aws-sam within the repo?

**Comment by jfuss** [comment]
Closing due to age and no follow up response. 

If something is still off or confusing, please create a new issue.
