### ISSUE TITLE
Permission Denied on Windows for creating SAM app from cli

### ISSUE THREAD

**Issue by Jnana-kodierer** [aws/aws-sam-cli#4267]
Below is the error I'm facing while creating a lambda function using vscode and cli (both) :

Cloning from https://github.com/aws/aws-sam-cli-app-templates (process may take a moment)
Error: Unstable state when updating repo. Check that you have permissions to create/delete files in C:\Users\Colorbracket Office\AppData\Roaming\AWS SAM directory or file an issue at https://github.com/aws/aws-sam-cli/issues

![Screenshot (8)](https://user-images.githubusercontent.com/114011117/193056319-d9516269-0861-4aa8-84ee-625e2c6ab4dd.png)

**Comment by Jnana-kodierer** [comment]
Fixed the issue by typping the below commands in powershell admin mode: 
```
New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
-Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
```

**Comment by sriram-mv** [comment]
Closing this in favor of https://github.com/aws/aws-sam-cli/issues/4031 which talks about the same issue.
