### ISSUE TITLE
Feature request: esbuild / metadata support in Globals

### ISSUE THREAD

**Issue by sbol-coolblue** [aws/aws-sam-cli#4274]
### Describe your idea/feature/enhancement
A nice next step for esbuild would be allowing us to set up this metadata block only once, for example via the Globals section. This would allow us to set up esbuild only once, and share its configuration across all functions. Within a single stack, most likely all code would benefit from the same build pipeline.

Currently this fails:
```
[InvalidGlobalsSectionException('Globals', "'Metadata' is not a supported property of 'Function'. Must be one of the following values - ['Handler', 'Runtime', 'CodeUri', 'DeadLetterQueue', 'Description', 'MemorySize', 'Timeout', 'VpcConfig', 'Environment', 'Tags', 'Tracing', 'KmsKeyArn', 'AutoPublishAlias', 'Layers', 'DeploymentPreference', 'PermissionsBoundary', 'ReservedConcurrentExecutions', 'ProvisionedConcurrencyConfig', 'AssumeRolePolicyDocument', 'EventInvokeConfig', 'FileSystemConfigs', 'CodeSigningConfigArn', 'Architectures', 'EphemeralStorage', 'FunctionUrlConfig']")]
```

### Proposal
Add `Metadata` to the list of properties that `Globals::Function` supports and copy/merge it into the definition of `AWS::Serverless::Function` resources.

Things to consider:
1. This will require a change to the SAM Specification, as it will expand the list of fields that can be provided via the Globals section for an AWS::Serverless::Function.

### Additional Details
N/A

**Comment by mndeveci** [comment]
Thanks for your suggestion, I will be discussing with the team about taking this as a feature request.

**Comment by mndeveci** [comment]
Apologies for duplicate comments but this was already requested before in this issue: https://github.com/aws/aws-sam-cli/issues/3713

I am going to resolve this one for now, and we will be discussing with the team to provide a way to configure common esbuild properties for multiple functions.

Thanks!
