### ISSUE TITLE
Please update the hash function to SHA1 or pass in  `usedforsecurity=False` flag

### ISSUE THREAD

**Issue by ARMAAN7139** [aws/aws-sam-cli#4277]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/samcli/lib/package/packageable_resources.py", line 127, in export
    self.do_export(resource_id, resource_dict, parent_dir)
  File "/usr/local/lib/python3.9/site-packages/samcli/lib/package/packageable_resources.py", line 149, in do_export
    uploaded_url = upload_local_artifacts(
  File "/usr/local/lib/python3.9/site-packages/samcli/lib/package/utils.py", line 171, in upload_local_artifacts
    return zip_and_upload(local_path, uploader, extension)
  File "/usr/local/lib/python3.9/site-packages/samcli/lib/package/utils.py", line 188, in zip_and_upload
    with zip_folder(local_path) as (zip_file, md5_hash):
  File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/samcli/lib/package/utils.py", line 210, in zip_folder
    md5hash = dir_checksum(folder_path, followlinks=True)
  File "/usr/local/lib/python3.9/site-packages/samcli/lib/utils/hash.py", line 63, in dir_checksum
    hash_generator = hashlib.md5()
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS
Error: Unable to upload artifact src/ referenced by CodeUri parameter of resource.
[digital envelope routines: EVP_DigestInit_ex] disabled for FIPS

**Comment by sriram-mv** [comment]
Thanks for the issue! could you give us some more details such as the platform, version of aws sam cli. 

Where do you want us to pass in the flag? Additional details would be appreciated.

**Comment by ARMAAN7139** [comment]
I am using RedHat8 with SAM CLI, version 1.41.0

**Comment by mndeveci** [comment]
@ARMAAN7139 do you know if this will change the output of the hash function?

**Comment by ARMAAN7139** [comment]
I do not think so.

**Comment by jfuss** [comment]
I was just looking into this but we still support 3.7 and 3.8: https://github.com/aws/aws-sam-cli/blob/develop/setup.py#L57 So we either have to wait to drop them or do some python version checks. 

The md5 is not used for anything security related. It's used to compute a hash of the function code that we can rely on to allow us to only upload code that has changed to s3 (so optimization for caching).

@ARMAAN7139 is this something you are interested in contribution?

**Comment by qingchm** [comment]
As suggested above, hashlib.md5() method is only used for build a local build.toml file that helps us to compare between builds. We understand that md5 should not be used for security purposes and strictly follow that ;) @ARMAAN7139 And we are open to move away from this library to use another hash function for build.toml!

**Comment by DewaldDeJager** [comment]
Can this issue be closed since the PR was merged?

**Comment by mndeveci** [comment]
Thanks for the reminder @DewaldDeJager 

Since we updated md5 usage in this PR (https://github.com/aws/aws-sam-cli/pull/4812), I am resolving this issue. Please let us know if you still experience issues about this.
