### ISSUE TITLE
Bug: sam deploys Java sources instead of binaries

### ISSUE THREAD

**Issue by Meijuh** [aws/aws-sam-cli#4281]
### Description:
Applications that are built with Gradle are not deployed correctly; their sources are deployed instead of binaries.

### Steps to reproduce:
The problem is easily reproduced with sam-cli, with the hello-world example.

1. `sam init --app-template hello-world --name sam-tutorial --package-type Zip --runtime java11 --dependency-manager gradle`
2. `cd sam-tutorial`
3. `sam build`
4. `sam package --template-file template.yaml --output-template-file output.yaml --s3-bucket <bucket>`
5. `sam deploy --template-file output.yaml --stack-name sam-tutorial --capabilities CAPABILITY_IAM`

### Observed result:
1. Running the "HelloWorldFunction" lambda in the AWS console using a test event produces: `{
  "errorMessage": "Class not found: helloworld.App",
  "errorType": "java.lang.ClassNotFoundException"
}`.
2. "Actions | Export function" in the AWS console exports the hello-world Java sources, instead of the binaries.

### Expected result:
Triggering the lambda should work and not produce an exception.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Fedora Linux
2. `sam --version`: 1.58.0
3. AWS region: eu-west-1
4. `python --version`: Python 3.10.7
5. `java -version`: `openjdk version "11.0.16.1" 2022-08-12 LTS
OpenJDK Runtime Environment Corretto-11.0.16.9.1 (build 11.0.16.1+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.16.9.1 (build 11.0.16.1+9-LTS, mixed mode)`

Edit: the `sam package` command seems to upload the sources to the S3 bucket, not the binaries. Is that intended? Leaving out `sam package` and using `sam deploy --s3-bucket <bucket> ...` instead does solve the problem.

**Comment by sriram-mv** [comment]
On step 4. you are not reffering to the built artifacts. you are referring to the source.

changing 

```
sam package --template-file template.yaml --output-template-file output.yaml --s3-bucket <bucket>
```

to

```
sam package --output-template-file output.yaml --s3-bucket <bucket>
```

will ensure it works, since this will pick up the template located at .aws-sam/build/template.yaml instead.
