### ISSUE TITLE
`pywintypes-stubs` is now available through `types-pywin32`

### ISSUE THREAD

**Issue by Avasam** [aws/aws-sam-cli#4289]
Just a heads-up that `types-pywin32` has been added to typeshed, so you don't need to ignore `pywintypes` for mypy and pylint anymore.

**Comment by sriram-mv** [comment]
Thanks for the issue! would you be open for creating a PR on this? :)

**Comment by Avasam** [comment]
> Thanks for the issue! would you be open for creating a PR on this? :)

I had to fight with the CI a bit, but it's done: #4297

**Comment by jfuss** [comment]
Typically, we only close issues once released. Since this is for typing/developing and the PR is merged, going to close the issue now. 

Thanks for the issue and contribution @Avasam.
