### ISSUE TITLE
Bug: Windows version supports running "sam" only from CMD

### ISSUE THREAD

**Issue by jvuori** [aws/aws-sam-cli#4310]
### Description:
Windows installer (.msi) generates the following script: `C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd`. The directory is also added to PATH which makes it possible to run SAM CLI with just typing "sam". It works also when called from a CMD script.

The problem is that the script where "sam" is called is not necessarily always a CMD script. Git for Windows comes with sh.exe and bash.exe which makes it possible to run .sh scripts also on Windows. This is useful because the build and deployment scripts are often sh/bash scripts but the development environment can be Windows.

If you try to call "sam" from an sh script the interpreter doesn't recognize `sam.cmd` as executable ~~and even if it did, it wouldn't understand the CMD format~~.

SAM CLI Windows installer could generate also `sam` (without any extension) to support cases where sh or bash scripts are used.

The content could be for example:
```
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
"$SCRIPT_DIR/../runtime/python.exe" -m samcli "$@"
```

Alternatively `sam.cmd` could be `sam.exe` which would be interpreted as executable from both CMD and sh/bash script.

### Steps to reproduce:
1. Write a script with name `test.sh`:

```bash
#!/usr/bin/env bash
sam --version
```

2. Open Windows Command Prompt
3. Run the script:
```
sh test.sh
```

### Observed result:
```
C:\temp>sh test.sh
test.sh: line 2: sam: command not found
```

### Expected result:
```
C:\temp>sh test.sh
SAM CLI, version 1.60.0
```

### Additional environment details

1. OS: Windows
2. `sam --version`: SAM CLI, version 1.60.0
5. AWS region: N/A

**Comment by lucashuy** [comment]
Hi thanks for raising this issue. I can see that the AWSSAMCLI/bin folder is included in the `PATH` when using Git for Windows and I am able to reproduce what you have experienced (not being able to invoke `sam` in bash).

Can you try invoking with the full path instead as a workaround for now?
```
Administrator@WIN-5V2VS1FEF7M MINGW64 ~
$ /c/Program\ Files/Amazon/AWSSAMCLI/bin/sam.cmd --version
SAM CLI, version 1.56.0

Administrator@WIN-5V2VS1FEF7M MINGW64 ~
$ cat test.sh
#!/usr/bin/env bash
/c/Program\ Files/Amazon/AWSSAMCLI/bin/sam.cmd --version

Administrator@WIN-5V2VS1FEF7M MINGW64 ~
$ sh test.sh
SAM CLI, version 1.56.0
```

**Comment by jvuori** [comment]
Thanks for your response! Interestingly `sam.cmd --version` seems to be working even without the full path. Maybe a bit surprising but on the other hand makes sense.

However, the reason for raising this issue is compatibility in general. These .sh scripts are almost always written against Linux and executed for example as part of AWS CodeBuild job. So they shouldn't really depend on anything Windows specific.

So better workaround is to really write a script `sam` and put that in the same directory with `sam.cmd`. But based on this funny finding the content could be even simpler:
```
sam.cmd "$@"
```

**Comment by lucashuy** [comment]
This is something we can look into adding, thanks for your findings with `sam` and `sam.cmd`!

**Comment by sriram-mv** [comment]
Thanks for the discussion here, I'm going to close this issue in favor of https://github.com/aws/aws-sam-cli/issues/3589 to ensure there is no duplication.
