### ISSUE TITLE
Support Ref for CodeUri property.

### ISSUE THREAD

**Issue by kihtov23** [aws/aws-sam-cli#4314]
We are using sam template to describe our cloud formation stack deploy for Api gateway with lambdas.

What we have now in our SAM template for one lambda is:
  #CodeUri: ./artifacts/AbcProject.zip
  CodeUri:  ./src/providers/AbcProject/bin/Debug/netcoreapp2.1

So when we deploy to AWS - we need to use 
CodeUri: ./artifacts/AbcProject.zip
and when we run api locally we use:
CodeUri:  ./src/providers/AbcProject/bin/Debug/netcoreapp2.1

Thats why we need to comment/uncomments codeUri depending on whether we deploy or run locally.

Is there any way to use conditional CodeUri?

Expected result - use conditional CodeUri.

**Comment by jfuss** [comment]
This is a pretty old issue and might have before `sam build`.

Today what you would do is the following:
* Template would point to the source code
* `sam build` to build artifacts and create a template that points to those artifacts (you do not need to care about this template)
* `sam deploy` to push local artifacts to AWS and deploy the updated template

Closing but if there is still something missing in the workflow, please create a new Issue and we would be happy to discuss further.
