### ISSUE TITLE
HelloWorld example failed with CodeBuild error:An error occurred (AccessDenied) 

### ISSUE THREAD

**Issue by YuyuLin1003** [aws/aws-sam-cli#4358]
### Description:

For best,
Could someone help me about this issue? I try to build a helloworld lambda application with AWS SAM CLI. I follow the document to build 2 pipeline in AWS codepipeline: dev and prod. But I has a error in the codebuild phase: An error occurred (AccessDenied) when calling the AssumeRole operation

### Steps to reproduce:

just follow the instruction of AWS SAM document. I first init 2 pipelines: dev and prod. And I deploy the application by this command: 
sam deploy -t codepipeline.yaml --stack-name aws-sam-cli-managed-dev-pipeline-resources --capabilities=CAPABILITY_IAM --region eu-central-1

### Observed result:

An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::123456789:assumed-role/aws-sam-cli-managed-dev-pipel-CodeBuildServiceRole-Y46RJYKWLIRH/AWSCodeBuild-dc7ebf8d-087a-48cf-b406-d5b9134d40dd is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::123456789:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1ULJPW45KY4CV
--
282 |  
283 | [Container] 2022/10/29 09:20:57 Running command sam package --s3-bucket ${TESTING_ARTIFACT_BUCKET} --region ${TESTING_REGION} --output-template-file packaged-test.yaml
284 | Error: Unable to upload artifact HelloWorldFunction referenced by CodeUri parameter of HelloWorldFunction resource.
285 | An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: mac os
2. `sam --version`:SAM CLI, version 1.60.0
3. AWS region:eu-central-1

`Add --debug flag to command you are running`

**Comment by mndeveci** [comment]
Thanks for reporting this issue, can you provide which document or instruction that you follow to create these CodeBuild resources?

**Comment by YuyuLin1003** [comment]
Hello, here is the link for the document: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-generating-example-ci-cd-codepipeline.html

**Comment by xazhao** [comment]
Hello @YuyuLin1003 . I follows the document and it works fine on my side. So I guess there's something didn't go well when you bootstrapped.

It uses tag to setup trust relationship. Can you go to your AWS Console and check the role `aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1ULJPW45KY4CV`? The trust relationship there should have a block like below:
```
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "XXXXXXXXX"
            },
            "Action": "sts:AssumeRole",
            "Condition": {
                "StringEquals": {
                    "aws:PrincipalTag/Role": "aws-sam-pipeline-codebuild-service-role"
                }
            }
        }
```
If you go to CodeBuild role, you should also see a tag `aws-sam-pipeline-codebuild-service-role`.

Let me know if have any other questions.

**Comment by YuyuLin1003** [comment]
Hello @xazhao, many thanks for your information. I update the IAM policy but it still does not work. And I try to redo the process and I failed again. And I find that the name of IAM roles created by SAM are very weird and I can not understand the process well. I think there could be some problem on my AWS CLI configuration. So I decide to try another way to build my application, I try the CodeStar. So far it is ok. Thanks again for your help!

**Comment by xazhao** [comment]
Resolving this issue. Feel free to reopen it or create a new one if you have any other questions. Thanks!
