### ISSUE TITLE
Packaging: aws-sam-cli files conflict with the python "installer" package

### ISSUE THREAD

**Issue by javmorin** [aws/aws-sam-cli#4375]
I maintain a [package](https://aur.archlinux.org/packages/aws-sam-cli) for `aws-sam-cli` in Arch Linux. One of the users of the package notified me that it conflicted with the `python-installer` package (See refs [#1](https://pypi.org/project/installer/), [#2](https://archlinux.org/packages/community/any/python-installer/)) shipped by ArchLinux. I have confirmed this is the case, that aws-sam-cli does "ship" several files in an installer directory which when installed via pypi or setup.py could conflict with this other package.

I did some review of the source code, but I cannot see any direct calls to the `installer` files within `aws-sam-cli`. I am wondering if the `installer` files are necessary post-install, or if I can remove them as part of the packaging process.

Would appreciate clarification from the devs on this matter.

**Comment by hawflau** [comment]
Hey @javmorin, thanks for raising the issue.

>  I am wondering if the installer files are necessary post-install, or if I can remove them as part of the packaging process.
They are not. You can remove them as part of the packaging process

However, I'm curious why it only happened recently. It looks like the `installer` library has existed for a while.

**Comment by javmorin** [comment]
> They are not. You can remove them as part of the packaging process
Good to know, thanks! Barring other feedback, I will look to do this.

> However, I'm curious why it only happened recently. It looks like the `installer` library has existed for a while.
I think it was only noticed recently as I don't think many people install the `python-installer` package (that's a guess, I have no visibility to install #'s). Those files have been present in the repo for some time, but on my personal machine I didn't have the conflicting page installed (either directly or indirectly). 

I do think in the case of a system install via PyPi, this could lead to silent corruption as files are placed outside of the samcli directory, possibly overwriting existing files. I wonder if it's possible to alter the setup/install mechanism of `aws-sam-cli` to not install these files?

**Comment by hawflau** [comment]
I checked with some team members. It seems like we can exclude "installers" in setup.py on this line:
https://github.com/aws/aws-sam-cli/blob/develop/setup.py#L54

But in general, we advise installing SAM CLI in an isolated environment (e.g. in a virtual environment), pretty much like how it's installed through our installer binary. This reduces the chance of having conflicting dependencies. Is there any chance you can explore in updating your package to install AWS SAM CLI in an isolated env?

**Comment by javmorin** [comment]
I appreciate that is the preference on your teams side. The general preference on Arch is to not set up virtual envs for "normal" packages. There is a "binary" package as well which does what you suggest and installs your provided zip file, but some user (myself included) try to avoid "binary" packages to avoid duplicate code (20M install vs 181M install as well).

I do think that given the package is published on PyPi, that it should be a good citizen to other packages installed that way. Given the level of effort for the "fix", it seems a low-risk and easy win; though that is for your team to decide.

**Comment by hawflau** [comment]
We've merged #4389 to not include the "installer" directory. This change will be out in next release.

**Comment by mndeveci** [comment]
Changes have been released with [SAM CLI v1.62.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.62.0)
