### ISSUE TITLE
Bug: Error cloning the template.

### ISSUE THREAD

**Issue by crystalwee** [aws/aws-sam-cli#4403]
Environment: windows
![image](https://user-images.githubusercontent.com/1115675/201236231-4d2e3060-e1b4-4d9d-914c-d0b077030da2.png)

**Comment by mndeveci** [comment]
Thanks for reporting this issue @crystalwee ,

I've tried but couldn't reproduce this issue on a windows machine.

Please make sure that you have long path settings configured for your machine. You can read more about it here: https://github.com/aws/aws-sam-cli/issues/4031#issuecomment-1173147840

Please let us know if you are still experiencing this issue.

Thanks!

**Comment by crystalwee** [comment]
Hello Mehmet,
Thank you for your prompt reply.It works after I changed the registry key value LongPathsEnabled to 1.

Regards,Crystal

    On Friday, 11 November 2022 at 11:56:24 am GMT+11, Mehmet Nuri Deveci ***@***.***> wrote:  
 
 


Thanks for reporting this issue @crystalwee ,

I've tried but couldn't reproduce this issue on a windows machine.

Please make sure that you have long path settings configured for your machine. You can read more about it here: #4031 (comment)

Please let us know if you are still experiencing this issue.

Thanks!

**Comment by crystalwee** [comment]
Issue resolved.
Change the registry key before run the "sam init" command.
The registry key Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled (Type: REG_DWORD) must exist and be set to 1.
