### ISSUE TITLE
`sam sync` does not read values from samconfig.toml file

### ISSUE THREAD

**Issue by ljacobsson** [aws/aws-sam-cli#4409]
If I run `sam sync --config-file samconfig.toml` I get the following output:

```
$ sam sync --config-file samconfig.toml 
Usage: sam sync [OPTIONS]
Try 'sam sync -h' for help.

Error: Missing option '--stack-name'.
```

If I run `sam sync -h`, I get:
```
$ sam sync --code --watch --stack-name {stack}

Options:
  --config-env TEXT               The environment name specifying the default
                                  parameter values in the configuration file
                                  to use. Its default value is 'default'. For
                                  more information about configuration files,
                                  see: https://docs.aws.amazon.com/serverless-
                                  application-
                                  model/latest/developerguide/serverless-sam-
                                  cli-config.html.
  --config-file TEXT              The path and file name of the configuration
                                  file containing default parameter values to
                                  use. Its default value is 'samconfig.toml'
                                  in project directory. For more information
                                  about configuration files, see:
                                  https://docs.aws.amazon.com/serverless-
                                  application-
                                  model/latest/developerguide/serverless-sam-
                                  cli-config.html.
[...]
```

The expected behaviour is that it should pick up the stack name from the config file.

**Comment by mndeveci** [comment]
Thanks for reporting this issue, can you share your `samconfig.toml` file that you are using with this project? `stack_name` parameter should be configured in that file. There are 2 options;

- A global configuration for any parameter;

```
version=0.1
[default.global.parameters]
stack_name = "my-stack"
```

- Configuration specific to command itself;
```
version=0.1
[default.sync.parameters]
stack_name = "my-stack"
```

**Comment by qingchm** [comment]
Hi @ljacobsson this is expected behaviour as sam sync will not share configs with other commands such as sam deploy. If you are running sync with a samconfig file that specifies deploy configs, please replicate the same settings in a section for sync as suggested above! Sorry for the confusion but this is not a bug, we cannot by default use configs from other commands!

**Comment by jghaines** [comment]
[default.sync] parameters are also ignored and need to be replicated across [_env_.sync] blocks. What a brain-dead limitation.

**Comment by mndeveci** [comment]
@jghaines let's make sure we are following our community guidelines, I've removed part of your comment which was offensive.

For your feedback, there is an open feature request in the backlog which you can see it from here; https://github.com/aws/aws-sam-cli/issues/3010
