### ISSUE TITLE
SAM unable to find python.exe after SAM version upgrade

### ISSUE THREAD

**Issue by tomwaldnz** [aws/aws-sam-cli#4412]
### Description:
After an  upgrade from SAM version (about) v1.40.0 to v1.62.0 I receive the error message below when I try to use AWS SAM. I've been using SAM successfully for a couple of years.

Fatal error in launcher: Unable to create process using '"c:\users\containeradministrator\appdata\local\temp\tmpx0xr0ddm\runtime\python.exe"  "C:\Program Files\Amazon\AWSSAMCLI\runtime\Scripts\sam.exe" ': The system cannot find the file specified.

I have tried:

- uninstalling AWS CLI v2 and AWS SAM, rebooting, reinstalling both, rebooting again.
- upgrading docker desktop, uninstalling docker desktop, reinstalling docker desktop
- Installing AWS SAM version 1.40.0, 1.46.0, 1.55,0, 1.61.0

I've never had a c:\users\containeradministrator folder, and there's no reference to it anywhere I can see.

### Steps to reproduce:

I'm not sure this is reproducable. On my own PC Windows 10-64 22H2 it works fine when I do the upgrade.

- Upgrade to the latest version of SAM
- Restart PC
- Run AWS SAM: "sam"

I expect this will work on most computers and that it's something odd going on.

### Observed result:

sam --debug
Fatal error in launcher: Unable to create process using '"c:\users\containeradministrator\appdata\local\temp\tmpo6grtwiq\runtime\python.exe"  "C:\Program Files\Amazon\AWSSAMCLI\runtime\Scripts\sam.exe" --debug': The system cannot find the file specified.

### Expected result:

SAM to work

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 Enterprise 24 bit 21H2, OS Build 19044.2130
2. `sam --version`: (gives the error above but it's 1.62.0)
3. AWS region:  ap-southeast-2
4. 'aws --version': aws-cli/2.8.12 Python/3.9.11 Windows/10 exe/AMD64 prompt/off
5. 'python --version': Python 3.9.13

`Add --debug flag to command you are running`

**Comment by tomwaldnz** [comment]
I have found a workaround, which is to uninstall python from a sensible location and install it into the location SAM is looking for it (copied below). Something is not right thought, this shouldn't be necessary. I don't believe that there was any reference to that location on my computer before this happened - the older version of SAM was working just fine. SAM works fine on my home PC though, so it's an unusual problem.

`c:\users\containeradministrator\appdata\local\temp\tmpx0xr0ddm\runtime\python.exe`

**Comment by MrCloudston** [comment]
Good Morning,
You should be able to resolve this issue by checking "Environment Variables" and updating the PATH.

1. Locate Python installation folder
2. Go to System Properties > Advanced System Settings
3. Select Environment Variables
4. Double Click Path, Look for your Python Directory
5.  Check C:\.....\PythonX and C:\....\PythonX\Scripts

I do not have SAM listed (Win 11, 22H2) but I have Python listed there, I would suspect that you have the C:\Users\ContainerAdministrator\....... in there over the accurate path, change for SAM paths there as well.

Hopefully this will resolve your issue.
Enjoy the day,

**Comment by mildaniel** [comment]
Thanks @MrCloudston for providing the explanation. 
The AWS SAM CLI doesn't have any notion of `c:\users\containeradministrator`, it simply looks for the Python executable in the configured directory. In this case, it looks like there might be a misconfiguration there as @MrCloudston mentioned.

**Comment by tomwaldnz** [comment]
I agree it's probably computer specific. I carefully checked the path and it didn't contain that folder when this problem was occurring. The path does that now because I had to create that folder and install Python there, plus update the PYTHONHOME environment variable. I will uninstall everything, triple check the path, and install Python back in the standard location. I bet it'll work when I do that (again), because of Murphy's law.

What else could cause sam.exe to look for a python executable in that random folder?

The way I got this working was to install Python to that weird folder then run "pip install aws-sam-cli". I suspect it's actually using sam.exe from my Python scripts folder now rather than the version from the AWS installer.

I'll report back when I've played around a bit more. I might have time to do that tomorrow.

**Comment by tomwaldnz** [comment]
I removed python from my system did a reinstall of AWS CLI and AWS SAM, from the AWS provided installers. Here's what I found.


**Fresh Install**
Fresh install of SAM from AWS Windows package ( https://github.com/aws/aws-sam-cli/releases )
```
C:\Users\Tim>set PYTHONHOME
Environment variable PYTHONHOME not defined

C:\Users\Tim>set PATH
Path=C:\Program Files\Amazon\AWSSAMCLI\runtime\Scripts;C:\Tools\jdk-18.0.1.1\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Go\bin;C:\Tools\OpenSSL-3.0.3\bin;C:\Program Files\Git\cmd;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Amazon\AWSSAMCLI\bin\;C:\Users\Tim\AppData\Local\Microsoft\WindowsApps;C:\Documents\tools\scripts;C:\Users\Tim\go\bin;C:\Users\Tim\AppData\Roaming\npm;C:\Tools\OracleJDeveloper\oracle_common\bin;C:\Documents\tools\oracle_sqlplus;C:\Program Files\Amazon\AWSSAMCLI\runtime\Scripts;

C:\Users\Tim>sam
Fatal error in launcher: Unable to create process using '"c:\users\containeradministrator\appdata\local\temp\tmp4b4093hu\runtime\python.exe"  "C:\Program Files\Amazon\AWSSAMCLI\runtime\Scripts\sam.exe" ': The system cannot find the file specified.
```

**Change PATH**
I noticed that SAM installer installs python.exe, but doesn't put it into the Windows path. I put it on the Windows path

```
set PATH
Path=C:\Program Files\Amazon\AWSSAMCLI\runtime\Scripts;C:\Tools\jdk-18.0.1.1\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Go\bin;C:\Tools\OpenSSL-3.0.3\bin;C:\Program Files\Git\cmd;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Amazon\AWSSAMCLI\bin\;C:\Program Files\Amazon\AWSSAMCLI\runtime;C:\Users\Tim\AppData\Local\Microsoft\WindowsApps;C:\Documents\tools\scripts;C:\Users\Tim\go\bin;C:\Users\Tim\AppData\Roaming\npm;C:\Tools\OracleJDeveloper\oracle_common\bin;C:\Documents\tools\oracle_sqlplus;C:\Program Files\Amazon\AWSSAMCLI\runtime\Scripts;


C:\Users\Tim>python --version
Python 3.8.8

C:\Users\Tim>sam
Fatal error in launcher: Unable to create process using '"c:\users\containeradministrator\appdata\local\temp\tmp4b4093hu\runtime\python.exe"  "C:\Program Files\Amazon\AWSSAMCLI\runtime\Scripts\sam.exe" ': The system cannot find the file specified.
```



**PIP Install**
I removed the deployment of SAM made with the AWS installer, installed Python 3.9.13 with its installer, and installed sam with pip.

```
pip install aws-sam-cli

C:\Users\Tim>python --version
Python 3.9.13

C:\Users\Tim>sam --version
SAM CLI, version 1.64.0

```

Something screwy is going on.

**Comment by tomwaldnz** [comment]
This is a weird issue that was probably environmental. I've closed the issue, but it could be re-opened if it happened for anyone else.

**Comment by madhakuday** [comment]
Test Data For React App

**Comment by FrederickEskens** [comment]
I had the exact same issue. Uninstalling the SAM CLI done with the AWS installer and then installing it with pip fixed it for me as well, thank you!
