### ISSUE TITLE
[ERROR]Lambdas Handler Runtime.ImportModuleError: Unable to import module

### ISSUE THREAD

**Issue by GustaveDjoutsop** [aws/aws-sam-cli#4415]
sam issue:

Hello SAM-LAMBDAS  teams
I have been running SAM in container
and facing some intersting issue with the Runtime.

The Dockerfile
`FROM python:3.8
WORKDIR /app
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN python3.8 get-pip.py --user
RUN mkdir python3
RUN python3.8 -m pip install pandas -t python3/
RUN pip3 install awscli
RUN pip3 install aws-sam-cli`

The docker-compose file
`version: '3.6'
services:
  sam:
    build: .
    environment:
      - TZ=Etc/GMT
      - SAM_CLI_TELEMETRY=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ${PWD}:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app

    command: sam local invoke HelloWorldFunction --docker-network containerized-aws-sam_backend --container-host host.docker.internal --debug

    ports:
      - "3000:3000"
    networks:
      - "backend"

networks:
  backend:
`
Project structure:
![image](https://user-images.githubusercontent.com/33835451/201942853-8574ea06-fb4e-4a7d-8241-42be599c7509.png)

After docker-compose build and up I am getting following error:
`Recreating containerized-aws-sam_sam_1 ... done
Attaching to containerized-aws-sam_sam_1
sam_1  | 2022-11-15 14:12:09,735 | Config file location: /app/samconfig.toml
sam_1  | 2022-11-15 14:12:09,736 | Config file '/app/samconfig.toml' does not exist
sam_1  | 2022-11-15 14:12:09,748 | Using SAM Template at /app/template.yaml
sam_1  | 2022-11-15 14:12:09,784 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
sam_1  | 2022-11-15 14:12:09,784 | Using config file: samconfig.toml, config environment: default
sam_1  | 2022-11-15 14:12:09,784 | Expand command line arguments to:
sam_1  | 2022-11-15 14:12:09,784 | --template_file=/app/template.yaml --docker_network=containerized-aws-sam_backend --container_host=host.docker.internal --function_logical_id=HelloWorldFunction --no_event --layer_cache_basedir=/ro
ot/.aws-sam/layers-pkg --container_host_interface=127.0.0.1
sam_1  | 2022-11-15 14:12:09,784 | local invoke command is called
sam_1  | 2022-11-15 14:12:09,793 | No Parameters detected in the template
sam_1  | 2022-11-15 14:12:09,817 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
sam_1  | 2022-11-15 14:12:09,817 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
sam_1  | 2022-11-15 14:12:09,837 | Found Serverless function with name='HelloWorldFunction' and CodeUri='.'
sam_1  | 2022-11-15 14:12:09,850 | Found one Lambda function with name 'HelloWorldFunction'
sam_1  | 2022-11-15 14:12:09,850 | Invoking app.lambda_handler (python3.7)
sam_1  | 2022-11-15 14:12:09,850 | No environment variables found for function 'HelloWorldFunction'
sam_1  | 2022-11-15 14:12:09,850 | Loading AWS credentials from session with profile 'None'
sam_1  | 2022-11-15 14:12:09,880 | Resolving code path. Cwd=/app, CodeUri=/app
sam_1  | 2022-11-15 14:12:09,881 | Resolved absolute path to code is /app
sam_1  | 2022-11-15 14:12:09,881 | Code /app is not a zip/jar file
sam_1  | 2022-11-15 14:12:09,899 | Skip pulling image and use local one: public.ecr.aws/sam/emulation-python3.7:rapid-1.63.0-x86_64.
sam_1  |
sam_1  | 2022-11-15 14:12:09,899 | Mounting /app as /var/task:ro,delegated inside runtime container
sam_1  | 2022-11-15 14:12:12,610 | Starting a timer for 30 seconds for function 'HelloWorldFunction'
sam_1  | START RequestId: f97e56e9-1b90-4d68-b076-7370e06ab40a Version: $LATEST
Traceback (most recent call last):uleError: Unable to import module 'app': No module named 'app'
sam_1  | END RequestId: f97e56e9-1b90-4d68-b076-7370e06ab40a
sam_1  | REPORT RequestId: f97e56e9-1b90-4d68-b076-7370e06ab40a Init Duration: 0.21 ms  Duration: 87.30 ms      Billed Duration: 88 ms  Memory Size: 128 MB     Max Memory Used: 128 MB
sam_1  | {"errorMessage": "Unable to import module 'app': No module named 'app'", "errorType": "Runtime.ImportModuleError", "stackTrace": []}2022-11-15 14:12:13,618 | Cleaning all decompressed code dirs
sam_1  | 2022-11-15 14:12:13,711 | Installed version 1.63.0, current version 1.63.0
sam_1  | 2022-11-15 14:12:13,715 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics

`
This is the template.yaml

`AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  containerized-aws-sam
  Sample SAM Template for containerized-aws-sam

Globals:
  Function:
    Timeout: 30

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: . #hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7

      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get
`

**Comment by mildaniel** [comment]
Hey @GustaveDjoutsop, some of the formatting is a little hard to read but I went ahead and tried to reproduce your issue with a minimal app and was able to successfully invoke it.
Steps:
1. Created the following app
```
├── Dockerfile
├── app.py
├── docker-compose.yaml
└── template.yaml
```
2. Used an identical Dockerfile and template.yaml as the ones you provided.
3. Created a simple handler that looks like 
```
def lambda_handler(event, context):
    return {
        "status": 200,
        "body": "{'hello': 'world'}"
    }
```
4. A `docker-compose.yaml` that looks like
```
version: '3.6'
services:
  sam:
    build: .
    environment:
      - TZ=Etc/GMT
      - SAM_CLI_TELEMETRY=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ${PWD}:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    ports:
      - "3000:3000"

networks: 
  backend:
    driver: bridge
```
5. Run `docker-compose up --build -d`
6. Run `sam local invoke HelloWorldFunction --docker-network {PROJECT_NAME}_backend`
Output:
```
Invoking app.lambda_handler (python3.7)
Skip pulling image and use local one: public.ecr.aws/sam/emulation-python3.7:rapid-1.61.0-x86_64.

Mounting /Users/mladan/ws/test-issue/docker-compose-project as /var/task:ro,delegated inside runtime container
START RequestId: 3abd000d-ac80-4ea2-95f9-a07dfd035aa1 Version: $LATEST
END RequestId: 3abd000d-ac80-4ea2-95f9-a07dfd035aa1
REPORT RequestId: 3abd000d-ac80-4ea2-95f9-a07dfd035aa1	Init Duration: 0.32 ms	Duration: 84.84 ms	Billed Duration: 85 ms	Memory Size: 128 MB	Max Memory Used: 128 MB
{"status": 200, "body": "{'hello': 'world'}"}
```

Please let me know if this helps.

**Comment by GustaveDjoutsop** [comment]
Hi @mildaniel ,  sorry for the belated feedback, I was sick meanwhile.

So I updated the docker-compose file as you did and follwed the step 5 and 6 as you did  on my Gitlab-Pipeline but I got  a timeout issue: (running it locally is fine)

The gitlab-ci file:

 script:
    - apk add build-base
    - apk add  python3-dev
    - apk add --update py-pip
    - python3 -m pip install awscli
    - pip install --upgrade pip
    - apk add gcc musl-dev libffi-dev openssl-dev
    - pip install --no-cache-dir cryptography==2.1.4
    - python3 -m pip install aws-sam-cli
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - until docker --version; do echo "Docker-in-Docker service not ready"; sleep 1s; done  # wait that the dind service is up
    - apk add --no-cache docker-compose
    - until docker-compose --version; do echo "docker-compose service not ready"; sleep 1s; done
    - docker network create ${PROJECT_NAME}
    - echo "start container"
    - docker-compose up --build -d
    - docker network ls   
    - echo "Invoke a LambdaFunction"
    - sam local invoke HelloWorldFunction --docker-network ${PROJECT_NAME} --debug
    - sam build --debug
    - ls .aws-sam/build
    - echo "start SAM service with docker"
    - sam local start-api --host 0.0.0.0 --port 3000 --docker-network ${PROJECT_NAME} > /dev/null 2>&1 &


The OUTPUT:

> $ docker network ls
NETWORK ID          NAME                       DRIVER              SCOPE
498bbfdd7255        bridge                     bridge              local
0046d31e3f99        host                       host                local
2d74795ec0ec        none                       null                local
42abd0d669a5        containerized-aws-sam   bridge              local

> $ docker-compose up --build -d
Building sam
Step 1/9 : FROM python:3.8
3.8: Pulling from library/python
Digest: sha256:89986864f936860f6e74a7540ab98b23586011e90482b09125aa6792f2ea0195
Status: Downloaded newer image for python:3.8
 ---> 928a35165ae5
Step 2/9 : WORKDIR /app
 ---> Running in 261da00119c3
Removing intermediate container 261da00119c3
 ---> 2d6c14e6b51c
Step 3/9 : RUN curl -O https://bootstrap.pypa.io/get-pip.py
 ---> Running in 34b503646439

...................

> $ sam local invoke HelloWorldFunction --docker-network ${PROJECT_NAME} --debug
	SAM CLI now collects telemetry to better understand customer needs.

2022-11-21 08:45:48,966 | Config file location: /builds/${PROJECT_NAME}/samconfig.toml
2022-11-21 08:45:48,966 | Config file '/builds/${PROJECT_NAME}/samconfig.toml' does not exist
2022-11-21 08:45:48,974 | Using SAM Template at /builds/${PROJECT_NAME}/template.yaml
2022-11-21 08:45:49,017 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-11-21 08:45:49,018 | Using config file: samconfig.toml, config environment: default
2022-11-21 08:45:49,018 | Expand command line arguments to:
2022-11-21 08:45:49,018 | --template_file=/builds/${PROJECT_NAME}/template.yaml --docker_network=containerized-aws-sam --function_logical_id=HelloWorldFunction --no_event --layer_cache_basedir=/root/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1 
2022-11-21 08:45:49,018 | local invoke command is called

2022-11-21 08:45:49,075 | Found Serverless function with name='HelloWorldFunction' and CodeUri='.'
2022-11-21 08:45:49,075 | --base-dir is not presented, adjusting uri . relative to /builds/${PROJECT_NAME}/template.yaml
2022-11-21 08:45:49,116 | Found one Lambda function with name 'HelloWorldFunction'
2022-11-21 08:45:49,117 | Invoking app.lambda_handler (python3.7)
2022-11-21 08:45:49,117 | No environment variables found for function 'HelloWorldFunction'
2022-11-21 08:45:49,117 | Loading AWS credentials from session with profile 'None'
2022-11-21 08:45:49,143 | Resolving code path. Cwd=/builds/${PROJECT_NAME}, CodeUri=/builds/${PROJECT_NAME}
2022-11-21 08:45:49,143 | Resolved absolute path to code is /builds/${PROJECT_NAME}
2022-11-21 08:45:49,144 | Code /builds/${PROJECT_NAME} is not a zip/jar file
2022-11-21 08:45:49,149 | Image was not found.
2022-11-21 08:45:49,150 | Removing rapid images for repo public.ecr.aws/sam/emulation-python3.7
Building image......................................................................................................................................................................................................................................................................................................................................................................................................................
2022-11-21 08:46:36,664 | Skip pulling image and use local one: public.ecr.aws/sam/emulation-python3.7:rapid-1.65.0-x86_64.
2022-11-21 08:46:36,665 | Mounting /builds/${PROJECT_NAME} as /var/task:ro,delegated inside runtime container
2022-11-21 08:46:57,442 | Cleaning all decompressed code dirs
2022-11-21 08:46:57,442 | Timed out while attempting to establish a connection to the container. You can increase this timeout by setting the SAM_CLI_CONTAINER_CONNECTION_TIMEOUT environment variable. The current timeout is 20.0 (seconds).

**Comment by mildaniel** [comment]
Have you tried increasing the timeout based on the suggestion to see if that works?

**Comment by GustaveDjoutsop** [comment]
yeah I increased it to 300 sec but same issue

**Comment by mildaniel** [comment]
Hey @GustaveDjoutsop, I came back to your original example and was able to get it to work by following this issue https://github.com/aws/aws-sam-cli/issues/2279. It seems as though the Docker in Docker approach creates the nested container on the host. If you mount the same directory on the host in the container, your original docker-compose file should work. In your CI config you should only need to call the docker-compose commands.

**Comment by GustaveDjoutsop** [comment]
Hi @mildaniel , 
I updated the command with volume but got the same issue.

`command: sam local invoke HelloWorldFunction --docker-network containerized-aws-sam_backend --container-host host.docker.internal -v "/app" --debug`

Can you shared how you solved it please?

**Comment by mildaniel** [comment]
Hi @GustaveDjoutsop,
Apologies if I wasn't clear enough with my prior response. What I mean is in the `docker-compose.yaml`, try mounting the same directory path as the one where the code lives on your machine. If the code is in a directory called `/Users/name/code/`, the corresponding configuration would be:

```
volumes:
      - /Users/name/code/:/Users/name/code/
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by hnnasit** [comment]
Hi @GustaveDjoutsop, did @mildaniel's suggestion help resolve the issue?

**Comment by mildaniel** [comment]
Issue is inactive, closing.

**Comment by GustaveDjoutsop** [comment]
Yes it can be closed I got sick for a while, 
It helped solved the issue thanks.
