### ISSUE TITLE
SAM build with --manifest don't recognize the package.json

### ISSUE THREAD

**Issue by Maoragai12** [aws/aws-sam-cli#4427]
### Description:
When I try to build a Lambda function with the `--manifest` to locate the `package.json`, it throws an error:

```
ENOENT: no such file or directory, open '/private/var/folders/cf/ggmwqfwn03q443mj6vzryn0c0000gr/T/tmpch3vnyji/package.json'
```

### Steps to reproduce:
Run the following command:

```
"sam build --manifest ./package.json --template services/expenses-service/template.yaml --parameter-overrides EnvType={args.EnvType} --beta-features --build-dir=.aws-sam/build/expenses-service --debug"
```

### Observed result:
```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.65.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 301, in run
    action.execute()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.65.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/nodejs_npm/actions.py", line 114, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: NPM Failed: npm WARN config production Use `--omit=dev` instead.
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /private/var/folders/cf/ggmwqfwn03q443mj6vzryn0c0000gr/T/tmpsxb76scf/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/private/var/folders/cf/ggmwqfwn03q443mj6vzryn0c0000gr/T/tmpsxb76scf/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:

Build Failed
```

### Expected result:
Take the `package.json` from the specified location and build the Lambda. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Monterey V12.5.1
2. `sam --version`: SAM CLI, version 1.65.0
3. AWS region: us-east-1

**Comment by mildaniel** [comment]
Thanks for reporting the issue. I will take a closer look and report back!

**Comment by jfuss** [comment]
I tried this locally but cannot reproduce. Here is what I did:
1. `sam init` filled out options to get a nodejs project
2. `cd sam-app`
3. `mv hello-world/package.json .`
4. `sam build --manifest ./package.json`

This resulted in
```
ls .aws-sam/build/HelloWorldFunction/
README.md     events        hello-world   node_modules  package.json  template.yaml
```

Given the error, it's likely your command is not correct for your system. To help further, I would need to understand you setup better.

**Comment by qingchm** [comment]
@Maoragai12 Hey please let us know if the above information helped! Closing as we couldn't reproduce and doubt that there is a bug here, but feel free to re-open the ticket if your issue persists. Also if you still require some attention would be helpful if you can provide the expected locations of your file or the folder structure of your project (where manifest location is relative to template file etc. it would be greatly helpful!)

**Comment by Maoragai12** [comment]
Hi guys,
I just ran it without the
--manifest and it worked. It took the package.json from the root folder as expected. Thanks!

**Comment by oieduardorabelo** [comment]
> I tried this locally but cannot reproduce. Here is what I did:
> 
> 1. `sam init` filled out options to get a nodejs project
> 2. `cd sam-app`
> 3. `mv hello-world/package.json .`
> 4. `sam build --manifest ./package.json`
> 
> This resulted in
> 
> ```
> ls .aws-sam/build/HelloWorldFunction/
> README.md     events        hello-world   node_modules  package.json  template.yaml
> ```
> 
> Given the error, it's likely your command is not correct for your system. To help further, I would need to understand you setup better.

Hey @jfuss , I tried yor suggestion using sam init for typescript, and it doesn't work:

https://user-images.githubusercontent.com/829902/223573269-1394cdfc-9a7f-4203-b7ff-48477e4c2e4d.mov

I assume it is because the `CodeUri` is still pointing to `hello-world` folder. Instead it should point to the folder where the `package.json` is located.
