### ISSUE TITLE
Bug: Terraform support is not working for SAM CLI installed in linux using the x86_64 - command line installer

### ISSUE THREAD

**Issue by moelasmar** [aws/aws-sam-cli#4432]
### Description:
Customers are seeing `Error: Import error - HookFunctionality module "samcli.hook_packages.terraform.main` when attempting to use sam cli commands against terraform projects.

### Steps to reproduce:
- install SAM CLI using in a linux environment using the x86_64 - command line installer (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html)
- on a Terraform project, run `sam build --hook-name terraform --beta-features --debug`
- you will get the following error `Error: Import error - HookFunctionality module "samcli.hook_packages.terraform.main"`

### Observed result:
SAM CLI failed to build the terraform project with this error `Error: Import error - HookFunctionality module "samcli.hook_packages.terraform.main"`

### Expected result:
SAM CLI should build the terraform project without errors.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. `sam --version`: 1.65.0

`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
This issue is fixed in [this sam nightly release](https://github.com/aws/aws-sam-cli/releases/sam-cli-nightly/). As a workaround for now, please follow these [instructions](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/manage-sam-cli-versions.html#manage-sam-cli-versions-nightly-build) to install the sam nightly version. We will update this issue once we release this fix.

**Comment by super132** [comment]
SAM CLI released [1.66.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.66.0) and Terraform support feature is working when installing through Linux installer. I'm resolving this issue.
