### ISSUE TITLE
Bug: sam-nightly 1.65.0.dev202211240904 No response from invoke container for AwsLambdaFunctionPublishBookReviewBFC97F47

### ISSUE THREAD

**Issue by Yoimer** [aws/aws-sam-cli#4443]
### Description:

No response from invoke container for AwsLambdaFunctionPublishBookReviewBFC97F47 after executing
sam-nightly local invoke aws_lambda_function.publish_book_review -e events/new-review.json --beta-features
following what's on [Better together: AWS SAM CLI and HashiCorp Terraform](https://aws.amazon.com/blogs/compute/better-together-aws-sam-cli-and-hashicorp-terraform/?trk=global_employee_advocacy&sc_channel=sm&advocacy_source=everyonesocial&es_id=76e74fed05)

### Steps to reproduce:

`git clone https://github.com/aws-samples/aws-sam-terraform-examples`
`cd aws-sam-terraform-examples/zip_based_lambda_functions/api-lambda-dynamodb-example/`
```
provider “aws” {
    region = “us-east-1” # e.g. us-east-1
}
```
`terraform init`
`terraform apply`
`sam-nightly build --hook-name terraform --beta-features`
`export AWS_DEFAULT_REGION=us-east-1`
`sam-nightly local invoke aws_lambda_function.publish_book_review -e events/new-review.json --beta-features`

### Observed result:

```
sam-nightly local invoke aws_lambda_function.publish_book_review -e events/new-review.json --beta-features

Experimental features are enabled for this session.
Visit the docs page to learn more about the AWS Beta terms https://aws.amazon.com/service-terms/.

Invoking index.lambda_handler (python3.8)
Image was not found.
Removing rapid images for repo public.ecr.aws/sam/emulation-python3.8
Building image............................................................................................................................................................................................................................................................................
Skip pulling image and use local one: public.ecr.aws/sam/emulation-python3.8:rapid-1.65.0.dev202211240904-x86_64.

Mounting /home/yoimer1988/dev/aws-sam-terraform-examples/zip_based_lambda_functions/api-lambda-dynamodb-example/.aws-sam/build/AwsLambdaFunctionPublishBookReviewBFC97F47 as /var/task:ro,delegated inside runtime container
START RequestId: a71963f1-531f-49cc-9787-34001722baab Version: $LATEST
Function 'aws_lambda_function.publish_book_review' timed out after 30 seconds
No response from invoke container for AwsLambdaFunctionPublishBookReviewBFC97F47
```

### Expected result:

`A 200 response code`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:"22.04.1 LTS (Jammy Jellyfish)" (WLS2)
2. `sam-nightly --version`: version 1.65.0.dev202211240904
3. AWS region: us-east-1
4. Docker version 20.10.20, build 9fdeb9c
5. `AWS CLI version:` aws-cli/2.9.1 Python/3.9.11 Linux/5.10.16.3-microsoft-standard-WSL2 exe/x86_64.ubuntu.22 prompt/off

`Add --debug flag to command you are running`

**Comment by mildaniel** [comment]
Can you try cloning the sample app again. We updated it recently to comment out a few lines that seem to be causing some problems. Hopefully that works for you, please let us know!

**Comment by Yoimer** [comment]
Dear @mildaniel thanks for responding. I did indeed and everything is working great. A quick note regarding the debugging with VS Code though. The **launch.json** file should be like this

`{
    "version": "0.2.0",
    "configurations": [
          {
            "name": "Attach to SAM CLI",
            "type": "python",
            "request": "attach",
            "address": "localhost",
            "port": 9999,
            "localRoot": "${workspaceRoot}/src",
            "remoteRoot": "/var/task",
            "protocol": "inspector",
            "stopOnEntry": false
          }
    ]
  }
  `
 For those who just copy and paste (like me) from this great article [Better together: AWS SAM CLI and HashiCorp Terraform](https://aws.amazon.com/blogs/compute/better-together-aws-sam-cli-and-hashicorp-terraform/?trk=global_employee_advocacy&sc_channel=sm&advocacy_source=everyonesocial&es_id=76e74fed05l)
 The debugger will not work because that config shown there might be from the person's laptop who posted. But the code I just shared show work on any Linux or Mac.
 Thanks again for the support.

**Comment by mildaniel** [comment]
Thanks for the update!

**Comment by Yoimer** [comment]
Thank you @mildaniel and all the people who are supporting!!

**Comment by jfuss** [comment]
I pinged the owner of the blog about the feedback above. 

Closing this as it appears to be resolved. If I misunderstood the state, please reopen.
