### ISSUE TITLE
Feature request: Support Code properties on AppSync resolvers and function configurations

### ISSUE THREAD

**Issue by jplock** [aws/aws-sam-cli#4482]
### Describe your idea/feature/enhancement

I would like to have `CodeS3Location` added into the `AWS_APPSYNC_RESOLVER` and `AWS_APPSYNC_FUNCTIONCONFIGURATION` attributes so AppSync Javascript resolvers can be sourced from the local path to support external testing frameworks.

### Proposal

Add details of how to add this to the product.

Things to consider:
1. Add `CodeS3Location` into https://github.com/aws/aws-sam-cli/blob/develop/samcli/lib/utils/resources.py#L61
2. Add `CodeS3Location` into https://github.com/aws/aws-sam-cli/blob/develop/samcli/lib/utils/resources.py#L62

**Comment by qingchm** [comment]
Thanks for the request! As attached above we already have a PR that will address this feature request, waiting for the PR to be merged and release

**Comment by hawflau** [comment]
Closing as the feature has been shipped in AWS SAM CLI v1.68.0

**Comment by jplock** [comment]
Thank you!
