### ISSUE TITLE
Feature request: Terraform hook should handle more complex source_path variables

### ISSUE THREAD

**Issue by tam116** [aws/aws-sam-cli#4495]
### Describe your idea/feature/enhancement
The terraform lambda module supports complex source_path arguments or simple path strings.

To specify custom build commands the more complex source_path object is required, such as specifying a custom `pip install` command.
https://registry.terraform.io/modules/terraform-aws-modules/lambda/aws/latest#commands

The terraform hook should be able to handle at least single source path specified in the style of

source_path = [
{
path = "source_path",
commands = ['my command']
}
}

### Proposal

The terraform json parsing code something along the lines of:
if isinstance(tf_source_path, dict):
  cfn_source_path = tf_source_path['path']
else:
 cfn_source_path = tf_source_path

**Comment by qingchm** [comment]
Hey @tam116 thanks for reaching out! Really appreciate your advice, just curious since you have provided some code level proposal, would you be interested to contribute to this feature and add this improvement?

**Comment by tam116** [comment]
@qingchm I've made a PR #4506  that should add the feature and the relevant unit tests

**Comment by moelasmar** [comment]
Thanks @tam116 for your contribution. I checked your PR, it looks good to me, it just misses adding an integration test case to cover the new case for source_path.

**Comment by sriram-mv** [comment]
Closing as part of 1.69.0 release.
