### ISSUE TITLE
Feature request: `sam local ...` option to use actual environment variables

### ISSUE THREAD

**Issue by bestickley** [aws/aws-sam-cli#4500]
### Describe your idea/feature/enhancement

I wish SAM CLI would allow me to set a option for `sam local ...` commands that downloaded my function's actual environment variables and injected them into the local runtime so I can debug with them.

### Proposal

Before the function is invoked, SAM CLI can use the API: [GetFunctionConfiguration](https://docs.aws.amazon.com/lambda/latest/dg/API_GetFunctionConfiguration.html) to get the environment variables and feed them into runtime environment.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model) No

**Comment by jfuss** [comment]
This is similar to https://github.com/aws/aws-sam-cli/issues/332#issuecomment-1218371195 but not exactly the same. Regardless, this is better for `sam sync` (same as the execution role).

Closing
