### ISSUE TITLE
Feature request: `sam local ...` command option to use lambda's execution role

### ISSUE THREAD

**Issue by bestickley** [aws/aws-sam-cli#4501]
### Describe your idea/feature/enhancement

I wish SAM CLI would provide a CLI option for `sam local ...` commands where SAM assumed my Lambda's execution role during local runtime. I want this feature because I want to know when developing locally if my Lambda has incorrect permissions. I don't want to develop locally, think I'm good to go, deploy, and then have to fix permissions.

### Proposal

Use AWS STS [AssumeRole](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) API and inject appropriate environment variables into the runtime environment

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model) No

**Comment by jfuss** [comment]
Please see https://github.com/aws/aws-sam-cli/issues/332#issuecomment-1218371195 

Closing as duplicate
