### ISSUE TITLE
Bug: Fail sam local gracefully for cases with inline code

### ISSUE THREAD

**Issue by praneetap** [aws/aws-sam-cli#4505]
sam local should fail gracefully in cases where lambda code is defined inline, since it doesnt support it. Look at this issue comment https://github.com/aws/aws-sam-cli/issues/790#issuecomment-1157759305

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
@praneetap ... do you mean only if all functions in the project defined with inline code?

**Comment by praneetap** [comment]
@moelasmar just updated the issue with more details. Here is the issue comment this issue is referencing - https://github.com/aws/aws-sam-cli/issues/790#issuecomment-1157759305

**Comment by hawflau** [comment]
Released with [1.74.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.74.0). Closing.
