### ISSUE TITLE
Error: Unstable state when updating repo. Check that you have permissions to create/delete files in C:\Users\97155\AppData\Roaming\AWS SAM directory

### ISSUE THREAD

**Issue by rasheedmit** [aws/aws-sam-cli#4516]
sam init is giving error as below, please help!

Cloning from https://github.com/aws/aws-sam-cli-app-templates (process may take a moment)
Error: Unstable state when updating repo. Check that you have permissions to create/delete files in C:\Users\97155\AppData\Roaming\AWS SAM directory or file an issue at https://github.com/aws/aws-sam-cli/issues

**Comment by moelasmar** [comment]
Thanks @rasheedmit for raising this issue. Could you please share the exact steps to reproduce this issue to investigate it!

**Comment by qingchm** [comment]
@rasheedmit Hi please refer to https://github.com/aws/aws-sam-cli/issues/4031 for a workaround, sorry for getting into this issue! https://github.com/aws/aws-sam-cli/issues/4031#issuecomment-1183633630 This would be the comment that will be most helpful to you!
