### ISSUE TITLE
generate-event: Add S3 Batch Operations Event

### ISSUE THREAD

**Issue by arjunrawal4** [aws/aws-sam-cli#4521]
### Describe your idea/feature/enhancement

S3 Batch Operations is missing from `sam local generate-event`. It would be nice to have sample events for Batch Operations lambda invocations

### Proposal

Add new event to SAM.

```
{
    "invocationSchemaVersion": "1.0",
    "invocationId": "YXNkbGZqYWRmaiBhc2RmdW9hZHNmZGpmaGFzbGtkaGZza2RmaAo",
    "job": {
        "id": "f3cc4f60-61f6-4a2b-8a21-d07600c373ce"
    },
    "tasks": [
        {
            "taskId": "dGFza2lkZ29lc2hlcmUK",
            "s3Key": "customerImage1.jpg",
            "s3VersionId": "1",
            "s3BucketArn": "arn:aws:s3:us-east-1:0123456788:awsexamplebucket1"
        }
    ]
}
```

### Additional Details
https://docs.aws.amazon.com/lambda/latest/dg/services-s3-batch.html
https://docs.aws.amazon.com/AmazonS3/latest/userguide/batch-ops-invoke-lambda.html
https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/doc_source/batch-ops-invoke-lambda.md

**Comment by moelasmar** [comment]
Thanks @arjunrawal4 for raising this feature. I checked your PR and looks good to me, I will ask the team to provide another approval to merge it.

**Comment by sriram-mv** [comment]
Closing as part of 1.69.0 release.
