### ISSUE TITLE
sam build and sam deploy succeed, but lambda fails with Could not find the required deps.json file

### ISSUE THREAD

**Issue by alexgurman** [aws/aws-sam-cli#4547]
### Description:
Running a .NET Core 3.1 project containing Lambdas, trying to deploy using sam build and sam deploy. All is successful, but test immediately fails with an error: Could not find the required 'WSO.WSOData.DataExtractor.LambdaServices.deps.json'. This file should be present at the root of the deployment package.: LambdaException.   WSO.WSOData.DataExtractor.LambdaServices is the assembly holding lambdas.

### Steps to reproduce:
Running ADO pipeline (attached), deploying SAM template (attached). I can see the template and binaries in the S3 bucket as specified and they appear correct. Even the deps.json file that the error specifies is right there, under bin\Release\netcoreapp3.1\linux-x64

### Observed result:
Getting an error - Could not find the required 'WSO.WSOData.DataExtractor.LambdaServices.deps.json'. This file should be present at the root of the deployment package.: LambdaException.   WSO.WSOData.DataExtractor.LambdaServices is the assembly holding lambdas, so it's really <assembly name>.deps.json. 

### Expected result:
Lambda to run correctly

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Lambda in AWS
2. `sam --version`: Tool 'amazon.lambda.tools' (version '5.6.2')
3. AWS region: us-west-2

`Add --debug flag to command you are running`
Done
[azure-pipelines-release.zip](https://github.com/aws/aws-sam-cli/files/10362287/azure-pipelines-release.zip)
[ADO pipeline - Deploy log.txt](https://github.com/aws/aws-sam-cli/files/10362306/ADO.pipeline.-.Deploy.log.txt)
[ADO pipeline - Build log.txt](https://github.com/aws/aws-sam-cli/files/10362307/ADO.pipeline.-.Build.log.txt)
[ErrorsFromCloudWatch.txt
![DeploymentArtifactsOnS3Bucket-Capture](https://user-images.githubusercontent.com/3374431/211078463-094e3e28-10bd-452b-903b-1711e7e26dea.PNG)
![DeploymentArtifactsOnS3Bucket-inside-zip-2-Capture](https://user-images.githubusercontent.com/3374431/211078464-a4608aaa-2086-4cab-b043-b93210ca48b7.PNG)
![DeploymentArtifactsOnS3Bucket-inside-zip-Capture](https://user-images.githubusercontent.com/3374431/211078467-c36dc89a-5f4f-45e9-b0f8-19768de4b924.PNG)
](https://github.com/aws/aws-sam-cli/files/10362331/ErrorsFromCloudWatch.txt)
[91e816fc4f3fd86957d7d6f2361852d9.template.zip](https://github.com/aws/aws-sam-cli/files/10362364/91e816fc4f3fd86957d7d6f2361852d9.template.zip)

**Comment by hawflau** [comment]
Hi @alexgurman, thanks for reporting the issue. Would you also let us know what permissions the directories and the files have in your deployment zip file? 

I noticed you were using SAM CLI v1.67.0. Did you see any issue before `1.67.0`?

**Comment by alexgurman** [comment]
1. all permissions are rwxrwxrwx, bith files and directories
2. it's a new thing, we are migrating from using a different deployment tool, so no idea. As you can see in the pipeline, we are just specifying in a step: _update -g Amazon.Lambda.Tools_ . If you want us to try a particular version, LMK which version to try - I guess we can always run dotnet tool update -g Amazon.Lambda.Tools --version <recommended version> instead.

**Comment by mndeveci** [comment]
One thing I notice in your pipeline definition is that, you are defining the `--template` parameter for both `sam build` and then `sam deploy` commands with same value.

```
        - task: AWSShellScript@1
          displayName: 'Build'
          inputs:
            regionName: $(awsRegion)
            scriptType: 'inline'
            inlineScript: |
              sam build --debug \
              --template-file $(AssignValues.LambdaTemplateFilePathFull) \
              --config-env $(environment) \
              --config-file samconfig.toml

        - task: AWSShellScript@1
          displayName: 'Package & Deploy'
          inputs:
            regionName: $(awsRegion)
            scriptType: 'inline'
            inlineScript: |
              sam deploy --s3-bucket noticemanager-deployment-$(environment)-$(awsRegion) \
              --s3-prefix CF/$(AssignValues.MyBuildName)/ \
              --template-file $(AssignValues.LambdaTemplateFilePathFull) \
              --no-confirm-changeset \
              --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM \
              --stack-name $(appName)-$(environment) \
              --force-upload \
              --on-failure ROLLBACK \
              --no-fail-on-empty-changeset \
              --config-env $(environment) \
              --config-file samconfig.toml \
              --debug
```

`sam build` command builds your functions and puts the built files under `.aws-sam/build/<logical_id>` folder. Then, it updates the original template with the new locations of the functions, and writes it under `.aws-sam/build/template.yaml`. Original template still points to source folder so that you can re-build it later.

After this, subsequent commands should use that build template under `.aws-sam/build/template.yaml`.

Looking at your pipeline definition, you seem like re-using the same template location (`$(AssignValues.LambdaTemplateFilePathFull)`) which was used with `sam build`. Using the same value with `sam deploy` will cause the source folders to be uploaded as the build folder. For that reason, lambda might not work as expected.

I would recommend removing `--template` parameter for `sam deploy` (or replacing with the path which will point to built template) and give it a retry.

Please let us know if this will resolve your issue.

Thanks!

**Comment by alexgurman** [comment]
This was the problem, awesome!!!!
