### ISSUE TITLE
Bug: SAM not able to connect lambda function in production to MQTT endpoint

### ISSUE THREAD

**Issue by MaxOrelus** [aws/aws-sam-cli#4551]
Would love some help from the AWS SAM team to troubleshoot why AWS services aren't working nicely together...

https://github.com/aws/aws-iot-device-sdk-js-v2/issues/315

`sam build --use-container && sam local start-api --debug`

connection to MQTT endpoint works locally with the exact same credentials in production.

- AmazonRootCA1.pem
- device.pem.crt
- private.pem.key

`sam build --use-container && sam deploy`

Same credentials across the board and the deployed resources can't make the connection to the endpoint.

Any thoughts?

**Comment by mndeveci** [comment]
Thanks for reporting this issue.

`sam local` commands will be running with your local credentials, which might have broader permissions than what you have configured in your deployed template.

You can try using `sam sync` to test your application in the cloud (which should give the same permissions error), but it should help you to quickly identify the issue and resolve it with faster feedback loop.

Please let us know if you have other questions or concerns.

**Comment by sriram-mv** [comment]
Closing this issue on account of inactivity for the initial set of questions, what mndeveci says holds if you are still facing this issue please open a new issue with more details. Happy to dive deeper!
