### ISSUE TITLE
Bug: BuildProperties > External does not parse CommaDelimitedList ref

### ISSUE THREAD

**Issue by sebelga** [aws/aws-sam-cli#4558]
### Description:

When using the `esbuild` BuildMethod we have the option to declare `External` dependencies under the BuildProperties. 
To not repeat the list over and over I decided to create a `CommaDelimitedList` Parameter that I can reference.
The correct way to declare the list is: `"ajv, aws-sdk, axios"`.

But doing so does not work, the list is not parsed

```
# Output when building, the list of dependencies is still a string
 ... `External': ' ajv, aws-sdk, axios'
```

The only way to make it work is to pass an Array directly in the Parameter, but that's not a valid template.yaml

```
# This works but is not a valid `template.yaml`

Parameters:
  EXTERNALDEPS:
    Type: CommaDelimitedList
    Default: [
      "ajv",
      "aws-sdk",
      "axios"
    ]
```

```
# Output when building (valid)
 ... `External': ['ajv, aws-sdk, axios']
```

This works and I can run `sam build`, but I cannot deploy the app anymore. I get this error

```
Error: Failed to create changeset for the stack: <stack-name>, An error occurred (ValidationError) when calling the CreateChangeSet operation: Template format error: Every Default member must be a string.
```

### Steps to reproduce:

Add a CommaDelimitedList parameter

```
Parameters:
  EXTERNALDEPS:
    Type: CommaDelimitedList
    Default:  "aws-sdk", "axios"
```

Reference it in the BuildProperties

```
Metadata:
  BuildMethod: esbuild
  BuildProperties:
    Minify: true
    Target: "es2020"
    Sourcemap: false
    External:
      Ref: EXTERNALDEPS
```

### Observed result:

The List is **not** parsed as an array

```
Building codeuri: /<path> runtime: nodejs16.x metadata: {'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': True, 'Target': 'es2020', 'Sourcemap': False, 'External': 'aws-sdk, axios'}} architecture: arm64 functions: FunctionName
```

And we get the following error

```
Error: NodejsNpmEsbuildBuilder:EsbuildBundle - Invalid type for property external, must be a dict.
```

### Expected result:

The list of deps passed as an array

```
Building codeuri: /<path> runtime: nodejs16.x metadata: {'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': True, 'Target': 'es2020', 'Sourcemap': False, 'External': ['aws-sdk, axios']}} architecture: arm64 functions: FunctionName
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`: `1.67.0`
3. AWS region: Happens locally

**Comment by mndeveci** [comment]
Thanks for reporting this issue.

This is a known limitation for SAM CLI builds in general, that there is no way to provide common settings for multiple functions (see: https://github.com/aws/aws-sam-cli/issues/3713)

Just a workaround for your case, you may try with providing `--parameter-overrides` for `sam build` and use the values which lets you to deploy as default value.

You can use this in the template as default: `'ajv, aws-sdk, axios'`
And you can try this in `--parameter-overrides` just for `sam build`: `['ajv, aws-sdk, axios']`

Again this is just a workaround, proper way of setting these values will be provided once we resolve the issue above.

Please let us know if you can bypass your issue with the workaround.

**Comment by sebelga** [comment]
Thanks for the answer @mndeveci

Unfortunately the workaround does not work

```
# When I send this
sam build --parameter-overrides EXTERNALDEPS=['axios']
```

It is converted to `String` (and not a dict)

```
# Notice the quotes around the brackets
... 'External': '[axios]'
```

Throwing the following error

```
Invalid type for property external, must be a dict.
```

**Comment by sebelga** [comment]
I guess we can close this issue and continue further discussion in https://github.com/aws/aws-sam-cli/issues/3713. Cheers
