### ISSUE TITLE
Bug: samconfig.toml values don't override default values in sam template

### ISSUE THREAD

**Issue by alexgurman** [aws/aws-sam-cli#4572]
### Description:
Running a .NET Core 3.1 project containing Lambdas, trying to deploy using sam build and sam deploy. Build is successful, but Deploy fails in AWS because parameter overrides specified in samconfig.toml are not used, even though log for both sam build and sam deploy states that they are found correctly. 

### Steps to reproduce:
Running ADO pipeline (attached), deploying SAM template (attached) with samconfig.toml. 

### Observed result:
The template generated by sam build has original default values specified for parameters, and they are the ones used during deployment, even though log says : for sam build: Loading configuration values from [uat.['build'].parameters] (env.command_name.section) in config file at '/workspace/1/s/Main/Source/Services/samconfig.toml' and similar for sam deploy

### Expected result:
the template to be deployed with parameters specified in [uat.global.parameters] section in samconfig.toml

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

OS: Lambda in AWS
sam --version: Tool 'amazon.lambda.tools' (version '5.6.2')
AWS region: us-west-2

Attached are logs for both Build and Deploy steps as well as the original template, generated one and samconfig.toml (in templatesAndSamCfg.zip)
[Build-Log.txt](https://github.com/aws/aws-sam-cli/files/10406008/Build-Log.txt)
[Deploy-Log.txt](https://github.com/aws/aws-sam-cli/files/10406009/Deploy-Log.txt)
[samconfig.zip](https://github.com/aws/aws-sam-cli/files/10406011/samconfig.zip)
[templatesAndSamCfg.zip](https://github.com/aws/aws-sam-cli/files/10406018/templatesAndSamCfg.zip)

**Comment by mndeveci** [comment]
Hi there,

I checked your `samconfig.toml` file with the deployment outputs, and I confirm that SAM CLI used the parameter overrides from the `samconfig.toml` file exactly. I don't want to paste here since it might contain some private information, and I would recommend not posting them without masking some information.

I believe your deployment error is not related to this or your default parameters for `[uat.global.parameters]` might be wrong.

Thanks

**Comment by mndeveci** [comment]
This is the `sam deploy` output, which displays the VpcId as 

```
Parameter overrides          : {**** "VpcId": "vpc-0ac935c52afd582e7", ***}
```

I believe this is the value that you are expecting. If so this might be coming from somewhere else. If you can provide us a minimal template which we can re-produce the issue, then we can investigate further.

**Comment by alexgurman** [comment]
Minimal template works fine, no issues. Even weirder, for dev environment, the values are substituted correctly - I intentionally changed default values on SAM template and they get replaced by the correct values from samconfig.toml file just fine. But not for uat environment, for the real code. For Hello World template the same  samconfig.toml file works fine in both dev and uat. Mystified.

**Comment by alexgurman** [comment]
Parameter override works for some projects, doesn't work for others, not seeing a pattern. Sometimes will work for the first environment, but not for the second. 

Attached is data from smaller project, where Sam deploy doesn't override parameters for the first environment. Attached are logs from build step - no errors that I can see; deploy step - no errors that I can see till we get to AWS Cloud Formation deployment, where because parameter Stage retains default value of Lcl instead of Dev, there is a naming clash.

Attaches is a screenshot pf cloud formation stack parameters, where one can see that the parameters were not replaced as claimed in Sam deploy log. Also attached is samconfig.toml file used.
[DeployLog.txt](https://github.com/aws/aws-sam-cli/files/10540299/DeployLog.txt)
[BuildLog.txt](https://github.com/aws/aws-sam-cli/files/10540300/BuildLog.txt)
![AWS CF Parameters](https://user-images.githubusercontent.com/3374431/215605414-f9025e63-6787-4687-ae27-4f40fb22857a.PNG)
[samconfig.toml.txt](https://github.com/aws/aws-sam-cli/files/10540307/samconfig.toml.txt)

**Comment by alexgurman** [comment]
SAM CLI, version 1.72.0

**Comment by mndeveci** [comment]
Can you provide how do you run `sam deploy` command? Looking at the command output, it looks like you are providing the `--parameter-overrides` option, which overwrites what you have in `samconfig.toml` file there.

```
Expand command line arguments to:
2023-01-30T21:09:18.1563412Z 2023-01-30 21:09:18,155 | --template_file=/workspace/2/s/.aws-sam/build/template.yaml --s3_bucket=noticemanager-deployment-dev-us-west-2 --s3_prefix=CF/Lambda-AccessKeysManager-Build-master-New --capabilities=('CAPABILITY_IAM', 'CAPABILITY_AUTO_EXPAND', 'CAPABILITY_NAMED_IAM') --stack_name=noticemanager-accesskeymanager-dev --force_upload --on_failure=ROLLBACK --parameter_overrides={'AwsRegion': 'us-west-2'} --tags={'Company': 'IHS Markit', 'Stage': 'dev', 'BusinessService': 'NoticeManager', 'Product': 'AwsKeyUpdater', 'CostCenter': '11807000', 'User': 'Alex.Gurman', 'OrgID': '00385', 'Capacity': 'BRMigration', 'Contact': 'DLLoanPlatformsAWSNotifications@ihsmarkit.com', 'Service': 'Notice Manager', 'Group': 'nonprod'} 
```

[From our documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html)
> Parameter values that you provide on the command line take precedence over corresponding entries in the configuration file. For example, if your configuration file contains the entry stack_name = "DefaultStack" and you run the command sam deploy --stack-name MyCustomStack, then the deployed stack name is MyCustomStack.

**Comment by alexgurman** [comment]
Here it is, thank you. The only value we override through parameter-overrides is region. Everything else comes from samconfig.toml file.

- task: AWSShellScript@1
            displayName: 'Package & Deploy'
            continueOnError: true
            inputs:
              regionName: ${{parameters.awsRegion}}
              scriptType: 'inline'
              inlineScript: |
                sam deploy --s3-bucket noticemanager-deployment-${{lower(parameters.environment)}}-${{parameters.awsRegion}} \
                --s3-prefix CF/$(AssignValues.MyBuildName) \
                --no-confirm-changeset \
                --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM \
                --stack-name $(appName)-${{lower(parameters.environment)}} \
                --force-upload \
                --on-failure ROLLBACK \
                --no-fail-on-empty-changeset \
                --config-env '$(AssignValues.SamEnv)' \
                --config-file $(AssignValues.SamconfigFilePathFull) \
                --parameter-overrides AwsRegion=${{parameters.awsRegion}} \
                --debug

**Comment by mndeveci** [comment]
Thanks for details, I think issue is coming from that parameter you are passing. If you pass `--parameter-overrides` it will overwrite the values in `samconfig.toml` file. I would recommend moving it into `samconfig.toml` file or use [CFN pseudo parameter `AWS::Region`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html) in your template.

I am resolving this issue now, but please let us know if you have other questions.

**Comment by alexgurman** [comment]
Please re-open, the issue is still there.

Here is the updated code snippets for build & deploy steps, new logs attached - the issue is very much still there. Please give me a chance to verify before you close the issue?

Appreciated.

 - task: AWSShellScript@1
            enabled: true
            displayName: 'Build'
            inputs:
              regionName: ${{parameters.awsRegion}}
              scriptType: 'inline'
              inlineScript: |
                sam build --debug \
                --
[logs.zip](https://github.com/aws/aws-sam-cli/files/10689787/logs.zip)
template-file $(AssignValues.LambdaTemplateFilePathFull) \
                --config-env '$(AssignValues.SamEnv)' \
                --config-file $(AssignValues.SamconfigFilePathFull)

          - task: AWSShellScript@1
            displayName: 'Package & Deploy'
            continueOnError: true
            inputs:
              regionName: ${{parameters.awsRegion}}
              scriptType: 'inline'
              inlineScript: |
                sam deploy --s3-bucket noticemanager-deployment-${{lower(parameters.environment)}}-${{parameters.awsRegion}} \
                --s3-prefix CF/$(AssignValues.MyBuildName) \
                --no-confirm-changeset \
                --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM \
                --stack-name $(appName)-${{lower(parameters.environment)}} \
                --force-upload \
                --on-failure ROLLBACK \
                --no-fail-on-empty-changeset \
                --config-env '$(AssignValues.SamEnv)' \
                --config-file $(AssignValues.SamconfigFilePathFull) \
                --debug

**Comment by mndeveci** [comment]
With this new deployment, you can see now you have `Parameter overrides` populated with following values;
```
Parameter overrides          :{"ApiUrl": "***", "ErrorNotificationsEmail": "***", "Stage": "dev", "OCTOEnv": "DEV", "VpcConfigSubnetId": "***", "VpcId": "***", "SecretName": "***", "LoggingBucketLevel": "Information", "LoggingCloudWatchLevel": "Error", "LoggingBucketName": "***", "AwsRegion": "us-west-2"}
```

From your previous example you only had the region value there;
```
Parameter overrides          : {"AwsRegion": "us-west-2"}
```

The latest values are expected because these are from `samconfig.toml` file's `devuswest2.global.parameters` section (I confirmed all values are loaded from there).

And what I can see from your deployment logs is that its execution have failed. You need to check `Events` tab in CloudFormation to see which resource failed to be deployed and its failure reason.

**Comment by alexgurman** [comment]
Thank you, we are still verifying, but looks promising. Hoping to confirm tomorrow. May I suggest to clarify the documentation on the precedence - it does state at https://docs.amazonaws.cn/en_us/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html that command line take precedence over corresponding entries in the configuration file, but the explanation (see below the full quote) clearly states that this is happening per parameter_overrides entry, not a global deal, meaning you can override a single parameter.

Full text:
_Parameter values that you provide on the command line take precedence over corresponding entries in the configuration file. For example, if your configuration file contains the entry stack_name = "DefaultStack" and you run the command sam deploy --stack-name MyCustomStack, then the deployed stack name is MyCustomStack.

For the parameter_overrides entry, both the parameter values that you provide on the command line and entries in the configuration file take precedence over corresponding objects declared in the Parameters section of the template file._

**Comment by mndeveci** [comment]
Thanks for your suggestion, I will take this to our doc writers to address your issue.

In the meantime, were you able to fix your deployment issues?

**Comment by alexgurman** [comment]
Absolutely, thank you.

**Comment by mndeveci** [comment]
Thank you too! Please let us know if you still have questions about this issue, otherwise we will close it.

**Comment by super132** [comment]
Resolving as no questions received. Feel free to submit a new issue if there is still problem. Thanks.
