### ISSUE TITLE
[Announcement] Installing/Updating AWS SAM CLI through Homebrew

### ISSUE THREAD

**Issue by mndeveci** [aws/aws-sam-cli#4607]
With [recent change to `homebrew-core` library](https://github.com/Homebrew/homebrew-core/pull/120653), AWS SAM CLI can now be installed without requiring to tap `aws/tap`. 

But this change also causes some delays to our releases. As of now, installing AWS SAM CLI through homebrew by running `brew install aws-sam-cli` installs `v1.70.0` which was released last week.

For users who wants to use up to date version, we recommend running `brew install aws/tap/aws-sam-cli` which should install latest version which was released couple of hours ago.

In the meantime, we are discussing with Hombrew maintainers for the way forward.

**Comment by pjungermann** [comment]
At least at the moment, both seem to install aws-sam-cli version 1.81.0, however the formula looks different for both.

E.g., [aws/tap/aws-sam-cli](https://github.com/aws/homebrew-tap/blob/master/Formula/aws-sam-cli.rb) depends on python 3.8, [aws-sam-cli](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/aws-sam-cli.rb) depends on pyhton 3.11. Just to mention one.

**Comment by sriram-mv** [comment]
@pjungermann [aws-sam-cli](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/aws-sam-cli.rb) is not the official formula. AWS SAM CLI maintains its own tap.

**Comment by pjungermann** [comment]
I guess I misunderstood. I assumed the idea was to transition to the homebrew-core version eventually. (awscli is also available at homebrew-core, but I guess it is also not official.)

I guess many homebrew users will find the core one first (if the aws/tap is not installed).

**Comment by mndeveci** [comment]
Superseded by https://github.com/aws/aws-sam-cli/issues/5613
