### ISSUE TITLE
Feature request: ZIP_STORED instead of ZIP_DEFLATED

### ISSUE THREAD

**Issue by Manouchehri** [aws/aws-sam-cli#4622]
### Describe your idea/feature/enhancement

I'm not sure there's a huge benefit to using DEFLATE compression for things like AWS Lambda packages. They're already very small.

### Proposal

I'd like there to be a flag to disable (or choose) compression.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model) - No.

### Additional Details

https://github.com/aws/aws-sam-cli/blob/ee23953806be066ebfb72dd42e188de4866483ae/samcli/lib/package/utils.py#L238

**Comment by Manouchehri** [comment]
If I were an AWS employee, I'd also consider adding zipalign later. This would probably get slightly faster Lambda startups by bypassing the zip decompression stage; you can just mmap things straight out of the zip file, like modern Android does. 

This optimization is out-of-scope for this ticket, just a bit of free advice. =)

**Comment by qingchm** [comment]
Thanks for opening this feature request! We will take a look at the request and if it makes sense we will put it into our backlogs

**Comment by jfuss** [comment]
See response in PR: https://github.com/aws/aws-sam-cli/pull/4644#issuecomment-1570592936

Closing as we are electing to not support this at the current time. You can provide your own Zip file within the template, which will be uploaded if you still want tight control over how the artifact is zipped.
