### ISSUE TITLE
Bug: Getting error "Error reading configuration file, Empty key found at line 1 col 0"

### ISSUE THREAD

**Issue by alexgurman** [aws/aws-sam-cli#4629]
### Description:
Trying to deploy using sam build and sam deploy. Build fails with cryptic message "Error reading configuration file: /workspace/9/s/Main/Source/AccessKeysManager/samconfig-admin.toml Empty key found at line 1 col 0"

Attached logs have the log of OutputSamConfigFile step, printing out sam config file used (I added a step in ADO build to print it out so what I attach is what is actually been used), as well as log for failed sam build command step.

### Steps to reproduce:
Running task below from linux pool on ADO:

         - task: AWSShellScript@1
            enabled: true
            displayName: 'Build'
            inputs:
              regionName: ${{parameters.awsRegion}}
              scriptType: 'inline'
              inlineScript: |
                sam build --debug \
                --template-file $(AssignValues.LambdaTemplateFilePathFull) \
                --config-env ${{lower(parameters.environment)}}-${{parameters.awsRegion}} \
                --parameter-overrides AwsRegion=${{parameters.awsRegion}} \
                --config-file ${{parameters.samConfigFile}} 

All parameters are correct, the sam config file (the name is actually samconfig-admin.toml) accessible, the path is correct, so no idea about the error. 

### Observed result:

Error reading configuration file: /workspace/9/s/Main/Source/AccessKeysManager/samconfig-admin.toml Empty key found at line 1 col 0

### Expected result:
Build should succeed, it succeeds in other projects using the same ADO template

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

OS: Lambda in AWS
sam --version: Tool 'amazon.lambda.tools' (version '5.6.2')
AWS region: us-west-2

```
# Paste the output of `sam --info` here
```
2023-01-27T19:16:56.5145005Z [command]/usr/local/bin/dotnet tool update -g Amazon.Lambda.Tools
2023-01-27T19:17:00.1543739Z You can invoke the tool using the following command: dotnet-lambda
2023-01-27T19:17:00.1546903Z Tool 'amazon.lambda.tools' (version '5.6.3') was successfully installed.
[Build.txt](https://github.com/aws/aws-sam-cli/files/10528892/Build.txt)
[OutputSamConfigFile.txt](https://github.com/aws/aws-sam-cli/files/10528893/OutputSamConfigFile.txt)

**Comment by qingchm** [comment]
Can you please verify that your config.toml file looks something like the following?

```
version = 0.1
[uatuseast1.global.parameters]
stack_name = "something"

[uatuseast1.deploy.parameters]
capabilities = "something"
...
```

**Comment by alexgurman** [comment]
My understanding was that  stack_name only needed for sam deploy, not sam build. Adding to our config.toml didn't make any difference - same error. Just in case, attaching updated config.toml as well as latest log from sam build.  
[samconfig-admin.toml.txt](https://github.com/aws/aws-sam-cli/files/10538219/samconfig-admin.toml.txt)
[Build.txt](https://github.com/aws/aws-sam-cli/files/10538238/Build.txt)

**Comment by alexgurman** [comment]
The issue was with encoding - it was not UTF-8, but UTF-8-BOM
