### ISSUE TITLE
Bug: Chmod command is not working 

### ISSUE THREAD

**Issue by aneelaanee** [aws/aws-sam-cli#4637]
![issue2](https://user-images.githubusercontent.com/123464578/215704073-0b6f04bd-91bb-4971-b504-cfe261e5ccfc.PNG)

### Description:
I need to run a shell script so before that step iam trying to give permission to the file .but iam getting Operation not permitted Issue 

### Steps to reproduce:
Docker file: FROM node:14-alpine3.16 [using this image]

gitlab.ci : 
 - chmod +x replace_env.sh
 - ./replace_env.sh

### Observed result:
Operation not permitted

### Expected result:
Need to get required perssion for replace_env.sh

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
@aneelaanee Can you provide more information? Are you running `sam build`? Do you have a reproducible example you can share? What version of `sam` are you using?

**Comment by jfuss** [comment]
Closing given no response.
