### ISSUE TITLE
Bug: sam validate --lint always return 0, even on failure.

### ISSUE THREAD

**Issue by andyloughran** [aws/aws-sam-cli#4649]
### Description:
When running sam validate --lint, it always exits with 0 on linting failure.

### Steps to reproduce:

- Start with a perfect template.
- Run `sam validate --lint` and see a success.
- Run `echo $?` to get the return code, it shows 0.
- Create a deliberate linting mistake in your template (such as adding a conflicting property to a resource)
- Run `sam validate --lint` and see a failure.
- Run `echo $?` and see the return code is still 0.

### Observed result:

A return code of 0 on a linting failure

### Expected result:
A return code of greater than 0 for a linting failure, to demonstrate error.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

MacOS

```{
  "version": "1.70.0",
  "system": {
    "python": "3.11.1",
    "os": "macOS-13.2-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.22",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}```

**Comment by mildaniel** [comment]
Thanks, @andyloughran. Let me try to reproduce and look further into this issue.

**Comment by mildaniel** [comment]
I was able to reproduce and confirm the behaviour. I will raise a PR shortly to address this issue.
