### ISSUE TITLE
Feature request: Allow arbitrary environment vars in SAM Template file when running locally

### ISSUE THREAD

**Issue by pstephenwille** [aws/aws-sam-cli#4663]
### Describe your idea/feature/enhancement

I wish SAM CLI would allow me to set arbitrary environment vars when running locally.
My use case is running an AWS Lambda function locally via AWS ToolKit, and this function requires proxy vars to work:
http_proxy=x.x.x.x:port

Without this, it fails

### Proposal

Allow the SAM template file to be tailored locally, and/or allow CLI params to point to a local.json file to set these parameters.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

### Additional Details
Issue is explained in
https://github.com/aws/aws-sam-cli/issues/139#issuecomment-334977285

**Comment by jfuss** [comment]
You can do this today by providing `--invoke-image` and adding your custom env vars into an image you build locally. This would be the way to achieve custom things within the build image. This is to keep the local from SAM CLI as close to Lambda as possible, which helps reduce issues where "it works locally" but then would fail in Lambda directly.
