### ISSUE TITLE
Feature request: Template enhancement should adhere to cfn-lint rules

### ISSUE THREAD

**Issue by corey-cole** [aws/aws-sam-cli#4695]
### Describe your idea/feature/enhancement

I would like SAM CLI, when enhancing templates, to respect cfn-lint rules down at the informational level.
For example, when adding ApplicationInsights monitoring, the [resource group name](https://github.com/aws/aws-sam-cli/blob/9a74f02a3e118aaee0b76e3b0869396849277856/samcli/lib/init/template_modifiers/application_insights_template_modifier.py#L29) uses `Fn::Join`.  The cfn-lint rule `I1022` states "Prefer a sub instead of Join when using a join delimiter that is empty".

When SAM CLI includes constructs that violate cfn-rules, it results in false-positives during development and or manual toil to fix something that we already know how to fix.

### Proposal

The unit tests for template creation should execute cfn-lint and check for "I" level results.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model): No

**Comment by jfuss** [comment]
Seems reasonable. We can update this.

**Comment by qingchm** [comment]
Hey there, this has been addressed in our most recent release 1.79.0 (https://github.com/aws/aws-sam-cli/releases/tag/v1.79.0). Closing the issue here. Thanks for the improvement idea!
