### ISSUE TITLE
Bug: sam local invoke - NotFound

### ISSUE THREAD

**Issue by BritnessDev** [aws/aws-sam-cli#4711]
### Description:

I downloaded a Lambda function from AWS Lambda using AWS Toolkit in Visual Studio Code
And tried debugging. but I faced out following error
**Invoking index.handler (nodejs14.x)
Error: 404 Client Error: Not Found ("page not found")
... ... ...
An unexpected error was encountered while executing "sam local invoke".**

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`:   SAM CLI, version 1.73.0
3. AWS region:  US-east2

sam --info
{
  "version": "1.73.0",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.19041-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "17.03.1-ce-rc1",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}

![image](https://user-images.githubusercontent.com/108443885/218663117-68ea2da7-2099-4012-965d-6e21ffb216b8.png)

![image](https://user-images.githubusercontent.com/108443885/218663157-76857c26-4d32-49c5-88d3-bfc6f2ad75ce.png)

**Comment by BritnessDev** [comment]
Please let me know about the solution of this issue... This is very urgent thing for me.

**Comment by lucashuy** [comment]
Hi, can you try upgrading your Docker version? Noticed that you are using `17.03.1-ce-rc1`, which is a release candidate version from 2017.

**Comment by lucashuy** [comment]
Closing due to fix/workaround provided. Please feel free to open another issue if you have any other problems or potential bugs to report.
