### ISSUE TITLE
SAM cli defaults to creating an x86 function even when running on an Arm host 

### ISSUE THREAD

**Issue by AGSaidi** [aws/aws-sam-cli#4733]
Why not default creations to Arm when running on an Arm host? That local invokes will work by default which now if you don't specify Arm and then try to run your newly created function an unclear error message is provided. 

```
$ sam init
Which template source would you like to use?
	1 - AWS Quick Start Templates
	2 - Custom Template Location
Choice: 1

Choose an AWS Quick Start application template
	1 - Hello World Example
...
Template: 1

Use the most popular runtime and package type? (Python and zip) [y/N]: y
Would you like to enable X-Ray tracing on the function(s) in your application?  [y/N]:
Would you like to enable monitoring using CloudWatch Application Insights?
For more info, please view https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-application-insights.html [y/N]:

$ cd sam-app

$ sam local invoke
Invoking app.lambda_handler (python3.9)
Local image was not found.
Removing rapid images for repo public.ecr.aws/sam/emulation-python3.9
Building image...............................................................................................................................................
Failed to build Docker Image
NoneType: None
Error: Error building docker image: The command '/bin/sh -c mv /var/rapid/aws-lambda-rie-x86_64 /var/rapid/aws-lambda-rie && chmod +x /var/rapid/aws-lambda-rie' returned a non-zero code: 1
```

**Comment by jfuss** [comment]
From the pr: "Lambda defaults to x86 if there is no architecture specified in the template file, what's happening here is the template file defaults to x86 on an Arm host."

I understand that, but the reason we are doing that is 1) back compat to what happened before arm was supported (which isn't the biggest thing for init templates). 2) SAM CLI behaves like AWS Lambda in which if the Arch is not specified we default to x86. 

If you want to have an arm function, why not specify this in the `sam init` command?

**Comment by mndeveci** [comment]
As @jfuss stated out earlier, we are instantiating x86 function to keep backwards compatibility. 

We don’t want customers to create functions on different architectures depending on their machines implicitly since function’s architecture has no direct relation with developer’s machine. And it may drive further confusion for customers if they are already have/working on x86 functions in their other stacks.

You can always select the architecture by providing `architecture` flag during `sam init`.
