### ISSUE TITLE
sam-validate fails when date is unquoted in `AWSTemplateFormatVersion: 2010-09-09`

### ISSUE THREAD

**Issue by ljacobsson** [aws/aws-sam-cli#4735]
### Description
![image](https://user-images.githubusercontent.com/7579097/219804835-1d298431-b788-42a0-bb07-2481bd0a2b4a.png)

When using third party tools, like sam-patterns-cli, evb-cli, etc to modify the SAM templates there's a conversion happening between YAML->JSON->YAML. This leaves the `2010-09-09` part unquoted.

`sam build and sam deploy` works, but `sam validate` fails with: 
```
Template schema validation reported the following errors: [AWSTemplateFormatVersion] datetime.date(2010, 9, 9) is not of type 'string', [AWSTemplateFormatVersion] datetime.date(2010, 9, 9) is not one of ['2010-09-09']
```

I'd expect sam validate to be successful if the deploy is successful

**Comment by hnnasit** [comment]
This issue has been addressed by the changes released in SAM CLI 1.75.0. Please check if the fix works and feel free to open a new issue if the problem still exists.
