### ISSUE TITLE
Bug: sam build - ImportError280281[Container]

### ISSUE THREAD

**Issue by ashkumarverma** [aws/aws-sam-cli#4736]
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by sriram-mv** [comment]
Thanks for raising this issue, we need more information on this front before we can attempt to debug. What template are you operating on? which runtime? Are you on the latest version of `aws-sam-cli` ?

**Comment by sriram-mv** [comment]
I'm going to close this issue, could you re-open with more information?
