### ISSUE TITLE
Bug: sam build - ImportError

### ISSUE THREAD

**Issue by yadavManvendra** [aws/aws-sam-cli#4737]
### Description:

Error: cannot import name 'IS_STR' from 'samtranslator.model.types' (/root/.pyenv/versions/3.7.16/lib/python3.7/site-packages/samtranslator/model/types.py)

### Steps to reproduce:
sam build --template-file ${TEMPLATE_PATH}

### Observed result:
An unexpected error was encountered while executing "sam build".
Command did not exit successfully sam build --template-file ${TEMPLATE_PATH} exit status 1

### Expected result:
Build should get succeed

pip install aws-sam-translator==1.57.0

1. OS: ### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
Amazon Linux
2. `sam --version`:
3. AWS region: us-east-1

```

**Comment by sriram-mv** [comment]
do you have the latest version of `aws-sam-cli` ? Could you fill us in on which runtime you are operating on?

**Comment by sriram-mv** [comment]
Please re-open with full details, I'm closing as this is not actionable. Also looks like you are running an older version of aws-sam-cli as referenced with aws-sam-translator version number.

https://github.com/aws/serverless-application-model/releases/tag/v1.58.1 was released which added back the breaking change you have mentioned.

Please update to the latest AWS SAM CLI and this error should go away. Please re-open an issue if you are continuing to face issues on this front.

Thank you!
