### ISSUE TITLE
Bug: sam build - DockerImagePullFailedException

### ISSUE THREAD

**Issue by kumarraja2k05** [aws/aws-sam-cli#4763]
Could not find public.ecr.aws/sam/build-python3.7:latest-Architecture image locally and failed to pull it from docker. -->

### Description:
I'm using the command: - **sam build --use-container --template-file serverless_template.yaml** 
Its showing the error 
Error: Could not find public.ecr.aws/sam/build-python3.7:latest-Architecture image locally and failed to pull it from docker.
It should not show error as I have passed the template filename with path speicified.

### Observed result:

Starting Build inside a container
Building codeuri: C:\Users\kraja\Watchguard Work\dnsw-networks-svc\application\functions\health runtime: python3.7 metadata: {} architecture: Architecture functions: NetworkSvcHealthFn

Error: Could not find public.ecr.aws/sam/build-python3.7:latest-Architecture image locally and failed to pull it from docker.

### Expected result:

Should build Successfully.

1. OS: Windows
2. `sam --version`: 1.72.0
3. AWS region: us-west-2

```
# Paste the output of `sam --info` here
```
{
  "version": "1.72.0",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.19041-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.21",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}

**Comment by sriram-mv** [comment]
```
public.ecr.aws/sam/build-python3.7:latest-Architecture
```

and 


```
Building codeuri: C:\Users\kraja\Watchguard Work\dnsw-networks-svc\application\functions\health runtime: python3.7 metadata: {} architecture: Architecture functions: NetworkSvcHealthFn
```

are your clues.

Check the template.yaml that you have provided and provide a valid architecture such as x86_64 or arm64 and not `Architecture`

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-architectures
