### ISSUE TITLE
Bug: sam local start-lambda does not override environment variables defined in template

### ISSUE THREAD

**Issue by Pipo93** [aws/aws-sam-cli#4764]
### Description:
I have a Lambda function defined with CDK. When starting this Lambda locally and specifying a json file with values for the Lambda function's environment variables  those values are not being applied. Using the same environment file when invoking the Lambda it's working fine.

### Steps to reproduce: 

I have a local.json file with this content:
```
{
  "Parameters": {
    "MY_ENV_VAR": "test-value-new",
  }
}
```

Building the template based on CDK stack: `cdk synth MyLambdaStack --no-staging > template.yml`. The template also has those environment variables defined:
```
...
      Environment:
        Variables:
          MY_ENV_VAR: test-value
...          
```

Then I started the lambda locally: `sam local start-lambda -n ./local.json --force-image-build`

And finally invoking the lambda locally: `sam local invoke -e events/myEvent.json`

### Observed result:

`logger.info(process.env.MY_ENV_VAR)` prints `test-value` 

### Expected result:

`logger.info(process.env.MY_ENV_VAR)` prints `test-value-new` 

When invoking with environment variables (`sam local invoke -e events/myEvent.json -n ./local.json`) it works as expected but it should also work without so that I can invoke it locally from other services as well.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```
{
  "version": "1.74.0",
  "system": {
    "python": "3.8.16",
    "os": "macOS-13.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.21",
    "aws_cdk": "2.50.0 (build 4c11af6)",
    "terraform": "Not available"
  }
}
```

**Comment by sriram-mv** [comment]
Thanks for raising the issue! Trying to understand what you are trying to do deeper. 

`sam local start-lambda` is about starting the lambda locally such that its accessible over the AWS CLI or through the AWS SDK by supplying a local config.

are you trying to start a lambda locally and then try to locally invoke again with sam? if that is the case, `sam local invoke` by itself should do the trick.

**Comment by sriram-mv** [comment]
I am only going to look at your `sam local start-lambda` usecase and I could not reproduce it. I was able to return the new env var as part of my testing.

>> Since I can't run it against the same configuration I need a way to override the environment variables when starting the lambda

What do you mean by this? you can override with env vars in both `start-lambda` and `local invoke`

**Comment by hawflau** [comment]
@Pipo93 I also could not reproduce the issue for `sam local start-lambda`. There is no difference in how `sam local invoke` and `sam local start-api` handle the local env var file. Can you provide more info to help us reproduce the issue?

**Comment by moelasmar** [comment]
Closing given no response. Please re-open or create a new issue if you still facing the same problem.
