### ISSUE TITLE
Bug: sam list stack-outputs

### ISSUE THREAD

**Issue by robwdux** [aws/aws-sam-cli#4768]
### Description:

I would like to use `sam list stack-outputs --config-env <value>` (stack name is set in samconfig.toml) - not supported according to `--help` given stack name is listed as required and therefore cannot just specify config env.

```
Usage: sam list stack-outputs [OPTIONS]

  Get the stack outputs as defined in the SAM/CloudFormation template.

Options:
  --stack-name TEXT      Name of corresponding deployed stack.   [required]
  --config-env TEXT      The environment name specifying the default parameter
...
```

### Steps to reproduce:

```
# samconfig.toml

[default.deploy.parameters]
region           = us-east-1
stack_name = mystack
```
`sam list stack-outputs --config-env default`

### Observed result:

```
# expect this to work
❯ sam list stack-outputs --debug --config-env <value>
2023-02-24 18:29:28,816 | Config file location: /path/to/samconfig.toml
2023-02-24 18:29:28,816 | Loading configuration values from [<value>.['list', 'stack-outputs'].parameters] (env.command_name.section) in config file at '/path/to/samconfig.toml'...
2023-02-24 18:29:28,827 | Configuration values successfully loaded.
2023-02-24 18:29:28,827 | Configuration values are: {}
Usage: sam list stack-outputs [OPTIONS]
Try 'sam list stack-outputs -h' for help.

Error: Missing option '--stack-name'.

# what actually works
sam list stack-outputs --debug --region <region> --stack-name <stack-name>
```

`sam list stack-outputs` should not require `--stack-name` if passed `--config-env`, throw an error if stack name is not available.

`--config-env` does not appear to be parsed at all.

### Expected result:

Expect that, with a samconfig.toml which specifies minimally region and stack name for the following command to return the stack outputs.

`sam list stack-outputs --config-env <value>`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

```
❯ sam --info
{
  "version": "1.74.0",
  "system": {
    "python": "3.8.16",
    "os": "macOS-12.6.2-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "1.3.8"
  }
}
```

`Add --debug flag to command you are running`

**Comment by hnnasit** [comment]
Hi @robwdux, you can specify the stack_name and region under `[<value>.global.parameters]` for `sam list stack-outputs --config-env <value>` to pick up the parameter values. For example:
```
[default.global]
[default.global.parameters]
stack_name = "myStack"
region = "us-east-1"
```
Please let us know if you have more questions.

**Comment by robwdux** [comment]
@hnnasit as mentioned, stack name is required and config env is not parsed. Even when providing stack name and config env it will result in an error not finding the stack because it defaults to UE2 region instead of what is specified in samconfig.toml in my case. Also, see the debug output provided, I interpret it as no config is read from Samconfig.toml

**Comment by sriram-mv** [comment]
The issue is

```
# samconfig.toml

[default.deploy.parameters]
region           = us-east-1
stack_name = mystack
```

the stack_name is set under `default.deploy.parameters` but you are running sam list command, which means you need to use `default.list.parmeters` or list the stack_name commonly under `default.global.parmeters`


```
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = mystack
region = us-east-1
```

Should work.

**Comment by robwdux** [comment]
🤦 Apologies for not catching making the distinction about setting values under global.

Thank you @hnnasit and @sriram-mv for pointing out my user error.
