### ISSUE TITLE
Bug: golang sam local start-api doesn't work without a .aws-sam from sam build

### ISSUE THREAD

**Issue by danludwig** [aws/aws-sam-cli#4784]
### Description:
Running `sam local start-api` without a `.aws-sam` build output in a default go1.x runtime results in an error when the api is invoked. The error does not occur when running `make build` or `sam build`, but does recur when the `.aws-sam` output is removed.

### Steps to reproduce:
The following steps were executed and [pushed here ](https://github.com/danludwig/aws-sam-cli-bug-reports/tree/master/v1.75.0/golang-sam-local-start-api) for a reference reproduction.
```
sam init --name sam-app0 --runtime go1.x
```
- Select (1) AWS Quick Start Templates
- Select (1) Hello World Example
- Select remaining (N) defaults
```
cd sam-app0
```
- Do not run `sam build` or `make build`, if there is a `.aws-sam` folder, delete it
```
sam local start-api --debug
curl http://localhost:3000/hello
```

### Observed result:
From `curl`:
> {"message":"Internal server error"}

The CLI output is:
> You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. If you used sam build before running local commands, you will need to re-run sam build for the changes to be picked up.

> 2023-02-28 16:57:04,757 | Found one Lambda function with name 'HelloWorldFunction'
> 2023-02-28 16:57:04,757 | Invoking hello-world (go1.x)
> 2023-02-28 16:57:04,757 | Resolving code path. Cwd=/Users/dan/code/github/danludwig/aws-sam-cli-bug-reports/v1.75.0/golang-sam-local-start-api, CodeUri=/Users/dan/code/github/danludwig/aws-sam-cli-bug-reports/v1.75.0/golang-sam-local-start-api/hello-world
> 2023-02-28 16:57:04,757 | Resolved absolute path to code is /Users/dan/code/github/danludwig/aws-sam-cli-bug-reports/v1.75.0/golang-sam-local-start-api/hello-world
> 2023-02-28 16:57:04,764 | Reuse the created warm container for Lambda function 'HelloWorldFunction'
> 2023-02-28 16:57:04,769 | Lambda function 'HelloWorldFunction' is already running
> 2023-02-28 16:57:04,771 | Starting a timer for 5 seconds for function 'HelloWorldFunction'
> START RequestId: 1fb75e5a-dc58-4676-80bf-164ea836860e Version: $LATEST
> fork/exec /var/task/hello-world: no such file or directory: PathError
> null
> 2023-02-28 16:57:04,805 | Unable to find Click Context for getting session_id.
> 2023-02-28 16:57:04,806 | Lambda returned empty body!
> 2023-02-28 16:57:04,806 | Invalid lambda response received: Invalid API Gateway Response Keys: {'errorMessage', 'errorType'} in {'errorMessage': 'fork/exec /var/task/hello-world: no such file or directory', 'errorType': 'PathError'}
> 2023-02-28 16:57:04 127.0.0.1 - - [28/Feb/2023 16:57:04] "GET /hello HTTP/1.1" 502 -
> END RequestId: 1fb75e5a-dc58-4676-80bf-164ea836860e
> REPORT RequestId: 1fb75e5a-dc58-4676-80bf-164ea836860e  Init Duration: 0.19 ms  Duration: 16.96 ms      Billed Duration: 17 ms  Memory Size: 128 MB     Max Memory Used: 128 MB

### Expected result:
From `curl`:
> Hello, ${IP_ADDRESS}

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac Intel 2019
2. `sam --version`: 1.75.0
3. AWS region: localhost

```
{
  "version": "1.75.0",
  "system": {
    "python": "3.11.2",
    "os": "macOS-13.2.1-x86_64-i386-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.21",
    "aws_cdk": "Not available",
    "terraform": "1.3.7"
  }
}
```

**Comment by sriram-mv** [comment]
for compiled languages specifically, one need to build before trying to local invoke. This is not a bug per se, but how we envision users using the tool as workflow i.e building before local invoking. Would something like auto-build before invoke be what you are referring to?

**Comment by mndeveci** [comment]
As @sriram-mv mentioned, `sam build` should be run first for compiled languages. Even for interpreted ones, if function has external dependencies, `sam build` should run first in order `sam local` to succeed.

Resolving this issue due to inactivity.

**Comment by bujosa** [comment]
@mndeveci @sriram-mv Thank u so much
