### ISSUE TITLE
Bug: sam deploy --guided doesn't remove conflicting properties

### ISSUE THREAD

**Issue by mildaniel** [aws/aws-sam-cli#4841]
### Description:

When running a guided deployment and saving the parameters back to a `samconfig.toml` that already includes a `resolve_s3=true` option, the S3 bucket option is also added, making the next `sam deploy` without a guided flag fail.

### Steps to reproduce:

1.  Initialize any hello world application using `sam init`.
2. Run `sam build` 
3. Run `sam deploy --guided` and ensure to save to a `samconfig.toml` file
4. Run `sam deploy` again without the --guided flag

### Observed result:

Error message about conflicting arguments
`Error: Cannot use both --resolve-s3 and --s3-bucket parameters in non-guided deployments. Please use only one or use the --guided option for a guided deployment.`

### Expected result:

Deploy should succeed.

The issue seems to be that when writing to the config file,  the `resolve_s3=true` option isn't cleaned up even though AWS SAM CLI creates a managed bucket and uses that bucket for subsequent deployments.

The fix is adding a step here: https://github.com/aws/aws-sam-cli/blob/develop/samcli/commands/deploy/guided_config.py#L66 to remove these kinds of conflicting parameters before flushing the config.

**Comment by qingchm** [comment]
This is fixed by the latest release [1.78.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.78.0) Please have a look! Feel free to re-open if there are other issues regarding this!

**Comment by mlowy** [comment]
I seem to face this issue in github actions using setup-sam@v2 : 
`sam package \
    --s3-bucket ${TESTING_ARTIFACTS_BUCKET} \
    --region ${TESTING_REGION} \
    --output-template-file packaged-testing.yaml
    --debug
  shell: /usr/bin/bash -e {0}
  env:
    TESTING_ARTIFACTS_BUCKET: aws-sam-cli-managed-dev-pipeline-artifactsbucket-xyz..
    TESTING_REGION: eu-central-1
......

Error: Cannot use both --resolve-s3 and --s3-bucket parameters. Please use only one.
Error: Process completed with exit code 1.
     `

**Comment by ruminize** [comment]
> SAM CLI, version 1.90.0

version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
  build:
    commands:
      - . ./assume-role.sh ${ENV_PIPELINE_EXECUTION_ROLE} deploy
      - sam deploy --stack-name ${ENV_STACK_NAME}
                    --template ${ENV_TEMPLATE}
                    --capabilities CAPABILITY_IAM
                    --region ${ENV_REGION}
                    --s3-bucket ${ENV_BUCKET}
                    --no-fail-on-empty-changeset
                    --role-arn ${ENV_CLOUDFORMATION_EXECUTION_ROLE}

Running command sam package --s3-bucket ${TESTING_ARTIFACT_BUCKET} --region ${TESTING_REGION} --output-template-file packaged-test.yaml

Cannot use both --resolve-s3 and --s3-bucket parameters. Please use only one.

**Comment by hawflau** [comment]
Reopening the issue for investigation

**Comment by hawflau** [comment]
Hi @ruminize @mlowy, can you please confirm `resolve_s3` is not set in the `samconfig.toml` in your project? You should remove it if it exists. Please feel free to open a new issue if that doesn't resolve your issue.

Closing again since the new comments are about non-guided deploy.
