### ISSUE TITLE
Bug: `sam validate --lint` does not pick up region from shell

### ISSUE THREAD

**Issue by jfuss** [aws/aws-sam-cli#4844]
### Description:
When running `sam validate --lint`, SAM CLI will call out to CFN Lint to run it's linting. We set the region if it is passed into SAM CLI [here](https://github.com/aws/aws-sam-cli/blob/dd33a030d6a383eb5147b1447ab39d6587668d36/samcli/commands/validate/validate.py#L145). If you do `sam validate --lint --region <region>` things will work as expected. However, if you have the region in your shell, like `AWS_DEFAULT_REGION`, we do not pass any region to CFN Lint. Causing CFN Lint to use it default region: https://github.com/aws-cloudformation/cfn-lint/blob/55752dc40ee5935704c48ad7422dc98e1e71c88f/src/cfnlint/config.py#L654. 

This is super confusing when you get an error for a specific region but you think you are running on a different region (due to it being set on your shell). 

This might be a thing to ask CFN Lint to support directly. To me it makes sense that you can set the region in your shell and things would just work. At the very least, we need to solve this within SAM CLI as all other commands use the boto3 region resolution making this work as expected for customers.

**Comment by jfuss** [comment]
PR to support this directly within CFN Lint: https://github.com/aws-cloudformation/cfn-lint/issues/2617

**Comment by hawflau** [comment]
linking to the PR directly https://github.com/aws-cloudformation/cfn-lint/pull/2618

**Comment by jfuss** [comment]
PR was merged in CFN Lint. We need to update CFN Lint and release now.

**Comment by hawflau** [comment]
Closing as the fix has been released in AWS SAM CLI v1.77.0
