### ISSUE TITLE
Sam config Conditions based on Parameters dont work

### ISSUE THREAD

**Issue by FireAndIceFrog** [aws/aws-sam-cli#4852]
Following the example in the AWS documentation[ here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html)  fails.

The parameter's value is never accounted for and always either uses the default value or no value at all.

I have attempted to use this in my system, we have a paramter (envType) and a condition (useLocalDevelopment)

Then I use the condition "useLocalDevelopment" to change the codeUri to a different AWS::SERVERLESS::FUNCTION.

This always uses the default value or no value (if there is no default defined) for the !Equals condition.

**Comment by mndeveci** [comment]
Thanks for reporting this issue, can you provide an example template so that we can try to re-produce this issue?

**Comment by FireAndIceFrog** [comment]
this is a simplified version

`AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Everbridge Contact integration pipeline
Parameters:
  EnvType:
    Description: Environment type.
    Default: test
    Type: String
    AllowedValues:
      - prod
      - test
    ConstraintDescription: must specify prod or test.
Conditions:
  CreateProdResources: !Equals
    - !Ref EnvType
    - prod
Resources:
  ContactIntegrationApi:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 256
      Timeout: 900
      Runtime: python3.9
      Architectures:
        - arm64
      Handler: app.lambda_handler
      CodeUri: !If CreateProdResources [functions/prod/app/,functions/dev/app/]
`

I use sam build and sam deploy, but when I run sam build it always uses the "dev" file path even if my parameter overrides say otherwise

**Comment by hawflau** [comment]
Hi @FireAndIceFrog for the intrinsic `!If` on the last line, it should be `!If [CreateProdResources, functions/prod/app/,functions/dev/app/]`. I tried and could produce the correct result. Could you please try again?

**Comment by mildaniel** [comment]
The issue should be resolved by @hawflau's response. If anything else comes up, please open a new issue!
