### ISSUE TITLE
Use faster `get_managed_policy_map` when calling SAM transform locally

### ISSUE THREAD

**Issue by hoffa** [aws/aws-sam-cli#4858]
The SAM transform library now supports faster local transforms by only loading managed policies when not already [bundled within the transform library](https://github.com/aws/serverless-application-model/blob/develop/samtranslator/internal/data/aws_managed_policies.json) (see https://github.com/aws/serverless-application-model/pull/2839), instead of loading them every time. It also minimizes annoying credential expiry issues.

To migrate:

1. Set [`managed_policy_map`](https://github.com/aws/serverless-application-model/blob/e2dd6f63d00b60ccce5427196abab3f7b60ce9d9/samtranslator/translator/translator.py#L48) to `None`.
2. Create a function `get_managed_policy_map` that loads managed policies and caches the result:

    ```python
    @lru_cache(maxsize=None)
    def get_managed_policy_map() -> Dict[str, str]:
        return managed_policy_loader.load()
    ```

4. Pass `get_managed_policy_map` to the new [`get_managed_policy_map`](https://github.com/aws/serverless-application-model/blob/e2dd6f63d00b60ccce5427196abab3f7b60ce9d9/samtranslator/translator/translator.py#L109) argument.

See [`transform.py`](https://github.com/aws/serverless-application-model/blob/develop/samtranslator/translator/transform.py) for an example.

**Comment by hawflau** [comment]
Released in AWS SAM CLI v1.77.0. Closing
