### ISSUE TITLE
lsBug: sam local invoke - FileNotFoundError

### ISSUE THREAD

**Issue by rsleSO** [aws/aws-sam-cli#4866]
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by hawflau** [comment]
Hi @rsleSO Can you provide more info about the error you saw?

**Comment by rsleSO** [comment]
Seems minor mistake was on my site, invalid, closing.
