### ISSUE TITLE
Bug: sam validate incorrect reports the optional Rules: section at the CloudFormation root as 'unexpected'

### ISSUE THREAD

**Issue by andyloughran** [aws/aws-sam-cli#4869]
### Description:

If you specify the optional `Rules:` section at the template root, then `sam validate` complains with the message: `Template schema validation reported the following errors: [.] Additional properties are not allowed ('Rules' was unexpected)`

Rules appear to be valid on the CloudFormation template schema: 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/rules-section-structure.html

### Steps to reproduce:
Add a Rules: section to your base template with a few example rules.

### Observed result:
(Cannot provide output)
`Template schema validation reported the following errors: [.] Additional properties are not allowed ('Rules' was unexpected)`

### Expected result:
No error for a Rules section.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
```
{
  "version": "1.73.0",
  "system": {
    "python": "3.11.2",
    "os": "macOS-13.2.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.23",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}
```

**Comment by hawflau** [comment]
Hi @andyloughran, can you provide a template to help reproduce the issue?

**Comment by moelasmar** [comment]
Closing given no response. Please re-open or create a new issue if you still facing the same problem.
