### ISSUE TITLE
sam deploy won't accept a fifo as config file

### ISSUE THREAD

**Issue by nVlast** [aws/aws-sam-cli#4875]
Trying to pass a fifo as config file to sam deploy results to an error:
```bash
$ sam deploy --config-file <(echo test)
Error: Config file /dev/fd/63 does not exist or could not be read!
```
This was tested with version 1.76.0.

While trying to understand what's going on, I tracked the issue down to [this line](https://github.com/aws/aws-sam-cli/blob/a2a4540427806b11e2a508d4d118d517d296efef/samcli/cli/cli_config_file.py#L136) where the `is_file` check fails.

I am not sure whether this is intentional, but I'm reporting it because it used to work with earlier versions (I think before 1.55.0)

**Comment by hawflau** [comment]
Hey @nVlast thanks for raising the issue. I confirmed that, if the is_file check is omitted, a named pipe can be used for `--config-file`. Marking it as bug and we will prioritize to fix it.

**Comment by hawflau** [comment]
Steps to reproduce:
- in a sam project with a default `samconfig.toml`:
```
mkfifo testpipe
cat samconfig.toml >testpipe
```
- open another terminal session and cd into the sam project:
```
sam build --config-file ./testpipe
```

**Comment by hawflau** [comment]
@nVlast while we will prioritize, please also free feel to raise a PR if you'd like to contribute

**Comment by nVlast** [comment]
Hey @hawflau, I'd like to raise a PR, thanks! I think that we could just enable accepting pipes as config files to address this bug. Do you think we should remove the `is_file` check altogether?

**Comment by hawflau** [comment]
I'm think we can check:
- if it is a file or a named pipe, the proceed
- otherwise, throw an exception
