### ISSUE TITLE
Bug: `sam list resources` command only works for first 100 resources.

### ISSUE THREAD

**Issue by awood45** [aws/aws-sam-cli#4909]
### Description:

When I run `sam list resources` on a template with > 100 resources (~140 in this case) a number of resources have "-" as the PhysicalResourceId in the resulting map.

I strongly wager that this is an issue with pagination, because I believe that `DescribeStackResources` returns 100 resources per page, and you need to look for a response truncation and continue to iterate if the response is truncated (has a NextToken value or similar).

### Steps to reproduce:

1. Create a SAM/CFN template with more than 100 resources.
2. Deploy it by `sam deploy` or any other means.
3. Run `sam list resources` against that template, and note that "-" is present for `num_resources - 100` resources.

### Observed result:

Described above in detail.

### Expected result:

All resources with valid `PhysicalResourceId` values should have them present in the response.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS
4. `sam --version`: `1.75.0`
5. AWS region: `eu-south-1`

```
# Paste the output of `sam --info` here
{
  "version": "1.75.0",
  "system": {
    "python": "3.11.2",
    "os": "macOS-12.6.2-x86_64-i386-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "2.69.0 (build 60a5b2a)",
    "terraform": "Not available"
  }
}
```

`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
thanks @awood45 .
