### ISSUE TITLE
Bug: sam build - FileNotFoundError

### ISSUE THREAD

**Issue by Xantra** [aws/aws-sam-cli#4947]
### Description:

I'm trying to build the custom runtime for Powershell on Lambda using the following repo: [https://github.com/awslabs/aws-lambda-powershell-runtime](url)
I encounter the following error when trying to build: Error: [Errno 2] No such file or directory: 'C:\\Users\\REDACTED\\aws-lambda-powershell-runtime\\examples\\demo-runtime-layer-function\\.aws-sam\\build\\PwshRuntimeLayer\\.\\powershell\\Modules\\PackageManagement\\DSCResources\\MSFT_PackageManagement\\MSFT_PackageManagement.strings.psd1'

### Steps to reproduce:

git clone https://github.com/awslabs/aws-lambda-powershell-runtime.git
cd aws-lambda-powershell-runtime/examples/demo-runtime-layer-function
sam build --parallel --use-container

### Observed result:

[https://imgur.com/eM7jKne](url)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: SAM CLI version 1.78.0
3. AWS region: eu-west1

```
# Paste the output of `sam --info` here
```
{
  "version": "1.78.0",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.19041-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.23",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}
`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
thanks @Xantra for raising this issue. Could you please rerun the `sam build` command again with `--debug` parameter and share the full logs with us.
Also can you run `docker info` and share the output with us
