### ISSUE TITLE
[Announcement] .NET Core 3.1 Runtime Deprecation

### ISSUE THREAD

**Issue by mildaniel** [aws/aws-sam-cli#4953]
### SAM CLI will stop supporting .NET Core 3.1 by May 3rd, 2023.
This runtime is no longer supported by [AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), and it is on the deprecation path. Users are not able to deploy/update these functions anymore.

## What is deprecation schedule?
After May 3rd 2023, SAM CLI will no longer allow customers to use deprecated runtimes within the CLI.

## Am I impacted by this deprecation?
You are impacted by this if you are still using the .NET Core 3.1 runtime. The recommendation is to upgrade these runtimes to a newer version which is supported by AWS Lambda.

For more information about supported runtimes by AWS Lambda, please check https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

AWS Lambda Builders will stop support using it as a library for .NET Core 3.1, see https://github.com/aws/aws-lambda-builders/issues/479 for more details.

**Comment by moelasmar** [comment]
Lambda already finished the phase 2 deprecation for .Net Core 3.1 on May 3, 2023 (Get more info about lambda runtimes deprecation policy [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy)). SAM CLI also deprecated supporting .Net Core 3.1 in the [latest release 1.89.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.89.0)
