### ISSUE TITLE
Feature request: How to use `beta_features = true` in `sam sync --code` command

### ISSUE THREAD

**Issue by mirumirumi** [aws/aws-sam-cli#4957]
### Describe your idea/feature/enhancement

I use cargo-lambda to build Rust with SAM.

I like to use the sam sync command to speed up development, but unfortunately I can't seem to use the `--code` and `--beta-features` options at the same time.
This means that the `--watch` option or `--resource-id` etc. will use CloudFormation, which will slow down the synchronization.

Is there a solution to this?

Thank you!

**Comment by hawflau** [comment]
Hey @mirumirumi, thanks for raising the issue. I've confirmed that it's a bug that `--beta-features` is not accepted for `sam sync`.

Meanwhile, you can use `SAM_CLI_BETA_RUST_CARGO_LAMBDA=1 sam sync --code`
