### ISSUE TITLE
Error : During sam deploy.

### ISSUE THREAD

**Issue by Ashoks22** [aws/aws-sam-cli#4988]
Hi,
I am facing an error for the following.sam deploy. After AWS Region ....... : I am getting error as mentioned below;
Please help to fix this error..

PS C:\Users\Ashok\pipeline_060423\sam-app> sam deploy --guided

Configuring SAM deploy
======================

        Looking for config file [samconfig.toml] :  Found
        Reading default arguments  :  Success

        Setting default arguments for 'sam deploy'
        =========================================
        Stack Name [sam-app]:
        AWS Region [US East (Ohio)]: 

Error: [InvalidTemplateException("'Resources' section is required")] 'Resources' section is required
Traceback:
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)

**Comment by qingchm** [comment]
Seems like you have an invalid template file in the location. Can you check the indentation to ensure that the Resources field exists in the template like the following? Thanks!
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
...
```

**Comment by sriram-mv** [comment]
Closing this issue as per @qingchm 's response. However, this experience can be improved to not create a traceback. Will flag this.

**Comment by Ashoks22** [comment]
HI everyone.
Thanks for your reply. This got resolved. I have added resources as per above suggestion, this got worked.
Thanks once again for your response and suggestions.
This is resolved now.
