### ISSUE TITLE
Layer conversion failed: Could not scan one or more directories; error on deploy

### ISSUE THREAD

**Issue by ManudeepHirigowdaTR** [aws/aws-sam-cli#5036]
**Description**
Deploying my application fails on lambda updating with a file permission error for a layer.
the code is working fine in local. having issue on ci/cd pipeline.
**Error message** Layer conversion failed: Could not scan one or more directories;

we are using AWS codebuild and code pipeline.

AWS-SAM-CLI versions tried - 1.79.0 and 1.80.0

**Comment by lucashuy** [comment]
Hi, thanks for opening this issue. Are you able to deploy the project outside of the CI/CD environment (ie. using `sam deploy` on your local machine)? Additionally, can you paste the contents of `sam --info` here, and if possible a project for us to be able to reproduce?

**Comment by ManudeepHirigowdaTR** [comment]
No this is done full automated on the virtual environment

**Comment by lucashuy** [comment]
Sorry for the late response, is there a project, template, and/or a set of steps that we can use to reproduce this?

**Comment by moelasmar** [comment]
Closing this issue. Feel free to open a new issue if the issue still persists.
