### ISSUE TITLE
typescript doesn't work with nestjs

### ISSUE THREAD

**Issue by lifthus** [aws/aws-sam-cli#5052]
First I tried with tsc and not worked.

Now I'm trying with esbuild which is supported with SAM officialy.

but it is same. 

I set all configuration correctly I think.

CodeUri, Handler, and Metadata as well.

when I use "sam build", my lambda function is generated well in .aws-sam.

but when I invoke the function in browser, it always says " can't find module lambda" , lambda which is my handler file.

anyone got any idea?

**Comment by lucashuy** [comment]
Thanks for opening this issue, can you post a sample template and steps to reproduce your issue by following the template?
```
<!-- Make sure we don't have an existing Issue that reports the bug you are seeing (both open and closed). 
If you do find an existing Issue, re-open or add a comment to that Issue instead of creating a new one. -->

### Description:
<!-- Briefly describe the bug you are facing.-->



### Steps to reproduce:
<!-- Provide detailed steps to replicate the bug, including steps from third party tools (CDK, etc.) -->



### Observed result:
<!-- Please provide command output with `--debug` flag set. -->



### Expected result:
<!-- Describe what you expected. -->



### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

<!-- Either provide the following info (for AWS SAM CLI v1.68.0 or before) or paste the output of `sam --info` (AWS SAM CLI v1.69.0 or after). -->

1. OS:
2. `sam --version`:
3. AWS region:

# Paste the output of `sam --info` here

`Add --debug flag to command you are running`

```

**Comment by lifthus** [comment]
I changed the device and my Lambda function transpiled with tsc works now, though I don't know what was the exact reason. 

sam build using esbuild still doesn't work but not about the problem I described above. it finds module correctly but there is an issue about **this** object binding.
