### ISSUE TITLE
Bug: sam init returns "Stopping generation because post_gen_project hook script didn't exit successfully"

### ISSUE THREAD

**Issue by justinpermar** [aws/aws-sam-cli#5057]
### Description:
```
➜ sam init --location https://github.com/aws-samples/cookiecutter-aws-sam-python


	SAM CLI now collects telemetry to better understand customer needs.

	You can OPT OUT and disable telemetry collection by setting the
	environment variable SAM_CLI_TELEMETRY=0 in your shell.
	Thanks for your help!

	Learn More: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html

project_name [Name of the project]: testing
include_safe_deployment [n]: 
env: python: No such file or directory
2023-04-21 11:07:52 Stopping generation because post_gen_project hook script didn't exit successfully
Error: An error occurred while generating this project : Hook script failed (exit status: 127)
```

### Steps to reproduce:

1. Install SAM CLI using homebrew: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html
2. Verify successful SAM install: `sam --version`
3. Attempt to generate project from template: `sam init --location https://github.com/aws-samples/cookiecutter-aws-sam-python`

### Observed result:
```
➜ sam init --debug --location https://github.com/aws-samples/cookiecutter-aws-sam-pythona
2023-04-21 11:22:13,869 | Config file location: /Users/jpermar/Developer/sam/samconfig.toml
2023-04-21 11:22:13,869 | Config file '/Users/jpermar/Developer/sam/samconfig.toml' does not exist
2023-04-21 11:22:13,869 | Using config file: samconfig.toml, config environment: default
2023-04-21 11:22:13,869 | Expand command line arguments to:
2023-04-21 11:22:13,869 | --location=https://github.com/aws-samples/cookiecutter-aws-sam-pythona --package_type=Zip --output_dir=. 
2023-04-21 11:22:14,008 | Parameters dict created with input given
2023-04-21 11:22:14,009 | {'template': 'https://github.com/aws-samples/cookiecutter-aws-sam-pythona', 'output_dir': '.', 'no_input': False, 'extra_context': {'architectures': {'value': ['x86_64']}}}
2023-04-21 11:22:14,009 | Baking a new template with cookiecutter with all parameters
2023-04-21 11:22:14,350 | Unable to find cookiecutter.json in the project. Downloading it directly without treating it as a cookiecutter template
2023-04-21 11:22:14,351 | Downloading project from https://github.com/aws-samples/cookiecutter-aws-sam-pythona to .
2023-04-21 11:22:14,351 | https://github.com/aws-samples/cookiecutter-aws-sam-pythona location is a source control repository
2023-04-21 11:22:14,672 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-04-21 11:22:14,674 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'f406bf87-98e2-43ee-be8a-40a9b14715c1', 'installationId': '6745f11f-aa23-4b75-a329-13d9d51b1eb0', 'sessionId': 'b4c8365a-fac9-4330-ad7b-e545bd98b52d', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.11.3', 'samcliVersion': '1.81.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam init', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 802, 'exitReason': 'ArbitraryProjectDownloadFailed', 'exitCode': 1}}]}
2023-04-21 11:22:15,171 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Please verify your location. The following types of location are supported:

* Github: gh:user/repo (or) https://github.com/user/repo (or) git@github.com:user/repo.git
          For Git repositories, you must use location of the root of the repository.

* Mercurial: hg+ssh://hg@bitbucket.org/repo

* Http(s): https://example.com/code.zip

* Local Path: /path/to/code.zip
```

### Expected result:
Successful project creation.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
```
➜ brew --version
Homebrew 4.0.14
Homebrew/homebrew-core (git revision 3a7cd771717; last commit 2023-04-21)
➜  python --version
Python 3.9.16
➜  brew info aws-sam-cli
==> aws-sam-cli: stable 1.81.0 (bottled)
CLI tool to build, test, debug, and deploy Serverless applications using AWS SAM
https://aws.amazon.com/serverless/sam/
/Users/jpermar/Developer/homebrew/Cellar/aws-sam-cli/1.81.0 (8,782 files, 204.9MB) *
  Poured from bottle on 2023-04-21 at 09:52:07
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/aws-sam-cli.rb
License: Apache-2.0
==> Dependencies
Build: rust ✘
Required: python-typing-extensions ✔, python@3.11 ✔, six ✔
==> Analytics
install: 19 (30 days), 6,237 (90 days), 7,432 (365 days)
install-on-request: 19 (30 days), 6,232 (90 days), 7,427 (365 days)
build-error: 0 (30 days)
```

1. OS:
Mac Ventura 13.2.1
4. `sam --version`:
SAM CLI, version 1.81.0
6. AWS region:
us-east-1

```
# Paste the output of `sam --info` here
{
  "version": "1.81.0",
  "system": {
    "python": "3.11.3",
    "os": "macOS-13.2.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}
```

`Add --debug flag to command you are running`

**Comment by lucashuy** [comment]
Thanks for opening this issue! This line (`env: python: No such file or directory`) is interesting, seems like its not picking up the Python version that was bundled with SAM CLI and is instead trying to find it globally. I can replicate this with both the core and AWS taps for SAM CLI.

**Comment by mndeveci** [comment]
Thanks for creating this issue @justinpermar ,

The template that you tried to use has hooks configuration, which tries to run a python script here (https://github.com/aws-samples/cookiecutter-aws-sam-python/blob/master/hooks/post_gen_project). And if you don't have a python executable in your `$PATH` environment variable, `sam init` will fail since it can't complete the template generation.

I would recommend adding a python executable to your `$PATH` environment variable and re-running `sam init` again.

Please let us know if you have further questions.

**Comment by justinpermar** [comment]
@mndeveci I can't say that makes sense to me... as you saw in my original post, I printed out my python version:

```
python --version
Python 3.9.16
```

**Comment by justinpermar** [comment]
ok interesting... you're comment made me think a bit more... I've resolved my own install issue, but I think perhaps there's more work to be done on SAM for this case. Here's what was going on...

1. I Installed `aws-sam-cli` using brew: https://formulae.brew.sh/formula/aws-sam-cli. That package has a dependency on `python@3.11`. Please note that in my original post you'll see `sam --info` prints out  `"python": "3.11.3"`.
2. Python in my PATH, as noted above, is python3.9.
3. What's unclear to me is the "dependency resolution" process that `sam init --location https://github.com/aws-samples/cookiecutter-aws-sam-python` uses at that point... all I can tell you is that it doesn't work.
4. To fix this issue, I "re-installed" SAM using instructions here: https://awslabs.github.io/aws-lambda-powertools-python/2.14.1/. specifically,
```
pip install aws-lambda-powertools\[all\]
pipenv install --dev "aws-lambda-powertools[aws-sdk]"
pipenv shell
```
5. Re-run the original command which now succeed: `sam init --location https://github.com/aws-samples/cookiecutter-aws-sam-python`

**Comment by mndeveci** [comment]
@justinpermar thanks for the details, one quick recommendation from my side, can you try it with our PKG installers which is recomended way of installing SAM CLI. [The page you linked](https://aws.amazon.com/serverless/sam/) seems a little bit outdated, I will be contacting with our doc writers to update that. 

You can find PKG installer links down below;

- x86_64 (Intel) –[ aws-sam-cli-macos-x86_64.pkg](https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-macos-x86_64.pkg)
- arm64 (Apple) –[ aws-sam-cli-macos-arm64.pkg](https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-macos-arm64.pkg)

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html

**Comment by justinpermar** [comment]
hi @mndeveci I already tried that (version 1.81.0 installed from arm64 pkg). See a bit related info in my comment above (near the bottom I have "update").

**Comment by mndeveci** [comment]
@justinpermar can you try following example in the case where it fails to generate the template for you?

1. Create a basic script file with python shebang at the top
```
#!/usr/bin/env python

def main():
  print("Hello world....")

if __name__ == "__main__":
  main()
```
2. Set it executable by running `chmod +x {file_name}`
3. Try to run it `./{file_name}`

Looking at your original error, `Error: An error occurred while generating this project : Hook script failed (exit status: 127)` exit status 127 is indicating that "command not found". https://stackoverflow.com/questions/1763156/127-return-code-from
It is very likely that, your environment configuration is missing the python installation. You might have it in your terminal, but somehow it can't be found during execution.

**Comment by justinpermar** [comment]
bingo.

```
cat testing.sh
#!/usr/bin/env python

def main():
  print("Hello world....")

if __name__ == "__main__":
  main()
```

```
 ./testing.sh 
env: python: No such file or directory
```

**Comment by mndeveci** [comment]
I am not really expert on this but reading from the SO questions/answers, `/usr/bin/env` should look for `PATH` for the executable, which is there for your case but somehow `env` can't resolve it. You may search for what `pipenv` does to your session or environment and start from there (since it resolves your problem)?

**Comment by justinpermar** [comment]
ok the root cause is `alias python=python3`.

```
cat testing.sh
#!/usr/bin/env python3

def main():
  print("Hello world....")

if __name__ == "__main__":
  main()
```
```
~ ./testing.sh  
Hello world....
```

```
which python
python: aliased to python3.9
```

The good news here is that I can fix my own env issue... first, remove the aliases and then

```
ln -s /Users/jpermar/Developer/homebrew/bin/python3.9 /Users/jpermar/Developer/homebrew/bin/python
```

and then the command completes successfully:

`sam init --location https://github.com/aws-samples/cookiecutter-aws-sam-python`

```
You've downloaded /Users/jpermar/.cookiecutters/cookiecutter-aws-sam-python before. Is it okay to delete and re-download it? [yes]: 
project_name [Name of the project]: testing
include_safe_deployment [n]: 
 [SUCCESS]: Project initialized successfully! You can now jump to testing folder
 [INFO]: testing/README.md contains instructions on how to proceed.
```

I guess the simplest feature requests could be user experience improvements for your users:

1. This current method of running python is brittle. Adding additional python install/location detection options to the SAM scripts/hooks that are running would be helpful.
2. Any output helpful to humans about what's going on would also be helpful.

A big thank you to all for working with me to resolve this bug!

**Comment by justinpermar** [comment]
> I am not really expert on this but reading from the SO questions/answers, `/usr/bin/env` should look for `PATH` for the executable, which is there for your case but somehow `env` can't resolve it. You may search for what `pipenv` does to your session or environment and start from there (since it resolves your problem)?

pipenv modifies the PATH. Therefore SAM CLI is able to find `python` on the PATH.

**Comment by mndeveci** [comment]
I am glad that you find a resolution for your problem!

> 1. This current method of running python, from my perspective, is brittle. Adding fallback python install/location detection options to the SAM scripts/hooks that are running would be helpful. The obvious simple workaround is to look for python3 on the path, or even other specific versions python3.9 etc.
> 2. Any improved output helpful to humans about what's going on would also be helpful.

For your suggestions above, unfortunately this is very generic from our perspective. SAM CLI does execute cookiecutter commands to generate the given template. And since this template was not maintained by us, we can't assume or catch any errors and provide better messaging. For another template, an after hook might try to execute some other command (let's say `javac` for instance) which might not be on the `PATH` of the user, that will fail for some other customer.

I've created an issue on the other repository where they can provide more details about the required setup before initializing the template. https://github.com/aws-samples/cookiecutter-aws-sam-python/issues/45

**Comment by heitorlessa** [comment]
Powertools Python team chiming in - thanks @mndeveci for notifying us.

@justinpermar I'm so sorry to hear you had this bumpy road to start with that template -- we'll revamp that entirely after hearing this painful experience.

For now, if you're using the latest SAM CLI, we now have a built-in hello world Powertools template as part of the "sam init" command.

sam init --app-template hello-world-powertools-python --name sam-app --package-type Zip --runtime python3.9 --no-tracing

This should do it.

For that other template, we'll rewrite it to remove that hook to prevent issues like this (first I heard), and take the opportunity to add some production quality opinionated tools to fast track development.

Again, sorry to hear this. That's now the experience we want customers using Powertools to have at all.

We'll revert and do a much improved template on top.

Thanks

**Comment by heitorlessa** [comment]
Powertools docs being updated as we speak to use this newer SAM CLI built-in template. I'm sending a fix to the old template to use `python3`, then I'll reconvene with other maintainers on Friday to discuss prioritizing a newer template with 2023 opinions baked in.

<img width="1825" alt="image" src="https://user-images.githubusercontent.com/3340292/234700288-685f0c78-7057-4a63-a32a-36ceab960fd5.png">

**Comment by heitorlessa** [comment]
All done from our side (Powertools) - thank you SAM CLI team for helping Justin troubleshoot his python setup, and thank you Justin for your perseverance on this. 

- [x] [Older template fix](https://github.com/aws-samples/cookiecutter-aws-sam-python/commit/7a8e97e1bcb4c74c1f609ecef27f7a9495705907) to use `#!/usr/bin/env python3` instead of `#!/usr/bin/env python`
- [x] [Powertools documentation update to refer all examples to use the newer SAM CLI template](https://github.com/awslabs/aws-lambda-powertools-python/commit/f3ae0b6398d8f4a06b9bcc039ba3ea522fb215dc)
- [x] [Rebuild latest Powertools documentation with this hotfix](https://github.com/awslabs/aws-lambda-powertools-python/actions/runs/4813395596) to prevent anyone else not seeing this until our next release next week
  - [x] [Tutorial section](https://awslabs.github.io/aws-lambda-powertools-python/2.14.1/tutorial/)
  - [x] [Homepage Quick Getting Started section](https://awslabs.github.io/aws-lambda-powertools-python/2.14.1/#quick-getting-started)

**Comment by mndeveci** [comment]
Thanks for your quick help @heitorlessa !

And thanks for bringing this issue to us @justinpermar , I will be resolving this issue since we already find a workaround and resolved the problem at https://github.com/aws-samples/cookiecutter-aws-sam-python/ side.

Please let us know if you have further questions.

**Comment by justinpermar** [comment]
> Powertools Python team chiming in - thanks @mndeveci for notifying us.
> 
> @justinpermar I'm so sorry to hear you had this bumpy road to start with that template -- we'll revamp that entirely after hearing this painful experience.
> 
> For now, if you're using the latest SAM CLI, we now have a built-in hello world Powertools template as part of the "sam init" command.
> 
> sam init --app-template hello-world-powertools-python --name sam-app --package-type Zip --runtime python3.9 --no-tracing
> 
> This should do it.
> 
> For that other template, we'll rewrite it to remove that hook to prevent issues like this (first I heard), and take the opportunity to add some production quality opinionated tools to fast track development.
> 
> Again, sorry to hear this. That's not the experience we want customers using Powertools to have at all.
> 
> We'll revert and do a much improved template on top.
> 
> Thanks

In fact I used that template this morning to generate my template power tools app. Fantastic work thank you.
