### ISSUE TITLE
Does DynamoDB in SAM LOCAL support Streams events from DDB?

### ISSUE THREAD

**Issue by AkshatNGupta** [aws/aws-sam-cli#5058]
I have started running SAM application locally, but when i trigger an API call, it writes to the table, but the linked streams call does not happen, Does anyone know how to resolve/ fix it?

**Comment by lucashuy** [comment]
Thanks for opening this issue, can you provide more details about your project (reproducible template/code, steps)? SAM CLI's local capabilities is scoped to Lambda functions and API Gateway behaviour with Lambda function integrations.

**Comment by lucashuy** [comment]
Hi, thanks for opening this feature request. At the moment, `sam local` only supports Lambda Functions and API Gateway resources.

To test event passing locally, the `sam local generate-event dynamodb update` can generate an update event you can pass into `sam local invoke <function> -e <event file>`.

`sam sync` can also be used to test this functionality in the cloud.

Please open other issues if there are any other problems or requests you'd like to make.
