### ISSUE TITLE
Bug: sam local invoke - Docker - Have you got it installed and running

### ISSUE THREAD

**Issue by mattiamatrix** [aws/aws-sam-cli#5059]
### Description:

I have seen similar issues around but I am not sure this is exactly the same. When I try to `local invoke` a Lambda defined in my cdk project I get the error `Error: Running AWS SAM projects Locally requires Docker. Have you got it installed and running?`. But Docker is clearly running in the background.

I read something about `DOCKER_HOST` but if I touch the `cdk build` breaks instead 

![image](https://user-images.githubusercontent.com/5013654/233678023-9279021a-8687-4ff3-93ee-10cc0b75a39e.png)

`sam --version`: SAM CLI, version 1.81.0
`docker --version`: Docker version 20.10.24, build 297e128

### Steps to reproduce:

`sam local invoke -t`

### Observed result:

Error

### Expected result:

No error

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOs 13.3.1 (22E261)
2. `sam --version`: SAM CLI, version 1.81.0
3. AWS region: n/a

```
{
  "version": "1.81.0",
  "system": {
    "python": "3.8.16",
    "os": "macOS-13.3.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "2.74.0 (build 70e2a33)",
    "terraform": "Not available"
  }
}```

`Add --debug flag to command you are running`

**Comment by lucashuy** [comment]
Hi, thanks for opening this issue! It looks like the Docker context might be using a different context than what SAM CLI expects (from your screenshot, where `Context: desktop-linux`).

Following https://github.com/aws/aws-sam-cli/issues/4329#issuecomment-1289588827, does this work around work for you?

**Comment by mattiamatrix** [comment]
My understanding is updating `DOCKER_HOST` might affect other applications.

`sudo ln -sf "$HOME/.docker/run/docker.sock" /var/run/docker.sock` suggested [here](https://github.com/aws/aws-sam-cli/issues/4329#issuecomment-1513679805) looks a workaround

**Comment by lucashuy** [comment]
Setting the `DOCKER_HOST` environment variable right before the command (`DOCKER_HOST=<...> sam local invoke ...`) should only set it for that particular command run. Symlinking the Docker socket in the home directory to the default Docker one should work, however this seems to be more of a global approach since this persists and will affect things other than SAM CLI.

**Comment by mildaniel** [comment]
Seems like discussions on this issue have stalled so I will close this out now. Should anything else arise or you have anymore questions, please don't hesitate to open up a new issue.
