### ISSUE TITLE
Bug: Lambda functions containers initialization failed because of 404 Client Error

### ISSUE THREAD

**Issue by justinpermar** [aws/aws-sam-cli#5071]
### Description:
I cannot start the lambda locally using SAM. The lambda is from the power tools tutorial created using the "hello-world" app-template. Note that I am using podman locally with `alias docker=podman` in my shell config.

### Steps to reproduce:

1. Install Podman Desktop
    1. Do not install using brew. Instead use the .dmg file.
    2. https://podman-desktop.io/docs/Installation/macos-install
    3. Note: install the engine from within the Desktop app (don't install separately using brew)
2. Initialize Podman Desktop
    1. https://podman-desktop.io/docs/getting-started/getting-started
            1. Note: if initialization from the GUI takes forever, instead use podman CLI
    2. start up podman
```
podman machine init
podman machine start
```
3. Add docker alias to podman
    1. Edit your ~/.zshrc to alias docker: https://podman-desktop.io/docs/getting-started/getting-started
4. Follow the tutorial… https://awslabs.github.io/aws-lambda-powertools-python/2.14.1/tutorial/#getting-started
5. `sam init --runtime python3.9 --dependency-manager pip --app-template hello-world --name powertools-quickstart`
6. `cd powertools-quickstart`
7. `sam build`
8. `sam --debug local start-api`

### Observed result:
`sam --debug local start-api`
```
2023-04-25 09:37:56,813 | Return available internal hook packages
2023-04-25 09:37:56,814 | Return available internal hook packages
Initializing the lambda functions containers.
Lambda functions containers initialization failed because of 404 Client Error: Not Found ("b'Not Found'")
Error: Lambda functions containers initialization failed
```

### Expected result:
No error

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
`sam --info`
```
{
  "version": "1.81.0",
  "system": {
    "python": "3.8.13",
    "os": "macOS-13.2.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "4.4.4",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}
```

1. OS:
Ventura 13.2.1

2. `sam --version`:
```
SAM CLI, version 1.81.0
```
4. AWS region:
us-east-1 (AWS CLI not configured)

**Comment by jfuss** [comment]
I think this is the same as https://github.com/aws/aws-sam-cli/issues/5019.

It comes from podman not supporting the distribution api. There is a PR open for handling the response failure in a way to make this work. 

Do note: We can only support docker api compliant solutions, which podman is not fully (or at least what we use). So there may be more of these cases, as you go deeper into podman.

Closing as a duplicate.
