### ISSUE TITLE
Bug: List of actions in authorizer response results in error

### ISSUE THREAD

**Issue by rhynix** [aws/aws-sam-cli#5083]
### Description:
When the authorizer returns a list of actions in a statement, internal validation fails. This results in a `AuthorizerUnauthorizedRequest` error. This issue is very similar to https://github.com/aws/aws-sam-cli/issues/5072.

### Steps to reproduce:

1. Set up a local authorizer lambda.
2. Make it respond with the following:

   ```json
   {
     "principalId": "user",
     "policyDocument": {
       "Version": "2012-10-17",
       "Statement": [
         {
           "Action": ["execute-api:Invoke"],
           "Effect": "Allow",
           "Resource": ["..."]
         }
       ]
     },
     "context": {}
   }
   ```
3. Call a route that uses the authorizer.

### Observed result:
Exception `AuthorizerUnauthorizedRequest` is raised.

### Expected result:
The authorization succeeds and the endpoint for the route is called.

### Additional environment details

```json
{
  "version": "1.81.0",
  "system": {
    "python": "3.8.16",
    "os": "Linux-6.1.21_1-aarch64-with-glibc2.34"
  },
  "additional_dependencies": {
    "docker_engine": "23.0.2",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}
```

### Research

The following two places were found where changes should be made for this to work:

* https://github.com/aws/aws-sam-cli/blob/0d699164d5d5aa02b44e5c7f429e8cce023f8c8c/samcli/local/apigw/authorizers/lambda_authorizer.py#L521
  
  Allow list of strings in addition to strings.
* https://github.com/aws/aws-sam-cli/blob/0d699164d5d5aa02b44e5c7f429e8cce023f8c8c/samcli/local/apigw/authorizers/lambda_authorizer.py#L377

  Check if the action does not contain the `_IAM_INVOKE_ACTION` if it is a list, in addition to checking if it does not equal the `_IAM_INVOKE_ACTION` if it is a string.

If I find some time, I will consider creating a pull request for these changes.

**Comment by sriram-mv** [comment]
Willing to take a PR! thanks for raising this!

**Comment by rhynix** [comment]
The updated unit test is failing due to a deprecation warning from Werkzeug. It looks like it only happens when Werkzeug happens to resolve to version >=2.3.0. I believe there are three options we have here:

1. Pin Werkzeug to <2.3.0. It is now a transitive dependency which is not pinned.
2. Update Flask to >=2.2.4. This removes the use of the deprecated function.
3. Ignore the deprecation warning in `pytest.ini`.

My preference would go to option 1. Am I missing any options? Are there any things I should take into consideration here?
