### ISSUE TITLE
Bug: sam deploy - UnicodeDecodeError

### ISSUE THREAD

**Issue by apipinic** [aws/aws-sam-cli#5087]
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by sriram-mv** [comment]
Hey @apipinic , please re-open this issue with more information such as requested above, along with the stack trace and it will be easier to debug this issue. I'm going to close this current one.
