### ISSUE TITLE
Bug: Method ARN sent to local authorizer and used for checking against authorized resource inconsistent with API Gateway

### ISSUE THREAD

**Issue by rhynix** [aws/aws-sam-cli#5104]
### Description:

When using a local authorizer, there are two issues with the method ARN used:

* The `methodArn` in the request to the authorizer lambda contains the Flask endpoint instead of the actual path of the request.
* The resources returned by the authorizer are compared to an ARN containing the same Flask endpoint instead of the actual path of the request.

This only leads to issues when the endpoint is parameterized.

### Steps to reproduce:

1. Use the code from this gist: [AWS SAM local method ARN inconsistency](https://gist.github.com/rhynix/27d6d1c163b9ae80f3ca315dfb513604)
2. Start the local API Gateway with `sam local start-api`
3. Fire the following requests:
   1. ```sh
      curl http://localhost:3000/projects/1 --header "Authorization: Bearer token"
      ```
   2. ```sh
      curl http://localhost:3000/projects/4 --header "Authorization: Bearer token"
      ```

### Observed result:

1. The responses to these two requests are respectively:
   1. ```json
      {"message":"User is not authorized to access this resource"}
      ```
   2. ```json
      {"message":"User is not authorized to access this resource"}
      ```
2. These requests lead to the following logs for the authorizer:
   1. ```methodArn: arn:aws:execute-api:us-east-1:123456789012:1234567890/dev/GET/projects/<id>```
   2. ```methodArn: arn:aws:execute-api:us-east-1:123456789012:1234567890/dev/GET/projects/<id>```

### Expected result:

This is the behavior when this template is deployed to AWS using `sam deploy`.

1. The responses to these two requests are respectively:
   1. ```json
      {"message":"ok"}
      ```
   2. ```json
      {"message":"User is not authorized to access this resource"}
      ```
2. These requests lead to the following logs for the authorizer:
   1. ```methodArn: arn:aws:execute-api:us-east-1:123456789012:1234567890/dev/GET/projects/1```
   2. ```methodArn: arn:aws:execute-api:us-east-1:123456789012:1234567890/dev/GET/projects/4```

### Additional environment details

```
{
  "version": "1.81.0",
  "system": {
    "python": "3.8.16",
    "os": "Linux-6.1.21_1-aarch64-with-glibc2.34"
  },
  "additional_dependencies": {
    "docker_engine": "23.0.3",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}
```

**Comment by rhynix** [comment]
If the expected behavior is agreed upon, I will work on a pull request to fix this issue.

**Comment by hnnasit** [comment]
Thanks for flagging this issue @rhynix. I confirmed that this is a bug and `method_arn` does not reconstruct the entire endpoint. Currently `flask_request.endpoint` is used to get the endpoint ([code](https://github.com/aws/aws-sam-cli/blob/0d699164d5d5aa02b44e5c7f429e8cce023f8c8c/samcli/local/apigw/local_apigw_service.py#L803-L812)), but looks like this is not the complete URI as per the [docs](https://tedboy.github.io/flask/interface_api.incoming_request_data.html#flask.Request.endpoint). Feel free to raise a PR and contribute to fix this issue. Possible fix could be using `flask_request.view_args` or `flask_request.path`.
