### ISSUE TITLE
Bug: sam local start-api do not cache layers ~/.aws-sam/layers-pkg

### ISSUE THREAD

**Issue by PavelJacobo** [aws/aws-sam-cli#5187]
### Description:
As [Documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-layers.html) explains, When you invoke your function using one of the sam local commands, the layers package of your function is downloaded and cached on your local host.
on unix based system it should be ~/.aws-sam/layers-pkg
but It's not happening like this.

SAM CLI, version 1.84.0

### Steps to reproduce:

having this repository example: https://github.com/PavelJacobo/samcliIssue
I run the command sam local invoke:
the command execute properly, but not layer is created as Documentation says.

```
$ sam local invoke -e ./lambda/lambda_event.json LambdaDemoFunction --debug
Invoking lambda.lambdaHandler (nodejs18.x)                                                                                                                                                 
layerDatabaseConnectionNode is a local Layer in the template                                                                                                                               
Local image is up-to-date                                                                                                                                                                  
Building image....................
Using local image: samcli/lambda-nodejs:18-x86_64-b78302d3ab286b38c934964a0.                                                                                                               
...
{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module '/opt/nodejs/db'\nRequire stack:\n- /var/task/lambda.js\n- /var/runtime/index.mjs","trace":["Runtime.ImportModuleError: Error: Cannot find module '/opt/nodejs/db'","Require stack:","- /var/task/lambda.js","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:997:17)","    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1032:21)","    at async start (file:///var/runtime/index.mjs:1195:23)","    at async file:///var/runtime/index.mjs:1201:1"]}

```

### Observed result:
I can see the following output:

```
Invoking lambda.lambdaHandler (nodejs18.x)                                                                                                                                                 
layerDatabaseConnectionNode is a local Layer in the template
"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module '/opt/nodejs/db...
```

and when go to ~/.aws-sam/layer-pkg 
no cached layers in there

```
$ ls -tlr ~/.aws-sam/layers-pkg/
total 0
```

### Expected result:
I expect to cache layers after running sam local start-api.
I'm working with a apigateway with several lambdas, the behaviour is the same when I run sam local start-api. The command runs successfully but when I hit a lambda endpoint it fail because not layer was found.
Error: Cannot find module '/opt/nodejs/db'

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 22.04
2. `sam --version`: SAM CLI, version 1.84.0
3. AWS region: us-est-1

```
{
  "version": "1.84.0",
  "system": {
    "python": "3.11.3",
    "os": "Linux-5.19.0-41-generic-x86_64-with-glibc2.35"
  },
  "additional_dependencies": {
    "docker_engine": "23.0.6",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

`Add --debug flag to command you are running`

**Comment by hawflau** [comment]
Hi @PavelJacobo thanks for raising the issue, and thanks for providing the example. It helps me understand your issue more quickly.

I tried with your example and figured you might have missed running `sam build`. Running `sam build` will build the `layerDatabaseConnectionNode` Layer and cache it in the directory `.aws-sam/build/layerDatabaseConnectionNode` relative to your project root. And then running `sam local invoke -e ./lambda/lambda_event.json LambdaDemoFunction` will succeed.

The documentation "How layers are cached locally" describes the behavior for the case that a layer is remote. For example:
```
  LambdaDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: lambda.lambdaHandler
      Runtime: nodejs18.x
      Layers:
        - !Ref layerDatabaseConnectionNode
        - !Sub arn:aws:lambda:${AWS::Region}:094274105915:layer:AWSLambdaPowertoolsTypeScript:11
```

`layerDatabaseConnectionNode` is built when you run `sam build`, and is built in `.aws-sam/build/layerDatabaseConnectionNode`. The Lambda Powertools Layer won't be built when running `sam build`. Instead it is pulled and cached at `~/.aws-sam/layers-pkg`.

Closing as it doesn't seem like a bug. Feel free to reopen if my answer doesn't resolve your issue.
