### ISSUE TITLE
Bug: sam local start-api wrong layer path Nodejs

### ISSUE THREAD

**Issue by PavelJacobo** [aws/aws-sam-cli#5192]
### Description:
Hello
First said that I'm new to AWS and Cloudformation so sorry if I may miss something during  testing.

according to **Including library dependencies in a layer**, using Nodejs

As per [Documentation](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-path), For each [Lambda runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), the PATH variable includes specific folders in the **/opt.**

For nodejs the path would be as follow: /opt/nodejs/node18/node_modules:/opt/nodejs/node_modules:/var/runtime/node_modules:/var/runtime:/var/task
I understand that the layers I create would be mounted into some of those folders. /opt/nodejs/**

But when I run "sam local start-api" the layer content is directly mounted into **/opt** directory.
and **/opt/nodejs/*** directories do not exist.

if I want to require my layer from /opt/nodejs/mylayer, It will give me an error while trying to reach my lambda function.
{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module '/opt/nodejs/mylayer' ...}

what should I do if I want to require mylayer from "/opt/nodejs/mylayer"?

### Steps to reproduce:
I have create a test repository [here](https://github.com/PavelJacobo/samcliIssue)

1. Download [repository](https://github.com/PavelJacobo/samcliIssue)
2. Move to develop branch: `git checkout develop`
    a. You will see a /hello/hello.js lambda function code.
    b. in the line 1, you will see a `const db = require("/opt/nodejs/db");` This is the layer I want to import, but it's wrong path.
3. run `sam local start-api --debug`
4. from curl or postman call http://localhost:3000/hello: `curl http://localhost:3000/hello`
    a. You will receive an error `"Error: Cannot find module '/opt/nodejs/db'"`
5. change line 1 of /hello/hello.js lambda to `const db = require("/opt/db");` :
    a. now the request work properly because the layer is on **/opt/db**, but not on the directories the documentation says.
    b. Please check the output in the console about **NODE_PATH** and the **/opt** content
### Observed result:
In the hello lambda you can see logs about /opt directory content. **/opt/nodejs, /opt/nodejs/node_modules** directories do not exist and as I understand documentation, it should exists at least /opt/nodejs/, isn't it?

### Expected result:
I want to use **sam local start-api** and **not sam build** because I would like to hot-reloading code and fastly develop and not to sam build any time.

I expect to have my layer inside **/opt/nodejs/mylayer** so I can import it properly using `const db = require("/opt/nodejs/db");`
but layer path is /opt/mylayer.

as I said I'm new to sam cli and aws, please let me now if I miss something in the template.yaml 

Many many many thanks

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 22.04
3. `sam --version`: SAM CLI, version 1.84.0
4. AWS region: us-east-1

```
{
  "version": "1.84.0",
  "system": {
    "python": "3.11.3",
    "os": "Linux-5.19.0-42-generic-x86_64-with-glibc2.35"
  },
  "additional_dependencies": {
    "docker_engine": "23.0.6",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
Hello @PavelJacobo, 
Thanks for raising this issue.

SAM CLI puts the Layers in expected paths only if it got built by SAM CLI. So to fix this problem, you just need to run `sam build` before you run `sam local` commands.

If you do not want to use `sam build`, so you need to restructure your project to be as following:
```
.
├── apigateway
│   ├── apigateway.js
│   └── apigateway_event.json
├── databaseConnection
│   └── nodejs
│       ├── db.js
│       └── package.json
├── hello
│   └── hello.js
├── lambda
│   ├── lambda.js
│   └── lambda_event.json
├── package.json
├── samconfig.toml
├── spec.yaml
└── template.yaml
```
Move the layer content to be in nodejs directory inside the layer directory, and keep your template referring to the layer root.

**Comment by PavelJacobo** [comment]
Hello @moelasmar thanks so much for response.

I've restructured directory tree as you suggested. It works ok while developing with "sam local start-api", but **once we are done** with development we need to **build and deploy** to aws.

with this workarround sam build is now broken, and We need to restructure again directory tree. For this simple example is not a big issue, but for large applications with several layers it could be difficult to change directory structure back and forward anytime we want to develop and deploy.

I applied sam build after directory restructuration and this is the layer path when we run sam build and call the hello lambda:

```
2023-05-24T08:29:15.349Z        ec8a391c-d815-4479-a57c-a710044ce4ba    INFO    Directory: /opt/nodejs
2023-05-24T08:29:15.350Z        ec8a391c-d815-4479-a57c-a710044ce4ba    INFO    Directory: /opt/nodejs/nodejs
2023-05-24T08:29:15.350Z        ec8a391c-d815-4479-a57c-a710044ce4ba    INFO    File: /opt/nodejs/nodejs/db.js
2023-05-24T08:29:15.350Z        ec8a391c-d815-4479-a57c-a710044ce4ba    INFO    File: /opt/nodejs/nodejs/package.json
```
it means `const db = require("/opt/nodejs/db"); `is not accesible anymore. 

Thanks so much for support
regards

**Comment by moelasmar** [comment]
sorry if my reply was not complete, to use `sam build`, and this is the recommended approach, you can do the following changes:
 - keep your project structure as it was originally:
 ```
.
├── apigateway
│   ├── apigateway.js
│   └── apigateway_event.json
├── databaseConnection
│   ├── db.js
│   └── package.json
├── hello
│   └── hello.js
├── lambda
│   ├── lambda.js
│   └── lambda_event.json
├── package.json
├── samconfig.toml
├── spec.yaml
└── template.yaml
```
 - run `sam build` to build your lambda functions, and layers.
 - now you can run `sam local` commands to test your lambda functions and Api gateways.
 - Also you can run `sam deploy` to deploy your application to AWS.

I verified both local and deploy commands and verified that both works fine, I just had to do small changes in your template to be able to deploy it.

**Comment by PavelJacobo** [comment]
Hello, thanks so much for response. 

I agree with You. I understand **with "sam build" layers are placed in the correct place** and we can then run "sam local start-api" that will take build from .aws-sam and then we can deploy to AWS without issue., but if we use sam build, we do not have hot-realod as we have with sam local start-api when there is no previous build.

You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. **If you used sam build before running local commands, you will need to re-run sam build for the changes to be picked up.** You only need to restart SAM CLI if you update your AWS SAM template 

The questions are. **Why "sam local start-api" places the layer in a different path? is this not a bug? shouldn't "sam local start-api" place the layers in the same path "sam build" does?**

if we want to use hot-reloading functionality, are we forced to change the directory structure?

In my opinion it's a bug that does not allow us to proper develop with "sam local start-api" when layers exist and of course there is no previous build. with this layer path issue we cannot use **hot-reloading functionality** and we are force to run first "sam build" to develop.


Thanks  so much
regards

**Comment by cg1101** [comment]
I agree with @PavelJacobo . If `sam build` can work out the directory structure correctly, so should `sam local start-api`. It is confusing that two have different behavior. I found the same problem with python. 

I guess `sam build` doesn't require the `python` or `nodejs` folder if the layer's build method is explicitly set to python or nodejs. I hope `sam local start-api` can do that too.

I guess the extra layer of `python`, `nodejs` or even `bin` is needed if we are building a generic layer, i.e. a layer can be shared by functions of different runtimes.

**Comment by moelasmar** [comment]
@cg1101, @PavelJacobo are you are asking that `sam local` commands to structure the layers code in the expected structure, so customers can execute them without running `sam build` command.

If yes, so we could not do this or at least to make it the default behaviour of `sam local` commands (and I think it should be also extended to other commands, like `sam deploy` or `sam package`). The reason is the current SAM CLI behaviour is to assume that the customer will package the layers in the expected structure if they will not use `sam build` functionality, and they will build it in their own way. If we changed this behaviour, we are going to break existing customers.

**Comment by moelasmar** [comment]
@PavelJacobo .. I want to understand more about your concern, is your concern that you do not want to run `sam build` after doing changes in the layers or lambda functions when you use `sam local` command with `--warm-containers` feature.  

If yes, could you please explain the steps you are doing right now (or you want to do). How you build your lambda functions, and layers, and how you run `sam local`, and how do you update your code and if you need to rebuild it after you updated or not.

**Comment by cg1101** [comment]
Thanks for the reply @moelasmar. I am asking for a behavior change for `sam local`. The current behavior is not compatible with `sam build`.  `sam local` expects an extra level under the layer folder but `sam build` doesn't. 

- If my python packages are under layer folder directly, then deployed lambda works, but local test with `sam local start-api` won't work, with or without running `sam build` first.
- if my python packages are put inside `python` under layer folder, (1 level deeper), then `sam local start-api` works, libraries can be found, but lambda functions deployed after running `sam build`/`sam deploy` won't work, libraries can't be found because there will be two levels of `python` in the bundle.

Right now I can test my functions without running `sam build` first. It works as long as there is an extra level of `python` or `nodejs`, etc. However, this directory structure makes deployed functions fail.

**Comment by PavelJacobo** [comment]
Hello @moelasmar 

Well the steps I wanted to reproduce was as follow:

  1º. I would like to develop without the need of rebuilding for any change I do at code level, so I run "sam local start-api --debug". This allows me to check code changes on the fly without the need of run "sam build" anytime I do code changes.
  
  2º. Once I finish developing I would like to build and deploy. So it means to run "sam build" and "sam deploy"
  
  but since "sam local start-api" is not compatible with "sam build", because the layer path is different when we run one or another, if i start developing by running "sam local start-api" then I cannot run "sam build" and "sam deploy" because the layer path will be different and deployment will fail.
  
  basically starting with not any **.aws-sam** directory, in the following scenario:
```
.
├── apigateway
│   ├── apigateway.js
│   └── apigateway_event.json
├── databaseConnection
│   └── nodejs
│       ├── db.js
│       └── package.json
├── hello
│   └── hello.js
├── lambda
│   ├── lambda.js
│   └── lambda_event.json
├── package.json
├── samconfig.toml
├── spec.yaml
└── template.yaml
```
  1.  `  $ sam local start-api --debug`

  2. then I test it and It's ok, because /opt/nodejs/db is properly pathed.
`curl http://localhost:3000/hello
{'message': 'I Send You Hello World from Layer'}`
 
 3. I finish developing and I prepare to build it before deploy to aws, so I run sam build
 `$ sam build`
once I run "sam build" the directory **.aws-sam** is created.
  
  4. I want to test again before deploy resources to aws. so I run
  `  $ sam local start-api --debug`
  and then test the endpoint
  `curl http://localhost:3000/hello
  "Error: Cannot  find module '/opt/nodejs/db' `
  
  As I explain I'm quite new to aws so maybe the methodology is not the proper one. :) 
  
  What or how would you do if You want to use "sam local start-api" hot-reloading feature for developing porpose and then, once finished developing, build and deploy it to aws? which ones should be the steps?
  

  Thanks so much for following and for explanation.
  
  regards

**Comment by hawflau** [comment]
Just looked into this issue and probably missed a lot of context. "First run `sam build`, then run `sam local *`/`sam deploy`" was the design choice we made since the beginning. `sam build`'s purpose is to create a package that can be zipped and uploaded to S3 for a Lambda Function. With these premises, it's natural for `sam local *` to just mount the layer with the given file structure like that in `.aws-sam/build`, and do not do anything extra. Perhaps we can do something smart in `sam local *` to check and mount a layer's source code to the correct path as it should be in a Lambda Function. We will need to consider this deeper and understand if this will break any existing behavior.

Meanwhile, as a workaround, is it possible do kind of dynamic import? For example,
```javascript
if (process.env.LOCAL_TEST === "1") {
  const db = require("/opt/db");
} else {
  const db = require("/opt/nodejs/db");
}

```

**Comment by mildaniel** [comment]
Issue is inactive, closing.

**Comment by nikhilrizal** [comment]
is this resolved ?
i have same issues
