### ISSUE TITLE
SAM Deploy not sure if I am doing something wrong or if SAM works that way

### ISSUE THREAD

**Issue by estebance** [aws/aws-sam-cli#5198]
Hi, 
I've been testing SAM for some time and I have some concerns about the right way to deploy an application with a couple of microservices. 

This is an example of my project structure 
> project_name
template.yml
src/functions/function_a/app.js
src/functions/function_b/app.js
src/package.json 

My SAM template follows this structure 

  > functionA:
     Type: AWS::Serverless::Function 
     Properties:
     CodeUri: src/
     Handler: functions/function_a/app.handler
     Runtime: nodejs16.x

  > functionB:
     Type: AWS::Serverless::Function 
     Properties:
     CodeUri: src/
     Handler: functions/function_b/app.handler
     Runtime: nodejs16.x

Then I just run the command to build my application with docker

` sam build --use-container`

To deploy for the first time 

` sam deploy --guided`

So, the samconfig.toml is created  in the root folder of my project 

Everything at this point is ok. But after some time I've realized that the code packaged for each lambda function includes the entire project code and dependencies, even the code from other lambda functions. The result is an error related to the size of the package I want to deploy. 

When I export the code from lambda for the functionA I can see this structure 

 > functionA
  src/functions/*
  src/node_modules/
  .aws-sam/* <includes the code packaged too>

To avoid this issue I have to do this every time I want to deploy my application 

` cd .aws-sam/build/`

Because a template.yaml is generated there and If you take a look to it, the code for each lambda function is referenced correctly I have to execute: 

`  sam deploy --config-file ../../samconfig.toml`

I think I could be doing something wrong to deploy or configure the project structure and I'd really appreciate your help.

It doesn't feel right to move between directories to build and deploy an application after you have been working with serverless framework for example.  

This is a link to a project I am working and it represents the scenario in detail [any-doc-classifier-aws](https://github.com/TBBC-AI/doc-classifier-aws)
 
Cheers,

**Comment by moelasmar** [comment]
Thanks @estebance for raising this issue. The problem is related to how you define the source code of your lambda functions.
Your template look like the following:
```
functionA:
	Type: AWS::Serverless::Function
	Properties:
		CodeUri: src/
		Handler: functions/function_a/app.handler
		Runtime: nodejs16.x

functionB:
	Type: AWS::Serverless::Function
	Properties:
		CodeUri: src/
		Handler: functions/function_b/app.handler
		Runtime: nodejs16.x
```

and this informs SAM CLI that the root directory of each lambda function is in `src` directory, and when you run `sam build` SAM CLI will consider everything in `src` directory is related to the Lambda function code. 
To avoid this problem you need to update your template to be as following:

```
functionA:
	Type: AWS::Serverless::Function
	Properties:
		CodeUri: src/functions/function_a/
		Handler: app.handler
		Runtime: nodejs16.x

functionB:
	Type: AWS::Serverless::Function
	Properties:
		CodeUri: src/functions/function_b/
		Handler: app.handler
		Runtime: nodejs16.x
```
Now SAM CLI will package only the code, and dependencies related to each lambda function, and you can run both `sam build` and `sam deploy` commands from the root directory of your project that contains your template file.

I hope that my answer is clear and helps you to resolve your problem.

**Comment by estebance** [comment]
Thanks for your reply  @moelasmar. 
Related to the dependencies  if  I want to have a common package.json,  how can I do it ? 
or is required to define them in the following order ? 
 
```
src/functions/function_a/package.json
src/functions/function_b/package.json

```

**Comment by moelasmar** [comment]
if you want to make it common, you can have it in a separate location, but when you run `sam build` add the parameter `--manifest` and pass the location of the `package.json` file.

**Comment by estebance** [comment]
Ohh I see,  Thanks  for helping me
