### ISSUE TITLE
Support Static Websites + Serverless Backend Scenario

### ISSUE THREAD

**Issue by sanathkr** [aws/aws-sam-cli#523]
This is a feature request to better support local testing of static websites that are backed by Serverless Backends (API+Lambda). Customers would like to use SAM CLI to serve their static website locally, so they can run and test it on a Web Browser. During the process, they want SAM CLI to also start a serverless backend locally (using `sam local start-api`). Their local website will connect to the local backend so they can have a fully integrated development solution. 

Currently, SAM CLI has a `--static-dir` property that kind of supports this scenario. But this is not sufficient as discussed in #512, #200 etc.

**Comment by terrywarwar** [comment]
@sanathkr When I start sam using `sam local start-api --static-dir public`  and browse to `http://localhost:3000/` I get `{"message":"Missing Authentication Token"}`.  When I browse to `http://localhost:3000/index.html` it works as expected.  Is there anyway to make the default `index.html`?

**Comment by studds** [comment]
FWIW, I've had success doing this the other way around: having a frontend server which proxies the local APIG. I'm using angular cli, which has [support for this built in](https://github.com/angular/angular-cli/wiki/stories-proxy).
