### ISSUE TITLE
Feature request: sync --watch output should include timestamp

### ISSUE THREAD

**Issue by gormatoobay** [aws/aws-sam-cli#5267]
Given sam sync --watch can be running for DAYS, the output line beginning with "Finished syncing..." should be preceded with a timestamp, so we know the last time it was run.

**Comment by mildaniel** [comment]
Thanks for the suggestion! We welcome contributions if you'd like to work on this, but I'll bring it to the team for prioritization.

**Comment by hnnasit** [comment]
Closing as the PR has been merged and released.
