### ISSUE TITLE
Feature request: Optional flag to disable authorizer for "sam local start-api"

### ISSUE THREAD

**Issue by mikepianka** [aws/aws-sam-cli#5285]
### Describe your idea/feature/enhancement

Being able to test API Gateway authorizers locally when running `sam local start-api` is a great new feature. However, I think it would be helpful to be able to pass an optional flag at the command line to disable the authorizer for local testing.

### Proposal

Add an optional flag to disable API Gateway authorizers like `sam local start-api --disable-authorizer`

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

**Comment by mildaniel** [comment]
Thanks for the suggestion @mikepianka, I like the idea! We welcome contributions if you'd like tackle this yourself, if not, I'll take it back to the team for prioritization.

**Comment by hnnasit** [comment]
Closing as the PR has been merged and released.
