### ISSUE TITLE
Bug: sam local invoke - TypeError

### ISSUE THREAD

**Issue by AkhilAnand5** [aws/aws-sam-cli#5292]
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by mildaniel** [comment]
Hi @AkhilAnand5, are you able to provide some more details that will help us reproduce the issue? Please follow the bug template format and fill in the provided fields.

**Comment by nanicpc** [comment]
Hi I'm having the same issue.

Steps to reproduce: 
create a c9 environment and then create a LambdaSAMApp "Hello world"
Observed result:
Error
![image](https://github.com/aws/aws-sam-cli/assets/15998450/4d9e8667-ea51-47c1-aa94-cc1cde31f859)


Expected result:
no error

Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
OS: Amazon Linux2
sam --version: 1.72.0
AWS region: Ireland

I've followed the "Using AWS SAM and AWS Cloud9 to Create, Edit, and Deploy a Lambda Function demonstration"

ps: I've managed to make the local invoke work by using the terminal and doing
```
sam init
cd sam-app
sam build
sam local invoke
```
but I don't really understand why

**Comment by mildaniel** [comment]
Thanks @nanicpc for providing supplemental info, however your particular issue seems different from the commenter's. It seems like the issue you are having is with running the two debugging instances and attempting to use the same port which is already in use. We certainly shouldn't crash there though, so I will create a new issue for that.

As for the initial issue, there is not enough information for us to follow up so I will go ahead and resolve this.
