### ISSUE TITLE
Bug: can not create project

### ISSUE THREAD

**Issue by jason-desygner** [aws/aws-sam-cli#5319]
☁  test  sam init

You can preselect a particular runtime or package type when using the `sam init` experience.
Call `sam init --help` to learn more.

Which template source would you like to use?
	1 - AWS Quick Start Templates
	2 - Custom Template Location
Choice: 1

Choose an AWS Quick Start application template
	1 - Hello World Example
	2 - Data processing
	3 - Hello World Example with Powertools for AWS Lambda
	4 - Multi-step workflow
	5 - Scheduled task
	6 - Standalone function
	7 - Serverless API
	8 - Infrastructure event management
	9 - Lambda Response Streaming
	10 - Serverless Connector Hello World Example
	11 - Multi-step workflow with Connectors
	12 - Lambda EFS example
	13 - DynamoDB Example
	14 - Machine Learning
Template: 3

Which runtime would you like to use?
	1 - dotnet6
	2 - java17
	3 - java11
	4 - java8.al2
	5 - java8
	6 - nodejs18.x
	7 - nodejs16.x
	8 - nodejs14.x
	9 - python3.9
	10 - python3.8
	11 - python3.7
	12 - python3.10
Runtime: 6

Based on your selections, the only Package type available is Zip.
We will proceed to selecting the Package type as Zip.

Based on your selections, the only dependency manager available is npm.
We will proceed copying the template using npm.

Would you like to enable X-Ray tracing on the function(s) in your application?  [y/N]: y
X-Ray will incur an additional cost. View https://aws.amazon.com/xray/pricing/ for more details

Would you like to enable monitoring using CloudWatch Application Insights?
For more info, please view https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-application-insights.html [y/N]: y
AppInsights monitoring may incur additional cost. View https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/appinsights-what-is.html#appinsights-pricing for more details

Project name [sam-app]: app

    -----------------------
    Generating application:
    -----------------------
    Name: app
    Runtime: nodejs18.x
    Architectures: x86_64
    Dependency Manager: npm
    Application Template: hello-world-powertools-typescript
    Output Directory: .
    Configuration file: app/samconfig.toml

    Next steps can be found in the README file at app/README.md

Commands you can use next
=========================
[*] Create pipeline: cd app && sam pipeline init --bootstrap
[*] Validate SAM template: cd app && sam validate
[*] Test Function in the Cloud: cd app && sam sync --stack-name {stack-name} --watch

Error: An error occurred while generating this project app: Unable to create file 'template.yaml'. Error message: 'collections.OrderedDict object' has no attribute 'Powertools for AWS Lambda (TypeScript) for AWS Lambda (TypeScript) Tracing'. Context: OrderedDict([('cookiecutter', OrderedDict([('project_name', 'app'), ('runtime', 'nodejs18.x'), ('Powertools for AWS Lambda (TypeScript) Tracing', 'enabled'), ('Powertools for AWS Lambda (TypeScript) Metrics', 'enabled'), ('Powertools for AWS Lambda (TypeScript) Logging', 'enabled'), ('_copy_without_render', ['.gitignore']), ('architectures', {'value': ['x86_64']}), ('_template', '/Users/jasonkristian/.aws-sam/aws-sam-cli-app-templates/nodejs18.x/hello-ts-pt'), ('_output_dir', '/Users/jasonkristian/test')]))])
☁  test

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: mac os x 13.4
2.SAM CLI, version 1.85.0
3. AWS region: us-east-1

**Comment by mildaniel** [comment]
Moved the issue to AWS SAM CLI since it likely related more closely to that.

**Comment by mildaniel** [comment]
I was able to replicate this issue and confirmed that this is a bug.
