### ISSUE TITLE
Please upgrade cfn-lint to 0.77.8

### ISSUE THREAD

**Issue by amancevice** [aws/aws-sam-cli#5365]
### Description:
The `cfn-lint` package needs to be bumped to `v0.77.8` in order to support the new `ruby3.2` Lambda runtime

### Steps to reproduce:
- Create a template with an `AWS::Serverless::Function` resource and set `Runtime: ruby3.2`
- Run `sam validate --lint`
- See error

### Observed result:
```plaintext
E3030 You must specify a valid value for Runtime (ruby3.2). Valid values are ["dotnet6", "dotnetcore1.0", "dotnetcore2.0", "dotnetcore2.1", "dotnetcore3.1", "go1.x", "java11", "java17", "java8", "java8.al2", "nodejs", "nodejs10.x", "nodejs12.x", "nodejs14.x", "nodejs16.x", "nodejs18.x", "nodejs4.3", "nodejs4.3-edge", "nodejs6.10", "nodejs8.10", "provided", "provided.al2", "python2.7", "python3.10", "python3.6", "python3.7", "python3.8", "python3.9", "ruby2.5", "ruby2.7"]
```

### Expected result:
template should pass linting

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 13.4
2. `sam --version`: 1.86.1
3. AWS region: us-east-1

```
{
  "version": "1.86.1",
  "system": {
    "python": "3.8.17",
    "os": "macOS-13.4-x86_64-i386-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "1.5.0"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by lucashuy** [comment]
Thanks for letting us know that cfn-lint needs a bump! We'll look to updating this for a future release.
