### ISSUE TITLE
Question: Control dependencies installed using sam build

### ISSUE THREAD

**Issue by alex5207** [aws/aws-sam-cli#5367]
I have recently run into issues regarding the size of my lambda deployment package. I have a usual `requirements.txt` file. Investigating the packages I found that one of my dependencies listed in `requirements.txt`; `aws-xray-sdk` causes `botocore` to be installed. The `botocore` package is already included in the Python lambda runtime and is like ~80mb so avoiding reduces the size significantly.

**My current solution:** In my `buildspec` file I run a step after running `sam build` to remove the package 
`...`
`- sam build -t tenant template`
`rm -rf .aws-sam/build/LayerThatContainsThePackage/botocore`
`sam package --s3-bucket MyBucket`

This works but feels a bit clumsy. Is there any better way to avoid certain dependencies getting installed when using `sam-build`?

**Comment by lucashuy** [comment]
Thanks for opening this issue. I don't recall if there is something within `sam build` (or `sam package` for that matter) that will avoid bundling certain dependencies. A custom Makefile builder or buildspec step like you have now seems like the current workaround for this.

We can also consider this as a feature request (and thus be raised to the team) if this is something you'd like to see
