### ISSUE TITLE
Generate warning if template elements are ignored

### ISSUE THREAD

**Issue by ericraymond** [aws/aws-sam-cli#537]
**Description:**
Related to #528, if parts of the template are skipped or ignored, a warning message should be displayed.  This message should be displayed by default (rather than via --debug)

Silently ignoring parts of the template places undue responsibility on the user to realize that the tool has not completely done its job.
 
This may be a easier, faster fix than fixing #528 and related issues.

Bonus points for:
- providing a command line option to hide these messages
- optionally ignoring the message if the value is covered by an --env-var  (This might be more work to implement than the benefit).

**Output of `sam --version`**:
SAM CLI, version 0.4.0

**Comment by jfuss** [comment]
@ericraymond While I understand the intention here, I don't think adding everything we skip or ignore is the right thing to do. Where is the line drawn? How do we keep this updated when new things are released and we can't support right away? Maybe there is some happy medium but not sure this is the correct way we should be solving the problem.

**Comment by tebruno99** [comment]
There are also a lot of features in SAM that don't translate to things that are useful. For instance, SAM Local doesn't need to honor VPC definitions when run locally. We also create all of our policies, roles, etc from SAM which should also be ignored via sam local (Validated yes, but ignored).

I'm looking through our production templates and atm and I'd say at least 95% of everything in the template actually doesn't apply to sam local at all.

Hide all, or show an huge number of possibilities doesn't seem useful for our teams.

**Comment by ericraymond** [comment]
I see what you mean.  Some elements are relevant and some are not. 

I'm ok with warnings on the "irrelevant" ones not being displayed (or perhaps only when there is a command line arg --display_all_skipped?).

There is a big difference between "not yet supported" and "never makes sense locally".  Hopefully it is very clear (not just obvious) what is what and there is some way to debug your local stack.

**Comment by sriram-mv** [comment]
From the original opening of the issue it seems to indicate that support of intrinsics was not present within SAM CLI at that point in time. However that has been updated to support instrinsics as of v0.21.0. Closing this issue.
