### ISSUE TITLE
Bug: sam deploy - ClientError

### ISSUE THREAD

**Issue by Adegbenga1** [aws/aws-sam-cli#5408]
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by Adegbenga1** [comment]
OS: Windows 10
sam --version: SAM CLI, version 1.72.0
AWS region: AWS Region [us-west-2]:

Output: https://github.com/aws/aws-sam-cli/issues/new?template=Bug_report.md&title=Bug%3A%20sam%20deploy%20-%20ClientError


An unexpected error was encountered while executing "sam deploy".
Search for an existing issue:
https://github.com/aws/aws-sam-cli/issues?q=is%3Aissue+is%3Aopen+Bug%3A%20sam%20deploy%20-%20ClientError
Or create a bug report:
https://github.com/aws/aws-sam-cli/issues/new?template=Bug_report.md&title=Bug%3A%20sam%20deploy%20-%20ClientError
ec2-user:~/environment/trivia-app $

**Comment by sriram-mv** [comment]
Could you share the template? and go deeper on the issue you experienced?

**Comment by sriram-mv** [comment]
Please re-open with more details, ClientError usually indicates Credentials not being present or malformed though.
