### ISSUE TITLE
Permission Error when Binding to port 443

### ISSUE THREAD

**Issue by mrgkoa** [aws/aws-sam-cli#5411]
Hello Guys,

I'm trying to run my lambda in local in port 443 so I can access my lamba in "https://" instead of "http://" format e.g. "https://local.lambda.com" but when doing so I get a permission error.

I already have a self signed certificate in place
![image](https://github.com/aws/aws-sam-cli/assets/129647169/3c0a429f-6e53-426c-b7f2-da9b4df85d8a)

Command:
`sam local start-api --debug --env-vars env.json --host local.lambda.com -p 443 --skip_pull_image --docker_network=services_app-network --warm_containers=EAGER`

Response:
![image](https://github.com/aws/aws-sam-cli/assets/129647169/8ec84358-7b0a-4015-813d-cf5c1b5cdb91)

Hope you there's a light on this.

Thanks,

**Comment by sriram-mv** [comment]
Could you clarify what you are trying to do? Also do you have the entire stack trace?

**Comment by mndeveci** [comment]
Resolving due to inactivity, feel free to open a new issue or comment here when you have more information, thanks!
