### ISSUE TITLE
Bug: sam build - InvalidSamDocumentException

### ISSUE THREAD

**Issue by Denn0** [aws/aws-sam-cli#5419]
SAM is not up to date with SAM resource properties.

**Template key:** 
Globals.Function.PropagateTags: True

**sam build and sam validate give error:** 
E0001 Error transforming template: 'Globals' section is invalid. 'PropagateTags' is not a supported property of 'Function'. Must be one of the following values - ['Handler', 'Runtime', 'CodeUri', 'DeadLetterQueue', 'Description', 'MemorySize', 'Timeout', 'VpcConfig', 'Environment', 'Tags', 'Tracing', 'KmsKeyArn', 'AutoPublishAlias', 'AutoPublishAliasAllProperties', 'Layers', 'DeploymentPreference', 'RolePath', 'PermissionsBoundary', 'ReservedConcurrentExecutions', 'ProvisionedConcurrencyConfig', 'AssumeRolePolicyDocument', 'EventInvokeConfig', 'FileSystemConfigs', 'CodeSigningConfigArn', 'Architectures', 'SnapStart', 'EphemeralStorage', 'FunctionUrlConfig']

**However, this is a valid key according to documentation:** 
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html#:~:text=Layers%3A%0A%20%20%20%20MemorySize%3A%0A%20%20%20%20PermissionsBoundary%3A-,PropagateTags,-%3A%0A%20%20%20%20ProvisionedConcurrencyConfig%3A

It's probably the same issue with the other Global elements like API, StepFunction.

Thanks!

**Comment by sriram-mv** [comment]
Closing in favor of tracking at: https://github.com/aws/aws-sam-cli/issues/5407
