### ISSUE TITLE
SAM error puts stack into indeterminate, undeletable state

### ISSUE THREAD

**Issue by garretwilson** [aws/aws-sam-cli#5533]
I'm using SAM version 1.88.0 on Windows 10.

If something goes wrong with a deployment (for example, the SAM bug in aws/serverless-application-model#3264), SAM leaves the stack in some `REVIEW_IN_PROGRESS` state that isn't deployed and but isn't deleted either. If I try to delete the stack using `sam delete`, it says:

> `Error: The input my-stack does not exist on Cloudformation in the region None`

I'm forced go into the CloudFormation console and manually delete the stack. I should never be forced to go into the console to do something because SAM put something into an indeterminate state. At the very least I should be able to delete the thing and start over from the command line.

(I haven't tried deleting from CloudFormation, but in any case I should be able to delete a failed deployment stack from SAM.)

**Comment by hawflau** [comment]
@garretwilson Thanks for raising the issue. Marking this issue as a bug. We will prioritize fixing it.
