### ISSUE TITLE
Bug: Typescript Function fails to run following Deploy

### ISSUE THREAD

**Issue by peadarkda** [aws/aws-sam-cli#5553]
### Description:

I am facing an issue when deploying a Typescript Lambda function using SAM CLI.

The following definition is used for creating a Typescript AWS Lambda function:

```
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
   # Other properties omitted for brevity
```

with the following folder structure:

```
template.yaml
samconfig.toml
src/
|_ app.ts
|_ tsconfig.json
|_ package.json
|_ ...
```

Here is my `tsconfig.json`

```
{
    "compilerOptions": {
      "target": "es2020",
      "strict": true,
      "preserveConstEnums": true,
      "noEmit": true,
      "sourceMap": false,
      "module":"es2015",
      "moduleResolution":"node",
      "esModuleInterop": true, 
      "skipLibCheck": true,
      "forceConsistentCasingInFileNames": true,  
    },
    "exclude": ["node_modules", "**/*.test.ts"]
  }
```

When using `sam sync` it successfully creates the function and compiles and deploys the latest source code. This Lambda runs as expected when invoked. ✅ 

However, when using `sam deploy`, the Lambda and AWS resources are successfully created/updated yet invocations trigger the following error in Cloudwatch: 🔴 

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'app'",
        "Require stack:",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:997:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1032:21)",
        "    at async start (file:///var/runtime/index.mjs:1195:23)",
        "    at async file:///var/runtime/index.mjs:1201:1"
    ]
}
```

I believe that the Typescript -> Javascript compilation is being skipped when using `sam deploy`.

I have tried running `sam build` as a prerequisite but this does not appear to make a difference.

### Steps to reproduce:

1. Create project with above folder structure
2. Create a Typescript Lambda function using the above YAML definition
3. Run `sam deploy`
4. Invoke function via Lambda console

### Observed result:

The following error is output to Cloudwatch:

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'app'",
        "Require stack:",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:997:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1032:21)",
        "    at async start (file:///var/runtime/index.mjs:1195:23)",
        "    at async file:///var/runtime/index.mjs:1201:1"
    ]
}
```

### Expected result:

I would expect the `sam deploy` behaviour to auto-compile the Typescript code, similar to how `sam sync` behaves.

This would enable the function is run successfully.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS Ventura
5. `sam --version`: SAM CLI, version 1.90.0
6. AWS region: eu-west-1

```
{
  "version": "1.90.0",
  "system": {
    "python": "3.8.17",
    "os": "macOS-13.4.1-x86_64-i386-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.8",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by mildaniel** [comment]
Hi @peadarkda, unfortunately, `sam deploy` does not compile the code in the way ` sam sync` does. Under the hood, `sam sync` runs `sam build`. `sam build` is what compiles the TS into JS. As for why `sam build` isn't working, I'm curious from which directory you're running `sam deploy` after building, and if you're providing the `-t` flag at all.

**Comment by peadarkda** [comment]
Solved! The issue was that i was running `sam deploy` and using `-t` to reference the `template.yaml` at the root of the project.

Updated this to run `sam deploy` inside the generated `.aws-sam/build/` directory and referenced the `samconfig.toml` at the root of the project.
