### ISSUE TITLE
Request: Remove dependency on `serverlessrepo` by vendoring

### ISSUE THREAD

**Issue by sirosen** [aws/aws-sam-cli#5569]
### Describe your idea/feature/enhancement

`aws-sam-cli` currently depends on `serverlessrepo`, a project which EOLed in 2019 as noted [here](https://github.com/aws/aws-sam-cli/pull/5494#pullrequestreview-1529261756).

[`serverlessrepo` pins the version of pyyaml to 5.x](https://github.com/amazon-archives/aws-serverlessrepo-python/blob/b08cb944d93519e05087fa51993a778623b69ec0/setup.py#L9), although it has very limited dependencies, this one in particular is an issue and is going to become more of a problem into the future.
If pyyaml bugs and vulnerabilities are discovered, they will most likely only be fixed in 6.x.

pyyaml 5.4.1 (the last 5.x release at time of writing) only has wheels up to python3.9, and sdist builds -- as an application will see for this install on python3.10+ -- have recently started failing due to the Cython 3.0 release.
It seems likely that pyyaml will not do any 5.4.2 release or similar to patch their `build-system.requires` data, meaning that users installing `aws-sam-cli` as a python package will have to take care to install Cython 2.x and use that to build pyyaml 5.x themselves (either by explicitly doing the build or via a non-isolated pip install).
End result: the install experience for `aws-sam-cli` is worse for a broad class of users on a growing set of environments (those with py3.10+).

### Proposal

`serverlessrepo` is only used in `samcli/commands/publish/command.py`, no other modules (except tests).
There, it is scoped down to a single function, `do_cli`, which uses several `serverlessrepo` features.

I see two feasible paths forward: to reimplement those features, or to vendor `serverlessrepo`.

Vendoring has the advantage of being _much_ faster to achieve and giving a much stronger guarantee of backwards compatibility.
The source tree for `serverlessrepo` needs to be copied into the package tree somewhere here, e.g. into `samcli/_vendor/serverlessrepo/`, imports need to be rewritten in `serverlessrepo`, and then the import of `serverlessrepo` within `samcli` can be updated to use the vendored copy.

Once `serverlessrepo` is vendored, the pyyaml version is controlled only here.

### Additional Details

I will submit a PR to do the vendoring if this gets approval from the `aws-sam-cli` maintainers.

If desirable, it can be done as a git history merge to preserve the whole `serverlessrepo` history (I would recommend _against_ this).

A decision would need to be made about preserving `serverlessrepo`'s testsuite or not.
I would tend to remove it, as it can always be fetched from the archived repo and added later, and porting it may present its own challenges.

**Comment by mildaniel** [comment]
Hi @sirosen, thanks for opening this issue. We're currently exploring various options related to this and talks are ongoing internally within the team.
