### ISSUE TITLE
Layer is not packaged correctly when --template parameter is provided to `sam deploy` command

### ISSUE THREAD

**Issue by andmoredev** [aws/aws-sam-cli#5594]
### Description:
`sam deploy` seems to not package layers correctly when --template parameter is specified on the command.
When looking at the deployed layer artifacts the `nodejs` directory is missing.

### Steps to reproduce:
1. Run sam build for your template
2. Run sam deploy specifying the --template parameter pointing to your template file.
3. View deployed lambda layer, nodejs folder will be missing.

### Observed result:
Deployment works fine, it's the artifacts while looking at the layer and downloading it, it has the missing nodejs directory.

### Expected result:
Layer to have the nodejs directory when the --template attribute is provided in the `sam deploy` command.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Running in github action | Ubuntu 22.04.2
4. `sam --version`: 1.90.0
5. AWS region: us-east-1

```
# Paste the output of `sam --info` here
```
{
  "version": "1.90.0",
  "system": {
    "python": "3.11.3",
    "os": "Linux-5.15.0-1041-azure-x86_64-with-glibc2.35"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.25+azure-2",
    "aws_cdk": "Not available",
    "terraform": "1.5.3"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

`Add --debug flag to command you are running`

**Comment by mildaniel** [comment]
When deploying using the `-t` flag, are you pointing to the built template or the template in your project root? When running `sam build`, the built artifacts are put into the `.aws-sam` directory and a subsequent `sam deploy` without specifying a template will use that template and those artifacts. If you point to the template in the project root, those artifacts will not be used.

**Comment by lucashuy** [comment]
Closing this issue, if you are still experiencing this issue even when pointing (or not using the `--template` option) to a specific template, please create new issue with those details.
