### ISSUE TITLE
Bug: sam deploy - SamConfigFileReadException

### ISSUE THREAD

**Issue by gokulnath1122** [aws/aws-sam-cli#5605]
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: windows ll
2. `sam --version`:version 1.93.0
3. AWS region: [ap-south-1]:

```
# Paste the output of `sam --info` here 
{
  "version": "1.93.0",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.22621-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}

```

`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
Thanks @gokulnath1122 for raising this issue. Could you please share with us your template, and the config file you are using in your project to try to reproduce this issue.
