### ISSUE TITLE
Change of Support Model of SAM CLI Installation Experience of Homebrew

### ISSUE THREAD

**Issue by mndeveci** [aws/aws-sam-cli#5613]
Starting from 2023/09/12, the AWS SAM CLI will no longer support installation through the AWS-managed Homebrew installer (`aws/tap/aws-sam-cli`). We recommend you use our supported first-party installers. To continue using Homebrew, the community-managed installer (`aws-sam-cli`) is available at your discretion.

From 2023/09/12, when you run `brew install aws/tap/aws-sam-cli`, you will be re-directed to the community-managed formula. This is the same behavior as running `brew install aws-sam-cli`. 

Here is the list of first-party installers:

* For MacOS PKG installers 
    * https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-macos-x86_64.pkg
    * https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-macos-arm64.pkg
* For Windows MSI installer
    * https://github.com/aws/aws-sam-cli/releases/latest/download/AWS_SAM_CLI_64_PY3.msi
* For Linux ZIP file
    * https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip

Please visit AWS SAM CLI Installation page for more information https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html

Thanks!

**Comment by francoisauclair911** [comment]
You guys should add a warning on the documentation page 
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html

**Comment by mndeveci** [comment]
> You guys should add a warning on the documentation page https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html

Thanks for the suggestion, it is in work in progress at the moment, they should be updated soon.

**Comment by ethanmills** [comment]
What's the recommended way of getting upgrades when installing from the package rather than a package manager like brew?

**Comment by sebastian-zero** [comment]
Homebrew is the only real cross-platform package manager and our whole dev team uses it to have up-to-date installations of the various AWS and other CLI tools without having different installation and update instructions for each OS devs use. 

Now we'll have to go through manually installing AWS SAM CLI / unzipping and sudo-installing on Linux dev machnes for each update.

So, why is AWS pulling support for this? Sorry if this sounds harsh, but it seems like quite a developer-hostile move by AWS.

**Comment by rafrafek** [comment]
Official installer is broken, see #5649

**Comment by mndeveci** [comment]
We appreciate all the feedback provided here.

I just want to point out that, installing through `brew install aws-sam-cli` will still be available. That is maintained in the homebrew core repository by public community.

I also want to check the cask alternative. Users will be able to install using `brew install --cask aws-sam-cli` and that will use our PKG installers in the background (note that cask is only supported for MacOS, it is not supported by Linuxbrew). That will help us to streamline the installers that we are providing today. If you think installing through cask will be a better alternative, please give this comment a 👍🏼 

Thank you!

**Comment by HCrane** [comment]
Sad to see this happen as homebrew is very convenient on WSL and, as @mndeveci has written, is not available for Linuxbrew. Could you provide a `.deb` package or any convenient way to install and maintain it on Linux?

**Comment by iainelder** [comment]
> Could you provide a `.deb` package or any convenient way to install and maintain it on Linux?

This, please. I'm an Ubuntu user. A Debian package repository with all the AWS developer tools would allow Ubuntu to automatically keep my developer tools up to date. Something like Microsoft's [Linux Package Repository](https://learn.microsoft.com/en-us/linux/packages) would be awesome.

At least publish a deb package so that I may install and uninstall using standard tools such as apt and [deb-get](https://github.com/wimpysworld/deb-get).

Are you still going to support installation via pip?

I have enough pip-installed tools that this is an acceptable solution:

```bash
pipx install/upgrade/uninstall aws-sam-cli
```

**Comment by arran4** [comment]
> Sad to see this happen as homebrew is very convenient on WSL and, as @mndeveci has written, is not available for Linuxbrew. Could you provide a `.deb` package or any convenient way to install and maintain it on Linux?

I used this script to create myself a deb file:
```
#!/bin/bash

# Define package metadata
package_name="aws-sam-cli"
package_version="1.98.0"
package_description="AWS SAM CLI"
maintainer="Your Name <your@email.com>"

# URL to download the AWS SAM CLI ZIP file
sam_cli_zip_url="https://github.com/aws/aws-sam-cli/releases/download/v$package_version/aws-sam-cli-linux-x86_64.zip"

# Set up the package directory structure
package_dir="$package_name-$package_version"
package_deb_dir="$package_dir/DEBIAN"
package_bin_dir="$package_dir/usr/local/bin"
package_sam_dir="$package_dir/usr/local/aws-sam-cli"

# Create the required directories
mkdir -p "$package_deb_dir"
mkdir -p "$package_bin_dir"
mkdir -p "$package_sam_dir"

# Download the AWS SAM CLI ZIP file
wget "$sam_cli_zip_url" -O aws-sam-cli.zip

# Extract the 'dist' directory from the ZIP file
unzip aws-sam-cli.zip -d "$package_sam_dir" dist/*

# Create the symbolic link for the 'sam' executable
ln -s "/usr/local/aws-sam-cli/dist/sam" "$package_bin_dir/sam"

# Create the control file
cat <<EOF > "$package_deb_dir/control"
Package: $package_name
Version: $package_version
Section: utils
Priority: optional
Architecture: all
Maintainer: $maintainer
Description: $package_description
EOF

# Create the .deb package
dpkg-deb --build "$package_dir"

# Clean up temporary files
rm aws-sam-cli.zip
rm -r "$package_dir"

echo "Package created: $package_name-$package_version.deb"
```

No reason this couldn't be made part of the github workflow.

**Comment by mndeveci** [comment]
SAM CLI has completed its migration and homebrew installation channel has been using [homebrew-core community bottles](https://github.com/Homebrew/homebrew-core/blob/master/Formula/a/aws-sam-cli.rb) since October 3rd, 2023. You can update your installation by running `brew update && brew upgrade` which should configure your local installation to start using the bottles published by the homebrew-core repository.

Thank you for your feedback on this ticket. A few quick notes:
1. If you experience any issues specific to the installation, feel free to create issues in this repository or [homebrew-core issues backlog here](https://github.com/Homebrew/homebrew-core/issues).
2. Regarding to debian package request, the team wanted to provide an installation method that will work on Linux free from the package manager that particular distro uses. For that sense, having a ZIP file where you can just download and throw anywhere in the system which is in the `$PATH` environment variable should be sufficient. Community is still welcome to create and manage package manager.
3. For distributing as Homebrew Cask, community is welcome to create this one as well by raising a PR to their repository.
4. We have no current plans to drop support installation via pip.

Thanks for your understanding and support!
