### ISSUE TITLE
Include files other than JS in final SAM deployment

### ISSUE THREAD

**Issue by ulissesferreira** [aws/aws-sam-cli#5633]
Hello all,

I have seen a common pattern in APIs that are powered by lambdas where database migrations are made using one of those lambdas (just not exposed as part of the API). While playing around with this setup I have noticed that if you use esbuild to bundle your lambdas you don't get the needed SQL files to run your migrations shipped when you deploy them.

Running the `sam build` command removes all other files that are not JS and source maps. 

Am I missing something or is this a legitimate problem?

Thank you

**Comment by moelasmar** [comment]
Thanks @ulissesferreira for raising this issue. Currently SAM CLI does not support adding any files that do not related to the lambda function code to the build output. We already have [this feature request](https://github.com/aws/aws-lambda-builders/issues/516) to cover this case. I am going to close your issue as it is duplicate with the Lambda Builder's feature request. Please keep an eye on the Lambda Builder's issue to keep updated.
