### ISSUE TITLE
Bug: AWS SAM CLI with Terraform does not read TF_VAR_** environment values for Windows

### ISSUE THREAD

**Issue by s-stefanov** [aws/aws-sam-cli#5671]
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
I updated the title on #5670, as it seems like this title was suppose to be for that issue. If that is not the case, @s-stefanov please open a new issue.
