### ISSUE TITLE
Bug: sam local invoke - IndexError

### ISSUE THREAD

**Issue by soumyajit05** [aws/aws-sam-cli#5673]
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
@soumyajit05 Closing since you provided no details. If you still have the details, please create a new issue with them.
