### ISSUE TITLE
Bug: --container-env-vars option is not being taken into account

### ISSUE THREAD

**Issue by gamaleonardo** [aws/aws-sam-cli#5754]
### Description:

Why the environment variables for the container are not passed if no debug_ports were also passed?

![image](https://github.com/aws/aws-sam-cli/assets/8484872/eadf7617-0766-4480-a6bf-cdc90a10fa10)

### Steps to reproduce:
Create a .json file with environment variables
Execute ```sam local start-api --container-env-vars env.json```

### Observed result:
The variables are not passed to the container.

### Expected result:
All variables in env.json to be passed to the container.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 22.04 in WSL
2. `sam --version`: 1.90.0
3. AWS region: eu-west-1

```
# Paste the output of `sam --info` here

{
  "version": "1.90.0",
  "system": {
    "python": "3.11.3",
    "os": "Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35"
  },
  "additional_dependencies": {
    "docker_engine": "23.0.4",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

`Add --debug flag to command you are running`

**Comment by lucashuy** [comment]
Thanks for raising this issue. The current behaviour is to only apply environment variables when in a debugging session. See #3795 for more details. In the mean time, we can look towards changing the help text for the command to mention that this only applies for debugging modes.
