### ISSUE TITLE
Bug: sam build - OSError

### ISSUE THREAD

**Issue by sivasaisubashbabu** [aws/aws-sam-cli#5761]
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by lucashuy** [comment]
Thanks for opening this issue. To better help us diagnose the problem, can you provide some details about the issue by editing the original post?

**Comment by moelasmar** [comment]
closing this issue as there is no details. Please open a new issue with the required details if you still face an issue with SAM CLI.
