### ISSUE TITLE
Bug: Local lambda authorizer: wildcards in resource ARNs do not match an empty string

### ISSUE THREAD

**Issue by ethanmills** [aws/aws-sam-cli#5777]
### Description:

When running with `sam local start-api`, a lambda authorizer returning a policy for `arn:aws:execute-api:us-east-1:123456789012:1234567890/Prod/*/*` does not permit requests to the root URL, which has a methodArn of `arn:aws:execute-api:us-east-1:123456789012:1234567890/Prod/GET/`. This does not reflect the deployed behaviour.

### Steps to reproduce:

- Create an application with a lambda authorizer which returns a policy with statement 
```json
{
    "Action": "execute-api:Invoke",
    "Effect": "Allow",
    "Resource": ["arn:aws:execute-api:us-east-1:123456789012:1234567890/Prod/*/*"],
}
```
- Call a lambda mounted at `/`

### Observed result:

`{"message":"User is not authorized to access this resource"}`

### Expected result:

Request should be permitted, as in the deployed API gateway

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```json
{
  "version": "1.95.0",
  "system": {
    "python": "3.8.13",
    "os": "macOS-13.5-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.2",
    "aws_cdk": "Not available",
    "terraform": "1.5.5"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by lucashuy** [comment]
Thanks for raising this issue and the PR to fix this! I can reproduce this issue with a template that has a method wildcard, and path wildcard, and can see that with a root resource ("`/`"), it matches correctly when deployed vs when using `local start-api`.
