### ISSUE TITLE
Bug: ERROR cannot find git on sam cli

### ISSUE THREAD

**Issue by dreathediva** [aws/aws-sam-cli#5783]
### Description:

Error: Cannot find git, was looking at executables: ['git', 'git.cmd', 'git.exe', 'git.bat']

### Steps to reproduce:

I'm using windows cli..I ran sam init and there's an error saying there was something wrong with the command

### Expected result:
 I expected the command to run the script

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: windows 
2. `sam --version`: sam 1.95.0
3. AWS region: us-east-2

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
Hello @dreathediva,
Thanks for raising this issue. `sam init` command reads the SAM CLI templates from our github repo, and so it depends on git to download these templates for the first time. 

So, it seems either you do not have git installed in your environment, or it needs to be added to PATH. Could you please try to install git and let us know if this fixes your problem.

**Comment by hnnasit** [comment]
Closing this issue since this error seems to be thrown due to missing git installation or adding git in your PATH as @moelasmar mentioned. Feel free to open a new issue if you still have questions/concerns.
