### ISSUE TITLE
Bug: New project root setting doesn't appear to work?

### ISSUE THREAD

**Issue by toddtarsi** [aws/aws-sam-cli#5821]
### Description:
There's a new setting thats basically essential for any mature terraform projects: ` --terraform-project-root-path`. It doesn't appear to work in latest?

### Steps to reproduce:

```
➜  sam --version                               
SAM CLI, version 1.95.0
➜  sam build --terraform-project-root-path=./..
Usage: sam build [OPTIONS] [RESOURCE_LOGICAL_ID]
Try 'sam build -h' for help.

Error: No such option: --terraform-project-root-path
```

### Observed result:

See above

### Expected result:

I expected the command to succeed or at least attempt to roll.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```
{
  "version": "1.95.0",
  "system": {
    "python": "3.8.13",
    "os": "macOS-13.4.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.2",
    "aws_cdk": "Not available",
    "terraform": "1.4.6"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

Current samconfig.toml:

```
version=0.1

[default]

[default.build.parameters]
debug = true
hook_name = "terraform"
beta_features = true
terraform_project_root_path = "./.."

[default.local.invoke.parameters]
debug = true
hook_name = "terraform"
beta_features = true
terraform_project_root_path = "./.."
env_vars = "./samconfig.env.json"

```

**Comment by hawflau** [comment]
Hi @toddtarsi, thanks for raising the issue.
According to https://github.com/aws/aws-sam-cli/compare/v1.95.0...develop, it seems like the feature (#5745) has not been released yet. It will be shipped in our next release.

**Comment by toddtarsi** [comment]
@hawflau - Ah, that explains it! Thank you for the quick response. Would it work if I switched to the nightly release?

**Comment by PaulMillen-Which** [comment]
Hi @toddtarsi This doesn't appear to be an option as of 1.108.0 (not listed in -h), although I can see it was released at the end of Aug 23. Still getting Error: No such option: --terraform-project-root-path and it doesn't work as a samconfig.yaml setting either.

**Comment by toddtarsi** [comment]
@PaulMillen-Which - Yeah, I gave up on using sam for now. It's too much pain and pretty soon you're like paying for the localstack pro plan and it just seems a bit silly. I'm just using tf and testing using staging environments.

**Comment by PaulMillen-Which** [comment]
@hawflau was the feature added then removed?
