### ISSUE TITLE
Support API Gateway v2 with Terraform on local

### ISSUE THREAD

**Issue by bastienrobert** [aws/aws-sam-cli#5848]
### Describe your idea/feature/enhancement

I wish SAM build command using the Terraform hook would generate an AWS::ApiGatewayV2::Api resource from aws_apigatewayv2_api configuration.

### Proposal

Add a new resource property mapper in the Terraform hook package: https://github.com/aws/aws-sam-cli/tree/develop/samcli/hook_packages/terraform/hooks/prepare.

**Comment by bastienrobert** [comment]
Great news! Thanks for the quick answer

**Comment by moelasmar** [comment]
hello @bastienrobert , we just released the API Gateway V2 support in [SAM CLI version 1.97.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.97.0). Please let us know if you have any more questions.
