### ISSUE TITLE
Running a SAM based python lambda vscode debugger when using a custom docker file

### ISSUE THREAD

**Issue by dangeReis** [aws/aws-sam-cli#5859]
I have a need to use a custom docker file for my python 3.11 based lambda(not based on an AWS lambda runtime) and I would like to be able to do step debugging in it using vscode.  

I have no problem doing this with AWS supported images.  

Is there documentation on what needs to be installed in order to have the local debugging working?

**Comment by hnnasit** [comment]
Hi @dangeReis, you can find all the documentation for debugging lambda functions using vscode [here](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/serverless-apps-run-debug-no-template.html). Could you describe what issues are you facing when using non AWS Lambda images in the dockerfile?

**Comment by mndeveci** [comment]
Resolving this issue for now, feel free to provide more details, we are happy re-open this issue in the future.
