### ISSUE TITLE
[Announcement] Deprecating AWS SAM CLI on Python3.7 on Oct 24th, 2023

### ISSUE THREAD

**Issue by jfuss** [aws/aws-sam-cli#5889]
**_NOTE: If you are installing AWS SAM CLI with Homebrew, Native Linux Installer or through MSI, you are not impacted by this change._**

As of now, AWS SAM CLI can be installed or used as a library within python3.7+ versions. However, python3.7 has reached its end of life by June 26th, 2023.

## What is deprecation schedule?

AWS SAM CLI will not work on python3.7 environments by October 24th, 2023.

## Will this impact my AWS Lambda functions using python3.7?

No, AWS Lambda functions which is using python3.7 as runtime will not be affected by this change. For more information about supported runtimes, please check https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

## Am I impacted by this deprecation?

If you are installing AWS SAM CLI with Homebrew, Native Linux Installer or through MSI, you are not impacted by this change. Following use cases will be impacted by this change;

* If you are using python3.7 and installing AWS SAM CLI through pip install
* If you are using aws-sam-cli as a library and you are building your application with python3.7

**Comment by mndeveci** [comment]
Completed in https://github.com/aws/aws-sam-cli/releases/tag/v1.100.0
