### ISSUE TITLE
Bug: sam init - OSError

### ISSUE THREAD

**Issue by M56413893478** [aws/aws-sam-cli#5983]
### Description:

"SamCliError: Cannot find git, was looking at executables: ['git', 'git.cmd', 'git.exe', 'git.bat'] [SamCliFailed]"

### Steps to reproduce:

Create Lambda app from command palette.

### Expected result:

Hello World template.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows
2. `sam --version`: 1.97.0
3. AWS region: us-east-1

```
# Paste the output of `sam --info` here
```
SAM CLI failed (exitcode: 1, expected 0): 
`Add --debug flag to command you are running`

**Comment by mndeveci** [comment]
Hi there,

`sam init` requires Git (https://git-scm.com/) and it looks like it is not available on your machine. Installing Git should resolve this issue, please follow guidelines about how to install Git for your operating system & environment.

Please let us know if you have further questions.

**Comment by hnnasit** [comment]
Closing this issue as the PR for gracefully handling the error has been released. Feel free to open a new issue if you are still having issues or have any questions.
