### ISSUE TITLE
Feature request: add support for sam import

### ISSUE THREAD

**Issue by softprops** [aws/aws-sam-cli#6085]
### Describe your idea/feature/enhancement

Provide a clear description. Ex. I wish SAM CLI would [...]

I wish sam could make the process of importing existing aws resources into my stack 

### Proposal

Add details of how to add this to the product.

cf natively supports importing existing resources into your stack but is currently a very laborious and manual process.

I’d like it if sam could provided a “guided” workflow to import those into my sam stacks

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

no

**Comment by mndeveci** [comment]
Thanks for the feature request, this was already raised in following issue, let's continue discussion there. https://github.com/aws/aws-sam-cli/issues/1699
