### ISSUE TITLE
Bug: Thumbprint not match my Thumbprint 

### ISSUE THREAD

**Issue by 3beerkamal** [aws/aws-sam-cli#6095]
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 11
2. `sam --version`: AWS_SAM_CLI_64_PY3
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by mndeveci** [comment]
Hi there, it is very hard for us to investigate an issue with very little details. Please re-open the issue with the missing details that we are asking in the template.

Thanks!
