### ISSUE TITLE
Windows SAM installer :: Installer integrity check failed .i.e. thumbprint value do not match the documentation

### ISSUE THREAD

**Issue by SMKrish** [aws/aws-sam-cli#6162]
### Description:
Referring to page https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html
under windows I see cert thumbprint.

The value on doc is F2 8D EB E5 8B 21 78 C9 34 27 CD 3D 0F 8B 24 CE 12 8F A0 D1
but actual value is c011d416e99a1142c0e0235118ef64c2681f3db9

### Steps to reproduce:
Steps as described on link https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html

### Observed result:
Thumbprint not matching.

### Expected result:
Thumbprint on Documentation should match value after download 

![image](https://github.com/aws/aws-sam-cli/assets/9677513/b2302b47-eefb-4696-95fa-4a86d22835dd)

**Comment by SMKrish** [comment]
I have used the latest release notes and found the SHA256 value and I have verified that value to prove the integrity.
i.e. https://github.com/aws/aws-sam-cli/releases (windows installer - sha256

**Comment by mndeveci** [comment]
Hi there,

Thanks for raising this problem. I do confirm that the previous thumbprint was only valid till Nov 8th 2023, and the new one (`c011d416e99a1142c0e0235118ef64c2681f3db9`) is valid till September 2024. We will update our documentation page accordingly.

SHA256 of the files are generated and verified for each release, so they should be always up to date.

Let us know if you have more questions while our documentation page gets updated. We will resolve this issue once update is completed.

Thanks!

**Comment by mndeveci** [comment]
Thanks for pointing out this issue, we've updated our documentation page to reflect this.
