### ISSUE TITLE
Feature request: Upgrade Lambda Functions to use nodejs18.x

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sam-cli#6195]
### Describe your idea/feature/enhancement

As of [Nov 27, 2023](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), creation of AWS Lambda Functions on Node.js 14.x is going to be stopped.

The sam-cli appears to use `nodejs14.x` in some tests

https://github.com/aws/aws-sam-cli/blob/e0e109957ac0a9b7513d56dca299d533dd5cc863/tests/functional/commands/validate/lib/models/api_merge_definitions_global.yaml#L34

### Proposal

Update Lambda Functions to. use `nodejs18.x`

### Additional Details

N/A

**Comment by moelasmar** [comment]
Thanks @trivikr for your contribution, the team usually has internal tasks to deprecate the runtimes that reaches end of life.

**Comment by moelasmar** [comment]
I reviewed your PR, it looks good to me, but it misses some of changes that should be done as part of the runtime deprecation. I will check with the team to update your PR with the remaining changes
