### ISSUE TITLE
More accurate reproduction of Lambda environment

### ISSUE THREAD

**Issue by mhart** [aws/aws-sam-cli#622]
I'm currently exploring how to make `docker-lambda` run with some more accurate settings to reproduce the Lambda environment and I think these should be applied to AWS SAM CLI local as well.

I'm specifically looking at the restrictions Lambda places on various `/dev/*` entries – but I'd also love to reproduce the more esoteric network and permissions restrictions too if possible. Any advice from the AWS Lambda team on what exactly these are, and ideally how to replicate using docker, would be greatly appreciated.

For example, if you currently run docker unmodified and do an `ls -l /dev`, you'll see something like this:

```console
$ docker run --rm --entrypoint ls lambci/lambda:nodejs8.10 -l /dev
total 0
lrwxrwxrwx 1 root root   11 Aug 19 18:47 core -> /proc/kcore
lrwxrwxrwx 1 root root   13 Aug 19 18:47 fd -> /proc/self/fd
crw-rw-rw- 1 root root 1, 7 Aug 19 18:47 full
drwxrwxrwt 2 root root   40 Aug 19 18:47 mqueue
crw-rw-rw- 1 root root 1, 3 Aug 19 18:47 null
lrwxrwxrwx 1 root root    8 Aug 19 18:47 ptmx -> pts/ptmx
drwxr-xr-x 2 root root    0 Aug 19 18:47 pts
crw-rw-rw- 1 root root 1, 8 Aug 19 18:47 random
drwxrwxrwt 2 root root   40 Aug 19 18:47 shm
lrwxrwxrwx 1 root root   15 Aug 19 18:47 stderr -> /proc/self/fd/2
lrwxrwxrwx 1 root root   15 Aug 19 18:47 stdin -> /proc/self/fd/0
lrwxrwxrwx 1 root root   15 Aug 19 18:47 stdout -> /proc/self/fd/1
crw-rw-rw- 1 root root 5, 0 Aug 19 18:47 tty
crw-rw-rw- 1 root root 1, 9 Aug 19 18:47 urandom
crw-rw-rw- 1 root root 1, 5 Aug 19 18:47 zero
```

However, on Lambda itself, it's more like:

```console
total 0
crw-rw-rw- 1 root root 1, 7 Aug 19 17:51 full
crw-rw-rw- 1 root root 1, 3 Aug 19 17:51 null
crw-rw-rw- 1 root root 1, 8 Aug 19 17:51 random
lrwxrwxrwx 1 root root   15 Aug 19 17:51 stderr -> /proc/self/fd/2
lrwxrwxrwx 1 root root   15 Aug 19 17:51 stdin -> /proc/self/fd/0
lrwxrwxrwx 1 root root   15 Aug 19 17:51 stdout -> /proc/self/fd/1
crw-rw-rw- 1 root root 1, 9 Aug 19 17:51 urandom
crw-rw-rw- 1 root root 1, 5 Aug 19 17:51 zero
```

This leads to issues with things like Python's `multiprocessing` module, which uses `/dev/shm` extensively, working on `docker-lambda` (and hence AWS SAM CLI local), but [failing on Lambda](https://github.com/lambci/docker-lambda/issues/26)

Another thing that won't work for example is process redirection (and I guess any anonymous pipes?) due to a lack of `/dev/fd`. Eg, even just this simple bash command will fail on Lambda: `cat <(echo hello)` – fails with `cat: /dev/fd/63: No such file or directory`. Now why `/dev/fd` is removed on Lambda is anyone's guess – it's just a symlink to `/proc/self/fd` (which does exist). Personally I'd love to just lobby for the AWS Lambda team to add that back in – so any help on that front would be great.

However, I assume that lobbying would take a while, so in the meantime, I'm just trying to replicate the environment more faithfully so I can at least see these errors thrown before my code makes it into production.

Perhaps the most correct solution would be to use AppArmor to model all these restrictions?

That's quite a lot of work though, and may require more hassle for users than it's worth, so I've managed to come up with a pretty good proxy for the `dev/*` restrictions, just by doing the following:

```
docker run --rm -v $PWD:/var/task \
  -v /dev/null:/dev/fd/dummy \
  -v /dev/null:/dev/shm \
  -v /dev/null:/dev/mqueue \
  -v /dev/null:/dev/core \
  -v /dev/null:/dev/tty \
  lambci/lambda:nodejs8.10
```

Any thoughts on adding these "null" mounts to the run commands in AWS SAM CLI as well? Or if you know of a simpler way to remove these entries altogether, that would be even better!

**Comment by mhart** [comment]
(I wonder if `/var/empty` is better for directory entries like `/dev/fd` and `/dev/shm`, instead of `/dev/null` – it's still not quite the same as not-existing, which would be ideal, and it will throw permissions errors instead – but may be better than errors that may arise from where a directory was expected, but a file was found)

**Comment by mhart** [comment]
Would love some thoughts on this – @sanathkr ?

**Comment by mhart** [comment]
@jfuss the difference to customers would totally depend on what was trying to read from those files/directories, and how it was trying to read (ie, is the call testing for file existence, or is it testing whether it can be written to, etc). Hopefully the errors would be very similar if not the same (eg, in the `cat` example, the error is the same with these mappings as on production Lambda, thankfully).

Ideally the files/directories would be removed entirely to be honest – but I'm not sure of an easy way to do that.

**Comment by jfuss** [comment]
In the Dockerfile, could you just `rm -rf` those directories? Or does that not work due to permissions or something?

**Comment by mhart** [comment]
@jfuss Docker adds them when it runs – they don't exist during build time.

**Comment by allan-simon** [comment]
@mhart  can the entry point of the docker image remove/unmounted them when the container is launched ?

**Comment by mhart** [comment]
@allan-simon I doubt you can do that from within the container

**Comment by jfuss** [comment]
Closing as we are now publishing lambda execution environment docker images and those are what is being used in SAM CLI.

**Comment by mhart** [comment]
@jfuss are you replicating those same device capabilities though? This issue was less about what's on the image itself (whether it's docker-lambda or not) and more about device capabilities that certain binaries, etc expect. I don't think this has been resolved.

Eg, the example I gave: `cat <(echo hello)` – fails with `cat: /dev/fd/63: No such file or directory.` on Lambda

**Comment by philiptzou** [comment]
Wondering anyone have a solution of the `cat: /dev/fd/63: No such file or directory.` issue here. I tried to create a symlink to `/proc/self/fd` but an error popped out "ln: failed to create symbolic link ‘/dev/fd’: Permission denied".

Huh, Lambda really doesn't want people to use `/dev/fd`.
