### ISSUE TITLE
`sam deploy` using orbstack does not work

### ISSUE THREAD

**Issue by georgettica** [aws/aws-sam-cli#6272]
### Description

if I have a sam cli application that builds a docker and the docker backend is orbstack (https://github.com/orbstack/orbstack).
my OS is macos.

for comparison it does work well with podman (https://github.com/containers/podman) as the docker backend

### Steps to reproduce

install orbstack
create a sam cli that uses a Dockerfile
`sam build && sam deploy`

### Observed result

could not find docker

### Expected result

build and deploy passes

### Additional environment details

1. OS: MacOS
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: SAM CLI, version 1.100.0
3. AWS region: us-east-1

**Comment by mildaniel** [comment]
Hi @georgettica, thanks for creating this issue. You might need to set the `DOCKER_HOST` environment variable to point to the orbstack socket. See https://github.com/aws/aws-sam-cli/issues/5646#issuecomment-1658320645

After setting the environment variable, I was able to run `sam build -u` and `sam local invoke` using an orbstack backed. Let me know if this works for you.
