### ISSUE TITLE
Bug: Cannot find module 'aws-sdk/clients/dynamodb' in Node.js 18.x with javascript v3

### ISSUE THREAD

**Issue by Sky-Soo-Ap** [aws/aws-sam-cli#6276]
### Description:

1) Cannot find module 'aws-sdk/clients/dynamodb in Node.js 18.x with javascript v3:
Just npm install and usage below modules;
import { DeleteItemCommand, UpdateItemCommand, GetItemCommand, DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { marshall, unmarshall } from "@aws-sdk/util-dynamodb";
import { IoTDataPlaneClient, PublishCommand } from "@aws-sdk/client-iot-data-plane"; // ES Modules import

PS: Copy and paste codes to Lambda function is okay which created directly via AWS website.

2) No need to install AWS SDK javascript v3 as  create Lambda function at AWS website;

### Steps to reproduce:

Just npm install and usage above modules;
sam deploy --guided;
API Gateway to trigger Lambda function got this error => Cannot find module 'aws-sdk/clients/dynamodb'.

### Observed result:

API Gateway to trigger Lambda function got this error => Cannot find module 'aws-sdk/clients/dynamodb'.

### Expected result:

1) Fix this bug => Cannot find module 'aws-sdk/clients/dynamodb in Node.js 18.x with javascript v3:
2) No need to install AWS SDK javascript v3 as  create Lambda function at AWS website;

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: SAM CLI, version 1.101.0
3. AWS region: ap-northeast-1

```
# Paste the output of `sam --info` here
```
{
  "version": "1.101.0",
  "system": {
    "python": "3.11.4",
    "os": "Windows-10-10.0.19045-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.17",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
`Add --debug flag to command you are running`

**Comment by hnnasit** [comment]
Hi there, it seems you are trying to build a Typescriot application and test the code on AWS console. You can run `sam build` to transpile code from Typescript to Javascript and `sam deploy` to deploy the stack. More information and examples can be found in [1](https://aws.amazon.com/blogs/compute/building-typescript-projects-with-aws-sam-cli/) and [2](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build-typescript.html#serverless-sam-cli-using-build-typescript-example). Let us know if you still have further questions or issues.

**Comment by Sky-Soo-Ap** [comment]
No changed and can not reproducible, so closed it.
