### ISSUE TITLE
[Announcement] Upcoming Runtime Deprecations

### ISSUE THREAD

**Issue by mildaniel** [aws/aws-sam-cli#6298]
### SAM CLI will stop supporting the listed runtimes
This runtime is no longer supported by [AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), and it is on the deprecation path. Users will be unable to deploy/update these functions after the listed dates.

## Am I impacted by this deprecation?
You are impacted by this if you are still using any of the listed runtimes. The recommendation is to upgrade these runtimes to a newer version which is supported by AWS Lambda.

### What is deprecation schedule?
AWS SAM CLI will not support Nodejs12.x AWS Lambda Functions after December 16th, 2023.

### What is deprecation schedule?
AWS SAM CLI will not support Ruby2.7 AWS Lambda Functions after January 2024.

### What is deprecation schedule?
AWS SAM CLI will not support Python3.7 AWS Lambda Functions after January 2024.

### What is deprecation schedule?
AWS SAM CLI will not support Nodejs14.x AWS Lambda Functions after January 2024.

### What is deprecation schedule?
AWS SAM CLI will not support Java8 on AL1 AWS Lambda Functions after January 2024.

### What is deprecation schedule?
AWS SAM CLI will not support Go1.x AWS Lambda Functions after January 2024.

For updating Go AWS Lambda functions, customers need to update the runtime to `provided.al2` or `provided.al2023`. [This blog post outlines the steps for migration.](https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/).

### What is deprecation schedule?
AWS SAM CLI will not support Custom Runtime on Amazon Linux 1 AWS Lambda Functions after January 2024.

For more information about supported runtimes by AWS Lambda, please check https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

AWS Lambda Builders will stop support using it these runtimes as a library see https://github.com/aws/aws-lambda-builders/issues/577 for more details.

**Comment by hnnasit** [comment]
Closing this issue as all the above mentioned runtimes have been deprecated already.
