### ISSUE TITLE
sam publish not throws error when duplicate version is published

### ISSUE THREAD

**Issue by ShanmugapriyanSP** [aws/aws-sam-cli#6301]
### Description:
When using the `sam publish` command to publish a new version of a SAR app, if I forget to update the semantic version in the template metadata, it succeeds leading the user to think they published a new version.

### Steps to reproduce:
We use this script when publishing to SAR:
https://github.com/awslabs/aws-athena-query-federation/blob/master/tools/publish.sh

It has the exact commands that get run. The steps to reproduce are:

1. use the script to publish an initial semantic version to SAR
2. deploy an instance of that app
3. make a code change to the app but forget to change the semantic version
4. publish the code change using the script
5. attempt to deploy an update to the previous app instance.

You'll find that step 4 doesn't throw any error but that after step 5 which also won't error, the deployed app will still be running the code from step 1.

### Expected result:
Step 4 should somehow throw an error or helpful information to indicate a new version is not published so that we can stop before running step 5.  
If you see the underlying aws command `create-application-version` it returns an error when we publish the same version `An error occurred (ConflictException) when calling the CreateApplicationVersion operation: Cannot publish version 1.2.0 for application arn:aws:serverlessrepo:eu-central-1:<account-id>:applications/<app> because it already exists`

While looking at the sam publish code, the conflict exception was explicitly ignored.
https://github.com/aws/aws-sam-cli/blob/develop/samcli/vendor/serverlessrepo/publish.py#L68

Related to https://github.com/aws/aws-sam-cli/issues/1764

**Comment by hnnasit** [comment]
Hi @ShanmugapriyanSP, thanks for reporting the issue and linking the similar old issue. It makes sense to me that the command should throw an error and not exit silently if the app is exists already. Marking this as a bug to have better error handling when the application already exists.
