### ISSUE TITLE
sam build --use-container keeps failing

### ISSUE THREAD

**Issue by eigyef** [aws/aws-sam-cli#6304]
Im running macOS and I have docker and sam installed. Running sam build --use-container always fails on my end. 

### Description:
it says "Container was not created. Skipping deletion"

### Observed result:
2023-11-21 15:52:39,705 | Container was not created. Skipping deletion
2023-11-21 15:52:39,713 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-11-21 15:52:39,719 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-11-21 15:52:39,719 | Unable to find Click Context for getting session_id

It's also strange that the telemetry configures it to us-west-2 but I need it to be us-east-1

### Expected result:
build successful

1. OS: MacOS
2. `sam --version`: SAM CLI, version 1.103.0
3. AWS region: us-east-1

```
# Paste the output of `sam --info` here
{
  "version": "1.103.0",
  "system": {
    "python": "3.8.13",
    "os": "macOS-13.3.1-arm64-i386-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.6",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}

**Comment by mildaniel** [comment]
Hey @eigyef, thanks for reporting. Are you able to provide a sample application to help us reproduce the issue?

**Comment by mndeveci** [comment]
Resolving due to inactivity, please open a new issue once you have more information about this failure. We will appreciate more log outputs as well as a reproducible example.
