### ISSUE TITLE
sam build command failing with all sam images with nodejs20.x

### ISSUE THREAD

**Issue by nadavyeru** [aws/aws-sam-cli#6319]
### Description:
sam build command failing with all sam images with nodejs20.x

### Steps to reproduce:
```
docker run -it --rm public.ecr.aws/sam/build-nodejs20.x:1.103.0-20231116235248  /bin/sh
sam build -h
```

### Observed result:
`2023-11-22 12:29:28 Command 'build' is not configured correctly. Unable to import 'samcli.commands.build'
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/samcli/cli/command.py", line 263, in get_command
    mod = importlib.import_module(pkg_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/samcli/commands/build/__init__.py", line 6, in <module>
    from .command import cli  # noqa
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/samcli/commands/build/command.py", line 11, in <module>
    from samcli.commands._utils.options import (
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/samcli/commands/_utils/options.py", line 32, in <module>
    from samcli.commands._utils.template import TemplateNotFoundException, get_template_artifacts_format, get_template_data
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/samcli/commands/_utils/template.py", line 10, in <module>
    from botocore.utils import set_value_from_jmespath
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/botocore/utils.py", line 38, in <module>
    import botocore.httpsession
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/botocore/httpsession.py", line 22, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'ssl' from 'urllib3.util.ssl_' (/usr/local/opt/sam-cli/lib64/python3.9/site-packages/urllib3/util/ssl_.py)
Usage: sam [OPTIONS] COMMAND [ARGS]...
Try 'sam -h' for help.

Error: No such command 'build'.`

### Expected result:
`sam build -h
Usage: sam build [OPTIONS] [RESOURCE_LOGICAL_ID]

  Build AWS serverless function code.

Description:

  Build AWS serverless function code to generate artifacts targeting
  AWS Lambda execution environment.

  Supported Resource Types
  ------------------------
  1. AWS::Serverless::Function

  2. AWS::Lambda::Function

  3. AWS::Serverless::LayerVersion

  4. AWS::Lambda::LayerVersion

  Supported Runtimes
  ------------------
  1. Python 3.7, 3.8, 3.9, 3.10, 3.11 using PIP

  2. Nodejs 18.x, 16.x, 14.x, 12.x using NPM

  3. Ruby 2.7, 3.2 using Bundler

  4. Java 8, Java 11, Java 17 using Gradle and Maven

  5. Dotnet6 using Dotnet CLI (without --use-container)

  6. Go 1.x using Go Modules (without --use-container)

  This command may not require access to AWS credentials.

Examples:

    $sam build

    $sam build FUNCTION_LOGICAL_ID

    $sam build --use-container

    $sam build --use-container --container-env-var-file env.json

    $sam build && sam local invoke

    $sam build && sam deploy

Required Options:

    -t,--template,--template-file
                                    AWS SAM template file.  [default: template.[yaml|yml|json]]

Template Options:

    --parameter-overrides STRING,LIST
                                    String that contains AWS CloudFormation parameter overrides encoded as key=value
                                    pairs.

AWS Credential Options:

    --region TEXT
                                    Set the AWS Region of the service. (e.g. us-east-1)

    --profile TEXT
                                    Select a specific profile from your credential file to get AWS credentials.

Build Strategy Options:

    -p, --parallel
                                    Enable parallel builds for AWS SAM template's functions and layers.

    -x, --exclude TEXT
                                    Name of the resource(s) to exclude from AWS SAM CLI build.

    -m, --manifest PATH
                                    Path to a custom dependency manifest. Example: custom-package.json

    -c, --cached / --no-cached
                                    Enable cached builds.Reuse build artifacts that have not changed from previous
                                    builds.

                                    AWS SAM CLI evaluates if files in your project directory have changed.

                                    Note: AWS SAM CLI does not evaluate changes made to third party modules that the
                                    project depends on.Example: Python function includes a requirements.txt file with
                                    the following entry requests=1.x and the latest request module version changes
                                    from 1.1 to 1.2, AWS SAM CLI will not pull the latest version until a non-cached
                                    build is run.

Container Options:

    -u, --use-container
                                    Build functions within an AWS Lambda-like container.

    -e, --container-env-var TEXT
                                    Environment variables to be passed into build containers Resource format
                                    (FuncName.VarName=Value) or Global format (VarName=Value).

                                     Example: --container-env-var Func1.VAR1=value1 --container-env-var VAR2=value2

    -ef, --container-env-var-file PATH
                                    Environment variables json file (e.g., env_vars.json) to be passed to build
                                    containers.

    -bi, --build-image TEXT
                                    Container image URIs for building functions/layers. You can specify for all
                                    functions/layers with just the image URI (--build-image public.ecr.aws/sam/build-
                                    nodejs18.x:latest). You can specify for each individual function with (--build-
                                    image FunctionLogicalID=public.ecr.aws/sam/build-nodejs18.x:latest). A combination
                                    of the two can be used. If a function does not have build image specified or an
                                    image URI for all functions, the default SAM CLI build images will be used.

    -mw, --mount-with [READ|WRITE]
                                    Specify mount mode for building functions/layers inside container. If it is
                                    mounted with write permissions, some files in source code directory may be
                                    changed/added by the build process. By default the source code directory is read
                                    only.

    --skip-pull-image
                                    Skip pulling down the latest Docker image for Lambda runtime.

    --docker-network TEXT
                                    Name or ID of an existing docker network for AWS Lambda docker containers to
                                    connect to, along with the default bridge network. If not specified, the Lambda
                                    containers will only connect to the default bridge docker network.

Artifact Location Options:

    -b, --build-dir DIRECTORY
                                    Directory to store build artifacts.Note: This directory will be first removed
                                    before starting a build.

    -cd, --cache-dir DIRECTORY
                                    Directory to store cached artifacts. The default cache directory is .aws-sam/cache

    -s, --base-dir DIRECTORY
                                    Resolve relative paths to function's source code with respect to this directory.
                                    Use this if SAM template and source code are not in same enclosing folder. By
                                    default, relative paths are resolved with respect to the SAM template's location.

Extension Options:

    --hook-name TEXT
                                    Hook package id to extend AWS SAM CLI commands functionality.

                                    Example: `terraform` to extend AWS SAM CLI commands functionality to support
                                    terraform applications.

                                    Available Hook Names: ['terraform']

    --skip-prepare-infra / --prepare-infra
                                    Skip preparation stage when there are no infrastructure changes. Only used in
                                    conjunction with --hook-name.

Configuration Options:
    Learn more about configuration files at:

    https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html.

    --config-env TEXT
                                    Environment name specifying default parameter values in the configuration file.
                                    [default: default]

    --config-file TEXT
                                    Configuration file containing default parameter values.  [default: samconfig.toml]

Terraform Hook Options:

    --terraform-project-root-path PATH
                                    Used for passing the Terraform project root directory path. Current directory will
                                    be used as a default value, if this parameter is not provided.

Beta Options:

    --beta-features / --no-beta-features
                                    Enable/Disable beta features.

Other Options:

    --debug
                                    Turn on debug logging to print debug message generated by AWS SAM CLI and display
                                    timestamps.

    -h, --help
                                    Show this message and exit.`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by nadavyeru** [comment]
solved with running the container with 
e 'LD_LIBRARY_PATH='

**Comment by alexeyvoren** [comment]
@nadavyeru Great find! This is an excellent catch and truly important fix.
Your solution resolves the issue perfectly!
I just want to expand on your solution with a short usage example:

`LD_LIBRARY_PATH= sam build`
