### ISSUE TITLE
Bug:  ELIFECYCLE Command failed with exit code 141 on automatic tests.

### ISSUE THREAD

**Issue by Juubes** [aws/aws-sam-cli#6321]
I spent about six hours debugging this and figured out what's up.

### Description:

I had a bug with the `sam local start-api` command. The CLI command throws 141 and exits the whole stack. No other info. I was running automated tests against a local backend environment. I have an API Gateway + Authorizers + Lambda + DynamoDB stack. I'm using remote DynamoDB. We're also using CDK and testing it locally with SAM. I couldn't reproduce the error with Postman. **I fixed the error with 5s -> 30s timeout on tests**

### Steps to reproduce:

1. Start the API Gateway + Lambdas stack with `sam local start-api`
2. Run automatic tests with Jest + supertest
3. Make a request to the local backend with 
```
import * as request from 'supertest';

const res = await request(API_URL)
  .get('account/data')
  .send();
```

### Observed result:
```
2023-11-22 23:22:46,285 | Starting a timer for 3 seconds for function 'GetAccountDataFunction'                                        
START RequestId: 42b2fbe9-fc18-4063-82b4-5f58c82d8d19 Version: $LATEST
END RequestId: 42b2fbe9-fc18-4063-82b4-5f58c82d8d19
REPORT RequestId: 42b2fbe9-fc18-4063-82b4-5f58c82d8d19  Init Duration: 0.12 ms  Duration: 494.41 ms     Billed Duration: 495 ms Memory Size: 128 MB   Max Memory Used: 128 MB

2023-11-22 23:22:47,982 | Cleaning all decompressed code dirs                                                                         
2023-11-22 23:22:47,982 | No Content-Type given. Defaulting to 'application/json'.                                                    
2023-11-22 23:22:47 127.0.0.1 - - [22/Nov/2023 23:22:47] "GET /v1/d/account/data HTTP/1.1" 200 -
 ELIFECYCLE  Command failed with exit code 141.
```

Sometimes the backend crashes on different functions. We now know it's about the timeout of the frontend.

### Expected result:
No error

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
Linux, running inside a VSCode dev container. CDK through NPM.

SAM info:
{
  "version": "1.99.0",
  "system": {
    "python": "3.11.3",
    "os": "Linux-6.5.4-76060504-generic-x86_64-with-glibc2.35"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.7-1",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}

**Comment by mildaniel** [comment]
Hi @Juubes, thanks for raising this issue. I'm having some trouble reproducing, are you able to provide a minimal sample app that you're able to reproduce with?
