### ISSUE TITLE
Bug: sam local start-lambda - ReadTimeout

### ISSUE THREAD

**Issue by eediksolves** [aws/aws-sam-cli#6346]
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by mildaniel** [comment]
Thanks for reporting @eediksolves. Are you able to provide some additional information to help us reproduce the issue? We recommend following the issue to template provided.

**Comment by mildaniel** [comment]
Going to close out this issue for now. If you are able to provide more details, please open a new issue.
