### ISSUE TITLE
Bug: `sam local` includes extraneous `version` attribute in `ApiGatewayLambdaEvent` (incompatible with aws-lambda-rust-runtime)

### ISSUE THREAD

**Issue by ramosbugs** [aws/aws-sam-cli#6442]
### Description:

#1942 added support for API Gateway HTTP (aka v2) APIs to `sam local`. This change also modified the API Gateway REST API (aka v1) request payload to include a `"version": "1.0"` attribute that is **not** part of the payload that API Gateway includes in production.

This extraneous `version` attribute breaks compatibility with runtimes like the [aws-lambda-rust-runtime](https://github.com/awslabs/aws-lambda-rust-runtime) that [reject payloads that include unexpected fields](https://github.com/awslabs/aws-lambda-rust-runtime/blob/d513b13b4c48122602c0690f55147607f3bcc0da/lambda-events/src/event/apigw/mod.rs#L16).

As a consequence, the current versions of aws-sam-cli and aws-lambda-rust-runtime are mutually incompatible with one another for local testing. This is quite frustrating.

Since `sam local` is supposed to behave identically (as much as possible) to the corresponding AWS services, I feel the `version` attribute should be removed from `ApiGatewayLambdaEvent`:
https://github.com/aws/aws-sam-cli/blob/aa132f863a6580ed2e279fabfc44f7fc6af7f2f1/samcli/local/events/api_event.py#L208

### Steps to reproduce:

1. Define an `AWS::Serverless::Api` resource and corresponding Lambda proxy integration
2. Run `sam local`

### Observed result:

Lambda receives a request payload that includes `"version": "1.0"` (not present in API Gateway payloads).

### Expected result:

Lambda should receive a request payload without `version` that mirrors the payload API Gateway sends in production.

**Comment by hnnasit** [comment]
Hi @ramosbugs, thanks for reporting the issue. I see your PR in `aws-lambda-rust-runtime` got merged. Does that unblock you? As for the `version` field, I do see it in the [docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) for both the versions of API Gateway.

**Comment by ramosbugs** [comment]
> Hi @ramosbugs, thanks for reporting the issue. I see your PR in `aws-lambda-rust-runtime` got merged. Does that unblock you?

Yup, but I think this is still a bug in aws-sam-cli worth fixing.

> As for the `version` field, I do see it in the [docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) for both the versions of API Gateway.

API Gateway **HTTP** APIs support two payload versions, which is what that link documents. API Gateway **REST** APIs do not have a `version` field: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format

It's easy to confuse because HTTP APIs are sometimes called v2 APIs, and REST APIs are sometimes called v1 APIs, but this nomenclature is independent of the HTTP API **payload** versioning represented by the `version` field:

Quote from the docs you linked above:
>  If you create a Lambda integration by using the AWS CLI, AWS CloudFormation, or an SDK, you must specify a `payloadFormatVersion`. The supported values are `1.0` and `2.0`.

In this repo, I believe `ApiGatewayLambdaEvent` represents a REST API payload that shouldn't include a `version`. `ApiGatewayV2LambdaEvent` represents an HTTP API that seems to also use payload version 2.0 (although I see from the tests there is some support for version 1.0 HTTP API payloads as well: see `http_v1_payload_route` compared with `api_gateway_route`):
https://github.com/aws/aws-sam-cli/blob/821fcb64185f365c469eba9aeaf377541ffb367f/tests/unit/local/apigw/test_local_apigw_service.py#L33-L65

**Comment by hnnasit** [comment]
Thanks for providing the detailed references @ramosbugs. Marking this as a bug for the team to check if the field `version` can be removed without breaking any existing customers.
