### ISSUE TITLE
Bug: issue in local start api

### ISSUE THREAD

**Issue by nirob-appsbee** [aws/aws-sam-cli#6562]
### Description:

sam local start api create as much docker container as much function i have created . so the big problem is that i have more than 50 function and and a lambda layer . so local start api create 50 docker container and for run local api it's taking huge time and huge resource also . 

### Steps to reproduce:
crate as much function as you can and a lambda layer also . after that add the lambda layer in all this function and create api and attache api in all of function and after that run sam local start api . 

### Expected result:

it should open 1 single container and run all the api so that machine resource need lower and api can run fast

**Comment by hnnasit** [comment]
Hi @nirob-appsbee, can you try running the command `sam local start-api --warm-containers LAZY` which enables the containers to be loaded only when each function is first invoked. This will save time in not initializing containers for all the functions at start time.

**Comment by hnnasit** [comment]
Closing as the issue has been inactive for a while. Feel free to try the suggestion above and open a new issue if you still have questions or concerns.
