### ISSUE TITLE
sam build image buffers output from docker until it's finished

### ISSUE THREAD

**Issue by kwanxyz** [aws/aws-sam-cli#6576]
### Description:

sam build appears to be hanging when building the docker image. There is no output during the build process and this makes it appear as the sam build process is frozen and not responding when an image takes a long time to build.  The output does eventually get displayed when the build process completes.  I can see the docker output when I ran docker build.  I have also confirmed this behavior with aws support team.

This does not happen when using my old intel mac. 

### Steps to reproduce:

Create a sam project in python with an docker image

Run command "sam build" 

### Observed result:

Docker build outputs are missing until the image build is completed.

### Expected result:

Docker build outputs during the build process

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region: us-east-1

I am on M2 macbook pro running apple silicon, 
SAM CLI, version 1.107.0
Docker Desktop 4.26.0 
```
# Paste the output of `sam --info` here
```
{
  "version": "1.107.0",
  "system": {
    "python": "3.8.13",
    "os": "macOS-13.5-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.7",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}

`Add --debug flag to command you are running`

**Comment by fade2black** [comment]
@kwanxyz I guess I mentioned the same issues in this [issue (6507)](https://github.com/aws/aws-sam-cli/issues/6507). Are they same?

**Comment by kwanxyz** [comment]
@fade2black yes, same issue. It's super annoying since my image takes a while to build, around 10 minutes. And sometimes the build process would fail but I wouldn't know of the failure since I get no output during the build process,

**Comment by fade2black** [comment]
@kwanxyz yes, the same is here. It fails, and you don't know the reason. Really annoying. Then you need to build it using docker command without sam and see what happens.

**Comment by kwanxyz** [comment]
@fade2black I contacted aws support and they are seeing the same problem using the latest sam cli.

**Comment by fade2black** [comment]
@kwanxyz I hope they assign this issue to the highest priority, otherwise it is really annoying.

**Comment by hnnasit** [comment]
Hi @kwanxyz, thanks for reporting the issue. As @fade2black mentioned, this seems similar to the issue 6507. I am closing this issue since it's a duplicate. Please track the other issue for updates and we will prioritize fixing the bug.
