### ISSUE TITLE
Crazy dependencies 

### ISSUE THREAD

**Issue by OpakAlex** [aws/aws-sam-cli#6579]
```shell
==> Installing dependencies for aws-sam-cli: libssh2, libgit2, python@3.12, z3, zstd, ninja, swig, llvm, rust, python-setuptools, python@3.11, pycparser, cffi, python-flit-core, python-packaging, python-pathspec, python-typing-extensions, python-setuptools-scm, python-pluggy, python-trove-classifiers, python-hatchling, python-hatch-fancy-pypi-readme, python-hatch-vcs, python-attrs, six, python-dateutil, python-pyproject-hooks, python-build, python-networkx, python-pbr, python-mpmath, python-sympy, python-urllib3, cython, python@3.10, pyyaml, cfn-lint, pygments, python-click, python-markupsafe, python-jinja, python-certifi, python-charset-normalizer, python-idna, python-requests, cookiecutter, python-cryptography and python-pytz
```

For me just a question, Do you think this is normal?) 
3 python versions to install one lib...... 3

I think we should add pornhub client also, at least something good to watch for 2h, while this hell will be installed. 

`usr/local/Cellar/llvm/17.0.6_1: 7,207 files, 1.5GB, built in 114 minutes 14 seconds`

How match CO2 we produced?

**Comment by hnnasit** [comment]
Hi @OpakAlex, sorry for your experience. It seems you are trying to install SAM CLI using brew which is now maintained by the [community](https://github.com/Homebrew/homebrew-core/blob/master/Formula/a/aws-sam-cli.rb). Please check out the [docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html) on how to install SAM CLI using the binaries that we provide.

**Comment by OpakAlex** [comment]
This is amazing feature "closed this as [completed](https://github.com/aws/aws-sam-cli/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [5 minutes ago](https://github.com/aws/aws-sam-cli/issues/6579#event-11631959800)". We realy should ask religion to develop this feature! Really, why?
- We have pour people -> it's not our scope, close it! No more poor people. Amazing! let's vote!
