### ISSUE TITLE
--image_repositories not working

### ISSUE THREAD

**Issue by jorgesisco** [aws/aws-sam-cli#6630]
I am working on a shell script that ends up creating a final command based on recent version tag for each one of the repos I have for each lambda.

In the `--image-repositories` I am providing the URIs to sam deploy and in `--parameter-overrides` I provide the URI in order to be able to included in the `template.yaml` I already defined the parameter names in the template.

```commandline
sam deploy --image-repositories ServiformProxyEventLambda=123456678.dkr.ecr.eu-central-1.amazonaws.com/serviform-api-proxy:v0.0.8 TextClassifierReq=123456789.dkr.ecr.eu-central-1.amazonaws.com/text-classifier-req:v0.1.0 SFTPEventLambda=123456789.dkr.ecr.eu-central-1.amazonaws.com/sftp-req-jud:v0.1.3 NerReq=123456789.dkr.ecr.eu-central-1.amazonaws.com/ner-req:v0.2.5 ProcessEmailLambda=123456789.dkr.ecr.eu-central-1.amazonaws.com/etl-email-images:v1.2.3 Serviform=123456789.dkr.ecr.eu-central-1.amazonaws.com/serviform:v0.3.3 \
--parameter-overrides ServiformProxyEventLambdaImageUri=123456789.dkr.ecr.eu-central-1.amazonaws.com/serviform-api-proxy:v0.0.8 TextClassifierReqImageUri=123456789.dkr.ecr.eu-central-1.amazonaws.com/text-classifier-req:v0.1.0 SFTPEventLambdaImageUri=123456789.dkr.ecr.eu-central-1.amazonaws.com/sftp-req-jud:v0.1.3 NerReqImageUri=123456789.dkr.ecr.eu-central-1.amazonaws.com/ner-req:v0.2.5 ProcessEmailLambdaImageUri=123456789.dkr.ecr.eu-central-1.amazonaws.com/etl-email-images:v1.2.3 ServiformImageUri=123456789.dkr.ecr.eu-central-1.amazonaws.com/serviform:v0.3.3

```

The issue is that I am getting the following error: 
```
Error: Invalid value for '--image-repositories': --image-repositories is not a valid format, it needs to be of the form function_logical_id=ECR_URI

```

I double checked my function_logical_id and they all seem ok, now I think I need to only provide one repo at the time? there should be way of being able to include all the repos for each deployment right?

**Comment by mndeveci** [comment]
Can you provide which version you are using? Also, can you run same command with `--debug` flag and provide the output?

I've tried to re-produce locally but it didn't fail during argument parsing step.

**Comment by jorgesisco** [comment]
> Can you provide which SAM CLI version you are using? Also, can you run same command with `--debug` flag and provide the output?
> 
> I've tried to re-produce locally but it didn't fail during argument parsing step.

Hey! I am using `SAM CLI, version 1.103.0`

I managed to solve it by adding the values into the `samconfig.toml` with the following format:

```
parameter_overrides = "LambdaImageUri1=ECR_URL_1 LambdaImageUri2=ECR_URL_2 LambdaImageUri3=ECR_URL_3"

image_repositories = ["function_logical_id_1=ECR_URI_1", "function_logical_id_2=ECR_URI_2", "function_logical_id_3=ECR_URI_3"]

```

I would assume the format would also work if I were to provide them in the command as shown in my question, but since I am adding that to the `samconfig.toml`, I can just do `sam deploy` and I get no changes so far, since I have no recent changes in ECR and no changes in the template.
