### ISSUE TITLE
An HTTP Client raised an unhandled exception: sequence item 0: expected str instance, bytes found

### ISSUE THREAD

**Issue by Vikku14** [aws/aws-sam-cli#6668]
### Description:

**sam deply** is giving this error

> An HTTP Client raised an unhandled exception: sequence item 0: expected str instance, bytes found

### Steps to reproduce:

i was using aws-sam-cli version **1.74.0**. everything was working.
Once i update the aws-sam-cli using 

`brew upgrade aws-sam-cli`

And, Now after updation the version is **1.109.0**.

### Observed result:

**sam deply** is showing

```
Error: Unable to upload artifact Layer referenced by ContentUri parameter of Layer resource.
An HTTP Client raised an unhandled exception: sequence item 0: expected str instance, bytes found

```
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```
# Paste the output of `sam --info` here
{
  "version": "1.109.0",
  "system": {
    "python": "3.12.1",
    "os": "macOS-14.2.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "25.0.2",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```
**i am using Runtime: python3.7 in Yaml files**

**Comment by orangekame3** [comment]
same error occur for me

```bash
An HTTP Client raised an unhandled exception: sequence item 0: expected str instance, bytes found

❯❯❯ sam --info
{
  "version": "1.109.0",
  "system": {
    "python": "3.12.1",
    "os": "macOS-14.2.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.6",
    "aws_cdk": "Not available",
    "terraform": "1.5.7"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}


```

**Comment by orangekame3** [comment]
It's same issue
https://github.com/aws/aws-sam-cli/issues/6667

**Comment by Vikku14** [comment]
i just found the solution.
i uninstalled the **aws-sam-cli** completely from my Mac. also from **brew**
i downloaded the official latest version(1.109.0) from [aws website ](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html). 
Now `sam deply` is working
