### ISSUE TITLE
Bug: Cannot push image to public Repository on ECR

### ISSUE THREAD

**Issue by h3110Fr13nd** [aws/aws-sam-cli#6691]
### Description:

Pushing image to Public Repository on ECR gives **Invalid Image Repository ECR URI**
In `samconfig.toml` setting `image_repository` already doesn't work, while setting `image_repositories` work but only for private repos.
```toml
[default.deploy.parameters]
# ...
image_repositories = ["<Function Name>=public.ecr.aws/<some code>/<repo name>"]
# ...
```
### Observed result:

```bash
Usage: sam deploy [OPTIONS]
Try 'sam deploy -h' for help.

Error: Invalid value for '--image-repository': Invalid Image Repository ECR URI: public.ecr.aws/<some code>/<repo name>
```

### Expected result:

The Image should be pushed in my public repo, Similar to Private repos.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 22.04
2. `sam --version`: SAM CLI, version 1.109.0
3. AWS region: us-east-1

```bash
$ sam --info

# Output 
{
  "version": "1.109.0",
  "system": {
    "python": "3.11.3",
    "os": "Linux-6.5.0-15-generic-x86_64-with-glibc2.35"
  },
  "additional_dependencies": {
    "docker_engine": "25.0.2",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}

```

`Add --debug flag to command you are running`

**Comment by mildaniel** [comment]
Hi @h3110Fr13nd, thanks for creating this issue. Lambda does not currently support image functions inside of public ECR. The image function must be in a private ECR inside of the same region and account.

**Comment by h3110Fr13nd** [comment]
> Hi @h3110Fr13nd, thanks for creating this issue. Lambda does not currently support image functions inside of public ECR. The image function must be in a private ECR inside of the same region and account.

So, This is an intended behaviour. And not a bug. Thank you for telling.
I'm Closing the issue with "won't fix". As it is intended behaviour.
Still, I'll recommend to include this feature.
