### ISSUE TITLE
Is it possible to config custom authorizer and run locally?

### ISSUE THREAD

**Issue by moonctp** [aws/aws-sam-cli#672]
Hi, 

I am now using Serverless with Golang to write some API functions. Because some of my APIs need Authorization before processing, so i have added a custom authorizer. Everything works good after deploying to AWS. But when i work on some APIs in my local environment ( actually i need to add some content in the response Context in my custom authorizer ),  i can not figure out how to config the template.yml to run the custom authorizer. 

I try to read all the issues about the custom authorizer under this repo but can not find any solution on this. Is there any way to config it to run locally?

**Comment by matthewduren** [comment]
https://github.com/awslabs/aws-sam-cli/issues/137
