### ISSUE TITLE
Need help with Error: No images found to deploy, try running sam build

### ISSUE THREAD

**Issue by ddl-msingh** [aws/aws-sam-cli#6720]
Can someone tell me what could be wrong, I keep on getting below error even after scessfully building via sam build

Error: No images found to deploy, try running sam build
SAM CLI, version 1.109.0

Building Apple M1

**Comment by lucashuy** [comment]
Hi, can you provide a project where we can reproduce this?

**Comment by lucashuy** [comment]
Closing this issue due to a lack of information, please open another issue if you have more information or other problems to report.
