### ISSUE TITLE
Bug: sam build - TypeError

### ISSUE THREAD

**Issue by rush257** [aws/aws-sam-cli#6739]
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by jysheng123** [comment]
Hi, sorry for us to take a look at the issue we would need a lot more context, could you respond by filling out the initial issue template? Thanks so much.

**Comment by hnnasit** [comment]
Closing as there is not enough information for us to investigate. Please open a new issue with more details if you are still facing issues or have questions.

**Comment by yan-olydis** [comment]
i have the same error " unhashable type: 'list'"
this is below my sam config
Run sam --info 
{
  "version": "1.110.0",
  "system": {
    "python": "3.11.3",
    "os": "Linux-6.5.0-1015-azure-x86_64-with-glibc2.35"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.9",
    "aws_cdk": "Not available",
    "terraform": "1.7.4"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}

Telemetry {'metrics': [{'commandRun': {'requestId': 'dfa3bfe4-38c7-4976-a8d3-a6daf5eaacc0', 'installationId': '4840ff81-f838-4eb6-8f42-3296c6e3da54', 'sessionId': '78665f6d-34f4-4bda-8478-ac178772b58c', 'executionEnvironment': 'GitHubAction', 'ci': True, 'pyversion': '3.10.12', 'samcliVersion': '1.110.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': '7041e5aea25a39391ab66afa24e528086268a744f7be816514ca82e0d5ed1c80', 'initialCommit': None}, 'duration': 124, 'exitReason': 'TypeError', 'exitCode': 255}}]}
2024-03-06 09:30:30,373 | Unable to find Click Context for getting session_id.
