### ISSUE TITLE
Bug: Updating the CloudFormation stack via "sam deploy" gives an error "Update of resource type is not permitted"

### ISSUE THREAD

**Issue by bbs-md** [aws/aws-sam-cli#6786]
### Description:
Deployed the project with resource `Type: AWS::SNS::Topic`

Change type `AWS::SNS::Topic` -> `AWS::SQS::Queue` (template.yaml) and update stack via 

```
sam update
```

I got an error 
```
Error: Failed to create changeset for the stack: incoming-email-processing-bug, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Update of resource type is not permitted. The new template modifies resource type of the following resources: [IncomingEmailLambdaDLQ]
```

### Steps to reproduce:
Create a project with `AWS::SNS::Topic` resource and deploy it. In the template.yaml,  change the resource type `AWS::SNS::Topic` -> `AWS::SQS::Queue`. Deploy updates

```
sam deploy
```

### Observed result:
Got the result in the terminal
Error: Failed to create changeset for the stack: incoming-email-processing-bug, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Update of resource type is not permitted. The new template modifies resource type of the following resources: [IncomingEmailLambdaDLQ]

### Expected result:
Updated CloudFormation stack.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Manjaro Linux x86_64
Host: Virtual Machine Hyper-V UEFI Release v4.0
Kernel: 6.1.77-2-MANJARO
2. `sam --version`: `SAM CLI, version 1.110.0`
3. AWS region: `eu-west-1`

```
{
  "version": "1.110.0",
  "system": {
    "python": "3.11.0",
    "os": "Linux-6.1.77-2-MANJARO-x86_64-with-glibc2.39"
  },
  "additional_dependencies": {
    "docker_engine": "25.0.2",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by sidhujus** [comment]
Hi, thanks for reaching out. I checked and this does look to be the intended behaviour from CloudFormation when trying to change the resource type of an existing SnsTopic resource. You should be able to work around this by changing the name of the resource so that it recognizes the queue as a new resource.
