### ISSUE TITLE
Bug: sam sync crashes when a "prepare" statement is in package.json

### ISSUE THREAD

**Issue by maplion** [aws/aws-sam-cli#6835]
### Description:
`sam sync` crashes on loading when there is a "prepare" statement within "scripts" section of the package.json

Context:
I'm using the npm husky library (https://typicode.github.io/husky/get-started.html) as an "automated" way to have things done at commit time consistently among my team and it currently seems to break sam sync because of the "prepare": "husky" in the package.json that is required to be there to ensure everyone on the team installs it at least once for each repo/project.

### Steps to reproduce:
1. Install husky `npm install --save-dev husky`
2. Setup husky `npx husky init` -- you should see a `"prepare": "husky"` added as a final "scripts" line within the package.json (if not, add it manually).
3. Run sam sync for some template.yml

### Observed result:
sam sync crashes with a Python error during startup -- this can be resolved by temporarily removing the prepare statement and starting again.

### Expected result:
I expect sam sync to start as normal and ignore the prepare statement

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 11
4. `sam --version`: 1.108.0
5. AWS region: us-east-1

```
{
  "version": "1.108.0",
  "system": {
    "python": "3.11.7",
    "os": "Windows-10-10.0.19045-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by sidhujus** [comment]
Hi @maplion, Thanks for opening the issue! I wasn't able to reproduce the error when I tried running `sam sync` after following the steps you posted. Could you try running `sam sync` with the `--debug` flag and providing the output here?

**Comment by maplion** [comment]
@sidhujus 

Here is the error I receive:

```shell
npm ERR! A complete log of this run can be found in: C:\Users\<user>\AppData\Local\npm-cache\_logs\2024-03-15T19_55_36_822Z-debug-0.log

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\lib\sync\watch_manager.py", line 257, in _execute_infra_sync
    infra_sync_result = self._execute_infra_context(first_sync)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\lib\sync\watch_manager.py", line 187, in _execute_infra_context
    return self._infra_sync_executor.execute_infra_sync(first_sync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\lib\sync\infra_sync_executor.py", line 168, in execute_infra_sync
    self._build_context.run()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\commands\build\build_context.py", line 332, in run
    raise UserException(str(ex), wrapped_from=wrapped_from) from ex
samcli.commands.exceptions.UserException: NodejsNpmEsbuildBuilder:NpmInstall - NPM Failed: npm WARN config production Use `--omit=dev` instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
'husky' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code 1
npm ERR! path C:\Users\RDAMMR~1\AppData\Local\Temp\tmp8k6l4ov8
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c husky
```

**Comment by sidhujus** [comment]
Spoke on slack, summarizing the workarounds here for visibility. When SAM CLI builds a node project it does not download the dev dependencies which is what causes the command not found error. specifying the `--build-in-source` flag bypasses this issue, additionally adding `husky` to the regular dependencies will also fix the problem. A third possible workaround is to follow the guidance provided [here](https://typicode.github.io/husky/how-to.html#ci-server-and-docker) and set the command to never fail

**Comment by maplion** [comment]
I ended up using the `"prepare":"husky || true"` method to solve this as it seems to be the simplest and does what I need it to do without interruptions to sam sync.  Both other methods were tried and work, but this was my preferred way to go about it.  Closing this as I consider this a viable workaround.  Thanks for the help @sidhujus !

**Comment by efimk-me** [comment]
https://github.com/aws/aws-lambda-builders/issues/635
