### ISSUE TITLE
Verifying the integrity of the AWS SAM CLI installer

### ISSUE THREAD

**Issue by ashlllll** [aws/aws-sam-cli#6836]
### Description:

Hi there,

I followed those steps to do in my laptop, but it doesn't work. I don't know why. Please help me fix it, thanks.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by sidhujus** [comment]
Hi Thanks for opening the issue! Could you provide more information on what steps you followed and what exactly isn't working? Thanks!

**Comment by sidhujus** [comment]
Closing the issue for now as theres not enough information. Feel free to open a new one with the required fields filled out
