### ISSUE TITLE
How to report bug in StepFunctionsLocal.jar ?

### ISSUE THREAD

**Issue by anentropic** [aws/aws-sam-cli#6846]
I know that users of SAM may also be users of the StepFunctionsLocal.jar mock server as recommended [in the SAM docs](https://docs.aws.amazon.com/step-functions/latest/dg/sfn-local-lambda.html#start-stepfunctions-local)

The tool itself doesn't seem to be on GitHub and the docs don't provide any link where to report bugs?

Do the SAM team have any contact with the authors of that tool within AWS?

I was getting this error when trying to execute my statemachine:
```
[400] StartExecution <= Invalid State Machine Definition: 'Parse error: State Machine contained a syntax error.'
```

There are some obvious problems with this error (and error logging by that tool generally):
- no stack trace
- no line number or context for where in my statemachine definition the "syntax error" exists

I had to decompile the jar in order to attach a debugger (painful)

Catching the error in JDB allows to see the real problem:
```
e.getMessage() = "Unrecognized field "ProcessorConfig" (class com.amazonaws.stepfunctions.local.model.definition.states.BranchDefinition), not marked as ignorable (3 known properties: "States", "StartAt", "Comment"])
    at [Source: (String)"{"StartAt": "Invoke-PreparePartitionsLambda", "States": {"Invoke-PreparePartitionsLambda": {"Next": "Partitions-Map", "Retry": [{"ErrorEquals": ["Lambda.ClientExecutionTimeoutException", "Lambda.ServiceException", "Lambda.AWSLambdaException", "Lambda.SdkClientException"], "IntervalSeconds": 2, "MaxAttempts": 6, "BackoffRate": 2}], "Type": "Task", "ResultSelector": {"partitioned.$": "$.Payload"}, "Resource": "arn:aws:states:::lambda:invoke", "Parameters": {"FunctionName": "ETLPreparePartiti"[truncated 1518 chars]; line: 1, column: 853] (through reference chain: com.amazonaws.stepfunctions.local.model.definition.WorkflowDefinition["States"]->java.util.LinkedHashMap["Partitions-Map"]->com.amazonaws.stepfunctions.local.model.definition.states.MapStateDefinition["ItemProcessor"]->com.amazonaws.stepfunctions.local.model.definition.states.BranchDefinition["ProcessorConfig"])"
```

OK, so it's in my Map state, which necessarily has an ItemProcessor, and the serializer code in the tool is not expecting to see a ProcessorConfig key in the ItemProcessor

Looking at the decompiled sources I can see that `com.amazonaws.stepfunctions.local.model.definition.states.MapStateDefinition` defines `ItemProcessor` as a `BranchDefinition` which is a non-specific type that lacks implementation for the `ProcessorConfig` field which is [documented here](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-asl-use-map-state-inline.html#map-state-inline-additional-fields)

When I define the state via CDK the `ProcessorConfig` field is always generated, it's not something I can omit myself

At the moment it looks like I have to do some post-processing of the ASL definition generated by CDK to filter out the unsupported field before forwarding it to the mock server for creation

Apologies for the off-topic issue, just trying to find any way of getting in touch with the devs of this otherwise super useful tool! Even if there's license issues or something that prevent it being published to GitHub it'd be great if some kind of issue tracker could be provided.

**Comment by anentropic** [comment]
So, I thought I could make a 

> At the moment it looks like I have to do some post-processing of the ASL definition generated by CDK to filter out the unsupported field before forwarding it to the mock server for creation

And... this doesn't work:
```
ℹ 2024-03-18 09:43:10.223691+00:00 | infra.utils.stepfunctions_local_client stepfunctions_local_workaround
╰─ Map.ItemProcessor has no ProcessorConfig
ERROR

E           botocore.errorfactory.InvalidDefinition: An error occurred (InvalidDefinition) when calling the CreateStateMachine operation: Invalid State Machine Definition: ''SCHEMA_VALIDATION_FAILED: Value cannot be null at /''

.venv/lib/python3.11/site-packages/botocore/client.py:1009: InvalidDefinition
```

So `ProcessorConfig` is both required and unsupported, an impossible combination ☹️

**Comment by mildaniel** [comment]
Hi @anentropic, thanks for reporting. Unfortunately, this seems like this isn't related to the AWS SAM CLI and there isn't much we can do here. I recommend reaching out to [AWS support](https://aws.amazon.com/contact-us/) for any non-open source issues you may have.

**Comment by hnnasit** [comment]
Closing as this has been inactive for a while and it does not seem to be related to SAM CLI. Feel free to open a new issue if you have any questions/concerns.
