### ISSUE TITLE
No way to set a requestContext.authorizer when running locally

### ISSUE THREAD

**Issue by psxpaul** [aws/aws-sam-cli#685]
**Description:**
I am developing a lambda function behind an ApiGateway that is authenticated with Cognito. I need to read the `event.requestContext.authorizer` property to get the cognito user's unique id. As far as I can tell, there is no way to set this property when running `sam local start-api`.

**Steps to reproduce the issue:**
1. `sam local start-api`

**Observed result:**
`event.requestContext.authorizer` is undefined

**Expected result:**
There should be a way of passing a value to `event.requestContext.authorizer` when running locally. Maybe requests with a `x-apigateway-event` header could be passed through?

**Comment by jayco** [comment]
Any news on this or a possible work around?

**Comment by joeythomaschaske** [comment]
@jayco check this out. I commented on a related issue with a work around

https://github.com/awslabs/aws-sam-cli/issues/137#issuecomment-466794575

**Comment by ssenchenko** [comment]
Closing as inactive
