### ISSUE TITLE
`tags` in samconfig.toml show error with JSON schema store (samcli.json)

### ISSUE THREAD

**Issue by mirumirumi** [aws/aws-sam-cli#6851]
Hi!

I use "Even Better TOML" vscode extension, and my samconfig.toml recieves an error like this:
![image](https://github.com/tamasfe/taplo/assets/88871226/ed384945-b7ba-4c1a-b85e-749b5e90b0ad)

The AWS documentation says this is the correct way to write it:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html

 The schema is set correctly:
![image](https://github.com/tamasfe/taplo/assets/88871226/f987a143-ce73-4a40-b5ab-bd4cf15f91be)

Any ideas?

**Comment by mildaniel** [comment]
Thanks @mirumirumi. Seems like this field can be a string or array which we need to handle in our schema generation. I will mark this down as a bug and we will prioritize a fix.

**Comment by mirumirumi** [comment]
👍
