### ISSUE TITLE
Feature request: Enable deployment of two different environments

### ISSUE THREAD

**Issue by FabricioPatrocinio** [aws/aws-sam-cli#6887]
### Describe your idea/feature/enhancement
I have a lambda project in PRD and I would like to be able to deploy the same project in a DEV environment, so I can use the entire AWS infrastructure in the same way as the PRD environment.

### Proposal
Allows you to deploy two or more different environments, such as: MyProjectLambdaPrd and MyProjectLambdaDev and so on...

Things to consider:
The idea is that this can be done in a practical and simple way. Because today there is no easy way to do this other than using ssh scripts, and I think this type of feature would make the use of sam more common

### Additional Details
We could have something like this:
```sam deploy --enviroment prd```
```sam deploy --enviroment dev```

**Comment by hawflau** [comment]
Hey @FabricioPatrocinio thanks for raising the issue. It seems to me that what you suggested is already supported by use of "samconfig". Please read https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html for more info. 

Closing the issue. Feel free to reopen or open a new issue if you have more qeustion
