### ISSUE TITLE
Bug: `sam local start-api --add-host` does not work

### ISSUE THREAD

**Issue by gkuga** [aws/aws-sam-cli#6888]
### Description:

I executed `sam local start-api --add-host="host.docker.internal:host-gateway"`, but it didn't reflect in the hosts file.

### Steps to reproduce:

Execute `sam local start-api --add-host="xxx"` command.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 22.04.3 LTS (5.15.146.1-microsoft-standard-WSL2)
2. `sam --version`:  SAM CLI, version 1.113.0
3. AWS region:

```
# Paste the output of `sam --info` here
$ sam --info
{
  "version": "1.113.0",
  "system": {
    "python": "3.11.3",
    "os": "Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.7",
    "aws_cdk": "Not available",
    "terraform": "1.6.5"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

`Add --debug flag to command you are running`

**Comment by hawflau** [comment]
@gkuga Thanks for raising the issue and PR! We will try to repro the issue and review the PR.

**Comment by lucashuy** [comment]
Issue will be closed automatically via the tag once the fix has been released
