### ISSUE TITLE
Token Authorizer doesn't get linked if FunctionPayloadType missing in template.yml 

### ISSUE THREAD

**Issue by Tolsto** [aws/aws-sam-cli#6910]
There is an issue where Token Authorizers are not being linked correctly if the FunctionPayloadType is missing in the template.yml file. This is due to the default value for `authorizer_type` being initialized as `token`, but then compared against `TOKEN` in a case-sensitive manner.

https://github.com/aws/aws-sam-cli/blob/c3e154763d758e17ffa86eb7d05ddcc9b27a095e/samcli/lib/providers/sam_api_provider.py#L321-L324

**Comment by lucashuy** [comment]
Thanks for reporting this, we'll prioritize a fix for this within the team's capacity.

**Comment by lucashuy** [comment]
This fix has been released as part of the [SAM CLI 1.119.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.119.0) release. Closing issue.
