### ISSUE TITLE
Permission denied: '/tmp/samcli/source/gradlew' when building aws-sam-cli-build-image-java11

### ISSUE THREAD

**Issue by JozefKsl** [aws/aws-sam-cli#6934]
### Description:
My build is failing when running the below build command, the error says: Permission denied: '/tmp/samcli/source/gradlew'

```
sam build --use-container \
     --build-image MyFunction=amazon/aws-sam-cli-build-image-java11
```

### Steps to reproduce:
1. Create a simple lambda function in java.
2. Try to build the function using this image https://hub.docker.com/r/amazon/aws-sam-cli-build-image-java11 using the command above.

### Observed result:
Build fails with this error `Error: [Errno 13] Permission denied: '/tmp/samcli/source/gradlew'`

### Expected result:
Successful build.

### Additional environment details (Ex: Windows, Mac)

1. OS: macOS Sonoma 14.4.1
2. `sam --version`: SAM CLI, version 1.114.0
3. AWS region: us-east-1

```
{
  "version": "1.114.0",
  "system": {
    "python": "3.12.2",
    "os": "macOS-14.4.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "25.0.3",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

`Add --debug flag to command you are running`

**Comment by jysheng123** [comment]
Hi, thanks for bringing up the issue. I was not able to reproduce the error using a simple Java project creating using `sam init`, would it be possible for you to provide a sample project you are failing on so I can accurately reproduce and debug the issue?

**Comment by JozefKsl** [comment]
@jysheng123 You're right it works fine with other project,
