### ISSUE TITLE
Bug: sam local start-api - ReadTimeout

### ISSUE THREAD

**Issue by yogzathoth** [aws/aws-sam-cli#7084]
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by lucashuy** [comment]
Thanks for visiting our repo, to help us diagnose your problem, please fill out the issue template. If the issue is closed due to the lack of information, please open a new issue with the filled template.

**Comment by lucashuy** [comment]
Closed, please create a new issue with a filled out template.
