### ISSUE TITLE
Bug: Error: The runtime 'provided.al2023' is unsupported. (golang)

### ISSUE THREAD

**Issue by aallbrig** [aws/aws-sam-cli#7139]
### Description:

I'm seeing "Error: The runtime 'provided.al2023' is unsupported." when trying to run my golang lambda function in Intellij IDEA.

<img width="652" alt="Screenshot 2024-06-06 at 9 34 57 AM" src="https://github.com/aws/aws-sam-cli/assets/3106250/3755e4ba-fcf7-41e0-afe4-acb6978543d4">

I made sure I have the latest AWS toolkit plugin and am on the latest version of SAM.
<img width="760" alt="Screenshot 2024-06-06 at 9 33 21 AM" src="https://github.com/aws/aws-sam-cli/assets/3106250/87e67b74-60fe-4dd6-bc5a-2efcf3d72915">
<img width="530" alt="Screenshot 2024-06-06 at 9 31 39 AM" src="https://github.com/aws/aws-sam-cli/assets/3106250/6c4929cc-635f-4856-87d4-028412fa7440">

Just trying to get debug breakpoints hitting from my lambda function on my M2 macbook pro. I realize being on ARM may be why I was having previous issues: https://github.com/aws/aws-sam-cli/issues/5412

### Steps to reproduce:

<img width="781" alt="Screenshot 2024-06-06 at 9 30 51 AM" src="https://github.com/aws/aws-sam-cli/assets/3106250/b014884c-9490-4741-bd3b-a4f8fd207668">
Followed from https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/

### Observed result:

<img width="652" alt="Screenshot 2024-06-06 at 9 34 57 AM" src="https://github.com/aws/aws-sam-cli/assets/3106250/3755e4ba-fcf7-41e0-afe4-acb6978543d4">

### Expected result:

Able to debug my golang based lambda function via jetbrains IDEA on my M2 macbook pro

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
```
{
  "version": "1.118.0",
  "system": {
    "python": "3.8.13",
    "os": "macOS-13.6-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "26.1.1",
    "aws_cdk": "Not available",
    "terraform": "1.5.7"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}

```

**Comment by aallbrig** [comment]
Would _love_ some detailed instructions on getting breakpoints breaking when running golang based lambda functions on M2 macbook. For now, I've downgraded back to intel based MBP 2020 so I can have the pain free debugging experience using go.1 runtime but seems like I'll have to migrate to provided.al or provided.al2023 anyways. I'd love to get back to my M2 MBP if possible.

Has anyone been able to get their golang based lambda functions working locally with breakpoints on an ARM based laptop?

**Comment by hnnasit** [comment]
Hi @aallbrig, `provided.al2023` runtime for golang is support by SAM CLI. We also have [init templates](https://github.com/aws/aws-sam-cli-app-templates/blob/master/al2023/go/hello/%7B%7Bcookiecutter.project_name%7D%7D/template.yaml) for this runtime. The issue seems to be originating from the intellij toolkit side. I am not able to transfer the issue, but could you close this issue and open the issue on the [aws jetbrains toolkits repository](https://github.com/aws/aws-toolkit-jetbrains/issues)?

**Comment by aallbrig** [comment]
Sure!

**Comment by aallbrig** [comment]
Done: https://github.com/aws/aws-toolkit-jetbrains/issues/4567

**Comment by hnnasit** [comment]
Thank you, closing this issue. Please open a new issue if you have questions or concerns the team can help with.
