### ISSUE TITLE
Bug: AWS::Events::Rule EventBusName -> 'name' member must satisfy regular expression pattern [\.\-_A-Za-z0-9]+

### ISSUE THREAD

**Issue by JandaTheMan** [aws/aws-sam-cli#7155]
### Description:

When deploying a stack with sam deploy command, all of a sudden a error appears with the following message:
'name' member must satisfy regular expression pattern [\.\-_A-Za-z0-9]+

The EventBusName specified is the default event bus name that was created with Partner event sources for a EventBridge with salesforce partner.

The deploy was working, this behaviour was noticed today.

Additional info: 
The allowed EventBusName pattern from the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-eventpattern): `[/\.\-_A-Za-z0-9]+`
Differs from the one output in the error:                                 `[\.\-_A-Za-z0-9]+`

**Comment by hnnasit** [comment]
Hi @JandaTheMan, thanks for reporting the issue. Could you provide a reproducible CFN template that we can use to investigate further? Was this working before and you are noticing the error recently?

**Comment by JandaTheMan** [comment]
It seems like the issue was fixed by cloudformation team automatically since the issue disappeared by its own again.

**Comment by hnnasit** [comment]
Thanks for confirming that. I'm closing this issue in that case. Feel free to open a new issue if you have questions or concerns.
