### ISSUE TITLE
Api Gateway requests with query string always response 400

### ISSUE THREAD

**Issue by namsic6460** [aws/aws-sam-cli#7170]
Hello, I am configuring a Lambda through SAM and connecting it to API Gateway and Route 53 to create API. After deploying to AWS and conducting tests, I connected the domain and certificate to Route 53.

When defining the API in SAM, I explicitly included the query string, and it appears correctly in AWS as well. However, when I call the API with the query string included, the request does not reach the Lambda and I receive a 400 response. If I remove all query strings and try again, the request reaches the Lambda, and I can see the logs in CloudWatch. API Gateway also has a feature to log to CloudWatch, and I have configured this as well. However, when the query string is present, no logs are recorded.

I am unsure what the issue might be. I would appreciate any help you can provide. Thank you.
<img width="340" alt="image" src="https://github.com/aws/aws-sam-cli/assets/52943870/ae66682a-3556-4560-910c-bffd98853cf4">
![image](https://github.com/aws/aws-sam-cli/assets/52943870/684d73eb-6723-4ae2-a8f2-2efbdf028a52)
<img width="496" alt="image" src="https://github.com/aws/aws-sam-cli/assets/52943870/fa35bd6a-377b-4e93-b25a-7109443cb89e">

**Comment by namsic6460** [comment]
I am concerned that too much of the image might be obscured, but I have hidden it just in case. If you need any additional information, please let me know, and I will provide it. Thank you for your understanding.

**Comment by mndeveci** [comment]
Hi @namsic6460, thanks for creating this issue

Would you be able to provide a simple reproducible example so that we can investigate the issue on our side?
