### ISSUE TITLE
Feature request: Upgrade cfn-lint dependency

### ISSUE THREAD

**Issue by jplock** [aws/aws-sam-cli#7260]
### Describe your idea/feature/enhancement

Can the `cfn-lint` dependency be upgraded to something post 1.x? Every time I reinstall aws-sam-cli through pip, it downgrades `cfn-lint` back to 0.87.9

**Comment by jplock** [comment]
Related to https://github.com/aws/aws-sam-cli/pull/7207

**Comment by jysheng123** [comment]
Thanks for bringing this up. Our team is working on bumping up the cfn-lint version, but it has some breaking changes in the new version that we have to update our codebase for, so it make take a bit of time
