### ISSUE TITLE
Bug: sam local invoke - SSLError

### ISSUE THREAD

**Issue by manikandannp** [aws/aws-sam-cli#7304]
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by hnnasit** [comment]
Hi @manikandannp, I'm closing this issue as there is not enough information to investigate. Please open a new issue with more details following the template questions and steps to reproduce the behavior.
