### ISSUE TITLE
Thumbprint of the AWS SAM Windows MSI installer does not match the documentation

### ISSUE THREAD

**Issue by lachriz-aws** [aws/aws-sam-cli#7372]
### Description:

The thumbprint of the `AWS_SAM_CLI_64_PY3.msi` file does not match the documentation.

The file has been downloaded from here: https://github.com/aws/aws-sam-cli/releases/latest/download/AWS_SAM_CLI_64_PY3.msi

What I get: `d52eb68bffe6ae165b3b05c3e1f9cc66da7eeac0`
What the docs state: `c011d416e99a1142c0e0235118ef64c2681f3db9`

![image](https://github.com/user-attachments/assets/a9efab6d-5910-4e52-8ec1-3edc7d4fbe98)

It looks like a new certificate was taken into use recently to sign the installer (valid from August 2nd 2024), so I assume that the docs is simply lacking behind on that?

![image](https://github.com/user-attachments/assets/e304d29c-5d50-4d61-bfc4-291052ec1786)

### Steps to reproduce:

Follows the steps for Windows, as outlined in the documentation, here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/reference-sam-cli-install-verify.html

### Observed result:

Thumbprint of installer is not matching the docs.

### Expected result:

Thumbprint in the docs should match the thumbprint of the installer.

**Comment by hawflau** [comment]
@lachriz-aws thanks for raising the issue. We will investigate.

**Comment by hnnasit** [comment]
Closing as the [docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/reference-sam-cli-install-verify.html) have been updated to reflect the correct thumbprint. Thanks for reporting the issue.

**Comment by Daniel-Axr** [comment]
Hi. 
### Description:
Same issue as above. The thumbprint of the AWS_SAM_CLI_64_PY3.msi file does not match the documentation.
Downloaded the latest .msi installer from https://github.com/aws/aws-sam-cli/releases/latest/download/AWS_SAM_CLI_64_PY3.msi

What I get: `6c4ef05967db0a2c69871731ec9e515d7cd6e952`
What the Doc state: `cd62479397f09d72a04c7399a254b0a91da53d6c`

### Screenshots:
<img width="828" height="505" alt="Image" src="https://github.com/user-attachments/assets/5e89bce3-e472-4beb-954c-43fe11551371" />

<img width="376" height="508" alt="Image" src="https://github.com/user-attachments/assets/4894ff7b-b0e5-4905-bd09-38c12f6e5c37" />

### Steps to reproduce: 
Follow the instructions from the [document](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/reference-sam-cli-install-verify.html#reference-sam-cli-install-verify-signature). 

1. Right-click on the installer and open the Properties window.

2. Choose the Digital Signatures tab.

3. From the Signature List, choose Amazon Web Services, Inc., and then choose Details.

4. Choose the General tab, if not already selected, and then choose View Certificate.

5. Choose the Details tab, and then choose All in the Show dropdown list, if not already selected.

6. Scroll down until you see the Thumbprint field and then choose Thumbprint. This displays the entire thumbprint value in the lower window.

### Observed result:

Thumbprint of installer is not matching the docs.

### Expected result:
Thumbprint in the docs should match the thumbprint of the installer.
