### ISSUE TITLE
Feature request: Add `dotnet` BuildMethod in addition to `dotnet7`

### ISSUE THREAD

**Issue by Beau-Gosse-dev** [aws/aws-sam-cli#7463]
### Describe your idea/feature/enhancement

There is a custom build method called donet7 shown here: https://github.com/aws/aws-sam-cli/blob/9f956dfa7760c50b86f79c1d86bef5a1b61e9e6f/samcli/lib/build/workflow_config.py#L150

This command isn't really specific to version 7 of .NET since it just calls into the underlying Lambda Builder for dotnet in general and the AWS extensions for the .NET CLI figures out what version of .NET it's building. 

### Proposal

`dotnet7` could be replaced with `dotnet` to allow future custom runtime/provided runtime builds for .NET 9 and other non-Lambda supported .NET runtimes. However, to keep backwards compatibility, we could instead just add `dotnet` as a build method in addition to `dotnet7`

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model) - No it should not
2. Will this require updates to the docs? - I'm not sure, but I can't seem to find `dotnet7` mentioned in the docs

### Additional Details

Here is the CR for when dotnet7 was added: https://github.com/aws/aws-sam-cli/pull/4410/files

**Comment by Beau-Gosse-dev** [comment]
I can try to find time to implement this if you think it makes sense and don't see any potential problems with it.

**Comment by hnnasit** [comment]
Thanks @Beau-Gosse-dev for the feature request. Let me check with the team and get back to you.

**Comment by hnnasit** [comment]
Hello @Beau-Gosse-dev, I checked with the team and they seem fine with the idea. Feel free to work on the feature request.

**Comment by hnnasit** [comment]
Closing as the change was release as part of [SAM CLI version 1.127.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.127.0). Thanks for your contributions!
