### ISSUE TITLE
Bug: boto3 causes SyntaxError when building/invoking with python3.11

### ISSUE THREAD

**Issue by Gmfholley** [aws/aws-sam-cli#7526]
### Description:
Demonstrated with Hello World python3.11 template.

If you use `sam init` and choose the python 3.11 'Hello, World' template

1. `sam build --use container` fails with a `source code string cannot contain null bytes` error.  This happens with no changes to Hello World.
2.  `sam build` and `local invoke -e events/event.json` succeeds.
3.   `import boto3` and `sam build` and `local invoke` will now fail with the same syntax error.

python3.12 or python3.10 builds succeed in all three scenarios.

### Steps to reproduce:

1. sam init
4. Choose Hello World Template
5. Use python3.11 runtime
6. cd into new directory
7. Run `sam build --use-container` (fails on build step)
OR
8. Add 'import boto3' to the `hello_world/app.py` file.
9. Run `sam build`
10. Run `sam local invoke -e events/event.json` (fails on invoke step).

### Observed result:
* For `sam build --use-container --debug`
[output](https://gist.github.com/Gmfholley/9cedb7d1cb692d5094b28066848a55be)

* For `sam local invoke -e events/event.json --debug`
[output](https://gist.github.com/Gmfholley/6b6ee6913010162fb501e862189907e4)

### Expected result:
Expected it to build and return what Hello World is supposed to return, what it returns for python3.10 and python3.12.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
11. `sam --version`:

{
  "version": "1.123.0",
  "system": {
    "python": "3.8.13",
    "os": "macOS-14.6.1-x86_64-i386-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.8",
    "aws_cdk": "Not available",
    "terraform": "1.5.7"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
12. AWS region: us-east-1

**Comment by hawflau** [comment]
Hi @Gmfholley thanks for raising the issue. I tried your steps to reproduce but it worked fine on my Mac. Can you share the requirements.txt for us to investigate? Thanks!

**Comment by Gmfholley** [comment]
@hawflau  Did either of them reproduce, or just not the second one?  I did fail to add that for the second, I imported boto3.

So for exhaustiveness, the `requirements.txt` for 'Hello World' that failed on the 'build' step was:

```
requests
```

and for importing boto3 was:

```
requests
boto3
```

**Comment by Gmfholley** [comment]
I tested again, and was again able to reproduce the issue.  But since you weren't, I decided to completely delete all Docker volumes and data, and that fixed it.  Something must have been broken in my container.

I'm sorry for the bug report.  Hopefully this can help someone else.
