### ISSUE TITLE
Feature request: Add AWS_LAMBDA_INITIALIZATION_TYPE environment variable

### ISSUE THREAD

**Issue by leandrodamascena** [aws/aws-sam-cli#7532]
### Describe your idea/feature/enhancement

According to the [official AWS documentation](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html) there is a environment variable named `AWS_LAMBDA_INITIALIZATION_TYPE` that can contains following values: `on-demand`, `provisioned-concurrency`, or `snap-start`. Since SAM is intended to emulate Lambda in local environment, so, its good if SAM can include this env var with the value `on-demand`, for example. 

### Proposal

Add this environment variable.

**Comment by hawflau** [comment]
@leandrodamascena Thanks for raising the issue and the PR. I'll take a look into the PR!
