### ISSUE TITLE
Bug: sam deploy - DockerException

### ISSUE THREAD

**Issue by aryatomar19** [aws/aws-sam-cli#7610]
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by hnnasit** [comment]
Closing the issue as there's not enough information provided for the team to triage the issue. Please open a new issue with more details if you are still running into issues or have questions.
