### ISSUE TITLE
Bug: unknown resource type: AWS::CloudFormation::LambdaHook

### ISSUE THREAD

**Issue by jftjamf** [aws/aws-sam-cli#7729]
### Description:
`sam` does not know about the `AWS::CloudFormation::LambdaHook` resource type.  Can you please update the program to include this resource type?

### Steps to reproduce:
```shell
$ sam validate --lint -t template.yaml

[[E3006: Validate the CloudFormation resource type] (Resource type 'AWS::CloudFormation::LambdaHook' does not exist in 'us-east-1') matched 385]
Error: Linting failed. At least one linting rule was matched to the provided template.
```

However, `sam deploy` will successfully deploy this resource type.

### Expected result:
I expect `sam` to know about this resource type and return an exit value of `0`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: `MacOS 15.1.1`
2. `sam --version`: `SAM CLI, version 1.130.0`
3. AWS region: `us-east-1`

```jeon
{
  "version": "1.130.0",
  "system": {
    "python": "3.8.20",
    "os": "macOS-15.1.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "2.99.0 (build 0aa1096)",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}

```

**Comment by lucashuy** [comment]
Hey, thanks for raising this issue. We've updated `cfn-lint` to a newer version (in #7706), however this has not made it out to a release yet.

Please stay tuned for a new version of SAM CLI, in the mean time you can consider using `cfn-lint` manually (https://github.com/aws-cloudformation/cfn-lint), or you can omit `--lint` to just check if the template is syntactically correct.
