### ISSUE TITLE
Bug: AutoPublishAlias won't create new versions if only layer arn is modified.

### ISSUE THREAD

**Issue by DiscreteTom** [aws/aws-sam-cli#7775]
### Description:

AutoPublishAlias won't create new versions if only layer arn is modified in function's properties.

This will also affect SnapStart since new versions can't be created, users must create the version and modify alias manually.

### Steps to reproduce:

1. Deploy an official hello world example (e.g. python3.9 in my case) with AutoPublishAlias enabled. The first deployment will create version 1 for the function.
2. Modify the function's property in template.yaml, add a layer with an ARN. E.g. with lambda web adapter's `arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerX86:23`
3. `sam build` then `sam deploy`. The function is updated but no new versions created.
4. Modify the layer's arn, e.g. use an old lambda web adapter layer arn: `arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerX86:22`.
5. `sam build` then `sam deploy`. The function is updated but no new versions created.

### Observed result:

Add/Modify a layer arn won't create new function versions.

### Expected result:

Add/Modify a layer arn should create new function versions.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```
{
  "version": "1.119.0",
  "system": {
    "python": "3.11.8",
    "os": "Linux-6.1.111-120.187.amzn2023.x86_64-x86_64-with-glibc2.34"
  },
  "additional_dependencies": {
    "docker_engine": "25.0.6",
    "aws_cdk": "2.131.0 (build 92b912d)",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

`Add --debug flag to command you are running`

**Comment by mbfreder** [comment]
Thanks for opening this @DiscreteTom . Setting [`AutoPublishAliasAllProperties`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-autopublishaliasallproperties) to true creates a new [AWS::Lambda::Version](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-version.html) when any property in the Lambda function is modified. Please try this and let me know if it works.

**Comment by vicheey** [comment]
The way SAM know to publish a new version or not is by check the hash of a function. With `AutoPublishAlias`, only a handful of default properties are used fro the hashing. Layer is not one of this default properties. To solve your current issue, the`AutoPublishAliasAllProperties` should be used to tell SAM to consider Layer and additional properties when creating a hash.

**Comment by DiscreteTom** [comment]
Thanks for the response. [`AutoPublishAliasAllProperties`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-autopublishaliasallproperties) works like a charm.
