### ISSUE TITLE
Add pipenv support for build command

### ISSUE THREAD

**Issue by sthulb** [aws/aws-sam-cli#817]
It would be cool if SAM CLI could understand Python projects that use pipenv. Right now, `sam build` only supports dependencies that are specified in a `requirements.txt`.

---
SAM Version: 0.8.0

**Comment by TheSriram** [comment]
This could be a new workflow in https://github.com/awslabs/aws-lambda-builders. The current worflow is a python_pip workflow. this could be a python_pipenv workflow.

**Comment by sthulb** [comment]
I’ll see if I have capacity to do this next week.

**Comment by jblakeney** [comment]
:+1:

**Comment by jrupp** [comment]
Any movement on this?

**Comment by solarmosaic-kflorence** [comment]
FWIW using `pipenv` with `PackageType: Image` works fine (you can utilize it in your `Dockerfile`). I seem to be having some issues getting that to work with `sam local invoke`, though (can't seem to find the dependencies even though they exist in my image).

**Comment by sriram-mv** [comment]
I'm going to go ahead and close this in favor of using a `makefile` based builder if one wants additional flexibility.

**Comment by matteocontrini** [comment]
@sriram-mv is there a chance to have this mentioned in the documentation, perhaps with an example?
