### ISSUE TITLE
sam local RequestParameter is null

### ISSUE THREAD

**Issue by kappaj2** [aws/aws-sam-cli#868]
Running sam local with a Java8 Spring Lambda.
Laptop is Macbook Pro:
SAM CLI version 0.9.0

Have a simple rest controller that accepts RequestParameters. When deployed onto AWS then the parameters are populated.
Running with $ sam local start-api 
All the parameters as null

The controllers are simply returning an "Ok" at the moment with no other code in the controller body.
Tried running sam local with -d , attached IntelliJ and debugged. All three variables are null.

Have similar issues with a POST command. Also not populating the POJO.

Any help appreciated.

**Comment by jfuss** [comment]
@kappaj2 I am assuming you are trying to use this feature within API Gateway: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration-requestParameters.html?

If so, this is currently not supported by the local implementation.

**Comment by mingkun2020** [comment]
@kappaj2 Closing this issue since inactive for a long time. If you encounter this issue anymore, feel free to reopen it.
