### ISSUE TITLE
Extract generated_sample_events into separate python library

### ISSUE THREAD

**Issue by billyshambrook** [aws/aws-sam-cli#910]
### Describe your idea/feature/enhancement

When writing unit and integration tests against lambda functions, it's common to need some sample events. sam-cli has a package that has great sample events generation used by the cli, and would be great if this could be used as part of a sam application test library.

Here is a example of how we use the current package in our tests using py.test...

```python
import json

import pytest
import samcli.commands.local.lib.generated_sample_events.events as sam_events


@pytest.fixture(scope='module')
def sam_event():
    events = sam_events.Events()
    def generate(service_name, event_type, values_to_sub=None):
        return json.loads(events.generate_event(service_name, event_type, values_to_sub))
    return generate
```

Two issues that we see with doing this...

1. You need to install the whole aws-sam-cli library just to use this package.
2. The package API could change as it's a "unsupported" use of the code.

### Proposal

Would be great to extract this functionaility into a standalone library that is available via PyPi with a clear public interface.

**Comment by ssenchenko** [comment]
Closing as inactive
