### ISSUE TITLE
Debug config settings don't work for multiple Lambdas

### ISSUE THREAD

**Issue by mcshaman** [aws/aws-sam-cli#927]
### Description

No documentation to configure VS Code to debug `sam local start-lambda` for projects with multiple lambdas. Flowing the configuration for debugging `sam local invoke` causes throw errors because it can't the local files based on a single local root.

### Steps to reproduce

I have a folder structure similar to this:

```
| MyApp/
| - .vscode/
  | - launch.json
| - node_modules/
| - src/
  | - Lambda1/
    | - index.js
    | - package.json
  | - Lambda2/
    | - index.js
    | - package.json
| - package.json
| - template.yml
```
I followed the configuration for `sam local invoke` found here [https://github.com/awslabs/aws-sam-cli/blob/develop/docs/usage.md](url).

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Attach to SAM CLI",
			"type": "node",
			"request": "attach",
			"address": "localhost",
			"port": 5858,
			"localRoot": "${workspaceRoot}",
			"remoteRoot": "/var/task",
			"protocol": "inspector",
			"stopOnEntry": false
		}
	]
}
```
and ran command `sam local start-lambda --debug-port 5858` then ran another script that called one of the lambdas through the SDK.

### Observed result

VS Code through error messages at me saying it couldn't find `index.js` in `MyApp/`.

### Expected result

Obviously this is because the documented configuration is for testing a single Lambda. How do you configure the development environment to test multiple Lambdas in seperate directories?

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`: SAM CLI, version 0.10.0

`Add --debug flag to command you are running`

**Comment by brandond** [comment]
Also watching. I have an in-house built process that collects and builds a number of APIs and Lambda functions into a single template; as noted above there does not appear to be a way to test this using 'sam local' since it seems to assume a single API or Function per template.

**Comment by mcshaman** [comment]
The user experience might be able to be improved using the new [custom command and user input variables](https://code.visualstudio.com/updates/v1_31#_custom-command-user-input-variables) introduced by VS code. I don't have time to try this yet but you may be able to configure the launch.json to prompt the user to choose a lambda to test... To what extent this can be done dynamically I don't know but it is something I plan on trying.

**Comment by chrismowbray** [comment]
Im surprised this hasn't got more traction. I'm having the same issue. Only way for me to test is too append the path of the lambda im testing to `localRoot` e.g `"localRoot": "${workspaceRoot}/lambdas/LambdaOne",`

**Comment by abecks** [comment]
Just ran into this issue. Would be nice to have a fix for this. Currently have to setup a launch configuration for each lambda function in my API.

I am using `sam local start-api` with multiple lambda functions configured. Because `localRoot` must be set to a specific lambda, I must setup individual configuration for each one:

```
    {
      "name": "Renderer Attach",
      "type": "node",
      "request": "attach",
      "address": "localhost",
      "port": 9999,
      "localRoot": "${workspaceRoot}/built/renderer",
      "remoteRoot": "/var/task",
      "protocol": "legacy",
      "stopOnEntry": false,
      "sourceMaps": true,
      "skipFiles": [
        "/var/runtime/node_modules/**/*.js",
        "<node_internals>/**/*.js"
      ]
    },
    {
      "name": "Form Handler Attach",
      "type": "node",
      "request": "attach",
      "address": "localhost",
      "port": 9999,
      "localRoot": "${workspaceRoot}/built/form-handler",
      "remoteRoot": "/var/task",
      "protocol": "legacy",
      "stopOnEntry": false,
      "sourceMaps": true,
      "skipFiles": [
        "/var/runtime/node_modules/**/*.js",
        "<node_internals>/**/*.js"
      ]
    }
```

**Comment by ssenchenko** [comment]
[AWS Toolkit provides tooling to integrate with IDEs](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/serverless-apps.html).

 [SAM documentation for debugging](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-debugging.html) is pointing to the toolkit page now
