### ISSUE TITLE
Provide a way to pre-fetch images

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-sam-cli#931]
Due to the limits imposed by the IDEs debuggers, we need a way to pre-download images so that it does not happen when trying to debug.

**Comment by mingkun2020** [comment]
Thanks for the feature request! We have a [roadmap](https://github.com/aws/aws-sam-cli/wiki/SAM-CLI-Roadmap) here, but we also try to take in popular feature requests based on 👍🏽 from the community. We will be adding this to our intake for prioritization.

**Comment by jfuss** [comment]
Closing due inactivity. Please create a new issue if you would still like this feature.
