### ISSUE TITLE
After I deploy Lambda Function Resource of Go1.x with SAM and Windows 10 onto AWS, it occurs an error.

### ISSUE THREAD

**Issue by MenEnger** [aws/aws-sam-cli#954]
### Description

I cannot run a lambda function of Go1.x on AWS console.

### Steps to reproduce

Prepare Windows10 Pro.
Setup  Python3.7, AWS-CLI, AWS-SAM-CLI, Go1.11.4.
Configure AWS API key etc....
Do "sam init -r go"
Create S3 bucket to store package on AWS.
Build an executable file with "GOOS=linux" .
Do "sam package" and "sam deploy" commands.
Test the function on AWS Lambda console with "hello-world"-based event.

### Observed result
```
{
  "errorMessage": "fork/exec /var/task/hello-world: permission denied",
  "errorType": "PathError"
}
```

### Expected result

Show IP adress of "https://checkip.amazonaws.com"

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:Windows 10 Pro
2. `sam --version`:0.9.0

`Add --debug flag to command you are running`

### Cause to guess
I suspect that SAM-CLI does not use "aws-lambda-go/cmd/build-lambda-zip" when zipping executables of Golang.
Zip in Python module doesn't change the attribute like `chmod 777`, does it?

**Comment by jfuss** [comment]
SAM CLI does not use that go package and shouldn't for zipping. Instead we should be updating the external_attr attribute on the zipfile.ZipInfo before zipping.

**Comment by spaceraccoon** [comment]
@jfuss Are there plans to merge the fix for `external_attr`? `sam build` on the default `hello-world` for `go` still creates a lambda function with the error:

```
{
  "errorMessage": "fork/exec /var/task/hello-world: permission denied",
  "errorType": "PathError"
}
```

Thanks!

**Comment by jfuss** [comment]
@spaceraccoon There currently isn't a PR for this and not aware of anyone directly working on it at the moment. It's something we should defiantly fix. Are you willing to try and implement it?

**Comment by spaceraccoon** [comment]
Started a PR at #1986.
