### ISSUE TITLE
Locally debugging API Gateway (start-api  -d) can't be terminated from Eclipse

### ISSUE THREAD

**Issue by phijacobs** [aws/aws-sam-cli#998]
### Description

When locally debugging with the API Gateway (sam local start-api -d), the API Gateway process can't be stopped from the IDE. SIGTERM is caught to properly to clean up the running container, but it isn't propagated to terminate the Python process running sam local.

Once the API Gateway request completes, the SIGTERM handler is still in effect. The SIGTERM handler needs to be set back to the default handler after the API Gateway request completes. The IDE can't stop the API Gateway process after a request is completed and the debugger detaches.

### Steps to reproduce

1. Test API Gateway locally as documented at https://docs.aws.amazon.com/toolkit-for-eclipse/v1/user-guide/tke-sam-local.html
2. After debugging the request, stop the running process using the stop button, and you'll get a Terminate failed.

### Observed result

Please provide command output with `--debug` flag set.

### Expected result

Describe what you expected.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS X 10.11.6 El Capitan
2. `sam --version`: SAM CLI, version 0.11.0

`Add --debug flag to command you are running`

**Comment by morefaey** [comment]
@phijacobs can you please submit this as a PR for review?

**Comment by phijacobs** [comment]
@morefaey I rebased and will have the PR shortly. Thank you!

**Comment by phijacobs** [comment]
Hi @morefaey, I created PR #2205

**Comment by CoshUS** [comment]
Closing as stated in https://github.com/aws/aws-sam-cli/pull/2205#issuecomment-687976761
Debugger should be attached with `sam local invoke` instead of `sam local start-api`.
