### ISSUE TITLE
Dealing with upgraded protocol version on aws-lambda-builders

### ISSUE THREAD

**Issue by sriram-mv** [aws/aws-sam-cli#999]
### Describe your idea/feature/enhancement

AWS SAM CLI relies on aws-lambda-builders for supporting the `sam build` command. In particular aws-lambda-builders error codes are also dependent on using the correct RPC protocol version.  aws-lambda-builders are also packaged on to the different docker containers that are used by aws-sam-cli. There needs to be a way to operate different protocol versions of aws-lamda-builders on the container vs a different version of aws-lambda-builders being required on the aws-sam-cli project. Right now, if the protocol versions dont match, there is no further action taken but to say incompatible version. An upgrade to one, should not make aws-sam-cli unusable without having to download the latest containers.

### Proposal

Operate with semantic versioning to establish compatible versions of aws-sam-cli and aws-lambda-builders.

**Comment by TheSriram** [comment]
https://github.com/awslabs/aws-lambda-builders/pull/78 partially addressed it.

**Comment by TheSriram** [comment]
Maybe a doc which tells when the version can be bumped and not bumped would be a good starting point.

**Comment by sriram-mv** [comment]
Closing this issue as the integration into build containers now have the source code available within the repo, on what version of sam cli is used.
